endless-sky/endless-sky

- endless-sky.desktop
The Categories field is necessary at least on my distro to get the game entry in the proper menu (Games > Simulation).
GenericName is meant to be a very short description of the "type of software", like "Web browser" or "Text editor" (the tag name is poorly chosen IMO, but there is more info about its purpose here: http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys
Some desktop environments show "Comment" in the tooltip when you hover the game name, while other use "GenericName" (like KDE).
> Some desktop file improvements

- source/Format.cpp
So, how do you feel about delimiters? 
Maybe something like commas:
^ This is how it looks in version I committed.
Or spaces:
As opposed to the way it's displayed now:
I personally think it would improve readability. Especially in range of hundreds of thousands as you can see in Principal column. I know it seems trivial but I just wanted to take a quick jab at modifying something and this was easiest on my list of issues I found.
> Add comma delimiter between thousands in formated number output

- source/Mission.cpp
Everywhere <passengers> is used in the project, there is already a 'your', usually reading "You wish your your passenger..."
> 'your' before 'passengers' is removed

- EndlessSky.xcodeproj/project.pbxproj
Grouping the source files this way matches the filesystem representation, and makes it a little easier to get at items that currently sort below the source files in the navigator.
> Xcode: place source files into a group called 'source'

- source/EscortDisplay.cpp
- source/EscortDisplay.h
When some of your escorts are off screen (particularly on a small monitor) it's
hard to know when they're all ready to jump. I think this also adds a nice
feeling of waiting for your escorts to signal that they're ready.
> color escort icon green if it is ready to jump

- source/OutfitterPanel.h
- source/ShipyardPanel.h
Functions in OutfitterPanel.h and ShipyardPanel.h are intended to override the ones in ShopPanel.h according to [this comment](https://github.com/endless-sky/endless-sky/blob/master/source/ShopPanel.h#L48). Adding the 'override' specifier eliminates the (Xcode 7) warning: "... overrides a member function but is not marked 'override'"
> Fix warnings about member function overrides by adding override specifiers

- source/Engine.cpp
Selected target is colored Radar::SPECIAL on radar. This is how it worked in EV and was missing it in ES. The white dot stands out enough to be easily distinguishable, yet subtle enough to not overcast the other dots on the radar.
(https://lh3.googleusercontent.com/-S0KCQZ2zNLI/VkCXyh8d80I/AAAAAAAABlQ/kD7SOQlP2FA/s1600/Screen%2BShot%2B2015-11-09%2Bat%2B6.55.21%2BAM.png)
> Selected target is white on radar

- source/MapPanel.cpp
Change the travel plan draw color to a more orange-ish color when distance exceeds jumps remaining.
Just playing with stuff and wanted to try modifying something simple and making a PR. As a player, I sometimes need to calculate how far i get through hostile or unpopulated territory without needing to land and refuel. To do this currently, I have to check my fuel gauge and then manually count jumps on the map. With this change, I can easily tell when a travel path extends beyond the range of my current fuel. 
Update: If you have a fleet with you, you get a green line for your fleet's maximum fuel range.
> Change travel plan color when distance exceeds jumps remaining

- data/events.txt
- data/free worlds middle.txt
- data/map.txt
This may be a debatable change, as I did find (while researching just now) that 'vender' is by some sources considered an acceptable variant of 'vendor' (albeit much less-used, according e.g. to data from Google Ngram: http://i.stack.imgur.com/QaTDo.png ).
Either way, consistency in usage is generally desirable, and as the two other cases where Endless Sky currently uses the word (1 other instance in map.txt & 1 in free worlds start.txt) have the 'vendor' spelling, standardising it one way or the other seems sensible.
Edit: also includes an unrelated grammar fix for free worlds middle.txt.
> vender -> vendor spelling

- source/AI.cpp
Now when switching landing targets in a system a new message will appear, "Switching landing targets, now landing on ____." This makes it more obvious what object is being landed upon after the target has switched.
> Added additional log message when switching landing targets

- data/map.txt
- keys.txt
- source/AI.cpp
- source/Command.cpp
- source/Engine.cpp
- source/HailPanel.cpp
- source/MainPanel.cpp
- source/OutfitterPanel.cpp
- source/Planet.cpp
- source/Planet.h
- source/StellarObject.cpp
- source/StellarObject.h
- source/System.cpp
I have added a new member function to the Planet class that returns an improper noun for a given object depending on its attributes. For instance, any object with "station" amongst its attributes will be referred to as a station within the in-game dialog, rather than a "planet" as before. Additionally, I have added a "moon" attribute to all named moons within map.txt (as stations have the "station" attribute), this facilitates referring to these objects as "moon" within the in-game dialog. If "moon" or "station" are not amongst the attributes, the default "planet" is used.
For objects that cannot be landed on, I have added two new properties to the StellarObject class: IsMoon and IsStation. This enables the messages generated upon attempting to land on these objects to be more accurate …
> Objects properly referred to as station/moon/planet

- source/Files.cpp
- source/Point.cpp
Fixed a small memory leak that occurred when creating the plugins folder.
Also fixed an ambiguity in the initialisation of the 'v' attribute in the private Point constructor. I am not sure if it is a bug, but better safe than sorry.
> Small fixes

- data/interfaces.txt
- source/Font.cpp
- source/ShopPanel.cpp
I noticed that there are many hotkeys in all of the game dialogs, but there is no visual indication of the hotkeys on any of the buttons, currently the player has to find out through trial and error. To make these hotkeys much more obvious, I've added the ability to underline a character in a label by preceding the character with an underscore, e.g. "_Shipyard" would display as S&#818;hipyard. I went ahead and added underscores to all labels in the game (I believe) that have hotkeys defined.
~~For the most part it looks good, but there are some wide characters for which the underscore doesn't quite underline the whole character (capital "O", for example).~~
~~One exception was the ShopPanel, which draws the buttons differently; for this function I drew the underscores slightly …
> Added underscores beneath hotkey of most in-game buttons

- source/Files.cpp
I ran into this problem when building the program on OS X via scons (i.e. without using XCode). The first problem is that on Macs the program assumes resources are in `../Resources`, which is only true if you build a full application bundle, so I changed it to just add `../Resources` to the end of the current path, so that the current directory will still be searched if `../Resources` doesn't exist.
The other issue is that if you fail to find resources it goes into an infinite loop checking `/` over and over again; this patch fixes that as well.
Thanks for making this game!
> Improve resource search

- data/jobs.txt
… so that people who choose the Sparrow can start these types of jobs right away. The missions disappear as soon as your combat rating rises to 6, at which point the regular track of escort missions becomes visible.
> Added some baby-sized escort jobs

- source/HailPanel.cpp
Hailing a derelict ship (including the asteroid in #372) will now result in the message, "There is no response to your hail."  The "Ask for Help" button and its hotkey are also disabled in such cases.
> disable conversations with rocks (and derelict ships) to resolve #372

- data/jobs.txt
That fact that pirates never appear in these areas normally means that the Navy is probably doing a pretty job of this themselves! It's odd that huge pirate ships would be waylaying merchants near Earth…but only once the player becomes powerful enough to defeat them!
> Don't offer pirate hunting jobs near Earth

- data/map.txt
- source/Engine.cpp
- source/MapPanel.cpp
- source/MapPanel.h
- source/PlayerInfo.cpp
- source/PlayerInfo.h
Created function specifically for drawing wormholes (DrawWormholes), this way the wormholes can be guaranteed to be drawn under all other links. To appear as a wormhole link on the map, the wormhole *must* have a planet entry, I have added one for Wormhole Alpha, but not for the Pug wormhole (Although we could choose to do so).
This also adds the visitedPlanets data structure and saves/loads that information to the pilot file, as before. This could be quite useful for story-telling purposes.
This supersedes https://github.com/endless-sky/endless-sky/pull/398, which I have closed.
> Merged wormhole-links with new way of traversing wormholes that avoids links

- data/jobs.txt
Switched the garbage missions to indicate the type of garbage you'd be carrying, now that this is supported
> Make garbage missions indicate type of garbage

- data/jobs.txt
This was left over from a previous incarnation of the job where there was no NPC ship to escort.
> Removed the passenger requirement for the science vessel escort job

- source/OutfitterPanel.cpp
- source/ShopPanel.cpp
- source/ShopPanel.h
When clicking on an item located near the bottom of the screen, the user needs to scroll the window in order to see the details. This PR implements an autoscroll feature that will automatically bring the item details into view. 
A quick demo:
[![Autoscroll demo](http://img.youtube.com/vi/C0G-QprMBWs/0.jpg)](http://www.youtube.com/watch?v=C0G-QprMBWs)
> Add autoscroll to ShopPanel to bring item details into view

- source/BoardingPanel.cpp
- source/BoardingPanel.h
- source/ConversationPanel.cpp
- source/ConversationPanel.h
- source/InfoPanel.cpp
- source/InfoPanel.h
- source/LoadPanel.cpp
- source/LoadPanel.h
- source/MapPanel.cpp
- source/MapPanel.h
- source/MapSalesPanel.cpp
- source/MapSalesPanel.h
- source/MissionPanel.cpp
- source/MissionPanel.h
- source/Panel.cpp
- source/Panel.h
- source/ShopPanel.cpp
- source/ShopPanel.h
- source/UI.cpp
Fixes endless-sky/endless-sky#805
This PR changes the prototype of `Panel::Drag(int, int)` and `Panel::Scroll(int, int)` to `Drag(double, double)` and `Scroll(double, double)`. `Scroll` did not absolutely need to be changed since it's mostly used to scroll Panels in large increments from keyboard shortcuts, but I did change it for the sake of consistency.
Other methods like Click() do not need a change since the click coordinates are always compared to integer coordinates. The only exception is InfoPanel::Hover() which required special treatment.
All Panels that handle scrolling have seen their various scrolling related attributes changed from int to double.
I have not been able to test proper dragging/scrolling for the following panels:
- BoardingPanel
- ConversationPanel
- LoadPanel
- …
> Changed Panel::Drag and Panel::Scroll to take double dx/dy

- source/InfoPanel.cpp
Info panel crashes when no ships on new or just loaded game. Start new game but don't buy a ship and leave shipyard. Press Shift-I, switch to Ships tab. Move mouse over panel as bug in Hover() method. 
Tested on Windows and Linux.
> Fixed segfaults on end() iterator dereference

- source/MissionPanel.cpp
- source/MissionPanel.h
See #846
1. When switching from the map view to the missions panel (that's the biggest source of confusion), auto-select the first available or accepted mission in:
- the selected system
- the player's current position
- along the travel plan (going out)
If no mission was found, display the missions panel with NO mission selected.
2. When switching from the planet view to the missions panel, auto-select the first available or accepted  mission in:
- the player's current system
- along the travel plan (going out)
If a mission was found, auto-select the system and center the map on it, otherwise, display the panel with no mission selected.
If the panel displays with no mission selected, just pressing the up/down arrow keys initiates navigation through the missions.
> Autoselect mission in selected system or along travel plan.

- data/map.txt
Illogical placement of Korath Home in Kor Ak'Mari (it has no hyperlinks, therefore no way for worldships to get to the system. Home ships that spawn here glitch when their hull is damaged and basically give up on life
> Remove impossible Korath fleet (Korath Home) from Kor Ak'Mari

- source/OutfitterPanel.cpp
Fixes #740 by making `OutfitterPanel::CanBuy()` return false for outfits in cargo that cannot be installed.
With these changes, having an outfit in cargo does *not* allow a player to install an outfit for which they do not have a license. I do not know if this prevents players from being able to do something they would have been able to do, looking into it.
> error message for installing outfits in cargo

- readme-developer.txt
this way it can be copy-pasted after `apt-get install` or anything of the kind
> make dependency list easier to copy-paste

- data/free worlds intro.txt
Two small corrections to mission text. The comma is unnecessary and in my case the mission was on a moon, making "fly around the planet" awkward.
> Wording change and grammar fix

- source/Ship.cpp
Outfits can now be given a "solar collection" attribute, which will generate a variable amount of power, based on distance from the current system's star, using a similar formula to that which determines ramscoop effectiveness.
Given the current formula, a solar collection value of .5 will effectively power a shuttle as long as the star is close enough to be visible.
This was suggested by @DingusShingleton.
> enable solar collection attribute

- data/outfits.txt
- source/BoardingPanel.cpp
- source/OutfitInfoDisplay.cpp
Only the mass expansion was actually made unplunderable in this pull request, because plundering them can result in impossible ship configurations with negative outfit space available. 
For the record, I don't want reactors or other popular plundering targets to become unplunderable; I think there are better ways to improve economic balance.  However, having support for the attribute is certainly a good thing.
> Support "unplunderable" attribute for outfits.

- data/ships.txt
Moved the vanguard from behind the protector down before the wasp
> Get the Vanguard back in alphabetical order

- data/map.txt
I fixed the mention of "Republic Senate" in the description for Reunion, and changed Reunion's local government to "Senate" to avoid having to restructure the sentence.
> refer to Reunion 'local legislature' and Republic 'Parliament'

- source/Font.cpp
- source/Interface.cpp
- source/ShipyardPanel.cpp
- source/WrappedText.cpp
- source/main.cpp
Per the "No compiler warnings" rule in the style guide, resolve compiler warnings for uninitialized members and recommended parentheses.
> Remove compiler warnings

- source/InfoPanel.cpp
Dumping a specific number (>1) of outfits from cargo wasn't displaying the credit value of the dump because DumpPlunder is called for that instead of Dump and DumpPlunder doesn't have Message logic.
Tangentially there's a bit of code repetition between InfoPanel::Dump, InfoPanel::DumpPlunder, and the logic that fires them in InfoPanel::KeyDown. I'm not sure how best to reduce that due to the ui callbacks involved.
> Value of dumped outfits missing message

- source/BankPanel.cpp
In the Bank panel, allowed 'pay extra' when used on Other to pay to more than just the first account
https://github.com/endless-sky/endless-sky/issues/1215
I created an issue for this because I wasn't sure about the PR etiquette and people's input can be helpful but I see that the contributing guide suggests going ahead and making a PR if you have something so here goes.
> Bank Panel, Pay Extra to Other one time

- source/OutfitterPanel.cpp
"Do you want to reload all the ammunition for your ship" message would pop up regardless of whether you could source the ammo while at that outfitter
> fixed ammo dialogue popping up regardless of availability

- source/PlayerInfo.cpp
re: https://github.com/endless-sky/endless-sky/issues/1245
formatting of filePath with ~ in the snapshot name causing missing pilot info on load screen and sometimes pileup of ~ in snapshot names
> find first ~ instead of last during pilot load

- source/HailPanel.cpp
- source/Politics.cpp
causing a planet to be temporarily hostile to you by provoking its government which was friendly causes bribes-to-land to be accepted but you're unable to land
swapped check to make bribes matter before provocation, the other option is making provoked governments not accept bribes
> can bribe but still not land on provoked planets

- source/ShipInfoDisplay.cpp
re: https://github.com/endless-sky/endless-sky/issues/1256
There's always going to be edge cases depending how people want to pronounce words, especially with h and y so I've left them out. Not sure if that can reasonably be handled short of having the content maker name their license in full: "a Historical Reenactment License" "an Honorguard Equipment License"
> Grammatical an

- data/interfaces.txt
- source/LoadPanel.cpp
removed the ability to save a snapshot after you die
this could have made sense before autosave was in but it's extraneous now and is in the way of possible options like permadeath or possible hardcore modes
fixed being able to press load game when no save files exist
stopped add snapshot from being an option when no player is loaded
removed ability to delete main save file as is suggested by the greying of the ui
> disabled saving after death

- source/InfoPanel.cpp
https://github.com/endless-sky/endless-sky/issues/1266
unpark button was showing for flagship and disabled ships despite them being unable to park or unpark
> add check for park button visiblity, off for flagship and disabled ships

- source/MapPanel.cpp
Engine.cpp sets the travel plan to the flagship's target if there isn't one so you couldn't truly clear your travel plan
clearing the travel plan in MapPanel::Select now clears the flagship target system as well
re: https://github.com/endless-sky/endless-sky/issues/1272
re: https://github.com/endless-sky/endless-sky/issues/744
> fix flagship target system sticking on map

- source/CargoHold.cpp
- source/OutfitterPanel.cpp
re: https://github.com/endless-sky/endless-sky/issues/1277
A better fix might be to have CanAdd restrict itself to positive numbers in the first place and have a CanRemove function for its counterpart but since both jobs are being done by CanAdd currently I don't know if that's desired, some people don't like too many functions all over the place.
> fix ammo problems from negative CanAdd and mass change

- source/HiringPanel.cpp
You could still hit the hire button if your bunk space was negative due to accepting a passenger mission
> fix, negative bunk space allowed hires

- source/PlayerInfo.cpp
fighter's not in your system were being sold off instead of remaining stranded
> fix unlanded fighters being sold on takeoff

- source/Files.cpp
Previously, the return value of `SDL_Get{Base,Pref}Path` was not checked
for validity which could result in segmentation faults if one of several
oddities occurred (e.g. creation of the saves directory failed for lack
of writing permissions on `~/.config` on Linux). Now we exit somewhat more
cleanly and provide a useful error message in this scenario.
> Fix segfault on problematic paths

- source/DrawList.cpp
Recent changes in b5aee26abb0f8a35459bc5230a3b7aba057b35c5 made cloaking a stark transition at cloak value 1.0 instead of a fade.
Used a call instead of moving the logic from, and removing, DrawList::Item::Cloak function despite only being used one place in case it finds use elsewhere with recent ongoing refactoring.
> add cloak call to fix stark cloak fade

- source/Ship.cpp
Ship::FinishLoading will reset the sprite of variants to the base model's sprite, because at load time Body::HasSprite() is very likely to return false.
While Body::LoadSprite will set `sprite` there's nothing forcing the sprite to have loaded frames at that point since GameData::spriteQueue is asynchronous, resulting in Body::HasSprite() returning false.
As a fix Ship::FinishLoading could use Body::GetSprite instead of Body::HasSprite, or some guarantee could be made about sprites being loaded but that's more complicated.
> [bug] Variant Sprites Are Reset to The Base Model's

- source/HailPanel.cpp
re: https://github.com/endless-sky/endless-sky/issues/1342
Fleet cost total can overflow singed or unsigned int for eager players resulting in oddities in bribe totals.
The actual bribe calc/value should be fine as int for now as you'd need a fleet cost of 10T to overflow the result.
> fix overflow of fleet cost in hail panel

- source/Ship.cpp
re: https://github.com/endless-sky/endless-sky/issues/1349
The change to make invisibility separate from cloaking missed the targeting check, making spriteless ships targetable
> add !isInvisible to Ship::IsTargetable

- data/interfaces.txt
- source/AI.cpp
- source/Engine.cpp
- source/PlayerInfo.cpp
Small fixes including the position of the volume level bar, hails occuring for dead players, preventing carried ships from being unloaded if they can't actually land with you, and checking for reserved bay space before choosing a parent.
The last issue was causing stranded fighters/drones because their potential parent would leave before being asked to pick them up since they were all trying to dock with one ship.
> Little fixes, hails, volume, fighters and drones

- source/Flotsam.cpp
- source/Flotsam.h
- source/Ship.cpp
re: https://github.com/endless-sky/endless-sky/issues/1453
Two changes to floatsam and ammo:
change Flosam::UnitSize() to use double
This change allows UnitSize to accurately describe the size of what it contains since some items have fractional masses which UnitSize() reported as 0
This fixes ships trying to pick up flotsam they don't have room for, typically ammo
change Ship::Jettison outfit to allow non-full flotsam boxes
This is to stop fractional mass items from disappearing if they don't completely fill a flotsam box.
removed static keyword to allow box sizes to be appropriate for each item
> ammo and flotsam

- data/free worlds middle.txt
Changed “dreadnought” to “Dreadnought”
> Capital Letter Missing (typo fix)

- source/PlayerInfo.cpp
drones and fighters kept the swizzle they were initially loaded with until manually launched
re: https://github.com/endless-sky/endless-sky/issues/1462
> Added ship government update during PlayerInfo::ApplyChanges()

- data/boarding missions.txt
Merchants occasionally pay you for helping them - why not the extremely friendly, peaceful, Hai?
I made it so it pays more, and has more of a chance, for two reasons:
a) The only place they get disabled is on the border between theirs and the Unfettered's borders, making it extremely dangerous, with a high chance of death.
b) They are the Hai, who are more friendly, more generous, etc.
The missions pay much more than the original (30k as opposed to 10) and are more common (< 27 as opposed to < 10.)
Similiar issues: #333 and #1002.
> Hai assist mission

- source/BankPanel.cpp
- source/InfoPanel.cpp
Details of the whys are in the commit messages, fixes include
* updating the loan qualification when the pay all button is used
* viewing a ship in your system from the info panel while in space will select that ship
They're separate commits in case you wanted to cherry pick items, if you prefer single commits let me know.
> Little fixes, bank pay all, info panel targeting

- data/hai ships.txt
- data/ships.txt
- data/weapons.txt
The ship and weapon descriptions for a lot of the user-submitted content--my own included--tend to be wordier than everything else, with rougher prose. Wherever there were such issues, I've tried to tighten up the prose, fix various grammar errors, and improve the clarity of what's being communicated.
> Prose and grammar improvements for many ship and weapon descriptions

- data/wanderers.txt
Vara Ke'sok was not tabbed in, and therefore it did not update the planet description when this event was triggered.
> Fixed part of the "wanderers: more systems lost" event

- data/map.txt
Spotted a missed word in the Kraken Station spaceport description. Easy fix
> Kraken spaceport typo

- source/Mission.cpp
- source/Mission.h
- source/Politics.cpp
This addresses https://github.com/endless-sky/endless-sky/issues/556. The new behavior is triggered by adding "stealth" under "illegal" in the mission description. You can now additionally add an optional message after the fine to have it displayed when you're scanned. Example:
```
mission "Transport partiers [1]"
name "Transport partiers to <planet>"
job
repeat
description "This group of <bunks> university students is willing to pay <payment> to have a huge party on <destination>, along with <tons> of their completely legal pharmaceuticals."
passengers 7 12
cargo "completely legal pharmaceuticals" 2 4
illegal 1000 "It turns out that the completely legal pharmaceuticals in your hold are not so completely legal after all. The officers who confiscate the goods spend a long time talking with …
```
> Getting scanned can now optionally fail any mission with illegal cargo

- data/names.txt
Fixed an issue with male titles showing up too frequently in civilian ship names introduced with https://github.com/endless-sky/endless-sky/pull/1783. Male titles were fully half of the plural nouns. Now it's 12%, and that number will fall as more plural nouns are added.
> Fixed an issue with PR 1783

- data/hai outfits.txt
Someone pointed out [over on the Steam forums](http://steamcommunity.com/app/404410/discussions/0/312265782622433578/) that the Hai engines, unlike the other engines in the game, are all over the place when it comes to the increase in efficiency per level. These changes make the increase in efficiency less spastic (and fix the Basrem Atomic Steering being more efficient than the Benga Atomic Steering, despite the Benga being a level above the Basrem).
@LocalGod79 Given that these were originally your doing, does it look alright to you?
> Hai atomic engine balance

- data/ships.txt
Changed the thruster flares scaling of certain Marauder Engine Variants (which have 3 close together engine hardpoints) to the  default threeway scaling of 0.7 + 1 + 0.7. MF and MQ were not changed on purpose, since they look better without.
> Marauder Engine Variants Scale 0.7 + 1 + 0.7;

- readme-developer.txt
I just moved from Mac to Fedora and found that the package names in the development readme are only accurate for DEB-based distros. Updated it with the correct package names for RPM-based distros.
Regardless, *man* was that easier than setting up a development environment on macOS.
> Updated development readme for RPM-based distros

- readme-developer.txt
In the RPM world, the libmad dev package is named "libmad-devel", not "libmad0-devel" (no such package is available).
> One-character fix for dev docs

- readme-developer.txt
I was worried you meant something different (Super-GLEW?) but...considering it's a one character difference, I think it's just a typo.
> Fix typo in package list for RPM based distros

- data/map.txt
Changed 'feat' in '...due to the feat that the Resistance might...' to 'fear'.
> Typo in Delve of Bloptab spaceport description.

- source/PlayerInfo.cpp
Previously, the "on complete" check of a mission could check out-of-date auto conditions. Now, UpdateAutoConditions() is run directly before checking for missions that can be completed.
To keep this tidy, CreateMissions() no longer runs UpdateAutoConditions at all, and PlayerInfo::New() (the only other function to run CreateMissions) runs UpdateAutoConditions itself just before.
This PR is to fix a scenario I was finding particularly with conditions like "ships: Medium Warship". If a mission has an `on complete` condition based on them, it'd check the condition as it was when you _last landed_, not as you're landing now. Leave ships behind, allow ships to catch up, have your ships destroyed or even just park/unpark since you last landed, and you'd have trouble.
> Auto conditions updated on landing before mission completion check

- .gitignore
Kind of the Windows equivalent of .DS_Store files
These come up a lot when making PRs on Windows that involve images.
> Adding Thumbs.db files to .gitignore

- data/coalition jobs.txt
Fixed the mission description for the Coalition games job to display the number of passengers. This fixes https://github.com/endless-sky/endless-sky/issues/2020
> Coalition games job fixes

- data/outfits.txt
It's not obvious that scanners' attributes are additive, with the range and speed increasing with every additional scanner you install. I changed the descriptions to mention this.
> Scanners' descriptions mention the benefit of installing more than one

- data/wanderers middle.txt
Wanderers: Sestor Search. When entering Aya'k'k during the mission, a "planet" tag is used, which refers to Vara K'chrai and not the planet in the system, Varu K'prai. Instead, I just hard-typed "Varu K'prai" to resolve this. If anyone has more elegant solutions, I'll be happy to amend it.
> Typo fix, Sestor Search?

- data/wanderers start.txt
#2094 @Alkallid 
>"Wanderers: Alpha Surveillance J" Has No Description
Fixed.
edit: also syntax change in earlier mission; converted `Farpoint` to `<origin>` (which it is) for appropriate style.
> Name and Description for Alpha Surveillance J (@Alkallid)

- data/wanderers middle.txt
- data/wanderers start.txt
A bunch of typo fixes for the Wanderer start and middle files.
One thing perplexes me:
Kor Efret or Kor Efreti?
> Wandering typo fixes

- data/jobs.txt
- data/wanderer jobs.txt
12 unique (30 total) generic Wanderer jobs. Just passenger transport and cargo delivery, all available after you can speak with the Wanderers. 
I specify generic because I plan to later do story-specific jobs that are available between certain parts of the story, like special jobs to transport Wanderers through the Eye or assist the Mereti in building their Greenhouses by giving them materials that they don't have.
The passenger/cargo sizes and payments are based off of Coalition jobs. Just tell me if you want it higher or lower.
I also received some help from PompanoZombie on Steam with these, working off of some stuff that he had done.
> Generic Wanderer jobs

- source/PreferencesPanel.cpp
This resolves https://github.com/endless-sky/endless-sky/issues/1901
I've added a dialog that appears when the user clicks on the zoom factor button, but higher zoom levels aren't allowed:
> Notify the user why higher zoom levels sometimes aren't allowed

- data/coalition jobs.txt
For reference:
http://www.dailywritingtips.com/punctuation-mistakes-1-unnecessary-commas/
Removing unnecessary commas:
Commit 1: "I, need food" would be incorrect, it is "I need food".
Commit 2: "I need a car, to get food" should be "I need a car to get food". The extra comma is extraneous.
Commit 3: "As part of a retirement plan, transport these 500 retirees" is incorrect. (https://owl.english.purdue.edu/owl/resource/597/01/) The phrase "as part of the retirement plan" does not apply to you, who is transporting the retirees. Instead, it should be "As part of a retirement plan, these 500 retirees need transportation". It's a grammatical error otherwise.
Commit 4: Same as above. The Arach interspecies are done correctly, so I just changed everything to fit the Arach.
Commit 5: "I need a …
> Resolving Punctuation Errors in Coalition Jobs

- data/transport missions.txt
The mine explosion happened on planet injured miners are transported from, not to, hence origin instead of planet in Rescue Miners 2.
> Correct place of accident in Rescue Miners 2

- data/free worlds start.txt
In FW Prisoner Parole 2 mission F.S. Starry Warrior became R.N.S. Starry Warrior. Corrected that.
> F.S. Starry Warrior shouldn't change its prefix in FW Prisoner Parole 2

- data/transport missions.txt
Now player is given a bit more precise instructions, and said ion thruster takes up 10 t of cargo space. (Initially was going to make it take up 20 t (as X1050) or 16 t (as even smaller thruster + steering), but decided against it in order for the mission being doable with Sparrow.)
> Edited Amy's instructions and added "thruster equipment" cargo in Terraforming Rand 3

- data/map.txt
added "station" attribute to heliarch ringworlds - since all quarg ringworlds have it too - and to Smuggler's Den
added "moon" attribute where it was missing ; performed fulltext search for "moon" and afterwards performed a full search for nested named objects (`		object `)
-------
I hope I did everything the "correct" way now, it's still my first attempt for a pull.
> +station tag to heliarch ringworlds ; +moon tags

- data/hai jobs.txt
- data/syndicate world jobs.txt
- data/wanderer jobs.txt
- hai jobs: dialog strings contained improperly escaped doublequotes. Fixed by using `` instead of "", as is done with other jobs/dialogs that have embedded doublequotes.
Before: ![tribute to firelode](https://cloud.githubusercontent.com/assets/20871346/24784259/e023186a-1b16-11e7-9292-8b88f503004e.png)
After: 
- syndicate world jobs: Updated the "Corporate retreat" mission displayname to avoid confusion
- wanderer jobs: Updated the "Invasive Species" missions to avoid confusion
Use of <planet> in the display name does not load the name of the intermediate destination that the planet has to visit, but is the same as <origin>.
Using <stopovers> would be better, but this text replacement hotword also gets the system name, so it will overflow the "Missions available" panel. It also may have …
> Fix errors/inconsistencies in jobs.txt files

- data/coalition.txt
Note: the heliarch outfitter is not used in v0.9.6 at all, but I changed it as well for consistency. Currently, every planet outside coalition space which has an outfitter, sells a Local Map. I.e. human space, hai, wanderer and kor efreti.
> mission "Coalition: First Contact"
> 			`	The centaur pulls out a map printed on a thin sheet of plastic. You recognize it as a star map of this region. Lines mark out three different territories, and where they meet are three star systems colored yellow. The centaur points to the southernmost of the three. "Where you must go, here it is," it says.`
They know what a map is and they even have hard copies.
----------
Possible reason to reject this pull: The player does not yet understand any of the 3 languages. Only the coalition species have the …
> added Local Map to coalition & heliarch outfitters

- data/korath weapons.txt
According to the description, the hitforce should be negative as well. Otherwise hitting the mine before it deploys generates more hit force when after deploy.
Alternatively, remove the hitforce from the Launcher and use only the hit force from the submunition, if a negative hit force for the launcher seems inappropriate.
> fixed typo @Mine Launcher hit force

- source/ConditionSet.cpp
- source/ConditionSet.h
Introduce "random" and playerConditions to the right side of conditions, allowing for:
- "random var" <= random
- "random var" = random
- "CoalitionJobsOld" = "CoalitionJobs"
- "reputation: Navy Intelligence" >= "reputation: Republic"
> introduce "random" to the right side of conditions

- source/AI.cpp
As the title says: ships shall not attempt to harvest flotsam if their cargo space is full. Before this PR they do/did.
Note that a ship still may follow its mining personality and crack those asteroids, even if cargo space is full. That happened before and was not changed.
Suggestion: If a ship has HARVESTS and MINING, then it should stop mining. A ship which has only MINING but not HARVESTS, should mine no matter if the cargo space is full - because that personality profile assumes, that some other ship(s) will harvest.
> ignore harvesting when cargo space is full

- source/AI.cpp
- source/AI.h
relates to: #2356 
In my local build it works like a charm.
Fighters can dock (my flagship) at "any speed" because they are now told to adjust to the carrier's velocity vector.
This PR does not modify the general behaviour of the carrier ships, i.e. AI controlled carriers (own escorts and NPCs) still come to a full stop. This should be done in a separate PR, imho. This is just a required step...
> Intercept (dock with moving targets)

- source/Engine.cpp
Fighters and drones "under" should be under any engine flares.
I simply swapped the two code blocks, drawing "under" bays before drawing engine flares now.
> Changed z index of bays "under"

- source/Engine.cpp
- source/PreferencesPanel.cpp
I adapted the code from the `target sprite` section, some 70 lines below.
Rotating the sprite of the flagship in the HUD helps particularly, if your escorts are "over" your flagship.
> rotate player sprite according to facing

- source/BoardingPanel.cpp
- source/Ship.cpp
- source/Ship.h
Okay, this doesnt look perfect in terms of the number of commits as I was struggeling a bit with the number of branches in my profile, but that's my first attempt to contribute to the code.
**Warning:** I am not used to write C++ && I dont have tested this since I dont have downloaded the code to my system (where, since it is Debian, a compiler must be available, lol). --> Hence some dev needs to check what I wrote.
Purpose: Give the friendly boarding (with respect to refuelling) a better AI allowing to refuel in more cases.
Currently, Sparrow 1 with 152 fuel cant refuel Sparrow 2 with 51 fuel because 0.9.6 always wants to transfer the full 100 (given a Hyperdrive).
Stripped savegame for testing attached
[Lydia S~non-smart refuelling in Sirius …
> smart refuelling

- source/MapSalesPanel.cpp
This mini change takes sprite->Width() into account when scaling a sprite (to be displayed in a map sales panel).
Without that, wide sprites didnt look as expected but overlapped the bounding box.
Attached the sprite which made me find this and motivated me to solve this.
> (bug fix) scale wide sprites properly @ map sales panels

- data/jobs.txt
The job title says dangerous origin but the description said dangerous destination. Changed so that the description says dangerous origin.
> Escort job description fix

- source/Engine.cpp
> Fix to scanned ships that jump away still having scan circles visible

- data/ships.txt
I noticed this issue while I was looking through the ships file for unrelated reasons. The original sentence is technically grammatically correct, but I believe this one is more readable.
> Readability fix for Bactrian description

- source/DistanceMap.cpp
Escorts will not attempt to pathfind via wormholes that are inaccessible to them but are accessible to the player.
Closes #2490
This does not solve the sub-issue raised by the unique situation in #2490 where, after the player uses a route that the escorts cannot, then returns to regions available via accessible routes, escorts "misbehave". It should, however, prevent such a situation from arising in the first place.
> Pathfind via accessible objects only

- source/AI.cpp
This PR closes #2503 
Autopilot landing was added in 8483cff
In 3d66260, code was added that acted before the autopilot AI could issue its landing order.
This PR moves the relevant block from UpdateKeys to MovePlayer, just before the keyStuck commands are evaluated.
I had thought that perhaps modifying the lines introduced by 3d66260 would be simplest, but including ship.GetTargetStellar() in the keyStuck.Has(Command::JUMP) comparison results in a segfault upon arrival in the destination system, while moving the code block (this PR) results in successful autopilot reactivation:
> Reactivate Autopilot Landing Sequence

- source/MainPanel.cpp
Previously, an NPC with an outfit in cargo would not show that cargo
when scanned. This makes an outfit in
cargo behave like ordinary cargo for scanning.
@endless-sky, your commit 80593fc9c734e178ef9989a2b0697775637e92f5 only included the plundering side of #2495, not the scanning.
With @tehhowch's PR #2517 and without this, we get this:
> Outfits in cargo can be scanned

- data/fleets.txt
fleets.txt contains a wrong spelled ship name in Line 709.
This PR fixes that.
Edit: forgot to mention @tehhowch who found out that there is an error in the "Large Human Merchants (Hai)" fleet definition.
> content typo/bugfix: Water Bug (wrong: Waterbug) in a fleet definition

- source/Engine.cpp
At the moment, Engine::EnterSystem plays music before IncrementDate is
run (which manages event handling). This means that if an event changes
the music of the system you're in, you won't get the change until a day
later. This fixes that by reordering the code. Should also fix the same
issue with haze, if an event changes that.
> Fix to changing a system's music in an event

- data/hails.txt
- source/Government.cpp
- source/Government.h
- source/HailPanel.cpp
- source/Ship.cpp
@Amazinite suggested in #2526 that it'd be useful to be able to define a custom `hostile disabled hail`, rather than Wanderers, Unfettered, Heliarch etc. calling you a fobbing dizzy-eyed codpiece. @EndrosG suggested (https://github.com/endless-sky/endless-sky/issues/2531) we should, at the same time, permit a custom `friendly disabled hail`.
@EndrosG, @tehhowch and I have put together this PR to do this. The format is as follows:
```
government "Heliarch"
...
"friendly hail" "friendly heliarch"
"hostile hail" "hostile heliarch"
"friendly disabled hail" "friendly disabled heliarch"
"hostile disabled hail" "hostile disabled heliarch
```
with each line being completely optional. This PR shouldn't change anything in-game by itself: content creators will need to PR/propose changes to …
> Disabled hail (friendly and hostile)

- data/free worlds intro.txt
With the current set up of the intro missions there is a fall off in the chance of the player getting any one of them as more [sets of] missions are completed. The probabilities are approximately 67% 71% 56% 33%* for 0,1,2,3 missions completed respectfully. 
This feels backwards to me because I would expect that the more you help the FW the more they will ask for your help. This also means that as players get closer to starting the campaign proper it gets harder to find that next mission.
I propose that the probability is increased for each mission completed so that the probability of the next mission being found either increases or remains roughly the same.
The table below shows the percentage chance of each mission with a number of "assisted free worlds" conditions held along with an …
> Altered random conditions across all FW intro missions

- source/Sale.h
As per https://github.com/endless-sky/endless-sky/issues/2559, 5d955787ccc74c09b04e9b9708de32fd1b594345 doesn't compile. This fixes it by using `std::string` instead of `string`.
> Fix to string definition of token in Sales.h

- source/Ship.cpp
When a ship dies, in addition to any items in its cargo hold, any ammunition it was using may also be jettisoned as flotsam (5% probability vs 25% for cargo).
This may be better done with a double check, first at a low rate (e.g. 1%) and then normal quantity (25%) if successful. This method may be more attractive if there is a lot of pickup spam from ships which are disabled before using their complement.
> enhancement: Add Ammunition outfits to explosion flotsam

- data/wanderers middle.txt
There was originally a typo, but that particular phrase read a bit weird anyway.  I reckon the current wording is a bit nicer / more polished.
> Minor wording tweak in Pug Assistance 1

- source/System.cpp
When an event should replace the fleet presence in a system, it was
instead always adding. This is due to a typo, where the haze is cleared
instead. Best way to see this is, in a post-Free Worlds save, going to
Altair and watching the Pug show up.
> Fixed an issue with events changing system fleets

- source/Fleet.cpp
In a fleet definition, using the node `remove variant` and then supplying a valid existing variant for that fleet will result in the removal of that variant from the instantiated fleet definition.
- A valid existing variant is one which contains the same ship specifications (in any order).
- `remove variant` ignores any supplied weight value and always removes the variant if a matching variant is found, starting with the first variant (and ordered as listed in the original fleet definition).
- If no match is found, a stack trace is printed to aid in debugging content. This can be removed / altered but should only appear for malformed or unnecessary removal requests.
Issues addressed/enabled: #2549, #1520
<details>
<summary>Functionality Verification Files:</summary>
modding text: …
> enhancement: Remove variants from Fleet definitions

- source/Projectile.cpp
The Wiki describes the steady state of projectiles as being
acceleration/drag, but it's currently acceleration/drag - acceleration.
This fixes that by tweaking the order of adding acceleration and scaling
by drag.
Noticed this in response to https://github.com/endless-sky/endless-sky/issues/1939#issuecomment-305274004, and it seems to mean that most missiles in the game are a little slower than expected.
The current code in Projectile::Move is:
```
if(accel)
{
velocity += accel * angle.Unit();
velocity *= 1. - weapon->Drag();	
}
```
Take a [Meteor Missile](https://github.com/endless-sky/endless-sky/blob/master/data/weapons.txt#L504-L510): velocity 10, acceleration 1 and drag 0.1. In the first frame, it will gain 1 speed, and then be dragged back 10% to 9.9. The steady state is 9, when it …
> Fixing projectile steady state speed

- source/AI.cpp
The previous fix to #2331 was 3cf5f95 and 525c6196, but the latest update to targeting removed this check for player-defined targets. This commit restores this check, preventing turrets from tracking cloaked ships.
Without the fix, the player is able to target cloaked ships:
> bugfix: Turrets only track targetable ships

- source/AI.cpp
- source/AI.h
- source/Engine.cpp
Issuing MOVE_TO orders now includes a target system, allowing selected escorts to navigate across system boundaries to the specified position, instead of navigating to that point in their current system.
Ref #2584, Closes #2580, Closes #2382
> bugfix: MOVE_TO orders refer to a specific System

- data/events.txt
- data/wanderers.txt
One fleet got missed (Wanderer Defense). I also incorporated the #2577 functionality to change the mk2 republic event from redefinition to dynamic update. Using the dynamic method adds back a few lines, but will prevent squashing any content added to these fleets by plugins, and also help introduce this syntax & use to content-creators.
> Shortening events with add variant (Wanderer Defense + Mk2 Republic)

- data/landing messages.txt
The relevant sprite was missing.
This was added in my other PR, but given the other commits I chose to separate the related-but-not-totally updates into separate PRs.
> Add default non-landable message to restricted red wormholes

- source/AI.cpp
This is an implementation of solution 2 as identified in #2608
With this fix, carried fighters and drones will remember any assigned orders that require a target, so long as the target is valid (e.g. exactly like normal escorts). This allows commands which toggle on a target (such as GATHER or ATTACK) to correctly function, no matter if your fighters/drones are deployed or in their bays. Without this fix, commands which toggle on a target can only be set if any of your fighters are being carried. Attempting to revoke / toggle the command will instead re-issue the command.
> Carried fighters/drones no longer clear orders needing a target.

- source/AI.cpp
**Problem:** although a weapon's Range() is mostly correct (though I still hope #1826 can be merged, as submunition velocities still aren't considered), the new AimTurrets function effectively recalculates it, and uses Lifetime rather than TotalLifetime. This means that a turret using submunitions will struggle to aim, as follows:
Well within range, but the turret won't turn to hit. It'll only turn within 240 range, as per:
```
outfit "Matrix Battery"
category "Turrets"
...
weapon
...
"submunition" "Matrix Bolt 1" 1
"lifetime" 12
"velocity" 20
```
**Solution:** just switched Lifetime for TotalLifetime. Seems to solve the problem.
> Fix to AimTurret to use TotalLifetime instead of Lifetime

- source/BoardingPanel.cpp
```
Previously, capturing a ship didn't actually change your reputation with
the ship's government. The event never went into the eventQueue, so
wasn't processed by AI::UpdateEvents and didn't flow into Offend. This
fix directly runs Offend when you capture a ship.
```
Credit to Farteous (on Discord) for noticing this when delving into how to capture a Heliarch Interdictor. It doesn't look like capturing has ever changed reputation, as far as we can see.
Disabling, boarding and capturing a Heliarch Interdictor (RequiredCrew = 44) should give you -79.2 reputation ([0.5+0.3+1](https://github.com/endless-sky/endless-sky/blob/master/source/Government.cpp#L36-L38) times [44](https://github.com/endless-sky/endless-sky/blob/master/source/AI.cpp#L223)), but we only saw -35.2, consistently. …
> Capturing ships should affect reputation

- source/Ship.cpp
- source/Ship.h
- source/ShopPanel.cpp
```
The nomenclature is the word "swizzle" (quotes unnecessary) followed by
a number between 0 and 8, at the same level of indentation as sprite or
attributes. Use 0 for no swizzling of the original sprite.
```
@endless-sky, I'm closing https://github.com/endless-sky/endless-sky/pull/2617 in preference to this, as per your suggestion.
Have compiled and tested not just with the `swizzle 0` cases, but arbitrary values.
First commit is just the necessary changes, and second makes the shift to using `key` instead of `child.Token(0)`.
**Edit:** oops, hold on, lost an `if(government)` line. One minute. (Third commit fixes that.)
**Edit 2:** may have another issue with `swizzle 8`, investigating. (This seems to be 'normal', that the outline swizzle doesn't show in flight even if a government is …
> Ships can have a custom "swizzle" property

- data/interfaces.txt
```
Adding the Logbook button, and the condition for when it's active has
incidentally attached that condition to the Next and Previous buttons in
Ship Info. This means they're greyed out unless you have log entries.
This fix just adds the line "active" so that Next/Previous are always
active.
```
My Ship Info screen right now:
The problem is that this block in interfaces.txt:
```
active if "enable logbook"
button l "_Logbook..."
center 255 305
dimensions 90 30
visible if "five buttons"
button n "_Next"
center 145 305
dimensions 90 30
button p "_Previous"
center 45 305
dimensions 90 30
```
causes the "enable logbook" condition to apply to the next two buttons as well. (But no further, because after that a new "can park" active-if applies.) Switching these two sections around escapes that. …
> Fix to 'inactive' Next/Previous buttons when you have no Log entries

- source/Engine.cpp
- source/Font.cpp
- source/Font.h
- source/HailPanel.cpp
- source/PlayerInfoPanel.cpp
- source/ShipInfoPanel.cpp
- source/ShipyardPanel.cpp
- source/ShopPanel.cpp
Adds front or end string truncation to the following locations:
- Shipyard sale confirmation dialog: each ship occupies a maximum of one line instead of possibly overflowing onto multiple (#2249)
- Shipyard/Outfitter ship details panel: no overflow out of rounded square border
- Hailing screen: no overflow off right edge for combinations of long ship names and/or long government names.
- Targeting reticle: no overflow off left edge of ship name
- Player Info fleet list: no overflow of ship name across category
- Ship detail screen: no overlap of "ship:" and the ship name
I have applied front truncation where sensible to preserve any identifying numbers that may have been added to the end of the ship name when buying in bulk.
<details>
<summary>Appearance with this PR:</summary>
Selling …
> Truncate displayed ship names to prevent overflowing containers

- source/AI.cpp
Commit c162a34a44ca749f3edebeae92afde1bd8c4a833 adjusted the default behavior of parented ships (e.g. ships in a fleet, your owned escorts, or mission NPCs (friendly or hostile)), but it has some oddities with hostile escorts in systems in which they have no other targets:
These pirate fleets in Wah Ki have no natural enemies (no `attitude toward` / from either Hai or Unfettered) except for the relatively rare Merchant fleet spawning. If you happen to not feel like fighting at the moment and cloak, c162a34a44ca749f3edebeae92afde1bd8c4a833 instructs them to follow the MoveEscort routine. MoveEscort logic will fail due to the lack of target and parent commands, and sends the hostile escorts to the KeepStation() method, with their parent as the target. Parent is your flagship, and thus you …
> Hostile NPCs should not KeepStation with cloaked parents

- source/NPC.cpp
```
If you need to board or scan a ship, and that ship is destroyed before
you do so, the mission will now fail.
```
If you try to write an `npc board` mission that isn't also an `npc save` mission, you'll run into this. If the target is destroyed before you can board it, the mission is stuck in limbo and there's no good way out of it as a mission creator.
To fix this, I've modified NPC::HasFailed so that a mission is marked as failed in this situation. It now:
- defines a bit field mustLiveFor, the mission actions that require the target be alive for (boarding and scanning).
- returns the failed state if:
```
(~it.second & succeedIf & mustLiveFor) && (it.second & ShipEvent::DESTROY)
```
in plain English:
- there's an action we haven't performed yet (~it.second)
- that we need to perform …
> Made a mission fail if it becomes impossible to complete

- source/AI.cpp
These steps prevent the player from toggling LAND in an otherwise "uninhabited" system with a StellarObject already targeted, which will generate a segfault at AI.cpp:2472.
With this PR, the following issues can be closed: #2487, #2596
The functionality of #2601 (TravelPlan Validation upon Takeoff) still has merit, as it will prevent the player from automated traveling that will not get them to their final destination (and further guard against invalid StellarObject targeting).
> AI TravelPlan actions should not target inaccessible StellarObjects

- data/wanderers middle.txt
The Varu K'prai hint now tells the player that the Sestor fleet left wanderer space. 
I don't think this is too much telling simply because it simply dose not occur to them that the fleet could have used jump drives. Hopefully this will get people to start searching beyond human space when #2427 can help them.
> made a sestor search hint less subtle

- source/AI.cpp
Added a check of the target's personality for the "escort" tag, which indicates a ship important enough to the player that it appears in the HUD.
Should fully address #2586
This will both increase and decrease the difficulty of "Escort to ____" missions, as they spawn opposition with the "nemesis" personality:
1. A single-ship player is no longer the sole target of the pirates.
2. The player will need to help defend the NPCs being escorted, rather than simply get close enough to become the target and then fly away from the freighters.
Things affected:
- Escort to ___ jobs
- Planetary defense spaceport missions
- FW mid: Ryk Bartlet
- FWR 1B/1C: Syndicate ships will more readily target the `timid` Navy Intelligence ship
- FWR Embassy: Pirate ships will more actively target your Dreadnought …
> "Nemesis" target selection now considers NPCs escorted by the player

- source/AI.cpp
When cross-system MOVE_TO was implemented, the check to space out ships that were in the player's system did not get updated.
With this PR, any ship in the command group will offset its target point from the group's target point by a small amount. This will prevent ships that were not in the player's system at the time of the order issuance from stacking on the same exact spot, except in the rare case that they are already in the same spot.
> MOVE_TO orders should not stack ships on the same position

- source/AI.cpp
@Amazinite  tipped me off that ships which are mining may completely ignore that they promised to help.
He was right.
This PR fixes that by preventing a ship that is mining from starting a new mining cycle if it has promised to help someone. Additionally, the AI will not request the help of a ship that has targeted an asteroid (e.g. is actually mining, not just able to mine), or is trying to pick up some space debris.
> bugfix: Ships no longer mine if they have offered assistance

- source/Engine.cpp
- source/Ship.cpp
When a ship cloaks, any "scan circles" will be removed
If your targeted ship is cloaked, you cannot attempt to scan it.
This PR makes this no longer possible:
(that Arfecta scan circle was drawn *while the Arfecta was completely cloaked*)
> bugfix: Do not allow scanning of cloaked ships

- data/interfaces.txt
- source/Engine.cpp
- source/EscortDisplay.cpp
- source/EscortDisplay.h
Status overlays (shields, hull, scanning progress) were previously fixed
- New colors are added to data/interfaces.txt to allow custom colors
Escort attributes (shields, hull, fuel, heat, energy) were previously hard-coded to the default values assigned to the flagship.
- Escort colors now mimic the custom values given to the user's flagship's attributes.
- The existing "overlapping bar" behavior for displaying attributes that differ between like-model escorts is preserved.
These changes to user-colors allow players (and mods) to define more visually accessible color schemes as needed.
Acknowledgements to @jafdy for the PR request.
> enhancement: Use user-defined colors for status overlays and escort attributes

- data/syndicate world jobs.txt
Removed the `timid` personality, as the espionage target is already `uninterested` and all timid does is force an escort to be near its parent (and `uninterested` means it has no parent)
Added the new `target` personality so the player can begin tracking this NPC as soon as it enters the system, and not only after somehow managing to cycle through all the possible ships in the system.
This doesn't address the sheer insanity of trying to keep up with a Bounder or Scout that is forbidden from accepting a ship target (by `fleeing`), but does make it a little easier.
Also changed the "overheard" snippet, as I'm not quite sure how scanning the ship's cargo could set someone else back, rather than advance the party receiving the scan..
> Use the Target personality with Corporate Espionage

- source/AI.cpp
If a vindictive NPC targets a ship that can leave the system while not ceasing to exist (e.g. certain NPCs or a carried ship), that ship leaves the system, and there are no new targets to acquire, the vindictive NPC will fail to behave normally (e.g. KeepStation with its parent), and instead simply drift.
This PR updates the vindictive targeting logic to consider if that target has left the system in some manner.
A simpler check is to replace the cloaking and GetSystem checks with IsTargetable(), but that would remove the "vindictive" flavor wherein the NPC continues to unload into the already-dead and exploding target (since IsTargetable() checks that the target's hull is > 0 and it is not exploding).
> bugfix: Vindictive ships only remember in-system targets

- source/AI.cpp
The mining personality will now deploy any carried ships while actively mining.
These carried ships inherit the mining personality, so if they have cargo space free, they will mine independently.
After filling their cargo space, carried ships will assist their parent ship in destroying its target asteroid.
The restriction to carried ships is arbitrary, and could be removed, in which case any member of a fleet that is not actively mining or in combat, but has a fleet leader with the `mining` personality, would choose to assist that fleet leader in destroying its target asteroid. Removing the carried ship restriction would necessitate adding a check for a shipToAssist.
If the DoMining routine is updated to allow changing the target asteroid if it gets too far away from the ship that is …
> Carried ships assist in NPC mining operations

- data/interfaces.txt
- source/Engine.cpp
- source/EscortDisplay.cpp
- source/EscortDisplay.h
- source/Radar.cpp
If a mission adds a hostile ship to the escort display so that the player can track its whereabouts, this ship will appear under the player's colors (green) on the radar and in the target reticle, rather than the orange-red hostile colors:
This commit prevents drawing hostile escorts as assumed friendlies:
> Mission NPCs added to the escort display are drawn with hostile colors as appropriate.

- source/AI.cpp
In 4ab74b5bc8 hostile, non-staying NPCs which could not target any ships in a system were instructed to patrol it instead of jump away and then jump back. However, if the player left the system while remaining untargetable, the NPCs would get stuck landing if they were targeting a non-planet at the time of your jump.
This commit resolves the logic bug in MoveEscort that assumed the ship's stellar target was a landable planet by verifying that it is indeed a landable planet. If it is not, the ship will clear the target and resume tracking down the player.
This simple mission illustrates the issue: accept the job, then cloak and jump away once the bounty ship is targeting a non-landable object in the system.
[hostile_shouldfollow_stuck.txt](https://github.com/endless-sky/endless-sky/files/11 …
> bugfix: Restore follow-parent behavior for hostile NPCs which began patrolling

- source/AI.cpp
See [comment](https://github.com/endless-sky/endless-sky/issues/2251#issuecomment-314875350)
Now if a ship cannot make a jump and is flitting about the star, it will jump away when it has enough fuel to do so.
> NPCs which cannot land on a stellar object will not get stuck trying to.

- source/Personality.h
With the addition of the Marked personality, `Personality::IsSkybound()` was effectively removed from the game. ...Except for the declaration in Personality.h. This PR fixes that.
> Remove "Skybound" declaration

- source/GameData.cpp
https://github.com/endless-sky/endless-sky/commit/dfa06d6afd0f3f5ad91c9d4bd9db567327a2f4fc made the submunition check in GameData::PrintWeaponTable() always fail. This PR uses an empty category to detect submunitions instead.
> fix check for submunitions in PrintWeaponTable()

- source/Engine.h
Ship 'forget' tracking is done internally within the Ship class.
> Remove unused 'forget' defintion

- data/map.txt
I've checked the descriptions of all the affected planets and I believe that all the replacement images fit the descriptions as well as or better than the previous image.
The main purpose of this was to use some unused landscape images, but this only uses half of what is currently unused. There's another 22 images that are unused either because there aren't enough planets with the type of landscape that the image is or I didn't think that any of the unused images could replace a duplicate image and still fit the description (e.g. the planets with lava0 or lava6 didn't feel like they could be replaced with lava7).
> Replacing duplicate landscape images

- data/wanderers middle.txt
- data/wanderers start.txt
- data/wanderers.txt
This work is taken from my PR that adds more mining variants (to capitalize on #2726 ) and extends mining from just humans and the Kor Mereti to almost all factions. When it came time to add to the Wanderers, I noticed that while we had updated the fleet definitions with add/remove, we had entirely neglected to do the same for system definitions. 
This PR splits the work of changing how the fleets are defined in Wanderer events from the tangentially related "update fleets and races to utilize mining" that is #2752
> Implement add/remove syntax for the Wanderers campaign

- source/CargoHold.cpp
- source/CargoHold.h
When performing a TransferAll(), first obtain a descending-by-mass sorted vector of the outfits to be transferred, and then move outfits by iterating over that vector. If an outfit does not have a specified mass, outfit->Get("mass") will return 0 and there is no limit to the number that can be in a given cargo hold.
This means that the largest outfits that can fit in escort holds are guaranteed to be in escort holds.
edit: this is a First-Fit-Decreasing bin-packing implementation, minus the bits where new bins can be added and the bins are all the same size.
Photo proof:
My cargo while landed:
1 Jump Drive, 1 Large Heat Shunt, 2 System Core (Medium), 1 System Core (Small).
This order is also the order of the items in the `outfits` variable used by CargoHold.
To takeoff, on `master`, this …
> Transfer outfits in reverse size order

- source/AI.cpp
The reparenting fix af9e646be could result in fleets which have carry-capable ships and also more fighters to carry than bays available. This commit allows a full carrier to begin moving again, instead of remaining paralyzed while the escort feebly attempts to board.
> bugfix: Carriers should only wait if they have bays free

- data/drak.txt
Spotted by Steam user [insanity](https://steamcommunity.com/profiles/76561198132906458), reported [here](https://steamcommunity.com/app/404410/discussions/0/1458455461480814723/#c1458455461482195536)
Since the variant has multiple turret types, they were being placed differently than the normal Archon's weapons..
> Restore Archon (Cloaked) turret assignments

- data/wanderers start.txt
Because the mission does not use stopovers/waypoints (since you can sell a Jump drive in any particular Unfettered system), indicate to the player why the mission has not yet completed despite displaying the "mission is ready to complete" marker.
> Add `on visit` to "Wanderers: Jump Drive Source"

- source/AI.cpp
Refs #2823 
Add checks during AI::Step to require that ships which have asked for refueling assistance come to a stop, even if the ships in question have specialized action personalities.
- Ships which are entering hyperspace do not ask to be refueled mid-jump.
- If a ship resets its assistance target to no ship, it carries out normal AI::Step behaviors instead of skipping a turn
To accomplish this, AI::Step was mildly reordered:
1. "Am I disabled/stranded and can anyone help me?" If no one can refuel me, then I'll act normally.
2. Cloak if cloaking, deploy if deploying.
3. Low-health actions (dump cargo if appeasing, forget parent if coward)
4. Turret aiming, weapon autofiring, and attack target assignment were made to apply to all ships, by moving to follow the low-health actions
5. …
> Update Stranded / Assisting ship behavior

- data/interfaces.txt
- source/Engine.cpp
- source/Radar.cpp
- source/Radar.h
This PR adds a "radar blink" color that mission targets use to mark themselves. It can be set independently of the color of the ships the player's flagship is targeting.
> Allow mission target blink color to be set independently of ships the player is targeting

- source/Engine.cpp
This PR makes restricted planets show up yellow on the radar, instead of red. (Red is still used for hostile planets).
I felt like there should be a difference between "you can't land here because this planet is restricted" and "you can't land here because we hate your guts".
To be fair, there _is_ a difference in the `master` branch: The little spikes on the planet label. You'd have to be really attentive to notice it, though.
EDIT: I just now noticed how this change is nicely consistent with the way restricted planets appear in the map view :)
> Make restricted planets a separate color from hostile ones

- source/AI.cpp
Ref #2829, and probably others.
Ref: https://steamcommunity.com/app/404410/discussions/1/1458455461497401563/ and probably others
Summary:
- Escorts that are routing through wormholes to reach their parent will not set both a target planet (wormhole) to land on, and a target system to jump to.
- This fixes a bug causing Ship::JumpsRemaining() to erroneously return 0 when the ship's targetSystem is its current system instead of nullptr (e.g. making ships think they were stranded when they were not).
- Escorts that cannot jump to their flagship's target system will not attempt to refuel until the flagship leaves their system, and after attempting to refuel, will wait at the system center until a route to the parent's system exists.
- No more "landing dance" while the player holds the jump …
> Fix MoveEscort bugs when using wormholes or unreachable destinations

- source/Ship.cpp
If the flagship is below its required crew count, the transfer amount was always set to at least 1, even if the captured ship was an automaton.
Ref #2789
> Bugfix: do not transfer crew to automatons when short on crew

- source/AI.cpp
**Refs #2836**
Instead of checking `ship.Cloaking()`, access the ships Commands to determine if it is cloaking/maintaining cloak, or is decloaking. This allows the higher hysteresis value to only apply when the ship is trying to cloak, rather than while the ship has any degree of cloak, preventing the ship from immediately recloaking if it takes any damage while decloaking.
Test save (courtesy of Steam user): 
On `master`, the Archon will cloak to repair after being reduced to health = 1, but then after repairing to health = 1.4, it will rapidly cycle its cloak if it is in your fleet's weapons range and takes damage before decloaking.
With this PR, the Archon has to be damaged back to health = 1 once it has started decloaking before it will cloak to repair.
[Travion …
> bugfix: Ships which cloaked to repair should fully decloak after repairing

- source/Engine.cpp
In the `master` branch, modders can use StartConditions.txt to specify an alternative starting date from the default. Unfortunately for them, the help messages typically shown for the first 4 days of a vanilla game... assume modders don't do that, for some reason.
This PR switches the help message cutoff to be 4 days ahead of the actual defined starting date, whatever this may be. This has 2 effects:
1) If plugins set the start date ahead of the vanilla start date, the basics help messages will still be shown
2) If plugins set the start date way _behind_ the vanilla start date, the basics help messages will not continue to be shown for literally the entire playthrough.
> Help messages no longer assume a fixed start date

- data/wanderers middle.txt
Refs #2848 
- Fix incorrect <system> in on offer conversation
- Add `waypoint Alnilam`
- Add `to complete`
- Move the "fail bomb zenith" for having defended Farpoint into the bomb Zenith mission
- Would otherwise remain in the mission list until landing again, despite actually being failed via the `on offer` of Sestor Alt: Alnilam 1.
I wanted to add an `on visit` as well, but due to the completion order, but if you came straight from Alnilam and destroying the Sestor fleet there, you'd still get the `on visit` message because the fleet-destruction missions weren't marked as complete yet.
> Update Wanderers: Sestor Alt Alnilam 1

- source/MainPanel.cpp
Without it, things kinda jumble up:
The idea of knowing what's in a void sprite's stomach is a different matter :laughing:
> bugfix: Add missing newline to scan dialog for uninstallable outfits in cargo

- source/ShopPanel.cpp
> bugfix: Skip disabled ships when shift-clicking a range in Shipyard / Outfitter

- source/AI.cpp
- source/AI.h
Ref #2835 , #2846, perhaps some steam issues.
This PR dramatically reduces the game lockup seen when entering an uninhabited system with a large number of out-of-fuel escorts, to the point where it is almost indistinguishable from that of the normal game.
Summary
- Move "can anyone help me" code into into separate function
- Use std::vector to store possible choices instead of 2 pointers.
- Randomly choose a possible helper (must check all ships in the system in order to determine if there is an enemy present)
- Reduce frequency of calls to avg. 2 per second rather than every step for every stranded/disabled ship.
> Refactor AI::Step's "Find someone to assist me" section

- source/Engine.cpp
Something I've noticed is that if one has the "warning siren" preference on, then hostile ships that flash on the radar (i.e. are overheated or have the `target` personality) will also trigger the warning siren... repeatedly. This PR stops that behavior by querying the ship's target, rather than its radar type.
> Ships that flash no longer repeatedly trigger the warning siren

- source/AI.cpp
- source/Engine.cpp
Refs #2840 
If the player selects a landable object that is not part of the travel plan, it will have priority over the automatic landing target needed for completing the TravelPlan.
I also added a QoL feature, where if you press Jump when your next step is to land on a wormhole, a message about landing on the wormhole is displayed instead of the erroneous message about jumping to the system you are facing.
> Allow landing on planets or wormholes that are not in the TravelPlan

- data/remnant missions.txt
Refs #2866 
- Move the existing faction log for the Remnant to the `on decline` so that it is learned only if the player could logically have learned it.
- Created a replacement faction log with the observed information at the time of flight, if the player refuses.
- Added a regular log message so that the player can remember when the Remnant was first met.
If a method to improve Remnant rep is added, a mission which adds the missing information to the special logs can be added when the player is able to learn of the Remnant's history.
> Update Remnant faction knowledge based on friendly/hostile relationship

- data/weapons.txt
After the update that gave turrets limited turn rates, the description of the basic laser turret still said it could turn instantly, which was no longer true.
This PR corrects that description.
> Correct the laser turret's description

- data/ships.txt
Old Barb:
>Though the Syndicate doesn't build Fighter carriers
This PR:
>Though the Syndicate doesn't build fighter carriers
> Typo fix in ship description

- source/NPC.cpp
Appeared in ee9d339f: when multiple ships are present in an NPC specification, only the last one would get FinishLoading() called while instantiating the parent mission.
e.g.
```
npc
ship "Ship A" "Something"
ship "Ship B" "Something 2"
```
Ship A would not call FinishLoading(), while Ship B would call FinishLoading() twice.
> bugfix: Call FinishLoading for all ships in an NPC block when instantiating missions

- source/AI.cpp
Otherwise they would end up circling endlessly around a disabled target ship they had not boarded (until new hostiles appeared in system).
Refs #2972
> Ships which plunder do not act as such unless they have free cargo space

- source/MissionAction.cpp
Otherwise "you are fined \<payment\>" becomes "you are fined -200,000".
Refs #2902
> Always display a mission's <payment> substitution as a positive number

- source/AI.cpp
- source/ShipInfoDisplay.cpp
Key Press   Command
[Up]        Engage Forward Thrust (and disable Reverse Thrust).
[Left]      Turn Left.
[Right]     Turn Right.
[Down]      If Reverse Thrust installed and not engaging Forward Thrust,
engage Reverse Thrust,
else if not turning Left nor Right,
turn to the reverse direction the ship is moving to.
Behavior Changes:
- Can no longer engage both Forward and Reverse Thrust at the same time.
- Turning Left or Right, will no longer disable Reverse Thrust.
- Can Reverse Thrust while turning Left or Right.
- Engaging Forward Thrust will always behave as if Reverse Thrust is not installed.
> Reverse Thrust while turning.

- source/NPC.cpp
Instead of repeating the same line or custom fleet block, a number of times to spawn an instantiation of that fleet is used:
```
npc
fleet "stock fleet name" 4
fleet 4
variant
ship "A"
variant
ship "B"
```
vs
```
npc
fleet "stock fleet name"
fleet "stock fleet name"
fleet "stock fleet name"
fleet "stock fleet name"
fleet
variant
ship "A"
variant
ship "B"
fleet
variant
ship "A"
variant
ship "B"
fleet
variant
ship "A"
variant
ship "B"
fleet
variant
ship "A"
variant
ship "B"
```
This syntax is already used for specifying planetary defense fleet counts on map.txt.
> enhancement: NPC nodes accept numeric argument to create multiples of the same fleet

- source/AI.cpp
Ensure the ship can actually make a jump before telling it to PrepareForHyperspace. Ships that cannot make a jump but have a target system (e.g. can jump in general, just not right now) will move to the system center to speed up refueling, instead of drifting aimlessly.
> bugfix: Escorts currently without fuel to jump should not PrepareForHyperspace

- data/governments.txt
- data/hails.txt
- data/syndicate world jobs.txt
Made the syndicate target ships into self-destructing automata, imposed a penalty for failure, and added some appropriate hostile and disabled hails, thereby resolving the following issues:
- https://github.com/endless-sky/endless-sky/issues/2151
- https://github.com/endless-sky/endless-sky/issues/2268
- https://github.com/endless-sky/endless-sky/issues/2890
I also wanted add a fine on failure, but that currently doesn't show up right in the description. I have opened issue https://github.com/endless-sky/endless-sky/issues/2900 to track that.
> Syndicate Target Practice fixes

- data/governments.txt
Refs #2931 
If the player attacks Merchants in Hai space, they will have to fight against the local Hai as well.
The Hai will also defend any Merchant fleets against Pirate ships that may have been led into Hai space somehow.
Ideally the Pirate would not need an attitude towards the Hai (e.g. the attack on Merchants would be enough to make the Hai intervene, but pirates simply being present would not), but that level of provoke escalation behavior currently only exists for the player, and introducing such a mechanic would require considerable review of the existing attitude relationships, along with every mission, to ensure no unintended side effects.
> Update Pirate, Hai relationships

- source/AI.cpp
With no enemies around the escort behavior defaults to KeepStation. If they were near death mid-battle they would lose their target, defaulting to KeepStation and resulting in them just sitting there taking damage. Since they are prime targets, that behavior is suicide.
Now escorts no longer lose their target when near death.
Reference: #3004
> Fix near death escorts doing nothing.

- source/PlayerInfo.cpp
- Carried ships that are in remote systems when the player takes off will start out loaded into their carrier ship, just as they would in the player's system, rather than needing to board.
- This prevents any possible "dropped fighters" in case 1) the carrier is Stepped before the fighter is able to ask it to become its parent, and 2) the carrier is Placed in such a manner that it can jump immediately
- Ships in remote systems will recharge their shields, hull, and energy, if they have the equipment to do so, rather than starting out with whatever shields/hull they had a day ago, and 0 energy (if loading save) or their previous energy.
> Out-of-system escort tweaks

- source/PlayerInfo.cpp
If you ended up with a path in recent.txt that pointed to a non-existent file (via deleting it outside the game and not clearing recent.txt) the game would create a harmless but useless save instead of ignoring it.
ex. [df df.txt](https://github.com/endless-sky/endless-sky/files/1288686/df.df.txt)
This PR adds a Files::Exists() check to PlayerInfo::LoadRecent().
> fix loading a non-existent save from recent.txt

- source/AI.cpp
AI ships would not attempt to help any of their faction's disabled ships if the only enemy in system was disabled.
With this PR, once the danger to their faction has ceased (all enemies destroyed or disabled), they will request repairs.
> Request help when all enemies remaining are disabled

- source/Mission.cpp
470d525 ends up dereferencing an iterator to actions.end() from duplicated code and a missing .end() check. Should be fixed here while still incorporating the original intent.
> bugfix - dereferenced actions.end() iterator

- source/ImageBuffer.cpp
This patch fixes an issue where the png loader feeds grayscale png data to OpenGL as BGR data.
To reproduce, replace images/_menu/side panel.png with this image:
This image is visually identical to the one that currently ships, but since it's one-channel it appears in the game like this:
The fix is just to make sure to call `png_set_gray_to_rgb` if needed.
> Load grayscale pngs properly.

- data/transport missions.txt
The hallucinated ships weren't moving and weren't firing. Now they do.
A more generic solution could be to make "never disabled" imply that the [RequiredCrew](https://github.com/endless-sky/endless-sky/blob/899829760b9dc2fa7563d973ecb13056d3574ef8/source/Ship.cpp#L2032) is zero. Right now it seams to only imply that the [MinimumHull](https://github.com/endless-sky/endless-sky/blob/899829760b9dc2fa7563d973ecb13056d3574ef8/source/Ship.cpp#L2588) is zero.
> Fix hallucinations not moving

- data/free worlds middle.txt
A mission named "FW Northern 4.1B" is referenced here [free worlds middle.txt#L959-L969](https://github.com/endless-sky/endless-sky/blob/93979842e1bdaa023fe52dd530b8b2dee0a3ad1b/data/free%20worlds%20middle.txt#L959-L969) but is never declared. You probably wanted to reference "[FW Northern 4.2A](https://github.com/endless-sky/endless-sky/blob/master/data/free%20worlds%20middle.txt#L998)" here.
> Fix dangling mission reference in condition

- source/MapPanel.cpp
- source/Mission.cpp
Refs #3055 
- When NPCs plunder the player's ships, the respective missions whose cargo or passengers were taken are now failed.
- While in-flight, any failed missions are no longer colored as though they are able to be completed.
> Fail missions if mission cargo/passengers are stolen from the player

- source/PreferencesPanel.cpp
Refs #3054 
Also made it easier to change in the future - only ZOOM_FACTOR_INCREMENT needs to be altered.
I chose 10 so that the current zooms (100, 150, 200) are still available by scrolling or clicking. Choosing 25 would also work, but only adds 2 zoom levels.
> Add additional UI overlay zooms

- data/map.txt
Proposing change of typo in line 26712 from "The Stronghold of Flugbu was used a military base during the War of Independence." to "The Stronghold of Flugbu was used as a military base during the War of Independence."
> Typo in map.txt

- source/Flotsam.cpp
- source/Flotsam.h
- source/Minable.cpp
- source/Ship.cpp
The last box of commodities was not being jettisoned unless it was a multiple of 5, which is the maximum number of commodities per box.
Note that this will also allow players to send out more flotsam to distract pirates (select commodity, dump a quantity lower than 5, repeat).
> Fix missing jettisoned commodities

- source/AI.cpp
There are some checks that are no longer required due to the updated order of AI::Step, making personality-based actions such as Surveillance come after combat.
- If the ship's target ship is not targetable, FindTarget gives it a new one that is.
- This target ship may have left the system since being targeted on a previous iteration of AI::Step, so this must still be checked.
- Since the start of DoSurveillance checks that the ship is in-system (and staying in-system), this does not need to be checked again before performing ship-based surveillance actions. (This section existed before the checks were originally added to the start of DoSurveillance in https://github.com/endless-sky/endless-sky/commit/eb149c335b22021af6cb317a8c20ea23ce191995).
- Removed now-unnecessary `isInSystem` …
> Refactor DoSurveillance

- source/AI.cpp
- source/AI.h
- source/Ship.cpp
- source/ShipInfoDisplay.cpp
- Support fully automated ship movement for ships with afterburners but no other forward thrust mechanism.
- If no forward thrusters are installed, the displayed MaxVelocity and Acceleration values are determined by using the afterburner values. If forward thrusters are installed, adding or removing afterburners do not alter their values (since they are no longer used by default).
- Afterburner heat and energy usage are added to the ShipInfo display table.
- In addition to fuel usage, NPCs consider the afterburner's energy use and thermal output before deciding to use it (endless-sky#1819), when usage is optional. If usage is not optional (no forward thrust), these checks are bypassed.
- Consider afterburner usage whenever MoveToAttack is used (ships, asteroids)
- Consider afterburner …
> Update Afterburner Logic

- data/marauders.txt
when I reshaded the Marauders, the Leviathan's 3 variants in the GIMP file weren't exactly on top of each other, which means the hardpoints have always been off a little
since I work precisely, I did put them all on top of each other, but this caused some hardpoints to be really off, so I took like 20 minutes to fix them & figure out how to delete a fork, refork, and then PR the edit
edit:
I don't remember any other Marauders that were "resized" or anything in GIMP so I think it's fine now
> fixed hardpoints from Marauder reshades

- source/Flotsam.cpp
When I made the last commit of #2962 (57d3a7a) I introduced a bug while cleaning up the lifetime formulas I had been testing.
`count / TONS_PER_BOX` is an integer division and will produce a 0 lifetime for 1-4 ton flotsams.
Turned it into `count * (1. / TONS_PER_BOX)`, which is floating point multiplication with a one side constant.
Sorry about that. :(
> Fix partial commodity flotsam lifetime.

- source/MapPanel.cpp
- source/Mission.cpp
- source/Mission.h
- source/MissionAction.cpp
- source/MissionAction.h
With 3bfa5eee6e0a4942857e240a4614e1f2c1975bb2 players lost the ability to observe in-flight if any current missions they had that use outfit gifting were able to be completed.
This PR changes the display state of the mission in the MissionPanel view based on whether or not the player has the required outfits to perform the exchange.
For example, if the player takes a mission to mine 100 tons of Aluminum and lands in-between harvests, some of the haul is on an escort ship (potentially multiple). The only way to determine if this mission can be completed is to manually toggle through all of the player's ships and keep a running total of stored Aluminum. With this PR, the game will only color the mission in white when the player has 100 Aluminum  in ships that are present in-system.
The …
> enhancement: Visual feedback for outfit transfer missions while in-flight

- source/HailPanel.cpp
When you asked for help you had to read the text to know if the ship was really coming to assisting you.
Now you just have to glance at the grayed out help button to see that they decided to assist you.
To keep the dialog consistent in other hail attempts, it will repeat the positive reply message if it's already coming to assist you.
> More feedback in HailPanel

- source/AI.cpp
- source/Engine.cpp
In the `master` branch, I have noticed that if there is more than one planet in a system, you can land on one planet, then just before the planet panel pops up, you can click on the other planet. This makes your ship (which is _really_ small by now) fly off toward the second planet you clicked on - but it brings up the first planet's panel. 
This PR prevents this by not allowing other planets to be targeted (besides the current one) if the player is already in the process of landing.
> Prevent players from switching landing targets if they are already landing on a planet

- source/Engine.cpp
- source/Ship.cpp
- source/Ship.h
Refs #3083  
While no wormhole-like objects in the base game move far enough each day that the flagship's position is noticeably incorrect, mods do exist and the game might eventually have something like this.
> Use a wormhole's actual position instead of the previous day's position

- data/interfaces.txt
- source/MainPanel.cpp
- If a conversation, dialog, or other panel is generated while the player is dragging, stop drawing the drag box and reset the drag status.
Refs #3093
> Pop-ups cancel drag actions

- source/AI.cpp
- If the target asteroid is sufficiently out-of-reach, the mining ship selects a new minable rather than embarking on a hopeless chase.
- either double the engagement range away (1600.)
- or moving faster than the ship can
- Mining ships utilize turrets to mine, if they do not have a ship to aim their turrets at.
I updated Autofire to account for the random velocity of each weapon's projectile (which is accounted for in other aim/fire code, but was not here). I did not do any updates for RandomLifetime, as those changes are being addressed in #1894. 
There is a fair bit of duplicated aiming code in AimTurrets now, but I'm not sure of the best way to reduce it, as there are small details specific to each implementation (target asteroid, aim straight ahead, sweep the sky, or aim at the best …
> Refactor Mining Logic

- source/OutfitterPanel.cpp
- source/OutfitterPanel.h
- source/ShipyardPanel.cpp
- source/ShipyardPanel.h
- source/ShopPanel.cpp
- source/ShopPanel.h
Pressing `r` or `u` will uninstall the selected outfit and place it in to your cargo hold, if there is sufficient room. If there is not sufficient room for the outfit in cargo, it will be sold.
Excess ammunition that needed to be stored but cannot fit in the remaining space will be sold.
As expected, the normal modifier keys work to multiply the quantity moved to cargo.
This makes it possible to move an outfit installed on a ship directly into cargo, or to more simply sell an outfit from a ship when you have some in cargo that you want to keep (uninstall once + sell once vs sell every copy in cargo, then the one from the ship, then buy back into cargo).
> Press R or U in Outfitter to uninstall selected outfit directly to cargo.

- source/Engine.cpp
I can see when all jumps are done (minimap disappears).
It is easier to cancel a wrong jump (minimap is visible longer).
I also wanted to show the travel plan in the minimap but that is better done after some refactoring, which I'm not comfortable in doing right now.
> Also show minimap while preparing to jump.

- source/AI.cpp
CanLand also checks politics, and the player may be able to bribe for clearance.
> Use IsAccessible rather than CanLand to ID unalterably unlandables

- source/AI.cpp
- source/DistanceMap.cpp
- source/DistanceMap.h
- source/Planet.cpp
- source/Planet.h
- source/System.cpp
An escort traveling to the parent ship's system could get stuck when it encountered two consecutive system where it could not refuel because it only checked if it had enough fuel for the next system.
Now it checks how much fuel is required to reach the next refuel stop and uses that to decide if it should refuel in the current system.
> Enhancement: Consider next refuel stop when traveling to parent ship's system

- source/AI.cpp
- source/Engine.cpp
This PR represents a big change in the way that mission NPCs behave - up until now, every mission NPC has had the parent ship of the player's flagship (unless `personality uninterested`), which means that the NPCs have always wanted to route to the player's system, and follow the player's ship around in-system. With this PR, only a single ship from a fleet specified in an NPC definition will behave in this manner, and the rest of the ships in that NPC block will follow it. This means the ships will travel as a fleet - jumping together - rather than an every-man-for-itself race to the the player's side.
(edited per comments below: )
The ship to be made the fleet leader of each NPC block is chosen on as the first ship specified, consistent with flagship assignment for regular NPC fleets …
> Mission NPCs use fleet movement behavior to travel in groups

- source/AI.cpp
Orders::KEEP_STATION is currently unused (never set by a command issued by the player), but code to handle it is implemented.
This PR changes the order given when right-clicking a non-hostile ship from `Orders::GATHER` (which calls `AI::CircleAround`) to `Orders::KEEP_STATION` (which calls `AI::KeepStation`).
With this change, telling an escort to follow a ship will result in your escort matching that ships' orientation, position, and speed - which is ostensibly more of a "follow" behavior than circling.
> "Follow" order uses station-keeping rather than circle-around

- source/PlayerInfo.cpp
This is parallel to the "net worth" auto condition, and allows missions
to require you have >=, <, etc. a certain credit balance. This is
necessary for negative payment missions (missions where you pay a bribe,
etc.) to be handled correctly if you can't afford it. Without this, they
just don't appear. With this, you can create a mirror 'blocking' mission
if you don't have enough money.
**Context:** I _promised_ myself I'd finish a minor story without requiring any changes to the code. But a sideline to the first mission is the ability to bribe someone for more information on the mission. If you can't afford this, the mission doesn't appear at all – without explanation. With this auto condition, I can do the following:
<details>
<summary>Mission snippet</summary>
```
mission "Syndicate …
```
> Create an auto condition for your credit balance

- source/Command.h
- source/Ship.cpp
This small PR adds a soft warning for each weapon (gun or turret) hardpoint beyond the first 32.
For ship definitions and for ships in savegames.
Reason: Command.h / Command.cpp only support the first 32 weapons to actively fire because a 32 bit mask is used there.
Relates to #2473.
> minor enhancement: soft warning for more than 32 hardpoints

- source/AI.cpp
- source/AI.h
- A ship which reaches the position it was sent to changes its MOVE_TO order into HOLD_POSITION.
- All HOLD_POSITION orders now include a point definition.
- When taking off from a planet, escorts will return to where they were told to HOLD_POSITION rather than freeze upon takeoff.
- If hit by an explosion and "dislodged", escorts will return to their original point. Fighters and other light ships will not be permanently scattered if an enemy ship explodes in close proximity.
> Move_to & Hold_Position orders convert based on distance to position

- source/LogbookPanel.cpp
Pressing Up while at the top entry will select the bottommost entry.
Pressing Down while at the bottom entry will select the topmost entry.
Right now, the logbook does not wrap its scroll. This seems weird, considering every other interface with selectable elements does wrap. This PR adds scrolling wraparound to the logbook.
> enhancement: Logbook selection wraps around

- source/Engine.cpp
- source/Flotsam.cpp
- source/Flotsam.h
The leftover units would vanish when only part of the flotsam fits the
cargo hold. This means that you can lose cargo just by transfering it
to another ship of your fleet (jettison cargo, then guide other ships to
the flotsam).
This commit changes that behaviour, only removing the flotsam when there
are no more units. Only 1 ship can collect from the flotsam on each step.
> Keep partially collected flotsam

- source/CaptureOdds.cpp
- source/CaptureOdds.h
- source/Government.cpp
- source/Government.h
Adds 2 new optional attributes to governments: `crew attack` and `crew defense`. This would be the strength per crew member of that government's ships. (If one or both attributes are omitted, the default values of 1 for attacking and 2 for defending will be used.) This allows one to create alien governments whose ships are easier or harder to capture than normal.
> Allow modders to override default crew attack/defense values per government

- source/AI.cpp
- source/Ship.cpp
- source/Ship.h
Use reverse thrust if its capability exceeds:
- the target's ability to close the distance
- the current closing rate of the target
- the ship's forward thrust capability
Otherwise, turn around to use the better thrusters.
Ref #2716
> Simple logic to determine if missile boat AI will reverse or turn around

- data/tooltips.txt
- source/OutfitInfoDisplay.cpp
- source/Ship.cpp
This PR adds a `cloaking heat` attribute for further customization of outfits, (specifically, cloaking devices).
Requested by @TheUnfetteredOne
> Add cloaking heat attribute

- source/NPC.cpp
Hey, so the way I did e6e7c0ae11039c6dc00bd9682fffe7b6bac5f095 originally was a bit more complicated than necessary: `mustLiveFor` isn't needed.
The gist was: if you need to do something to an NPC (`succeedIf`) that you haven't done (`~it.second`) and that requires them be alive (`mustLiveFor`), then if they got destroyed the mission has failed.
Practically, an NPC has to be alive for anything you need to do to it. The only reason I made `mustLiveFor` was for if what you needed to do to the NPC was kill it, but I hadn't thought through that that really isn't a problem.
> Simplifying NPC::HasFailed by cutting mustLiveFor

- source/NPC.cpp
Refs #2855 
NPC::Do calculates whether a given ShipEvent causes success or failure by comparing the value of HasSucceeded before and after recording the ShipEvent.
- The previous implementation inherited knowledge about the ship's Disabled status from the ship itself, and not from the recorded information.
This meant that `evade` missions could never determine that the incoming ShipEvent::DISABLE was the one that allowed for success criteria.
- Learning of a new ShipEvent::ASSIST will appropriately remove a ship's known ShipEvent::DISABLE flag.
- It should now be possible to `evade` a ship which is `never disabled` by destroying it (in addition to being in a different system)
This PR resolves all the issues I mentioned in 2855
- `npc evade` dialogs are shown when all required evaded npcs …
> Fix NPC HasSucceeded() to use only recorded ShipEvent information

- source/Dialog.cpp
Refs #2869 
If Esc is not the "Show Main Menu" key, it will close the dialog
- Closed dialogs
- Choose "Cancel" or "Decline", if possible
- Choose "OK" for information-only dialogs.
- If Esc is the "Show Main Menu" key (default), that functionality has priority (e.g. the player can save when being offered a mission dialog).
> Dialogs properly respond to Esc or Ctrl+W (as is indicated by documentation)

- source/DistanceMap.cpp
- source/MapPanel.cpp
Refs #2936 
- Removes incorrect/vague MapPanel error message when the player's flagship has no hyperdrive/jump drive installed.
- Wormhole-only travel plan creation is possible for the player when no hyperdrive/jump drive is installed.
If a player has no hyperdrive or jump drive installed, this PR will enable them to make appropriate & allowed travel plans that use only wormholes.
The error message shown when attempting to route to an unrouteable system now properly indicates if you know how to get to that system but do not have the correct equipment which makes said travel possible, or if you actually do not know how to get to that system.
> Update allowed travel plan creation conditions

- source/GameEvent.cpp
- source/GameEvent.h
- source/PlayerInfo.cpp
Refs #3110 
- Adds ability for a game event to give the player knowledge of a system or planet.
- Visit actions occur after any 'unvisit' actions in the same event
- Update the structure of GameEvent::Load
> Support 'visit' & 'visit planet' in events

- source/ShopPanel.cpp
Refs #3115 
- Ensure only ships which can appear in the Shipyard/Outfitter are selected.
- If the currently selected ship is not in the new selection of ships, update it.
> Fix ships selected by number keys in Shipyard/Outfitter

- data/pirate jobs.txt
Under certain circumstances, or when using mods, it's possible to get a very negative rep while still too weak to handle the bounty hunters.
> Add a combat rating check to "Hunted by State" missions.

- source/ShopPanel.cpp
- source/ShopPanel.h
~~In the outfitter, when you have an outfit selected and choose a different ship it will auto-scroll the outfit description back to the same place it was relative to the screen.~~ In the outfitter, when you have an outfit selected and choose a different ship it will keep the selected outfit in the same screen height.
This is needed because when a new ship is selected it can add or remove outfits before the selected outfit, causing the selected outfit to be placed in a different position.
It is also able to auto-scroll down and tries to make the ~~outfit~~ image visible.
You can deselect the ~~outfit~~ item and cancel the auto-scroll by clicking on other areas of the main panel.
> Use selected ship/outfit as scroll reference.

- source/AI.cpp
This makes them behave more like the player. They're not total jerks though - they still respect cargo space limits.
This will be useful for any missions that offer "competitors" to the player, if the player is tasked with collecting items from minables.
> Mission NPCs ignore mining time/count limits

- data/pug.txt
- source/GameData.cpp
- Wormhole "planets" are given a system, but unless also defined with a `planet` entry, would not pass GameData::CheckReferences until the wormhole was linked to another system
per #404 wormholes with no `planet` definition are not drawn on the map, so until #2601 merges, the link to the pug galaxy will be drawn (if one revisits it, as it will then be marked as visited).
refs #3137
> Add "Pug Wormhole" planet definition

- source/Engine.cpp
Other Engine.cpp updates: 
- Only send ShipEvent::DESTROY when the ship is destroyed (e.g. landing and forget removals do not generated events).
- Use cached variables where sensible or already defined.
> Do not draw the flagship if it is destroyed

- source/Mission.cpp
For planets which are only fully defined after certain GameEvents (The Eye), it is possible that the game attempts to obtain the government of their system. Since these planets are not in a system yet, this would generate a segfault due to an unhandled nullptr use.
Since Planet.cpp has several existing uses of `GetSystem` without checking for nullptr, I opted to perform this bugfix for #3155 in the function call that only occurs when the player lands, and only if missions that use destination or stopover LocationFilters are picked to offer, rather than in the function that is called in-flight by countless NPCs.
> Prevent matching LocationFilters to planets that have no system

- source/OutfitInfoDisplay.cpp
- source/OutfitterPanel.cpp
- source/Ship.cpp
Refs #3147 
The fix is to not combine the `const char *` value `it.first` and `':'`. Previously, `it.first` was a `std::string`, but after 595d2e8557489ae4549e42e3eb42a5ac7eecd04d it became `const char *`. Due to use of `auto` for the iterator `it`, the pointer to char was kept, rather than converting to a string for display / use.
Summary:
- Change `auto` to the type `pair<string, double>` when `it.first` is to be used as a string
- `push_back` to `emplace_back`
- Simplify display of per-second values
- Omit per-second values if reload = 60 (i.e. per second == per shot)
- Separate non per shot / per second values from values which should be printed as per shot / per second
- Addition of new damage types no longer requires updating the `isContinuous` offset
> Fix Outfitter Attribute display bug

- source/Body.cpp
- source/Body.h
- source/Ship.cpp
Refs #3183 
Ship::Carry sets the fighter's system to nullptr, clearing the Ship class variable `currentSystem`.
Ship::Move sets ships with no `currentSystem` as needing removal
Thus when a ship first launched, it would not be marked for removal, but once it boarded its parent, it would be.
> Fighters that are launched should not be marked for removal

- source/PlayerInfo.cpp
Fixes crash when you create a new player with the preference "Rehire extra crew when lost" enabled.
References: #3086 #3089
> Only rehire extra crew when the player has a flagship.

- data/map.txt
Appart from fixing a mistake, the description misleadingly lead to
believe that the mantle of a planet is liquid, which is not the case.
> Modified description of Sek Alarfarat

- source/AI.cpp
- source/Ship.cpp
The boarding approach changes the ship angle, velocity, and position artificially (no engines). It is activated when you are close enough and slow enough.
After activating it, you can become too far away by selecting another target and you can become too fast by getting hit. With this commit the boarding approach will be temporarily suspended until you get close enough and slow enough again.
> Suspend the boarding approach when too far away or too fast.

- data/hai ships.txt
Reference: #2880 
I tried to follow the advice given by @endless-sky on making ship descriptions:
>In general, I don't mind making ship descriptions wordier for the sake of adding new lore or funny or interesting information, but expanding the description just to tell the player things they can see easily from the stats (like how many turret mounts it has, or the fact that it has a lot of cargo space) doesn't make sense to me.
I feel that I did a fair job, but everyone else can be the judge of that.
> Expanded the descriptions of the 4 main Hai ships

- source/PlayerInfo.cpp
- Check was added in 03a9a089df3e9440e784604de0c80e8365a447be, when the fine action did not check if the player was freshly loaded.
- Check was deprecated by 2866bcf1c65abd90db07ffb7e470c2f73bf9485f
I originally made this commit on #3070 but I'm not sure how soon that will be merged.
Relevant comment:
>When I was developing this (and ships were shown while landed), I couldn't figure out how IsEnemy was returning false for "known" hostiles (which led to using both "IsEnemy()" and "rep < 0" checks). While swapping to use System::Danger in the map coloring scheme, I noticed this issue on a massive scale - all because I'm landed on Greenrock, which resulted in auto-bribing the Pirate government upon game load.
> Remove deprecated bribe action

- source/PlayerInfo.cpp
- source/PlayerInfoPanel.cpp
Refs #3202 
Ctrl+Shift+Up -> move the selected ships up one space
Ctrl+Shift+Down -> move the selected ships down one space.
Tweaked the position selection for PlayerInfo::ReorderShips so that the direction of movement indicates which side of the position is moved to:
- If moving up the list, current behavior (first selected ship moves to the targeted index)
- If moving down the list, move one more (the ship at the targeted index is moved ahead of the first ship.
This altered behavior means that the selected ship can be dragged (or arrow-keyed) to the end of the list, and not just the position before it.
As with drag-moving non-adjacent ships, they are all grouped after the movement.
> Ctrl-Shift-Arrow key moves selected ships on PlayerInfoPanel

- source/AI.cpp
- Hyperspacing ships can still (de)cloak and autofire weapons, but have no ability to change their movement strategies.
- Overheated ships are effectively disabled, but IsDisabled explicitly does not return true for a ship which is solely overheated (so the radar can blink their pointer properly)
- Stranded/Disabled ships shouldn't ask overheated or hyperspacing ships for help since that help may be a long time coming.
This should cut down on a bunch of repeated-yet-unnecessary movement routing checks (e.g. a ship picked a destination and is already jumping to it - no need to keep checking if it should refuel, if it can get there, etc.).
> Overheated/Hyperspacing ships don't need to decide on actions

- data/outfits.txt
The dedicated Tactical Scanner gives 100 * sqrt(32) range (565),  while this multipurpose outfit gives a tactical range of 300. Increased the price based on the new ability, ~144000 / sqrt(32) * sqrt(9)
I don't see any reason for the Navy to care about what asteroids contain (assuming IED asteroids isn't a thing yet), so I did not feel it necessary to include "asteroid scan power."
> Surveillance Pod has some tactical scan power

- data/weapons.txt
Changed "Gatling Gun Ammo" value to 4 each, because 25% of 4 is 1 (and 25% of 2 is 0).
> Tweaked gatling gun ammo price.

- data/hails.txt
Since case sensitivity is important, this set of hostile Syndicate hails isn't currently being used.
> Fixed a phrase typo

- data/ships.txt
Right now their high minimum crew complement makes their daily cost is too high given their capabilities. This should make them more attractive to players in early-to-mid Tier 1 gameplay. This fixes https://github.com/endless-sky/endless-sky/issues/1627
> Reduce Bastion and Splinter minimum crew complements

- source/Font.cpp
- source/OutlineShader.cpp
For samplers, Mesa3D expects the argument to be int.
It was being sent as uint.
Reference: #3292
> Fix binding of sampler tex.

- source/AI.cpp
- Previous behaviors did not consider blast radius for non-homing weapons (such as Heavy Rockets), or trigger radius at all.
This PR should help any NPC that uses Nuclear Missiles or Heavy Rockets, or any plugin weapon that has a blast radius and a trigger radius.
As with the existing check, this is a **simple** check that assumes
1) The target does not approach the firing ship
2) The firing ship does not follow the projectile to the target
These assumptions do not currently hold for Heavy Rockets, and are in general dependent on the other weaponry installed (e.g. NM's + Meteors will result in these being valid, but NM's & Heavy Lasers will not). This firing check is basically verifying that the projectile will not immediately explode and harm this ship.
A different PR that alters …
> Consider both trigger and blast radius when firing all weapon types

- source/AI.cpp
Instead, they attempt to keep the minimum safe distance (blast radius + trigger radius) between them and their target ship. 
The behavior switch (close towards target vs start distancing) occurs at a point larger than the safe distance since the ship requires some time to turn away. I opted for 125%, which is (50 + 30) * 1.25 = 100px for Heavy Rockets, and (150 + 30) * 1.25 = 225 for Nuclear Missiles.
This PR (even without coupling with #3300 ) should greatly improve the AI behavior for the "Hawk (Rocket)" and Captain Nate NPCs, along with other NPCs using non-safe, exploding weaponry.
> Ships with non-safe blast radius weaponry do not follow the projectile

- data/interfaces.txt
- source/Engine.cpp
Refs #1825 
For this screenshot I set the wrap width to be really short, in order to illustrate the wrapping.
> Wrap messages when drawing them to prevent overflow

- data/weapons.txt
Reference: #3287 
* Submunition lifetime: 20 -> 24
* Range: 528 -> 624 (96 pixel / 18% increase)
* This makes the Proton Gun's range about 83% that of the Particle Cannon instead of the previous 70%.
* Submunition shield damage: 8 -> 8.4 (5% increase)
* Shield DPS: 180 -> 189
* Submunition hull damage: 6.6 -> 7 (6% increase)
* Hull DPS: 148.5 -> 157.5
An overall 5.5% increase in damage.
The increased range and slightly increased damage to the Proton Gun makes it a more viable alternative to the Plasma Cannon and its powerful heat damage or the Particle Cannon and it's massive range and substantial hit force, and the inaccuracy of the submunitions makes it an interesting weapon to use at range but a very powerful weapon up close.
> Slightly buffed the Proton Gun

- data/events.txt
- data/free worlds intro.txt
- data/free worlds start.txt
This is a resolution to #3317 , as an alternate solution to #3318 
This change causes the player to become hostile with the Republic after "FW Prisoner Parole" is completed and while "FW Prisoner Parole 2" is still active.
The event timer in "FW Prisoner Parole" is extended to 8 days, as the mission can still be successful by the end of the 7th day (on the deadline) but the hostility event was triggering at the start of that day.
The -10 reputation setting in mission "Defend Sabik" is removed, as it is now redundant with the -10 setting in the event its self.
The -1000 reputation setting in mission "FW Prisoner Parole 2" still exists as it happens after and supersedes the event.
> enable "start of hostilities" to trigger Republic rep penalty

- data/coalition jobs.txt
- data/free worlds checkmate.txt
- data/free worlds epilogue.txt
- data/free worlds intro.txt
- data/free worlds middle.txt
- data/free worlds reconciliation.txt
- data/free worlds side plots.txt
- data/free worlds start.txt
- data/hai jobs.txt
- data/hai missions.txt
- data/kestrel.txt
- data/remnant missions.txt
- data/transport missions.txt
- data/wanderers middle.txt
- data/wanderers start.txt
- data/wanderers.txt
- source/Mission.cpp
Kept it simple so that any desired phrasing can be used:
For a mission with waypoints in Kornephoros and Wei, this substitution would yield:
`"Scout the <waypoints> systems."` - > `"Scout the Kornephoros and Wei systems."`
`"Scout <waypoints>."` -> `"Scout Kornephoros and Wei."`
> Add text substitution for <waypoints> in missions

- data/free worlds start.txt
Due to the temporary ceasefire event applying to all FW-Republic conflict, these escorts can properly belong to the Free Worlds government rather than the player's government, without negatively impacting mission completions.
> Swapped two FW NPCs to Free Worlds instead of Escort

- data/weapons.txt
Missed adding a required crewman and fixed a grammar error in the description.
> Fixes for the Proton Turret

- data/free worlds middle.txt
Rather than let these NPCs use the player government, they properly belong to the Free Worlds and have the `escort` personality tag so they are still shown as your "convoy."
Spotted this automatic use of the player government when looking over the mission referred to in #3354 
I highly doubt this PR would resolve any underlying issue there.
> Added a government specifier to a set of ships that did not have one

- source/NPC.cpp
- source/Ship.cpp
Refs #3349 
In addition to making sure that random NPCs emit ShipEvent::ASSIST (they already emitted ShipEvent::BOARD), adds ShipEvent::BOARD and ShipEvent::ASSIST to the list of ShipEvents that only count toward NPC completion when performed by the player.
Previously, the player could have a mission that required boarding an NPC, and it would be completed if any ship completed the task (e.g. a pirate job to take some cargo from a Merchant, and a random pirate boarded the ship before the player could).
> Allow non-player ships to emit ShipEvent::ASSIST when repairing ships

- source/Ship.cpp
- source/Ship.h
- Swapped the Outfit pointers to Weapon pointers for the associated ship firing methods
- Print warning messages for incorrect armament specifications:
- guns positioned in turret hardpoints
- turrets positioned in gun hardpoints
- non-weapons positioned in any hardpoint.
An example warning message for a really messed up ship definition:
> Change Outfit to Weapon & warn on incorrect armament specifications

- source/CargoHold.cpp
- source/Mission.cpp
Refs #3354 
Commit https://github.com/endless-sky/endless-sky/commit/8e0d8167403de689132a08406b9d7f3211beebf4 ended up generating 0-quantity references to outfits, commodities, and passengers.
This PR adds a check for a non-zero passenger quantity before failing a mission, and also takes steps to prevent creating a 0-quantity entry *at all* for commodities, outfits, and passengers.
See https://github.com/endless-sky/endless-sky/issues/3354#issuecomment-349132704 for a destroyed ship's CargoHold instance, on master and before the named commit above. As of this PR, the original behavior is restored.
Test save located [here](https://gist.github.com/bluss/6587944bf49386a12ba1f4ea70e85ad6) courtesy of   @bluss
> Avoid creating a passenger reference when 0 passengers are transferred

- source/Ship.cpp
Refs #3348 
- Directly clear the carried ship's target system and target StellarObject upon boarding its parent.
- Add a `nullptr` check for `currentSystem` in Ship::IsReadyToJump and Ship::JumpFuel
> Carried ships forget their target system/object when reboarding

- source/Ship.cpp
- 2633668c9f9c5933cbf8f0a98c855ab7b9345d20 made it so that every ship that FinishLoading is called for considers itself not disabled - even if its current hull and shields value mean it should be disabled.
> Revert automatic assertion in FinishLoading that a ship is not disabled

- source/AI.cpp
While the parent won't ask its carried escort to help it, that escort would discover it has a disabled parent and attempt to assist it when combat ends, or when its own health is low enough that it has no combat target.
This PR removes that behavior, so that only non-carried ships will consider assisting their disabled parent.
> Certain ships should not auto-assist their disabled parent

- source/ConversationPanel.cpp
- source/ConversationPanel.h
- source/Engine.cpp
- source/Engine.h
- source/MainPanel.cpp
- source/MainPanel.h
- source/UI.cpp
- source/UI.h
Refs #3005 ,  #3129 
- Handling ShipEvents can result in new UI elements.
- Only one UI element should be created and displayed to the player at a time (i.e. do not display a dialog and the BoardingPanel simultaneously).
- Callbacks from one UI element from a given ShipEvent may result in status changes that should influence other UI elements created from the same ShipEvent (e.g. if a mission conversation offered upon boarding an NPC results in that NPC's destruction, the player should not be able to plunder said NPC).
This PR does not attempt to fully address the existing issues with boarding missions (as that is done in #3005 ). It does add one tiny bit of #3005, to check that the player has space for a mission offered in space.
This PR does not implement the needed callbacks to the NPC …
> Implement a ShipEvent queue to allow delayed ShipEvent handling

- data/interfaces.txt
- source/MapDetailPanel.cpp
- source/MapPanel.cpp
- source/MapPanel.h
- source/Planet.cpp
- source/Planet.h
Splitting the MapPanel refactoring out of #2601 so that #2601 can deal only with adding functionality re: invalid travel plans and not also rewrite a good chunk of `MapPanel`
- Improve mod coloring support via expanded use of interfaces.txt:
- Switch the minimap from a hardcoded position to an `Interface`
- Use travel plan colors from interfaces.txt
- Use System name, link colors from interfaces.txt
- Move the increment of `step` from the `DrawMissions` method to the base `Draw` method
- Add comments to `DrawMiniMap`, `DrawTravelPlan`, and `DrawWormholes`
- Used and updated `MapPanel` constants
- Draw the Travel Plan after wormholes, since wormholes by default have non-zero alpha.
- This removes the small, dark purple centerline from drawn travel plan routes that use wormholes
- Adds …
> Refactor MapPanel's Draw___ methods

- source/Mission.cpp
- source/Mission.h
- source/PlayerInfo.cpp
- source/PlayerInfo.h
- Use StepMissions() to handle changes to active missions - recording NPC self-destructs, completions, failures, etc.
- Planets for which mission clearance has been given (or if infiltrating) will not fine the player ( Refs #1452 )
> Refactor PlayerInfo::Land

- source/AI.cpp
Refs #2147, fc785a18f37f3a1ac6a39bdd84d916d67268c4ba
- Switched Outfit * to Weapon * and updated variable names
- Updated the includes to reflect the used classes.
With this, while ships are being told to prepare to jump, they will not fire weaponry which imparts a firing force on their (e.g. could cause them to no longer be jump-ready). This behavior properly propagates to mission NPCs that would jump with you.
> AI does not autofire weapons with firing force if preparing to jump

- data/coalition missions.txt
- data/coalition outfits.txt
- data/outfits.txt
- data/remnant missions.txt
- data/remnant outfits.txt
- data/wanderer outfits.txt
- source/OutfitterPanel.cpp
Reference: #2177
The licenses are the "materialization" of the log entries that mention getting permission to purchase something, so the descriptions are copies of the log entries or are based on them.
**Changes in this commit**:
- outfitter shows the licenses you own when there is an outfit for them.
- new outfits "Militia Carrier License", "Coalition License", "Wanderer Outfits License", "Wanderer License", "Wanderer Military License", and "Remnant License".
- new matching log entries for "Coalition License" and "Remnant License".
> Show licenses in outfitter

- data/transport missions.txt
- data/wanderers middle.txt
- data/wanderers.txt
Changed any instances of `Travel(er/ed/ing)` being spelled with two `L`s to one `L` to match the rest of the uses of the word in game.
Reference: https://github.com/endless-sky/endless-sky/pull/3298#discussion_r158734115
> Typo fixes

- source/ConversationPanel.cpp
- source/GameEvent.cpp
- source/PlayerInfo.cpp
- source/PlayerInfo.h
Refs #3196 , https://groups.google.com/d/msg/endless-sky/_XAgbcSP6Is/t-jKZSazBQAJ, 
- Fixes issue where changes to the stored government reputations were not reflected in the current political landscape when the changes were performed via conversation `apply` node.
> Add missing reputation serialization to conversation ConditionSets

- source/AI.cpp
If there are a significant number of ships in-game (either due to the player accepting many NPC-creating missions, such as bounty hunting, or simply having a massive fleet https://github.com/endless-sky/endless-sky/pull/2788#issuecomment-352947338), AI::DoScatter can become a bottleneck as it currently checks against every ship to determine if there is a similar movement profile.
This PR flags the check for a future refinement, while also adding a simple preliminary check that the two ships are in the same system.
> Update AI::DoScatter to ignore out-of-system ships

- endless-sky.appdata.xml
Resolves #3453
Resolves #3461
I've opted to not to rename the desktop file and instead add the `<launchable>` tag to associate the AppStream data with the desktop file. An alternative approach is to remove/not add the `<launchable>` tag, and instead rename the desktop file to match the AppStream ID (i.e. `io.github.EndlessSky.endless-sky.desktop`).
Relevant part of the AppStream spec: https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html
> Update AppStream file to standardize ID and add version, release date, and changelog information

- source/AI.cpp
To take back an order like "gather" or "focus fire" you issue it again.
When one of your ships is unparked in another system it will first travel to your system. While it is traveling, orders that require a target could be given but not taken back.
> Fix not being able to take back orders that require a target

- source/MissionPanel.cpp
This allows you to know which of the missions has the system as a waypoint or has a system planet to land on.
> When you click a system in the map mission view, iterate through all missions that involve the system.

- source/MissionAction.cpp
- source/MissionAction.h
**Update:** lot of great discussion below, but for newcomers: most of it's, I think, talking about other ways this could be extended (in a different PR). As of 10/05/17 I'm still suggesting this PR is merge-worthy and merge-ready, as a starting point if nothing else.
_____________________
With this PR, instead of only being able to write (in an mission's `on` clause)
`require <outfit>`
to always require at least one copy, you can now also write
`require <outfit> 3`
`require <outfit> 0`
respectively requiring at _least_ 3, or _exactly_ 0. (0 is the only one that will look for an exact match: any other number is happy with at least that many.) You can still use the existing syntax which will require at least one copy.
`outfit <outfit> [<number>]` is completely unchanged: it will still …
> require <outfit> can require a specific number, or specifically zero

- data/fleets.txt
- data/map.txt
Added some more fancy and passenger-oriented ships to the fleets that hang around Paradise planets, to make that region of space feel busier and richer--full of wealthy tourists, busy killer suits, and spoiled teenagers racing Flivvers.
> Fancier ships in paradise

- data/drak.txt
- data/kestrel.txt
- data/marauders.txt
- data/wanderer ships.txt
- Simplify definition of the Kestrel and its variants
- Simplify definitions of Marauder variants
- Simplify definition of the cloaking Archon
- Simplify definition of the Deep River variants
With these changes, plus the Doombat change from earlier, proper usage of `add attributes` is conveyed to any content creators that prefer to learn from existing examples, and not just from reading the wiki (where `add attributes` should get an entry, in the Variants header: https://github.com/endless-sky/endless-sky/wiki/CreatingShips#variants).
> Use add attributes

- data/conversations.txt
- data/pirate jobs.txt
- source/GameData.cpp
- Fix incorrect references to opposing forces (e.g. "militia" used where it should be "Navy")
- Add unpaid variants of the defense missions
- Use stock conversations to hold the `on offer`
- Add reference checking for stock conversations
> Update Pirate planetary defense missions

- source/MissionAction.cpp
- source/PlayerInfo.cpp
- source/PlayerInfo.h
Refs #3167 
- Adds a "BasicCallback" to enable conversations that come from non "on offer" conversations to force the player to depart the planet.
- Guards setting "shouldLaunch" to true while in flight, as a boarding/assisting mission could otherwise set this and cause odd behavior on the next landing.
I didn't extend this callback to the conversation started by completing an NPC since the player is never on a planet when they "complete" an NPC.
> Enable any mission conversation to require the player to launch

- source/Mask.cpp
- source/Mask.h
- source/Ship.cpp
- source/Ship.h
- source/Weapon.cpp
- source/Weapon.h
- To mitigate the damage falloff for weapons with a trigger radius, a multiplier based on the ratio of trigger and blast radius is used.
- For a weapon with 0 trigger radius, the damage will range from 100% at the center, to 25% at the edge of the blast radius.
- "advanced" weaponry can define if it is not damage-scaled.
Refs #1630, #2529, #3275 
As of d400956, the denominator is chosen to vary with distance such that it does not immediately plummet, but rather gently plateaus before decreasing after ~40% of the blast radius:
This can be changed to a more aggressive profile (see discussion in #2529 ).
This change is best combined with an "Avoid" behavior in the AI that would seek away from danger (be it an exceptionally strong ship, or a potent explosive), but they are separate issues and …
> Weapon blast strength decreases with distance from blast

- source/AI.cpp
- source/AI.h
Refs #2256 , 
There were two ways to perform the check in the new `Has()` method:
1) loop every ship in the `actions` map, and check if their government is the same as the ship performing the targeting check, and then if they have been the target of the event in question
2) Add a map which stores this information directly
I went with route 2 as it is logically simpler to understand, and requires no loops in the new method.
The specific value of the prioritization could be tweaked. I wanted it to offset the deprioritization caused by removing all weapons from one's ship, but it's possible this value will result in armed ships that plunder being excessively targeted by other members of the boarded factions. However, IMO this is a warranted side-effect of boarding and (and likely destroying) …
> Boarding a faction increases the chance of being targeted by them

- data/transport missions.txt
Because I don't think this is intended:
> Asteroids should be "inscrutable"

- source/Engine.cpp
Seems a bit odd that we can't visualize the realtime data from our player-owned ships just because they're out of range.
> Always show tactical information if targeting a player-owned ship

- source/LocationFilter.cpp
- source/LocationFilter.h
- source/Mission.cpp
- source/Mission.h
- source/NPC.cpp
- Support choosing a random system or planet from a given location filter outside of just mission instantiation
- Remove duplication (albeit there isn't much yet)
(This will be useful for #2990 or another PR that adds travel instructions to mission NPCs.)
> Move PickSystem and PickPlanet from Mission to LocationFilter

- source/MainPanel.cpp
Because if you've already engaged your hyperdrive, you probably figured out how to jump to another system.
> "Lost" help should not appear while you're in the middle of hyperspacing to another system

- source/AI.cpp
Since `commodity` is a reference, the value `commodity.second` is changed by the call to Ship::Jettison.
Example using the code in `master`:
`toDump` = 15
`commodity.second` = 20 -> `min(20, 15)` = 15
The ship jettisons 15 tons (`commodity.second` is now 5)
`toDump -= commodity.second` -> `toDump` is now 10 instead of 0.
With this PR, the ship will only jettison 15 tons, instead of 15 tons, plus 10 tons, plus perhaps more
> Appeasing ships do not overdump commodities

- data/events.txt
Currently:
* `event "initial deployment 1"` (lines 150--254) adds Barb to Syndicate Basics shipyard and X1050 to Syndicate Basics outfitter
* `event "southern carriers 1"` (lines 516--529) adds Barb to Syndicate Basics shipyard and X1050 to Syndicate Advanced outfitter
* `event "southern carriers 2"` (lines 531--559) adds Barb(Proton) to Syndicate Basics shipyard and X1050 to Syndicate Basics outfitter
In other words, the Barb and X1050 are currently added twice. This proposal removes them from the first event, because their occurence there is probably a leftover which ought to have been removed; it doesn't make sense to add the X1050 to the Basics outfitter long before it's added to the Advanced outfitter.
> Removed unnecessary Barb and X1050

- data/engines.txt
The current description of the "X5200 Ion Steering" describes it as “standard equipment for Republic cruisers and carriers”. However, none of the Republic ships nor any of their variants actually use a X5200, therefore the description is clearly wrong. This patch rewrites the text to something more generic.
> Corrected X5200 description

- endless-sky.appdata.xml
The AppStream ID I recommended in https://github.com/endless-sky/endless-sky/pull/3455 reflected an immature understanding of the nuances of how AppStream interacts with DBus and what characters are acceptable. Since then, I was contacted by the AppStream and DBus maintainers who set me right, leading to [a formal change in the spec](https://github.com/ximion/appstream/issues/162).
The bottom line is that hyphens and spaces should always be replaced with underscores, so Endless Sky's optimally-correct Appstream ID should be `io.github.endless_sky.endless_sky`
> Correct AppStream ID to conform to latest version of the AppStream spec

- data/interfaces.txt
I accidentally included commas when I moved these to user colors.
> Remove commas from color specifications

- source/LoadPanel.cpp
- source/MainPanel.cpp
- source/MapPanel.cpp
- source/MapSalesPanel.cpp
- source/MenuPanel.cpp
- source/OutfitterPanel.cpp
- source/ShopPanel.cpp
Double `using namespace std;`
Forward declaration of `class Sprite` in the .cpp when the .cpp already has `#include "Sprite.h"`
> Update needed declarations

- source/AI.cpp
- source/AI.h
- source/Ship.cpp
- source/Ship.h
Summary
- Bugfix to `personality swarming`
- 55ec12b46883cb2540e5b2148b7edda46e5cc601 / #2828 moved calls for target seeking and automatic firing above personality behaviors (so that ships performing those behaviors would still fire at hostiles if the hostiles were near, even if not being actively attacked)
- AI::FindTarget would change the target of `swarming` ships without decrementing the associated `swarmCount` value, resulting in a rapid maxing of any ship which lingers in a system. Basically, every `swarming` ship thought that the other ships in-system were already being protected, and would therefore land immediately
- Fixed by guarding the call to FindTarget by a personality check. Prior to #2828, swarming ships were effectively pacifist (did not target enemies or autofire upon …
> Refactor some AI functions

- source/AI.cpp
#3531 used the wrong "Should I scan this target?" check in FindTarget
This PR restores the "relaxed" scanning behavior to non-surveillance ships, wherein only any ship of that government can satisfy the urge to scan. Surveillance ships retain their penchant for nosiness, requiring a personal inspection.
> Revert use of aggressive scanning check for non-surveillance ships

- source/MapPanel.cpp
- source/MapPanel.h
- source/Preferences.cpp
- source/PreferencesPanel.cpp
Another part of #3070 (and #2678 ) was that the player should have a way to know where their escorts are. This has also come up in other issues, where players have trouble locating systems (to go get stranded escorts, etc).
Rather than add a pointer or a thin ring around escort systems (which are generally used for missions), I've opted to fill in the central ring of a system with a small pip if it has at least one player ship. If the only escorts are parked, the pip will be dimmer than if there are unparked ships there.
This is an opt-out preference.
<details><summary>Preference panel</summary>
</details>
<details><summary>Escorts in Pherkad, Shaula, and Lesath</summary>
</details>
Possible alterations:
- ~~Differentiate between systems with only parked escorts, and those with at least …
> Show location of player escorts on the map

- source/WrappedText.cpp
Refs #3588 
- If `CENTER` or `RIGHT` aligning, the width of the last word is needed. With adding it, `extraSpace` erroneously included the width of the final word, resulting in the addition of too much space when adjusting word positions.
- Since `JUSTIFIED` is historically the only alignment used, and no justification of the final line is done (it's always left-aligned), this escaped detection for quite a while :)
> Update the line width for the final word in a wrapped text string

- data/events.txt
- data/free worlds middle.txt
- data/free worlds reconciliation.txt
Refs #1360 
- `"fw syndicate welcoming"` resets the player's rep to 1 (ensuring the player can land on the Syndicate worlds, which are not accepting bribes at that point).
- If the player had a Jump Drive but did not dominate Syndicate worlds, they would be unable to land until the event triggered.
- Since `on enter` MissionActions are processed after the player's pending GameEvents are checked, any GameEvent within an `on enter` will not actually occur until the next day (e.g. jump or planetary takeoff), the rep change is moved from the GameEvent into the `on enter` MissionAction. The player does not have any Free Worlds or Republic escorts for this mission, so the `attitude toward` and system fleet adjustments can wait the extra day.
- Also removes a few uses of the "Escort" government …
> Replace timer for "fw syndicate welcoming" with filter-restricted "on enter"

- data/free worlds checkmate.txt
- data/free worlds middle.txt
- data/free worlds reconciliation.txt
- data/free worlds side plots.txt
- source/AI.cpp
- source/BoardingPanel.cpp
- source/Engine.cpp
- source/PlayerInfo.cpp
- source/Ship.cpp
- Swaps to using the less-complex yet still-correct check `Ship::IsYours()` rather than `Ship::GetGovernment()->IsPlayer()`
- Every mission NPC declares its government
- Swapped a number of unspecified (i.e. Player government) NPCs to using the more-appropriate Free Worlds government
> Replace most gov->IsPlayer with ship->IsYours

- source/AI.cpp
- source/AI.h
- Cloaked ships can decloak to repair their disabled / stranded allies (and be asked to do so by ships of their own government)
- Extended the "don't cloak if you'll be stranded" check to ensure that the ship can actually even achieve cloak
- Switched from absolute shield/hull health to using the "health until disabled" metric, using the same threshold as retreating fighters.
- Cloaking for repairs does not occur unless you can actually repair
- Added a rudimentary "retreat" behavior, so that ships that choose to cloak to repair will actually increase the distance from their target (rather than continue to move as though they are not cloaked)
- Cloaked AI escorts will cloak when their friendly parent cloaks, and then rendezvous with them (thus making it more likely that they focus on the …
> Improvements to the Cloaking AI

- source/Engine.cpp
For missions which are generated when the player lands, if more than one ship is in an NPC block with `personality uninterested`, multiple NPC flagships would be assigned
1) Since Fleet::Place and Fleet::Enter perform NPC flagship assignments
2) Since Engine::EnterSystem also performs NPC flagship assignments (but exclusively for mission NPCs)
During instantiation, the Fleet method is called, and while the NPC flagship chosen here is the first ship in the group, the ships are added to the **front** of the NPC's ship list. Upon launching after accepting the mission, the mission ships are then placed again, starting with the **front** of the NPC ship list (and this ship will become the NPC flagship).
I opted for this change, rather than altering the `push_front` in Fleet::Enter and …
> Freshly-instantiated, uninterested NPC flagships should have no parent

- data/wanderers middle.txt
Refs #3424 and #3467
- Adds a blocked check to the Quarg recruitment, on the premise that the empathetic Elias would offer medical supplies to help Farpoint's injured. This blocked check then requires the player to arrive at Farpoint with the needed 2 space free for the bomb.
- Splits the log entry for the Quarg escorts (as some players choose instead to wander with them, and may forget exactly when they picked up these escorts).
- Adds an `on enter` to Bomb Zenith 1, which hints at the alternate solution. The text is per @Amazinite's https://github.com/endless-sky/endless-sky/issues/3467#issuecomment-354374324, with a paragraph break added.
New dialog & conversation appearance:
> Update blocked Farpoint Defense mission

- data/hai.txt
- data/korath.txt
- data/remnant.txt
- source/AI.cpp
- Default fleet cargo tries is 3, which results in mostly-filled cargo holds (and therefore an inability to plunder)
- Added `harvests` to the Korath Raid fleet so that it will care about the jettisoned cargo from injured Remnant and Merchant fleets
> Improve likelihood that "plunders" fleets can plunder

- source/Engine.cpp
a4a4b3e has a missing `(` (and also adds an unnecessary guard for the flotsam collection, since a ship with any level of cloaking satisfies `CannotAct()`)
Refs #2786
> Fix missing parentheses and remove redundant check

- source/ShopPanel.cpp
If the height of the selected item was a bit bigger than the main height, the auto-scroll would go up and down repeatedly and never stop.
> Don't try to match the top when scrolling down a big selected item.

- source/Fleet.cpp
- source/Mission.cpp
- source/System.cpp
- Variant toRemove only needs to be initialized once
- set.erase first performs a count, and erase(<key>) returns 1 if <key> was erased
- System.links & System.neighbor used to be vectors, but were made sets in 4fa19f67a4f4e559f08b769bf7596ff52005eff2, and set supports erase(<key>)
> Update erase usage

- source/Format.cpp
Show 0.7 instead of .7.
Natural languages always have at least 1 digit to the left
of the decimal separator; unlike some computer languages like C/C++.
Fix issue #3611
> Always put a digit to left of the decimal separator.

- source/Angle.cpp
When long is 32-bit, lround overflows with the values produced in System::SetDate, returning an implementation dependent number.
Using llround is enough to avoid overflowing with the expected values.
Since: 1c6e6a6f8cb77bc0447952a84d86bf66b492071b
Fixes: #3640
> Fix overflow in Angle.

- source/AI.cpp
Refs #3149 
- Ensure that at least one target will always be aimed at, by increasing the starting score to +Inf
- Handle NaN returns from RendezvousTime
> Always track a target, even if out-of-range

- data/outfits.txt
This patches a particular exploit where the player is able to plunder the Cloaking Device from Pug Arfectas (yes, it can be done, I've tested it), even though they cannot uninstall it from within an outfitter without selling the ship. (This is [intentional](
https://github.com/endless-sky/endless-sky/issues/1344#issuecomment-234128902).)
- It doesn't seem logical to me that you would be able to plunder the cloaking device with on-ship tools, yet not be able to uninstall it with a full outfitter.
- Note that this patch would still allow a cloaking device in cargo to be plundered, according to [BoardingPanel.cpp#L88](https://github.com/endless-sky/endless-sky/blob/1fd6336f3194f5a2d2fc148f48cad8790a5e327b/source/BoardingPanel.cpp#L88). The cloaking device, as far as can be known to the …
> Made the cloaking device unplunderable.

- data/free worlds middle.txt
Ref: #3678 and the various related issues.
It doesn't make sense for Admiral Danforth to agree to help to liberate Poisonwood if he's also going to try and blow you up or get blown up by your escorts.
> Admiral Danforth now only helps liberate Poisonwood if your reputation is positive with Oathkeepers

- source/MapPanel.cpp
- source/MapPanel.h
- source/MissionPanel.cpp
The result of a search in the map is currently centered incorrectly when the zoom is not at the default level.
Results of searching for "Sol" at +1 zoom before and after the change:
> Fixed map search centering at non-default zoom.

- source/Engine.cpp
- source/HailPanel.cpp
- source/Ship.cpp
- source/Ship.h
#3716 seemed like a neat little addition, so here you go. This change allows these text replacements to be used in ship hail strings (suggestions for additions/changes welcome, of course):
- `<first>`, `<last>` (captain's name)
- `<ship>` (flagship's name)
- `<system>` (current system's name)
- `<npc>` (hailing ship's name)
- `<date>`, `<day>` (current date)
Contrived example (this PR does not include any actual new hails):
> Enabled text replacements in ship hails (#3716).

- data/pirate jobs.txt
Given that illegal cargo is no longer required for a mission to fine the player upon being scanned, I've removed the "slave food" from pirate slavery jobs, since the only point of the slave food was so that the player could be properly punished for carrying slaves.
I'm keeping the extra cargo in the wanted passenger jobs because they have blurbs that pop up upon being scanned that relate to the cargo. (Although, I can see an argument for them being removed in the non-highly wanted passenger missions given the specificity of how the passengers are taken vs the relative commonality of the job, ref: https://github.com/endless-sky/endless-sky/pull/3688#issuecomment-385249464.)
> Removed "slave food" from pirate slavery jobs

- data/quarg missions.txt
- data/wanderers middle.txt
My main issue is specifically in the Wanderer mission when you are ordered to ask the Quarg for help, because the Quarg then have a very good handling of the modern English language, when in a previous encounter (if any) they clearly... had problems. I propose that we change that.
> Make the Kuwaru Efreti Quarg more consistent with their language

- data/transport missions.txt
For consistency, since other mission weapons are categorized.
> Give a proper category to a mission weapon.

- data/events.txt
- data/governments.txt
This PR will make it very difficult to make the Republic friendly to the player after they have joined the Free Worlds (except when it is ceasefire time and when the war is over). This means killing pirates is not a viable option. Plus, because it is very difficult to make the Republic friendly again, this PR will also make the Republic hostile to the Korath exiles again.
> Prevent messing up the FW storyline

- source/Audio.cpp
- source/Preferences.cpp
This increases the upper limit on what the volume can be set to back to 100% (as before 006238e85b7c9647e011c1d6bebcee40216c81ee).
The default volume remains unchanged (now 12.5% of maximum).
Volume in existing configurations remains unchanged. In the configuration file, the volume value now has the range from 0 to 4 (instead of 0 to 1).
Fixes #3725.
> Increase maximum volume back to 100%

- endless-sky.appdata.xml
This change makes the AppStream file pass both XML and AppStream validation (`appstreamcli validate <file>`).
Also, I added some more screenshots. Regarding screenshots, it would be fantastic if you could provide the following:
- A larger, 16:9 widescreen version of https://endless-sky.github.io/screenshots/beams.jpg or something like it
- A larger, 16:9 widescreen version of https://camo.githubusercontent.com/647979e73d2121a1a982a96b0561e0e435598fd4/68747470733a2f2f656e646c6573732d736b792e6769746875622e696f2f73637265656e73686f74732f736d616c6c382e6a7067 or something like it, and display it at https://endless-sky.github.io/screenshots.html
The better Endless Sky's AppStream metadata is, the more I can advertise Endless Sky as a good example when I blog about [KDE …
> Make AppStream file use valid XML, pass `appstreamcli validate`, and add screenshots

- source/Engine.cpp
- source/Personality.cpp
- source/Personality.h
Refs #1567
- Mission NPCs with the "launching" personality will always take off with the player, even if their government (or other attributes) would normally prevent them from landing.
> Add a "launching" personality, to complement "waiting"

- source/Mission.cpp
- source/Mission.h
- source/MissionPanel.cpp
- source/MissionPanel.h
If a mission defines a waypoint, this waypoint is no longer visible once it has been visited, even if a task in said waypoint is incomplete (e.g. "destroy the Sestor drones"). Missions began tracking visited waypoints / stopovers in #3208, but they were not used outside of granting clearance to land without being fined.
This PR creates a faint ring around any visited waypoint of an active mission, when that mission is selected. In this screenshot I am in a waypoint system, and have the mission selected, which highlights the missions waypoints (both visited and unvisited).
> Show visited mission systems

- data/marauders.txt
- data/persons.txt
<s>Although I understand the Marauder Fury's need to defend itself, I think having it equipped with three Quarg Intrusion Countermeasures is hard to explain, lore-wise. This proposal replaces them with ordinary human laser rifles. There is no space (0/240) for security stations.</s>
Because it's a unique person ship, this proposal moves the M. Fury from the `marauders.txt` file to the `persons.txt` file to avoid unnecessary confusion.
> Moved M. Fury to persons

- readme-developer.txt
Debian stable doesn't have libpng12-dev or libjpeg-turbo8-dev.
> Update developer instructions for deb-based distros.

- source/Personality.cpp
- source/Planet.cpp
- source/Planet.h
Refs #2524 , #2318, 
- Use an vector of stock fleet definitions to allow customized tribute battles
- Increase difficulty of all tributes by changing the personality from `staying heroic nemesis` to `staying heroic marked unconstrained`
- Tribute fleets will now only target the player's ships, and will be ignored by all other ships even if they would be "natural" enemies.
- Increase visibility of tribute fleets in busy systems by applying the "target" personality
- Correct a bug in the bounds check for tribute fleet definition
- `fleet "Small Republic"` is currently skipped while `fleet "Small Republic" 1` is accepted. Both are valid and acceptable with this PR.
- Print a warning if there is a custom fleet definition (i.e. child nodes to a node that starts with `fleet`)
- If multiple mods …
> Support multiple fleet types in planet tributes

- data/free worlds middle.txt
I personally did not see the absolute need to change this, but it's ultimately *safer* to implement it the way @Amazinite suggested (dogging --> harassing).
Because, after all, when someone not familiar with the word or it's usage goes to look it up, this is what they'll find:
And that might not be the best or most accurate thing for players to be seeing. :P
> Changes "dogging" to "hounding" (refs #3780)

- data/remnant outfits.txt
All Remnant weapons and outfits require a Remnant license. The exception is the new EMP Torpedo Bay. My guess is this is not intentional, hence this patch, which applies the Remnant license to this weapon as well.
> EMP license

- source/AI.cpp
- source/AI.h
Refs #3507 , #2234
Extends the check prior to entering "follow the parent" behavior to consider if the parent is beyond the fence and the if the ship cares about that sort of thing.
I didn't tweak the behavior in MoveIndependent regarding out-of-range ships as it isn't entirely clear what the goal is:
https://github.com/endless-sky/endless-sky/blob/cb8d456b44dafc2695611540a6d65ecd674aea90/source/AI.cpp#L1127-L1137
My interpretation is
- Keep targeting this ship, even though it is out of your bounds
- if it is faster than you going outward, give up chasing and start returning to the center before it crosses the actual boundary
- if it is slower than you going outward, chase it for a bit even after it crosses the actual boundary
- When you give up the chase, execute a "wide turn" by …
> Hostile escorts consider parent position before using "follow" behavior

- source/Ship.cpp
- source/Ship.h
- Updated comments to reflect that this function can return negative values (e.g. hull damaged beyond minimum hull).
- Considers both "pooled" health (hull + shields) and hull-only health (per https://github.com/endless-sky/endless-sky/issues/3092#issuecomment-335036347 )
- Added consideration of disruption damage when adding shields in the pooled health part.
We could enforce the "return of 0 means it is disabled" by adding `|| isDisabled` in the check for a `<=0` divisor.
> Update Ship::Health calculation

- source/MapPanel.cpp
- source/MapPanel.h
- source/MapSalesPanel.cpp
- source/MissionPanel.cpp
Refs https://github.com/endless-sky/endless-sky/pull/3576#issuecomment-358497939
Current UI:
<details><summary>Active and parked</summary>
</details>
<details><summary>Flagship only</summary>
</details><details><summary>Active only</summary>
</details><details><summary>Parked only</summary>
</details>
~~To-do~~ Done
> Display a map tooltip for escorts in a given system

- source/BoardingPanel.cpp
- source/Conversation.cpp
- source/Conversation.h
- source/ConversationPanel.cpp
- source/ConversationPanel.h
- source/MainPanel.cpp
- source/Mission.cpp
- source/Mission.h
- source/MissionAction.cpp
- source/MissionAction.h
- source/NPC.cpp
- source/PlanetPanel.cpp
- source/PlayerInfo.cpp
- source/PlayerInfo.h
- source/Ship.cpp
Refs #3206 , #3129, #3228 
- Adds a new player-death keyword, `explode`, to resolve the ambiguity over how the player dies while in space
- If the player's ship should be destroyed, use `explode`. The flagship will explode.
- If the player's ship should be captured, use `die`. The player dies, and his ship is taken over by the ship it was boarding. (If `die` is used and there is no boarding ship, the flagship changes government, simulating a mutiny.)
- If you're dying as a result of a conversation, you aren't going to be shown the BoardingPanel
- `launch`, `depart`, and `flee` kill the NPC associated with a conversation, even if not boarded (say, if your outfit scan activated some embedded explosives' trigger mechanism...), unless you're dying too.
> NPC "completion" / MissionAction conversations can kill the player and/or NPC

- source/AI.cpp
- source/DistanceMap.cpp
- source/DistanceMap.h
- Extends advanced refueling logic to ships moving independently & following orders
- Extends advanced refueling logic to in-system escorts
- Chooses the best route for a ship to reach its destination system
@flaviojs please check this pull for differences in escort behavior compared to your pull - I'm pretty sure it keeps all the behaviors you added while extending them to MoveIndependent (where they can serve `personality uninterested` and #2990 ).
> Unify refueling and routing code

- data/interfaces.txt
- source/AI.cpp
- source/Engine.cpp
- source/Ship.cpp
- source/Ship.h
1. If a target is extremely overheated, there are probably other ships around that are not overheated that can attack the ship - those targets should be attacked more preferably than a ship which is incapacitated for a significant period of time.
2. ~~Adds a visual conveyance of the degree ( :grinning: ) to which the player has been overheated, by segmenting the HUD's `heat` bar.~~ Adds a second overlay bar with the ship's excess heat (the heat which needs to be dissipated before the ship is no longer overheated). This information is not currently available, so if the player is extremely overheated but otherwise not disabled, they can get visual feedback of how long they have to wait before their ship will begin responding again.
<details><summary>After provoking 20 Doombats:</summary> …
> Consider target's heat level when picking targets

- source/Engine.cpp
- source/Radar.cpp
- source/Radar.h
Refs #3605 
Scales up & down, ensures that the lines do not overrun the radar boundary. Even for a tiny screen (1024 W), the lines won't overlap and are still visible.
max zoom @ 1024x863
min zoom @ 1024x863
Uses an opt-out hidden preference `"Disable viewport on radar"`; I'm happy to alter that.
> Draw viewport boundaries on radar

- data/remnant ships.txt
I noticed that the right flare was slightly longer than the left flare on my Albatross. Did some digging and it looks like the engine zoom factors were swapped.
> Fixed the Albatross engine flare zoom factors

- data/weapons.txt
Currently the javelin pod (size 12) only has a better capacity than the meteor missile launcher (size 10), but in all other respects is significantly worse. This patch reduces the javelin's reload time from 20 to 15, which, although still not great, makes it at least a viable choice.
Before:
After:
> tweaked javelin reload time

- data/korath ships.txt
The Kor Sestor "Far Osk 27" fighter and "Far Lek 14" drone somehow have a ramscoop value of 3. They don't have fuel nor a hyperdrive, therefore this is rather useless and should be removed.
> Remove ramscoop from Sestor fighter and drone

- data/weapons.txt
Here's version 2 of my attempt to improve human missile playability, this time with more moderation and a lot more playtesting for balance.
All human missiles get +20% DPS to improve their combat usefulness compared to gun weapons. They get large increases in per-missile damage, accompanied (mostly) by significant reductions in missile launcher fire rate. Some missiles get a few additional tweaks to refine their battle roles.
The overall effect of these changes is to differentiate the human missiles from one another in terms of their ideal battle roles  in a way that makes the game world feel more realistic, and to make using them and facing them in battle more fun:
- Since missiles how have much larger per-missile payloads, getting a hit with individual missiles makes a difference: …
> Improve the playability and tactical flexibility of human missile weapons

- data/map.txt
This PR replaces a few duplicated landscape images with some of the images that are currently not in use. I tried to swap images out with similar looking images as much as possible. In some cases, like replacing the planets with forest landscapes, the newly used image only matches the old image in color as to not conflict with the planet image. Landscape images should still reflect what the planet description says, assuming it says anything at all about the landscape.
With this PR, the only unused non-space non-station images are cities 15, 16, and 17 as well as industrial0. 55 planets still share landscapes among 27 images. 
Unused space and station images still include space 0, 2, 3, and 5 and station 3 and 4, as I didn't look at the space station images with this PR. 30 stations still …
> Replaced duplicate landscape images with unused images

- source/OutfitInfoDisplay.cpp
Jump speed is a velocity and should thus be displayed in its per second value, as is done for similar stats.
> correct jump speed displayed

- data/transport missions.txt
The offer conversation and completion conversation mention someone called `Jim` but they are not listed as part of the family. Presumably, Jim is meant to be one of the parents so Cory becomes Jim.
> Typo fix in transport mission

- source/Font.cpp
https://github.com/endless-sky/endless-sky/commit/406c34e2baf6f88246d45a7ac70b8751c2c9092e#diff-38b37fd2bcdee403e42b45bbde753a3e moved the call to `glUniform1i(shader.Uniform("tex"), 0);` in `Font::SetUpShader()` up top without removing the old one. 
The second call logs `glUniform1i has failed because the operation requires a currently active program object (GL_INVALID_OPERATION)` if gl context debugging is enabled.
> remove extra call to glUniform1i in Font.cpp

- data/commodities.txt
Gas is pluralized as "gases" in the description of New Wales and Winter, but this one commodity has it pluralized as "gasses."
> Normalized spelling of gases

- data/free worlds middle.txt
As a huge lesbian I thought it kind of strange that, in revealing that Alondo is gay, the game implies that the PC _isn't_ (by sending you on the diplomacy mission that Alondo is too gay to go on). Since ES aggressively avoids implying anything about the PC other than their place of birth and vague age/backstory elements, I figured I'd add a response to Freyja that allows you to dispel that implication.
> Adds extra response to the "Alondo is gay" revelation

- data/hai missions.txt
Hai space is rather underused mission wise. While there are the few introduction missions to the Hai and a few Wanderer missions that deal with the Hai, this region of space doesn't actually have anything else in it.
This PR adds five new sets of missions to Hai space. 
* **Returning Home**: Elliot ran away from home when he was a teenager and found his way to Hai space. He would now like to return home to his family in the Dirt Belt.
* **Unwanted Cargo**: While in Hai space, a Hai child crawls its way into your cargo hold. You don't realize this until you make it back to human space, though! Return the lost child to its family.
* **Expanding Business**: Available after the main plot is completed, a Paradise World businessman would like to use your name to set up a outfitter in Hai space. …
> Hai spaceport missions

- EndlessSky.xcodeproj/project.pbxproj
This fixes some linker issues I had trying to build against brewed dependencies.
- The path to SDL2.dylib was relative to the project, so it would only have worked if your ES checkout was made at the correct place.
- The strange header search path cause the OS-provided libjpeg (in `/usr/{include,lib}`) to be found first.
> Fix XCode libraries

- source/Engine.cpp
- source/Ship.cpp
With OSX 10.13.3 17D102, XCode 9.4.1, and clang-902.0.39.2, building for `x86_64-apple-darwin17.4.0` generates loop-analysis warnings about copies:
<details><summary>Click to expand</summary>
```
=== BUILD TARGET EndlessSky OF PROJECT EndlessSky WITH CONFIGURATION Release ===
/Users/travis/build/tehhowch/endless-sky/source/Ship.cpp:550:40: warning: 
loop variable 'it' has type 'const pair<const Sound *, int> &' but is initialized with type
'const std::__1::__map_const_iterator<std::__1::__tree_const_iterator<std::__1::__value_type<const Sound *, int>, std::__1::__tree_node<std::__1::__value_type<const Sound *, int>, void *> *, long> >::value_type'
(aka 'const pair<const Sound *const, int>') resulting in a copy [-Wrange-loop-analysis]
for(const pair<const Sound *, int> &it : …
```
> Remove compiler warnings on OSX build

- source/LocationFilter.cpp
- source/LocationFilter.h
Refs #3139 
Missions that trigger on boarding or assisting can now reference the ship's
- category (e.g. "Heavy Warship")
- outfits (e.g. "Electron Beam")
- attributes (e.g. "cloaking fuel")
Outfit and attribute references return true if the ship has a positive value for the provided token - a ship with a negative or zero-valued attribute/outfit count will not match that attribute or outfit.
Outfits can also be used for planets to restrict by the items available in its outfitter.
These values are usable in the `source` (all), and  `destination` (outfits only) LocationFilters. A ship is not currently a supported mission destination, so specifying a ship attribute in the attributes node of a  `destination` filter will not work well (unless some planet in map.txt has that attribute). …
> Extend LocationFilter for ship sources

- source/Ship.cpp
Simply prevents a weapon from firing if it would reduce your heat below 0.
To make use of this, create weapons with negative heat costs.
Isolated from other changes as recommended in #3800.
> Heat as weapon resource

- data/tooltips.txt
- source/Ship.cpp
Currently all ships have some internal fuel capacity. However, it is not inconceivable ships with 0 fuel might be introduced, or outfits that lower the fuel capacity. (In fact I'm working on a plug-in that changes all ships to have 0 fuel.)
This patch introduces a "no fuel?" warning, analoguous to the "no hyperdrive?" warning (#3635).
> Introduce a "no fuel?" warning

- data/effects.txt
- source/Effect.h
- source/Engine.cpp
- source/Ship.cpp
- source/Ship.h
Refs #944
Until #957 is supported, supporting "retrieve effect" doesn't make much sense, since the effect location will be in a different place than the carried ship "gets absorbed" by the carrier. With #957 supported, adding support for a "retrieve effect" won't be difficult.
Example bay definition:
```
drone -66 24 over left
"launch effect" "external launch"
```
Caveat: effects for an "under" bay will be drawn on top of the ship. I don't think this part is easily addressed.
I've also defined a "basic launch" effect that any non-automaton ship will use for internal bays (that do not define their own launch effects), to prevent needing to go through every existing ship definition and add it explicitly.
[Basic launch](https://youtu.be/IQVC30iEi78)
(I'm sure this effect could be greatly …
> Support launch effects for carried ships when departing from their carrier

- data/drak.txt
- data/quarg outfits.txt
- data/transport missions.txt
- source/AI.cpp
- source/Outfit.cpp
- source/Ship.cpp
- source/Weapon.cpp
- "Outfit scan" and "cargo scan" have been deprecated a long time. Previously this has been "handled" by treating them like they aren't deprecated at all - runtime code had to check for both the old and new attributes. No more: these old attributes are converted during game load into the proper types.
- Converted the implicit default values of tracking `1.` and turret turn `4.` into explicit values, and added warning for failure to specify those attributes.
- bounds-check that split range, blast radius, and trigger radius are `>= 0.`
> Issue deprecation warnings & simplify some code

- data/events.txt
- data/free worlds war jobs.txt
Added a number of jobs that only occur during the war and mostly only offer when the player is receiving a salary from the Free Worlds.
The jobs:
* **Scout Run**: travel into Republic territory and scout out the Navy activity for the Free Worlds to use.
* **Convoy Defense**: War requires a lot of resources, especially if the shipyards are trying to pump out ships for the war effort. Escort multiple freighters and possibly a few warships filled with supplies for making new ships.
* **Reinforcements**: Bring Free Worlds soldiers to the frontline worlds of the war in order to reinforce the planets.
* **Outfitter Resupply:** Resupply the many outfitters of the Free Worlds as they become low on supplies.
* **Frontline Resupply:** Resupply the frontline planets with food, medical supplies, or …
> Added wartime jobs for the Free Worlds

- source/Engine.cpp
- source/Engine.h
- source/MainPanel.cpp
- source/Mission.cpp
- source/Mission.h
- source/MissionAction.cpp
- source/MissionAction.h
- source/PlayerInfo.cpp
- source/PlayerInfo.h
@Kryes-Omega mentioned that there were some issues with missions that offered on boarding, and I took a look into it.
This PR fixes a host of issues with missions that offer from ships, primarily
- ~~Offering when the player has insufficient cargo space / bunks~~ (ref https://github.com/endless-sky/endless-sky/commit/1d780317b9cfb4e1afb42bcd288dde344667a480)
- ~~Shifted / missing displayed cargo~~
- No "blocked" messages would be displayed
- Mission NPCs would not spawn until after the player next took off from a planet
- Gifting of outfits assumes the player is landed
With this PR
- Missions chosen to be offered, but unable to be offered due to insufficient space, will show a blocked message if one was specified.
- ~~If having accepted a mission from boarding/assisting a ship requires …
> Improve support for missions offered and actions performed while assisting/boarding

- source/Preferences.cpp
- source/PreferencesPanel.cpp
- source/Ship.cpp
The player can choose between "least need" (series) and "most need" (parallel). Maintains the default strategy of "least need" for AI ships and players who have not set the preference, while allowing player-specific control.
Refs #3182, https://github.com/endless-sky/endless-sky/issues/2333#issuecomment-291005200
> Use a preference to control fighter repair strategy

- data/paradise world jobs.txt
- data/pirate jobs.txt
- data/transport missions.txt
- source/Mission.cpp
- source/MissionAction.cpp
- Provides feedback to content creators about old syntax, or syntax that doesn't work as they may have thought
- Addresses our own old syntax re: `illegal` and `stealth`
- Handle `outfit <name> 0` while loading MissionActions rather than check at runtime.
> More deprecated syntax warnings

- data/kestrel.txt
The Kestrel is supposed to be a superb, modern, state-of-the-art warship of alien design. In practice, it's hardly better than a Bactrian, Carrier, or Dreadnought, its nearest human competitors. This patch intends to improve the Kestrel's desirability by tweaking various stats:
* +2000 shields, +1000 hull, putting it in the same range as the Carrier
* reduced required crew to 64, putting its daily upkeep slightly below the Bactrian's 70
* lowered drag to 11, because the Kestrel is a highly streamlined design, therefore it is odd it is currently relatively slow; for comparison, Cruiser is at 10.1, Dreadnought at 10.1, and Falcon at 6.7 (maximum velocity = thrust / drag)
* improved heat dissipation to .6; for comparison, Dreadnought has .65 and Falcon .7
* +10 weapon capacity, to allow six …
> Tweaked Kestrel

- data/ships.txt
- data/variants.txt
Placed the Carrier's first Heavy Anti-Missile turret on the first mount, to cover a greater area and protect it from full frontal missiles.
> reorder Carrier's HAM turret

- .gitignore
This reverts a change removing xcode project settings from `.gitignore` in c76aea7294f0f76a823e3009c6e7c96600a9eb98. That commit also changed ignoring `*.exe` to just `EndlessSky.exe` - Do we definitely want to do that?
> Revert some .gitignore changes

- data/map.txt
Because it improves consistency:
* other wormholes in the Ember Waste also require quantum keystones
* the "Ember Wormhole" is currently the only wormhole with a red sprite that doesn't require a quantum keystone; other reds do, purples don't
> made Ember Wormhole require quantum keystone

- data/free worlds war jobs.txt
Fixes some Free Worlds wartime jobs being impossible to complete without the jump drive (as the original deadlines didn't take into account the day that is spent taking off); deadlines for the most of other jobs are extended by one day to allow for one resupply landing while en route.
> Fix the impossible deadlines

- data/map.txt
Changed three instances of Quargs into Quarg, because it seems everywhere else Quarg can be both singular, plural, and adjective; cf. Hai, Pug, or Remnant.
> Quargs → Quarg

- data/map.txt
Remove southern merchants from Algieba, because it's an uninhabited system and none of its neighbours has a southern fleet, so it's weird they appear here out of nowhere.
> merchant fleet corrections

- data/map.txt
This proposal removes large merchant fleets from Kugel, Nocte, Fingol, Regulus, Lolami, Limen, Ipsing, Boral, Hintar, Orvala, Naper, and Umbral, because these are uninhabited dead-end systems leading to nowhere, so merchants have no business doing here.
Small merchant fleets are kept in these systems, because people might be exploring or too poor to purchase a map, so these merchants could then refuel the player.
See also #4039.
> removed large merchant fleets from uninhabited dead ends

- data/fleets.txt
- data/hai ships.txt
- data/ships.txt
- data/variants.txt
This PR adds Luxury accommodations to the Hai Centipede and Human Arrow, both of which are mentioned as specifically existing for the purpose of transporting wealthy people. Loadouts are adjusted a bit where needed to keep from becoming negative, as Luxury Accommodations add weigh 10 tons.
> Give more luxury ships Luxury Accomodations

- data/kestrel.txt
So that the player sees the (already existing) thumbnail in shipyard and outfitter screens. Will also fix it for the all-content-plugin.
> Add thumbnail definition to the "Unknown Ship Type"

- data/transport missions.txt
These jobs had missing or incorrect `stealth` tags and the 8m credit penalty didn't work (sorry about that). This patch fixes those bugs.
closes #4057
closes #4058
> Fix bugs in Shady Passenger Transport jobs

- data/transport missions.txt
Now that #3347 is done, here's an update to the capture a smuggler mission to use a Brig as well.
> Require a Brig for the mission to capture a smuggler

- data/events.txt
This excludes all `uninhabited` just to be sure.
Fixes #4104
> Do not trigger the remembrance day or war begins missions on uninhabited planets

- source/PlayerInfoPanel.cpp
- source/ShipInfoPanel.cpp
Closes #3703 
Fixes a bug / UX detriment where the Player Info panel could not be toggled with `i` - instead, `i` would open the mission panel. This stems from `i` being the default key associated with the INFO command.
This PR regularizes the use of `Command::INFO` to always do what the ticker says:
https://github.com/endless-sky/endless-sky/blob/d2e19f154a37c267562192847a720fd4a36e3c1b/keys.txt#L20
Additionally, for certain buttons associated with the Player/Ship info panels, (rename, park/unpark, park/unpark all), allows the use of the Shift key to perform the action. (The game ships an interface definition which makes the buttons emit the uppercase key, which keyboards generally can't do.)
I skipped including the Caps Lock key in this, since it is fairly probable that someone will …
> Improve UX for PlayerInfo / ShipInfo panels

- data/syndicate jobs.txt
Ref: #4115 
Syndicate test dummy ships will now disable instead of killing the player. A happy customer is an alive customer. No use in killing off captains in the Core that could otherwise be spending their money on Syndicate goods.
Also gave Syndicate test dummy ships a confusion value of 120. Confusion isn't used hardly enough in the game. Given that the technology that the Syndicate are working on with these ships is effectively the same thing as the Kor Automata, I thought it fitting to give these test dummies a behavior that makes it very clear that the technology of fully automating large vessels is only in the works for the Syndicate.
> Made Syndicate test dummies disable and gave them confusion

- data/hai jobs.txt
This adds some two-way transport missions for Hai space. They pay twice as much as the one-way delivery jobs, but have deadlines. This also nerfs the existing delivery jobs.
> Add Hai jobs to bring commodities back from human space

- data/transport missions.txt
For the entire terraforming string of missions, this is the only point in which there is any combat. Given the fact that a player can very easily reach this point without a very powerful ship or even any combat skills. I've swapped the NPCs that you have to fight from bounty hunters to pirates, meaning that the player must no longer take on these NPCs solo and will be supported by nearby merchants and any Navy fleets that enter the system.
> Changed the NPCs in Terraforming 11 from bounty hunters to pirates

- data/korath outfits.txt
Even though it will never spawn in vanilla gameplay. The command center should be unplunderable, like bunk rooms or outfit expansions.
> Make Korath Command center unplunderable

- data/events.txt
This is a minor immersion fix - there are Mark II Oathkeeper ships later in the story, but no randomly spawned fleets. This way the Navy isn't neglecting the fleets responsible for defending the North.
I also considered adding the Oathkeeper variants later, so that they can't be used for the Electron Beam hunting missions. If that's preferable, I'll add them in a separate event sometime between then and the FW Alphas missions.
> Add Mark II Oathkeeper fleets at the same time as the rest of the Navy

- .travis.yml
- EndlessSky.xcodeproj/project.pbxproj
- XCode/EndlessSky-Info.plist
- XCode/en.lproj/InfoPlist.strings
- Changed the path of libSDL2-2.0.0.dylib to match build instructions
- removed (unused) localization 
- added Bundle Display Name and changed the Product Name
Fixes #561
> Rename MacOS application to "Endless Sky"

- data/deep missions.txt
As it is (planet tag): 
With stopovers tag instead of planet:
> Deep missions fixes

- data/tooltips.txt
- source/Ship.cpp
- source/Ship.h
New players may be confused if their projectile weapons don't fire even though their energy bar is full. This PR adds a flight check warning that warns the player if a ship has a non-continuously-firing weapon installed that requires more energy than the ship has energy storage.
Here's an example shuttle with no energy storage that has an energy blaster installed:
Here's the same shuttle with a beam laser, which produces no warning since it fires continuously:
> Add a "battery too small to fire weapon" flight check warning

- data/remnant missions.txt
Adding the "Marked" personality to the target ship for the second Remnant Bounty mission so that the Remnant will leave it alone. Otherwise it is too easy for the player (not to mention harder to salvage from). And most importantly, so it works as intended.
> Adding the "Marked" Personality to the target of the 2nd Remnant Bounty job

- data/coalition jobs.txt
- data/deep jobs.txt
- data/dirt belt jobs.txt
- data/free worlds intro.txt
- data/free worlds middle.txt
- data/free worlds reconciliation.txt
- data/free worlds start.txt
- data/free worlds war jobs.txt
- data/frontier jobs.txt
- data/hai jobs.txt
- data/jobs.txt
- data/pirate jobs.txt
- data/rim jobs.txt
- data/south jobs.txt
- data/transport missions.txt
- data/wanderer jobs.txt
- source/Dialog.cpp
- source/Dialog.h
- source/MissionAction.cpp
- source/MissionAction.h
- source/NPC.cpp
- source/NPC.h
- source/Phrase.h
Refs #1856 
This PR introduces reserved syntax for the combination of the `dialog` tag and the `phrase` tag when defining text for dialog pop-ups shown in missions' `on ____` actions and in NPCs' "completion".
Includes some examples in the existing datafiles, and otherwise generally extracts repeated text to a single location (so that it can be more easily diversified by future pulls).
Preferred syntax:
```
dialog phrase <stock phrase name>
```
a "stock phrase" is any phrase defined as a root level `DataNode`--i.e. the first thing on a new line:
```
phrase "hostile disabled"
word
...
```
(see `hails.txt` and `names.txt` for lots more examples of root-level `Phrase`s and complex phrase construction.
Also supported: nested phrase specification
```
dialog
phrase
word
...
word
...
```
**Any …
> Allow phrase-based randomized dialog

- data/ships.txt
- data/variants.txt
This was originally intended to give H2H to pirates, but per suggestion from @Amazinite it's easier to just add them to the defaults. I gave each ship laser rifles equal to 1/4 the required crew count, rounded up, floor 2. I also added H2H to the FW military at the same ratios as the civvie ones. Per discussion in #4125 the Free Worlds don't focus on H2H doctrine, so there's no reason for them to invest in H2H beyond generally accepted practices. Variants with Hai outfits received Pulse Rifles instead.
The Remnant and all non-human factions are already appropriately armed.
> Add hand-to-hand to human Medium and Heavy Warships

- data/wanderers start.txt
Ref: #4093
Seeing as how @10010101001 seems unresponsive with fixing up #4093, I've made the changes myself.
The second new choice is the same, just placed at the end of the list of choices instead of the beginning. The first new choice now has the player express their understanding, but still voice concern to Rek, meaning that the following dialog from Rek can remain the same.
> Added sympathetic choices in Wanderer start (@10010101001)

- data/marauders.txt
- data/ships.txt
Ref: #4051 
Increased the Raven's cost by 400k. Also increased the Marauder Raven costs accordingly.
Even without a change like #4014, the Raven and Headhunter cost are surprisingly close to one another. This PR bumps the cost of the Raven up to be more in line with the cost of other light warships, placing the cost more between the Headhunter, which is statistically weaker than the Raven, and the Modified Argosy, a bigger ship.
Table showing cost of various ships around the progression of the Raven:
Ship | Category | Sale cost
----|----|---
Hawk | Interceptor | 1.028 M
Quicksilver | Light Warship | 1.964 M
Headhunter | Light Warship | 2.540 M
Raven | Light Warship | was 2.672 M, now 3.072 M
Modified Argosy | Light Warship | 3.324 M
Manta | Medium Warship | 4.789 M
> Increased the cost of the Raven

- data/free worlds intro.txt
- data/free worlds middle.txt
- data/free worlds reconciliation.txt
- data/free worlds start.txt
Titles and the names of specific bodies are capitalized in English, but when using words in a generic sense, they are not, nor are adjectives or adverbs. E.g. 'the US Senate is a senate'; 'Senator X was one of a group of senators who complained about their senatorial staff'. I did a `grep` to check for inconsistencies.
* Conservatory is always capitalized
* Council was usually but not always capitalized; this is corrected
* Councilor [sic] is always capitalized
* Parliament is always capitalized
* Parliamentary is corrected to parliamentary
* Senate is always capitalized
* senator(s) was occassionally capitalized; this is corrected
> Capitalization corrections

- data/deep missions.txt
Some of this was spotted by @oo13 
* Fixed the `to offer` of `Deep: Remnant 0` to refer to the proper mission name of `Deep: TMBR 1` and not 2.
* Used the new `declined` condition to make sure that the recruit escort/reinforcement missions during `Deep: Scientist Rescue 1` did not accept if the player declined `Deep: Scientist Rescue 1`.
* Simplified conditions and missions in order to ensure that missions offer or complete in the proper order and fail at the right times.
* Fixed an instance of a mission not being invisible when it should be.
> Deep mission fixes

- data/remnant missions.txt
Fixing a mission start error where Dawn aproaches the player after they've been off to retrieve the historical data but before the player has actually turned in the data.
Changes the "to offer" tie-in between the two strings for Expanded Horizons Quarg 1 from Salvage 1 done to Salvage 2 done.
> Fix starting condition for Remnant: Expanded Horizons Quarg 1

- data/boarding missions.txt
- data/south jobs.txt
Ref: https://github.com/endless-sky/endless-sky/pull/4139#issuecomment-457804708
Added assisting/boarding missions using the new mechanics added by #3140 and #3005.
New missions:
* Dangerous journey: Offered by assisting merchant freighters. Finish a basic cargo delivery job for a merchant captain who has been disabled twice in the past week trying to delivery the cargo to a frontier world. 
* Assisting law enforcement: Basically a planetary defense job, only offered upon assisting law enforcement ships that are not fighters or drones.
* Boarding pirate: A different take on the assisting merchant jobs. Upon boarding a pirate ship, have a small chance to find a treasure crate of credits. Credit size dependent on the ship category.
* Pirate ambush: After you've achieved a low combat rating, …
> Added new assisting/boarding missions

- data/hai outfits.txt
- data/power.txt
So I've long thought that the Armageddon core, far from being the best human reactor, is kinds rubbish. There's almost no reason to use it in favor of two Hai boulder reactors, which out perform-it in pretty much every way. While I understand that Hai tech is supposed to be more efficient and all-around better than their human counterparts, the extent to which the Armageddon is outstripped is a little sad. 
The problem is not its energy-to-weight ration, which IMO is fine. It's the excessive waste heat. I get the impression that it's humanities first attempt to create something like the (IMO overrated) Korath reactors, but to this extend the thing just doesn't have the stats to justify using it. I've decided a good way to make the navy's definitive heavy reactor a more attractive choice …
> Armageddon Core Balance

- data/harvesting.txt
Minor change to Lead's description, as pointed out by "a chemistry nerd" (Professor Ocecat on the Discord), Lead is not the densest non-radioactive element (Osmium is).
> Change Lead description

- data/syndicate jobs.txt
My bad. Reported by Matt on discord.
> Correct <source> to <origin> in syndicate prisoner jobs

- data/remnant missions.txt
Changes:
- Missing quotation mark at the end of line 879, the end of Remnant: RS2.
- Missing comma in RLS1 and  RCR.
- Capitalizing Captain in RS1.
Thanks to Pulsar for finding this!
> Fix missing quotation mark in Remnant:RS2

- data/free worlds reconciliation.txt
- source/NPC.cpp
- source/NPC.h
This PR would allow content creators to build off #4111 , and enable a mission's NPC to start out landed on a specific planet. If the specified planet is not in the instantiated NPC's system, then the planet specification is ignored.
e.g.
```
npc
system "Sol"
planet "Luna"
government "Korath"
fleet "Korath Raid"
```
will result in a Korath raid fleet taking off from Luna when the player next takes off, while
```
npc
planet "Hevru Hai"
government "Quarg"
fleet "Large Quarg"
```
will only result in a large Quarg fleet departing from Hevru Hai if the mission is being offered from Hevru Hai (as the default system when unspecified is the mission's origin system).
The requirement to specify the proper system in addition to the planet ensures that the NPCs will be in the proper system even if …
> Specify an initial planet for mission NPCs

- source/Engine.cpp
This PR prevents NPC fighter/drone carriers to get lost.
Current version of Engine::Place(npcs, flagship) counts the number of bay's free before unloading bays, so fighters/drones may be launched from the carrier.
A fighter/drone outside a bay can become a NPC flagship and a carrier will be able to load the fighter/drone, therefor a child ship of the fighter/drone gets lost.
> Fix a bug for NPC carriers to get lost.

- data/deep jobs.txt
- data/deep missions.txt
- data/transport missions.txt
These changes make it easier to get all of the missions done to get the Bactrian license by making them offer sooner, more often, or in a better location, in response to feedback I've received by people playing MCO's nightly build. The only outside requirement to the Bactrian missions now is to have discovered the Hai for the purposes of receiving the Deep: Remnant missions.
* The Terminus Scientists mission now offers in the Deep and ends on Bounty, instead of starting and ending on Bounty. This means that the player doesn't need to look outside of the Deep for missions.
* Made one of the mystery cube jobs offer more often, as to avoid having the player struggle to find any such jobs to progress the story with.
* Deep: Project Hawking no longer requires the player to have interacted with …
> Changes to missions related to earning the Bactrian

- data/remnant.txt
This PR simply adds the Salvage Scanner to the Remnant Outfitter. That's it.
Sorry this was missed.
> Adds the Salvage Scanner to the Remnant Outfitter

- data/map.txt
This Efreti station in the Kashikt system is said to be completely abandoned, but you can get fined for being there with Nerve Gas, so I set the security there to 0 since it didn't make sense.
> Set security to 0 for the Tefkar Ret station

- data/wanderers middle.txt
It seems rather odd that the Wanderers would already have an airport, and doubly curious as to why the player would be meeting Sobari Tele'ek out there. It makes a lot more sense to meet at the spaceport.
Thanks to Righthand on the ES Discord for spotting this.
This PR changes airport to spaceport.
> Changes "airport" to "spaceport" in "Wanderers: Sestor: Scan Drones"

- data/remnant missions.txt
In Remnant: Expanded Horizons Quarg 3, one dialogue line starts with `OK` whereas the writing style of ES uses `Okay` instead. So, changing it here. (this is in line 1257)
> Changing OK to Okay in Remnant Expanded Horizons Quarg 3

- data/free worlds epilogue.txt
- data/transport missions.txt
When testing the Paradise Fortune mission chain, FW Epilogue: Alondo offered, leading to a situation where I sat down and had a beer with Alondo while the Republic was hot on my heels.
The mission Paradise Fortune 4 has a branch that I assume was intended to handle this, but it does nothing to stop the mission from being offered (since it cant), only changes the beginning dialog.
This PR handles this oddity by removing the ineffective branch from Paradise Fortune 4, and marks the all the epilogue missions minor to avoid the need for any special dialog for this case or any other.
> fw epilogue edit

- source/main.cpp
A refined version of my earlier poor attempt. Attaches a console that has been detached due to the nature of building with subsystem windows and redirects stdout and stderr to it, or, failing that, allocates a new console.
<details>
</details>
Redirection:
[out.txt](https://github.com/endless-sky/endless-sky/files/3069220/out.txt)
> windows console output

- data/pirate jobs.txt
Ref: #2862 
Currently, the only way to increase pirate rep outside of attacking merchants is to do pirate assassination jobs. These jobs are combat oriented though, leaving smugglers no options to increase their reputation.
This PR makes it so that regional stealth jobs will increase the player's pirate reputation if they succeed and decrease the player's reputation with the local law enforcement if they fail (are scanned).
I have also added increase pirate rep to the eliminating law enforcement jobs, as thinning the herd is bound to make the pirates happy, and the trade off with this mission is having your reputation hurt by needing to attack the law enforcement.
Finally, any situation where Republic reputation was hurt now hurts Oathkeeper reputation, and likewise for Militia reputation …
> Added more options to increase pirate rep through pirate jobs

- data/transport missions.txt
If the source for Terraforming 6 is in Sol, the deadline becomes 0 making it impossible to complete.
Reported by Kiko the Exile on discord.
> Bugfix: Terraforming 6 should not offer in Sol

- data/remnant missions.txt
Fixing an erroneously labeled outfit in the description on line 909. Thanks to Kiko for finding it.
> Fix: Changing electron beam to S-970 Regenerators

- data/south jobs.txt
Removed launch on accept. There is no immediate action in nearby space anyway for these missions, the player has to jump several times to reach the objective, launching on accept seems unnecessary.
Re-worded the dialogue to suit.
Spotted by Kiko.
> Updated pirate occupation missions

- data/hai outfits.txt
Ref: [Feedback](https://steamcommunity.com/app/404410/discussions/0/1653297026046844771/#c1653297026047413327)
Explicitly state that the hit force of the Hai Trackers is a feature that compensates for their relatively low damage compared to human missiles.
<details><summary>Old description</summary>The Hai Tracker applies among the most hit force per shot and per second of the more agile missiles (i.e. Meteor, Sidewinder, Tracker, Piercer, Thunderhead). Given the volume with which Hai ships deploy Trackers, dealing with them can be difficult when they're constantly tossing you around.
This PR greatly reduced the hit force of the Tracker from 350 to 200, bringing its hit force more in line with something like the Meteor Missile, which actually does more damage per shot.</details>
> Explicitly state the hit force of the Hai Tracker as being a feature

- data/remnant missions.txt
This PR fixes a spelling mistake found in two locations, namely the word `developped` which should actually be `developed`, which occurs on line 690 and 884.
Thanks to Darcy on the Discord for spotting this!
summary:
developped -> developed
Two instances, line 690 and line 884.
> Remnant: Fixing Spelling Mistake (developped)

- data/deep missions.txt
Any Deep mission which is the beginning of a string or which triggers after a delay now checks to see if the war is currently happening before being able to offer. This is to avoid the situation where the player may be in the middle of a truce period with the Republic, start a mission in Republic space or with Republic escorts, then have that truce period end. Plot-wise, this also means the Deep won't appear to be off doing its own thing (especially for the Navy and Syndicate campaigns) when it should be helping the Republic.
> Various Deep missions now check to make sure that the war is not ongoing

- data/hai ships.txt
Even considering the fact that Hai engines are very good, the Centipede is rather fast for its size. This change brings the Centipede's speed in a bit.
Comparing with a Star Queen fitted with the same engines as the Centipede, as the Centipede was intended as a Hai version of the Star Queen.
Ship | Max Speed | Turn Rate (empty)
----|-----|----
Star Queen (5 spare outfit space) | 452.7 | 140
Centipede (current, 20 spare outfit space) | 830 | 169
Centipede (changed, 20 spare outfit space) | 622.5 | 156
> Reduced the speed of the Centipede

- data/remnant missions.txt
It has been reported that the sub-missions for the Remnant: Tech Retrieval missions aren't triggering when they should. Upon examination, it appears that this is due to the fact that these missions erroneously have the "minor" tag. Given that these missions are *not* the start of a new string, but rather are the continuation of a mission that is sitting in the player's mission list, it is inappropriate for them to be marked as such.
Therefor, this PR simply removes the `minor` tag from each of the outfit-specific sub missions.
This bug was brought to my attention by Zaphod on the discord.
> Remnant: Tech Retrieval missions not triggering fix

- data/remnant missions.txt
This PR fixes a wording mistake by deleting the word `giving`, which corrects the sentence so that it reads properly:
`They move eagerly to secure the new weapons to their flatbed and quickly hand you your payment of <payment> before vanishing into the lab.`
Thanks to Karimi / Azure on the Endless Sky discord for spotting & reporting this mistake.
> Remnant Fix: giving vanishing

- data/remnant outfits.txt
Fixing the lack of a license requirement for the EMP torpedo.
This issue is mentioned in: https://github.com/endless-sky/endless-sky/pull/3805
And: https://github.com/endless-sky/endless-sky/pull/3818
This PR simply adds the requirement to have the Remnant license in order to purchase the EMP Torpedoes.
The Remnant are a reclusive, relatively tight knit society that is so paranoid about security that they force newcomers to take a blood test before having any dealings with them (and attack anyone that refuses). They are *not* going to sell advanced weaponry to someone without security clearances.
In reference to the PRs mentioned, there is no statement explaining if this is intentional or simply an oversight. Even the PR that would (from the title) deal with this specifically (PR #3818 ) …
> Remnant Fix: Adding Remnant license requirement to EMP torpedoes

- data/coalition jobs.txt
- data/deep jobs.txt
- data/dirt belt jobs.txt
- data/jobs.txt
- data/near earth jobs.txt
- data/paradise world jobs.txt
- data/pirate jobs.txt
- data/rim jobs.txt
- data/south jobs.txt
- data/syndicate jobs.txt
- data/wanderer jobs.txt
Currently, the player will only receive an `on visit` dialog in certain missions, mainly escort missions where they have left the escort behind, or those missions where an objective must be completed first like killing/evading/disabling the enemy. There are other situations though where a player may get to the destination but need an `on visit` dialog to tell them why it isn't complete, such as cargo or passenger missions where the player may have escorts lagging behind.
This PR adds generic `on visit` dialogs to all jobs that have cargo or passengers. This PR does not touch any spaceport missions. I also skipped over certain jobs that weren't strictly "take this cargo/these passengers here," such as a few jobs that had stopovers, like the Wanderer Invasive Species jobs or a job I spotted …
> Player will now receive on visit dialog for cargo and passenger jobs

- data/remnant missions.txt
Removing the `s` from Plasma Cannons in the requirements for Remnant: Tech Retrieval and Remnant: Salvage 1 so that they properly match the name of the plasma cannon mission (which, like the other tech retrieval missions, is singular.)
Change:
- line 705 removed the plurral `s` from Cannons
- line 1040 removed the plural `s` from Cannons
Thanks to CaptJosh on the Endless Sky discord for reporting this.
> Remnant-Fix: Making Plasma Cannons singular

- data/remnant missions.txt
Changes one sentence on line 1122 by adding the word "it".
...`telling him that is probably the best available.` to ...`telling him that it is probably the best available.`
The former sounds better from an actual "quoting the character" point of view, but as this is narrated, the second sounds better from the narration side.
Thanks to CaptJosh on the Endless Sky Discord for spotting this!
> Remnant-fix: Fixing Salvage 2 missing "it"

- data/remnant missions.txt
Fixes five instances of words being lowercase when they should be uppercase for consistency:
All instances are in remnant missions.txt
- line 732: starling
- line 769 starling
- line 814 inhibitor cannon
- line 814 albatross
Thank you to Blop on the Endless Sky discord for pointing out the inhibitor cannon miscapitalization.
> Remnant-Fix: Capitalization Consistency

- data/remnant missions.txt
Adds a missing `'` to line 687 in the remnant missions.txt file.
Thanks to @jostephd for spotting this and reporting it in issue #4357 
Thanks to the Writing Commune led by Moonbeam for the advice on correcting it.
> Remnant-Fix: A missing quotation mark

- data/fleets.txt
- data/ships.txt
- data/variants.txt
The description of the Tactical Scanner says that it has been in use by the Navy for some time, while only recently being used by militia ships. Gave this scanner to Navy ships where it fit and to FW-used heavy and medium warships where it fit.
The Asteroid Scanner is a very useful tool for those looking to make money off of asteroid mining, yet the current human miners don't use them. Created new miner variants of the Hawk, Fury, and Headhunter that use asteroid scanners and appear twice as often as their variants that don't use the scanners. These miner variants are based off of the variants of these ships that use to spawn (e.g. the Headhunter (Miner) is based off of and replaced the Headhunter (Particle) within miner fleets).
> Gave Tactical and Asteroid scanners to some ships

- data/marauders.txt
All Marauder ships except Marauder Splinter and Marauder Falcon follow the same formula - the increase in amount of required crew equals the increase in amount of total bunks. E.g. other Medium Warships:
* Marauder Firebird has +3 required crew and +3 total bunks compared to regular Firebird.
* Marauder Manta has +1 required crew and +1 total bunks compared to regular Manta.
Marauder Splinter currently has +7 required crew and +1 total bunks compared to regular Splinter which greatly reduces the usability of Marauder versions of the ship compared to regular Splinter for both boarding and transport missions, including storyline ones, without any good reason, and looks odd compared to other Marauder ships. 
I propose to adjust required crew of Maradeur Splinter to +1 compared to regular …
> Adjust Marauder Splinter required crew value

- data/wanderers middle.txt
Currently, after the player has destroyed the Sestor ships plaguing human space, it is possible for the player to be completely without a visible active mission despite the fact that there is still something to do. This occurs when the player still has to destroy the Sestor fleets in Alnilam, but doesn't ask for help from Danforth.
This PR adds an additional mission so that the player will always have one active during this part of the Wanderer campaign. As a result, the mission where the player asks for escorts is now invisible, as otherwise it would look like the player has two of the same mission.
> Added an extra mission so the player has one active after the Sestor Remnant

- data/deep jobs.txt
- data/deep missions.txt
- data/dialog phrases.txt
- data/free worlds checkmate.txt
- data/free worlds intro.txt
- data/free worlds middle.txt
- data/free worlds reconciliation.txt
- data/free worlds side plots.txt
- data/free worlds start.txt
- data/free worlds war jobs.txt
- data/hai jobs.txt
- data/hai missions.txt
- data/jobs.txt
- data/paradise world jobs.txt
- data/remnant missions.txt
- data/south jobs.txt
- data/syndicate jobs.txt
- data/transport missions.txt
- data/wanderer jobs.txt
- data/wanderers middle.txt
- data/wanderers start.txt
Ref: #4315 
On visit dialogs for all remaining missions in the game. I split up the PRs to distinguish between jobs only using generic dialogs and proper missions with unique ones.
I've also made a new file named `dialog phrases.txt` used to store the generic dialogs used in various files.
This is taking longer than #4315 given that it isn't 100% copying and pasting `dialog phrase "generic..."` over and over again. Decided to PR what I have done so far.
Going forward, it should be standard to give a mission an on visit dialog if the mission can trigger it.
<hr/>
I haven't added dialogs to a select few missions where it didn't seem like it would make sense, such as the April Fools job or @Pointedstick's shady passenger double cross mission; the passengers had to be in the player's flagship …
> Added on visit dialogs for nearly all missions that can trigger them

- data/hai ships.txt
- data/korath ships.txt
- data/ships.txt
- data/variants.txt
- data/wanderer ships.txt
Added missile storage outfits to a select number of ships. These ships included those that had a large number of missile launchers to begin with or relied on missile launchers, and those ships that were marked as being missile variants. If the ship was marked as a missile variant, then I may have changed the loadout of the ship in order to make room for storage outfits. Otherwise, I kept the loadouts of the ships the same and only added storage outfits if there was space.
There are some ships that I looked at to add storage outfits to, but they didn't have enough space for them, and I didn't want to have to drastically change the loadouts of ships just to fit the storage outfits; the benefit of more ammunition often wouldn't outweigh the detriment of losing speed, shields, cooling, etc. …
> Added missile storage outfits to ship missile variants and ships that largely use missiles

- data/remnant missions.txt
Changed `has "Remnant Tech Retrieval: done"` to `has "Remnant: Tech Retrieval: done"` in the branch label in the mission for each outfit.
> Fix branches in Remnant tech missions

- data/frontier jobs.txt
- data/jobs.txt
- data/map.txt
- data/rim jobs.txt
- data/south jobs.txt
Ref: #4243
I gave all pirate worlds the frontier attribute and a regional attribute. In order to avoid any strange job sources or destinations, I then went through some regional jobs to ensure that they wouldn't offer or have a destination on pirate planets. I then went into the jobs files and just replaced `government "Republic" "Free Worlds" "Syndicate" "Neutral"` with `government "Republic" "Free Worlds" "Syndicate" "Neutral" "Independent"`. We can trim some fat from here if we want, though. (e.g. how Jana suggested not having passenger or rush delivery jobs to/from these former pirate worlds.)
The reason I added Independent to all the generic jobs, even some of the regional ones, is because of how future storylines may use the Independent government differently or on different worlds.
> Generic jobs can now offer from independent worlds

- source/Depreciation.cpp
Ref: #4368, #2034
I chose a DAILY_DEPRECIATION value of 0.997 because as outlined in #4368, this value about triples the time it takes to reach various points of depreciation when compared to the old model, where as 1d0fe94 alone didn't actually slow depreciation by very much.
Also added a GRACE_PERIOD constant that delays when depreciation starts kicking in. This allows for players to more easily experiment with various builds for a short amount of time before their items start to depreciate, and the change to DAILY_DEPRECIATION means that once depreciation does start, it isn't as harsh. I've currently put this grace period at 7 days/1 week.
> Slowed the depreciation rate and added a grace period

- data/deep missions.txt
Changed `<planet>` to `<origin>` at a point referencing the current planet; `<planet>` references the destination planet.
> Fix text replacement in Deep: TMBR 0

- source/AI.cpp
This PR fixes #1238.
Escorts make a refuel plan which is based on the target system of the parent ship or the travel plan to the final destination.
> Escorts refuel more reasonably when they have both a hyperdrive and a jumpdrive.

- source/MapOutfitterPanel.cpp
- source/MapShipyardPanel.cpp
MapShipyardPanel and MapOutfitterPanel now update the map coloring when switching between them.
From discord:
> 5:27 AM] Blaank: [bug][0.9.9]  When looking at the map, and selecting shipyards, the icons shown for has shipyard and does not have shipyard are incorrect.  They are identical to the has outfitter selection.  If you select a system, the upper left will correctly highlight if it has or does not have a shipyard but the colored circles are the wrong color.
The map coloring is only updated by DrawSystems() when MapPanel::commodity is changed, however the MapShipyardPanel and MapOutfitterPanel use commodity == SHOW_SPECIAL which draws whether a system has an outfitter/shipyard or not as opposed to ports view where it shows how many outfits/ships are available there.
Added …
> Fixes map not recoloring bug when switching between shipyard and outfitter views.

- source/MissionPanel.cpp
Fixes #4415
Ring around highlighted systems was drawing after, and on top of UI elements.  Draws rings earlier so this does not happen.
> Reordered drawing on map mission panel so rings are behind UI elements.

- data/south jobs.txt
Pirate occupation missions spawn on Quarg worlds, they shouldn't due to Quarg not being involved with human factions/they are much more powerful than any pirate in-game.
> Update Pirate occupation missions to exclude Quarg Planets and systems

- data/ships.txt
This PR is purely cosmetic, and is an effort to redirect the perception and fixation on the Bactrian by making one simple change:
- The Bactrian is reclassified as a Transport.
As @jafdy pointed out in the discussion for PR #4347 , a large part of the problem isn't the stats of the Bactrian, but rather the perception. As such, this PR seeks to rectify that perception in the most basic way: Change the label. After all, the label is the single most easily identifiable way to decide what something is. According to the discussion, the majority involved in the development of the game seems pretty clear that the Bactrian isn't a warship, it is simply a transport that is decent warship. And likewise, everyone seems pretty much in agreement that the Bactrian isn't a great warship when compared …
> Change Bactrian Classification

- data/interfaces.txt
* Moved done button to far right on map screen to be consistent with other interface elements such as shipyard, outfitters, planet landings, player info screen.
* All click areas for these buttons now match button visible areas.  Previously only the zoom +/- buttons did this.
~~Requires #4401 (removes old button code)~~ (merged)
Current version, 14 extra pixel separation.
Initial commit: 
Original:
> Moved done button on map to far right, adjusted button sizes.

- data/governments.txt
- data/persons.txt
*The original Marauder model artist wished to be somewhat dissociated from the person/character.
*Acquiring the Mad Quest no longer incurs "Author" wrath.
*Appears more often, and promotes the side-game of collecting the Marauder ships (as well as player exploration).
*Updated his loadout to more modern outfits - including Nerve Gas, likely causing a fine (upon capture) - to help offset the increase in ship value.
> Update Marauding Max

- source/Command.h
This fixes #4456 where, on architectures that default to unsigned
chars (ppc), turrets would only rotate in one direction.  The logic
in Aim and SetAim depend on the aim array to be able to represent
negative numbers.
> Change aim to be explicitly signed

- endless-sky.appdata.xml
The game title is a proper name and should not be translated. Also the previous German and French translation were a little off… 🙄 (see issue)
Fixes https://github.com/endless-sky/endless-sky/issues/4453
> Do not translate game title

- data/wanderers start.txt
If you land on Vara K'chrai ahead of the transports in `Wanderers Evacuation 1B`, you get the message to wait for the transports and then `Wanderers Evacuation 1C` starts anyway. I think this prevents that, while still preserving the illusion of a single multi-stop mission.
Unfortunately, when trying to test it, I screwed up juggling my snapshots and now have no save from the correct part of the plot.
> Fix "Wanderers Evacuation" to occur in order

- data/map.txt
Working on missions involving specific regions, turns out Bloodsea is the only southern pirate world without the `"south pirate"` attribute for some reason. Now it is not. Small fix.
> add the "south pirate" attribute to Bloodsea

- data/remnant outfits.txt
There has been at least one player who's had a save broken due to losing all keystones in remnant space before obtaining the license (https://steamcommunity.com/app/404410/discussions/0/1639794651173778949/), and therefore being trapped* in it. Although this PR doesn't prevent it from happening, it does make it much easier to escape remnant space. It also makes life easier for players who are outfitting in remnant space and don't want to go all the way up to hai territory.
Admittedly, it's a bit inconsistent with the lore, since the remnant probably wouldn't sell stones to an outsider, but I don't think anyone's going to uninstall the game over that.
*This is technically escapable by two methods, but neither are very intuitive.
> Remnant keystone no longer requries license

- data/remnant missions.txt
This fixes a spelling mistake on line 749 and 846 of `Remnant Missions.txt` that uses hanger (meaning something that hangs stuff) in place of hangar (a structure for storing ships and aircraft). As the later is the correct word, this PR fixes them.
> Fix: Correcting hanger to hangar

- source/PlanetPanel.cpp
Ref: #4508
https://github.com/endless-sky/endless-sky/commit/1df09fcf23afbe81d2729e17be163d9d4c2c83f8 made it so that the bank shows up if the planet is inhabited and if the player has a flagship. This change makes the bank accessible only if the planet is inhabited.
> The bank is now accessible without a flagship

- data/jobs.txt
Something that's always annoyed me about the bounty hunting missions is that one that requires you to hunt down a leviathan and one that requires you to fight a firebird have the exact same name and descriptions, so the only way you can figure out which ones you should take early on is by looking at nothing but the payment.
This changes the descriptions of all bounty hunting jobs so they give you a rough description of what you're going to be fighting.
> Changed the names and descriptions of bounty missions

- source/AI.cpp
- source/Engine.cpp
- source/Mission.cpp
- source/Mission.h
Refs #4307 
Also reduces the frequency with which carried ships that are escorts of a ship that cannot carry them seek different parents.
> Restrict reparenting of mission-affiliated carried ships to the same missison

- changelog
- source/Ship.cpp
This will allow variants with different thumbnails to have their thumbnails be preserved through a save/load cycle. Fixes #4503.
> Save thumbnails, just as we save sprites.

- data/ships.txt
Removing the word "blaster" to reflect the fact that the Protector now carries two anti-missile turrets in addition to the blaster turrets.
Thanks to Hyugat on the ES Discord for pointing out this discrepancy.
> Updating Protector Description

- changelog
- source/MissionAction.cpp
When `requiredOutfits` was implemented, it was included in `MissionAction::Save()` but not `MissionAction::Instantiate()`; since mission( action)s aren't saved until after they've been instantiated, this effectively meant that `requiredOutfits` could never be saved, and also couldn't be checked in any blocks except `on offer`, `on accept`, or `on decline`, all of which would have the same effect: prevent the mission from being offered if the `require` check failed.
This adds a line to copy `requiredOutfits` when instantiating the `MissionAction` object, allowing it to be saved in the save file and used for blocks not checked when the mission is offered.
Fixes #4554 (hopefully).
> Copy requiredOutfits in MissionAction::Instantiate().

- data/governments.txt
The Coalition is made up of species with increased affinity for close-quarters combat. They all move fast. Arachnids and beetles (animals the Arach and the Kimek are based upon) are carnivorous by design and have the benefit of their sturdy carapaces (natural armour) and natural weapons. Even Saryds would benefit from thick hides and strong kicks.
This proposed change reflects that.
Coalition civilians aren't taught to fight well, so they would have to rely on their natural instincts, There's also a possibility that a ship might be crewed by an all-Saryd crew (and they wouldn't be the ideal troops for fighting inside ships). Heliarch crews, however, are always mixed and are trained well to work in concert for their advantage.
> Increase crew attack and defense for Coalition species

- data/variants.txt
As of right now, the Quicksilver and Quicksilver (Mark II) have the *exact* same outfits. This PR changes the Mark II's outfits, upgrading it in the same way that the other Syndicate Mark II ships are upgraded (new shield gennies, better cooling, better power generation, atomic engines), excluding the addition of an Ionic Afterburner.
Error caught by @Kryes-Omega.
> Changed the Quicksilver (Mark II)'s outfits

- data/ships.txt
According to every other ship description, "Southbound Shipyards" is the correct name, and this was probably a transposition typo.
> Make "Southbound Shipyard's" plural in Fury description.

- data/transport missions.txt
I'm not sure about the formatting, since I don't know of any examples of this in the current game.
This makes Courier 2 (the small package mission) have several different offer dialogues, which are generated in the same way as the hail dialogue. For an example of what this can generate: `A resident of Earth approaches you and says, "Sorry to interrupt, but I have a small package that needs to get to New Boston by April 32nd, 3012. I'm willing to pay you 2 credits for it."`. I also made it so that it tells you how much you'll get paid for it 3 out of 4 times. (The current offer never states payment.) The longest possible combination is 237 characters long, which is 43 characters shorter than Courier 3's offer.
> Randomly generate the offer dialouge for Courier 2

- data/hai ships.txt
- data/marauders.txt
- data/ships.txt
In response to Issue #4567 "Making the Arrow Actually Fast", a proposed solution. 
<details><summary>Old PR description.</summary>Note: I'm not saying that this is definitely needed, but issue #4567 requested this change, so I'm PRing this as a possible solution that people can try out. This is probably a "minimal change" version that doesn't come anywhere near allowing the sorts of permanent speed boosts requested in that issue, but it would definitely make the Arrow a bit faster and give it better outfitting potential to be very zippy.
This PR changes:
- the Arrow's drag from 2.7 to 2.6 (increases base max speed from 606 to 630)
- the Arrow's engine space from 60 to 74 (which would give it the space to install an afterburner)
In stock configuration, this has a slight change, most …
> Tweaks to some human transport ship stats to make them more viable choices

- data/remnant missions.txt
As per Amazinite's suggestion in order to maintain consistency with how it is used in the Rim archeology and wanderer missions, this PR replaces all currently existing instances of "datapad" with "data pad". All of these instances are in `remnant missions.txt`
> Fix: Replacing instances of "datapad" in Remnant missions

- data/transport missions.txt
Currently, it is possible for Terraforming 7 to offer on any world that has a spaceport. According to 6, however, Amy is busy in an Earth spaceport. This pull fixes that.
> Added a missing source line to Terraforming 7

- .github/pull_request_template.md
Current GitHub support for multiple PR templates is lacking (url parameters only!) so people will just need to remove the bits that don't apply.
https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository#adding-a-pull-request-template
A UI for picking the template when there are multiple templates is apparently "in the works" for more than a year.
**Link to the rendered markdown: [is here](https://github.com/endless-sky/endless-sky/blob/contrib/pr-template/.github/pull_request_template.md)**
> Draft a PR template

- data/variants.txt
This gives the Frigate (Mark II) a250 atomic thrusters, because it is the only mark II ship that has ion thrusters, which looks out of place in my opinion. This PR gives it matching visuals with the rest of the Mark II ships, without changing the speed too much. It also gives the ship increased energy storage with the excess outfit space.
Suggested by @Arachi-Lover
> Frigate Mark II given matching visuals.

- data/jobs.txt
This fixes a small recently introduced typo in the bounty mission descriptions: lead -> led
> Fix typo in bounty missions

- data/transport missions.txt
One of the offer dialogues in Courier 2 used `<source>` instead of `<origin>`, giving a broken offer dialogue.
This fixes it by simply replacing source with origin
> Fix broken tag in courier 2

- data/remnant missions.txt
This gives " Drak " the same swizzle as the normal Drak, and gives it a favourable attitude toward the indigenous lifeforms to ensure that it continues its protective behaviours.
Thanks to Spookext for reporting the swizzle changing bug.
Change:
- Adds: 
`swizzle 5`
- Adds :
```
"attitude toward"
"Indigenous Lifeform" 1
```
> Fix: Correcting " Drak " swizzle

- data/coalition.txt
- data/governments.txt
- data/hai.txt
- data/hails.txt
- data/wanderers start.txt
- data/wanderers.txt
Ref: #2526, #4549
This PR adds hails to alien governments where they were missing, aside from the Remnant which I think @Zitchas should handle.
These hails aren't meant to be comprehensive, as you may notice that some yield a low number of combinations. I expect @Pointedstick to be able to take what's done here and run pretty far with it so that we have hail diversity in areas that aren't just human space. This PR is mainly for just filling in some holes in alien hails, but this should be expanded upon.
In some instances (Pug, Quarg), the hostile hails and hostile disabled hails are the same. I did this because I felt that the hostile hails fit good enough to also be hostile disabled hails.
> Added missing hails to alien governments

- data/ships.txt
- data/variants.txt
The Mule has been a topic of discussion for some time, as well as the balance between the various human medium warships. (Ref: #4579,  #1598/https://github.com/endless-sky/endless-sky/commit/ece73dc9cab663bf02f15d048b7252469cc65672, #1626, #1627, #3411, #2076) This PR seeks to knock the Mule down a bit, but in lowering the effectiveness of the Mule, I felt that I was making it too similar to some of the other human medium warships, so I made some slight tweaks to other medium warships as well. These tweaks also help to differentiate the various roles that the medium warships are suppose to fulfill. 
These are the roles that I see each medium warship filling:
* **Cheap but Effective**: Splinter, Manta
* **Dedicated Carrier**: Nest, Roost, Skein
* **Combat Carrier**: Aerie
* **Jack of All …
> Better differentiate various human medium warships and knock the Mule down a peg

- data/marauders.txt
- data/persons.txt
While the descriptions are currently not visible anywhere without plugins, they're still full of awkward phrasings and poor grammar; I particularly disliked the constant usage of in-game ship classifications like Medium Warship, which no stock ship description does. While I didn't feel confident enough to completely rewrite them at this time, I figured giving them at least an editing pass would be an improvement.
Mostly the result of @Cat-Lady complaining about them on Discord. I actually did most of this work days ago and then got busy with other things, but I dusted it off, finished the Marauder Splinter, and finally pushed it. I also did most of the work while tired, so let me know if I missed something obvious.
> Basic editing pass on Marauder ship descriptions.

- data/tooltips.txt
**Bugfix:** This PR fixes a bug that an attribute 'movement:' of no-cargo ships has no tooltip.
This PR adds the tooltip text for 'movement:'.
> Add the tooltip text for 'movement:'.

- data/map.txt
- data/pug.txt
- source/Planet.cpp
- source/Planet.h
- source/PlayerInfo.cpp
Ref: #4326
Adds an additional check to PlayerInfo::Fine to see if the planet is inhabited or not. If the planet is uninhabited, it can't fine the player for illegal outfits.
Also removed `security 0` from all uninhabited planets since it is redundant. Notably, this should also make it so that colonized Wanderer worlds will now fine the player, since the events in the Wanderer campaign right now don't change the security of colonized planets.
> Uninhabited planets are unable to fine

- data/tooltips.txt
- source/Account.cpp
- source/Account.h
- source/BankPanel.cpp
- source/PlayerInfo.cpp
- source/PlayerInfo.h
**Feature:** This PR implements the feature request detailed and discussed in issue #4284. 
Maintenance costs have also been requested or discussed in #4591, #3659, #2219, and more.
This mechanic is not intended to be used in vanilla, but seeing as how it has been requested many times, I see this as a worthwhile addition. 
Adds `"maintenance costs"` and `"operating costs"` outfit attributes that work similarly to how crew salaries work. Every day, the total maintenance cost is deducted from the player's credits. `"maintenance costs"` are always active so long as the player owns the outfit/ship while `"operating costs"` only apply to unparked ships. Both will show as `Maintenance` in the bank and with each day that passes.
Overdue maintenance costs have zero effect on the efficiency or …
> Added daily maintenance attributes

- data/wanderer ships.txt
- data/wanderers middle.txt
- data/wanderers start.txt
- data/wanderers.txt
Implements the Riptide (#4102) into the Wanderer campaign by replacing the last set of Deep River transports with Riptides instead, and foreshadows the existence of the Riptide during the first time you see Deep River transports. The first time you see Riptides, they become available to buy and can be seen in Wanderer freight fleets after 30 days.
> Implemented the Riptide into the Wanderer campaign

- data/remnant missions.txt
**Bugfix:** This PR addresses issues in mission "Remnant: Face to Maw2" and "... 2B."
Current version shows "decline" in the conversation:
It should add a indent to be a special tag.
> Fix two missing indents in "Remnant: Face to Maw2/2B."

- data/remnant ships.txt
The Petrels were erroneously converted into being close-quarter fighters. This fixes that change.
*Petrel:*
- restores their fuel capacity to 50, instead of the 100 it was pre-Derp
- ramscoop restored to 0.5, instead of the 1 it was before.
- engine capacity back up to 34, exactly the same as before (and the minimum to fit the crucible engines)
- scanning restored (10 from 12, and 20 from 26. So both ranges are shorter than they were)
- 1 inhibitor cannons again instead of thrashers (they originally had inhibitors. This is a long-range support fighter, NOT close quarters. Remnant aren't suicidal)
- restored the description that explains how the Remnant use these fighters.
*Tern:*
- scanning restored (10 from 12, and 20 from 26. So both ranges are shorter than they were)
> Fixing problematic changes to the Petrel and Tern

- data/governments.txt
- data/map.txt
- data/wanderers start.txt
**Content**
Ref: #4646
Now that the Bactrian has been locked behind a license, there's been some discussion of whether the Shield Beetle should be license locked, since it is now the most powerful non-license locked heavy warship. This is actually a question I've been contemplating since as far back as [late February 2018](https://trello.com/c/Ayg35ZeX/71-shield-beetle-unlock#action-5a94fa4f85224b44022f657f). 
Part of my rationale for locking the Bactrian behind a license was that the next best heavy warships below it are the Falcon and Leviathan, which are both rather weak in comparison, while all similar ships (Cruiser, Carrier, Dreadnought, Kestrel), require a license (or some story) to obtain. The same thing is now true for the Shield Beetle; all comparable ships (Bactrian, Cruiser, …
> Made Hai-home unbribeable and increased the required reputation

- data/events.txt
- data/free worlds middle.txt
Ref: #4172
The difficulty of this mission has been of concern for a while now. This change should make stealing an electron beam more consistent and reasonable now.
1. Wei no longer spawns large Republic fleets doing the duration of the mission. Given that the player is only expected to be in a single ship, it's unreasonable to expect the player to be able to either take on a large Republic fleet solo or be capable of always evading a large Republic fleet when jumping to Alnasl.
2. Greatly reduced the spawn rate of Mark II Gunboats in Alnasl, and added an NPC Gunboat spawned by the mission. This means that the player is guaranteed to run into at least one Gunboat in Alnasl upon entering, and is less likely to have to deal with multiple Gunboats at once.
> Make stealing an electron beam more consistent and reasonable

- source/AI.cpp
- source/AI.h
The variables that control the players auto-pilot had names like "keyStuck" and "autopilotCancelKeys". But those names were confusing, since the autopilot can also be controlled by the mouse.
I changed the variable names to something which I expect is more clear.
This PR only changes variable names.
> Renamed auto-pilot variables to make their function more clear

- data/wanderer ships.txt
The Strong Wind is described as a science vessel that has been retrofitted for combat. Given the Wanderer's focus on terraforming activities, it makes sense to me that their science vessel would have very powerful sensors related to that.
This PR adds the following to the Strong Wind:
- "asteroid scan power" 100
- "atmosphere scan" 100
- "tactical scan power" 20
This could result in the Strong Wind being an interesting candidate for a late-game mining ship for players so inclined. This change shouldn't have much impact on combat, but will help the Strong Wind feel a bit more unique than "just another warship."
> Boosting the Strong Wind

- data/marauders.txt
the description of the Marauder Firebird at one point mentions, like in other Marauder ships, how it has more shields and hull:
"With extra ..., hull plating"
but the MFirebird actually has *less* hull than it's normal counterpart, having 3000 for the Marauder version vs the 3400 for the standard.
In the same fashion as for other Medium Warships such as the Splinter and the Manta, and how their Marauder versions have 250 more hull than the Standard ones, this increases the Hull of the MFirebird to 3650.
> Update MFirebird Hull

- data/events.txt
- data/free worlds checkmate.txt
- data/free worlds epilogue.txt
- data/free worlds intro.txt
- data/free worlds middle.txt
- data/free worlds reconciliation.txt
- data/free worlds side plots.txt
- data/free worlds start.txt
- data/ships.txt
- data/wanderers middle.txt
- data/wanderers start.txt
Addressing a number of small issues pertaining to the FW Campaign all at once.
- Normalize Ijs vs Eyes, at least within the same mission (#2585)? **Doesn't seem necessary.**
- Epilogue for Tomek (mentioned in #2663). **Will change in or post #4672.**
> FW campaign changes

- data/remnant ships.txt
**Bugfix:** This PR addresses the fact that the Penguin does not have gaslining.
adds `"gaslining" 1` to the Penguin
Thanks to BeccaBunny for spotting this. I have no idea how I missed it, considering how much I like using the Penguin.
> Fixing the lack of Gaslining on the Penguin

- data/tooltips.txt
- source/Outfit.cpp
- source/OutfitInfoDisplay.cpp
- source/Ship.cpp
- source/Weapon.cpp
- source/Weapon.h
Ref: #4223
Using the syntax from #4223: `ammo <outfit name> <number of outfits consumed>`. Putting no number is the same thing as putting one. 0 ammo usage is allowed, but the ammo outfit must be installed in order to fire.
This displays in game as a new line underneath ammo called "ammo usage". Ammo usage will only appear on weapons that consume something other than 1 ammo per shot.
> Extended the ammo attribute to specify how much ammo is used per shot

- data/coalition outfits.txt
**Bugfix:** This PR addresses a spelling mistake in the "Overclocked Repair Module" description
1. replaces `unparalled` with `unparalleled`
2. changes the sentence structure from: `providing unparalled hull repair in all of Coalition space.` to `providing hull repair unparalleled in all of Coalition space.`
The previous sentence implies that it is an outfit that provides great hull repair that works throughout coalition space. The revised sentence implies that it is an outfit that provides the best hull repair that can be found in coalition space. Basically, the placement of the word 'unparalleled" in the current version makes it sound like the hull repair only works in coalition space.
Thanks to Mr. Doom on the Endless Sky Discord for spotting the spelling mistake in "unparalled".
> Fix overclocked repair module

- data/free worlds checkmate.txt
- data/free worlds middle.txt
Ref: #4671 (Forgot about this issue for the first PR.), #3772, #4672
A plot hole that I've seen brought up before concerns how the player gets punished in FW start for invading Bloodsea, but is given the option to invade Bloodsea in FW middle without consequences. This is brought up in #3772, where I highlighted how it is somewhat addressed after a single choice, but I feel that it isn't explained well enough currently, especially given that it's only explained by a single line that you only see if you choose the correct dialog.
* The leaders of Bloodsea now recognize you if you invaded them previously.
* Alondo now references the Tomek situation and explains why it's different now.
* Should you choose to invade, Alondo contacts the Senate for …
> FW Middle: (better) explain why attacking Bloodsea is fine now when it wasn't before

- data/intro missions.txt
**Bugfix:** This PR addresses issue #4707 
Jame's transport intro mission includes James giving the player instructions that "if they want to be safer, they should sell their gun." There are three options for resolving this:
A) give the shuttle a blaster
B) change Jame's dialogue to specify that the player should *avoid* buying a gun, rather than telling them to sell the one they have.
C) remove that section of dialogue entirely.
This PR is option B.
Note: Only one of option A or B should be implemented. When one is merged, the other should be closed.  Option [A can be found here.](https://github.com/endless-sky/endless-sky/pull/4708)
> Fix: James's intro mission - B: Change James' dialogue

- data/free worlds reconciliation.txt
If the player has a Jump Drive in the mission, FW Pug 2C, when they get a Jump Drive, normally nothing comes from it. With these changes, the player's Jump Drive will be noted by people in conversations a couple of times, and an extra Carrier with fighters and drones will accompany the player into occupied space, using the Jump Drive that the player would have taken but didn't need.
This is my first PR, so I might have got stuff wrong. If I have, then _please_ tell me, and I'll fix any issues.
> Extra ship in FW/Navy fleet attacking Pug if player has a Jump Drive

- source/Engine.cpp
**Bugfix:** This PR addresses issue #4729
PR #4513 adds an additional parameter to the statuses constructor, but the scan rings still needed to be updated. This PR adds the additional parameter also for the scan rings.
Performed an in-system flight performing a scan (with and without status overlays)
- The overlay rings show up properly.
- The scan rings show up properly.
Not provided, but any game with a flagship with cargo and/or outfit scanners can be used to verify.
> Bugfix: Add additional status parameter to scan rings emplace_back.

- data/map.txt
**Content**
This change adds `spaceport ""` to the attributes for all the internal Ember Waste and Remnant wormholes. As such, NPCs and Fleets that have the appropriate Key Stones should at least occasionally use the wormholes to exit the system instead of simply jumping back wherever they came from. 
Thanks to RightHand on the ES Discord for noticing this.
edit: This has been modified so that it only applies to those wormholes *within* the Ember Waste. It does not change the Ember Threshold, so NPCs should still ignore it.
> Updating Ember Waste Wormholes so they will be used by fleets

- source/AI.cpp
- source/AI.h
- source/Command.cpp
- source/Command.h
- source/Engine.cpp
- source/Engine.h
**Feature:** This PR combines all input-device signals in the Engine class into a single input towards the AI class
This PR combines the inputs from the keyboard and the mouse into a single activeCommands Command variable and sends the inputs through this variable into the relevant AI functions.
Keyboard inputs were moved into the Engine class for this.
N/A
I tested all the relevant input scenarios that I could come up with;
- MENU
- MAP
- INFO
- FORWARD, LEFT, RIGHT, BACK, PRIMARY, AFTERBURNER
- SCAN
- DEPLOY
- HAIL
- BOARD
- CLOAK
- LAND (autopilot)
- LAND (switch landing targets)
- LAND (landing based on mouseclick)
- JUMP (autopilot)
- JUMP (insufficient fuel warning)
- JUMP (WAIT, fleet waiting for jump)
- TARGET (cycle through enemy ships)
- NEAREST (cycle through friendly ships)
- …
> Combined single (keyboard and mouse) input from Engine towards AI

- keys.txt
- source/Command.cpp
- source/Command.h
- source/PreferencesPanel.cpp
- source/main.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #2738
This PR makes the fast-forward key configurable. It does not make using Caps Lock for low framerate in debug mode configurable, however.
This would be helpful for people using Caps Lock as a compose, layout switch, or second escape key.
It also makes the fast-forward feature easier to discover.
The fact that Caps Lock still toggles low framerate in debug mode means that one can use fast-forward in conjunction with it, for example to reproduce a bug which occurs only after some time.
(Note: It would be nice if the keybinding is listed in [the manual](https://github.com/endless-sky/endless-sky/wiki/PlayersManual#key-bindings-and-shortcuts), even if this PR is not merged)
| Before | After |
| --- | --- …
> Make fast-forward key configurable

- source/PlayerInfo.cpp
This allows checking crew-related conditions of the player flagship. Attached is a file to test.
This allows directly checking for `"crew"`, `"required crew"`, and `"bunks"` in the same way that `"cargo space"` and '"passenger space"` work now.
[test flagship conditions.txt](https://github.com/endless-sky/endless-sky/files/3220562/test.flagship.conditions.txt)
Note: recommend not merging until after the next stable release.
> Add flagship crew info to conditions. Partially implements #4286

- source/Mission.cpp
- source/Mission.h
- source/MissionAction.cpp
- source/MissionAction.h
- source/PlayerInfo.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #4565.
Implements a similar system as #4526 for on visit dialogs by telling the player how many other incomplete missions they have at this location instead of spamming them with a new dialog for each mission. The on visit dialog that gets shown is currently simply from the first mission in the list. Unique missions (i.e. one time missions) will show their dialogs separately from non-unique (i.e. repeatable) missions. If you have multiple non-unique on visits and any of them have deadlines, then you will be reminded of that.
See https://github.com/endless-sky/endless-sky/pull/4592#discussion_r334246030 for more screenshots of various cases.
> Combine multiple on visit dialogs into a single dialog to avoid being spammed

- source/PlayerInfo.cpp
**Urgent Bugfix**: Fixes issue  #4750.  The game crashes on new pilot creation due to dereferencing a null pointer to the flagship.  The fix sets the flagship bunks, crew, and required crew to 0 when no flagship exists.
This is an ***urgent*** fix.  It is presently impossible to create a new pilot.
> (Urgent) fix for New Pilot crash

- data/governments.txt
- data/hai missions.txt
- data/map.txt
This PR adds a spaceport to Wormhole Alpha. Enabling NPCs and fleets that spawn in Waypoint to land on the wormhole.
Thanks to @Zitchas for suggesting this, as I only thought of doing it for the Remnant wormholes in #4737
> Adding a spaceport to Wormhole Alpha and reworking containing systems

- data/remnant missions.txt
- data/remnant outfits.txt
Ref: #4491, #4493
This PR adds a mission that accounts for the scenario where the player enters the Ember Waste but loses their jump drive and/or quantum keystone for whatever reason and becomes stuck. The mission will only offer if the player doesn't have a quantum keystone/key stone and doesn't have a jump drive. Once the player is in this situation, they will trigger and event on a 14 day delay that triggers the mission. This delay is so that the player gets a sense of being stuck before help shows up. I just thought it'd be more interesting that way. 
This change reverts #4491 since that change will no longer be necessary to get the player out of this scenario.
Also, felt like pinning down the Caelian description with some story. Let it be known that the Remnant found out that the …
> Added a mission that helps the player if they become stuck in the Ember Waste

- data/remnant missions.txt
- source/Mission.cpp
Ref: #4409 #4491
These additional missions account for the player not always reaching the Ember Waste with a Quantum Keystone. These missions also make it explicit to the player that the keystones are used to enter the wormholes in the region.
The possible scenarios are now as follows:
* The player arrives in the Ember Waste with a Hai Keystone and is approached by the outfitter manager. This is currently the only possible way to progress the Remnant story.
* The player arrives in the Ember Waste without a Hai Keystone, but does know about the Hai. After helping the Remnant with one set of missions, the outfitter manager may approach the player asking them to search for alternative sources of Key Stones, to which the player will answer that they know of one such location.
* The player …
> Added additional Remnant: Key Stones missions 

- data/free worlds reconciliation.txt
For the FW Pug 2C missions where the player is given a Jump Drive by the Syndicate, having both a Hyperdrive and Jump Drive installed will result in the Syndicate removing your HD and giving you a second JD. 
Giving FW Pug 2C: Jump Drive priority means that this mission will prevent the Hyperdrive and Scram Drive versions of the mission from offering if the player has a jump drive already.
<details><summary>Old description</summary>This PR makes it so that the Hyperdrive and Scram Drive versions of this mission now check to make sure that the player doesn't have a JD already.
Note: This change will make it so that the player's entire fleet is checked for a JD, even though the mission states that only the flagship is being checked. Will need to extend the behavior of `require` to be able …
> Give FW Pug 2C: Jump Drive priority so that you aren't given an extra JD

- source/Engine.cpp
Resolves #4755.
Conflicts with #4745; awareness of full stop must be added to this change.
Implements this behavior:
1. Press J, B, or L to begin an autopilot action. (Or whatever you've assigned jump, board, and land.)
2. Hold down the button; do not release
3. Use movement keys. This cancels autopilot, as expected.
4. Stop using movement keys.
5. Autopilot resumes its action because J, B, or L are still pressed.
Previously, in step 5, the button was ignored.
> resume jump/board/land autopilot when movement keys are released

- .github/workflows/build_parse.yml
... As they can cause runs to fail at any time, see
https://github.com/dotnet/core-setup/issues/7778#issuecomment-523518122
https://github.com/endless-sky/endless-sky/pull/4756#issuecomment-578366139
**Bugfix:** This PR addresses an issue raised by [this action run](https://github.com/endless-sky/endless-sky/pull/4411/checks?check_run_id=408031429).
Refs #4757.
The run failed because `sudo apt-get update` was called, while Microsoft's repository was apparently taking a nap or something. This appears to be a [frequent issue](https://github.com/dotnet/core-setup/issues/7778#issuecomment-523518122), which isn't nice for test runners that should be as reliable as possible.
This PR removes all package lists using `packages.microsoft.com` at runtime. Specifically, those are lists for `dotnet`, …
> fix: CI: Prevent usage of microsoft's ubuntu repos

- source/Mission.cpp
As described in #4765, the map panel only runs basic checks in `Mission::IsSatisfied` and never checks the actual completion conditions. That causes some missions to be displayed as being able to complete, even though they can't.
This fix moves the test of completion conditions from `Mission::CanComplete` into `Mission::IsSatisfied` (which is called by `Mission::CanComplete`).  
A consequence of this is that we cannot lie to the player about the completion conditions quite so easily.
> consider completion conditions when coloring missions in map panel

- data/governments.txt
- data/hai missions.txt
- data/remnant missions.txt
- data/wanderers middle.txt
- source/GameData.cpp
- source/Government.cpp
- source/Government.h
- source/LocationFilter.cpp
- source/NPC.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #4767 
- Adds a government keyword `"display name"`
- Defaults the display name to the name used in the data files
- Updates `Government::GetName()` to return the display name
- Adds `Government::GetTrueName()` for places where the datafile token is required.
- Updates the current governments that use spaces to have the targeted display name
> feat(government): Allow customization of the government's displayed name

- source/ConversationPanel.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #4718 
Since conversations are more important than dialogs, don't let the player accidentally skip through them just because they were holding return to close a number of dialogs that appeared.
The easiest way to verify the behavior is to compare the "new pilot" process. Enter your character's name, then hold Enter. On `master`, the post-name panel will close shortly after it is accepted. With this PR, you must release Enter and press it again.
> refactor: Require a new press to exit a conversation or select a choice

- data/map.txt
despite the Kimek being an older species, the Arachi ringworld (Ring of Wisdom), which the quarg naturally would have started building later than the Kimek ringworld (Ring of Power), Ring of Wisdom shows signs of being more complete, being one large piece, nearly fully completing the circle, while Ring of Power has several, separated parts. this also shows in the number of landing spots, with Ring of Wisdom having 5, and Ring of Power having 4.
this changes that by swapping the rings's sprites, now RoP is the single large segment with 5 landing spots, and RoW is the more fragmented one with 4 landing spots.
> Swap RoP and RoW

- data/free worlds middle.txt
Ref: #4172 
Adds two missions that hint to the player where they should go to find the best place to steal an Electron Beam.
The first hint offers by landing on a Free Worlds planet near Wei. A FW captain informs you that the Navy is heavily patrolling the Wei system, so you'll likely need to find somewhere else to steal an Electron Beam from.
The second hint offers by landing on Hope in the Wei system. You tap into the surveillance rigs that the player and Freya set up in FW start and find that only lone Gunboats seem to be entering or coming from the Alnasl system., directly pointing you in that direction.
> Hint missions for stealing an Electron Beam

- data/wanderers start.txt
Adds a new Wanderer mission between Wanderers Conversation and Wanderers: Defend Vara Ke'sok, to direct the player towards Wanderers: Defend Vara Ke'sok.
[test 6.txt](https://github.com/endless-sky/endless-sky/files/4113305/test.6.txt)
Simply take off, land, and check the spaceport until you get offered the mission.
> Added Wanderer Mission that leads to Wanderers: Defend Vara Ke'sok

- source/AI.cpp
- source/Ship.cpp
- source/Ship.h
This PR fixed 2 issues that tehhowch mentions in https://github.com/endless-sky/endless-sky/pull/4288#pullrequestreview-258137829.
If an escort has no destination, Ship::JumpsRemaining() try to use the parent's destination.
> Ship::JumpsRemaining() calculates the jump counts a bit more optimistically.

- source/AI.cpp
- source/AI.h
- source/Engine.cpp
**Bugfix:** This PR addresses an issue regarding Engine keyboard input reading while the game is paused (as reported on Discord)
The engine is continuously running (at 60 fps), even when the game is paused, to ensure that functions like drawing of the main flight screen are continuously active.
Some functions like movement of ships, movement of projectiles and player commands to his/her flagship and fleet should however be suspended when the engine is not active.
This PR changes the reading of keyboard inputs to only register those inputs when the game is not paused.
I didn't have time yet to extensively test this PR; it needs some more testing before we can merge this.
> Only handle Engine keyboard inputs when the game is not paused

- source/Format.cpp
- source/Format.h
- source/Phrase.cpp
- source/Phrase.h
This PR adds 2 functions to the phrase node in order to avoid combinatorial explosion.
ref. #4533 and [this comment](https://github.com/endless-sky/endless-sky/issues/558#issuecomment-487903300).
(1) phrase expansion
A word in the phrase node can include phrase expansions:
```
phrase "buy and sell"
word
"buy ${contraband} from"
"sell ${contraband} to"
```
"contraband" is a phrase name.
(2) child node "replace"
The "replace" node specifies the way of replacement some strings.
```
phrase "test phrase"
word
"I suspect that"
word
" "
word
"the CEO of the Syndicate%"
"the leaders of the Syndicate"
word
" "
word
"don't have our best interests at heart."
"are keeping secrets from the rest of the galaxy."
"try to do right by people."
replace
"% do" " does"
"% are" " is"
"% try" " tries"
"%" "" …
```
> Add phrase expansion and replacement functions to the phrase node.

- data/hai missions.txt
**Bugfix:** This PR addresses issue #4811
Corrected a "soptovers" which was presumably supposed to be "stopovers".
> Typo: soptovers -> stopovers (@otsohelos)

- .gitignore
- EndlessSky.cbp
- EndlessSky.xcodeproj/project.pbxproj
- source/GameWindow.cpp
- source/GameWindow.h
- source/main.cpp
**NEW:** GameWindow Class. Contains all SDL window code that was in main.cpp
This resulted in changes to the order of operations to untangle SDL window code from other initialization tasks. The Window appears earlier in the loading process but otherwise appears the same to the user.
I modeled the class after the Audio class. Similar naming and use. One benefit is that initialization cruft that used to be in main has a smaller scope and can die when it's done, leaving only properties that we need to use later. 
_Curly's Law: Do One Thing_
To keep main short and sweet it initializes everything and then calls GameLoop, where the main loop lives. Reading main is now just reading a list of things. This makes 100% of real work done in modular bits. 
**CHANGE LOG:**
WAS: Normal VSYNC on.
NEW: …
> NEW CLASS: GameWindow

- data/deep missions.txt
**Content ( Missions )**
Simple remove auto launch line from this one mission. There's no urgency in the text, and I wanted to buy commodities before I left the planet.
This is an old change so I don't have any save files
- [ x ] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified
- [ N/A ] I uploaded the necessary image, blend, and texture assets here: {{insert link to assets}}
- [ N/A ] I created a PR to the [endless-sky-high-dpi repo](https://github.com/endless-sky/endless-sky-high-dpi) with the `@2x` versions of these art assets: {{insert PR link}}
> Don't auto-launch after accepting Project Hawking mission

- data/free worlds intro.txt
- data/outfits.txt
- data/ships.txt
despite being their strongest ship, the Dreadnought isn't restricted by the Free Worlds' current Militia Carrier license. When new storylines roll in, I'd imagine you'd have the Dreadnought be like a Cruiser or Carrier right now, not buyable unless you did the storyline of it's faction.
this changes the Militia Carrier License to just Militia License, adjusting the description, the mission that gives it, the licenses required for both the Skein and the Dreadnought, and also adding a mission to replace the Militia Carrier License in old saves with the new one.
> FW license

- data/free worlds intro.txt
Removed a tab at the start of the `on complete` dialog of `"FW Escort 3"`
> Fixed unnecessary tab

- .github/workflows/cd.yaml
**Feature:** This PR implements a continuous deployment targeting 64bit Linux distributions.
Upon publishing a release, an actions run is triggered, which will build an AppImage and upload it to the release.
Example Release: https://github.com/MCOfficer/endless-sky/releases/tag/test-deployment
> feat: Add initial CD (64 bit AppImage)

- data/deep jobs.txt
**Bugfix:**
The wording used in the phrase "deep mystery cube dropoff payment", which is in the on complete dialog of Deep Mystery Cube jobs, assumes features specific to a planet. However, Deep Mystery Cube jobs can still have a destination of a space station, making the phrase seem out of place. This fix stops the main mystery cube jobs from choosing stations as a destination. This pr is a variant of #4827 without the replacement jobs.
> Stop Mystery Cube Jobs from going to stations

- changelog
- data/remnant missions.txt
**Bugfix:**
Players getting stuck at the start of the Remnant storyline if they somehow miss the Keystone missions or happen to decline/abort them because they sound like a frivolous money-making scheme instead of a progression-locking mission.
Adds an alternate route to meeting the requirements for the Remnant basic license. This is done by allowing the completion of the second mission in the Broken Jump Drive mission series to count in place of the Keystone missions. The second mission was chosen because while the first BJD could be triggered by chance, doing it again demonstrates that the pilot is intentionally seeking to help the Remnant. On the flip side, it doesn't force the player to complete the whole BJD set right away. (It is intended to be an optional set that affects timers …
> Remnant: License Aquisition Options (and rejection tolerance)

- data/remnant missions.txt
**Bugfix:** This PR addresses the issue where players using a pilot file from before the addition of the "Return the Samples 2 timer" are unable to trigger the Face to Maw missions.
This adds a small reverse compatibility mission to fix pilot files for players who completed Return the Samples 2 before it had the timer.
> Adding Return the Samples 2 reverse compatibility

- data/remnant ships.txt
**Bugfix:** 
This PR addresses the discrepancy that the penguin does not have a listed license requirement. 
It fixes it by adding the basic Remnant license as a requirement to the Penguin.
> Fix: Adds license requirement to the Penguin

- copyright
Apparently I forgot to properly list the thumbnail entries of the Betelgeuse and Southbound redesigns. This PR adds them, under the relative sections
> Added missing copyright entries

- data/governments.txt
Changes:
- Indigenous Lifeform added at 0.05
- Korath reduced to -0.05
- penalty for assisting increased to -0.25
- penalty for capturing or destroying increased to 10
Purpose: To allow people to gain reputation from killing the Korath (which the Remnant appreciates), and to have a positive opinion of the Indigenous Lifeforms (because the Remnant don't want the Archons to hate them any more, and they also consider indigenous lifeforms to be valuable. Thus, they will be upset when the lifeforms are killed.
Likewise, the Remnant are few in number and place a high value on survival and life. Thus a larger-than-average appreciation for their ships being repaired, and a much stronger than average hatred for their ships being captured or destroyed (both of which results in the entire crew being …
> Remnant: Allow gain of reputation

- data/deep jobs.txt
**Bugfix:**
The wording used in the phrase "deep mystery cube dropoff payment", which is in the on complete dialog of Deep Mystery Cube jobs, assumes features specific to a planet. However, Deep Mystery Cube jobs can still have a destination of a space station, making the phrase seem out of place. This fix stops the main mystery cube jobs from choosing stations as a destination, and adds a new job and phrase specifically for Mystery Deliveries to stations. #4831 is a version of this pr without the replacement jobs.
The job was tested for whether it could offer and whether the on complete dialog would be correct. Omnis was used for a faster set up, and the ship was chosen for no particular reason.
This save file can be used to verify the bugfix. The bug will occur when using …
> Mystery cube jobs for stations

- data/remnant missions.txt
This fixes the "remnant salvage available" event, which currently has capitals and the standard for ES is for events to be entirely lowercase.
There are no missions that currently depend on this event, but probably will in the future.
> Fix: Normalizing remnant salvage available capitalization

- source/Engine.cpp
**Bugfix:** This PR addresses a command ghosting issue reported on steam
https://steamcommunity.com/app/404410/discussions/1/1750149787514366978/
The engine is only reading commands while it is active, but any key that
was pressed before the engine became active (and that is still pressed
when activating the engine) should not be seen as a new keypress.
This commit fixes that by discarding the very first commands read when
the engine becomes active.
Tested departing using 'd' with a ship with fighters (with and without this change). Without the change the fighters were deployed on launch, with this change the fighters were not deployed on launch.
None provided. Any ship with fighters or drones would be fine.
> Clear ghost commands from when the engine was not active

- data/news.txt
This fixes a 1-character typo in the technical writer news text.
N/A
> Fix a typo in news as reported on Discord

- source/AI.cpp
- source/AI.h
**Feature:** This PR changes the target in CircleAround, Swarm and KeepStation from Ship to the more generic Body class
This change will make those 3 functions also available for future changes that might want to use those functions with targets like asteroids, formation-positions or planets.
The 3 functions only use properties which are already available in the Body base-class; so there was no need to use the more specific Ship parameter.
N/A
This can be relevant if we want to use KeepStation (with different internal parameters) for formation position keeping in #4471 .
Compiled (it compiles) and started the game. Function parameters are normally checked at compile time, so just checking compilation this should be okay as long as ES doesn't generate new function calls at runtime.
None …
> Change CircleAround, Swarm and KeepStation to use Body target

- data/coalition weapons.txt
despite being a Tier above the Hai, and focusing heavily on military actions, the Heliarch's Ion Rain Gun is at best a very sad sidegrade of the Hai Ion Cannon, losing half the range and having over 4 times the firing energy for an extra 12 shield damage per second, *30 less hull damage per second*, and 200 *less* ion damage per second.
Now of course the Ion Rain Gun is considerably smaller than the Ion Cannon, but if we analyze the two based on attributes/s (per space), we have the following:
Ion Cannon= 3.5 shield damage/s, 1.2 hull d./s, 10.6 ion d./s | 2.5 firing energy/s, 3.1 f. heat/s
Ion Rain Gun= 10.5 shield damage/s, 1.7 hull d./s, 17.6 ion d./s | 10.5 firing energy/s, 3.5 f. heat/s
So, 3 times the shield damage, a .5 increase to hull damage, and not even double the ion damage, …
> Buff Ion Rain Gun

- source/main.cpp
**Bugfix:** This PR addresses issue #4880
Changing the order so that UI takes priority makes it so that fullscreen and fast-forward toggles are only activated if there is no active dialog taking input instead. You can think of it as making main() the root panel in the stack.
Tested with some parts of the game, things seem to not break in unexpected ways. 
Not applicable, can easily be verified with a new or existing save using the instructions in #4880.
> Make Fast forward and Fullscreen keys not override UI inputs

- data/jobs.txt
- data/paradise world jobs.txt
These commits add 5 new bulk passenger transport jobs that shouldn't spam things too much.
If you choose the playstyle where you run around with a sizable escort fleet you reach a point where the only jobs you ever take are the ones whose destination is a place you were already planning to stop at - because anything else just isn't cost effective.
The only exceptions to this are Colonist delivery missions, and occasionally strike breakers if you can pick up more than one for an area.
Colonist missions only really flow in one direction also, which makes them not all that common unless that's the direction you're going. This can make doing things in human space a tinsy bit dull if you were otherwise enjoying rolling around doing mission-running amidst your plot and other shenanigans. …
> A couple more Bulk Passenger jobs for balance and diversity

- .github/workflows/cd.yaml
**Bugfix:** This PR addresses an issue that arose in [this run](https://github.com/endless-sky/endless-sky/runs/495166301)
Continuous Builds always build a "version string" from the current commit message, which then gets put in credits.txt. The regex that did this could break when this version string contained a `/` and (potenially, untested) something like a `$1`. 
With this PR, the regex delimiter is now the lesser-used `|` symbol. In case a `|` or `$` still appears, it is replaced by a `_`. Since there is now bash string substitution for the sake of clarity, `"` is also being replaced by `'`.
This should make the regex resilient enough to build every time - probably not resilient enough for straight up sabotage, but enough for unexpected side effects.
Tested locally, since the …
> CD: Don't break with some special characters in commit messages

- data/governments.txt
The `"Hai"` and `" Hai "` governments should be identical in every way except wormhole access. If there is a need for a Hai government that can go through the wormhole, but should be treated differently, then it should be added separately. This fix is needed for pull request #4901 and is already incorporated into that PR.
> Same affinity towards "Hai" and " Hai " governments.

- data/tooltips.txt
- source/OutfitInfoDisplay.cpp
- source/Ship.cpp
- source/ShipInfoDisplay.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #2508. Also, turns out #2618 existed, so this is really just that PR redone.
Adds an attribute `"solar heat"` that would allow an outfit/ship to produce heat given its distance to the system center. Meant as a counter to solar collection's energy production given the distance to the center.
This PR does not add this attribute to any outfit, only implementing the mechanic to be used.
I'll note that I didn't use the same `"solar heat generation"` name as #2618; solar collection isn't `"solar energy generation"`, after all. 
```
outfit "Small Collector Module"
...
"solar collection" .8
"solar heat" .4
```
It builds and the CI tests pass. That's about all the testing I've done.
N/A
> feat: Solar heat mechanic for increased heat generation the closer you are to the system center

- .github/workflows/cd.yaml
- .github/workflows/cd_release.yaml
- build_appimage.sh
- utils/build_appimage.sh
**Feature:** This PR adds an AppImage to the CD.
Thus far AppImages were only build for releases. Since tarballs can link against libraries that the target system doesn't have, AppImages are a better choice for distributing portable linux packages.
This PR extracts the build steps into a script `build_appimage.sh`, which both the CD and Release CD use. It also fixes an issue with the Release CD's version number.
Please advise on where to put `build_appimage.sh`. Do we want a folder specifically for CI/CD scripts, similar to `test`?
https://github.com/MCOfficer/endless-sky/releases/tag/appimage-test-2
https://github.com/MCOfficer/endless-sky/actions/runs/55112999
> feat: CD: Also build AppImage

- source/PlayerInfo.cpp
**Feature:** This PR implements a feature to publish the flagships location (system and planet) in the player conditions.
This adds two new conditions:
```
"flagship planet: <planet-name>"
"flagship system: <system-name>" 
```
Those conditions can be used during automatic tests to put asserts on the location of the flagship.
N/A
To be used during automatic testing as a condition to wait for or to assert on.
Verified that the conditions get set (on Shangri-La in the Polaris system) and that the conditions get updated/rewritten (on Amazon in the Schedar system).
No significant impact expected, those conditions are only calculated on major events like departing or landing.
> Add flagship System and Planet to player conditions

- source/Depreciation.cpp
**Bugfix:** This PR addresses issue #4912.
MAX_AGE is now 1000 + GRACE_PERIOD (i.e. 1007). 
This makes it so that Depreciation::Save and Depreciation::Buy will use 1007 as the age for fully depreciated items instead of 1000 as is used currently, which meant that you'd actually gain back 7 days of depreciation (as seen in #4912).
Simplified the linear equation in Depreciation::Depreciate as a result of this change. The outcome of the Depreciate function has remained unchanged, though.
> fix: Account for the depreciation grace period in the max age of an outfit or ship

- data/remnant/remnant missions.txt
**Bugfix:** This PR addresses issue #4937 
Fixes erroneous use of "remnant taely" by replacing it with "remnant met taely".
Thanks to ErdrickXLII for reporting this in issue #4937.
> Fix eroneous varriable in Remnant: Face to Maw 2

- source/Ship.cpp
**Feature:** This PR implements ~~the feature request detailed and discussed in issue #{{insert number}}~~ a feature I thought of while updating #4520.
Right now, if an outfit that repairs your hull or regens your shields has a negative energy or fuel cost, that blocks your hull or shields from being repaired/regenerated. This simple change makes it so that negative `energyCost` or `fuelCost` values no longer block repairs by causing the `available` repairs to become negative.
Note that this will still run into the issue of negative attributes being blocked on install, ref: #4682.
N/A
The following shield generator would produce energy when in use (after you've forced it onto the ship):
```
outfit "Ion Converter"
...
"shield generation" 1
"shield energy" -1
...
```
None.
N/A
> Allow negative repair costs

- data/ka'het/ka'het missions.txt
Adjusting a sentence where Taely talks about the Ka'het and their tech. This adjustment just tweaks the wording so that Taely states that the Ka'het are a source of inspiration instead of they are their *main* inspiration.
While the Remnant certainly draw much inspiration from the Ka'het, I'd like to keep it a touch more vague about where they draw their inspiration from. Stating that the Ka'het are a source of inspiration is good. Stating that the Ka'het are their main source of inspiration is just a bit too absolute.
> Tweak: Remnant-Ka'het, Taely's dialogue

- .github/workflows/cd.yaml
- .github/workflows/cd_release.yaml
**Bugfix:** This PR potentially addresses issue #4923
We shouldn't be linking against the newer version of glibc shipped with Bionic when Xenial is still LTS. With this PR, AppImages are built on Xenial.
Tested in a clean Xenial VM. There are opposing results in #4923, however, so this is just a low-hanging-fruit fix.
> fix(cd): Compile AppImages on xenial rather than bionic

- data/map.txt
**Bugfix:** This PR addresses a typo in the description of Kaeyin.
> fix: Typo in Kaeyin description (@Mr. Doom)

- data/human/deep missions.txt
- data/human/transport missions.txt
**Bugfix:** This PR addresses issue #4965
Added the `minor` tag to "Inheritance Redirection" and "Hauler VI cargo prototype 1", and removed the tag from "Deep: Mystery Cubes 1" and "Deep: Scientist Rescue Timer".
> Added and removed `minor` tags from certain missions

- data/human/marauders.txt
minor nitpick, MArrow Engines' description mentions a "third engine mount" that isn't there.
this changes the description to comment on how the engines were expanded.
> Update Marauder Arrow (Engines) description

- data/human/transport missions.txt
~~In the "Hauler VI cargo prototype" missions, the Hauler VI is referred to. This is an odd choice in my opinion, as VI means 6, not 4, and the Hauler IV (4) would be the logical step up. This PR changes all mentions of "Hauler VI" to "Hauler IV". An alternative solution could be to keep it as the Hauler VI, but add a bit of dialogue referring to this oddity ("Why VI and not IV?").~~
In response to the feedback from Zitchas, Derpy and petervdmeer, I've changed the PR to add a new choice that covers the apparent oddness of moving from the Hauler III straight to the Hauler VI.
> Referenced the Hauler IV in the "Hauler VI cargo prototype" missions

- credits.txt
Moving the Artwork section up to be in front of the photos section, because I think the artwork section (which represents original artwork and derivations by community members, and are thus created for this project) should appear in the list alongside the other sections dedicated to stuff created for this project (programmers, writers, and editors), instead of being tacked on *after* the section crediting photographs that are neither original to this project nor created for it.
Basically, switching the "artwork" section with the "photos" section.
One last tweak to the order that I didn't quite get done before the Credits got merged in #4962 .
> Switching the order of Artwork/photos

- copyright
- credits.txt
This simply adds proper credit for Ravenshining's images. Four are their own works, and two are derivative of NASA's public domain images.
> Creating the copyright entry for Ravenshining's work

- .github/workflows/cd.yaml
**Feature:** This PR implements enables CD builds on Pull Requests, so people can download and playtest PRs without having to compile.
With this change, the CD workflow will run,
1. when a new commit is pushed to the master branch
2. when a PR is opened
3. when new commit are added to a PR
In the case of 1), artifacts will be published to the `continuous` release. For PRs, artifacts can be downloaded from the "Checks" tab:
https://gfycat.com/annualtintedcopepod
The download is still only available for logged-in users: https://github.com/actions/upload-artifact/issues/51
Tested on a multitude of PRs. As far as i can tell, this change needs to be in the head branch, so this will not work for old PRs until they merge master.
Post a comment on the PR with links to the assets. Unfortunately, …
> feat: Also build CD on PRs

- data/intro missions.txt
This is simply a spelling correction, found in the `intro [2 interceptor]`
`recgonize` -> `recognize` (line 385, near the end of the paragraph)
> Fix spelling in Intro Misions

- data/wanderer/wanderers start.txt
Same spelling mistake in line 607 and 641 of `wanderers start.txt`.
`enetered` -> `entered`
> Fix: Spelling mistakes in Wanderers Start

- source/Effect.cpp
- source/Effect.h
- source/Visual.cpp
**Feature:** This PR implements the feature request detailed and discussed ~~in issue #{{insert number}}~~ no where.
Allows effects to have a random lifetime akin to the random lifetime on projectiles, and to match the fact that they already have random velocity. 
N/A
```
effect "jump drive"
sprite "effect/jump drive"
"no repeat"
"frame rate" 12
"lifetime" 10
+	"random lifetime" 200
"random angle" 180
"velocity scale" 0.
```
Give a random lifetime to the jump drive effect, causing the jump drive particles to decay at random intervals. 
The jump drive effect after moving away from where I just jumped in. A high random lifetime leaves many particles remaining from where I just was.
A short time later, only a few particles are left.
-1 sanity.
> Random lifetime for effects

- source/ShopPanel.cpp
**Bugfix:** This PR addresses issue #4883 
The problem was that if you have an outfit in cargo, then you could buy additional outfits into cargo even if you didn't have the required license.
This fixes the issue by only allowing the player to install license restricted outfits from cargo (install = buying + ship selected).
Tried various combinations of selling/buying into stock/cargo to try to buy additional license restricted Crystal Capacitors, which with the patch doesn't work.
The save file from the linked issue, https://gist.github.com/shnwnd/ea07dfcf3ad6d32f2013505d698b64d6.
> Disallow buying license restricted outfits into cargo.

- .github/workflows/cd.yaml
**Feature**
The build time (actually the time of uploading) is now displayed along the commit hash and author. The formatting has been altered slightly.
Before:
After:
https://github.com/MCOfficer/endless-sky/releases/tag/continuous
> feat(cd): Display build time on the releases page

- data/map.txt
Fixing the grammar by replacing "relies" with "rely" in Aventine's planetary description, because it is referring to the formal group known as the Remnant, as opposed to simply a remainder of a people.
If "Remnant" was lower case, then it would be "The remnant relies on artificial greenhouses," as "The remnant is used in the context of "the group" or "the remainder of some people"; 
In contrast, with it capitalized, then it is being used as a name: "The Remnant rely on artificial greenhouses," in the same context as "The Romans rely on roads."
In this case, it is preferred to refer to the Remnant as a group, not as simply a remainder of people, so the capitalization of Remnant is correct, and thus "relies" should be changed to "rely".
> Fix: Aventine Description - Replace relies with rely

- data/hai/hai missions.txt
**Bugfix:** This PR addresses issue #5096
This fix corrects 4 typos:
harrass -> harass
condeming -> condemning
activites -> activities
planing -> planning
> fix: Typo hai missions (harrass, condeming, activites, planing)

- data/human/deep missions.txt
- data/human/marauders.txt
- data/human/transport missions.txt
**Bugfix:** This PR addresses issue #5098 
This commit fixes typos in 3 data files in the human subfolder:
deep missions.txt -> transfered -> transferred (3 times)
marauders.txt -> recognizeable -> recognizable
transport missions.txt -> and and -> and / sytem -> system / strangly -> strangely
> fix: typos in human data files

- data/help.txt
- data/intro missions.txt
- data/map.txt
**Bugfix:** This PR addresses issue #5102 
Fixes typos in 3 base data sets:
help.txt -> vasty -> vast
intro missions.txt -> recgonize -> recognize
map.txt -> refuelling -> refueling
> fix: typos in base data files (help, intro missions, map)

- data/drak/indigenous.txt
As best I can tell, persons have to have hyperspace capabilities to be spawned. 
This gives the Subsidurial hyperdrive capabilities. Also re-arranges a few of the attributes so they are closer to the standard order.
As a side change, replaced the word "cow" in the description with "bison." Bison are, in general terms, cow-like creatures with the key difference that they are much more prone to be found wild and wandering; whereas cows are almost 100% domesticated.
> Fix - Hyperspace capabilities of the Subsidurial

- data/human/free worlds start.txt
Ref. https://github.com/endless-sky/endless-sky/issues/2785
Currently, the mission FW Hope Recon 1C states 7 crew members as the normal complement of a gunboat, but due to the turret present in every gunboat they are actually at least 8. The bunks of a normal gunboat are also not enough to fly it after 8 crew members have been killed, which is what happens in the mission. This PR fixes the required crew stated in the mission and adds a gunboat variant with the scanners and the brig removed and a downgraded battery in favour of a bunk room, which could mean the Navy needed to bring specialized technicians to install the surveillance station.
In https://github.com/endless-sky/endless-sky/issues/2785 MZ says that the issue doesn't seem worth fixing, …
> Hope Recon 1C changes

- data/wanderer/wanderers start.txt
This issue arose during a discussion on the discord server. I decided to fix up the mission so that players who rush to Wanderer space after getting a JD don't get called a hero even if they haven't done anything. Plus a bunch of other changes
> Polished "Wanderers: Defend Vara Ke'sok Hint"

- data/coalition/coalition outfits.txt
despite being half a tier above the Wanderers and Korath, and having been improving their reactors to be more efficient with each generation, the Heliarch's Reactor Modules aren't much more than sidegrades to the Triple Plasma Core and the Blue Sun.
A stock Punisher has 2 Large Reactor Modules, 196 outfit space. If you replace that with a Triple Plasma Core, a Large Heat Shunt, and a Small Heat Shunt, you lose just 60 energy generation, 4 more outfit space, but it also produces about 200 less heat.
Below I've compared the energy/space, heat/space, and energy/heat efficiencies of various reactors
`Boulder= 11.53 e/s, 22.66 h/s | 0.508 e/h`
`Aeon= 8.21 e/s, 11.81 h/s | 0.695 e/h`
`Armaggedon= 11.16 e/s, 32.30 h/s | 0.345 e/h`
`PC= 13.22 e/s, 40 h/s | 0.33 e/h`
`DPC= 14.19 e/s, 46,45 | 0.305 …
> Increase Reactor Modules Energy Generation

- data/human/kestrel.txt
Prior to #3976, the More Shields Kestrel was by far the most popular option. <s>According to #4906, it is now by far the least chosen. That means it deserves a little extra (though nothing too major).</s>
This patch gives the More Shields Kestrel +10% heat dissipation, making it somewhat less vulnerable to heat damage weapons, consistent with it being the defensive variant.
> More Shields Kestrel +10% heat dissipation

- data/human/deep jobs.txt
**Bugfix** 
Adds 'not attributes "station"' to "Deep Mystery Cube [3]", just like all the other DMC non-station jobs.
> Add 'not attributes "station"' to "Deep Mystery Cube [3]" 

- .github/workflows/cd.yaml
- .github/workflows/cd_release.yaml
- .github/workflows/ci.yml
- .github/workflows/xcode_check.yml
**Chore:** This PR bumps the versions of the actions used in the CD/CD.
- upload-artifact v2
- Removed some `path: .` that are default anyways
- Bite the bullet and upload all 3k MacOS files without `tar`ing the beforehand. MacOS is already slow as hell, so 3m more won't matter much. Refs https://github.com/actions/upload-artifact/issues/69
- download-artifact v2
- Can download *all* artifacts, which we use in `cd.yml`
- cache v2
- Can now cache single files, no more moving around artifacts in `ci.yml`
All changed parts of the workflows ran at least once, see
https://github.com/MCOfficer/endless-sky/actions
https://github.com/MCOfficer/endless-sky/releases/tag/test-actions-update
https://github.com/MCOfficer/endless-sky/releases/tag/continuous
N/A
> CI/CD: Update action versions

- data/remnant/remnant missions.txt
**Content (Missions dialog addition)**
Depending on playthrough style, the Remnant: Key Stones mission may well be the first mission requiring the player to buy large amounts of an outfit for a delivery. As such, it is entirely possible that the player doesn't know that they can buy outfits into the outfitter instead of having to install them. This provides a dialogue opportunity for the player to ask for and get an explanation of how to do so in an in-character manner.
This PR adds text to the `Remnant: Key Stones` mission wherein the remnant giving the mission reminds <first> that they can just deliver the keystones in their cargo hold and don't need to install them on their hull, which then gives the player a choice.
1) Ask for an explanation, where the Remnant explains the three ways …
> Remnant: Dialog explaining "buy to cargo" in Remnant: Key Stones

- data/human/events.txt
**Bugfix:** This PR addresses a typo spotted on discord
Related:
#5108 (introduced it)
#5136, #5137 (Other fixes)
> fix: Typo in events.txt (@ ESSC)

- data/human/outfits.txt
- data/human/sales.txt
- data/human/ships.txt
Navy ships that have their own specialised license don't have a Navy License requirement, but the Auxiliary does.
> Remove Navy License from the Auxiliary to bring it in line with other large navy vessels

- source/Conversation.cpp
This gives a warning that will catch common conversation coding errors like these two:
```
mission whatever
...
on complete
conversation
...
"this is a regular line of text"
goto 1
"this is a regular line of text"
goto 2
choice
"this is a choice"
goto 3
```
The `goto 2` and `goto 3` are indented incorrectly, so the code treats them as regular text. These changes update Conversation::Load to give errors and ignore those lines:
```
Conversation text should be a single token:
file .../data/whatever.txt
L1:   mission whatever
L6:     on complete
L7:       conversation
L13:        goto 2
Conversation choices should be a single token:
file .../data/whatever.txt
L1:   mission whatever
L6:     on complete
L7:       conversation
L11:        choice
L16:          goto 3
```
> warn if conversation text has multiple tokens (e.g. incorrectly-indented goto)

- source/GameData.cpp
- source/System.cpp
The pathfinder could still choose to path through a system that has not
yet been defined (for example, when it is created by a mission).  The
rest of the game ignores these systems with similar checks to these.
I played a fair bit of the game with these fixes applied.  Testing that it actually fixes the bug was achieved by playing with PR 4871 applied, which triggers it.  The bug causes a hidden system at 0,0 (near Kor Men) to be pathable, but not visible.  This just takes it out of the pathfinder as well.
Bug only occurs with plugins or PR 4871 applied.
> Fixed pathing through undefined systems.

- source/Weapon.cpp
**Bugfix:** This PR addresses issue #5022
When calculating the total damage of a weapon with infinite submunition, the game crashes with a stack overflow due to infinite recursion. <del>The fix I'm introducing is to remember up to 10 submunitions and see if they are seen again. This means that the total damage of a weapon with infinite submunition is the total damage up to the point where the loop happens.
<del>This enables any infinite submunition whose repeating munition is at most 10. Should be enough for most.</del>
We can reuse the "calculated" flag to prevent the infinite recursion by setting it to `true` as soon as we start the calculation.
The issue also describes an error that the max velocity is 450000. I haven't seen this issue, even when I increase the velocity of the …
> Stop crashing when using weapons with infinite submunition

- data/human/events.txt
**Bugfix:** This PR addresses issue #5149 
In the event "pug territory liberated", Tinker's tribute is not restored - unlike all the other planets and stations in the affected territories.
Thanks to Pete-2004 for spotting this bug.
> Fix: Restores Tinker's tribute after Pug War

- data/map.txt
**Content (Map Data)**
This PR adds attributes to a variety of systems in order to label a few key features, as per the specification included in the [MapData ](https://github.com/endless-sky/endless-sky/wiki/MapData) wiki page. 
The attributes that it adds are:
- "ember waste" (applied to all systems in the Ember Waste)
- "graveyard" (applied to all systems in the Graveyard)
- "void sprites" (applied to Nenia)
- "archon" (applied to all systems that have resident Archons.)
- "wormhole" (applied to all systems that have wormholes)
I am planning a variety of generic jobs for the Remnant because, well, they don't really have anything other than the Korath Bounties. In order to target these jobs properly, they need to be able to have identifiers that allow the game to randomly pick from …
> System attributes for the Ember Waste and select systems

- data/map.txt
as suggested by Derpy here https://github.com/endless-sky/endless-sky/pull/4896#issuecomment-661946450
, this adds a supernova system closer to Coalition space. Though as he suggested one only accessible via Coalition space would be ideal to get players to trigger the recently added Coalition Yottrite missions, if it was so easily accessible there wouldn't be a need for you to bring them any since the Heliarchs could just mine a few asteroids with a Jump Drive-equipped Punisher and have all the material they'd need, without needing to go through territory that isn't theirs and then back.
system is positioned just under Shaula, a bit to the left, and can only be jumped to from Shaula and the neighboring FW systems, a bit too far away for one to jump there from the closest Coalition system.
> Add a supernova system closer to FW/Coalition

- source/Engine.cpp
- source/Mission.cpp
- source/Mission.h
- source/NPC.cpp
- source/NPC.h
- source/PlayerInfo.cpp
- source/PlayerInfo.h
**Feature:** This PR implements the feature request detailed and discussed in issue #5159. Related to #1564.
This PR adds the ability to spawn or despawn `npc`s based off of the player's conditions. 
The `to spawn` conditions are first evaluated after the player has accepted the mission, meaning that conditions changed during an `on offer` conversation can trigger whether `npc`s spawn. Should the `to spawn` conditions fail on accept, then they are reevaluated on every landing, departure, and jump until succeeding. If the conditions succeed, the `npc` will spawn on the next departure.
The `to despawn` conditions are evaluated at the same times as the `to spawn` conditions (on accept and after every landing, departure, or jump until succeeding), but only if the `to spawn` conditions have …
> Allow mission NPCs to spawn or despawn based off of ConditionSets

- source/Preferences.cpp
- source/PreferencesPanel.cpp
- source/ShopPanel.cpp
**Feature:** This PR implements a feature to fix the issue #2442.
Adds a new preference that toggles the behavior of the ship outlines in the ShopPanel. When set to "fancy," the game renders the sobel filters of the ship sprites, as it does now. When set to "fast," the game instead uses the top-down sprite of the ship instead of applying the shader to it.
NOTE: This preference ONLY affects the ShopPanel. The sobel filter shader is still used for the flight UI, the main menu, and for the ShipInfoPanel. In each of these cases you only have one or two ships that need the shader rendered, and therefore I saw the need to change these cases unnecessary, as the issue was with a large number of ships rendering this shader at once, which is only found in the ShopPanel.
The location of this setting …
> Allow the "fancy" sobel filters in ShopPanels to be replaced with "fast" sprite images

- source/Engine.cpp
- source/Outfit.cpp
- source/Outfit.h
- source/Ship.cpp
- source/Ship.h
**Feature:** This PR implements a feature request discussed on Discord in reference to #5042
Adds the ability to customize the sound and effect that a jump drive or hyperdrive has, instead of all jump drives and hyperdrive needing to use the same sounds and effect.
Adds the following new attributes:
* `"jump effect" <effect name>`: The effect that is created over a ship when it is jumping. This is an effect, not simply a sprite, so the effect must be defined elsewhere.
* `"jump sound" <sound name>`: The sound made when the player's flagship jumps. 
* `"jump in sound" <sound name>`: The sound made when other ships jump into the player's system.
* `"jump out sound" <sound name>`: The sound made when other ships jump out of the player's system.
* `"hyperdrive sound" <sound name>`: The sound …
> Customizable jump drive and hyperdrive sounds and effects

- data/human/free worlds intro.txt
- data/human/outfits.txt
Right now, the Militia license's description sticks out like a sore thumb amongst the other human licenses, reading more like a logbook entry. This PR changes it to be more in line with the other human licenses, and also adds a small part where you receive the license, like in the Deep missions.
> Change the Militia license to be more in line with the other Human licenses

- data/human/transport missions.txt
Fixes #5105.
The word "chit" is an old-fashioned British term and can be misidentified as a typo for "chip" to those unfamiliar with it (as occurred in #5105). In order to be easier to understand by English speakers outside of British and Commonwealth territories, replacing with the more commonly used "chip".
> Replacing chit with chip

- source/MainPanel.h
- source/MapPanel.h
- source/PlayerInfoPanel.h
**Bugfix:** This PR addresses a compiler warning that was introduced in #5148
The override keyword was missing for AllowFastForward(). C++ allows this, but it is more appropriate if the keyword is given so that the compiler can check for overrides that were done incorrectly.
Added the keyword.
Compiled the game after adding the keyword to allow the compiler to verify that overriding was done correctly.
N/A
> Add override to AllowFastForward() where appropriate.

- data/hai/hai news.txt
- data/human/news.txt
- data/interfaces.txt
- source/SpaceportPanel.cpp
- source/SpaceportPanel.h
This PR addresses #4325 and removes all portraits from news. This PR does *not* remove the functionality of portraits, only removing the current portrait images from being used. This PR also does *not* remove the portrait images from the game, as plugins may be using them. (If it's decided though that we should also remove the images from the game, we can easily do so.)
This PR also updates the interface so that the name and message move locations depending on if the news does have a portrait or not. Given that the heart of #4165 was the repetition of portrait images, and this PR removes said images from the base game, I've reverted dea4cf7 as well. This also fixes #4463 by removing the portraits and the commit that caused the issue when portraits …
> Remove portrait images from spaceport news

- data/remnant/remnant ships.txt
**Fix:** This PR addresses the fact that Remnant ships that either need to or will need to use Ember Waste wormholes do not  have a Quantum Keystone.
- Adds Quantum Keystones to a range of ships so that they are properly equipped for the missions they will be used in.
> Fix: Adding missing Key Stones to Remnant Ships

- data/dialog phrases.txt
- data/human/transport missions.txt
**Bugfix:** This PR addresses issue #5195.
Adds three new `on visit` dialogue phrases that can be used for future missions and the mission issue #5195 references: 
1) Missing waypoint or cargo
2) Missing waypoint or passengers
3) Missing waypoint, cargo, or passengers
Replaces `on visit` for `mission "WR Star 1"` with the new missing waypoint, cargo, or passengers phrase.
Using the provided save file, the phrase for missing waypoint, cargo, or passengers appears correctly.
This save file can be used to verify the bugfix.
[WaypointDialogTest.txt](https://github.com/endless-sky/endless-sky/files/5012386/WaypointDialogTest.txt)
The mission is already assigned. Simply leave the planet and land again to view the new dialogue.
> Add dialogue phrases for missing waypoints

- data/remnant/remnant missions.txt
**Content**
This pulls the two Chilia log entries out of their respective missions, and creates two log entry missions so that the player will always get the two entries in the specific order. It also centralizes introduction logs to avoid risk of duplicates logs.
This does not change the first log entry for Chilia, but it does remove the reference to him being the Defence Prefect from the second. As such, a the visible impact of this break out will be that the log entries no longer duplicate each other.
As there are multiple ways and orders the player can meet Chilia, this break-out means that regardless of order, the player will always get the first log entry (that identifies him as being the defense prefect) first, and the second one afterwards. Thus the second one doesn't need to …
> Content: Breaking out Chilia logs (adjustment, not new content)

- data/korath/korath news.txt
Adds 17 spaceport news dialogues for Kor Efret planets/stations (none of which is actual dialogue, as the player does not know Korath language). I tried to elaborate on the existing planet/spaceport descriptions of the dichotomy of market stalls and plazas in the middle of cities. Added a new minor aspect to existing lore:
Cities are partly abandoned/dilapidated due to the civil war: buildings range from brand new to structurally unstable. I thought this was appropriate considering the Korath's role as a declining species.
Below are a couple screenshots of the news.
[Test Pilot~korathnews.txt](https://github.com/endless-sky/endless-sky/files/5023874/Test.Pilot.korathnews.txt)
> Kor Efreti spaceport news

- data/human/boarding missions.txt
Change `damages` to `damage`, change `my ship` to `your ship` to preserve second-person, switch the randoms the right way round (where the number is equal to the chance (out of 100) to get the outcome, rather than the number being equal to 100 minus the percentage chance).
> Fix typoes in "Asteroid Course"

- data/ka'het/ka'het missions.txt
**Bugfix**
This bug fix prevents Ringworld Debris from being prematurely completed by landing on the first planet you took off from after the mission was added, likely New Boston for new pilots. Additionally, this PR makes entering Queri fail the mission, to clear it out of the save file after it has been used.
I've tested that the mission offers properly, that you can't prematurely complete it, that the conversation still triggers and that the mission goes away after collecting the debris.
> Fix "Ringworld Debris" completion to stop it from prematurely completing

- source/MapPanel.cpp
This feature lets you use a modify key (control in this case) to prevent automatic route planning on the map panel. While routes are very easy to plan in Endless Sky, having a trip with 3-4 stops make re-planning it tedious. With this change, holding down control lets you directly select a system, cycling you through available missions on the Missions tab, or letting you preview commodity prices for a stop on the way on the Ports tab.
Future development could allow for an option to enable/disable automatic route planning, where this modifier would be the inverse of that (plot route if enabled, directly select if disabled), but in the meantime, this is a quality-of-life change that benefits players who take on many jobs at once.
Tested for clicking on a variety of explored/unexplored …
> Support selecting systems without planning route

- source/PlayerInfo.cpp
**Bugfix:** This PR addresses a null-pointer issue found during the development of #4370
Calling PlayerInfo::SetTravelDestination with a nullpointer as planet causes a null-pointer-derefence. This PR addresses the null-pointer-dereference by first checking if the pointer is not null.
Tested during #4370.
The game keeps planet-travel-destinations until a new planet-travel destination gets set. A follow-up PR might be desirable to make sure that the travel-destination gets cleared when the player switches navigation to a new system (this larger fix is not included in this PR).
N/A (An older version of #4370 is required to trigger the issue seen here)
> bugfix: Allow calling PlayerInfo::SetTravelDestination with nullptr planet

- data/coalition/coalition ships.txt
I've had this in mind for a while but keep forgetting about it so opening this draft for discussion.
Adds ion protection to the 3 Heliarch ships, the value getting higher as the ships go from Light to Medium to Heavy warships.
Reasoning being that, being built to fight the Quarg, who have Ion Damage on their skylances, and the Heliarchs themselves having developped ion weaponry, they should know a thing or two about how to minimize the effects of ion damage on their ships.
Along with the 5032 buffs to the Reactor Modules, should make Heliarch ships (especially the Punisher) much less prone to getting affected by the ion damage of Skylances while they're still well above the disabled threshold
If my math is correct, these current values should reduce the ion damage the Neutralizer takes to …
> Add "ion protection" to Heliarch ships

- data/human/outfits.txt
This PR removes the references to needing to license ships and fines incurring to ships you don't have a license for, and replaces it with a description of how Parliament is restricting the freedoms of pilots.
> Update the Pilot's License description

- data/remnant/remnant missions.txt
This Remnant mission refers to "System Cores", when the outfit is called "Systems Core" singular, or "Systems Cores" plural, according to the outfit text. The plural would still work in the mission text, but feels a little awkward to use in a conversation, so I went with a singular usage, as it seems like the next sentence refers to the nanobots, not the outfits.
> Make spelling of Systems Core consistent in Remnant mission

- source/Dialog.h
- source/LoadPanel.cpp
- source/ShipInfoPanel.cpp
**Feature:** This PR implements the feature request detailed and discussed ~~in issue #{{insert number}}~~ below
The "rename ship" dialog will start prefilled with the name of the ship, rather than empty.
The save dialog will start prefilled with the date, rather than empty. The behavior is unchanged, I think: currently if the user clicks "OK" in the save dialog when the textbox is empty, the date is used.
The following two dialogs are affected. In master they both start with the textbox empty, the screenshot shows the new value:
N/A
I opened the dialogs and verified the textbox starts prefilled with the correct value, even when the day-of-month is single digit.
N/A
> Fill the default value in the save and ship rename dialogs

- data/governments.txt
**Bugfix:** This PR addresses the fact that Alpha Hand to Hand combat values are equal to that of a Navy soldier, despite being described as worth several of them.
Attack from 1.4 up to 3
Defense from 2.2 up to 3
Biologically, Alphas are supposed to be super-soldiers, engineered to be perfect warriors; Most of the description revolves around the physical, but there are hints here and there that it is mental as well.
Socially, the current Alphas are portrayed as veteran survivors who are aggressive guerrilla warfare specialists and stealth operators. They are described in the lore as one Alpha as being worth several Navy soldiers. This implies that they are experienced, well trained, and combat-hardened. It is worth noting that even when the Navy is forwarned and can bring their elite …
> Fix: Changing Alpha Combat Values to be better than the Navy's

- data/map.txt
**Feature:** Typo fix
Added a missing apostrophe-s to Babiali's planet description.
N/A
N/A
Made the same changes to my map.txt and tested it in-game. All works properly.
N/A
> Typo fix for the planet Babiali

- data/remnant/remnant.txt
**Bugfix:** 
Adding two missing spaces.
> Fix: Adding two missing spaces in Remnant Friendly phrases

- data/drak/drak.txt
**Bugfix:** This PR addresses issue #5273 
This adds a description to Archons.
This fixes #5273 
Thanks to McloughlinGuy for reporting it.
- This PR does not attempt to resolve any of the debate/questions surrounding the Archons and the Drak, instead codifying it so that it is clear that this isn't just players being confused - their pilot (and humanity in general) is equally confused as to what exactly the Archons are.
> Fix: Adds a description for Archons

- data/remnant/remnant missions.txt
**Bugfix:**
In Cognizance 4, Prefect Chilia exclusively signs. Note that there is no transition between this section and the later section describing how his gestures change with the topic of conversation. This is in contrast to his possible earlier introduction during Face-to-Maw where he sings.
Thanks to Ririshi on Discord for asking about this and bringing it to my attention.
> Fix: Remnant: Cognizance 4 - Changing sings to signs

- source/Ship.cpp
**Feature:** This PR implements part of the feature request detailed and discussed in issue #5171
This PR adds a temporary map in the function that saves the ship-outfits to a save-game file to ensure that the outfits are saved in alphabetical order.
N/A
N/A, the game automatically applies the ordering when saving.
I started the game with an existing save-game, pressed depart and then closed the game. The outfits in the save-game before and after starting where the same (but the outfits after starting the game were sorted in alphabetical order).
The effect of this change is that the function that saves the game takes a little bit longer time and temporary uses a little bit more memory (since it needs to build up the temporary map). But ships have small lists of outfits, so the impact …
> Save ship outfits in alphabetic order to savegame.

- data/drak/drak.txt
- data/remnant/remnant ships.txt
Changes:
- Drak draining field force 50 -> 100
- Drak Turret velocity and lifetime swapped. So same effective range, but a bit slower.
- Puffin mass dropped from 44 to 40.
Repeatedly running the Nenia puffin dodging mission.
Things are back to the Puffin getting shoved, although not as dramatically as it was when the force was 500 and working properly. The puffin usually gets hit enough times to build up some graphical indicators, but it is enough to outpace most of the turret shots. I've only tested it a dozen times or so, but it seems to work fairly well at  being exciting and stressful, but not dying. So, this is what I'm aiming for.
Alternatively, we could leave it at force 50, and drop the puffin mass some more. I don't know for …
> Fix: Tweaking Puffin-Drak conflict

- data/map.txt
Fixed instances of 'Membulem'
As request by Arachi, the System containing 'Corral of Meblumem' as been renamed to match the name of the Planet to be consistent with other Coalition Systems.
A quick search through other Coalition files says that this isn't references anywhere else, so this should be safe to merge as in (once Derpy's crash fix goes through?).
> Fixed instances of 'Membulem'

- data/hai/hai missions.txt
First Contact with Unfettered Update
In regards to endless-sky#2664 , I have modified the Hai missions to provide two different alternative versions for the First Contact mission to the Unfettered. This causes minimal changes and disruption. Existing saves that have already made contact should be unaffected, and existing files referencing the old mission tag will be unaffected, as I have designed this to use the existing tag.
I have mostly just copy pasted and rearranged the conversation in question to attempt to maintain the writing style in question, and not have the mission feel out of place to those who have done it previously.
This should be relatively easy to test, but if needed, I can provide a save landed on the Wanderer home world without contact with the Hai. The dual-mission …
> Arkhne's Unfettered First Contact Update

- source/GameData.cpp
- source/GameData.h
- source/News.cpp
- source/News.h
- source/SpaceportPanel.cpp
- source/SpaceportPanel.h
**Feature:** This PR implements the feature request detailed and discussed in issue #4945.
Adds a new node to news, `to show`. This is a condition set like `to offer` that must be passed in order for the news item to show, in addition to the location filter matching.
N/A
```
news "reminiscing about the war"
...
to show
has "main plot completed"
...
```
Created three news entries. One had no show conditions. The second was set to only show before the main plot was completed. The third was set to only show after the main plot was completed. All three news entries showed under the proper conditions.
N/A
> Conditional spaceport news

- EndlessSky.cbp
- EndlessSky.xcodeproj/project.pbxproj
- copyright
- source/DataFile.cpp
- source/DataFile.h
- source/DataNode.cpp
- source/DataNode.h
- source/DataWriter.cpp
- source/Utf8.cpp
- source/Utf8.h
**Feature:** This is a part of #4123 (for now) and needs no extra libraries.
This PR allows Endless Sky to read a data file contains a character encoded by UTF-8.
The code originates from #3312 and it is written by flaviojs.
N/A
[test-data.zip](https://github.com/endless-sky/endless-sky/files/5217965/test-data.zip)
This plugin introduces the government β that has the display name "Beta."
```
government β
"display name" "Beta"
```
The current master detects this when reading the plugin:
```
Skipping unrecognized root object:
file ${HOME}/.local/share/endless-sky/plugins/test-for-datafile-encoded-utf-8/data/governments.txt
L11:   government
```
This PR version raises no error.
N/A
> Support data files encoded by UTF-8.

- source/AI.cpp
- source/CargoHold.cpp
- source/DataWriter.h
- source/Depreciation.cpp
- source/Fleet.cpp
- source/GameData.cpp
- source/MapOutfitterPanel.cpp
- source/MapShipyardPanel.cpp
- source/MissionPanel.cpp
- source/Outfit.cpp
- source/PlayerInfo.cpp
- source/Ship.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #5171 
closes #5324 
Where parts of the player's save were not deterministically ordered, they now are. A template method, and a specialization for uses of std::map for a pointer type key, are used to create a vector of pointers to the collection elements, which is then sorted and iterated.
To avoid future code from manipulating DataWriters incorrectly, deletes the copy & move constructors / operators for it.
n/a''
n/a
Saved & loaded & saved again a couple times
n/a
> feat(mechanics): Save collections in order by element name

- data/human/hails.txt
The above hail uses the word "I don't hate them, but..." which is a slightly positive disclaimer which would normally be used to soften a negative follow-up. That does not match with the other words in that group, though, which are all slightly negative disclaimers followed by a positive statement. This PR adjusts it to the match the others.
> Phrasing fix for merchant hail

- source/ShipInfoPanel.h
Nothing more to add. `ShipInfoPanel::selectedIndex` was unused and clang generated a warning which failed the build due to `-Werror`.
> Remove unused member variable.

- data/korath/korath missions.txt
From the new Korath missions. Caught and noted by Arachi on discord.
> (Typo) Removing extra quotation mark

- source/Mission.cpp
**Build fix:** This PR addresses inability to successfully build master/continuous for macOS (10.11 using Xcode 8.2.1)
Mission.cpp - Line 961
Default initialization of an object of const type "const MissionAction" without a user-provided default constructor.
Add empty object initializer {} - this is the recommended fix by Xcode.
Builds successfully and game operates normally.
> Fixed Mission.cpp default init for EMPTY

- data/wanderer/wanderer jobs.txt
Fixes issue #5379 opened by @ roadrunner56.
-Corrected a typo
-Ensured station could not be a stopover for the job by adding `not attributes "station"` to stopover
To the best of my knowledge and some quick testing, this fixes the issue, but @tehhowch said something that made me a little hesitant:
> dynamic stopover filters in 0.9.13 are a small bit more lenient in the landing locations they can select, so pure government filters may not be sufficiently specific
So it sounds like there could be some things going on under the hood that I'm not fully aware of. If someone with a bit more knowledge of the code could check this in regards to @ tehhowch 's comment it would be much appreciated.
This save can be used to test this:
[Firstname Lastname~test …
> (fix) New Wanderer jobs corrections

- source/MissionAction.cpp
- source/MissionAction.h
- source/PlayerInfo.cpp
- source/PlayerInfo.h
- source/ShipyardPanel.cpp
Gives creators the ability to give ships to the player through missions
This is a partial implementation of  #4399 it allows the giving of ships through missions.
It can be used in a mission under `on offer`, `on accept`, etc.. 
```
on <action>
give ship <ship model> [<name>]
```
If the second name is left out, a civilian ship name will be generated for the gifted ship.
e.g.
```
mission "some mission"
...
on complete
give ship Sparrow "Mote of Might"
give ship "Star Barge"
```
indicates that completing the mission will result in the player being given a Sparrow that is named "Mote of Might," and being given a Star Barge with a randomly picked civilian name
Using the example mission gives two ships, one with a name, and one without a predetermined name, it gets …
> Feat: Give ship

- source/AI.cpp
**Feature:** This PR implements the bugfix/feature request discussed in #5382 
Ships (mostly the player flagship) owned by the player no longer automatically fires at ships that were previously boarded.
Amazinite did all the work to find the relevant code (and posted that in  #5382), I just created the relevant PR for it.
N/A
The relevant actions to trigger this change are:
- Get yourself a ship with turrets
- Enable auto-fire
- Board some ship
- Notice that the ship doesn't get fired upon by your ship after boarding
I checked that:
- Navy ships still fire at disabled ships.
- Free world ships still don't fire at disabled ships.
- Player ships no longer auto-fire at disabled ships after boarding.
The ship->IsYours() function just returns the value of a boolean, so I expect no serious …
> feat: Don't let player ships autofire at disabled ships that were boarded.

- data/human/free worlds checkmate.txt
Changed `Drive off the Pug fleet that is invading <system>` to `Drive off the Pug fleet that is invading <system>.`.
> typo: FWC Pug 4 missing period

- data/remnant/remnant missions.txt
- data/remnant/remnant ships.txt
- Removed the payment of 1000000
- Added in a `give ship "Penguin" "Shadow Hope"`
- Increased outfit space by 1 ton so that the turret spot can actually fit a PDT without needing to use alien engines. 
The original intention for the Face-to-Maw mission was to have Taely give <first> the penguin on the spot. With the recent addition of the `give ship "Penguin" "Shadow Hope"` command, this can now be done. 
Thanks to @Fzzr , @NomadicVolcano , @Gods-Righthand , @petervdmeer , and @Amazinite for getting that mechanic implemented and functional.
> Content: Remnant - Penguin Give

- data/human/free worlds side plots.txt
Also moved the logbook entry for the Stack Core to when it's released, as the player wouldn't know that they were creating the Stack Core up until that point.
> Stopped Stack Core missions from offering during the Pug invasion

- source/AI.cpp
This PR improves the AI a bit when the ship has afterburners or reverse thrusters.
1. `CircleAround` now uses the afterburner for speed - basically PR #4655 which the author has abandoned with the review incorporated.
2. `MoveTo` now better uses the reverse thruster if possible. For example, when landing on a planet while flying straight to it will now use the reverse thruster to stop instead of turning around<sup>1</sup>.
3. `MoveToAttack` uses reverse thrusters to reach the enemy quicker.
More details:
`CircleAround` will, if the ship is 750 away from the target fire its afterburners. This gives it enough time to gather without shooting past the target.
`MoveToAttack` circles the enemy, but if the enemy flies through the ship then currently the ship turns around. But if it has reverse …
> AI improvements for afterburners and reverse thrusters.

- data/remnant/remnant missions.txt
Changed branch condition `"remnant met taely" > 1` to `"remnant met taely" >= 1` so that Taely doesn't introduce herself again in "Face to Maw 2" if the player met her once before (e.g. by accepting "Tech Retrieval" without completing it).
> Fix: Conversation branch condition in "Remnant: Face to Maw 2"

- data/human/kestrel.txt
This matches the precedent of using thumbnail images to show ships in conversations, such as the Tempest, Penguin and Emerald Sword.
> Change Picture of Kestrel in "Kestrel Available" from top-down to thumbnail

- data/remnant/remnant missions.txt
Adds a short branch to tell the player that they can use a penguin, but the rest of the fleet will still have to use puffins.
Also pluralized the on complete section so that it is clear that it is talking about the group of puffins; not the player's specific puffin.
**Bugfix:** This PR addresses issue #5310 
fixes #5310 
- Adds a branch where Taely tells <first> <last> that the penguin will be suitable too, but they don't have others available, so they'll have to use puffins anyway.
- Pluralized "puffins" in the second paragraph to make it clear that it is talking about the group of puffins, not the player's specific ship.
- played the mission.
> Fix: Remnant Cognizance 12 Puffin-Penguin bug

- data/persons.txt
This marks LG's person ship's gridfire turrets as "safe" so they don't blow up unsuspecting players.
Gridfire is invisible and deadly to early game ships, and uses damage mechanics not present in human space.  Should Local God appear in the early game, and happen to attack a ship near the player, the player and their escorts may be easily destroyed or disabled.  Unlike, for example, Pointedstick's heavy rocket attacks, the Gridfire cannot be seen or dodged, may come from far off-screen, and may leave the player in the confusing (to new players) state of being disabled with their shields up.
For me, losing a valuable escort and having my flagship disabled out of the blue despite being nowhere near the local furball, it was a surprising annoyance and cause for a scum-save, for a new player …
> Make LG's gridfire friendly-safe

- data/remnant/remnant missions.txt
**Bugfix:** This PR addresses issue #5427 
Moved the requirement for the language from "have met the Remnant" to "they've demonstrated a willingness to work with the Remnant.
fixes #5427
Specifically, this mirrors the requirement for the technology available mission, except uses the Void Sprite 3: done criteria instead of the void sprite research event. This later has a 20 day timer on it. The idea that it will tend to mean that the learning sign mission should happen during this gap period that at least some players find distracting and cause to leave the area.
This also means that the learning sign missions cannot be done before the player has done the basic set of missions, thus resolving #5427
> Fix: Remnant: moving the eligibility for Learning Sign to be later.

- data/remnant/remnant ships.txt
**Bugfix:** This PR addresses issue reported by Dr. Doom (Corraban) on Discord.
The Heron description has both "existence" and "existance" in subsequent sentences. This PR replaces the erroneous "of them in existance" with "that exist" so it both solves the spelling mistake and the not-terribly-good thing that is having the same descriptor in two sequential sentences.
> Fix: Heron Description "Existance"

- data/governments.txt
**Content (Governments)** Disabled fines for Governments that shouldn't fine
Added `fine 0` and `bribe 0` for some governments (like Indigenous Lifeform) where it makes no sense if those governments give fines.
N/A
I would expect most future governments not to levy fines and to accept bribes, so we might want to do a change in the future to change the defaults for fine and bribe to 0 and only explicitly set them for governments that do levy fines and that do accept bribes.
> Added fine 0 and bribe 0 for Governments where those don't make sense

- source/Mission.cpp
- source/Mission.h
- source/MissionPanel.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #4018.
Adds a new `on abort` action.
* Only triggers if the mission is aborted by the player.
* Creates a new `"<mission>: aborted"` condition.
* Also creates a `"<mission>: failed"` condition when aborting. (BACKWARDS COMPATIBILITY)
* If a mission is aborted and no `on abort` action exists, any `on fail` action is triggered instead. (BACKWARDS COMPATIBILITY)
N/A
See testing done.
Given that aborting a mission creates both the aborted and failed conditions, the following condition sets can be used to test certain outcomes.
Mission failed **OR** aborted:
```
has "<mission>: failed"
```
Mission aborted:
```
has "<mission>: aborted"
```
Mission objective failed:
```
has "<mission>: failed"
not "<mission>: …
```
> Differentiate aborting from failing

- data/human/free worlds intro.txt
- data/human/pirate jobs.txt
- data/human/syndicate jobs.txt
- data/remnant/remnant missions.txt
**Content (Jobs)** Don't fine players for ships they didn't destroy in target practice.
This PR uses the feature from #5426 to ensure that aborted Syndicate target practice jobs don't fine the player for destroying the dummy ship by providing an empty on abort section.
I checked both the fail situation and the abort situation (using the compiled code from #5426). The abort situation doesn't give any output, the fail situation still gives the proper message.
I can provide a save file if desired, but the change is quite trivial, so I'm not sure if this is needed.
> Add empty "on abort" sections to Syndicate target practice.

- source/Engine.cpp
**Bugfix:** This PR might address issue #4078.
Adds the check to see if the hailing ship shares a language with the player to the CanSendHail function. This should prevent ships from hailing the player when a language is not shared under any circumstance, as CanSendHail is always checked before sending a hail message.
Still not sure how the World Ship in #4078 sent a disabled hail, though, as disabled ships do not send random hails, and the only way to view disabled hails is to hail a disabled ship, as best I can tell.
Flew around Ka'het space with and without this change. Without this change, Ka'het ships would occasionally hail me, but hailing them returned the expected alien language response. With this change, I was never hailed by a Ka'het ship. The same should extend to Korath …
> Make the language check a part of CanSendHail

- source/MapPanel.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #5399.
<insert the title here\>
Map system coloring using:
* commodity key (unchanged, notice Algieba)
* visited key (now highlights uninhabited systems with landable planets, notice Algieba)
* visited key (looking at a restricted planet w/o access)
* visited key (looking at a restricted planet w/ access)
N/A
See UI screenshots section.
N/A
> "You have visited" map key highlights uninhabited systems with landable planets

- source/MissionAction.cpp
- source/Ship.cpp
- source/Ship.h
**Bugfix:** This PR addresses issue #5400.
This PR fixes #5400 by saving the variant name to the save file instead of just the model name. This means that upon reloading, the correct ship is recognized as the one that should be gifted.
See the mission mentioned in #5400. Also tested that mission by giving normal Kestrels to ensure that Ship::VariantName() returns modelName if no variantName exists, and it works.
N/A
See #5404 for an alternative approach. I started work on that approach, then finished this one, then figured why not do the second one, then figured out why I like this one after finishing that one. Since I have both finished though, I figured I'd just post both.
> Save variant names for gifted ships

- source/PlayerInfo.cpp
- source/Ship.cpp
- source/Ship.h
**Feature:** This PR implements the feature request detailed and discussed in issue #1643.
Title says it all. Fighters, drones, or any carried ship category in the future can be piloted by the player as a flagship, if they so choose.
N/A
N/A
<details><summary>Tested by changing my flagship to a Finch. Was able to successfully depart solo, as well as with carries as escorts. Carried ships as escorts work normally.</summary>
</details>
N/A
> Allow carried ships to be the player's flagship

- data/human/transport missions.txt
Adds `noun "asteroid"` to the asteroid definition in the case that someone scans the asteroid, made the mission fail if the asteroid is assisted then blown up (would previously not fail as long as the asteroid was assisted).
> Fix "Terraforming 3"

- data/quarg/quarg outfits.txt
just because they're placeholder doesn't mean you can spell density as destiny smh
also changed a few things in the steering description ("quarg steering engines" roll off the tongue better than "quarg steering")
> Fix a typo in the new Quarg descriptions

- data/human/news.txt
- data/map.txt
This adds attribute tags to every system in the map file. Tags are based on the dominant species/government, with additional tags for sub-regions (such as the Deep), noteworthy points in galactic topography - such as dead-ends, hyperspace "islands", and system-defining phenomena such as the presence of supernova remnants, ringworlds, or wormholes.
New tags are prefixed with a ! to make find-and-replace easier. This isn't necessarily intended to be their final name; just something to facilitate replacement when that's decided on.
Topographical tags:
**!fringe** - applied to uninhabited systems which don't lead to any other inhabited systems. Only explorers, miners, or those with something to hide would have a reason to visit these systems.
**!isolated** - applied to systems which have no …
> Add regional/noteworthy features attributes to systems

- source/Engine.cpp
- source/Ship.cpp
**Bugfix:** This PR addresses issue #5220 
This being my first ever PR and my first hour of scanning through the code - I chose a very simple seeming issue, with little chance to sprawl and create more problems with the fix, that said however, I am obviously not completely au fait with the codebase, so apologies for any mistakes in my understanding.
From what I can see, the `centrevelocity` is what determines the blur shader strength, and the centrevelocity is set in Engine::step() based on flagship velocity, after the flagship "dies" I'm guessing that its velocity is never zeroed, hence the centrevelocity keeps accessing the "dead" ships velocity which is now frozen forever at its last updated value.
I added a conditional in Engine::Step() which asks if the flagship is destroyed, if so, …
> Stop blurshader thinking there is centervelocity movement after player death

- source/StellarObject.cpp
**Bugfix:** This PR addresses issue #5061 
As per linked issue, autopilot fails to land on spriteless planet, as it tries to calculate radius /distance from the sprite to start landing process, and constantly circles around a zero point.
Even though the unintended behaviour comes about as trying to use spriteless planets as a form of one-way wormholes, which probably isnt the ideal future way to make these, the behaviour itself is problematic, and I cannot think of any situation where you would want the game to land on a spriteless planet.
Added a conditional in get_planet() to return nullptr if there is no sprite on the object, get_planet() is checked for truthiness in all checks for landable planets in that system, so player and AI and everything else will just not consider it a planet …
> Add check for planet having a sprite before returning valid planet to land on

- EndlessSky.cbp
Currently, the CodeBlocks project file has three paths built into it: The precompiled libraries paths (which the wiki mentions you should extract them to that location), the 32-bit MinGW paths (which use a proper path, although for a version from years ago), then the 64-bit MinGW paths. These are not only inconsistent with the 32-bit paths, but completely nonsensical, as a user would only end up with them if they installed MinGW directly into C:\Program Files\ (which would leave other files lose in there, as well).
This PR updates the CodeBlocks project file to use the default install location from the latest version of MinGW (from 3-4 years ago), 8.1.0. It doesn't seem like a single developer working on ES uses the provided defaults, so changing them up will only help a user getting the …
> Update CodeBlocks 64-bit paths to use modern defaults

- source/PlayerInfo.cpp
**Bugfix:** This PR addresses issue #4544
Added a check for ->isDestroyed() in the SelectShips() function before allowing it to be selected.
Dragging and clicking select on live ships still works normally.
After escort dies, click and drag area it died, and now it is no longer selecting
[testy testy.txt](https://github.com/endless-sky/endless-sky/files/5430949/testy.testy.txt)
Just a quick save file with a tougher escort to ensure flagship dies first.
> Disallow selecting already destroyed ships by clicking/dragging

- copyright
**Bugfix:** This PR addresses issue #5346.
The file "copyright" doesn't indicate some authors.
This PR adds "endless-sky contributors" to the default item of copyright.
You may still claim your copyright if you want because this PR modifies only the default line.
N/A
N/A
> fix(doc) Update copyright file.

- source/Audio.cpp
**Bugfix:** This PR addresses issue #5462 
I fixed this by creating the `sounds` entry inside the mutex lock instead of outside, so that loading the sound file and accessing `sounds`'s size do not clash.
I couldn't get thread sanitizer to error out, but I verified using OP's error message that I correctly identified the two functions that race (`map::operator[]` and `map::size`).
However, I reduced the code into a small example to test my fix. If you remove the comment (my fix), then the race condition disappears. The example can be found here: https://godbolt.org/z/fP5r9s
N/A
> Fix race condition while loading the audio.

- source/OutfitterPanel.cpp
**Feature:** This PR implements a trivial quality-of-life feature
Having 'u' sometimes uninstall the outfits and sometimes sell them is very confusing.
Always place uninstalled outfits into the cargo hold, even if it exceeds its capacity.
This change will make swapping active and inactive outfits much more comfortable.
N/A
None, sorry.
It is modeled after existing code, so it should be OK.
N/A
Thank you!
> Skip capacity check on Uninstall v2

- data/remnant/remnant ships.txt
**Bugfix:** This PR addresses a missing paragraph indentation
2nd paragraph doesn't have an indent. This fixes it. Also swaps the backticks for quotation marks to maintain consistent styling with the rest of the ship descriptions.
Thanks to Arachi on discord for reporting the missing indentation.
> Fix: Missing indentation on Heron description, and stylization consistency

- .github/workflows/cd.yaml
**Bugfix:** This PR addresses an issue with the pipeline runs.
The other day, Github disabled the `set-env` command ([blog post](https://github.com/endless-sky/endless-sky/runs/1428472982?check_suite_focus=true)). The fix in 58c7501d8d3636ec2d5b239251aea8fb4e00ac18 was almost correct, but didn't add `$GOPATH/bin` to the path:
```bash
echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
echo "${GOPATH}/bin" >> $GITHUB_PATH
```
Unfortunately, appending to `$GITHUB_ENV` only creates the `$GOPATH` variable for the *next* step, so the second command only adds `/bin` to the PATH.
This PR simply uses `$(go env GOPATH)` again instead of `$GOPATH`.
https://github.com/MCOfficer/endless-sky/actions/runs/374012805
https://github.com/MCOfficer/endless-sky/releases/tag/continuous
> Fix setting of environment variables in continuous publish workflow

- data/human/fleets.txt
For five years, the scouts have been locked up in small cages in shipyards, unable to roam free. Well, no longer; this PR changes human fleets so that the scout can roam free in its natural habitat.
Northern, Deep, Paradise, Core, Southern, and Hai human civilian fleets get scouts. Scouts should be reasonably rare outside Deep and Northern merchant fleets.
Northern pirates and pirate raids also gain scouts. Given its ideal characteristics for raiding weak merchant vessels, small northern pirates have a reasonably high chance of getting one of these.
Test file provided, although you can just swap in fleets.txt and check the north.
[Scouty Steve.txt](https://github.com/endless-sky/endless-sky/files/5491858/Scouty.Steve.txt)
> Adding Scouts

- data/human/free worlds epilogue.txt
**Bugfi:**
Removes the `minor` attribute from all the FW Epilogue missions, due to them already having `landing`, which cancels `minor` out.
> Remove "minor" from the FW Epilogue missions

- source/ConversationPanel.cpp
This PR adds the ability to press 'D' to finish conversations. Currently, you can use the number keys to quickly and seamlessly make dialog choices with the left side of the keyboard, but have to move to the right side or the mouse to finish them. Using the 'D' key would make finishing conversations consistent with various other dialogs through Endless Sky, which can be confirmed with the same binding.
N/A
N/A
Finished the conversations at the beginning of the game, with the banker and James, by pressing the D key and return, to verify they both continue to work. Continues to work with both lower and uppercase D, and doesn't cause conflicts on the naming panel.
N/A
> Feat: Add 'D' keybind to finish conversation

- data/coalition/coalition ships.txt
I noticed the Heliarch Interdictor had over 20 free Outfit Space in its stock configuration, a lot more than the other 2 Heliarch ships. Seeing as that variant's main source of damage are the Finisher Torpedoes, I added 1 Finisher Storage Tube to its outfits and increased the amount of Finisher Torpedoes it carries from 80 to 100, to use up the extra ammo capacity offered by the Storage Tube.
> Add Finisher Storage Tube to stock Interdictor

- data/persons.txt
**Bugfix:**
Dropping from 8700 hull to 1200 hull seems like an extreme weakening of the base ship. Increasing from 8700 to 12000 seems reasonable for the appearance and being a person ship.  So this fix assumes that the 1200 is an error wherein it is missing a 0, and adds that missing zero.
> Fix: Changing MCO's person ship to have 12000 hull instead of 1200

- data/remnant/remnant missions.txt
**Bugfix:** This PR addresses issue reported by oo13 on Discord
Fixed the discrepancy that the mission reference for the scene was uppercase, whereas the image name is lowercase.
"scene/Sagittarius A" -> "scene/sagittarius a"
Thanks to oo13 on Discord for spotting this!
Asked oo13 if they can test this PR.
This save file can be used to verify the bugfix. The bug will occur when using the current continuous, and will not occur when using this branch's build.
GitHub is currently being problematic about letting me upload a pilot file, so here's a link to discord where I have uploaded a pilot file: https://discord.com/channels/251118043411775489/536900466655887360/784768232796061756
> Fix: Remnant Astral 2: Makes the scene reference lowercase

- source/PlayerInfo.cpp
**Bugfix:** This is a fix for #5536 .
I simply wrapped the individual ship cargo factor formula in a `max(0., ...)` to raise negative cargo factors up to zero.
I parked and unparked a variety of ships with a variety of cargo sizes to ensure that the cargo factor changes were as expected.
This save file can be used to verify the bugfix. The bug will occur when using 02987b57d6cd414b4da40905bf50dde671f24ad2, and will not occur when using this branch's build.
[Test Test.txt](https://github.com/endless-sky/endless-sky/files/5654389/Test.Test.txt)
> Fix: An unparked, unarmed ship with <=20 cargo space reduces the fleet's piracy threat

- source/PlayerInfoPanel.cpp
Currently, any ships that are disabled or destroyed will show up as red on the Player Info Panel list. This is good for providing immediate feedback that something happened to your fleet. However, this does not communicate if it's a problem that can be fixed (a disabled ship to be repaired), or something you can't do anything about (a destroyed ship) just by looking at colors.
This PR makes it easier to tell at a glance how much trouble you're in after a fight, by making disabled ships appear as an orange color instead of red.
Brought ships in various fleets to disabled, then destroyed states, to make sure they were properly updating when that state changes. Color will update from orange to red as soon as a ship's hull reaches 0.
N/A
> Use separate color for disabled ships in Player Info Panel

- data/hai/hai ships.txt
- data/human/ships.txt
- data/persons.txt
- data/remnant/remnant ships.txt
This PR adds pluralizations for Ibises, Geocorsises, the cargo and bunk Navy Auxiliaries, and Ursa Polaris. The back three are not surfaced in the shipyard, but Marauder Furies are not either, so they were made plural for consistency.
> Added pluralizations for 5 ships

- source/Ship.cpp
**Bugfix:** This PR addresses an issue I spotted while working on #4520.
Ships which are disabled are currently unaffected by ion damage. This PR changes that so that no matter the state of a ship, ion damage affects it.
The issue was that ionization was subtracted from energy just after the energy was increased according to energy generation, but this code was not reached if the ship was disabled. Moved where ionization is subtracted from energy outside of the chunk of code that didn't run if the ship was disabled.
Attacked a disabled ship with and without this change using a weapon with ion damage while using a tac scanner to check energy levels. Without this change the ship's energy levels don't drop while disabled. With this change they do drop.
N/A
> Allow ionization to affect disabled ships

- data/human/outfits.txt
Like #5256, this PR removes reference to the idea of flying unlicensed ships, and replaces it with a mention of spaceport scans, and how interference plating helps with those.
> Update interference plating description

- source/AI.cpp
- source/Engine.cpp
**Bugfix:** This PR addresses issue #5061 
As per #5466 being the wrong way to address this, have discussed and added relevant checks in AI.cpp instead
( and then one check in Engine.cpp so no labels surround the spriteless planet.
I have gone into a system with a spriteless planet and tried to land on it, it was not visible, had no label, no AI tried to circle endlessly around it, the player autopilot didnt find any planet to land on.
Set up the use case of a one-way wormhole, exiting into a system using the spriteless planet, the wormhole worked fine.
I am less confident in this PR, because more changes were required than I originally intended. But seeing as the first one wasnt suitable I feel the obligation to do it properly! hopefully the changes to the AI are in the right place. 
But …
> Add checks for AI so it does not try and land on Spriteless planets

- data/hai/hai missions.txt
**Bugfix:** This PR doesn't address a specific issue number. I just noticed this small typographical error and fixed it directly, but I can open an issue if necessary.
In the Hai mission `Pirate Troubles [1]: Haven`, a line of the existing dialog reads "The gang use to operate exclusively", but contextually the phrase "use to" is probably intended to be "used to" to indicate past tense. 
I changed the text in `hai missions.txt` locally and ran Endless Sky to verify it had no unintended side effects.
> fix(typo): use -> used

- .github/workflows/xcode_check.yml
**Bugfix:** This PR addresses typo in workflow definition `xcode_check.yml`  I noticed it while working in my fork of **master**.
Corrected keyword `branch` -> `branches`
Updated my fork of **master** and the check is no longer run on pushes to branches not defined (my `feature/*` and `bug/*` branches).
N/A
> fix(type): branch -> branches in Xcode project validation

- source/Ship.cpp
- source/Ship.h
- source/Weapon.cpp
- source/Weapon.h
**Feature:** This PR implements the feature request discussed as a way to improve system hazards (#4931).
Adds a new weapon tag `"gravitational"` that causes the hit force of a weapon to not be affected by the mass of the impacted ship. Uses a fixed scaling of 400 mass as to prevent hit force values from needing to be tiny. That is to say that with the `"gravitational"` tag, all ships will be impacted by hit force as if they have a mass of 400.
N/A
All ships hit by this weapon or hazard will be impacted by this hit force of -15 in the same way regardless of mass.
```
[outfit | hazard] <name>
...
weapon
...
"gravitational"
"hit force" -15
...
```
Gave the gravity system hazard from #5560 the "gravitational" tag and entered Sag A* with multiple ships across a wide range of masses. All ships …
> Create a gravitational weapon tag that causes hit force to ignore mass

- credits.txt
- data/interfaces.txt
- source/MapPanel.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #5554
The default behaviour for the map zoom levels is to use hard coded minimum and maximum values. This feature adds a new interface for the **map** in `data/interfaces.txt` along with the necessary changes in `source/MapPanel.cpp` to utilize the values in `data/interfaces.txt`.  The current default min and max values are maintained for now.
Zoom +4
Zoom +3
Zoom -3
Zoom -4
`data/interfaces.txt`:
```
interface "map"
value "max zoom" 4
value "min zoom" -4
```
- Changed values in `data/interfaces.txt` and used **+** and **-** buttons to zoom in/out.
- Scrolled map to ensure scrolling uses values.
- Zoom levels outside the currently defined levels will be maintained when loading player, and the **+** or …
> Allow min and max zoom levels to be defined in interfaces.txt

- data/tooltips.txt
- source/OutfitInfoDisplay.cpp
- source/Ship.cpp
- source/Weapon.cpp
- source/Weapon.h
**Feature:** This PR takes the alternative route to #5568.
This PR creates various new damage types:
* `"relative shield damage"`: Deals shield damage as a percentage of a target's maximum shield value, where 1 = 100% damage.
* `"relative hull damage"`: Deals hull damage as a percentage of a target's maximum hull value.
* `"relative fuel damage"`: Deals fuel damage as a percentage of a target's fuel capacity.
* `"relative heat damage"`: Deal heat damage as a percentage of a target's heat capcaity.
* `"energy damage"`: Deals damage that subtracts directly from a target's energy. Ionization is now the DoT (damage over time) version of this damage type.
* `"relative energy damage"`: Deals energy damage as a percentage of a target's energy capacity.
Also adds a new protection attribute, …
> Create "relative" damage types that deal damage as a percentage of a target's stats

- source/Ship.cpp
**Bugfix:** This PR addresses an issue spotted by Terin on Discord.
Adds a check to see if a ship is overheated at the end of TakeDamage.
Currently in the game, the only time that a ship checks if it is overheated is after it has finished its shield and hull generation. This results in a scenario where a ship that has been overheated will do its shield and hull generation for a frame after taking damage, since TakeDamage overwrites the isDisabled bool that should stop shield and hull generation without checking to see that the ship has been overheated.
Attacked a Shield Beetle with a flamethrower before and after this change. Before, causing the ship to take damage while overheated would activate its shield generation. After, the ship no longer generates its shields for a frame after …
> Check if a ship is overheated during Ship::TakeDamage

- data/persons.txt
Very minor, non-functional patch, but this makes frequency between the Tranquility and Subsidurial consistently formatted. The default frequency is 100, so either both should have it marked (in this case), or neither should have a frequency attribute.
> Add consistent frequency formatting for person ships

- source/LogbookPanel.cpp
- source/LogbookPanel.h
**Feature:** This PR implements scrolling in the list of categories in the logbook
Right now, it is possible to scroll the list of dates and sub-categories in the logbook. However, it is not possible to scroll the list of years and categories ("Factions", "People", "3034"). This is an issue, because it means that on low screen resolutions, on large save files it is not possible to access the latest years of the logbook.
No changes to data files are necessary
I have a large save file which has ~29 years of logbook history. I opened that save's logbook and tried scrolling
N/A
> Added scrolling in the logbook category list

- source/GameData.cpp
- source/GameData.h
- source/SpriteShader.cpp
- source/SpriteShader.h
- source/main.cpp
Use swizzling in shader instead of extension. This is effectively the same but removes the requirement for extension.
I forced swizzle to a constant value at compile time and verified the images look the same before and after my change.
> feat: Move swizzling into shader

- source/AI.cpp
**Bugfix:** This PR addresses issue #5520.
Thanks to the work of Vitalchip, whose work I'm uploading at this PR at their request. For the original issue:
> What seems to be happening is that on a normal approach the ship reaches the calculated stopping point, cuts thrust and passes the point. This makes the ship turn to face the point and then it decelerates using main engines. When there are reverse thrusters they fire, and instead of smoothly passing the stopping point it gets recalculated due to a decrease in velocity, putting it out in front again. The ship moves forward again to intercept and depending on the magnitude of the reverse thrust they may or may not fire again. This behaviour can also happen right before landing causing the ship to 'slide' sideways under reverse thrust, …
> Fix: Improved reverse thruster behavior for landing

- source/Preferences.cpp
- source/Preferences.h
- source/PreferencesPanel.cpp
This PR adds a dialog to Settings that pops ups when VSync state cannot be changed.
I added this popup because otherwise the UI appears unresponsive.
> add a dialog 'unable to switch vsync state' to settings

- data/persons.txt
**Bugfix:** This PR addresses issue regarding Zitchas abandoning drones in systems
The `Surveillance` personality is currently described as:
> scans random ships and visits random planets in system.
However, it has an intentional but undocumented behaviour in that it also causes ships to abandon drones when departing a system. This is used, for example, by Republic ships leaving surveillance drones behind in systems they want to record the activity in. 
Given that it is not intended to have Zitchas abandon their drones, this PR removes the "surveillance" behaviour.
> Fix: Removing Surveillance from Person-Zitchas

- source/Test.cpp
- source/Test.h
**Feature:** This PR implements a small update to the test-framework as discussed in #4308
The test-framework tries to follow the existing [conversation syntax](https://github.com/endless-sky/endless-sky/wiki/WritingConversations) where possible/applicable.
During some updates I noticed that the `apply` keyword as used in conversations was proposed under a different name `assign` in the test-framework. This PR changes the `assign` keyword to `apply` as used in conversations.
N/A
When writing tests, use the `apply` keyword instead of the `assign` keyword.
Variable rename (variable is not in active use), not explicitly tested.
N/A
> Rename assign to apply in testframework to match conversation syntax.

- data/remnant/remnant missions.txt
**Content (Mission)**
In line 2844, the word "who" is omitted from the line "Prefect Chilia, **who** coordinates the military defense of the Remnant."
In line 3405, there is a superfluous quotation mark at the end of the dialogue.
> Typos in Remnant: Cognizance

- .github/workflows/cd.yaml
**Bugfix:** This PR addresses [this error](https://github.com/endless-sky/endless-sky/runs/1666834370) in the CD pipeline.
Note that [the *other* error on that run](https://github.com/endless-sky/endless-sky/runs/1666834401) is likely due to some server issues on github's part; so try, try again.
The pipeline fails because brew tries to install `p7zip`, which apparently is already installed.
I don't know why this only fails now, as `p7zip` was added to the `macos-10.15` image [months ago](https://github.com/actions/virtual-environments/commit/26b764b1e3ab4be906a1ee672d9bf4beaf651b6b). Regardless, this PR removes `p7zip` from the list of packages to be installed.
On a sidenote: I also tried to apply the `--force` flag, which in my understanding should prevent such issues, but apparently …
> CD: Don't install p7zip on MacOS (already installed)

- source/AI.cpp
**Feature:** This PR implements the feature request discussed in a [comment](https://github.com/endless-sky/endless-sky/pull/5583#discussion_r549862995) on #5583
This PR changes the escorts behaviour to Keepstation around its parent while the parent is flying to a planet for landing. Escorts will also go for landing once the parent is landing. 
Escorts slower than the parent will just follow the parent. Escorts faster than the parent will stay near the parent.
N/A
N/A (behaviour is automatically executed by escorts)
Departed from planet with faster and slower escorts and checked that they stay with the parent during landing.
Also waited near the planet for some time to check AI fleet behaviour.
No impact expected, KeepStation is very common behaviour for escort ships.
> Keep escorts close to parent while flying towards planet for landing.

- source/PlayerInfo.cpp
This PR modifies the damage value used in deterrence calculations, by letting weapons that deal relative damage add to your fleet's DPS calculate it based on the vitals of the ship that's carrying it. While this is theoretically game-able by having it change based on what ship it's installed on, it would still let a plugin creator use small values of relative damage without completely blowing out the piracy threat scale, and would be better than any constants we could come up with.
As shown above, I tested by using two weapons (Deterrence from Omnis, which does 100% damage 60 times a second, and Deterrence Mini, which does 10% damage 1 time a second) on two different types of ships, the Star Barge and the Archon. I parked and unparked various combinations of those ships to see the fleet …
> Increase deterrence from relative damage weapons

- data/map.txt
- source/Ship.cpp
- source/System.cpp
- source/System.h
**Feature:** This PR implements the Jump drive part of the feature request detailed and discussed in #4334
This PR splits the keywords for arrival distances in systems into a hyperdrive-version, a jumpdrive version and a common syntax to set both.
This feature only works for systems. Setting arrive distances relative to a planet is not implemented yet.
N/A
Use the following keywords on relevant systems:
To set a default arrival distance for all (jumpdrive, hyperdrive):
```
arrival <nr>
```
To set a default arrival distance, but a specific one for hyperdrives:
```
arrival <nr>
link <nr>
```
To set an arrival distance for jump drives only:
```
arrival
jump <nr>
```
To set an arrival distance for jumpdrive and hyperdrive only (different from first example in case we get a 3rd drive type): …
> feat: Split arrival distance into hyperdrive and jump-drive version.

- data/help.txt
- source/BankPanel.cpp
- source/Hazard.cpp
- source/MainPanel.cpp
- source/MapDetailPanel.cpp
- source/MapOutfitterPanel.cpp
- source/MapShipyardPanel.cpp
- source/MissionPanel.cpp
This PR adds new tutorials and tutorial calls to the game, which explain to the player many undocumented features of Endless Sky, either only documented in the wiki, or undocumented entirely.
These include:
- `bank advanced`: Opens when a player first pays off, or applies for a new loan, which explains suffixes available to them.
- `multiple ship controls`: Appears when first launching into space with additional ships, which explains fleet commands, right click to issue spacial commands, and control groups.
The following tutorials are advanced map panel tutorials that appear after roughly two weeks, while on planet. This is done so the player has time to gather a good amount of system, ship, and outfit knowledge, do the tutorial if it wasn't skipped, and so they are in a situation with …
> Feature: Additional Tutorials

- data/help.txt
- source/ShipInfoPanel.cpp
- source/ShipInfoPanel.h
One last tutorial I hope to get in before the cutoff. Was considering putting it the original PR after I posted it, but it got merged so quickly!
This tutorial covers the Ship Info tab, more explicitly explaining how to re-arrange hardpoints, and describing the completely undocumented ability to rename ships. After seeing #5625 mention how they had to edit saves to rename ships, and other recent mentions on the Discord server, I figured this was worth getting in. It can be expanded if something like #4714 gets merged in the future, as well.
Very few code changes unlike #5622, just a simple override of Step() like the other panels.
> Add Ship Info tutorial

- data/wanderer/wanderers start.txt
Use the american form of "empathi**z**e" instead of "empathi**s**e".
> Fix typo in wanderers start.txt

- data/human/transport missions.txt
**Bugfix:** This PR addresses erroneous indentation in the conversation starting on line 3136 of `transport missions.txt`
Removed one tab from each line of this conversation.
Thanks to 7even for spotting this problem!
> Fix: Overly-indented conversation in Transport Missions.txt

- data/remnant/remnant missions.txt
- data/wanderer/wanderers start.txt
There are currently two missions in the game that have the player travel to Alexandria to get a copy of human cultural data, once for the Hai and once for the Remnant. There's no reason though that the player should have to make this same trip twice when they could have easily just saved a copy of the cultural data for themselves.
This PR makes it so that if you retrieve the cultural data for either the Hai or the Remnant, a condition "human cultural data" is saved. This condition is then used when you are asked by the other group to retrieve this data, allowing the player to skip over a trip to Alexandria. By using this condition instead of checking for the `: done` condition of the opposite mission, this also allows this information to easy be …
> Save human cultural data for later

- data/human/deep missions.txt
- data/map.txt
- data/remnant/remnant missions.txt
The capitalization of quantum keystone and quantum key stone was all over the place. This PR standardizes the capitalization, settling on lowercase "quantum keystone" when referring to Hai stones and capitalized "Quantum Key Stone" when referring to Remnant stones. This further emphasizes the difference in how the Hai see the stones and how the Remnant see them.
This PR also removes all references to keystones/Key Stones as crystals, instead using the term stone(s) when referring to the two types.
No save necessary.
> Standardize capitalization of Quantum Key Stone/quantum keystone

- data/map.txt
**Bugfix:** 
This PR does NOT actually fix the issue described in #2230 , however it does fix the fact that this issue crops up in Remnant systems right now.
Do to how the UI functions in-game, on small monitors the number of visitable planets in some Remnant systems (particularly in a gaslined ship) overloads the display and makes it impossible to see all the visitable places.
This PR adds the "requires: inaccessible" attribute to 11 such places and trims the Remnant systems down to 3 visitable planets:
- 1 inhabited planet (visitable normally)
- 1 uninhabited planet (visitable normally)
- 1 uninhabited gas giant (visitable with gaslining)
So normal ships will see 2 visitable planets in each system, and gaslined ships will see 3.
Play the game and look at the map in various Remnant …
> Fix: Culling 11 visitable objects from Remnant space

- tests/retryable_issues.txt
- tests/run_tests.sh
**Feature:** This PR implements a retry mechanism for the CI integration tests if the tests fails on a known framework issue (#4308, #5645)
If the testframework detects the error-message `SDL message: "No available video device"`, then it will retry to run the test (max 5 times). This SDL errormessage would (usually) not be related to the test itself, but looks like an intermittent issue between endless-sky, Xvfb and Ubuntu 20.04. We should still handle the `SDL message: "No available video device"` error in the future, this PR only acts as a workaround to prevent CI for unrelated PRs from failing on this error-message.
N/A
Automatically runs as part of the CI-jobs.
Tested with succesfull tests, failing tests and tests failing with the specific error-message.
N/A
> tests: Retry test if it fails on framework/Xvfb issue

- source/ShopPanel.cpp
**Bugfix:** This PR addresses issue a bug that @Amazinite describes in Discord.
This PR fixes a bug where an information of your cargo space is not shown in the Shop Panel.
This bug is introduced by 48926c015e39bb04ab2d81bdb27a5f3a175459d1.
You enter a shipyard and deselect your flagship, 'cargo space:' is shown under the shape of your ship but no _free space / cargo capacity_.
I enter a shipyard and deselect my flagship, the shop shows me _free space / cargo capacity_.
> Fix a bug where an information of your cargo space is not shown in the Shop Panel.

- data/remnant/remnant missions.txt
**Bugfix:** This PR addresses an issue reported on GitHub where the em dash appears as three boxes on Linux.
On line 4256 there is an em dash where there should simply be a hyphen. This has reportedly caused three boxes to appear on Linux.
As a side note, I did a search through all the data files, and couldn't find any other em dashes. (using Notepad++'s "find all in files" feature). Hopefully there are no others. 
Thanks to Kanerix on the Discord group for reporting this bug.
> Fix: Removing an Em-Dash

- source/LoadPanel.cpp
If you have a pilot with enough snapshots and scroll down to the bottom, then you swap to a pilot with only the default amount of saves, the center panel will appear blank unless you scroll up. This PR causes the center scroll value to reset when selecting a new pilot.
Tested that the scroll properly resets when selecting a new pilot, and stays as-is when clicking anything else.
Here's the bug without the fix. With the fix, you'll just see things as normal.
Save file includes a pilot with many snapshots, in case you don't have one
[saves.zip](https://github.com/endless-sky/endless-sky/files/5861593/saves.zip)
> Fix: Reset snapshots scroll when swapping to different pilot

- source/Engine.cpp
- source/Ship.cpp
This is a reopening of #4366.
Changes in the game:
1. Player cannot have both ship and asteroid targets simultaneously.
2. Clicking on ship deselects selected asteroid.
3. Clicking on asteroid deselects current ship.
4. Clicking on empty space deselects both ship and asteroid.
5. Asteroid target is now highlighted regardless of distance to flagship.
[testsave.txt](https://github.com/endless-sky/endless-sky/files/5860438/Broken.Escorts.2.escorts.stuck.txt)
> Asteroid and ship selection enhancements

- data/map.txt
**Bugfix:** This PR addresses the issue that the new systems in the Ember Waste's data isn't sorted correctly.
Moving system attributes into the following order:
- Pos
- government
- attributes
- haze
- link
- asteroid
- first by type, then by size.
- minables
- hazards
- objects
- From innermost to outermost.
> Fix: Cognizance system data sorting

- data/intro missions.txt
- data/map.txt
**Content**
I simulated population sizes of all the worlds in human space. Some planets have mentions of their population size, but the numbers I ended up with don't match the descriptions. Instead of lowering the total number of people as given by MZ at roughly 100 billion, and instead of bringing up the population density of lesser inhabited planets by an insane amount just so I could reach that final number without clashing with the planet descriptions that existed, I've decided to change some descriptions according to what I simulated, essentially canonizing the numbers I came up with.
Link to my numbers is [here](https://docs.google.com/spreadsheets/d/1dWKimAiiXrlVCibdjyiFNqtQJdiXJqB7F0Cs9La0Z60/edit?usp=sharing).
The sheet also includes settlement dates for planets where they could …
> Update references to population sizes of human worlds

- data/human/jobs.txt
Added hyphen to `grizzled-looking`, added comma to separate the two clauses.
> Fix Typo in "Raid Warning"

- data/human/kestrel.txt
- data/persons.txt
Change bay definition of Kestrels to match the change in 79260f206e28370f1a26f1b32b8011babe3794cd.
Also missing are bay definitions for the Prototype Kestrel. Should bays be added to this variant, or be held back for the finalised Kestrel?
> Change Kestrels to use new bay syntax

- data/drak/indigenous.txt
**Bugfix:** This PR addresses the fact that the Void Sprites are synchronized
After spending some more time hanging out with the new and improved Void Sprites, I realized that they don't have random start frames. This adds that.
Spent a lot of time visiting Nenia.
> Randomizing Void Sprite Start Frames

- data/human/fleets.txt
- data/remnant/remnant.txt
- source/AI.cpp
- source/Ship.cpp
**Bugfix:** This PR addresses issue #5540
This creates another problem: endless plundering (since the plundered ships are no longer killed, every ship entering the system that can plunder it does so).
[Craig.McCauley.txt](https://github.com/endless-sky/endless-sky/files/5881207/Craig.McCauley.txt)
> Ships with "disables" personality no longer kill plundered ships

- source/AI.cpp
- source/MainPanel.cpp
**Bugfix:** This PR addresses issues #4480 and #4736.
Player cannot attempt to do anything while landing or departing.
Landing and departing works normally, so there shouldn't be any issues.
[John Brown.txt](https://github.com/endless-sky/endless-sky/files/5904234/John.Brown.txt)
> Player cannot attempt to hail / land / jump / board / whatever while landing / departing

- data/interfaces.txt
- source/Command.cpp
- source/PreferencesPanel.cpp
Conflicting keybindings are saved to player's save file instead of reverted to default.
This is a reopening of #5611 with red keybinding conflict color changed to yellowish and the comment corrected.
Fixes #5582.
> Conflicting keybindings are saved

- source/AI.cpp
This is a correction of #5681. I noticed that previously you could initiate jump command while departing from planet and after #5681 you cannot. This PR lets the player do anything except landing while he is departing from a planet.
> Player can begin jump preparations while departing from a planet

- .winmake
**Bugfix:** This PR addresses a rare issue in the windows build.
The Makefile tries to download scons if it doesn't exist on the system yet. However, if sourceforge has issues and indicates this with status codes, it will still proceed to unpack the response as tarball (or rather, attempt to). This results in opaque errors such as
```
No system installation of SCons, downloading version 4.0.1
curl -sS -L http://sourceforge.net/projects/scons/files/scons-local/4.0.1/scons-local-4.0.1.tar.gz > scons-local-4.0.1.tar.gz
Unpacking tarball into scons-local
tar: Error opening archive: Unrecognized archive format
```
(from <https://github.com/endless-sky/endless-sky/runs/1819132923?check_suite_focus=true>)
This PR adds the `-f` flag to the curl invocation. We already use `-S` which makes curl …
> Makefile: curl should fail on invalid status

- source/Flotsam.cpp
- source/Flotsam.h
**Feature:** This PR implements a feature that's been talked about for a while now.
Flotsams are outfits or commodities that have been jettisoned from ships or dropped by destroyed minable asteroids. These flotsams have been criticized as dying too quickly, and in the case of asteroids their flotsams have been criticized as moving too quickly to pick up.
This PR does two things:
1) Greatly increases the lifetime of flotsams. Commodity flotsams use to last anywhere from 6 to 11 seconds for a full box. Full commodity boxes now last between 2 and 3 minutes. Outfit flotsams on the other hand last 10 times longer than they use to. For example, ore flotsams use to last about 8 seconds. They now last about 80. (Flotsam lifetimes range from about 80 to 85 seconds on average depending on the type …
> Greatly increase flotsam lifetimes and add drag

- data/intro missions.txt
**Bugfix:** This PR addresses the fact that people may not be aware that:
a) Earth Day is an actual real-life thing.
b) That in the 4th millennium humanity still actually celebrates a day that exists in real life.
c) People may not be aware of the date of the real-life thing, or associate the two.
Adds in a mention of the date "April 22nd" in Jame's explanation.
> Fix: People may not know when Earth Day is but James assumes they know.

- data/human/fleets.txt
Currently, a small southern pirate fleet can spawn anything from a single Sparrow, to three Furies with two Meteor Missile Launchers each. While there should be some variety, this is too much for the lowest end, and is reduced to two ships in this PR.
> Lower amount of missile Furies in small southern pirates

- .gitignore
This PR adds .gitmodules to ignored files, letting developers make use of git submodules to download and track plugins within their local repo, without having to push changes or create a separate branch. For example, you can run a command like this to add endless-sky-high-dpi to your plugins folder:
```
git submodule add -f https://github.com/endless-sky/endless-sky-high-dpi plugins/endless-sky-high-dpi
```
Then you could cd to that plugin folder and use git commands like normal (while the ES git repo would normally override it), and even some git submodule commands to affect them all.
There are a few things to be aware of if you work with submodules:
- When first adding submodules, it looks like it automatically stages .gitmodules and the downloaded plugin, so you'll have to run `git …
> Add .gitmodules to ignored files

- data/remnant/remnant ships.txt
**Bugfix:** 
This PR addresses the issue reported by clifflocked on the Discord group. Thank you! We always appreciate people playing the game and letting us know when something seems wrong.
Currently, the player can buy the puffin, and then strip it to gain access to Quantum Key Stones before they have the license. This fixes that. 
Of course, they'll still be able to get the anvil-class combined engine...
Moving the keystone out of the outfits and into the hull.
Correspondingly, this also reduces the available outfit space by 1.
> Fix: Removing the Key Stone from the Puffin

- data/human/free worlds middle.txt
Rand and Oblivion are on the North-eastern fringe of the Dirt Belt, not the north-western.
> Change "Northwestern" to "Northeastern" in "FW Rand 1"

- source/GameData.cpp
**Feature:** This PR implements the feature as described in the title
Firing force and hit-force can be important weapons characteristics to take into account when balancing ships.
This adds those two forces to the weapons table overview so that content creators can easily use them for balancing ships and weapons.
N/A
Run `endless-sky --weapons` to get the overview.
I used the newly printed values to choose weapons for an NPC ship I was creating.
None, only affects the printing function which is not run in-game.
> feat: Print firing and hit forces in weapons table overview

- data/map.txt
- data/remnant/remnant missions.txt
**Bugfix:** This PR addresses the gameplay element that revealed issue #5734 
- Postverta is described in the mission and lore as a system that appears where there wasn't one previously. This description comes from the Remnant, who have the best scanners available, long experience in the Ember Waste, a very strong astronomical program, and a keen awareness of their environment.
- Currently, this is implemented by giving Postverta the `hidden` tag, which renders it invisible and thus can't be jumped to via JD.
- Unfortunately, if the player can somehow gain access to any of the other Cognizance systems (such as Egeria, Prosa, Statina, or Diespiter) they will be able to follow the hyperdrive links to reveal Postverta, and thereafter be able to see it and jump to it whenever they want.
- …
> Fix: Making Postverta Properly Hidden

- data/hazards.txt
- data/map.txt
Amazinite and a few other people suggested that Sagittarius A* wasn't sufficiently scary, and ships with particularly good regen could last rather long periods even right on the event horizon.
So, this PR has two effects:
Firstly, ramps up the damage:
- (accretion disk) shield damage from 0.00028 up to 0.0018
- (event horizon) hull damage from 0.00028 up to 0.0009
Secondly, to maximize the impact and allow players to approach Sag A* instead of just being dropped on it, the system arrival distance has been changed from 500 out to 2000.
A range of values and combinations were tested, including:
- Doubling just the shield damage.
- Doubling the shields and small increase to hull damage.
- Various increases in damage. 0.00164 and 0.00082 were good too. …
> Tweak: Making Sagitarius A* deadlier

- data/human/ships.txt
It's established in some of the spaceport flavor text that ship
insurance doesn't exist. Therefore this text about insurance reports
indicating such-and-such about the Sparrow's longevity doesn't make
sense. Let's change it to something else.
> Don't mention insurance report in Sparrow description

- source/Test.cpp
- source/Test.h
**Feature:** This PR implements the navigate step of the test-framework as discussed in #4308
This adds the navigate step for the test-framework.
The code is nearly identical to the code used for the navigate steps in earlier versions of the framework.
N/A
See the testcase at [ES Stories|https://github.com/kikotheexile/Endless-Sky-Civil-War/blob/21e9676e58f01fdb2d7803e1ec0f7efe2b7beaca/data/tests/tests_framework.txt#L118] for the syntax of the navigate step (note that the other steps are using a different syntax though).
Tested in earlier versions of the framework and tested in ES Stories. I plan to bring the testcases also to ES when the test-framework in ES is more complete.
N/A
> feat: Integration Test Framework: Add navigate step

- data/interfaces.txt
- source/LoadPanel.cpp
**Bugfix:** This PR addresses issue where the items in load and start panels slightly misaligned vertically.
Especially in low res, I can see the texts of the items in load and start panels slightly misaligned to lower than preferences panel.
current version
preferences
Upper margin of 'l' and 'h' is 3 dots, lower's of 'p', 'y', 'g' is 2 dots.
load panel
Upper margin of 'l' and 'h' is 4 dots, lower's of 'p', 'y', 'g' is 1 dots.
start panel
Upper margin of 'l' and 'h' is 4 dots, lower's of 'p', 'y', 'g' is 1 dots.
This PR
load panel
Upper margin of 'l' and 'h' is 3 dots, lower's of 'p', 'y', 'g' is 2 dots.
start panel
Upper margin of 'l' and 'h' is 3 dots, lower's of 'p', 'y', 'g' is 2 dots.
> Vertically centered the items in load and start panels.

- data/tooltips.txt
- source/Projectile.cpp
This PR aims to make missile tracking and jamming much more strongly affected by the characteristics of the target ship and the missile's tracking and homing methods, rather than being something that almost always works no matter what. This is more fun, rewards the player for equipping their ship appropriately, and makes missiles a bit more likely to miss their targets on average.
To that effect, it implements the following technical changes to jamming and tracking:
- Double the "resolution" of missile tracking by checking for lock twice as frequently
- When a missile has lost its lock, zero out its base chance to regain it
- Attenuate the effects of radar jamming proportional to the distance between the jammer and the missile; more jamming means that radar-guided missiles can become …
> feat: Overhaul jamming and tracking to make them more fun and realistic

- data/human/weapons.txt
With the jamming and tracking changes in https://github.com/endless-sky/endless-sky/pull/4204, I've slightly adjusted the Torpedoes, Sidewinder, and Meteor.
The humble Meteor finally has a useful battle role: it is now a short-range bombardment weapon that is optimally fired from fighters against medium-to-large-sized ships, but can be used against small maneuvering ships when fired by a skillful pilot (i.e. the player).
However, it's still just as forgiving to new players--in fact maybe even more so: By worsening its tracking, it is now easier to dodge in a small ship. Its reduced range means that it won't come from out of nowhere. Reduced homing mean that when it misses, it never comes back around for another attack run.
The sidewinder's range was nearly cut in half. It's now …
> Adjust human guided missiles to adjust to jamming and tracking changes

- data/human/free worlds checkmate.txt
The dialogue used during FWC Pug 4B when you accept Freya's request to check with the Quarg is particularly clunky.
Freya asks the player that they should try to go to the Quarg, the player responds with yes, then Freya asks the player to trust her on this, even though the player has already said they wanted to go, then the player replies saying that "it can't hurt to try", despite having already explicitly saying that they wanted to go.
This PR changes it so that when the player accepts Freya's request, she only thanks the player and expresses her hope in getting useful answers.
> Fix clunky wording in FWC Pug 4B

- source/OutfitterPanel.cpp
- source/OutfitterPanel.h
- source/ShipyardPanel.cpp
- source/ShipyardPanel.h
- source/ShopPanel.cpp
- source/ShopPanel.h
This is a quick fix for the CanBuy function that was checking both items for sale as well as items already owned. That behavior was not correct if the player was asking for explicit buying. The function now has an additional boolean parameter to indicate if the already owned items should be checked or not.
Fixes: https://github.com/endless-sky/endless-sky/issues/5787
Executed the test-scenario from #5787 and performed some buy/sell actions of other outfits in the same game.
See the description in #5787 on how to setup a test-scenario quickly.
> bugfix: Add parameter to CanBuy to indicate if owned items should be checked

- data/persons.txt
This PR tweaks the frequency values for the three Ember Wastes-adjacent person ships. Currenctly, Becca's person ship has an over _one hundred_ times chance to spawn, compared to Zitchas's, and two hundred of the Subsidurial. The values are now adjusted to 1000, giving them a good chance to show up over regular person ships when in the eligible systems, but not overwhelmingly so.
> Equalize Ember Wastes person frequencies

- changelog
- data/human/boarding missions.txt
This commit adds a new assisting mission occasionally offered when
patching up a disabled merchant freighter. In it, the player meets a
sinister fellow named captain Tarquin who is running a secret slave
ship, and is given the option to help him, kill him, apprehend him and
turn him into law enforcement, die, or bungle the situation entirely
and let him escape, in which case he harbors a hatred of the player
that may cause him to pop up later in a future minor mission that is
yet to be written.
There are two variants: one if the player has a brig, and one for without one. This is an unfortunate implementation that results in a lot of duplication, and is working around the fact that testing for the presence of an outfit cannot be done inside a conversation.
Both variants are quite …
> feat(content): Add sinister assisting mission about a secret slave ship

- changelog
- data/drak/indigenous.txt
- data/persons.txt
**Bugfix:** This PR is a followup to #5104.
This PR addresses two issues that prevented the Subsidurial from spawning. First, it adds a "jump speed" attribute to it, which is required for a functional hyperdrive to jump in. Second, it adds the second (vestigial) token to the ship definition necessary to spawn the ship, an issue described in #5797.
Also includes minor formatting fixes to the persons file.
Removed the person ship spawning limiter, which causes all person ships to spawn in at once, and saw the Subsidurial finally coming in with all the rest (while in an uninhabited system).
> Fixed issues that prevented Subsidurial from appearing

- data/human/boarding missions.txt
**Bugfix:** This PR fixed some bugs in the missions "Slave Crew Rescue (No Brig Variant)" and "Slave Crew Rescue (Brig Variant)."
- A Hai ship doesn't offer these missions.
- You cannot resurrect captain Tarquin even if you buy or sell a Brig.
- Some formatting errors (indentations and closing quotation marks) are corrected.
- Typo fixed (redundant "sure").
- Remove an invalid ship category "Medium Freighter."
I tested these missions modified by "random < 100."
1. I assisted a Bulk Freighter without Brig, and got offered "Slave Crew Rescue (No Brig Variant),"
2. and then I installed a Brig and assisted a Bulk Freighter, and didn't get offered "Slave Crew Rescue (Brig Variant)."
3. I removed "Slave Crew Rescue (No Brig Variant): offered" from the save file.
4. I assisted a Bulk Freighter …
> Fix (content): "Slave Crew Rescue" missions.

- changelog
- credits.txt
- data/remnant/remnant missions.txt
**Bugfix:** This PR doesn't address an existing issue.
Upon showing a Remnant engineer my pair of S-970 Regenerators, I was asked to please deliver them to Esquiline. While it's possible that the Remnant have some legitimate reason for building an impact testing facility on a gas giant, actually delivering them in any gaslined ship available to the player requires lots of cargo expansions and imported power/engines small enough to fit in the remaining outfit space. (I'm pretty sure it can be done in a Penguin. It can definitely be done in a Petrel, although there's no in-game indication that Petrels are gaslined. It definitely can't be done in a Puffin or a Tern. It would be easy to do in a Heron, but only if you're @Zitchas. I assume it can be done in a fleet of gaslined ships, but I …
> Choose sensible destinations for remnant tech retrieval missions

- data/ka'het/ka'het ships.txt
Changing `"hull repair"` to `"hull repair rate"`.
Also to note: The Ka'het ships have shield heat without shield regeneration, and hull repair rate without any cost to it. Could someone tell me whether that was intentional or not?
> Use correct vocabulary for hull repair in Ka'het ships

- data/remnant/remnant missions.txt
The word "paid" is mis-spelled as "payed" in Remnant: Keystone Research 1.
Thanks to Bardagh on discord for spotting it.
Note, payed is actually a properly spelled word, but it has nothing to do with buying things. It has to do with sealing ships.
> Fix: Spelling mistake in Remnant: Keystone Research 1 - payed -> paid

- data/coalition/coalition outfits.txt
**(Balance)**
This PR  buffs the Heliarch Overcharged Shield Module and Overclocked Repair Module outfits.
The buff consists of the following:
- Reduced the constant energy consumption of the OSM from 90 to 30.
- Increased the shield generation of the OSM from 222 to 276.
- Increased the hull repair of the ORM from 78 to 84
The sum of the increases in regeneration is exactly 60, the amount subtracted from the energy consumption, that way the active energy usage of both those outfits can also be increased to match the regeneration, keeping them in line with the other Coalition regen outfits.
The changes that aren't purely buffs are the following:
- Increased the shield energy of the OSM from 222 to 276, to match its new shield generation value.
- Increased the hull …
> Buffed the OSM and the ORM.

- SConstruct
**Bugfix:** This PR addresses an issue introduced in 599142ac9a1ec88dc1ee525c1c776ac29f8ee9ac
599142ac9a1ec88dc1ee525c1c776ac29f8ee9ac changed the recursive glob in `SConstruct` to exclude anything containing `main.cpp`, rather than anything ending in `/main.cpp`. This caused the file `tests/src/test_main.cpp` to be excluded when compiling unit tests, which caused all unit test compilations to fail.
This fix simply re-adds the leading slash, so `test_main.cpp` isn't excluded anymore. This could in theory also match files such as `foo/main.cpp/myfile.cpp`, but I don't think we'll be seeing those anytime soon...
Waited for the CI run to not blow up.
> fix the failing unit test compilation

- data/remnant/remnant missions.txt
**Bugfix:** 
Fix capitalization of "License" to "license" so the mission "Remnant: Deep Surveillance" can actually trigger.
It's a one character change! Can't go wrong. Tested that it now triggers.
This save file can be used to verify the bugfix. The bug will occur when using 65d14e, and will not occur when using this branch's build.
[Nine Of Thirteen.txt](https://github.com/endless-sky/endless-sky/files/6338069/Nine.Of.Thirteen.txt)
> Fix capitalization of "License" to "license" for "Remnant: Deep Surveillance"

- data/coalition/coalition ships.txt
- data/coalition/coalition.txt
**Content (Variant)**
I noticed the Heliarch Interdictor was the only Heliarch ship (with the exception of the Rover, which has it as the stock variant) to lack a Scrappy (solely Bombardment Cannons and Turrets) variant, so I made one for it.
This also adds the variant to the Heliarch fleet spawns.
> Create Scrappy variant for the Heliarch Interdictor

- data/map.txt
**(Typo/plural fix)**
Just changed the description to use the proper plural `for the Arachi` instead of `for the Arach.`
> Typo/plural fix for Dwelling of Speloog's description.

- source/Ship.cpp
**Feature:** This PR implements the feature request I thought of because I'm amazing.
Currently when a ship is repaired, it gets repaired to MinimumHull(). Given that a ship becomes disabled if its hull is less than MinimumHull(), being repaired to this point means that any non-zero positive hull damage will immediately cause the ship to become disabled again. This can be especially frustrating when trying to assist a ship in the middle of combat, only to see it immediately become disabled again.
This PR changes it so that ships now get repaired to MinimumHull() * 1.5, giving some buffer room after a ship is repaired before it becomes disabled again.
Ships typically become disabled after reaching 15-45% hull remaining, with smaller ships becoming disabled sooner. Using MinimumHull() * 1.5 …
> Ships get repaired to MinimumHull() + some extra

- data/coalition/coalition missions.txt
**Bugfix:** This PR doesn't address an existing issue.
I noticed two minor problems with the Saryd Couple mission chain while playing a recent continuous build. This PR fixes both:
* a typographical error: `alhough` -> `although`
* the couple can't afford their stated purchases: increased budget from `1,500,000` to `two and a half million`
The budget probably needs a little explanation. The Arach Courier's ship data has `"cost" 723000`, which is about half of their original 1.5M budget (the other half being spent on the land). However, that's just the base hull and the actual purchase price of the ship includes the installed outfits, for a total of ~1.2M. In addition, they still need to pay the 325k mission reward -- leaving them with a significant shortfall even before shopping for …
> Minor coalition mission fixes

- data/help.txt
Fixed a tutorial typo for the payment dialog. An alternative could be "use suffixes K, M, B, and T...", but I think the current feels more natural.
> Fix bank tutorial typo

- data/persons.txt
> Fix typo in Author hails

- data/help.txt
Small typo fix:
"For example, enterting..." -> "For example, entering..."
Credit to the Discord user Lance for spotting the typo.
> fix(typo): Change "enterting" to "entering"

- source/Preferences.cpp
This PR removes 'Interrupt fast-forward' as on by default. While this is a handy option for people who frequently board and want 1x speed to safely get away, that is a small part of a game compared to just traveling around at 3x, which this option interferes with by disabling fast-forward as soon as you land. I don't think anyone would suspect this change in behavior is even an option, unless they are hooked into the Discord or Steam forums, and has someone else tell them otherwise.
We've had much, much less disruptive gameplay and UI elements added to the game and default to off, so I do not know why this one defaults to on.
> Set 'Interrupt fast-forward' to off by default

- data/remnant/remnant outfits.txt
**Bugfix:** This PR addresses issue #5918 
Changes Smelter reverse thruster heat from 1.5 to 6.12.
Thanks to ph2000bis for spotting this.
> Fix: Correcting Smelter-Class thruster reverse heat

- data/coalition/coalition missions.txt
- data/hai/hai missions.txt
- data/human/free worlds epilogue.txt
- data/human/free worlds intro.txt
- data/human/free worlds side plots.txt
- data/intro missions.txt
- data/remnant/remnant missions.txt
- source/Mission.cpp
**Feature:** This PR implements a feature that should stop my dumb ass from making changes like https://github.com/endless-sky/endless-sky/commit/62f0226bd1483c0d6ec02b01c258ac9f2993c826 again.
This PR adds a warning that gets written to the error file if a mission has either the minor or priority tag and also has the landing tag, as minor and priority don't effect landing missions.
N/A
N/A
Let's see what the test parses turn up.
N/A
> Warn about minor or priority being mixed with landing for missions
