endless-sky/endless-sky

- data/remnant/remnant missions.txt
This PR fixes some issues in Remnant: Keystone Research 1, 3 and 4
- Remnant: Keystone Research 1
In the dialogue, you're told to go to Allhome then Greenwater, but it's the other way around.
(We could also keep the dialogue unchanged and change the  destinations of this mission and the next instead.)
- Remnant: Keystone Research 3 to 3B
The `on stopover` dialogue was intended to be displayed on first `stopover`, but was shown on last instead. I moved it to the following invisible mission which is offered on first stopover (no matter the order in which you visit the planets), and moved and rephrased the dialogue of that mission to the next one. (3A -> 3B | 3 -> 3A)
- Remnant: Keystone Research 4
`on accept` dialogue wasn't displayed (probably because the player doesn't accept the …
> fix(content): Fix Remnant: Keystone Research missions

- source/Ship.cpp
**Bugfix:** This PR addresses a new crash I discovered!
Not only does -20 slowing damage break the game, it seems any amount of negative disruption damage breaks the game too. This PR puts firing ion, slowing, and disruption into the same vein as firing heat- negative values are now interpreted as requirements for firing, and so they will not drop below 0.
(I can't imagine what other issues this would create, but) weapons which have negative firing ion/slowing/disruption do not fire unless your ship has that amount of the value or more.
No vanilla weapons have negative firing ion, slowing, or disruption, so you would need to make a plugin with a weapon with such to test in and out of the bugfix, but anything with negative firing ion/slowing/disruption simply breaks the game.
> Prevent negative ion/disruption/slowing via firing

- data/wanderer/wanderers start.txt
**Bugfix:** This PR addresses an [issue reported on discord](https://discord.com/channels/251118043411775489/536900466655887360/841859108952080404) by user sasbot#9952.
By using `near "Ya Hai" 1 100` as a source filter in the mission "Wanderers: Hai Diplomat", Mirrorlake was excluded as a source and the player couldn't ask for an interpret there. I replaced it by `not planet "Hai-home"`.
I tested the missions from "First Contact: Wanderer" to "Wanderers: Diplomacy" in three cases: going directly to Hai-home, going to Mirrorlake then Hai-home, and going to a Hai world outside Ya hai then Hai-home.
[Test~wanderer-first-contact.txt](https://github.com/endless-sky/endless-sky/files/6465923/Test.wanderer-first-contact.txt)
This save file sets the player on Vara K'chrai with `"First Contact: …
> Allow "Wanderers: Hai Diplomat" to be offered on Mirrorlake

- data/korath/korath missions.txt
This PR fixes an [issue reported on discord](https://discord.com/channels/251118043411775489/460553532404400132/842508011984781353) by user BBHood217#8047.
In Korath mission "Sestar Fort Heating" the conversations had three occurrences of  `<payment> credits`, but `<payment>` is already replaced by `N credits`.
> Fix Korath mission "Sestar Fort Heating": `<payment> credits` -> `<payment>` 

- data/wanderer/wanderers middle.txt
After meeting with the exiles, Tele'ek and Rek meet with the player. However, the first time that Tele'ek speaks, he does so without any of the [trademark, unique] Wanderer syntax. This PR gives that dialogue to Rek, which also fits in more, as Rek is a diplomat and would be able to more adequately realise the strangeness of the Exile peace talks.
> Reassign fluent dialogue from Tele'ek to Rek

- data/ka'het/ka'het missions.txt
- data/map.txt
- data/quarg/quarg missions.txt
**Bugfix:** This PR doesn't address any known specific issues. It just cleans up some typos I noticed in a recent playthrough.
I've included three separate commits for three different minor text corrections. If you disagree with some but agree with others, I'll gladly rebase, drop or amend, and re-push with whichever parts you want to keep.
1. In most of the game text, whenever starting a sentence with a prepositional phrase, the established pattern is to follow that phrase by a comma before proceeding. 16ce09f8 adds a missing comma in one of these cases.
2. The description for "Starting Rubin" says the station is "on orbit" but I'm pretty sure this is meant to say it's "in orbit". The latter is much more typically used to describe the location of one thing orbiting another, whereas the …
> fix(content): various minor typos

- changelog
- data/remnant/remnant missions.txt
**Bugfix:** This PR addresses issue #5990
"Remnant: Face to Maw 1" has recently been changed so that it's not offered during the Cognizance missions (18b8c99). The mission "Remnant: Face to Maw 1B" which is supposed to be offered at the same time wasn't updated. That means that during the Cognizance missions, the player can currently be offered "Remnant: Face to Maw 1B" without having "Remnant: Face to Maw 1" too.
This PR gives "Remnant: Face to Maw 1B" the exact same `to offer` conditions as "Remnant: Face to Maw 1".
Limited. I only tested that the mission doesn't offer during Cognizance.
[github-5990-fix.txt](https://github.com/endless-sky/endless-sky/files/6526984/github-5990-fix.txt)
This is a modification of 2phunkey4u's save. It places the player on Viminal with "Remnant: Cognizance …
> Don't offer "Remnant: Face to Maw 1B" during Cognizance

- data/remnant/remnant missions.txt
**Bugfix:** This PR addresses issues reported on Discord
In Remnant: Void Sprite 2 there is a missing comma.
In the event for pantica void sprites, the code that adds the spaceport description includes an indent, but the spaceport text is used by itself in game, so there shouldn't be an indent there.
These two errors spotted by @TheMarksman-ES and reported on Discord.
> Fix: Two Punctuation errors in VS 2 and event: pantica void sprites

- data/map.txt
From `around each other in a helical patterns` to `around each other in a helical pattern`.
> Fix Typo in Follower's Spaceport Description

- data/korath/korath outfits.txt
This PR specifies that more bunks are needed for the Command Center on a ship with turrets, removing the confusion found in #6016.
> Clarify Command Center Description

- data/persons.txt
MZ's Finches had their definitions indented one layer too deep, which may have caused them to be able to be disabled.
> Fix indentation in MZ's Finches

- changelog
- data/intro missions.txt
**Bugfix:** This PR addresses issue #5917 and #6029 
Fixes #5917 
Fixes #6029 
- Changes the Freighter intro to also trigger if the player is flying a Heavy Freighter
- Changes the interceptor intro to also trigger if the player is flying a Fighter, Light Warship, Medium Warship, or Heavy Warship
Literally start a new pilot.
> Fix: Prevents James from running away if the player isn't flying a standard starter ship

- data/help.txt
Missing "ing" from the third example in this tutorial.
> Fixed trading tutorial typo

- changelog
- credits.txt
- data/korath/korath missions.txt
Fixed one small typo in the on complete conversation text of the "Setar Fort Heating" mission.
> fix(typo): Fix typo in Setar Fort Heating mission

- data/human/news.txt
**Bugfix:**
As per https://github.com/endless-sky/endless-sky/pull/5755#discussion_r646040671, we use traveller with one L. This is the last instance of the word spelled with two L.
> fix: Traveller -> Traveller

- data/coalition/coalition missions.txt
**Fix (Missions)**
Hadn't realized instances in the rest of the game had the cargo fully in lowercase, this is to make it consistent with everything else.
> Uncapitalize cargo instances in Coalition missions

- data/help.txt
**Bugfix:** This PR addresses issue #6054
`vasty` -> `vast`
/
/
lol indeed
> fix(typo): clarify "vasty" in help "lost 7" is not a typo

- data/remnant/remnant missions.txt
**Bugfix:** This PR addresses:
- Reported bugs on Discord about Astral missions requiring the player to go to Esquiline to pick up the research lab, when the later won't fit on a puffin. 
- Adjusts the "on complete" text for Cognizance 19 to more accurately reflect the nature of the mission. (the Remnant don't need the player's navigational log, they need the *additional data from* their navigational log.)
- Adds an exclusion to Astral 1 & 2 that prevents the destination from being selected as a planet requiring gaslining.
> Fix: Remnant Gaslined planet mission eligibility & Cog 19 on complete text tweak

- changelog
- source/ShipInfoDisplay.cpp
**Bugfix:** This PR addresses issue #6077.
Renamed emptyMass to baseMass in ShipInfoDisplay, as baseMass is a more accurate description of what Ship::Mass returns. Then, if in flight, fullMass is now equal to baseMass, as baseMass already accounts for cargo space used.
Tested the same scenarios as shown in #6077 (half cargo used and full cargo used) and observed results that are accurate with what is shown when landed.
N/A
> Don't count cargo mass twice while in flight in ShipInfoDisplay

- data/human/events.txt
One thing that struck me odd during the Pug invasion was the fact that, even after the Pug supposedly left, Pugglemug still responds to your hails, Pugglequat requires you to pay to land, and both planets have a functioning bank.
This PR makes it so that, when the pug flee, their planets become briefly uninhabited, until complete Pug liberation occurs.
Tested during FWC Pug invasion. Testing might need to be done on FWR.
Go to Silver, then go to Deneb to see the changes.
[combat testless~~previous-3.txt](https://github.com/endless-sky/endless-sky/files/6133897/combat.testless.previous-3.txt)
> Make Pug planets briefly uninhabited after they flee

- data/human/news.txt
I added three more news lines that are about merchants that have experienced Korath attacks in the Core. It seems odd to me that there's almost no hint that massive alien warships occasionally raid humanity, so I added these. Of course the Syndicate tries to keep it quiet, but you'd expect some stuff to slip through the cracks.
> Add news that hints at Korath attacks

- data/wanderer/wanderers start.txt
**Content (Mission)**
Currently, the player can destroy or capture one or both Arfectas spawned by "Wanderers Ap'arak 3: Pug". Despite this being a terrible act to the Wanderers, due to the way the mission is structure, you can only be penalized if you land on the planet where the mission is spawned, which is out of the way and only has one required landing in the rest of the Wanderers campaign.
From a suggestion from @beccabunny, this PR restructures that mission into two `npc save` missions. Upon both being failed, a third mission will be prompted on landing anywhere in Wanderer space, giving you the reputation hit and kicking you out. This is backwards-compatible with current saves, requiring both missions to be failed, and the second mission only activating if you haven't done the …
> fix(content): Bar off Wanderer space landing anywhere after killing Arfectas

- data/wanderer/wanderers middle.txt
- data/wanderer/wanderers.txt
This PR adds a basic mission to Spera Anatrusk, acting as a breadcrumb to alert the player that they'll need to wait until the colony is fully developed. It also changes the Kaliptari system over to the Wanderer government in `the eye opens` event, so that planet attracts player attention on jumping in. Many players have been confused with the end of Wanderers Act 1, going through the Eye but not knowing what to do. With this mission, it should keep the players on the hook while still letting the break naturally happen.
Rather than a simple landing dialog, should this mission keep a marker on Spera Anatrusk, becoming "completable" once the event is done and the colony is ready? It would act as a reminder of where the player needs to return to, but might give a bit …
> feat(content): Added post-Eye breadcrumb mission

- data/hazards.txt
- source/Engine.cpp
- source/Ship.cpp
- source/Ship.h
- source/Weapon.cpp
- source/Weapon.h
**Feature:** This PR replaces the "hit effect" keyword for hazards by "target effect" as discussed in #5751
This is just the rename to differentiate between "hit effect" (effect at point of impact, for projectile weapons) and "target effect" (as effects over a ship shape, for hazards) and some changes to make the hazard-weapon-terminology more in line with the projectile-weapon-terminilogy.
There are a number of other improvements being discussed in #5751, but the discussion was just started so I want to give a bit more time to discuss before creating other improvements.
N/A (only the keyword changed)
See `data/hazards.txt` for the replaced keyword.
Flown to Sagittarius A* and got my ship destroyed there in a cloud of nano particles.
None expected.
> Rename "hit effect" for hazards to "target effect".

- source/Planet.cpp
- source/Politics.cpp
**Bugfix:** This PR addresses an issue with demanding tribute affecting reputation with governments.
A while ago, demanding tribute from a planet was changed to be considered an atrocity. 7675eb7
It has been noted though that since then, demanding tribute from a pirate planet will lower your reputation with the Republic, despite the fact that the Republic has a negative attitude toward pirates. 
As it turns out, committing an atrocity is currently causing your reputation to drop to 0 for *all* governments that have an attitude toward the government you committed an atrocity against, whether that be a positive or negative attitude.
This PR changes it so that atrocities only drop your reputation to 0 with governments that are friendly toward the government you committed an atrocity against. …
> Only lower reputation due to atrocities if governments are friendly

- source/MissionAction.cpp
- source/MissionAction.h
**Feature:** This PR implements the **fines** part of the feature requested and discussed in issue https://github.com/endless-sky/endless-sky/issues/1216
This PR adds a keyword `fine` that can be used in `on accept`, `on complete`, `on <...>` mission actions.
Attached is a data-file [fines.txt](https://github.com/endless-sky/endless-sky/files/6728590/fines.txt) with 4 missions that can be used to test this feature (the missions are quite silent).
This PR only implements the `fine` keyword, it doesn't implement keywords to add a customized mortgage. I consider it an implementation detail that fines are handled as mortgages, so I consider it appropriate to use a separate keywords for fines and for mortgages (the implementation in https://github.com/endless-sky/endless-sky/pull/5073, minus …
> feat: Fines in mission actions

- source/AI.cpp
- source/Engine.cpp
- source/Flotsam.cpp
- source/Flotsam.h
- source/Ship.cpp
- source/Ship.h
- source/ShipInfoPanel.cpp
**Feature:** This PR implements a feature to improve the appeasing/flotsam dump behavior
This PR let's ship ignore (not pickup) flotsam that was explicitly dumped by other ships of their own government.
Only explicit dumps (for example to appease pirates) are ignored; ships still pickup flotsam from same-gov ships that explode.
Explicit dumps are triggered in AI.cpp (for NPCs) and in ShipInfoPanel (by the player).
Related to https://github.com/endless-sky/endless-sky/issues/4100 since this PR removes the long-life flotsam option as mentioned in that PR.
N/A
Player playing as a pirate: intimidate merchants and notice that the flotsam that they dump doesn't get collected by other merchants.
Player playing as merchant: dump cargo and notice that your escorts don't pick it up.
Attached is a …
> feat: Ignore flotsam that was explicitly dumped by same government

- data/remnant/remnant news.txt
It bothered me a little on my recent playthrough that after going to all the trouble of learning Remnant sign language well enough for complex mission-related conversations, I was still unable to understand random people in spaceports. This PR makes the `remnant incomprehensible` news block conditional on not having learned to sign and adds a `remnant comprehensible` news block (conditional on having learned to sign) that makes the formerly-incomprehensible chatter somewhat more comprehensible.
This isn't particularly imaginative, but it fixes a minor continuity issue and can serve as a starting point for further improvements to Remnant news. I considered having several variants that became progressively more comprehensible through the "learn sign" …
> Make some Remnant news comprehensible after completing sign studies

- data/human/sales.txt
**Content Balance (ship data)**
@petervdmeer [commented](https://github.com/endless-sky/endless-sky/pull/5949#issuecomment-870963463) on #5949 that because #5969 has yet to be merged (and will not be merged for 0.9.14) that the lack of stat differences between the BF and CT currently in master might be confusing.  This PR removes the CT from sales.txt.  Determined players may still cap the container version if they desire.
> temporarily remove CT from sales to avoid confusion

- changelog
- source/Ship.cpp
**Feature:** This PR reduces message log spam from ships with not enough crew.
The `<ship> is moving erratically because you do not have enough crew to pilot it.` messages have been marked as unimportant, so they will not redisplay at the bottom of the screen until they are cleared from the message queue - that is, after about 17 seconds, or sooner if there are many messages from other sources coming in.
~~In practise, a message from a severely shorthanded vessel will still be shown at almost all times, but~~  <- This is what I expected, but ES is bit lazy about cleaning the queue.  Rather, if you are in a quiet area of space you might not see any messages at all until a different messages is triggered, then you'll get the crew message(s).
As expected, however, it will not compete with …
> Don't spam "does not have enough crew" message until it clears the queue.

- credits.txt
- data/sheragi/sheragi ships.txt
This pull request adds an emerald swizzle to the Emerald Sword. When I play, after getting the Emerald Sword through the mission string, I am always disappointed at the colors changing to my current swizzle. I often simply go into the save file and change it, but it becomes a pain to constantly have to change the pilot file. This pull request makes it so that the ship will permanently have the original Sheragi swizzle.
This save file can be used to easily view the change:
[emeraldsword swizzletest.txt](https://github.com/endless-sky/endless-sky/files/6758993/emeraldsword.swizzletest.txt)
- [N/A] I uploaded the necessary image, blend, and texture assets here: {{insert link to assets}}
- [N/A] I created a PR to the [endless-sky-high-dpi …
> Swizzle the Emerald Sword (And Black Diamond)

- source/Engine.cpp
- source/Ship.cpp
- source/Ship.h
**Feature:** This PR implements the second part of the feature request detailed and discussed in issue #5751
This PR makes the `"target effect"` as discussed in #5751 also available for weapons (it was previously only available for hazards).
This PR also unifies the `Ship::TakeDamage()` function to a single function, but hazards don't make use of projectiles, so projectile-bound effects will still not be available for hazards.
I didn't include any provisions in this PR for the effect emitters [as discussed in 5751](https://github.com/endless-sky/endless-sky/issues/5751#issuecomment-787093802). This PR only removes some differences between hazards and weapons.
N/A
The `"target effect"` keyword should now also work for regular weapons (giving the same effect as for hazards).
Added "target …
> feat: Unify weapons and hazards Ship::TakeDamage() function

- data/coalition/coalition outfits.txt
**Fix (Outfit Licensing)**
The Large Cogeneration Module's license definition wasn't in the right format, this just sets it so that it'll require the license to purchase it.
Issue brought up by Amacita on the discord server.
> Fix licensing for the Large Cogeneration Module.

- source/PlayerInfoPanel.cpp
This PR adds a playtime tracker to the Player Info Panel in-game, which counts up in real-time. This lets a player observe or screenshot their progress as a pilot (net worth, fleet size, licenses, etc.), and see how long it has taken them to accomplish that.
Verified nothing anomalous happened when the time ticks over to add new units (minutes, hours, days).
N/A
> feat(UI): Add playtime tracker to Player Info Panel

- source/ConversationPanel.cpp
**Bugfix:** This PR addresses an issue with attempting to open the map while at the end of a conversation.
The map is typically capable of being opened by the player while in the middle of a conversation, except in two scenarios:
1. The conversation is currently at a name entry field.
2. The conversation is at its end.
Judging by a comment in ConversationPanel.cpp, only the former scenario is intended to block the player from opening the map. As such, this PR changes it so that the map is allowed to be opened while at the end of a conversation.
Attempted to open the map at the end of a conversation with and without this change. With this change, the map is able to be opened, while without it the map can't be opened.
Tested that the behavior of pressing `m` while at a name entry field is …
> Allow the map to be opened when at the end of a conversation

- data/persons.txt
- source/Armament.cpp
- source/Armament.h
- source/Engine.cpp
- source/Hardpoint.cpp
- source/Hardpoint.h
- source/Ship.cpp
**Feature:** This PR implements a feature described in #6062.
This PR makes it so that any gun hardpoint with a hardpoint sprite will now have the sprite rendered under the ship (by default). Previously, all hardpoint sprites were rendered on top of the ship. While this makes sense for turret hardpoints, which hardpoint sprites were designed for, this doesn't make as much sense if you wanted a gun hardpoint sprite, which is not disallowed from being done.
~~In the future it may be that we allow any hardpoint sprite to arbitrarily be drawn above or below the ship regardless of hardpoint type, but I chose to just draw all gun hardpoint sprites under the ship for the sake of simplicity; all we need right now are gun hardpoints drawn under ships, and allowing turret hardpoints under the ship …
> Draw any gun hardpoints under the ship (by default)

- source/AI.cpp
- source/Engine.cpp
- source/PlayerInfo.cpp
- source/PlayerInfo.h
**Feature:** This PR implements a feature related to this [comment](https://github.com/endless-sky/endless-sky/issues/1724#issuecomment-254778984)
This PR adds an "all secondary weapons selected" option after the currently available "no secondary weapon selected" and "single secondary weapon selected" options.
The internal implementation uses a set which will also be suitable for the "mouse selectable set of options" as discussed in https://github.com/endless-sky/endless-sky/issues/1724.
Screenshot of all weapons selected:
Just cycle through the list of available secondary weapons and notice that the new all-weapons-selected option is now also available at the end of the list.
Tested with firing all secondary weapons (on a ship with 3 separate secondary weapons installed).
Tested with …
> feat: Add ability to fire all secondary weapons

- source/PlayerInfoPanel.cpp
This PR expands the combat rating section in the Player Info Panel. Since the start, combat rating on the game's end is a number, usually in the thousands when a player has fought enough, which is tracked as a condition for various missions or tribute. This is surfaced to the player, also as "Combat Rating", but as the log of the internal number. This results in a drastically different value than what is expected for missions, leading to lots of confusion when a guide says combat rating of 15 is required, and they go "Oh no, but I only have 3!", when they meet the requirement just fine.
With help from Derpy, this breaks down the terminology to the player more, and surfaces the internal tracking number:
- Combat Rank: The currently surfaced Combat Rating
- Combat Title: The string …
> feat(UI): Provide more detail/terminology for combat rating

- source/PlayerInfoPanel.cpp
Some later combat rating titles are very long, and caused the new UI to overflow. This PR drops the parenthesis, which makes the longest title/number combination fit.
> fix(UI): Adjusted combat rank text to not overflow

- data/hai/hai missions.txt
- data/sheragi/archaeology missions.txt
Changes to two different conversations relating to the Deep Archaeology missions.
The first is the conversation with Albert Foster when he brings up the Pug in folk tales. If the player managed to play through enough of the FW campaign, they would know of the Pug and as such be able to respond with that knowledge.
The second conversation is with the first contact of the Unfettered Hai where the player may know of the Sheragi due to the Deep Archaeology and as such be able to respond with that knowledge.
It's not an incredibly major change, though for the sake of consistency the player should be able to say this information if they do know about it. One aspect that I considered but could not solve is of the `log` that is entered at the end of the Unfettered Hai …
> Dialogue changes about Deep Archaeology due to player's knowledge

- source/MissionPanel.cpp
- source/MissionPanel.h
**Bugfix:** This PR addresses issue causes an undefined behavior in Job Board.
It's undefined behavior to compare iterators that refer to elements of different containers. (§ 24.2.5 [forward.iterators#2])
The debug library on GCC (activated by -D_GLIBCXX_DEBUG) aborts the program when you enter Job Board from the planet panel.
This PR makes the function receive a parameter for the comparison.
I added option -D_GLIBCXX_DEBUG, and entered the Job Board.
> Fix a bug where causes an undefined behavior.

- source/AI.cpp
- source/Engine.cpp
- source/HailPanel.cpp
- source/MainPanel.cpp
- source/Messages.cpp
- source/Messages.h
- source/Mission.cpp
- source/MissionAction.cpp
- source/NPC.cpp
- source/PlayerInfo.cpp
- source/Ship.cpp
- source/ShipInfoPanel.cpp
- source/TradingPanel.cpp
Changed the second argument to Messages::Add from an optional bool called isImportant that defaulted to _true_ to being a required enum class with two options, Low, which maps to what was previously 'false', and High, which maps to what the default case was. Whilst the interface now effectively allows the addition of new importance levels in future, the underlying data type in the implementation is still a bool. No changes were made to the behavior of the code; the ONLY difference is that it is now explicit in the code, to force authors to make a more conscious decision on whether their message should be considered High importance or Low. Future work, IF ANY, could entail revisiting the Importance::High cases (which is almost every case), or adding additional importance levels, or adding …
> refactor(internal): Force authors to consciously decide the importance level of a Message

- data/remnant/remnant missions.txt
**Bugfix:** This PR addresses a spelling issue reported by Johnnydevo on the discord.
Spelling fix: Remnant: Keystone Research 1 "into" -> "in to"
Thanks to Johnnydevo on the discord for reporting this.
> Fix: Spelling "into" to "in to" in Remnant Keystone Research 1

- source/Mission.cpp
**Bugfix:** This PR addresses issue with the destination of invisible missions being able to be known by opening the map during an invisible mission's on offer conversation.
It is currently permissible for invisible missions to have on offer conversations. During an on offer conversation, the player is capable of opening the map and viewing a special marker placed at the mission's destination. This marker is created regardless of the visibility of the mission. Invisible missions otherwise don't create map markers of any kind, and the special map marker should be no different.
This PR makes it so that invisible missions do not pass the destination system to any MissionActions, which normally pass the destination to any created Dialogs or ConversationPanels, which only use the destination …
> Don't leak the destination of invisible missions from the special marker

- data/tooltips.txt
- source/Ship.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #4851, #3448.
Changes the calculation of a ship's default minimum hull from a mix of 15%, 45%, and 10/sqrt(hull amount), to a continuous curve moving from 75% to 10% roughly over the spectrum of human ship values. A table to give a rough feel for the change (it is not a very large change in actuality)
100 hull = 69.1 minimum
200 hull = 128.3 minimum
300 hull = 180 minimum
400 hull = 225.7 minimum
500 hull = 266.7 minimum
625 hull = 312.5 minimum (the 50% mark)
1000 hull = 425 minimum
1500 hull = 540 minimum
2000 hull = 633.3 minimum
3000 hull = 787.5 minimum
3333.3 hull = 833.3 minimum (the 25% mark)
4000 hull = 920 minimum
5000 hull = 1041.7 minimum
10000 hull = 1590.1 minimum
25000 hull = 3125 minimum …
> Change Default MinimumHull Formula

- source/PlayerInfo.cpp
**Feature:** #236 is related
<del>This is a pretty simple change: Sort the "available jobs" by payment. The jobs with the smallest payments are at the top while the job with the highest payment is at the very bottom.</del>
After feedback, this PR sorts the list alphabetically.
<hr>
<details>
<summary>Background information</summary>
Sorting jobs by payment/type/distance/... is requested lots of times (see #236). Yesterday I bought some good cargo/transport ships and did lots of jobs. It was pretty annoying to go through the whole list and find out which job paid the most.
This PR defaults jobs by payment and only that. I really don't think all the other sorts make any sense:
- By Cargo Space: cargo space is pretty much proportional to payment, so sorting by payment also sorts by cargo …
> Sort available jobs alphabetically.

- source/ShopPanel.cpp
**Bugfix:** This PR fixes #5966
The wrong sign was used when calculating the amount of scroll to apply when nothing is selected and the Up key is pressed. This resulted in way too much scroll - the last entry moved to the very top of the screen and then in the next frame got immediately moved back down - which caused the flickering.
Verified that the scenario in the issues is fixed and that this didn't introduce any other bugs.
> Fix flickering in the shop panel when going up with nothing selected.

- source/SpriteShader.cpp
**Bugfix:** This PR addresses issue https://github.com/emscripten-core/emscripten/issues/14079
The swizzler variable is currently modified after clearing the current program, which seems wrong: [the docs](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glUniform.xml) for glUniform1i say
> Specify the value of a uniform variable for the current program object
from which I gather there ought to still be a current program object, so this PR moves `glUseProgram(0);` to after this call.
I noticed because a change in the way Emscripten handler shaders caused this code to crash: https://github.com/emscripten-core/emscripten/issues/14079
I don't know on which other platforms this might be a problem. I just moved `glBindVertexArray(0)` to keep it next to `glUseProgram(0)`.
Works on …
> Reset swizzle before glUseProgram(0).

- data/wanderer/wanderer outfits.txt
Turns out that the energy generation on this is 1488, which paired with "white sun" is fairly sketch. This is a very minor tweak that makes the reactor not-Hitlery.
This changes the regen/sec from 1488 to 1485.
> Remove accidental white supremacy from White Sun

- data/wanderer/wanderer news.txt
**Bugfix:** This PR addresses issue in wanderer news.
Add a missing "word" keyword in wanderer news.
Print the news.
> Add a missing "word" in wanderer news.

- source/ImageBuffer.cpp
- source/Sprite.cpp
- source/text/Font.cpp
Alternative to https://github.com/endless-sky/endless-sky/pull/5153 at @petervdmeer's suggestion: let's just use RBGA everywhere! Unlike that PR, this does not eliminate the need for libjpeg-turbo.
> feat: Use RGBA texures instead of BGRA for better portability

- .github/workflows/ci.yml
- SConstruct
- source/BatchShader.cpp
- source/FillShader.cpp
- source/FogShader.cpp
- source/GameWindow.cpp
- source/LineShader.cpp
- source/OutlineShader.cpp
- source/PointerShader.cpp
- source/RingShader.cpp
- source/Shader.cpp
- source/SpriteShader.cpp
- source/StarField.cpp
- source/gl_header.h
- source/text/Font.cpp
Adds support for OpenGL ES, a variant of OpenGL targeting embedded systems. The new build flag `opengl` defaults to `desktop` but can be set to `gles` to target these systems. This PR makes shader code acceptable to both OpenGL 3.0 and OpenGL ES 3.0.
Support for OpenGL ES would be useful for targeting Raspberry PIs, mobile devices like iOS or Android, and WebGL. I'm interested in it because it enables an Emscripten build for the web.
I tested on an ubuntu18 vm with
~~~
scons opengl=gles
MESA_GLES_VERSION_OVERRIDE=3.0 ./endless-sky
~~~
This version check can probably be cheated with MESA_GLES_VERSION_OVERRIDE on any machine that runs the desktop build on Endless Sky because the only OpenGL ES 3.0 features used are those already supported by OpenGL 3.0. (full OpenGL ES 3.0 support is …
> OpenGL ES support

- source/Projectile.cpp
- source/Projectile.h
- source/Weapon.cpp
- source/Weapon.h
**Feature:** This PR implements the feature request detailed and discussed in issues #5376 and #3878
Closes #5376
Closes #3878
This PR adds an offset and an angle for the submunitions as requested in the 2 linked issues. The newly introduced keywords in this PR are `facing` (to select the angle for the submunition) and `offset` (to set the offset compared to the explosion location) which both are to be used under the `submunition` keyword in the datafiles that describe submunitions.
Chosen implementation is to set the facing and offset keywords in the submunition sections on the "parent-projectile" to allow the same "submunition" to be used on different angles and offsets from a parent projectile (without each angle or offset requiring its own definition).
Attached is …
> feat: Add offset and facing angle to submunitions

- data/human/transport missions.txt
**Bugfix:** This PR addresses issue #6146 (with a workaround)
Remove moons as suitable destinations for spacediving missions, to reduce the chance that spacedivers dive at locations that have no atmosphere. This doesn't fix the issue completely, but filters out a large set of unsuitable destinations.
The proper future solution seems to be to add attributes to planets that describe in more detail which planets have which properties (like atmosphere, landmass, oceans, volcanos, etc) and then filter on the right attributes.
The PR system will perform all parsing tests required for this change.
N/A
> content/bugfix: Filter out all moons for spacediving.

- source/Ship.cpp
**Bugfix:** This PR fixes #5936 
When `Place`ing a `Ship` (which happens when departing from a planet) the ship swizzle is updated. This fix updates any carried ships' swizzle too.
Tested the save file below.
This save file is adapted from the save file from the linked issue.
[tommaso.becca.txt](https://github.com/endless-sky/endless-sky/files/6839453/tommaso.becca.txt)
> Apply swizzle when departing to any carried ships too.

- source/Ship.cpp
**Bugfix:** This PR addresses the issue I posted in the Bug-Reporting discord channel
DragAcceleration formula updated to correctly treat drag as an acceleration in the same units.
The error size is small (~1.65%) but compounds to create significant problems when being used for predictive things such as stopping distances with reverse thrust.
See the excel sheet posted in bug-reporting for the full math explanation.
Nil - fix arose from testing and finding weird behaviour in related maths
Nil
> Fix dragAcceleration formula

- source/Ship.cpp
Reverts endless-sky/endless-sky#5776
This change has scaled ship  top speeds by 1/60. Issue was noted 9th March on the original PR and now reported on Discord and issue #6166
> Revert "Fix dragAcceleration formula"

- source/text/Format.cpp
- tests/src/text/test_format.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #{{insert number}}
Allow the player to enter mortgage payment numbers that include commas, like 1,000,000.
N/A
Tested a payment of 10,000 in the game.
N/A - parse code is only ever called on manually-entered user input.
> Allow commas in player-entered bank payments.

- EndlessSky.cbp
- EndlessSkyTests.cbp
**Bugfix:** This PR addresses a minor known issue where CodeBlocks on Windows gets a linker error because it can't find the uuid implementation.
This bugfix updates the CodeBlocks config by telling it to link with rpcrt4, which provides the Windows equivalent of libuuid.a.
With the patch, I can now build the project in CodeBlocks on Windows.
N/A
> Added Windows uuid library to CodeBlocks

- data/persons.txt
**Bugfix:** This PR addresses a typo in Brick's person ship description. Thank you to Mr Doom on the discord for pointing this out.
In the description, `into a palatial sarcophogus.` should be `into a palatial sarcophagus.`.
lol i changed one letter
Any save file works.
> Fix Brick's person ship's description typo

- source/text/Format.cpp
- tests/src/text/test_format.cpp
**Bugfix:** This PR fixes #6173.
This PR causes Format::Capitalize() to only set the bool to capitalize a character when it matches a space, rather than any alphabet letter. The only non-letter characters in commodities.txt are hyphens, apostrophes, and the number 3 for 3D printers. This fixes any issues with apostrophes.
By setting it to not capitalize after hyphens, there is a slight issue in terms of fully-hyphenated words, where we get High-performance Automobiles instead of High-Performance Automobiles. However, this leaves us with more proper De-ionizers or By-products, which seems preferable to the other hyphenated words.
Accepting missions with non-alphabet characters, and observing proper capitalization on them.
[asdf asdf.txt](https://github.com/endless-sky/endless-sky/files/6952 …
> fix(ui): Capitalize words after whitespace in cargo strings

- data/human/fleets.txt
**Bugfix:** I haven't seen this in the issues list.
Merchant ships in Deep space have been popping up with names from the Deep Security list instead of the merchant list.  I edited fleets.txt to prevent this.
I flew around the Deep looking at ship names.  Nothing out of the ordinary popped up in terms of either names or ships.
[Deep Merchant.txt](https://github.com/endless-sky/endless-sky/files/6959214/Deep.Merchant.txt)
> Fixed Deep merchant fleets using D.S.S. names

- data/human/transport missions.txt
Shortened the texts around skydiving as suggested in #6179, because the textbox was overflowing with the texts currently in the game.
Fixes #6179
N/A
N/A
> fix(ui,content): Shorten spacediving job descriptions to avoid overflow in the Missions panel

- .github/path-filters.yml
- .github/workflows/cd.yaml
- .github/workflows/cd_release.yaml
- .github/workflows/ci.yml
- readme-developer.txt
- utils/fetch_sdl2_framework.sh
**Build process:** This PR automates the upload of macOS release builds.
- Adds a job to `cd_release.yaml` which adds the Mac build when a release is published
- Also:
- renames the macOS CD build to omit the minimum version, since it now runs on 10.9 and later
- fixes an issue from #6121 where building with Xcode wouldn't find SDL2.framework unless a command line build using `xcodebuild -configuration "Release"` was run first
- updates macOS section in `readme-developer.txt`
Works On My Machine™ (macOS 10.12, 10.14, 10.15)
> Mac: automate upload of release builds

- data/human/weapons.txt
Every missile pod except the two mentioned above have burst counts equal to their ammo capacity.
> Make burst counts of Torpedo and Typhoon Pods equal their ammo capacity

- data/human/events.txt
This PR adds two new Poisonwood spaceport descriptions, with one for teaming up with the Oathkeepers and one for when your karma is too low. These descriptions reflect the events that occur in each path.
> Make Poisonwood's spaceport change in response to the path taken during FW Alphas

- data/coalition/coalition ships.txt
**(Balance)**
It is odd that the Coalition, a group that's been independent and at peace for six thousand years, and which the player can only access once they have a Jump Drive, produces freighters and transports with little advantage over their human counterparts other than slightly more HP, it so I tried my hand at buffing them.
The ship that bugged me the most was the Arach Hulk, the largest freighter in the Coalition, having less cargo space than the Bulk Freighter. I'm not discounting HP as an advantage, but I don't think anyone buys freighters primarily for how much damage they can take.
The buffs are the following:
- Saryd Light Freighters got a 10% increase to bunks and cargo space.
- Saryd Heavy Freighters got a 20% increase to bunks and cargo space.
- All …
> refactor(content): Buff civilian Coalition ships

- source/Engine.cpp
This PR sets the raid alert message's importance to Highest, highlighting it orange along with the mission failure or hyperspace alerts. The Raid Warning tutorial mission is still important for specifically laying out why it happens, but now that we have the capability to highlight messages, this seems like one of the more important ones.
> feat(UI): Highlight raid alert message

- data/coalition/coalition missions.txt
It seemed strange to me that as the player travels through Coalition space, few NPCs show much interest towards the player and their knowledge of the broader galaxy. I thought that there would probably be at least some Coalition citizens who would want to hear about the player's adventures and learn more about humanity. This mission has the player invited to a xenology seminar at Starlit University, where they have the option of telling the attendees about humanity and the galaxy as a whole. 
I realize that this may have broader implications for future storylines/missions involving the Coalition, so I avoided talking about the Quarg and Pug. Even so, if this seems too radical of an idea, then please say so.
I'm awful at making mission syntax work, …
> Adds a mission where the player is invited to a Coalition university seminar

- source/BoardingPanel.cpp
**Feature:** This PR implements the feature request detailed and discussed in ~~issue #{{insert number}}~~ this PR
In the plunder dialog, show commodities as `<count> x 1` rather than as `<count>`.
Why? Because otherwise, when scanning the "size" column, outfits and commodities are both listed as `<a single integer>`, even though commodities are divisible and outfits aren't. That is, before this PR, `Hyperdrive | 20` and `Luxury Goods | 20` could appear, even though a ship with 10 free cargo space could use the latter but not the former. (In the latter, `<mass> = 1` and `<count> = 20`; in the former, the `<count> = 1` and `<mass> = 20`.)
The `x 1` part is new.
N/A
Created a test mission with a `derelict` Carrier and boarded it.
N/A
Kinda related to the texty (fourth) mockup in …
> Boarding: Give <count> x <mass> even if <mass> is 1

- source/MapSalesPanel.cpp
**Bugfix:** This PR addresses issue derived from #5941.
In the Map Outfitter Panel, the texts are not centered in the height direction when you store some outfits in a planet.
> Correct a height offset of a text in the Map Outfitter Panel.

- data/tests/tests_wormhole_navigation.txt
**Feature:** This PR test both the navigation code and the time conditions
This PR adds time information to the navigation test to verify that the steps take the amount of time that was expected.
This PR also tests the time conditions code itself (which is useful if we move the time conditions to derived automatic conditions as is done in #5244).
N/A
Just run the test.
Just ran the test (in combination with the code from #5244).
N/A (doesn't take a lot of additional test-time either)
> test: Add time information to Ember Wastes Navigation test

- source/ShopPanel.cpp
**Feature:** This PR implements a suggestion from fluzzlemash on the Steam forums.
Currently, using the arrow keys in the shop will only navigate between shop items, unless you manually click on the side panel to change focus over there. This PR sets a keybind (in this case, Tab) to change the focus, letting you access that part of the shop with only a keyboard.
Tab was chosen as it is often used to swap between different forms in an interface, but I am open to other keys like space, or even a letter if it makes sense.
A future PR might make a visual distinction between which panel currently has focus, but in the meantime, this would offer some very useful commands to a power user, such as Tab+Shift+Up to select every ship on the planet.
Navigated between both side panels with items …
> feat(UX): Swap between main and side panel in shop with keybind

- data/human/weapons.txt
**Bugfix:** This PR addresses issue #6215 
fixes #6215 
Reload 50 to Reload 252 (this brings the typhoon in line with all other launcher to pod comparisons, wherein the full reload is equal to somewhere between 2.1 and 3 times the launcher reload.
Checked in game values to see that typhoon pod has changed from significantly faster shots per second than its launcher to below it.
> Fix: eroneous Typhoon Pod Reload value

- source/main.cpp
**Bugfix:** This PR addresses an issue with the game speed when integration-testing in debug mode
The integration testing framework was never waiting for the timer.Wait() in main.cpp, even when debugMode was set. This code
changes this to ensure that the framework does wait for the timer when debugging.
Executed the tests in the framework with debugMode enabled and noticed that the game was running at normal speed.
N/A
> test: Normal gamespeed when integration-testing in debug mode.

- source/Audio.cpp
- source/Audio.h
- source/GameData.cpp
- source/SpriteSet.cpp
- source/SpriteSet.h
**Feature:** This PR implements the feature request briefly mentioned on the discord.
This PR adds a warning if any unknown sounds (so sounds that don't exist on the file system) are used. Previously there was no warning. The warning added:
```
Warning: sound "blasterbb" is referred to, but does not exist.
```
Added invalid sounds in plugins and in the data files and verified that the warning is emitted.
Loops through every sound once when the game is loaded. Unlikely that this is going to have a big impact when starting the game.
> Add warning if unknown sounds are used.

- source/Angle.cpp
- source/Angle.h
This PR adds `noexcept` to `Angle`'s constructors (only the default constructor is needed but I added it to the others as well). This is needed to fix a compilation error on older versions of gcc and clang. 
What happened is that the behavior of explicitly defaulted constructors with different exceptions specifications (see `Weapon::Submunition` which has a defaulted `noexcept` constructor while its data member `Angle` doesn't) changed via a defect report. Before: compiler error. After: valid code.
This defect report came several years after C++11 was released and as such older compilers that support C++11 but were released before this change in behavior miscompile the code.
> Add noexcept to Angle's constructors.

- EndlessSky.xcodeproj/project.pbxproj
**Bugfix:** This PR addresses issue discussed in Discord where @vitalchip found naming an Xcode checkout of Endless Sky made building fail.
Add more quotes, that's always the solution!
There's an intermediate step where Xcode copies the script to a file with a name like `/Users/tomb/Library/Developer/Xcode/DerivedData/EndlessSky-fntizoreowhxxyetwmpsmmjusmaf/Build/Intermediates.noindex/EndlessSky.build/Debug/SDL2.build/Script-072599CB26A8C7AB007EC229.sh` that looks like this now:
```
#!/bin/sh
"${SRCROOT}/utils/fetch_sdl2_framework.sh"
```
but didn't have quotes before this change.
Ran `git clone git@github.com:thomasballinger/endless-sky.git "i hate spaces"`, switched to this branch, opened Xcode and hit the play button on 11.5.1, Xcode 12.5.1
> Allow spaces in project path in Xcode

- source/Fleet.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #6097
As said in the original issue, missions in Endless Sky have a lot of power to provide interesting situations while boarding disabled ships. However, this is limited only to naturally spawned ships, which were either disabled by yourself or an enemy of theirs.
This PR lets naturally spawned fleets make use of the `derelict` personality. If a ship from that fleet spawns as the player enters from/takes off into that system, it will be disabled and stationary. Then, no other ships from that fleet will be allowed to jump in.
Content creators can then have events which add a derelict fleet to a given system, of a specific government type that are the only ones eligible for specific boarding missions. We …
> feat(mechanics): Allow fleets to spawn derelicts

- data/dialog phrases.txt
- data/human/pirate jobs.txt
This PR corrects several issues with the Pirate smuggling missions:
1. The mission descriptions listed the amount of the fine, allowing
players to precisely calculate whether the mission could be worth it.
2. The fine amounts were much too low, often being less than the
payment! This the player could get caught and fined and still earn a
profit.
3. Being fined did not fail the mission! There is no possible universe
in which the police fine you for possession of illegal goods but
don't confiscate the goods. It just makes no sense.
4. The payments were too low given the risk entailed (if you're on the
side of the pirates) or the sunk costs involved (if you had to bribe
your way onto the planet), especially now that being fined fails the
mission, and *especially* for the slave smuggling …
> fix(content) Overhaul illegal good, drug, and slave missions

- data/remnant/remnant missions.txt
One of the two Dredger bounty mission from #5841 has a requirement of a failed Cognizance mission, which seems to be impossible. This changes the condition to `done` instead, making it appear.
> fix(content): Set Dredger bounty requirement to done instead of failed

- source/GameData.cpp
**Bugfix:** This PR addresses an issue that I randomly found out.
I was looking at `GameData::CheckReferences` a bit and then realized that hazards aren't checked. So, this PR adds the following warning when an undefined hazard is used:
```
Warning: hazard "test" is referred to, but not fully defined.
```
Added an undefined hazard and confirmed that the warning is emitted.
> Add warning when undefined hazards are used.

- source/Ship.cpp
(You can open a PR to add or improve a section, if you find them lacking!) 
Current code does not recharge carried ships with either excess energy or excess fuel since min(0,<value>) will never return greater than zero.
N/A
N/A
Unreported bug, found while playing with battery only fighters.
Code could be changed to max(0, excess energy/excess fuel) and pass the value regardless but I feel it is better to check for excess energy/fuel and then only call DoRepair if they exist, potentially saving multiple calls when there was no excess available to begin with.
Tested before and after with battery …
> Changed conditions for calling DoRepair for carried ships.

- source/AI.cpp
**Bugfix:** This PR addresses issue #6208.
The AI code now skips over NPC ships that have not yet been spawned when attempting to reparent mission NPCs.
No.
Use the save file linked in the bug report.
> Don't reparent mission NPCs to NPC ships that haven't been spawned

- data/tests/tests_framework.txt
Four of the asserts in the integration tests were not comparisons, but they were assignments.
The issue reported by Amazinite in https://github.com/endless-sky/endless-sky/pull/5244#discussion_r711283286 should have been found by those asserts if they had been written correctly.
Tested the asserts with different numbers (checking for 4 Light Freighters); the tests then fail as expected.
N/A
> Bugfix: asserts in Launch and Navigate tests.

- data/hai/hai missions.txt
**Bugfix:** This PR addresses something brought up in issue https://github.com/endless-sky/endless-sky/issues/6143
Add deadline tag to the "Hiding in plain sight" mission, since presumably the convention is taking place at a specific date and you need to get theme there by then.
> fix(content): Add deadline for "Hiding in plain sight" mission

- data/human/transport missions.txt
This PR adds conversation payments from #5157 to the Lost Boy and Earth Retirement missions, the former of which benefits from it and the latter of which was written with the expectation of this feature being available.
The Saryd Couple mission was also planned to use such a conversation payment (at least according to my own comment in #5157), but the mission structure and story was reworked to not need it, so I haven't rerework the mission to go back and add it.
N/A
N/A
> Implement conversation payments into some missions

- source/MapPanel.cpp
Currently one way wormholes are drawn just like two way wormholes: There are 2 arrows. But that's wrong, because for a one way wormhole one direction of travel is not possible, but just by looking at the map it doesn't seem like the wormhole is one way.
This PR fixes this by not drawing the arrow for one way wormholes. Here's how a one-way wormhole looks like with this PR:
> Correctly draw one way wormholes.

- data/human/transport missions.txt
- source/Conversation.cpp
- source/Conversation.h
- source/ConversationPanel.cpp
- source/ConversationPanel.h
- source/GameAction.cpp
- source/GameAction.h
- source/MissionAction.cpp
- source/MissionAction.h
- source/StartConditions.cpp
Public inheritance should really only be used when the derived classes are to be used via the base class interface. #5157 added public inheritance (_object A_ IS-A _object B_) between MissionAction and the new "GameAction" class solely for code reuse, when composition (_object A_ HAS-A _object B_) is the preferred approach.
Inheritance also enabled atypical access by other classes (e.g. Mission) to reach inside of MissionAction and consume internals that it has no business knowing about (the full GameAction interface). No code actually did this, but the encapsulation was broken, which made this possible to do more easily.
To additionally distinguish the new capabilities in conversations, the keyword "action" is permitted wherever "apply" was permitted. For legacy support, "apply" is still …
> refactor(internal): Replace public inheritance with composition in MissionAction refactor

- data/hai/hai missions.txt
**Bugfix:** This PR addresses a problem discussed in #6261
Recently, the Hiding in Plain Sight mission was changed to have a deadline, and meant to have it calculated automatically with the bare "deadline" keyword.  The automatic calculation depends on the DistanceMap::Days() function, which, unfortunately, will return -1 if it fails to find a route, which, per Amazinite's comment in the above PR, will always happen when the route crosses a wormhole, which it does for this mission.  The calculation then happily plugs in the -1 to compute a deadline of -2 days in the future (i.e. 2 days in the past), which is absurd.
Manually set a deadline of 30 days for the Hiding in Plain Sight mission.  This doesn't protect against further accidents with the bare "deadline" keyword; I'll file an issue …
> Manually specify 30-day deadline for cross-wormhole mission

- data/tooltips.txt
- source/OutfitInfoDisplay.cpp
Since the `atrocity` attribute is a boolean attribute, there is no reason to surface that an outfit has "1 atrocity" to the player. This PR adds the atrocity attribute to the likes of `unplunderable` or `installable`, adding a tag after the main description, saying "This outfit is considered an atrocity." Additionally, a tooltip is provided, explaining more in detail how it will cause you to be attacked in space if scanned, or cause a game over on land.
> Add boolean label/tip for atrocities

- data/human/human missions.txt
This branch is looking for a mission and not a general condition, so it needs the `: offered`.
> fix(content): Look for proper condition for Ivan wormhole Hai branch

- data/human/ships.txt
Gefüllte is currently redesigning the Navy Rainmaker's model, and one issue that's come up is creating a mass that could possibly fit the 7 required crew and 14 bunks in a such a small sprite. Looking at when those numbers were set, it seems like MZ went through in commit 408c7a8, and mostly increased required crew/bunks across the board. Most were sensible, but the Rainmaker had its crew more than doubled, and bunks more than _tripled._ That is an extremely excessive increase for a mostly autonomous missile boat, and with approval from Warlord Mike, this PR seeks to (mostly) revert it back to what it was, leaving in a few extra bunks.
Additionally, one of the few bunk reductions in that commit was the Sparrow. It changed the bunk quantity from 3 to 2, which massively changes the …
> Revert old bunk adjustments on Rainmaker/Sparrow

- source/Ship.cpp
**Bugfix:** This PR addresses an issue mentioned on the Discord by @1010todd.
Ships with the attribute `"fuel generation"` now correctly recharge their fuel completely if they land on an uninhabited planet. This isn't currently the case.
A ship with `"fuel generation"` correctly recharges its fuel on an uninhabited planet.
> Ships with fuel generation recharge on uninhabited planets.

- data/human/pirate jobs.txt
Fixes a bug due to a typo for a pirate job, reported by @matthew.najmon on the Discord.
> Fix typo (phase -> phrase).

- data/human/deep missions.txt
`The team of scientists is already waiting in the spaceport when you arrive. They remove the equipment from your ship and immediately begin analyzing the results after returning to the lab.`
"begin" was previously "being"
> Typo fix in Deep Missions.txt

- data/coalition/coalition missions.txt
The on visit for the first mission, in case you have no money, makes mention of the "beer's price",  but in this mission you are bringing Arach rum to the students, not beer.
Just changes the word to match with the rest, was the only instance I found of it not being rum.
> Coalition Saryd Students Word Fix

- source/CargoHold.cpp
**Bugfix:** This PR addresses issue #6313
`CargoHold::IllegalCagoFine` is responsible for calculating the fine for any illegal outfits inside a cargo hold. It only looked for  the `"illegal"` attribute on outfits. This PR makes it check for `"atrocity"` too.
Tested this PR with the plugin from the issue. Landing on the high security planet correctly issues a death sentence with an atrocity inside the cargo hold. On master it doesn't.
See the linked issue.
> Correctly detect atrocities in a cargo hold when scanning.

- data/coalition/coalition missions.txt
warp-core pointed out in 6324 I wasn't adding a "the" before using the <destination> replacement when the destination was a Heliarch ring. Turns out I never noticed that "the" in the First Contact missions/the jobs, so all my missions that have the rings as destinations have the issue.
This just adds the "the"s where they were missing. Let me know if I missed any.
> Make Destination Replacements referring to the Heliarch rings Consistent.

- data/remnant/remnant missions.txt
For the main dialog options when accepting Remnant: Deep Surveillance, the order of conditions checks if you've not revealed the Remnant at all, if you've given over technology, or if you've planted the cubes on their worlds, in that order. However, since planting the cubes implies you've given over technology, it will branch before getting there. This PR reverses the order of the technology and surveillance branches, ensuring a player will properly see it.
Big thanks to Kroniicoptor on the discord for digging into playing these missions!
> fix(content): Reorder Remnant: Deep Surveillance conditions to see last branch

- data/human/outfits.txt
This PR addresses an issue found by @Rocky196884 on the Discord: Luxury Accommodations didn't have a `plural` node so the default plural was used ("Luxury Accommodations**s**") which is wrong.
> Fix plural form of Luxury Accommodations.

- source/Government.cpp
- source/Government.h
- source/Ship.cpp
- source/ShipEvent.h
This is a continuation of #6351, which added the ability to specify a rep loss when a government is completely scanned.
This PR adds the ability for governments to be provoked by starting a scan, just like you provoke a friendly government by attacking them. The attribute name isn't great, so feel free to suggest another one.
Just like attacking a gov, whether the government becomes hostiles depends on the personality of the scanned ship (`pacifist` and `forbearing` are the only relevant ones).
```
government Remnant
"hostile when scanned"
```
Added the attribute to a government and verified that starting a scan provokes them. No effect on governments without this attribute.
Negligible.
> Add the ability for governments to be provoked when starting a scan.

- source/Angle.cpp
- tests/src/test_angle.cpp
**Bugfix:** This PR addresses issue #6367
`Angle::Random` that took a range can generate invalid (out-of-bounds) angles when the given `range` was greater or equal to 360 degrees. Calculating a unit vector of such an invalid angle caused an out of bounds access to the cache used to quickly find a unit vector.
The fix involves clamping the angle back into the allowed range on construction.
I called `Angle::Random` with a range of 3,600,000 degrees which always caused a seg fault on my machine. Not with this PR :)
> Fix an out-of-bounds access when generating random angles greater than 360.

- data/governments.txt
- data/remnant/remnant missions.txt
- data/remnant/remnant ships.txt
This makes the Remnant hostile to being scanned (they get provoked, and player will take a rep hit for scanning them), as well as bumping up the penalty for disable and boarding them slightly (from the default 0.5 and 0.3 to 1); and creates a separate government that *can* be scanned for times when a research subject is needed.
Also modifies Keystone Research 5 & 6 to make use of this scannable government.
The scannable government is `"Remnant (research)"`
edit. 
-The reputation hit for scanning has now been dropped from 1 to 0.1.
-Also added `"crew equivalent" 1` to the Tern so that the Remnant value their loss appropriately.
- ~~[X] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified~~
- ~~[X] I …
> Content: Making the Remnant Secretive (aka scan-hostile)

- data/human/human missions.txt
The spacediving jobs which don't give the advertised payments due to accidents are manually written as giving "120000 credits". However, payments procedurally substituted in like the normal spacediving jobs have it properly marked with a comma, as "120,000 credits". This PR adds a comma into the fake ones to make it not have an obvious tell.
> fix(content): Add comma to fake spacediving payments

- source/AI.cpp
- source/AI.h
**Feature:** This PR fixes a performance bottleneck found in #6329.
`AI::GetShipsList` returned a vector of `shared_ptr` which is unnecessary since there is no reason why a function that returns ships based on a filter should take ownership of the ships in question.
`AI::governmentRosters`, `AI::enemyLists` and `AI::allyLists` were also changed to use a simple `Ship *` instead of a `shared_ptr` since for them it is also unnecessary to incur the cost of ownership.
I'm sure there are still more cases of `AI` using `shared_ptr`s unnecessarily, but I didn't want to change too many things. And since only the fixes in this PR appeared on the profiling data, it seems like modifying the rest is at this point in time premature. but idk
Improvement. For N ships in the system, this PR saves the cost …
> Replace some unnecessary shared_ptrs with regular pointers in AI.

- data/map.txt
TLDR: Wayfarer description grammar is questionable.
`Tarazed corporation` should be `The Tarazed Corporation` instead.
> Fix questionable grammar in Wayfarer description

- source/ConversationPanel.cpp
- source/ConversationPanel.h
**Feature:** This PR implements the feature request detailed and discussed nowhere I think. 
If you use the mouse to select a choice in a conversation, then it can be confusing since the choice is not highlighted. This PR highlights the choice when hovering with the mouse, as seen in the gif below:
Tested this with a test mission as seen in the gif.
Negligible.
> Highlight conversation choice when hovering with the mouse.

- data/human/deep missions.txt
Switched `and he` to `, who` to avoid using a male pronoun.
Caught by Solarshade on Discord - thanks!
> fix(content): Remove male pronoun usage

- .gitignore
This just adds another folder to the `.gitignore`, ignoring `.metadata`, which is used by the Eclipse C/C++ IDE.
> Ignore Eclipse IDE folder

- data/interfaces.txt
- source/BankPanel.cpp
- source/HiringPanel.cpp
- source/Interface.cpp
- source/Interface.h
- source/TradingPanel.cpp
Introduces a new `LineElement` class for horizontal lines for interfaces. This PR also makes use of this element for the trading, banking and hiring panels. No visual difference between this PR and master.
The hiring panel is now fully implemented as an interface. 
```
line
from <x> <y>
dimensions <width> <height>
color <color>
```
Verified that there is no visual difference and that the lines are draw correctly.
N/A.
> Implement new line element for interfaces.

- source/Outfit.cpp
- source/PlayerInfo.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #6406
This PR allows outfits to have negative`"maintenance costs"` and/or negative `"operating costs"`, thus allows the creation of outfits that generate credits for the player.
If we want to include such outfits in the main game, then I would expect some additional work to be needed to improve the display in the bank panel (separate the money-generating-maintenance from the regular-maintenance), but this PR should already be useful for plugin creators as-is.
[paying_outfits.txt](https://github.com/endless-sky/endless-sky/files/7765303/paying_outfits.txt)
I installed the outfits given as example and made a few jumps with them (on a new player without morgage). The jumps each resulted in adding 50 credits …
> Allow negative maintenance and operating costs

- source/Audio.cpp
Since #6229 the integration test logs were spamed by "but does not exist" sound warnings. I have now figured out that this is caused by missing audio drivers in the CI env. With this PR if the audio could not be initialized it emits a single warning: 
> Warning: audio could not be initialized. No audio will play.
There's not much to test. The CI env ~~should not~~ edit: doesn't emit a million warnings anymore.
> Fix audio warnings spam when the audio driver can't be initialized.

- EndlessSky.xcodeproj/project.pbxproj
- EndlessSkyLib.cbp
- source/FogShader.cpp
- source/GameWindow.cpp
- source/LoadPanel.cpp
- source/MainPanel.cpp
- source/MapPanel.cpp
- source/MenuPanel.cpp
- source/PreferencesPanel.cpp
- source/Shader.h
- source/ShopPanel.cpp
- source/Sprite.cpp
- source/StarField.h
- source/opengl.cpp
- source/opengl.h
- source/text/Font.h
The Adaptive VSync detection implemented in #5000 is partially incorrect. Adaptive vsync is a platform specific extension and as such it doesn't appear in the list of OpenGL extensions in some drivers on Windows and not at all on Linux. SDL doesn't have a platform agnostic function unfortunately, so we need to call the platform specific functions manually.
I'm not quite sure whether OpenGL ES supports GLX and WGL. I can't seem to find anything except vague mentions in comments on the internet. I just left the existing logic (checking the standard extensions) for now.
I'm on Linux X11 with the official Nvidia drivers on a GTX 1650M:
- Without this PR: I can switch between vsync off and on in the settings.
- With this PR: I can switch between vsync off, on and adaptive in the settings.
I …
> Fix Adaptive VSync detection.

- .codespell.exclude
- .github/path-filters.yml
- .github/workflows/ci.yml
This PR adds a CI run that runs [codespell](https://github.com/codespell-project/codespell) when the `data/` folder was changed to find any typos. In contrast to traditional spellchecking tools that check if a word doesn't exist, codespell checks for misspellings. For example, `thiss` won't get flagged as a typo because the misspelling `thiss` doesn't exist in its database. As such some typos will get missed. But it also means we don't have to a huge list of false positive to filter.
Exclude files are always a bit dumb, but they're necessary. In this case, the whole line with the false positive needs to be copy+pasted into the exclude file. The alternative to this would be to mark the misspelling as not a typo, but then it might be an actual typo somewhere else that wouldn't get detected. …
> Add spellchecking CI with codespell.

- .github/workflows/ci.yml
When CIs are run the PR is merged with the current master implicitly. If a file has changed in master but the PR hasn't been merged with master yet than any line numbers by codespell will be incorrect, as they will refer to the merged file instead of just the PR file.
This PR fixes this issue by checking out only the PRs branch without this merge ([link to the docs](https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit)). Many thanks to @MCOfficer.
Verified that the checkout doesn't merge with master. If the CI is run on the branch itself without a PR then it still works.
> codespell CI wrong line numbers fix.

- data/tests/tests_wormhole_navigation.txt
As it's currently implemented, the "lost" tutorial prompt checks if you fly too far from the center of a system, based on how many days off from your starting date you are. The Ember Wastes Navigation pilot was set to fly around late 3012-3013 in #6214, which compared to the default start date, leaves you about -330 days out from the start.
While this currently doesn't affect vanilla content, something in the Ember Wastes may change in the future that would trip that tutorial prompt. According to Peter, there's no particular reason for the 3012-3013 dates, so this PR gets ahead of that. Perhaps we may want to suppress tutorial missions while running integration tests in the future as well, but this is a simpler fix at the moment.
> fix(integration-test): Adjust EW Navigation test dates to avoid tutorial prompt

- data/human/free worlds reconciliation.txt
Reported by pilover100 on Discord. Thanks!
On line 247 the word "member" makes it sound like a single member of parliament is responsible for all the questioning; whereas given the nature of a parliament, it is more likely that many of the members are doing the questioning. This is particularly the case given that other paragraphs in this same scene make a point of emphasizing how many members of parliament there are that come from Syndicate worlds, and how they all seem hostile to him.
n/a
n/a
> Fix: FW Reconciliation 2 pluralization of "member"

- data/remnant/remnant.txt
**Bugfix:** This PR addresses the serious lore problem of the Remnant not disabling anything when they are explicitly described as doing so (and even penalizing the player when they destroy something instead of disabling in one mission).
Adds the "disable" tag to the following fleets.
- Small Remnant
- Large Remnant
- Remnant Transport
- Remnant Home Guard
Note: The decoy, light, and large defence fleets are exclusively used for "no-holds-barred desperate fight for survival" situations, and thus explicitly should *not* be concerned about disabling, just like they aren't concerned about appeasing or harvesting.
https://github.com/endless-sky/endless-sky/pull/5667
Background:
This behavior was originally removed on the expectation that just having the "plunder" would cause the Remnant to …
> Fix: Re-establish Remnant Disabling Behavior

- source/Test.cpp
- source/TestContext.cpp
- source/TestContext.h
**Bugfix:** This PR addresses the review comment from https://github.com/endless-sky/endless-sky/pull/6290#discussion_r779266292
Combined the variables testToRun and stepToRun in the TestContext class into single callstack variable. A single vector with both the active test and test-step is more clear than two separate vectors that are treated as one.
Executed the set of integration tests.
N/A
> test (maintenance): Combine testToRun and stepToRun into single callstack variable

- .gitignore
- SConstruct
Adds support for compilation db, which is a database/file used by LSP servers like clangd to properly index source files (like an IDE). The file is generated by running `scons cbd`. This requires scons 4, which was released July 2020.
This PR also adds clangd's cache folder and the compilation db itself to the git ignore list.
> Add support for clangd compilation db.

- data/tooltips.txt
- source/BankPanel.cpp
- source/Outfit.cpp
- source/PlayerInfo.cpp
- source/PlayerInfo.h
**Feature:** This PR implements the feature request detailed and discussed in issue #6406
This PR adds the keywords `"income"` and `"operating income"` as suggested in #6406.
This PR also reverts the previous implementation (from #6423) that didn't use those separate keywords.
After commit 8697c90e7346529a7bbed62efafa794d88539936 :
See the attached file:
[paying_outfits.txt](https://github.com/endless-sky/endless-sky/files/7771629/paying_outfits.txt)
Tested with the examples above (and created the screenshots as seen above).
No impact is expected, since those calculations only run on launches and jumps (day changes).
> feat(mechanics): Allow outfits to generate income

- data/human/free worlds reconciliation.txt
**Bugfix:** This PR addresses issue #6436
There was some awkward phrasing in line 1468 of FW Reconciliation, where there is the line `"The aliens claimed that they had had dealings with the Deep in the past. Do you know anything about that?"`. While grammatically correct, it is awkward to read. I replaced it with `had dealt with` instead. 
I changed three words.
> refactor(content,grammar): Rephrase statement in FW Reconciliation

- data/human/free worlds middle.txt
This PR adds an `on fail` dialog to Defend New Tibet, the branching point for Free Worlds to Reconciliation vs. Checkmate. I've seen at least two cases of players ending up having the mission passenger on an escort which gets destroyed in the ensuing battle, and silently being unable to continue right before the climax of the whole campaign. Having an `on fail` dialog ensures that players won't miss that it happened, and from what I can tell, it does not conflict with this mission requiring a decline to start the Checkmate branch.
> fix(content): Add 'on fail' dialog for Defend New Tibet

- copyright
**Correction:**
This corrects the copyright from just being the author's Discord handle, to actually being the name they would like to have attributed to their work.
(Thanks J Everett Nichol for the awesome scene. I'm very glad to have it in the mission!)
(They just got back to me with what name they wanted the copyright attributed to)
> Fix: Updating Ssil Vida Alert Hologram's copyright

- source/Engine.cpp
- source/HailPanel.cpp
- source/PlayerInfo.cpp
- source/PlayerInfo.h
- source/Ship.cpp
- source/Ship.h
**Feature:** This PR implements part of the feature implemented in #6502
This PR moves the filling of the subs for hailing from Ship to PlayerInfo. This move results in Ship no longer needing to include PlayerInfo.h and it removes a reference to GameData from Ship.
This change is split off from #6502 because it can be described, tested and merged standalone.
N/A (the game should still look the same)
N/A (code change only)
I tested by replacing the `data/human/hails.txt` file by [hails.txt](https://github.com/endless-sky/endless-sky/files/7920320/hails.txt) and then hailing a friendly civilian ship during flight. The text-replacements showed up as expected.
No impact is expected, the handling of empty hails could theoretically be a bit slower (since the subs now get generated, even if we …
> feat: Remove PlayerInfo dependency from ship / Move hail-subs to PlayerInfo

- source/Armament.cpp
- source/Armament.h
- source/Ship.cpp
- source/Ship.h
**Feature:** This PR changes the Ship::equipped vector to be generated on demand
The Ship::equipped vector was generated during loading, but it was also possible to generate the numbers directly from ship.armament. Using generation makes the code a little bit simpler and benefits changes like moving the ship-loading to a different class (as is being done in #6502)
Testing this feature showed that some warnings were missing (also in the original code before this PR), the missing warnings were added.
N/A
N/A
Tested the new feature with the attached [tests_equipped.txt](https://github.com/endless-sky/endless-sky/files/7921010/tests_equipped.txt) datafile:
- Copy the datafile to the data-directory.
- Start the game (and notice warnings for the "Messed" ships)
- Check if the ships in-game …
> feat: Generate Ship::equipped on demand instead of on load

- source/GameData.cpp
- source/GameData.h
- source/GameLoadingPanel.cpp
- source/SpriteSet.cpp
- source/UniverseObjects.cpp
- source/UniverseObjects.h
#6279 introduced 2 race conditions while loading. The first one is when drawing the interface in `GameLoadingPanel::Draw` and the second one is concurrent read/writes in `SpriteSet::Modify` called by data objects that store a pointer to a sprite and the sprite loading threads from `SpriteQueue`.
My bad for not catching this earlier.
Used the thread sanitizer to verify that there are no more race conditions while loading the game.
Any access to sprites is now guarded by a mutex, but it shouldn't have a measurable effect on performance I believe (I didn't profile, but CPU load is the same). Most uses of SpriteSet cache the actual Sprite pointer, circumventing the lock. The cases where SpriteSet is used every frame are for various UI elements, so there aren't a lot of locks being taken. …
> Fix race conditions while loading the game.

- data/hai/hai jobs.txt
- data/human/jobs.txt
- data/human/paradise world jobs.txt
This PR lowers the required cargo or passenger space for various jobs to spawn across human and Hai space across the board. Currently, many of these more lucrative jobs are completely invisible to players until they upgrade their ship entirely, when many of them could be within reach. In particular, Large Rush Deliveries and Family Transports can sometimes fit on a stock Star Barge/Shuttle, or otherwise fit most with an extra cargo expansion/bunk room or two. However, new players would have no idea these missions would exist until they slowly grind up much lower-paying missions and buy a whole new ship. By having these missions appear sooner, a player can tweak their ship more purposefully without blindly or accidentally stumbling into these new ones.
To make clear: This PR does not …
> feat(balance): Lower hard requirements for cargo/passenger job visibility

- data/map.txt
This just changes the spaceport images of Baianus and Fertriery from duplicate images to unused ones. This will get rid of the last two duplicate images documented in #6446. I also found a small typo in Baianus' description, which I fixed in this PR as well. There is no new art in this PR, I just utilized unused images in the images folder.
> Content: Removing two duplicate spaceport images. 

- source/MapOutfitterPanel.cpp
- source/MapSalesPanel.cpp
- source/MapSalesPanel.h
- source/MapShipyardPanel.cpp
- source/MapShipyardPanel.h
**Bugfix:** This PR addresses an issue reported by @1010todd on the Discord.
The fix involves correctly passing the custom swizzle of ships to the function that draws the thumbnails.
Verified that the Emerald Sword is correctly swizzled inside the map shipyard panel as well as a few other ships with custom swizzles. Verified that outfits don't get swizzled and that the ships without a custom swizzle are swizzled according to the player's gov.
> Correctly draw ships with custom swizzles inside the map panel.

- data/human/free worlds intro.txt
When accept is a child of one of the choices in a conversation, it feels awkward to read because after clicking the choice, no new text appears and the player has to click [done].
By adding dialogue that appears after the choice, the player sees new content between having to click the choice and click [done].
This is what the game looks like without the change. The last line was a choice, so the player has already read that text.
> Show additional dialogue between accepting mission and closing conversation (FW Katya)

- data/persons.txt
The Lampyrid is an easter egg / tribute ship referencing the Firefly-class ship popularized by the TV show of the same name, as well as the Serenity movie. While it is rare to see and even rarer to fly, I thought it would still be a nice detail for those inclined to notice such things that it has the right number of bunks.
This also makes it slightly more useful / relevant for the rare player who actually manages to acquire it, although not massively so. It is still unlikely to ever be more than a trophy ship, but this is a nudge towards usefulness. 
https://firefly.fandom.com/wiki/Serenity
> Fix: Correcting the Lampyrid's number of bunks

- data/coalition/coalition missions.txt
-----------
**Fix (Missions)**
I was testing some stuff ingame when I clicked on the spaceport in Pelubta Station. I was prompted with the Arachi Orphans mission set, which I found very odd since I don't imagine a station is the best place for orphans to grow up in.
Turns out I hadn't removed it as a possible source for this mission, and for the Longcow Antibiotics mission (it's not impossible for the Longcow Ranchers to be around the station when they need to contact the player, but it is pretty weird to get that mission on the station I think).
This just removes Pelubta Station as a possible source for those missions.
Edit: I don't know why line 1948 is being apparently changed here.
> Coalition: Remove Pelubta Station as a source for some missions

- data/remnant/remnant ships.txt
**Bugfix:**
This deletes one line with a duplicate `"atmosphere scan" 100` from the Merganser.
Thank you to Hecter on the Discord for reporting it.
> Fix: Remove duplicate "atmosphere scan" on Merganser

- data/interfaces.txt
- source/LoadPanel.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #4891
Readds a shortcut to delete a pilot since deleting a pilot is now impossible to do accidentally. This doesn't add a shortcut to remove a snapshot because that confirmation dialog is too easy to dismiss. 
Pressing 'd' correctly opens the delete confirmation dialog.
N/A
> Add 'd' key shortcut to delete a pilot.

- data/human/human missions.txt
- source/Mission.cpp
This PR cleans up formatting for the Repulsor Failure mission, and adds a minor tag. Without it, you can have an instance of First Contact with aliens, followed by text saying that you're somehow still in space and haven't fully entered the planet's atmosphere yet. This will ensure that it won't collide with any landing missions.
> fix(content): Add minor tag and extra formatting to Repulsor Failure

- data/hai/hai missions.txt
- data/wanderer/wanderers start.txt
This PR adds a new mission where the player tries to enlist the help of the unfettered to help with translating the Wanderer language, covering cases where the player might think that the Unfettered are more trustworthy than their brethren, such as if they enter Hai space from the north.
> Add new mission where the player tries to get an Unfettered translator

- source/MapPanel.cpp
- source/Mission.cpp
- source/Mission.h
- source/MissionPanel.cpp
**Bugfix:** This PR addresses issue #6538 
Introduces a new function called `Mission::CanAccept` that checks whether a mission can be accepted. It checks whether the `on offer` and `on accept` actions can be done (which includes payment but also outfit requirements among others) and whether the player has enough space.
I didn't change the `Mission::HasSpace` function because that function is still useful standalone to avoid duplicating work when `CanOffer` is called as well.
TBH none (yes I know I'm lazy), but this PR is pretty straightforward I think (at least I hope so). But I'll do more testing if required.
> Introduce Mission::CanAccept to avoid accepting missions whose requirements aren't met anymore.

- changelog
**Bugfix:** This PR addresses some (potential) errors that were merged with #6296. While this section of the changelog is subject to change, these lines would not show up in in PR completing the changelog, so better discuss those things now before they are forgotten.
> fix(typo): Typos & Grammar in 0.9.15 changelog

- data/drak/drak ships.txt
**Content Fix**
The Drak Ammunition the augmented Drak weapons used was removed in favor of having them "use" 0 Jump Drives to fire, so there's no need for this attribute.
> [Fix] Remove Drak Ammo capacity attribute from the Archon

- data/human/free worlds middle.txt
When offered the FW Alphas 1.1 mission at New Tibet, Freya is in Zug (since FW Northern 3) and should not be able to participate in the discussion.
I know some people recently wanted to allow time travel, but I believe that for now there is no kind of instantaneous communication between systems, hence no option for video-conference.
no test file, no tests performed
> Replace Freya by Alondo in FW Alphas 1.1

- data/human/sales.txt
- data/map.txt
The outfitters adjacent to the largest uninhabited section of space don't carry the ramscoops needed to traverse it. This PR creates a new outfitter definition 'Northern Explorers' which contains only ramscoops and then adds it to the outfitters on Haven/Arneb, Prime/Betelgeuse and Sunracer/Mirfak. Catalytic ramscoops are not added.
> Add ramscoops to outfitters on Haven, Prime and Sunracer

- source/DataWriter.cpp
**Bugfix:** This PR addresses an issue reported by Apotheon on the Discord.
When writing strings to file that begin with a `'#'`, `DataWriter` didn't escape them with quotes. As a result, the string got interpreted as a comment and ignored when the file is loaded again by the game.
This PR fixes the issue by quoting strings that begin with a `'#'`. Strings that simply contain a `'#'` on any other position do not pose a problem for the parser.
Created a new pilot with the name `broken #hi`. The first line is on master and the second one is with this PR.
```
pilot broken #hi
pilot broken "#hi"
```
> Quote strings that begin with a '#'.

- data/human/near earth jobs.txt
...instead of failing only if landing somewhere on the very Earth Day.
This PR addresses issue #6526 (using "compact" conditions as per suggestion in #6553 comments)
It is the minimal fix to make the missions work as intended (according to their current "on fail" condition)
I didn't change the description of the missions as suggested in #6526, as I missed some proof-reading and I'm not sure it would be clearer (the current description might be ok, even if it may surprise people used to deliver after the deadline, like I was ;)
I edited the save file from #6526 with the new conditions:
- mission succeeds before Earth Day and deadline (same as before)
- mission fails when landing on Earth Day (same as before)
- mission fails when landing after Earth Day (unlike before)
> Really fail missions after Earth Day deadline

- source/DamageDealt.h
- source/DamageProfile.cpp
- source/Engine.cpp
- source/Ship.cpp
- source/Ship.h
**Bugfix:** This PR addresses issue #4836.
Currently, if a ship is hit by a blast radius weapon then it does not become provoked, except if that blast radius weapon directly hit the ship. But if a weapon has a trigger radius then it never directly hits the target, meaning trigger radius weapons will not provoke governments. This PR changes it so that ships hit by projectile explosions will become provoked if they were directly targeted by the projectile.
Fired at friendly ships using trigger radius weapons with and without this change. With this change, targeted ships now become provoked.
N/A
> Ships targeted by trigger radius weapons now become provoked

- .github/workflows/projects_check.yml
This PR restores the workflow triggers for the project validation workflow from #6572. I also readded the branches filter, simplified a few things, and fixed the indentation.
> Run project validation CI on PRs.

- source/Outfit.cpp
**Bugfix:** This PR addresses issue #6578
`"required crew"` could be reduced to 0 by buying an android. This means that when selling the android a crew member is hired but that is unnecessary since the player exists, which results in an extra crew being hired. The easiest way to fix this is to disallow `"required crew"` to be less than 1.
Tested buying and selling androids on ships.
> Don't allow "required crew" to be less than 1.

- .github/workflows/ci.yml
The CI was depending on the compute-changes workflow from the main repository (this one). This means that any fork will also use the workflow from the main repository instead of the local one, which isn't ideal.
This PR changes the absolute path into a relative path so that the repo is self contained.
> Use local CI instead of endless-sky/endless-sky.

- source/BatchShader.cpp
- source/FogShader.cpp
- source/OutlineShader.cpp
- source/SpriteShader.cpp
Some shaders used invalid GLSL. According to the [wiki](https://www.khronos.org/opengl/wiki/Type_Qualifier_(GLSL)):
> In this case, *type*​ can only be `float` or `int`.
This causes oldish drivers to fail to compile the shaders. This has happened at least once.
Verified that the relevant shader still work, also using OpenGL ES.
Edit: This PR fixes the compilation error on oldish drivers, confirmed.
> #ifdef OpenGL ES specific GLSL.

- source/BatchDrawList.cpp
**Bugfix:** This PR addresses issue #5508.
Corners of the effect image were calculated incorrectly.
Thanks to oo13 for finding the location of the bug.
I tested this with the void sprites. Since it works correctly for them, I think it should work correctly elsewhere too.
[Local God.txt](https://github.com/endless-sky/endless-sky/files/5932977/Local.God.txt) (to test the fix, go to Nenia and shoot some void sprites (-debug flag helps since then you can slow down the game))
> Fix: effects are no longer mirrored

- data/remnant/remnant 2 cognizance.txt
- data/remnant/remnant jobs.txt
**Bugfix:** This PR addresses the problem of a missed capitalization on things that test for one of the events changed in #6547 
While the event that sets and clears "remnant: ssil vida active" was correctly changed from in the recent fix, the jobs that depend on it were not. This fixes that part.
searched through and reviewed everywhere that sets variables in the Remnant missions.
Thanks to Starext on the Discord for reporting this problem.
> Fix: Remnant: Fixes capitalization on a variable "remnant: ssil vida active"

- data/human/culture conversations.txt
**Bugfix:** This PR addresses issue reported by u/riyan_gendut on the Discord bug reporting channel. 
Line 248 the `decline` is improperly indented. Needs one additional tab.
Thanks for reporting this, u/riyan_gendut!
> Fix: Culture: Syndicate Security Troops - Add a missing tab

- data/human/human missions.txt
On L2388, the officer of the Navy soldiers raises a megaphone to "their mouth", but is later referred to using male pronouns consistently.
Also makes the game remember the player's reputation with the republic, though I'm impartial to changing it back to how it normally works.
> Fixes to "Paradise Fortune"

- source/AI.cpp
~~The wiki description says cowards run at 0% shield but they do not, I updated it to match that.~~
The wiki's description needs to be updated to say that this happens to a ship when he reaches critical health, it works almost in the exact same way appeasing does except this one just gets out of there (generally it does match 0 shield but it actually is 35% of total health, meaning hull left before being disabled + shield / full available hull before disabled + full shields)
~~On top of that I discovered that coward wasn't working properly, because the current target was not removed so the ship would just exit the fleet and keep on fighting it's current target instead of getting the heck out of there.
So this makes cowards actually behave as you would expect, instead of stubbornly keeping …
> Make coward and appeasing trigger earlier

- source/Government.cpp
- source/Politics.cpp
This PR hooks up the Provoke ShipEvent as an event that can cause reputation changes. This can allow for the opposite of Forbearing, where a government can take immediate and permanent reputation loss the instant you fire on them, among other uses.
> feat(mechanics): Allow for rep changes from provoking a government

- source/Engine.cpp
**Feature:** The fuel bar will not break into a million pieces if you have a very large amount of fuel
If you have more than 1200 fuel (12 bars) on your ship, the fuel bar renders as one instead of 13 or 600 bars, or whatever crazy amount you may have.
If you've ever flown a ship with only 100 fuel, you know what the bar will look like.
Y'all are magicians testing these builds without some sort of game launcher that doesn't require you to compile the game by hand. Will heckin' test on ships with low fuel, and very high fuel, and fuel values not divisible by 100, after I make the pull request and ESL2 can grab this PR number. You know how it be.
Adds one check to a process I believe should occur once per frame, but I don't think checking the inequality of a variable to a constant is very …
> Enough fuel renders as just one solid bar of fuel

- data/coalition/coalition outfits.txt
A small typo snuck in with the addition of the Fuel Module in #5838. This PR addresses that.
> fix(typo): Typo in Fuel Module description

- data/hai/hai jobs.txt
This PR adds reputation gain to standard Hai jobs, so that a player can access Hai-Home without being super familiar with the Wah Ki metagame. It gives +2 for standard jobs, +3 for higher-profile jobs, and +5 for jobs that leave Hai space.
> feat(content): Add reputation gain to Hai jobs

- source/PlanetPanel.cpp
- source/PlayerInfo.cpp
**Feature:** Thought of this while reviewing #6615.
When the player doesn't have enough cargo or bunk space for an active mission when they attempt to depart, the game will prompt them that they will fail the mission if they continue, and choosing to continue then sends the FAIL trigger to that mission. 
This PR changes it so that missions that the player doesn't have enough space for on take off receive the ABORT trigger instead of the FAIL trigger, and all references to mission failure under this scenario have been changed to make it clear that the mission was aborted instead of failed.
The ABORT trigger didn't exist when this code was written, but it makes more sense to say that the mission was aborted instead of failed since it's player action that is removing the mission from their …
> feat(mechanics): Abort missions that you don't have space for instead of failing

- data/human/free worlds middle.txt
Changes the text from the generic bounty dialog, which wouldn't even work correctly due to npc ordering errors, to text that mentions both Ryk Bartlett's ship correctly and JJ's presence.
> Fix "on visit" dialog for FW Albatross 2A

- data/human/deep jobs.txt
This PR fixes some of the errors present in the jobs committed in 449debe59be4476707ea12a572ec35f7ea6f6ec2, most notably the ability for jobs to have the same destination as a source. It also fixes some of the text substitutions to the correct ones and changes some of the text, such as making it more explicit that the consultants leave behind stuff on your ship and pointing out how time-sensitive the "urgent" missions are. Also included are changes to the payment amounts of each job, integration of rep mechanics to the older mystery cube jobs, and removal of reputation penalties for the jobs, due to being problematic if the player fails/aborts them while at low reputation.
> Modifications to New Deep jobs

- source/PlayerInfo.cpp
A comment on "[checking] if the player has visited the given system" was copied over to the function that checks for planets.
> Correct documentation

- data/human/human missions.txt
Right now, TMBR 1 has a defer option after a fairly detailed explanation of the mission. This makes it somewhat awkward when the mission is continuously offered after the fact, as, across half the known galaxy, you'll be introduced to Becca (the stage manager), who'll explain her offer in depth the exact same way.
> Change wording in TMBR 1 so that the player can defer w/o going into specifics

- data/human/human missions.txt
Turns out that missions with names that are earlier in the alphabet are discarded first when it comes to picking a single `minor` spaceport mission, the opposite effect of what I expected. This fix should let minor missions offer properly again.
I would like if others would test this by creating a new pilot, heading to Rand/Smuggler's Den and checking the spaceport there, which should offer their respective unique missions.
> Correct mission load ordering in Spaceport Resetter

- data/kahet/kahet missions.txt
- wonders to wanders
- adjusted Dusk statement to make it clear that they're not meeting you for the first time
- adjusted player reply to make it clear they aren't meeting Dusk for the first time.
> Fix: Ka'Het: Patir Mystery 2 (Spelling and dialog) 

- data/hai/hai missions.txt
Left Unfettered space off of the source list, since it wouldn't be *that* bad to leave the child there. (Plus, what if it's an unfettered hai child?)
> Let Unwanted Cargo trigger outside of human space

- data/human/deep missions.txt
In conversation "deep: remnant". Should the spell check be updated to catch this?
> Typo fix: vacumm -> vacuum

- data/human/human missions.txt
Hopefully a mention of the amount of payment should make these jobs more appealing, rather than being stuff that gums up the spaceport. I neglected to add a mention of payment to some of the more descriptive/openly altruistic jobs, such as Courier 4, the pirate aid missions, and Rescue Miners.
> Mention payments in the less-descriptive spaceport mission on offers

- source/GameLoadingPanel.cpp
**Bugfix:** This PR fixes #6635 
Plays the landing sound if no recent save file was loaded.
Started the game with no save file: On master silence, with this PR you can hear the landing sound.
> Play landing sound when starting the game with no recent pilot.

- source/UI.cpp
This PR simply removes the extra PushOrPop call that seems to be unnecessary. Hopefully the integration tests confirm this.
> Remove PushOrPop after calling every Panel::Step.

- EndlessSky.xcodeproj/project.pbxproj
- EndlessSkyLib.cbp
- source/GameLoadingPanel.cpp
- source/LoadPanel.cpp
- source/MenuAnimationPanel.cpp
- source/MenuAnimationPanel.h
- source/MenuPanel.cpp
- source/MenuPanel.h
- source/PlayerInfo.cpp
- source/UI.cpp
- source/UI.h
This PR adds a new panel called the MenuAnimationPanel that is responsible for the shrinking circle animation as well as the sound and music that should be played.
Tested various combinations of opening and closing various panels in the menu, including going into the game and reopening the menu as well as verifying that the animation is still correctly drawn.
Also verified that the landing sounds are still played when playing the game.
> Add MenuAnimationPanel that handles the starting animation and sfx.

- data/coalition/coalition missions.txt
This PR fixes a typo and a duplicate paragraph found by Zenathano on the discord, and a typo that I found while looking at the mission.
> Fix a few typos in university lecture mission.

- data/human/weapons.txt
This PR is intended as a companion to #6671 and an alternative to #5796.
As of right now, among human primary weapons, lasers are the top dog in practically every scenario. Lasers are relatively small, meaning it's easy to saturate a ship's hardpoints with them. Lasers have very low firing requirements, meaning you don't need to dedicate as much of your outfit space to cooling or energy. And lasers have very high damage for their size, making them great choices in combat. And on top of all that, the instant impact nature of lasers makes them perfect for boarding playstyles where you want to leave your target alive and means that they'll never miss.
The two alternatives to lasers are blasters and cannons.
Blasters as they are right now are …
> Rebalance human primary weapons: buff blasters and cannons, nerf lasers

- data/hai/hai missions.txt
- data/human/human missions.txt
This just fixes a couple minor typos in mission text that I spotted in a recent playthrough.
> fix(typo): fix minor typos in two missions

- data/wanderer/wanderer ships.txt
- data/wanderer/wanderers start.txt
The Wanderers are an open handed trust culture. They provide food for the Unfettered to raid, they reach out the the Efreti, they provide a terraforming mind to the Mereti, and they disastrously invite the Exiles to assist with dealing with the Sestor. Regarding the Exiles,  "No," says Rek, "the leaders are right, we must offer them our trust until they prove utterly unworthy of it."
Yet, when it comes to the player, they restrict access to their repurposed exploration ship even though the player has fought beside them and assisted with their diplomacy for no direct financial compensation.
Additionally, the only thing actually restricted is the hull. The weapons systems and reactors needed to power them are available it the outfitter. At this point in the game, the player has access to …
> Moved the Strong Wind to the Wanderer licence

- data/kahet/kahet missions.txt
Previously, the mission could only offer after landing in the Graveyard, a requirement that doesn't match up with the other ringworld debris missions.
> Remove unnecessary condition check from "Ringworld Debris: Quarg"

- data/quarg/quarg missions.txt
Cargo names are usually in all-lower-case.
> Typo fix in "Lagrange Ring: Cargo"

- .gitignore
I have developed a portable IDE for Endless Sky contributors.  This change ignores files created by the tasks which replicate GitHub actions.
https://github.com/samrocketman/endless-sky-vscode-devcontainer
> Add gitignore for VSCode Devcontainer

- data/korath/korath ships.txt
**Balance**
The Stock Korath Raider currently has 12 outfit space going unused. Since it's particularly vulnerable to heat, as usual for the Korath, it's odd that they wouldn't put one more Small Heat Shunt there to help keep heat down a bit more.
This just changes the Raider's SHS number from 1 to 2, using 7 of that 12 outfit space it had available.
> Add 1 more Small Heat Shunt to stock Raider

- data/human/culture conversations.txt
Doesn't make much sense for it to offer in the spaceport. Kept the minor tag on.
> Set "Military Response Test" to offer on landing

- data/intro missions.txt
- data/start.txt
**Content**
~~This PR automatically adds a free local map to the player when starting a new game.~~
This PR is a tweak to the intro dialogue given by James, the player is now encouraged to visit the outfitter, rather than discouraged and is specifically told to buy a map.
This seeks to address a number of issues:
1. Many newer players find themselves unaware of the existence of the map, or what it does. 
2. Newer players often find themselves getting lost or unsure what to do upon starting a new game, ensuring that the player will purchase a map in order to reveal nearby systems helps to provide a good starting point while still leaving a lot of space for future exploration.
N/A - New Save Required to access content
Started a new game and confirmed that the dialogue with James was updated …
> Tweak: Adjust intro mission dialogue to encourage a map purchase

- data/human/fleets.txt
- data/human/jobs.txt
- data/human/pirate jobs.txt
Currently, Marauder ships only appear after the player has a combat rating of 600 (ignoring mission unique marauders). At that point, the player likely already has a warship far more powerful than any of the marauder ships that can spawn. To make matters worse, Marauder ships only spawn in fleets, meaning that, to get one, you have to be a decent amount stronger than an individual Marauder them to capture them, furthering their irrelevance.
This PR seeks to make solo Marauder runs more feasible by adding new bounty jobs that only spawn single Marauders. These jobs spawn at similar times to the regular bounty jobs, but with a heightened combat rating check and reward, as well as a lower offer rate, since these fights are generally much harder.
Also added are a series of rival Marauder jobs …
> Introduce new jobs to make smaller Marauders easier to obtain

- data/human/free worlds checkmate.txt
- data/human/free worlds intro.txt
- data/human/free worlds middle.txt
- data/human/free worlds reconciliation.txt
- data/human/free worlds start.txt
As it stands, the salary that the Free Worlds campaign gives out is peanuts: the starter salary can't even cover the crew costs of an Argosy. Having passive sources of income be a decent chunk worse than active sources makes sense from a balance viewpoint, but across the board, salaries pay out negligible amounts (roughly converting 1 cargo space to 150 credits, the initial salary is around 7% of a Raven's earnings, the first pay rise is 10% of a Firebird's, the second is 18% of a Falcon's, and the final salary is 40% of a Dreadnought's) compared to the responsibilities involved (from a lore standpoint, you're no longer an independently operating captain and must put your life on the line protecting the Free Worlds; from a gameplay standpoint, 50% of the known galaxy wants to kill you). …
> Greatly increase the amount of FW's salary + Make Recon's ending closer to Checkmate's

- data/human/kestrel.txt
Not checking for a default Kestrel, since that shouldn't happen.
> Show different Kestrels on the "for sale" mission

- data/human/ships.txt
After the merging of #5792 there are now two additional reverse thrusters available for purchase in human space. 
However to date, not a single ship comes equipped with either of these two new reverse thrusters and only one ship comes equipped with the previous atomic reverse thruster as part of their stock loadout meaning you rarely ever see them.
The intent of this PR is to increase the prevalence of these new outfits by selectively adding them to several human stock loadouts where appropriate to increase the diversity of builds available to a new player, as well as make the entirety of human space appear more "alive" as ships will now maneuver in different ways based on the thrusters they have installed.
You will now see a lot more ships in human space using reverse thrusters and will …
> Tweak: Add reverse thruster outfits to stock human ships where appropriate.

- data/hai/hai missions.txt
- data/map.txt
**Bugfix:** This PR addresses an issue reported on the [discord](https://discord.com/channels/251118043411775489/460556878334918657/964308597028814858).
Added `not planet "Darkwaste"` to "First Contact: Hai" and "Ask the Hai about the Unfettered". An alternate fix could be to make Darkwaste not a Hai planet, but I'll leave that decision up to someone else.
Landed on Darkwaste before any other Hai planet. Then landed on another Hai world and then an unfettered world, before landing back on Darkwaste.
[Hai Testman.txt](https://github.com/endless-sky/endless-sky/files/8493882/Hai.Testman.txt)
You start on Prime with a Scout with a Jump Drive and 7 fuel processors, and some Hai and Unfettered territory mapped. This isn't exactly the most optimal ship build for this test, you might die a few …
> Bugfix: Prevent some Hai missions on Darkwaste

- data/coalition/coalition outfits.txt
- data/drak/drak ships.txt
- data/hai/hai outfits.txt
- data/human/engines.txt
- data/human/ships.txt
- data/pug/pug.txt
- data/remnant/remnant outfits.txt
- data/wanderer/wanderer outfits.txt
This PR is meant as a stepping stone toward resolving #5271 and is a polished piece of #5779. It also resolves #6624.
The general gist of this PR is to shorten the range of speeds that ships are capable of while also increasing speeds at the low end of the spectrum. Shortening the range of possible speeds means that we won't as often have ships which, when using a reasonable engine loadout, go from normal to way too fast just be changing up the engines. This is mainly done by raising the speed floor rather than lowering the ceiling, which will most benefit default fittings and smaller ships.
The changes:
* **-66% Ionic Afterburner heat**: The Ionic Afterburner is a weaker afterburner that uses less fuel at the cost of having firing energy, which the …
> Rebalance the engine sandbox

- data/human/marauders.txt
- data/human/ships.txt
- data/human/variants.txt
~~Three~~ Two ships, the Marauder Manta, Auxiliary ~~and the Gatling variant of the Fury~~ had more/less ammo than their ammo capacity would allow, this PR fixes that.
<details>
<summary>Marauder Manta had 60 Meteor capacity but 70 Meteors installed</summary>
</details>
<details>
<summary>Auxiliary had 90 Sidewinder capacity but 100 Sidewinders installed</summary>
</details>
Purchased each ship and added as much ammo as possible and confirmed that it matched the new ammo amounts.
This save file will place you on New Boston with all of the edited ships already in your fleet.
[Ammo Fix.txt](https://github.com/endless-sky/endless-sky/files/8499177/Ammo.Fix.txt)
I also noticed two Person ships had too much ammo installed for their capacity:
Modified Osprey has 80 Finisher Capacity but has 200 …
> Fix ammo capacity not matching installed ammo on several ships

- data/hai/hai missions.txt
This PR fixes a typo in the attribute checked by the Hai First Contact Missions (uninhabitated to uninhabited), and also makes other applicable Hai missions not offer when landing on Darkwaste.
> Fix typo & add more checks to Hai missions for landing on Darkwaste

- data/coalition/coalition missions.txt
**Content (Missions Payment Changes)**
The Coalition's Yottrite missions currently have the player receiving 10% more for each Yottrite sample than they would get if selling them normally.
Given mining isn't very competitive as far as making money later in the game goes, though, and that the samples are very valuable to the Coalition and the Heliarchs, and also the fact that they can afford to pay better than that, it's odd that the payment bonus you get is hardly worth the trips in and out of the Coalition to get the samples.
This increases the bonus from 10% to 75%, save for the last mission where you get a 100% bonus for the last sample you bring them.
Also updates the conversation references to how many credits you'll receive, in missions where the payment …
> Coalition: pay more for Yottrite samples

- data/human/news.txt
Adds a "Mechanic" news entry for human governments. I'm totally open to adding an `attributes` filter, but a mechanic seems like someone that would presumably be present in any port.
> Content: add 'human mechanic' news

- source/Files.cpp
- source/LoadPanel.cpp
**Bugfix:** This PR addresses issue #6468
This fix uses the pilot's name as a prefix for the new snapshot.
> fix: wrong snapshot names

- data/human/free worlds intro.txt
It was previously missing a minor tag, letting it offer in the middle of other mission chains.
> Add minor to the first Pact Recon mission

- source/AI.cpp
- source/AI.h
**Bugfix:** This PR addresses issue #6720
Following Amazinite's suggestion in #6720, I made hostiles being in the system a requirement for dumping cargo.  Vitalchip suggested I added a proximity check as well as a disabled check.  The proximity check is based on each individual enemy's max weapons range plus a small buffer (currently 500).
I observed Remnant ships in the Ember Wastes ion storms with and without Korath ships in the system and they don't surrender their cargo to empty space anymore.  It is difficult to tell for certain if the buffer works perfectly, but I do know the range to distance comparison has an effect because when I was writing the changes I had my buffer (which was comically large because testing) on the wrong side of the comparison and it never triggered.  Do note …
> Smarter Appeasement

- source/MapOutfitterPanel.cpp
This PR simply replaces a "One" with "1" for consistency with other numbers and other parts where only one thing is mentioned (like "1 ton" and not "One ton").
Thanks to @pilover100 for reporting!
> Don't write out 1 inside the storage text amount for consistency.

- source/ShipInfoDisplay.cpp
**Bugfix:** This PR fixes #6711
In #6326 the padding for the ship info display was calculated incorrectly: There was an additional entry added without the corresponding change to the height variable. This PR fixes this issue by readding this padding and a small style issue.
Verified that you are able to see every line from the ship info display in the outfitter and shipyard.
> Fix missing padding in the ship info panel.

- data/landing messages.txt
If trying to land on a star gives "You cannot land on a star!" with an exclamation mark, then landing on a black hole _definitely_ should give one, as well.
> Add exclamation mark for black hole landing

- data/remnant/remnant 2 cognizance.txt
- data/remnant/remnant events.txt
This adds a single invisible mission that triggers a countdown for an event. This count down establishes a small window of calm in which missions that trigger based on the end of the Cognizance chapter will not occur. Basically, a short breather before all the side missions start triggering.
This PR has no player-visible content, but sets the stage for Remnant Chapter 3 as well as the small mission strings that take place after Cognizance 2. It is being PR'd separately so that it can be reviewed and merged quickly, and thus lay the foundation for the material to follow.
The following three short mission sets all require having this "cognizance calm", although I forgot to include this actual mission and event in some of them.
https://github.com/endless-sky/endless-sky/pull/6761 …
> [Content] Remnant: A breath of Calm

- data/hai/hai outfits.txt
- data/remnant/remnant outfits.txt
Take 2.
Accidentally nuked the previous PR (#6786), so reopening here.
Summary: It doesn't make much sense for keystones to be as large as they are metrically, so I'm trimming them down.
> Reduce Quantum Keystone/Key Stone mass

- data/hai/hai missions.txt
**Bugfix:** This PR addresses issue #6779
It changes the word 'ships' to 'ship'. This is consistent with all the other texts which always mention 'you' returning to your 'ship' instead of 'ships'. 
It only removes one letter from text. There are no other changes
no save file
> fix grammar error 'ships' to 'ship'

- source/BoardingPanel.cpp
- source/BoardingPanel.h
- source/LogbookPanel.cpp
- source/MapSalesPanel.cpp
- source/PlayerInfoPanel.cpp
- source/ShopPanel.cpp
- source/ShopPanel.h
**Feature:** This PR implements the feature request detailed and discussed in issue #6757
This supports going to the beginning and end of the lists. This is
useful when there are a lot of entries (e.g. items or ships) and you
want to quickly go to something specific, where you know where it is
located (e.g. a newly captured ship in the PlayerInfoPanel or the
attributes of your flagship in the outfitter panel.
The implementation needs to decide whether there should only be
scrolling or whether the first or last element should also be selected.
The used criteria is:
Does something else change when the selection is changed?
Therefore, only the BoardingPanel selects, which is consistent to how
other line-based GUI elements typically behave (e.g. in a file explorer
or a text file). The …
> Support the Home and End keys in the panels

- data/wanderer/wanderers.txt
The Wanderer colony on Spera Anatrusk in Korath space does not have an outfitter. As this is the first colony in the new territory it would be a critical first step for them to moving. As it is, resupplying thunderhead missiles is an 8 day round trip. A player needing to adjust a ship build or stock equipment will have to go to Kashikt or back through the wormhole. This PR adds a basic outfitter to the Spera Anatrusk colony event.
[Fred Flintstone.txt](https://github.com/endless-sky/endless-sky/files/8613827/Fred.Flintstone.txt)
Played through the Wanderer campaign until the event triggered. Outfitter showed on the map view and on landing.
> Add outfitter to Spera Anatrusk

- source/Hardpoint.cpp
**Bugfix:** This PR addresses the long-standing issue (in #5857 and lesser-so mentioned elsewhere) that many effects are placed incorrectly at high velocities. (Well, at any velocity other than 0, but the error is proportional with velocity)
Adds a sister Point variable, "visualStart", which mirrors "start", without the -0.5x velocity compensation. This fixes the issue!
I do not think this change has _any_ wider consequences other than fixing this visual bug. Might as well push this to master, no?
(Mind the plugin content, but this is before and after the change. Notice the streaky stars in the background, we're moving very quickly here.)
[bee person.txt](https://github.com/endless-sky/endless-sky/files/8544746/bee.person.txt)
Use this save file, take off from Trinket in the modified …
> Add "visualStart" to Fix Effect Placement Bug

- SConstruct
- utils/build_appimage.sh
We have a useful AppData xml file that provides various metadata information to various software using AppStream. However, we install this file inside the `appdata/` folder, which is very old legacy at this point. Even Ubuntu 16 supports the new recommended folder, `metainfo/` ([source](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location)). So this PR changes the install location.
The AppImage we distribute also automatically gets support for metadata information, as there the only supported folder for metadata is `/usr/share/metainfo`.
> Install the AppStream metadata file inside the correct location.

- tests/integration/run_tests.sh
This simply fixes the example on how to execute the script that forgot to be updated in #6770.
> Correct run_tests.sh path in example.

- data/coalition/coalition outfits.txt
**Content (Stats)**
Just changes the Coalition's solar panels' `heat generation` to `solar heat`, which was pointed in the Discord to be more appropriate since it'd scale with the solar collection, rather than being a constant heat.
> Make the Coalition solars use Solar Heat

- source/OutfitInfoDisplay.cpp
This simply changes the outfit info display to read `cost: free` instead of `cost: 0`. I think it's an improvement because it's a bit weird to see an attribute with the value of 0.
> Use "free" instead of "0" for outfits that are free.

- data/hai/hai outfits.txt
- data/tooltips.txt
- source/Armament.cpp
- source/Armament.h
- source/Hardpoint.cpp
- source/Hardpoint.h
- source/Ship.cpp
**Feature:** This PR implements a feature discussed in relation to #6783 and #5976.
Ion damage is currently considered rather weak compared to the other special damage types that are used in game right now, and with a PR like #6783 that seeks to buff batteries, ion damage would become even weaker. We could perhaps buff the amount of ion damage dealt by various weapons in the game, but then I imagine that'd just make ion damage a second type of heat damage, as the net effect of both special damage types would be to outright disable the target ship.
This PR seeks to buff ion damage by instead creating an additional effect of ionization, that being that ionized ships will sometimes have their weapons jam when they attempt to fire. A weapon which jams will fail to fire, but will still …
> Ionization now causes weapons to jam in addition to draining energy

- data/interfaces.txt
Don't know if this is a bug fix or new feature.
While not holding down alt:
While holding down alt:
The v key was already acting as a keyboard shortcut, this just means holding down alt underlines it in the button label.
> Add underscore for Save Order keyboard shortcut

- data/coalition/coalition ships.txt
**Bugfix:** This PR addresses an issue found by Kitteh on the Discord.
The "Pure Finishers" was missing a hyperdrive. This PR fixes this oversight.
> Add missing hyperdrive to "Pure Finishers" Punisher variant.

- data/kahet/kahet missions.txt
**Bugfix:** This PR addresses issue of being locked out of Cognizance 21 because Dusk is permanently busy.
Because the Kasei are labeled as 'NPC save', kiling them fails the mission; in which case the player doesn't get to see the `on complete` text.
This adds on `on fail` conversation that is simply the fail part.
He's emotional, so it makes sense he reverts to his most instinctive form of communication.
Note: I left a copy of the upset conversation in the 'on complete' to cover all our options. With that remaining in place, if the players manage to kill some Ka'sei somehow without triggering the fail; they'll still get the appropriate reaction either way.
Thanks to Dust on the ES discord for running into this problem and bringing it to my attention!
This save file can be used to verify …
> [Fix]Ka'het & Remnant: Dusk can be permanently locked as busy by failing Patir 5 (unintentional)

- data/coalition/coalition ships.txt
**Content (Ship Loadout Changes)**
With the recent buff to Battery outfits, pretty much every ship variant in the game now has way more energy capacity than they realistically need.
The Heliarchs, focused on being ever-ready for a Quarg invasion, would naturally have each ship type they field make the most out of what space and equipment they have available, and as the battery buff gave almost all Heliarch ships a very large boost to their energy capacity, they could lose some of the space used for batteries, and use it instead for some other outfits.
This PR changes the loadouts of most Heliarch ship variants, either switching larger batteries for smaller ones, or reducing the quantity of batteries. I filled up the outfit space that that opened to the best of my …
> Coalition: Minmaxing Heliarch Variants

- data/coalition/coalition ships.txt
**Content Fix(missed part of the changes for this variant)**
6823 was just merged: https://github.com/endless-sky/endless-sky/commit/0c9f72f48e9465043c3cf87ff1a00e98e367d49d
So I hopped on to check in my game and make sure all the variants were right, and I hadn't accidentally made something go into the negatives for outfit space.
Turns out I missed a change to the Ions variant of the Heliarch Punisher, swapping a Small Battery Module for a Small Reactor Module.
Should've made an ESL2 instance for the PR and checked beforehand, but I forgot, sorry.
> Fix Ions Punisher empty space

- source/CargoHold.cpp
**Bugfix:** This PR addresses an issue reported on Steam: https://steamcommunity.com/app/404410/discussions/0/4536825080749745672/
CargoHold's never clear outfits inside their map when their count reaches zero. The code for determining the fine of the illegal outfits inside that cargo hold didn't check whether there is actually an outfit (i.e. it's count is > 0), resulting in fines for outfits that were once in your cargo hold but not anymore.
I tested this a while back. Adding Nerve Gas to your cargo hold and then removing it and landing on a high security planet no longer gets you a fine.
> Skip ghost outfits when calculating the fine for outfits in a cargo hold.

- XCode/EndlessSky-Info.plist
- credits.txt
- utils/cd_update_versions.sh
- utils/set_version.sh
This PR improves the version identification of ES:
- Changes the current version string inside credits.txt to 0.9.15-alpha, as that is the current version
- The script that adds the "last change" lines to credits.txt no longer deletes the version string
- That same script also adds the commit hash behind the version string (so for example `version 0.9.15-alpha (14a3da2)`)
- Invoking the set version script with a commit hash no longer replaces the version string but adds `(#hash#)` behind the version string (so for example `ver. 0.9.15-alpha (14a3da2)`)
Invoked the scripts in question to verify that they work as intended with any input string (if applicable).
> Improve the version identification for users.

- source/Engine.cpp
- source/Engine.h
**Bugfix:** This PR fixes #6475 
The Engine::Draw() function used one frame before the one it should use, meaning that it was always one frame late. This PR fixes this issue by making it so that Draw() immediately uses the newly calculated draw lists.
Used the save file from the linked issue to shoot the mission Korath to death. With this PR the kill shot appears behind the dialog as expected. I also used clang's thread sanitizer to verify that this PR doesn't introduce a new race condition.
See the linked issue.
> Fix frames lagging one frame behind rendering.

- source/CargoHold.cpp
This ones on me. When implementing the feedback from derpy I looked through the code base to see if there were any loops that called `Cargo::Remove` and I missed the one in Ship where a dying ship jettisons its cargo. This was risky anyways tbh and could have been a bug in the future anyways even without that loop. 
This reverts that PR and uses the original fix I had for the issue in question, namely ignoring outfits with no count when calculating the fine.
> Fix crash when dying ships jettison their cargo.

- data/human/culture conversations.txt
Fix typo in culture conversations. 
I haven't tested this, but it seems pretty straightforward to me. I'm pretty sure this is preventing this conversation from ever occurring.
> Fix attribute typo

- data/remnant/remnant jobs.txt
**Bugfix:** This PR addresses issue #6560 
If the Ember Threshold was a little more remote (as it is in the map rework) then this distance is good, but until then I think it better to keep this rescue mission a bit closer to the wormhole. Basically, I'd like this mission to cover all the uninhabited areas but not including any of the inhabited systems.
In the meantime, I'd like to make this just a little more focused. (and, again, once the map rework is done, if it is implemented, this corner has a larger collection of uninhabited systems (It goes up to 3 or even 4 jumps to Tania or Delta), so a larger radius of it would be good.)
n/a
n/a
> [Fix]Remnant: Reducing the search area for Remnant Rescue 5

- source/Engine.cpp
- source/PlanetLabel.cpp
**Bugfix:** This PR addresses https://discord.com/channels/251118043411775489/266345072554016768/978383077116084244
The code that checks if planet labels will overlap with other StellarObjects in the system wasn't properly accounting for zoom.
This should now be fixed.
Before:
After:
Take off and zoom out a bunch.
[test test - Copy.txt](https://github.com/endless-sky/endless-sky/files/8757852/test.test.-.Copy.txt)
> fix(UI): Ensure planet label overlap check works correctly at all zoom levels

- data/harvesting.txt
- source/Minable.cpp
- source/Minable.h
Currently minables all have the same hull value (minables of the same type that is). This PR introduces a new attribute, `"random hull"`, to specify by how much the hull of a minable should be increased randomly.
I have also updated the minables in the game to have 20% random hull. 
```
minable "silver"
sprite "asteroid/silver/spin"
hull 2000
"random hull" 400  # <-- this
payload "Silver" 20
explode "smoke" 20
explode "bolide" 20
explode "asteroid crunch small"
```
When to a system with minables and verified that they all have randomly generated hull values.
N/A.
> feat: Make minables have different hull values.

- data/remnant/remnant 2 cognizance.txt
**Bugfix:** This PR addresses issue reported by matthew.najmon on the Discord
This is just a reminder mission to send the player to see Torza, which will remain active until Torza can actually be met. This adds the "landing" attribute so that it triggers properly instead of relying on them going to the spaceport.
Thanks for spotting this behavior!
Note: The mission currently triggers just fine (and invisibly) if someone went to the spaceport. Since most veteran players go to the spaceport regularly when doing campaign missions, I suspect most of us just got the mission that way and didn't realize it.
> [Fix] Remnant: Give Cog 27 the landing attribute

- data/remnant/remnant.txt
**Bugfix:** This PR addresses the issue that one of the Remnant hails mentions cloaking devices.
One of their hails mentions how thankful they are that they had a cloaking device. This is practically saying they have cloaking outfits, which they don't. 
So, this fix replaces "a cloaking device along" with "cloaking functionality". It works in all the phrases, is more accurate, doesn't lead people to expect to find cloaking outfits somewhere, and thus improves the phrases.
> [Fix]Remnant: Replacing reference to cloaking device

- data/remnant/remnant events.txt
For some reason the Republic system Porrima is included in the event "remnant: cognizance 1 systems available" which simply removes attribute "inaccessible".
This commit removes that line.
Maybe -- that was supposed to be Postverta instead? It's the next planet alphabetically after Porrima. Seems to be a little mistake there. So, unless Postverta should *not* be included as a target system in various remnant jobs that require 'not attribute "inaccessible"', this event should probably include it. Because as it stands, Postverta is not getting included those missions.
> Remove reference to Republic system Porrima in Remnant event

- source/LoadPanel.cpp
This fix avoids situations where the file name is used and the file name and pilot name don't match up.
Loaded a savegame with has mis-matching file and pilot names, the game now accepts the pilot name and rejects the file name (if it differs from the pilot name)
This save file can be used to verify the bugfix. The bug will occur when using f2e933b17f0f66afd749e35233e83174abcf7698, and will not occur when using this branch's build.
This save file (with mis-matching file and pilot names) can be used: [recent.txt](https://github.com/endless-sky/endless-sky/files/8791531/recent.txt)
Additionally the delete prompt also correctly displays the pilot name.
Note that the file name is `recent.txt` and the pilot name `Blockade Runner`
> Use pilot name to test deletion

- data/human/marauders.txt
- data/persons.txt
**Bugfix:**
This PR Replaces 3 occurrences of "Afterburner" with "Volcano Afterburner" to match the current naming scheme as some ships:
Marauder Raven
Marauder Bounder
Modified Osprey
Were not updated to match the new name for the Volcano Afterburner
> Changed obsolete references of the afterburner

- data/remnant/remnant 2 cognizance.txt
**Content (Missions )**
The mission 'First Flight' aka Cognizance 23 mentions a ship in Farinus, and has a waypoint in Farinus, but the 'npc kill' ship there jumps away. It should probably have personality 'staying' instead of 'waiting'
[Test Cognizance 23.txt](https://github.com/endless-sky/endless-sky/files/8829467/Test.Cognizance.23.txt)
Takes a few steps and there's a few other missions in the way but it's a small change.
> This npc kill ship should stay, not 'wait'

- data/remnant/remnant 1 introduction.txt
On one of my save files I noticed that there was a Korath fleet following me into Human space. I found that pretty funny.
The Korath fleet in Remnant Defense 1 attack the Remnant planet and as such they should stay in that system.
> Add 'staying' to the Korath fleet in Remnant Defense 1.

- data/wanderer/wanderer news.txt
You only learn the name of the Wanderers when you get the Hai translator, but news that explicitly name the Wanderers can be encounter before that point. This PR duplicates the wordless news items and removes any direct mention of Wanderers.
> Remove mentions of Wanderers in news before you learn their language

- EndlessSky.xcodeproj/project.pbxproj
- EndlessSkyLib.cbp
- EndlessSkyTests.cbp
- source/Conversation.cpp
- source/Conversation.h
- source/ExclusiveItem.h
- source/MissionAction.cpp
- source/MissionAction.h
- source/NPC.cpp
- source/NPC.h
- source/Phrase.cpp
- source/Phrase.h
- source/StartConditions.cpp
- source/StartConditions.h
- tests/unit/src/test_exclusiveItem.cpp
**Feature:** This PR implements yet another piece broken off of #4704, otherwise known as the PR that keeps on giving.
This PR adds a new template class, the ExclusiveItem ("exclusive" as in "mutually exclusive" [shorten to Mutex? MutexItem?], previously named the UnionItem). An ExclusiveItem is an object that holds either a pointer to or an instance of some other class. The usefulness of this object comes from the fact that there are various objects in the game that can be either defined as root objects or defined in place as a child of some other object. Examples include but are not limited to conversations (defined as a root or a child of a mission action), dialogs (defined as a root or a child of a mission action or NPC), and fleets (defined as a root or a child of an NPC). The way …
> Add ExclusiveItem class

- endless-sky.desktop
This key is intended to be used for cases like a music player with a
branded name where you want the user to be able to tell what it is (e.g.
"Music Player"). This doesn't really apply to games; the Comment field
which shows a longer description is more appropriate. On Linux, launcher
menu implementations often prefer the GenericName key over the Comment
when both are present. So let's remove the GenericName because the
Comment text is better and more appropriate.
> Remove GenericName key from Linux desktop file

- source/Engine.cpp
- source/Engine.h
When zooming in and out the `zoom` variable is changed right in the middle of a frame. This means that objects are drawn at different zoom levels depending on if they appeared before or after when the `zoom` variable gets updated. This mainly affects things like status overlays and planet labels.
This PR fixes this issue by storing the zoom change in another variable that gets updated at the start of a frame.
The reason for why `zoom` isn't updated with `nextZoom` inside `CalculateStep` is because that would cause a race condition between `Draw` and `CalculateStep`.
Quickly zoomed in and out and paying attention to the planet labels and the status overlays. With this PR they are consistent while without they seems to be one frame too slow.
> fix(mechanics): Draw overlays with the correct zoom level

- data/coalition/coalition missions.txt
`<origin>` is the substitution text key for the source planet, in "Coalition: Council of Ahr: Ablomab" there was <source>
> Fix mission text <source> : <origin>

- .winmake
**Bugfix:**
Added some quotes in the .winmake as paths in windows often have spaces so the command fails. Python(if installed globally) is stored normally in the "C:\Program Files\" directory which has spaces in the name so adding quotes fixes this. 
I don't think adding quotes should introduce some new errors.
> Added some quotes in the .winmake

- source/ImageBuffer.cpp
**Bugfix:** This PR fixes #6938 
The image files in #6938 are RGB pngs, i.e. pngs without an alpha channel. ES requires images to be RGBA when loading them, so the fix is to add a alpha channel to such pngs before reading them. This is done for every other type of png already (except rgb only). This PR adds the conversion needed for the last type of png not handled.
I use the recommended way to convert them to RGBA from the [manual](http://www.libpng.org/pub/png/libpng-1.2.5-manual.html) (search for "This code expands them into 4 or 8 bytes for windowing systems").
The image files from #6938 are correctly displayed in the outfitter with this PR.
[Squished Sprite.txt](https://github.com/endless-sky/endless-sky/files/8886392/Squished.Sprite.txt) (you need the plugin from #6938). Open the …
> Convert RGB pngs to RGBA before reading.

- data/kahet/kahet missions.txt
- data/remnant/remnant 2 cognizance.txt
**Bugfix:** This PR addresses issue identified in 6901
Swaps several conversation choices in Remnant and Ka'het missions that were in the third person.
https://github.com/endless-sky/endless-sky/pull/6901
To-do:
Look through the remainder of the Remnant missions to see if there's any others that I have missed.
> [Fix]Remnant: Swapping to first person actions in choices

- .github/workflows/cd.yaml
- .github/workflows/cd_release.yaml
- .github/workflows/ci.yml
- EndlessSky.xcodeproj/project.pbxproj
- utils/build_custom_libmad.sh
- utils/fetch_sdl2_framework.sh
- utils/mad-compat.rb
**Bugfix:** This PR addresses issue #6520
Running on macOS 10.13 and earlier would crash when landing on a base with background audio (the only instance where MP3 decoding is used) with "Symbol not found: ____chkstk_darwin". This is a [common error](https://github.com/nodegui/nodegui/issues/391) associated with using libraries on systems [older than they were compiled for](https://developer.apple.com/forums/thread/680395), and the fix is to set MACOSX_DEPLOYMENT_TARGET when compiling the library. This also highlights the shortcomings of relying on Homebrew to create libraries for distribution, but since libmad doesn't offer binaries of its own for download, using a customized formula for it is our best bet.
Ran this fork's CD build with the affected savefile on macOS 10.13 and it didn't …
> macOS: fix crash with background audio on older systems

- data/coalition/coalition ships.txt
**Content (Variant Balance Tweak?)**
Heliarch Hunters are meant to be ships that get in and out of systems quickly, their naturally high fuel capacity being so that they can patrol a lot of systems without refuelling due to their Scram Drive's higher fuel usage.
It turns out though that I forgot to have every variant of the Heliarch Hunter other than Stock actually use SDs. They just had regular HDs.
This PR just changes the loadouts of the other variants of the Heliarch Hunter so that they can fit a SD instead of the HD they previously had.
> [Variants Tweak] Make Heliarch Hunter variants use Scram Drives

- data/remnant/remnant ships.txt
**Bugfix:**
Some remnant albatross variants have 2 keystones installed instead of the usual 1 (which would be in keeping with the remnant not wasting resources). This PR removes the duplicate keystones being added to the ships.
[Reported on discord by @Mutant: https://discord.com/channels/251118043411775489/688532441324847150/988503845992820757](https://discord.com/channels/251118043411775489/688532441324847150/988503845992820757)
> Fix double stones on albatross variants

- data/remnant/remnant commodities.txt
No, you didn't see anything.
There shouldn't be any need to separate the different commodities in "remnant commodities.txt" into several trade nodes, as evidenced in the main trade.txt.
> Remove unnecessary lines in "remnant commodities.txt"

- .github/path-filters.yml
- .github/workflows/compute-changes.yml
- .github/workflows/projects_check.yml
- copyright
- utils/check_copyright.py
This PR adds a new CI checker that validates the copyright file using the official python-debian package. It only checks whether the copyright file is well-formed and nothing else.
In the future we can easily extend this script to check whether a file has no copyright, but currently all files are under MZ's copyright by default, even if they're not from him. That would mean manually specifying every asset that MZ created, instead of relying on the wildcard.
I intentionally missed an error in the copyright file to check whether the CI runs and catches the error.
> Add a validation CI for the copyright file

- .github/workflows/ci.yml
- source/Audio.cpp
- source/Music.cpp
- source/Music.h
While collaborating on adding music to Endless Sky I am hitting up against quirks in the engine.  This is a small bugfix to address a big issue.  However, there will likely be lots of audio-based fixes around music to come as part of this collaboration.
I am developing the plugin "Sounds of Endless Sky" which includes collaboration music by composer @Anthrophantasmus.
https://github.com/samrocketman/sounds-of-endless-sky
If a track is playing and a new track of the same name is requested, then it will continue playing the track instead of resetting playback to the beginning.
Bug behavior
------------
Music gets reset even if the same track is playing.  The track restarts from the beginning every time it resets.
- Jumping systems resets music.
- Pressing ESC resets music.
- Landing on …
> Bugfix: Smooth music playback

- .github/workflows/cd.yaml
- .github/workflows/ci.yml
Recently Github updated its Windows CI image which updated the provided mingw version from 8 to 11. This caused all of the Windows CI failures recently. At first I read that it could be due to caching problems, but I managed to reproduce the problem on my Windows machine and as it turns out the paths to the required DLLs changed.
So this PR simply fixes the paths used by CD/CI. I didn't update the paths for AppVeyor because AppVeyor still uses mingw 8 (and below) and doesn't even provide mingw 11.
Hopefully every Windows action succeeds. edit: yay!
> Fix Windows Actions caused by recent image update.

- data/remnant/remnant 2 cognizance.txt
I'm removing the cargo space requirement and adding to the mission description that they need to pick up 58 tons of material. Not quite as obvious as reserving the space, but hopefully people actually read it.
Sort of a problematic situation: The reserved cargo was appropriate for (and expects) that the player is switching to the Peregrine that they are given during this mission, so the amount of cargo their current ship has is actually irrelevant and should not block the mission. But there's no way to tell the mission that it needs to reserve that cargo space at the *end* of the "on accept" instead of at the start of the "on offer."
Thanks to Rocky196884 on Discord, among others, for reporting this bug.
n/a
n/a
> fix(content): Remnant: Fixing a confusing block message in Cognizance 32

- data/human/free worlds start.txt
Expand the prose in `FW Hope Recon 1C` to imply that the surrendering Gunboat crew will join the Oathkeepers.
Test by removing the `to offer` conditions from the mission, starting a new game, and flying to Hope.
I loaded the conversation in-game and verified the new condition was saved.
N/A
> feat(content): In the FW Hope Recon 1C surrender case, make the Gunboat crew join the Oathkeepers

- data/map.txt
**Content (Artwork)**
This PR fixes the overlapping of the new Coalition Megastructures and other Coalition Planets in their respective systems (Ablodab and Silver Bell).
~~## Save File~~
~~This save file can be used to play through the new mission content:~~
~~{{attach a save file that allows people to easily test your added mission content or see your new in-game art}}~~
~~## Artwork Checklist~~
~~- [ ] I updated the copyright attributions, or decline to claim copyright of any assets produced or modified~~
~~- [ ] I created a PR to the [endless-sky-assets repo](https://github.com/EndlessSkyCommunity/endless-sky-assets) with the necessary image, blend, and texture assets: {{insert PR link}}~~
~~- [ ] I created a PR to the [endless-sky-high-dpi …
> [Content] Coalition Megastructures Overlap Fix

- source/main.cpp
**Feature:** This PR implements a debugging feature for the integration tests framework.
This PR add 3 seconds delay for UI-actions when debugging tests:
If UI actions only take 1/60th of a second, then that is too fast for people that are debugging to see what actually happens. If UI actions take 3 seconds, then that seems to be slow enough to make things visible, and fast enough not to make the test feel slow.
N/A
To be used when manually running an integration test with the `--debug` flag.
Manually ran some integration tests for #6975
No impact expected; the delay is only used during active testing, and overhead of a single integer operation should be minimal.
> feat: Add 3 seconds delay for UI-actions when debugging tests.

- source/FrameTimer.cpp
Due to the recent update to MinGW 11, it turns out that the Winpthread implementation that MinGW uses for the C++11 threading library sleeps too long. This seems to be a "problem" since MinGW 9 with the only solution being to use the native Windows sleep function instead of the Winpthread implementation.
Sleeping too long is technically valid behavior, but this meant that the game wasn't running at 60fps. So this PR #ifdef the sleeping call to use the Windows Sleep function.
Used a frame viewer to verify that this PR fixes the framerate drops that occur using the MinGW 11 executable from Github Actions.
> Use Windows Sleep for framerate control

- data/human/human missions.txt
It is currently possible that the 'Laborer' mission can have a destination outside of human space, which in the context of the mission does not make sense. I added a destination filter to avoid this.
> Fix "Laborer" mission (AKA "Out of Work").

- source/AI.cpp
Shift-R will now select the nearest ship, friendly or hostile, even if hostiles are in the system. 
That's what the preferences setting says Shift-R does: "Select nearest ship". It currently prefers hostiles instead of selecting whatever ship is nearest. That's not what the preferences window or the comments says. If you wanted to select a hostile, that's what normal R does. So why does shift-R ignore friendlies when hostiles are nearby? You specifically held shift to select friendlies.
Now, this is very old code, so I wonder what the intent is as this has been this way forever. But either this, or the text explaining Shift-R should change. Because shift-TALK doesn't prefer ships - it just talks to the planet. So this should select the closest ship, friendly or not.
> fix(mechanics): Shift-R to select the nearest ship, even if hostiles are around

- source/Files.cpp
- source/LoadPanel.cpp
- source/Music.cpp
- source/PlayerInfo.cpp
- source/PlayerInfoPanel.cpp
- source/Ship.cpp
- source/main.cpp
This PR is simply a collection of fixes found by MSVC:
- No need to include Posix headers under Windows, MinGW already includes them.
- Use safe functions (`_s`) on Windows instead of unsafe ones.
- Use `partition` instead of abusing `sort`.
- Use a boolean for tick tock-ing instead of an int.
- Cast size_t to int before applying unary `-`.
- Don't call `.get` on a temporary shared_ptr.
- ~~Use a positive lambda for proper conversion between two lambdas~~ reported as a bug to MS
> Various fixes to the code found by MSVC

- data/map.txt
**Content (Map data security thing)**
Currently, every planet and station in the Coalition (with the exception of the recently added Guardian Array Sapphire) have no specified `security` value, thus defaulting to 0.25.
In order to give the planets there some more variety, and also to try and reflect Heliarch attention to the worlds, this PR adds `security` values to the majority of the Coalition worlds, most of them being increased from the default 0.25, but there are also some that have been lowered.
> Add security values to most Coalition planets.

- data/coalition/coalition missions.txt
**Bugfix:** In the Coalition's Expeditions Past mission chain, Mission 9's on visit doesn't make a whole lot of sense. You're not supposed to land on Hopper again, so being told that your escort with the passenger hasn't arrived yet is very odd. This happened because I just autopilot copy-pasted an on visit from another mission.
This issue was brought up by auldr on the Discord.
This PR changes the on visit so that instead of saying the escort with the passenger isn't in the system, it tells you that you haven't completed the goal of the mission yet (finding the last pylon), and restates the route one should try to set to look for it.
> Coalition Bugfix: Change an on-visit to make more sense

- data/human/power.txt
- data/wanderer/wanderer outfits.txt
**Balance?**
Significantly increase the energy capacities of the small and large Biochemical Cells.
3k -> 7.5k on the small.
7k -> 30k on the large.
Also, reduce the price of the nGVF-AA Fuel Cell from 40k to 35k because it seemed a little too close to the nGVF-BB Fuel Cell and raising the price on that would put it too close to the cell above and just lead to inflation of everything.
~~25% increase in energy and heat generation for the two Biochemical Cells, and increase the energy capacity of the large Biochemical Cell so it has slightly higher energy capacity/ton than the small, instead of significantly lower as it was before.
Buffs were chosen by @Amazinite in response to my suggestion that the proposed Hailstone fighters would need Red Sun Reactors because Small Biochemical Cells …
> Balance: Buff Biochemical Cells

- data/human/free worlds start.txt
This PR adds an additional invisible mission as well as one additional line of dialogue when transporting the Senator to Bourne as part of FW Senate 1B to address players who have a jump drive and are able to meet the deadline imposed by the Senator in order to resolve issue #6108
This save file will place you on Zug with two ships, one equipped with a hyperdrive, one with a jump drive. Using the JD equipped ship will allow you to see the new dialogue, using the HD equipped ship will show the old dialogue:
[Huygens Fix~Example Save.txt](https://github.com/endless-sky/endless-sky/files/9038099/Huygens.Fix.Example.Save.txt)
Old Dialogue:
New Dialogue (If delivered fast enough)
Started the mission on Dec 3rd in-game and made sure that the new dialogue would show if the Senator was delivered …
> Content: Alternate Dialogue in "FW Senate 1B" if player is fast enough.

- data/human/hails.txt
Could roll a type of friendly pirate hail with no space, which this fixes.
> fix(typo): Add space in pirate hail

- data/coalition/coalition missions.txt
**Bugfix:** In the Coalition's Long Lost Property missions, mission 2 is meant to serve as a marker to Shaula/Greenrock, in case one lands there but doesn't meet the credits requirement to bribe the junkyard owner. If you have accepted mission 3, that means you've bribed him, thus mission 2 is no longer needed.
However, the current check only sees if the mission is active to fail mission 2. If you never land between accepting mission 3, and completing mission 3, mission 2 won't get cleared out.
This just makes it so that mission 2's `to fail` has an `or` that checks not only for mission 3 being active, but also if mission 3 has been completed. If one lands between accepting mission 3 and completing it, then the `active` check will clear mission 2 out. If not, then …
> Coalition Bugfix: Long Lost Property to fail condition update

- data/coalition/coalition missions.txt
**Bugfix:** The "Alpha Encounter" mission in Coalition space has for one of its source filters `not attributes "station"`, when `"station"` isn't an attribute found in any Coalition worlds (the stations there use the separate `"coalition station"` attribute), so it's effectively not doing anything.
So, it could offer in one of the Coalition stations, which isn't intended since it could lead to some odd imagery on how the stations are structured, basically it's just simpler to imagine the events occurring on a regular planet.
This just changes the attribute filter in the mission from `not attributes "station"` to `not attributes "coalition station"`.
> Coalition Bugfix: Update source filter for Alpha Encounter

- source/Engine.cpp
- source/PlanetLabel.cpp
**Bugfix:** This PR fixes #6603
Planet labels were prematurely culled due to a typo/mismatch in the engine. In https://github.com/endless-sky/endless-sky/blob/1075dcb202eacc8655f257bb2a2f0c98b5bf5d07/source/Engine.cpp#L643, the label is culled at 400 pixels of distance, despite the number being 600. The label fades out at 600 pixels, and using 800 in that expression makes it so the labels are culled properly at exactly 600 pixels.
Now a little disclaimer here: as of now, I have _**absolutely no idea**_ about what causes this issue. Based on the original code, the previous author didn't know either. For some reason, there are extra 200 pixels there. If you are more familiar with the code base please, _please_ have a look at this black magic. I verified with console messages, the actual …
> Fix planet label culling

- source/Minable.cpp
This PR fixes a crash if you destroyed a minable with a negative payload:
```
minable iron
payload Iron -50
```
Having a negative payload is now equivalent to it being 0 (i.e. no drop).
Modified the iron minable as written above. Without this PR the game crashes when breaking the minable.
> Fix crash for minables with a negative payload.

- data/hai/hai jobs.txt
- data/hai/hai missions.txt
- data/sheragi/archaeology missions.txt
- data/wanderer/wanderers start.txt
**Bugfix:** This PR addresses the comment on the Unfettered campaign PR: https://github.com/endless-sky/endless-sky/pull/6416#issuecomment-1192470104
This was an oversight when adding new factions, and when adding the reputation changes to the jobs.
The jobs and missions only gave additional reputation for the main Hai faction, which means that you could be at war with the Hai (Whormhole Access), and not the Hai. But then whormhole access Hai aren't meant to have a different reputation with you than the main gov, they're just there when Hai missions take them trough the whormhole.
Then it made little sense that doing missions like transporting goods and peoples did not increase your reputation with the merchant Hai, as they're precisely the ones that would care the most about that.
The …
> Fix(oversight): made reputation changes from missions affect all Hai factions

- data/dialog phrases.txt
- data/hai/hai jobs.txt
**Bugfix:** This PR addresses an incorrect dialog for the Unfettered tributes.
When you had not yet been to the stopover and arrived at the destination it would say your escort has not entered the system yet. It was reported here: https://github.com/endless-sky/endless-sky/pull/6416#issuecomment-1193354648
I created a new generic dialog for missions that are cargo with a stopover, and made the unfettered tribute missions use it. I preferred doing it in a generic way, to allow for more missions to use that same dialog. (the Unfettered campaign PR for instance will use it a lot)
I manually checked every single mission with the generic cargo dialog, only the unfettered tribute missions have a stopover, so only those will use it for now.
The fact this builds properly shows that the name of …
> Fix(dialog): unfettered tribute missions use the right "on visit" dialog

- endless-sky.desktop
Terminal is a non-required key, and False is the default value if it's
not set, so this line is a no-op and can be removed with no consequences.
> docs: remove Terminal=false line from desktop file

- source/ShopPanel.h
This PR simply increases the outfit name max limit by 3 units, which means that the Heliarch H2H weapon can be displayed without dots:
Before:
After:
> Increase the outfit name limit by 3 units

- data/categories.txt
- data/coalition/coalition ships.txt
- data/hai/hai ships.txt
- data/human/ships.txt
- data/korath/korath ships.txt
- data/remnant/remnant ships.txt
- data/wanderer/wanderer ships.txt
**Content (Revision)**
Current ship class categories are... inadequate. Most of the recent debate has covered lumping everything of a certain size into one category such as Super Heavy (unpopular), and the suitability of categories for certain ships such as the Raider (most recently).
This is an attempt to reconcile those problems in a way that enhances the existing framework instead of either tacking onto it or shoehorning it.
To that end, this introduces two new categories and shuffles a few ships around.
- Transport: This is a word that is used widely to refer to the movement of both goods and people, including people who may be armed. The only really consistent thing about the use of this word both in games and IRL is that its associated with ships that _lack the meaningful capacity …
> feat(content): Transport Category Rework

- source/PlayerInfo.cpp
A (much simpler) companion to #7057, this PR will write any plugins a player has installed to the end of their save file, if they have any. Between this and recording the game version, it should be much easier to debug any issues a pilot is having from the save file alone.
> feat(saving): Write installed plugins to save file

- data/human/human missions.txt
Thanks to a tip-off from Kroniicopter on the Discord server, this PR fixes many issues with the Saving Artifacts chain:
- Sets the original `to offer` check for `event: fw conservatory founded` instead of just `fw conservatory founded`, which made the chain impossible to start before.
- Added display names to each mission. In-game missions shouldn't show "Mission Name #", instead using a broad chain name, or more specific per-mission names.
- Rearranged an `accept`, in mission 1, which also prevented the mission from being picked up.
- Removed the branch condition checking combat rating. To start this mission, the player will have needed to get midway through the FW campaign, and either A) Bribe their way through hostile Republic space to get these missions, or B) Drive off the Pug. …
> fix(mission): Clean up Saving Artifacts mission chain

- data/human/human missions.txt
**Bugfix:**
The description of Saving Artifacts 2 contains \<source\> (which is meaningless) instead of \<origin\>. This PR fixes that.
> fix(mission): replace <source> with <origin> in Saving Artifacts 2

- data/map.txt
In #6378 I standardized the habitable ranges of all systems in the game based off of the stars within them. The ranges used for all the stars are listed in the description of that PR. I've noted though how with the addition of all these new stars from #5825 which are must larger and brighter than what we use to have and the values chosen for them from #6378, there are a number of stars where adding even one of them pushes the habitable range for the system beyond the edge of the system fence, making using those stars for inhabited systems difficult. Raven has suggested reworking the values so that more of the larger stars can feasibly be used in inhabited systems.
This PR makes the following changes. I've included some unchanged stars for the sake …
> Restandardize habitable range of larger/brighter stars

- data/tooltips.txt
- source/OutfitInfoDisplay.cpp
**Feature/Bugfix**
Weapons such as the Moonbeams or Slicers fire in bursts, but fire continuously (every frame) during those bursts.
This results in 'per shot' stats being displayed as well as a numerical shots per second value.
This PR changes OutfitInfoDisplay so weapons with a burst reload of 1 or less and a burst count of more than 1 and `TotalLifetime()`s of exactly 1 will be marked as `continuous (#%)` and won't display 'per shot' stats.
The `#` value is an integer percentage of up time (produced with `Format::Number(lround(burstReload * 100. / reload))`).
~~The Gatling Gun is also affected. Given it's characteristics, this may not be appropriate.~~
Also, the game will only treat weapons with a reload of 1 or less as continuous if the `TotalLifetime()` is exactly 1, so a non-laser …
> Adjust display of bursty continuous weapons

- data/interfaces.txt
Someone commented on this and now it annoys me every time I see it.
Before:
After:
> Content(UI): Move the title on the main menu up

- data/human/syndicate jobs.txt
This PR adds a deadline to the Corporate Espionage Syndicate job, and tweaks the mission description. The way these jobs are meant to play out is being prepared to immediately intercept your target ship and scan them right after you take off. If you don't find them in 5-10 seconds, the NPC can and will jump *anywhere* in the galaxy, making it nearly impossible to find them. Adding a deadline makes sure a player can't fruitlessly chase after the target, and that it won't clog up the active mission list.
If we get the capability in the future to limit the movement of NPCs to certain systems, and can persistently mark those areas, that can let the player hold onto these missions for a longer time.
> feat(content): Add deadline to Corporate Espionage job

- tests/unit/src/test_account.cpp
**Fix:** This PR fixes the missing copyright header in [test_account.cpp](https://github.com/endless-sky/endless-sky/blob/master/tests/unit/src/test_account.cpp)
The file was created by @petervdmeer in #6139. The header was never included, even though all other test files have these headers. I think unless @petervdmeer explicitly tells us not to have this header, we should probably include it. (We should wait for their approval of course.)
> fix: Missing copyright header in test_account.cpp

- data/human/boarding missions.txt
- data/human/deep missions.txt
- Made the verb tenses consistent in one spot in the boarding missions file
- Changed an "on to" into an "onto" in the deep missions file
- Changed an "in to" into an "into"
- "lead" -> "led" to match tense
- "so called" -> "so-called"
- "mean time" -> "meantime"
- Removed a duplicate "that"
- Moved a misplaced comma
- "get recorded voice message" -> "get a recorded voice message"
- "You are brought to large research complex" -> "You are brought to a large research complex"
> Miscellaneous grammar in data/human/

- data/human/deep missions.txt
Since in #7156 I raised the point that “onto” should stay “on to” because it’s a figurative phrase where you don’t actually put things “on” to the object in question.
And that was acknowledged by @TheMarksman-ES but not changed before being approved.
And that *based on the examples in Zitchas link* and also other more detailed explanations ("loaded on" is in fact the verb section as the "to" part remains in its role as a preposition https://writingexplained.org/onto-vs-on-to-difference) it should be "on to".
I'm therefore opening this up since the other one was merged.
> Fix from #7156

- source/AI.cpp
The `CanPursue` check is applied in target choosing to all ships, including ones in the player's fleet. The fleet ships have no trouble following the player outside of the fence but having `CanPursue` return false in those cases make the ships just sit idly if enemies do follow the player outside of the fence for some reason.
A further refinement could be to make fleet ships follow a fence that's centered around the player, instead.
The easiest way to reproduce the issue is to fly outside of the fence and demand tribute from a planet. With this patch, the ships in the fleet target and attack the defending ships.
I wouldn't expect this change to affect other behavior.
Omitted, if you don't mind. Any save with enough combat rating to enable tributes will do. The bug will occur when using …
> fix(AI): Make owned ships ignore fence.

- source/Personality.cpp
- source/Personality.h
- source/Planet.cpp
**Bugfix**
Planetary defense fleets' carried ships don't currently set any specific personality. Specifically they lack the unconstrained flag, which makes them stick close to the carriers but if they reach the player outside of the fence, they won't target them. Since the carriers have it, they may very well end up there.
I tried it a bit and I think it made most sense to only enable unconstrained for them. The defeat check doesn't check for carried ships so having them blink as targets might be misleading. I don't think it'd be worth it to change the defeat check, if somehow a couple of fighters would be only left then it's pretty plausible for them to surrender.
I messed with some republic planets, which most often have carriers and cruisers. With this change their fighters and drones …
> fix(AI): Use unconstrained personality for defense fleet carried ships

- data/wanderer/wanderers start.txt
Currently, the pre-Hai version of Wanderers: First Contact only checks to see if (regular) Hai first contact was made. This PR makes that mission also check Unfettered first contact.
> Stop Wanderers: First Contact (Pre Hai) from triggering after visiting the Unfettered

- data/human/human missions.txt
There was an unnecessary `landing` line in Saving Artifacts 4 that was pointed out to me on Discord. This PR deletes that line.
> Remove extra 'landing' line in Saving Artifacts mission chain

- data/remnant/remnant 2 side missions.txt
**Bugfix:**
Currently, the location filter on the source of the recently added Teciimach mission only requires a planet with either of the attributes `"shipyard"` or `"remnant"`, meaning it can offer on a non-Remnant world with a shipyard, or a Remnant world with no shipyard.
This change means it will require both attributes, so it'll only offer on Remnant worlds with shipyards.
As is, I can receive the mission on Zug.
> fix(content): Teciimach mission source

- data/remnant/remnant ships.txt
Sorry, @Amazinite.
Replaces the Crystal Capacitor on the Smew with some built in energy capacity (and a little built in ion resistance) and reduces the outfit space by the size of the Crystal Capacitor.
> Quick Smew change

- data/governments.txt
Not sure which category this falls under... I'm using the content template because that's the closest thing there is.
Changed the colours of Hai and Unfettered Hai so that they're no longer quite so similar.
Closes https://github.com/endless-sky/endless-sky/issues/7186.
This save file can be used to view the map:
[Atlantian Cruise.txt](https://github.com/endless-sky/endless-sky/files/9481449/Atlantian.Cruise.txt)
N/A
Current Colours:
New Colours:
> Change Hai colours

- data/remnant/remnant events.txt
- data/remnant/remnant ships.txt
- data/remnant/remnant.txt
This PR implements the recently merged Smew:
- Adds to the shipyard
- Adds a miner (with a thrasher), a support (with an inhibitor), and a runabout (with an hd) variants.
- Adds all three of these to Remnant fleets in a few instances.
- Including one Ibis+2 miners+4 terns variant for mining operations.
> Feat(content): Remnant: Smew into the shipyard and fleets

- data/human/human missions.txt
Fixes a misspelling of `misspelt` in Saving Artifacts. (Ha ha.)
> Fixing typos in Saving Artifacts

- data/human/human missions.txt
Razer is a gaming hardware company, not a thing you shave with or a description of sharpness. Given that the context is a crazy person's weird poetry, it's possible this was an intentional typo, but it still stands out to me and seems like an error even if it was intentional, and the correction is correct too, so let's assume it was an unintentional typo and correct it.
> fix(content) razer -> razor

- data/human/human missions.txt
The `<source>` tag here isn't evaluated, and the ordering is a bit odd anyway. Let's fix this by replacing it with static text and re-arranging some lines.
Fixes this issue:
> fix(content): fix inappropriate <source> tag

- data/korath/korath variants.txt
- data/remnant/remnant jobs.txt
**Bugfix:** This PR addresses two issues
1. The target ship wanders aimlessly, and can go a very long ways away, making it almost impossible to find. (Thanks to warp-core for highlighting this to me)
2. While outfit expansions are eminently useful for players and NPCs who are making quick changes to ships and/or one-off ships, they do not make sense for factions that have ready access to shipyards and routinely make use of a specific configuration. (Thanks to Ravenshining for bringing this to my attention)
The fixes:
1. Giving the target ship the "staying" personality so that it doesn't wander. (please note that I would, in fact, like it to wander, but I would prefer to have it stay within the Ember Waste and/or within 2 jumps of its starting system. So having an NPC restriction system …
> fix(content): Remnant "Rano'erek (Ground Assault)" bounty and variant fix.

- data/korath/korath ships.txt
- data/remnant/remnant 2 cognizance.txt
@warp-core  correctly pointed out in #7218 that the the plural -zs for the 'olofez is inappropriate.  This should fix this minor oversight.
Normally I don't like opening PRs this small so if there's any other belated fixes I could add them here, too.
> minor(grammar) z plurals end in es

- data/wanderer/wanderers start.txt
**Content Fix (Keyword Change Fix Thingy)**
The Alt Start branch for the Pond Strider missions have an `origin` keyword, when you actually get this mission anywhere in Hai space. I got it on Frostmark while trading commodities. Leads to an awkward/misleading ending:
This just changes the keyword from `origin` to `planet`, as the destination planet for this alt start mission is Hai-home.
> Pond Strider Alt Start origin -> planet

- data/map.txt
**Bugfix:** This PR addresses the drifting ringworlds solar panels in Coalition space.
You could check the responsible commit yourself, it replaces the `period` of 70 objects from the incorrect 361.516 to the correct 349.820 to match the ringworld objects that are above each of them. I've also combed through the recent typo fixes pushed since this fixed file was made and corrected those so that these changes are the _only_ changes present.
Credit goes to @Amazinite for putting the file together to begin with, I am making a PR of it because otherwise he won't do it- simply pushing directly to master is no longer allowed, and the extra red tape of going through this whole process, like I'm doing now, was prohibitive to him at the time.
> Fix Ringworld Desyncs

- source/BankPanel.cpp
**Bugfix:**
It is possible to have values in the bank panel extend beyond their column and overlap other text.
This PR uses `Format::Credits()` on mortgage principals and mortgage, salary, and maintenance payments.
Ignore the very large mortgage having an obviously incorrect payment, this doesn't do anything about that.
Before:
After:
[World Forger.txt](https://github.com/endless-sky/endless-sky/files/9592857/World.Forger.txt)
> fix(UI): Use Format::Credits for more things in the bank panel

- data/korath/korath variants.txt
**Bugfix**
@DarcyManoel pointed out via Discord that some Korsmanath A'awojs drift upon spawning, and upon further examination that it lacked engines.
This PR adds its missing engines, identical to the other variants.
> fix(variant): Add missing engines to "Korsmanath A'awoj (Special)"

- data/korath/korath weapons.txt
**Feature (BugFix)** 
Fixes the Firestorm Torpedo from having a static animation (4 frames per second, no repeat) to having one similar to the firelight/typhoon effect (6 fps, random start animation). 
This was remains from Nomadic's firestorm effect which just had a "wind-up" glow ~~for some reason~~.
(Also adjusts Firelight data to match.)
I shot at ships and got shot at by ships. 👍
> fix(graphics): Fix Firestorm Animation

- data/human/human missions.txt
(You can open a PR to add or improve a section, if you find them lacking!)
**Content  Missions**
The Dragonriders mission currently uses the substitution <planet> in the mission code when the location referenced is <stopovers>. This makes for confusion reading as it talks about dragons flying through the air of the planet you are on when you take the mission. This mission can only take place on one planet: Skymoot. And, as Skymoot is hard coded in the later text of the mission, I've done the same here. Testing with <stopovers> is a bit clumsy as it lists both the planet and the system.
This was …
> Dragonriders/Karengo Mission: Correct planet references

- endless-sky.exe.manifest
- source/WinApp.rc
- utils/set_version.sh
**Bugfix:** This PR fixes #7133 
This PR embeds an application manifest on Windows, specifying that the game is DPI aware and doesn't need any scaling done by Windows itself.
Set my DPI to 175%. Starting the game with this PR results in a not zoomed-in game.
> feat(scaling): Tell Windows ES is high dpi aware using a manifest file

- data/human/human missions.txt
This PR:
- Increases the amount of time before the reminder triggers from 4 months to 8.
- Adds an option to decline at the start.
> Make "Spaceport Reminder" less annoying

- source/OutfitterPanel.cpp
- source/OutfitterPanel.h
- source/ShopPanel.cpp
- source/ShopPanel.h
In 949760972eb3053173f2c89001b4ab936e29c500, the maximum scroll in the outfitter/shipyard was changed from `nextY + mainScroll - Screen::Height() / 2 - TILE_SIZE / 2 + 40.` to `nextY + mainScroll - Screen::Height() / 2 - TILE_SIZE / 2 + VisiblityCheckboxesSize()`, where `VisiblityCheckboxesSize()` is 0 in the shipyard and 60 in the outfitter. This means the bottom of the shipyard lost 40 pixels of space, leading it to become somewhat cramped. Additionally, the extra space in the outfitter is only enough for outfits to be just above the visibility checkboxes. This PR reduces `VisibilityCheckboxesSize()` from 60 to 30, and adds 40 pixels back onto both the outfitter and shipyard. It also fixes a typo.
Before:
After:
Opened the game and played around on the outfitter/shipyard screen.
N/A
> Add more buffer space to the bottom of the outfitter and shipyard

- data/pug/pug.txt
Fixed the engine flares not being mirrored.
The recent change to the pug ship sprites lead to the T1 ships having their engine flares placed on top of each other producing a single lopsided flare in game as seen below.
This PR rectifies that issue by making sure the flares are properly mirrored.
> (Fix) Pug Flares

- data/deprecated ships.txt
This adds the old Korath ships to a new `deprecated ships.txt` file. The ship stats are the ones just before the rename, but using the new (renamed) outfits instead of the old ones.
This is to maintain compatibility if you use a plugin that relies on the old Korath names. I don't think it's a good idea to break every plugin that uses Korath ships, even if save files are unaffected. However, plugin authors are encouraged to update the references to the new names.
> Add deprecated Korath ships

- credits.txt
Updates the contributor lists to include everybody that has contributed since last time this was updated.
> Update contributor list

- data/remnant/remnant 2 cognizance.txt
- data/remnant/remnant outfits.txt
- data/remnant/remnant.txt
**Bugfix:** This PR addresses issue of Void Sprite Parts not showing up where they're supposed to.
pointed out in: https://github.com/endless-sky/endless-sky/pull/7261
- Creates a Void Sprite Parts outfit (Uses the Mouthparts sprite, since that is, literally, a part of the Void Sprites.
- With a specific outfitter for it (this outfitter is not visible anywhere, but is used to populate fleet cargo)
> fix(content): Remnant - Cognizance - Void Sprite Parts

- source/System.cpp
**Bugfix:**
Currently, the `remove` keyword for `object`s in `system`s will allow targeting a child object but then would potentially remove other objects with the same parent, which is undesired.
Thanks to @Amazinite for help finding this bug.
soon:tm:
> Fix possible bug in new `remove` feature

- data/wanderer/wanderers middle.txt
This isn't really a bug fix, more just "future proofing" in case a potential change to the new `remove` feature for system objects is changed to resolve possible conflicts elsewhere. (I haven't decided on making that change, yet, but if that change is made, it will be better to have this done now.)
Does not change the current behaviour.
> Slight change to Zenith events.

- data/korath/korath weapons.txt
Give it a plural name (`Firestorm Batteries`) so the plural doesn't default to `Firestorm Batterys`.
> fix(content): Missing plural name for Firestorm Battery

- data/human/ships.txt
The mule is classified under the new "Utility" category as of now. However, its description says it's classified as a warship. I tweaked it slightly to say it can be used as a warship rather than it's classified as one to fix this without disrupting anything.
> Mule is no longer a warship

- source/MapDetailPanel.cpp
**Feature:** This PR implements the small feature request from the last comment of the planetary UI issue (https://github.com/endless-sky/endless-sky/issues/7065)
Selecting a planet in the UI on the left selects it in the radar, and selecting it in the radar selects it for the flagship.
This makes it so selecting in the UI also selects it for the flagship.
N/A
Select a planet nicely from the map as you would from the radar.
~~Being on phone I cant test it. But its the exact same code as for radar selection, in the same context. There is no way this fails.~~
Thx to @quyykk for doing some testing
N/A
> Enhancement(UI): select the destination planet from the new map UI

- data/human/free worlds 3 reconciliation.txt
The on visit dialog for this mission references Alondo as your passenger rather than Freya. This PR is a simple name change only.
Not tested due to the simplicity of the change and the complexity of setting up a test pilot for it.
> Corrected passenger name for Pug 4 mission

- source/PrintData.cpp
**Bugfix:**
Thanks to @Hecter94 for pointing this out to me.
It's fairly self explanatory, I'm not sure how I missed these the first time.
> fix tab characters instead of commas in PrintEngineStats

- data/hai/hai missions.txt
- data/human/deep missions.txt
- data/human/human missions.txt
- data/remnant/remnant 2 cognizance.txt
- data/remnant/remnant 2 side missions.txt
- source/NPC.cpp
Changes the `accompany` check to only check for "living" ships being in the players system. To divide `accompany` tag from `save` tag.
> Fix accompany tag

- data/hai/hai ships.txt
**Bugfix:** 
Re-categorize Hai Centipede from Transport to Space Liner as every other high capacity transport (100+ bunks) were all moved to Space Liner recently due to #7059 . It's a little odd the Star Queen with lower bunk is a Space Liner while Hai Centipede isn't. 
This is not considering the oddly very specific specification of Space Liner category in that PR when the very ship it turned into Space Liner itself actually doesn't fit the specification, or to be more specific, this very line `have something like <10% required crew compared to the stock number of passengers` and two of the sampled ship that doesn't fit includes Star Queen (41 req/112 bunks, 38%) and Riptide (47 req/ 223 bunks, 21%). ~~(Or they actually do and I'm just bad at math)~~
None.
Any that have access to Hai …
> Recategorize Hai Centipede to Space Liner

- source/LoadPanel.cpp
We're planning on enabling Steam's auto cloud saves, so that save files can be synced across platforms on Steam. For this Steam generates a file called `steam_autocloud.vdf` inside the saves directory. This PR simply tells the game to ignore a file with that name, instead of showing it as a potential save.
> Skip the Steam auto cloud file when looking for save files

- data/map.txt
For a Paradise Planet, Mainsail looks awfully grey and dull:
This PR changes Mainsail's image from beach7-sfiera to the much nicer looking water13:
The previous user of water13, Inmost Blue, now uses the previously unused water14 instead:
> Change Mainsail's and Inmost Blue's landscape image

- data/kahet/kahet outfits.txt
**Bugfix:** 
The Ka'het Annihilator Turret has no sound associated with it, making it completely silent to fire, as reported by limagb on [Discord.](https://discord.com/channels/251118043411775489/308902312741568512/1028092078619623435)
Unlike the annihilator gun which uses the inhibitor sound effect.
This PR adds the same sound used by the gun to the turret. 
I checked the original PR and saw no mention of the Annihilator turret being silent, so I assume it was not intentionally created this way. 
If it was intentional that the turret does not have a sound effect, and that is desired behaviour, this can be closed.
Verified that without this fix, firing the turret is completely silent. With this fix, the turret makes the same sound as the gun.
> Add Sound to Ka'het Annihilator Turret.

- data/coalition/coalition ships.txt
**Content Tweak (Ship Category Change Thing)**
This PR moves the Saryd Traveler from the Transport category to the Utility category, to have it better fit with its lored description of being a science ship, and the recently added science-y stat `asteroid scan power`.
It also gives it `"atmosphere scan" 100`, as that seems to be something all science ships have, so reinforcing that aspect of it.
> Change Saryd Traveler category to Utility

- data/governments.txt
- data/hai/hai ships.txt
Simply gave pulse rifles by default to hai warships, as agreed with @MasterOfGrey.
This will help in solving the too easy capping of shield beetles, and showing the Hai as somewhat war ready (civilian ships dont have them though)
I only added as much as the ship's required crew to show this is only an emergency stash in case of need.
edit:
I also buffed the Uhai attack by 0.4 and their defence by 0.2 to make them slightly harder to capture and represent their better ability to fight than the hai, trough a lifetime of training. I could have gone further with the buffing but this way its sure it isnt too big of a buff for now.
> Make hai less defenceless in boarding

- data/human/free worlds 1 start.txt
**Bugfix:** This PR addresses issue #7336 
Fixed FW Refinery 1 saying that Tomek was going to Tundra instead of Bourne for a senate hearing.
None lol
> [Content] Change <planet> to Bourne in FW Refinery 1

- data/wanderer/wanderer jobs.txt
**Bugfix:** This PR addresses https://steamcommunity.com/app/404410/discussions/1/3388420865125653546/
Change the source filter to only offer from a system 1 to 10 jumps from Ka'ch'chrai, meaning it can't offer from the other side of the Eye.
> fix(content): Wanderer job offering with impossible deadline

- data/drak/drak missions.txt
**Bugfix:** This PR fixes the archon missions.
We recently changed the Archons and their personality, but since these missions are always active in the savefile we need to fail them so they can trigger again, with the new version.
I am sure I did not miss-spell the mission names and this should work. I cant try it from phone myself though.
This can be tested on any savefile with the old missions.
With the new ones it'll just retrigger them.
> Bugfix: retrigger archon missions for compatibility

- data/hai/hai missions.txt
**Bugfix:** This PR addresses issue #7363
Change of `<npc>` to `Keloid` to ensure that the mission description tells you to target Scar's ship instead of one of his escorts.
lol
> Fix Scar's Legion mission dialog

- source/PlanetLabel.cpp
- source/Preferences.cpp
- source/Preferences.h
**Bugfix:** This PR addresses fixes #7313 
This PR does two things:
1. Considers the planet's outer ring when checking for overlap with a label.
2. Prefers a direction where under any zoom level the labels stay in the same direction. This is to avoid the labels jumping around when zooming in/out.
Used the scenario described in the linked issue. Without this PR the label jumps around, with this PR it stays on the left side.
It does a couple more overlap checks per frame (8 to be exact). But I don't expect those to impact performance in any meaningful way.
> Disallow the planet label to jump around under different zooms

- data/remnant/remnant jobs.txt
**Bugfix:**
Thanks to Deathdealer#6209 on Discord for reporting the Patir issue.
- Prevent Graveyard rescue jobs from placing the target ship in Patir, even after it is revealed.
- Change list of systems in Remnant core cluster to `near "Arculus" 3`.
I would like to eventually provide the option for stuff like `near` in a location filter to traverse wormholes, which would mean special cases don't need to be considered, but that won't be for a while.
> fix(content): fix Remnant rescue jobs

- CONTRIBUTING.md
This PR updates the `CONTRIBUTING.md` file to contain the descriptions of the `art`, `sound`, `text - long` and `text - short` labels that can be used to show the scope of issues.
> Add scope labels to the contributing.md

- source/PrintData.cpp
- source/PrintData.h
**Bugfix:**
Thanks to @Hecter94 for the feedback leading to the delimiter improvement.
- Separate the attributes, when listing by planet or system, or the planets or systems when listing by attribute, by semi-colons instead of the comma used to separate the item from its children to improve parsability.
- Refactor attribute, list, and ship/outfit sale printing to use generic namespace methods instead of repeating almost identical code two or three times.
> Refactor: Improve game data printing

- data/remnant/remnant events.txt
**Bugfix:**
- Fix the Caeculus star; the `wr1` sprite no longer exists.
- Fix the scaling of Ssil Vida itself; when all station sprites were doubled in size and scaled to 0.5 in game, these events were not updated.
- Reset `"jump range"` of Postverta and associated systems on deactivation so AI ships can still jump into those systems after deactivation; I'm not sure the refactor that fixes this will be in for 0.9.16.
> fix(content): small changes to Ssil Vida events

- data/remnant/remnant jobs.txt
**bugfix:**
Remnant: Bounty 4 spawns a fully intact Rano'erek with a fully functional Jump Drive, which is not set to be staying, allowing it to jump freely around the Galaxy, even to places the player can't access, or into the middle of human space.
This PR changes the Rano'erek to a crippled version instead without a Jump Drive, so it will stay within Remnant space. 
Alternatively, the fleet could be given "Staying" and maintain its Jump Drive, however as the mission description states:
> A Korath ship is marauding through Remnant territory.
I feel it's best to use the crippled variant so it's still able to move around via hyperdrive.
In the future, we may want to make a new variant used specifically for this mission that's fully intact, simply missing a Jump Drive, but for now, this …
> BugFix: Switch Remnant: Bounty 4 to spawn a crippled ship

- source/MapPanel.cpp
- source/Ship.cpp
- source/Ship.h
**Bugfix:** This PR addresses an issue introduced by #7213.
Due to a change in #7213 to have Ship::HyperdriveFuel return 0 instead of Ship::JumpDriveFuel if you have no hyperdrive, the travel plan gets drawn incorrectly if you have only a jump drive and are jumping across linked systems. The game incorrectly assumed that if you were jumping between linked systems that HyperdriveFuel would give you the amount of fuel needed to make that jump.
The fix involves creating a new variant of the GetCheapestJumpType method to give the cheapest jump between two given systems instead of only between the ship's current system and destination. The result of this call is then used to determine the cost of a jump between two systems in your travel path.
Without the change when using a ship equipped with …
> Correctly draw travel plans

- source/Mask.cpp
- source/MaskManager.cpp
My motivation for this is compiling with Emscripten 3.1.24 but it seems like a good thing to do anyway.
> Qualify std::move

- data/human/events.txt
- data/human/free worlds 1 start.txt
**Bugfix:**
Re-adding the events to avoid an old mission appearing invalid if it was already in progress.
Changed offer conditions so the FW Pirates Attack and Diplomacy arcs can be restarted with the new versions of the missions if a person was previously in the middle of hte chain, but not if they had already completed it sufficiently to move on to FW middle.
> fix(content): Re-add events and missions to avoid breaking saves

- .github/workflows/cd.yaml
- .github/workflows/cd_release.yaml
- .github/workflows/ci.yml
- .github/workflows/steam.yml
- source/Account.cpp
This PR bumps the version of Ubuntu runtimes used in GitHub Workflows. This fixes the recurring issues of CI failure due to the use of Ubuntu 18.04, which is deprecated.
Changes:
- In places where 18.04 was used by itself, it was changed to 20.04
- Where it was used alongside 20.04, it was changed to 22.04 (so we now have 20 and 22 instead of 18 and 20).
I also removed some comments related to broken features in 18.04; hopefully we won't run into those issues on the newer versions.
> Update ubuntu runtime in CI

- source/AI.cpp
Just improved the logic a bit to not calculate stuff without need.
Also I made sure to clarify the comment so that others would not make the same mistake I did.
Sorry.
~~Quickly, merge this before anyone notices!~~
~~This was literally doing the opposite of what it was saying for the hull and shield (only being true when those were higher than 150% combined)~~
~~On top of that, that part was overwritten by the strength in the system; whereas this personality is advertised to activate when either of those conditions is true.~~
~~This meant that frugal escorts did not work properly, and same thing for the Augmented Archon weapons; you could kill the archon all you wanted, so long as you did so in a ship costing less.~~
> Mechanics: Frugal performance improvement and clarification

- data/remnant/remnant outfits.txt
**Bugfix:**
Thanks to @pilover100 for reporting this on Discord.
The lack of explicit plural name means `s` is appended to the normal name for plurals.
This is wrong as it results in `Void Sprite Partss` when the plural should actually be the same as the normal name.
> fix(content): Give `Void Sprite Parts` plural name

- data/wanderer/wanderers start.txt
**Bugfix:** This PR addresses a log at the wrong location.
It was reported on the discord that deferring the mission gives you the log, I moved it to when you accept it.
N/A
N/A
> Bugfix: log at wrong location for unfettered jump drive source mission

- source/ImageBuffer.cpp
This fixes the usage of some compressed PNGs that were displayed incorrectly. 
I verified that every other image still gets displayed correctly, and without this PR using a compressed version of the shipyard background it looks like this:
The modified shipyard background:
> Fix display for some compressed PNGs

- data/human/ships.txt
Currently, the stats of the Sparrow and the Flivver are in a bit of a weird place. With the Flivver being slightly more expensive than the Sparrow, it is a logical first upgrade for new players. However, the current stats distribution is opposite to the roles these ships are supposed to fulfill. 
If you're looking for a fast transport ship that's cheap and agile with a small number of bunks and cargo, you should pick the Sparrow since it has the same number of bunks, ten more cargo, and is slightly cheaper to buy
If you're looking for an early warship that's fast, cheap and agile, you should pick the Flivver since it has more HP, weapon space and engine space. 
This seems quite counter to the Sparrow's role as an interceptor and the Flivver's role as a transport. 
As such, I've put …
> Sparrow/Flivver Stat Tweaks to Better Match their Roles 

- data/human/marauders.txt
- data/human/ships.txt
The Falcon and the Leviathan are very similar ships: both cost more than 9 million credits, have the highest health among civilian ships and have 240 weapon space. However, despite costing 1 million more, and having 10 more required crew, the Falcon tends to be inferior to the Leviathan, having less health and significantly less outfit space. This PR aims to both buff the Falcon and make the Falcon and Leviathan more distinct ships, with the Falcon being a balanced ship with the ability to specialise and the Leviathan being specifically combat-focused.
Changes:
- Increased the Leviathan from 480 mass and 7.6 drag to 580 mass and 8.1 drag, and decrease the Falcon from 510 to 490 mass. This makes the speed difference between the two vessels far more noticable and impactful.
- Increased the …
> Make the Leviathan and Falcon more distinct

- source/AI.cpp
- source/Engine.cpp
- source/PlayerInfo.cpp
- source/Ship.cpp
- source/Ship.h
- source/Variant.cpp
We'll keep the changes for another PR. This is just refactoring.
I also made temporary values that only change once the ship runs out of ammo or has its outfits changed for deterrence and attraction.
It should result in some nice performance improvements, given strengths used to be updated and recalculated each Step() of AI.
~~But it also now takes into account the deterrence of ships when assessing their strength.
I did this change because often we look at the strength of ships within a system, and just basing it on cost is wrong. The player could for instance look strong in a very costly but undefended alien ship, or with a whole fleet of them.~~
~~This could cause problems with variants that have ships with no guns, and in general make the gunned ones more likely to spawn? I could make …
> Refactor: use strength instead of cost directly and optimization of deterrence + cargo attraction

- .github/workflows/steam.yml
CI only change for steam releases.
With more frequent steam releases discussion happening on discord the CI code for packaging steam runtime is getting more eyes.  I noticed I could improve debug output for the CI build so I am contributing this.
When building a docker container or launching shell scripts from CI it is good to use `set -ex` options for `/bin/sh` or `set -o pipefail -ex` when building a `/bin/bash` script.
The options are defined as the following:
| Option for set or /bin/bash | About |
| --- | --- |
| `-o pipefail` </span> | If set, the return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully. |
| `-e` | Exit immediately if a pipeline... returns a non-zero status. …
> CI only: Better bash debug output for steam release build

- source/ImageBuffer.cpp
`png_set_scale_16` is not available in the Steam runtime, because its libpng is too old. So use an alternative function, as recommended by the official manual.
> png_set_scale_16 is not available in the Steam runtime

- data/human/weapons.txt
BugFix
The twin blasters added in #7402 use Submunitons to have two separate projectiles, but as the main munition has a lifetime of 0, the weapons show as having a range of 0:
I loaded the game up and viewed the outfits with and without the fix. 
Without this fix:
With this fix:
Thanks to @Pointedstick for pointing this out on the original PR
> Add Range Override/Hit Effect to Newly Added Twin Blasters

- source/System.cpp
Fixes a potential null dereference for system fleets without a government. Found by clang's undefined sanitzer.
> Fix potential null dereference

- data/hai/hai reveal 4 middle.txt
The rework that Amazinite and I developed incorporated an existing story into the plot. 
This accounts for saves which have already done that plot.
> fix(content): Account for saves that have already done Pirate Troubles

- data/human/free worlds 0 prologue.txt
- data/human/jobs.txt
- data/human/pirate jobs.txt
- data/human/syndicate jobs.txt
Right now, bounty jobs are very passive; in most cases, players don't go out of their way to finish them, instead waiting until they stumble across their bounty by happenstance. This is due to a range of reasons:
- Bounty jobs have no investment cost. Unlike cargo or passenger jobs, you can take on an infinite number of bounty jobs.
- Bounty jobs have no chance of failure. Unlike rush or escort missions, bounty jobs stick around, making there be even less of an incentive to finish the job in a timely manner.
- Bounties are annoying to hunt down. Some bounty jobs can force you to check over 15 systems, most of which require copious backtracking to get to.
The fact that bounty jobs are so passive tends lead to the missions list getting filled by bounty jobs, as the rate of bounties offering …
> Make bounty jobs more active

- data/human/marauders.txt
- data/human/ships.txt
- data/human/variants.txt
- data/human/weapons.txt
- data/persons.txt
This PR increases the size of full-sized Human missile launchers (except the Javelin launcher) to differentiate them from the Pod versions and provide an in-game reason for small craft to use Pods: the big ones are too big! This necessitates tweaking the loadouts of many ships, typically to reduce the number of full-sized launchers by one in cases where missile-heavy ships would be overloaded.
Because larger missile launchers would have less DPS per ton, missile damage values are increased to match the same DPS/ton values that they were at before. This makes individual missiles more dangerous if they hit, so an additional change is made to make them hit less often: they are no longer launched at full speed, but rather have to accelerate up to their maximum speed, which is unchanged, …
> improvement(content): Increase weight of human launchers and rebalance missiles accordingly

- data/human/weapons.txt
The recently added twin blaster guns use submunition to have dual projectiles, however as the main projectile has a `velocity` of 0, the AI isn't able to correctly lead its target using the submunitions. 
This PR adds a `velocity override` to the twin blasters matching their submunition velocity so the AI is able to properly lead its target when firing. 
This save will place you on Greenrock with several sparrows armed with twin blaster guns so you can see them properly leading their targets.
[All Content.txt](https://github.com/endless-sky/endless-sky/files/9835228/All.Content.txt)
> Add a Velocity Override to both Twin Blaster Guns

- source/NPC.cpp
**Feature:** This PR reimplements #7335, but not broken this time.
Despite the `accompany` npc objective being implicitly save, most instances of the `accompany` objective are paired with the `save` objective, making it seem as though the two don't already overlap. This PR removes the implicit `save` objective from the `accompany` tag. The only `accompany` behavior is now achieved by using `accompany` and `save`.
Tested #7335 plus the fix from an earlier version of this PR. Accompany now no longer requires an npc to be saved, and evade doesn't break.
> Split the implicit npc save objective from the accompany objective

- data/interfaces.txt
- source/PlayerInfoPanel.cpp
Previously, the hotkeys for parking an individual ship and parking all ships was Shift+P and Shift+A, respectively. All other buttons (besides Disown, which should probably be obscure for safety) would show hotkeys when holding down alt, besides Park and Park All. This PR sets their hotkeys to K and A, and makes them visible when holding alt. It also maintains the old Shift+P hotkey in case anyone had the committed to muscle memory.
> feat(UI): Add proper hotkeys for parking ships

- data/hai/unfettered jobs.txt
This PR addresses that `fail`s in `on accept` don't work (at least for jobs), meaning that the Unfettered JD jobs don't fail. This is fixed by moving the fail trigger to a `to fail` node.
Took the job; it was already greyed out, and failed upon landing while still allowing another JD job to offer.
If I had provided a save file here, would you have downloaded it?
> Make Unfettered JD jobs fail properly

- source/Politics.cpp
This PR fixes two issues with the new scan evasion logic:
- Having completely concealed illegal goods with no legal goods is now 100% undetectable (thanks @leklachu)
- The rest of the scanning logic is no longer skipped by a successful evasion (whooops)
None, but the PR is fairly straightforward.
> Small fixes to the new scan evasion formula/logic

- data/hai/hai reveal 4 middle.txt
Since the mission chain largely triggers off set conditions it was still broken. Now those have been dealt with.
> fix(content): Pirate Troubles fix other offer conditions

- data/hai/hai missions.txt
**Bugfix:**
Thanks to @Arachi-Lover for pointing this out on Discord.
It is currently possible to get the unwated cargo mission where a Hai child has snuck unto your cargo hold on Alta Hai (the Quarg ringworld in Hai space).
Presumably, the intention is that this mission only offers on the other side of the wormhole.
Not sure if the government line from the filter should be removed now?
> fix(content): Ensure Unwanted Cargo cannot offer on Alta Hai

- data/human/ships.txt
The Star Queen is not a great ship: at 5.5 million credits hull price, it is the same cost as the Protector, and costs at least 1 million more than every medium warship. Fitting out the Protector with 11 bunk rooms (leaving it with 370 outfit space, 10 more than the Star Queen's total) gives it 113 total bunks versus the Star Queen's 112, which translates into even more passenger space due to the Protector's lower crew requirement. When putting in as many bunks as possible, the Star Queen has 151 passenger space, compared to the Protector's 193 and the Bastion's 131. (Both warships also have a large HP advantage, and the Bastion's hull only costs 3.8 million.) This PR increases the bunk efficiency of the Star Queen, so that it is a more worthwhile choice.
Changes:
- Decreased the Star …
> Buff the Star Queen

- source/PreferencesPanel.cpp
- source/text/Font.cpp
**Feature:**
Inspired by a suggestions from @samrocketman and zredfire#8549 on Discord.
Adds an option in the preferences panel, in the display section, to enable always underlining shortcut keys on button labels.
The preference defaults to false.
Launch the game, look at various buttons with the preference off and on to ensure that the underlines show up when expected and not when not. Also, hold alt to ensure that that still enables the unerlines when the preference is off and does nothing when it is on.
N/A, probably.
> Option to permanently underline shortcut keys on button labels

- data/hai/hai reveal 5 philosophers.txt
- data/human/variants.txt
I'd overlooked making sure Danforth and the Auxiliary had jump drives. This should hopefully sort that out.
> fix(content): Added needed jump variants and put them in for HR

- source/Outfit.cpp
While investigating an issue, I discovered a static assertion failing where `.back()` was being called on an empty string.
That call was occurring in `Outfit::Load()` following https://github.com/endless-sky/endless-sky/commit/7eb2186e77a08d64848a8c3a4aedd108a0de6ce4. I suspect it is when a `Ship` calls `Outfit::Load()` and passes it its `attributes` node which will leave the `name` of the `Outfit` empty.
Build Debug using @quyykk's Visual Studio project and run. Without this addition, a runtime error will occur while loading. With it, no such error is present.
> fix(internal): calling `back()` on an empty string

- source/Bitset.cpp
- source/Bitset.h
- source/FireCommand.cpp
**Bugfix:** This PR addresses issue #7458
Thanks to @quyykk for pointing me to this ~~after I already bisected 0.9.15 and 0.9.16 to find the commit that created the issue.~~
This issue was introduced by bc586bd20fe9ae770dab048c131697fb957d50f6.
It was clearing the `weapon` Bitset and aim vector of FireCommand, making them empty (no elements).
This means it is not possible to have any weapons fire.
This PR removes the old commands by resetting every element of the two collections to their initial values, indicating no command.
Capture a ship with any commit from the one creating this bug onwards and it will not fire its weapons and you will not be able to fire its weapons until reloading. With this PR, weapons can be fired immediately, without reloading, like before the bug was introduced. …
> Fix weapons on captured ships being inoperable until reload

- copyright
- io.github.endless_sky.endless_sky.appdata.xml
This PR does the following:
- Fixes every syntax error introduced by HR
- Uses standardized license short names
- Adds the license text for licenses used that didn't have one
> fix(copyrights): Fix misc errors/oversights in the copyright file

- data/human/free worlds 1 start.txt
Some of the old FW missions end with the player saying something with a choice, which is basically never seen elsewhere in the game (and for good reason, in my opinion; these ending lines feel like they're more blatantly taking away the player's agency than other pieces of unprompted dialogue). This PR either turns that final line into a choice, or outright removes it. It also slightly rearranges Barmy's ending words, mentioning to visit the spaceport last, instead of putting the reference in the middle of dialogue.
> Adjust stylistically awkward endings to old FW missions

- data/human/human missions.txt
Moves the log after taking drugs from being generated when "completing" the mission to when accepting it, so that the player doesn't need to land back on the same planet. Also made the job stop offering after refusing enough times.
> Make the log after taking drugs trigger properly

- data/human/human missions.txt
The descriptions of the old transport missions are somewhat messy; many don't specify what exactly you're carrying, or what the payment is. This PR updates those descriptions to specify as such, and also slightly changes the "on offer" text to mention the cargo/passenger space needed, as well as the payment.
> Standardise formatting of old transport missions

- source/Messages.h
Makes Messages::Add() default to Importance::Low if no importance is supplied.
Why? It's easier to do this this than write Messages::Importance::Low once.
Before: 
`Messages::Add("Test Message", Messages::Importance::Low);`
After:
`Messages::Add("Test Message");`
In Action:
None
> Messages::Add() default to Low importance

- data/persons.txt
**Content**
Adjust the following on Gefu's pers ship:
Remove unnecessary sprite line
Add spinal tags to Battleship and Fusion Cannon
Increase Fusion Cannon space & price to match the Dragonflame as a spinal weapon
Increase Battleship space to match
> Gefu pers ship adjustments

- .github/pull_request_template.md
This PR does the following:
- Uses "fixes" in the bug fix section so that GitHub automatically links the issue specified
- Updates the link to the asset repo
This is a draft because the asset repo hasn't been moved yet.
> Two small improvements to the PR template

- README.md
Updates the systems requirements:
- The RAM used when starting a new game is at bit more than 400MB, so I increased it to 500MB.
- The current size of a release build is 220MB, so I rounded it to the nice number 250MB.
- I increased the recommended storage to 1GB to account for people that want to use the high dpi plugin.
> doc(requirements): Update the system requirements

- source/AI.cpp
**Bugfix:**
Thank you to all the people who have reported the issue with the Winds of Light not actually staying in Peragenor, both on Steam and Discord.
It turns out that AI::DoSurveillance() was setting jump and land commands on ships without checking if they were `staying` and so should not receive such commands. I do not know how long this has been the case, but it does happen in 0.9.14.
The issue was only discovered relatively recently where the Winds of Light, the Starling you are required to scan in the missions: `Remnant: Keystone Research 5` (and 6) which has both `staying` and `surveillance` personalities.
The behaviour of it not staying is also, however, rather intermittent, but the frequency with which this behaviour is exhibited can be drastically increased by removing all …
> fix(mechanics): Surveillance personality no longer overrides staying

- source/Test.cpp
- source/Test.h
- source/main.cpp
This PR changes the integration tests runner to succeed when running known failing tests that actually fail, and if they do succeed emits an error (since they were supposed to fail).
Ran an integration test that should succeed, it did. Ran an integration test that should fail, it did. If it didn't then the error was correctly emitted. CI also will execute the integration tests.
> feat(testing): Better handling of known failing tests

- endless-sky.6
- source/Test.cpp
- source/Test.h
- source/main.cpp
- tests/integration/config/plugins/integration-tests/data/tests/tests_ship_sale.txt
- tests/integration/run_tests.sh
This PR adds a new option, `--list-tests` that lists every runnable (i.e. not partial and not broken) integration test. This simplifies getting the list of tests to run.
I modified the `run_tests.sh` script accordingly, and changed the status of one test because it now succeeds.
Used the option: it works. Also ran the integration tests, which CI should also run.
> feat(test): Include known failures and missing features in integration tests to run

- source/Color.cpp
- source/Color.h
- source/MapDetailPanel.cpp
**Bugfix:**
As it is, it is possible to have multiple governments with the same display names and map colours. It would then be possible to get two identical entries in the map key.
This PR should prevent this from happening.
It does so by keeping a list of display names of governments under consideration for the key and, if a government being added has a display named matching one already added, the colours for the two governments are compared. If the colours also match, then a new entry will not be added and the existing entry may have its `distance` score updated if the new government has a closer system.
To better facilitate this, an equality operator is also added to Color. It will return false if any of the four elements of the colour array don't match their corresponding element in …
> fix(UI): Don't duplicate government entries in the map key

- data/human/free worlds 0 prologue.txt
Added a check to the "offer" section of the "FW Escort 0" mission that grants backwards compatibility to players by preventing players who completed the old mission chain starting with "FW Escort 1," but did not yet join the Free Worlds from being offered the new mission, which represents the new starting point of the mission chain.
This pull request fixes a compatibility issue caused by the addition of the new "FW Escort 0" mission, which now preceeds "FW Escort 1" in the Free Worlds escort mission chain. See issue #7528.
**Bugfix:** This PR addresses issue #7528
When the new "FW Escort 0" mission was added, no checks were put in place to prevent the mission from being offered to players who had …
> Aneutronic patch 1

- data/map.txt
Moves the "Deep Space" systems (and Devil-Hide) from their location near Coalition space to a new location north of the wanderers, as requested by Arachi on the discord.
New location
> Move the "Deep Space" systems from Hai Reveal away from the Coalition

- data/human/free worlds 1 start.txt
The current text reads that Thule is "very weary" of the FW after the attack on Greenrock. I believe this should be "wary," as in suspicious instead.
This requires a save with a specific save point in the FW story line, which I do not have. I did ensure that I only changed the two words and check the enclosing quotes to make sure nothing had shifted.
> FW Thule post Greenrock: Change word choice from weary to wary

- data/human/deep missions.txt
Text in the mission showed "...It is covered with filled with letters and images..."
This change removes the text "filled with" because "covered with" seemed like the more appropriate of the two and using both seemed incorrect.
> removed unnecessary text in deep missions_Stone of Our Fathers 6

- data/map.txt
**Bugfix:**
Due to the short range of the MCS Resource Extractor, Coalition ships were having trouble mining asteroids, which in some systems was literally impossible for them. I simply went through the Coalition systems and lowered the mineable energy (somewhat arbitrarily) to make things easier for them.
Flew around and observed that Coalition ships were now able to mine asteroids more easily.
N/A
> [Fix] Coalition Asteroid Energy Reduction

- source/MapPanel.cpp
**Bugfix:** This PR addresses issue #7564.
Ensures that the game doesn't try to dereference a null pointer, which causes a crash.
The second of the pair of checks added here fix the issue, but the first is probably a good idea anyway.
https://github.com/endless-sky/endless-sky/files/9993600/a.a.txt
> fix(map): Prevent dereferencing nullpointer

- data/remnant/remnant 2 cognizance.txt
I found a typo in the dialog for a Remnant mission, and fixed it.
**Bugfix:** This PR addresses issue #7568
In "Remnant: Cognizance 9," there was a missing quote mark at the end of some dialog. The missing quote mark was added.
> Fix Typo in "Remnant: Cognizance 9"

- data/human/human missions.txt
For a mission that requires no combat rating, Terraforming 11 is very hard; in particular, you have to contend with a nasty Marauder Bounder (Engines) that will outspeed most ships, and receiving help during the fight is unreliable at best.
The following changes have been made in this PR:
- The Marauder Arrow and Marauder Bounder have been replaced with a Headhunter and Wasp respectively.
- Reinforcements have been added to the mission, and will arrive two systems behind the player.
- Text has been slightly adjusted to accommodate these changes.
Do it, you coward.
> Make Terraforming Tundra's fight less brutal

- data/korath/korath variants.txt
**Bugfix:** This PR addresses issue #7578 
These ships have very large crew counts, which can cause a crash on some systems when CaptureOdds is run.
The solution for the base ship is to add the `uncapturable` token so CaptureOdds doesn't run for it, but this property is not inherited by variants and so the token needs to be added to each variant definition as well.
> fix(content): Add `uncapturable` to Korsmanath A'awoj variants

- source/Ship.cpp
**Bugfix:** This PR addresses forbearing personality not accounting for special damage types, meaning you can overheat them and let them disable themselves by moving around without them doing anything about it.
Forbearing ships will now be provoked when either:
-taking shield/discharge damage and shields are lower than 90%
-taking hull/corrosion damage and hull is lower than 90%
-taking heat/burn damage and is overheated
-taking ion damage and has 10% chance of jamming
-taking ion/energy damage and its energy is lower than 50%
-taking slowing damage and is slown by 10%
-taking fuel damage and has no more than 2 jumps worth of fuel left
-taking disruption damage and has more than 100 disruption
Instead of just when hull/shields are lower than 90%.
n/a
Seems pretty straightforward to me and …
> Bugfix(AI): account for special damages for forbearing

- data/human/free worlds 3 reconciliation.txt
This PR adds a new mission that triggers if the player doesn't have a jump drive installed or in cargo, such as if they sold it. (It doesn't check planetary storage, however.) All the mission does is tell the player to revert to a previous save.
> Inform the player if they lose their jump drive during FW

- data/tooltips.txt
- source/AI.cpp
- source/Outfit.cpp
- source/OutfitInfoDisplay.cpp
- source/Ship.cpp
- source/Ship.h
- source/ShipInfoDisplay.cpp
[Was making this really a better use of time than paying attention to my orbital mechanics class?]
This adds a new attribute, `inertia reduction`, that reduces a ship's effective mass. It works similarly to the various protection attributes, where the new mass value is given by
`inertial mass = mass / (1 + inertia reduction)`
This is done in such a way that does not affect maximum heat / heat capacity. The attribute only affects mass with regards to movement.
A positive mass reduction value makes a ship less massy. For example, `mass reduction` 1 would cut your ship's inertia in half.
This only affects your base ship and its outfits. Cargo and docked fighters/drones will not be affected.
Inertia reduction can also be negative, up to -0.99. This lets you increase a ship's inertia by up to …
> [Mechanic] Inertia Reduction

- source/PlayerInfo.cpp
**Bugfix:** This PR addresses issue #1624 
This is an alternative approach to that in #5723.
When saving, two new blocks may be added between `missions` and `available jobs`: `mission cargo` and `mission passengers`.
These blocks will contain UUIDs for missions and ships and cargo/passenger counts for any mission cargo or passengers on ships not at the player's current planet.
The format will be:
```
"mission cargo" | "mission passengers"
"player ships"
<mission UUID> <ship UUID> <count>
```
`player ships` is included for some measure of future-proofing. In #5723, @tehhowch suggested NPC ships potentially being able to carry mission cargo. While that feature is not implemented here, this does leave room for that to be added without needing to change the save syntax introduced here, only …
> Record distribution of off world mission cargo and passengers

- data/remnant/remnant 2 cognizance.txt
There where two extra words in some of the dialog that didn't make sense, as if the author of the dialog started writing one thing, then changed mid-sentence to write something else. I took out the extra words from the first thing that was written to make the overall sentence make sense.
> Fixed Typo in "Remnant: Cognizance 25"

- data/interfaces.txt
- source/PreferencesPanel.cpp
- source/PreferencesPanel.h
**Feature:**
Settings can now be spread across multiple pages, navigated by dynamic `Next` and `Previous` buttons on the left of the bottom edge of the settings panel.
If there is only one page, the buttons will be totally hidden.
Else, both buttons will be visible, but one will be dimmed if there are no more pages in that drection.
<details>
(Note: for the screenshots, I have moved the `Other` category to a new page, but this PR does not include that change.)
</details>
Open the settings, click the buttons, use the shortcut keys, get the expected behaviour.
> feat(UI): Support spreading settings across multiple pages

- source/MaskManager.cpp
- source/MaskManager.h
Fixes a race condition inside MaskManager. The race condition as reported by the thread sanitizer:
<details>
<summary>stack trace</summary>
```
WARNING: ThreadSanitizer: data race (pid=67562)
Write of size 8 at 0x55dccb70ecf0 by thread T2:
#0 std::__1::__tree<std::__1::__value_type<Sprite const*, std::__1::map<double, std::__1::vector<Mask, std::__1::allocator<Mask> >, std::__1::less<double>, std::__1::allocator<std::__1::pair<double const, std::__1::vector<Mask, std::__1::allocator<Mask> > > > > >, std::__1::__map_value_compare<Sprite const*, std::__1::__value_type<Sprite const*, std::__1::map<double, std::__1::vector<Mask, std::__1::allocator<Mask> >, std::__1::less<double>, std::__1::allocator<std::__1::pair<double const, std::__1::vector<Mask, std::__1::allocator<Mask> > > > > >, …
```
> Fix race condition inside the MaskManager

- data/coalition/coalition missions.txt
**Bugfix:** This PR addresses issue #7595 
As spotted by damerell in the issue, the `on visit` for mission `"Longcow Antibiotics 1"` assumes you have a missing escort when you get it, when you could simply land on the destination planet without ever picking up the cargo.
Additionally, mission `"Coalition Outbreak 2"` features a pretty similar scenario.
This just changes up the dialogs a bit so that they account for both cases, missing ship or not having picked up the cargo.
> [mission tweak] Adjust on visits for a couple Coalition missions

- source/Files.cpp
- source/Ship.cpp
Fixes the issues the new CI is whining about. This includes adding two line breaks and the removal of an exclamation mark. The line breaks are straightforward, but the `!` is problematic:
It is part of a preprocessor warning. We didn't have those before, so the style checker CI cannot handle them (it would be a 30 second fix though), but the bigger issue is that these warnings are not entirely portable (for instance, they don't work in visual studio).
For now, I removed the exclamation mark that triggered the error. I can fix the script to handle it, or we could remove the preprocessor warning. Either way, we should probably have a permanent solution.
> chore(code style): Fix code style issues in master

- utils/check_code_style.py
This PR fixes a false positive related to preprocessor warnings. Now all preprocessor texts are completely removed during sanitization, except for the include statements (the "" includes still have their string contents removed, as previously).
> bug(CI): Fix false positive in code style checker

- .github/path-filters.yml
The path filter for the location of the integration tests was incorrect, which meant that PRs that only modify the integration tests didn't run the integration test CI.
> Fix path filter for the integration tests

- source/BoardingPanel.cpp
- source/Ship.cpp
- source/Ship.h
**Feature:** This PR implements the feature request detailed and discussed in issue #7608
Below the line informing the player that they have successfully captured a ship, there will now be a line telling the player how many crew were transferred, unless fewer than 1 were.
> feat(capture): Indicate crew transfer on ship capture

- tests/integration/config/plugins/integration-tests/data/tests/tests_afterburn_flight.txt
- tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
- tests/integration/config/plugins/integration-tests/data/tests/tests_disown.txt
- tests/integration/config/plugins/integration-tests/data/tests/tests_wormhole_navigation.txt
Simply multiply all capacities of the ships defined in the test savefiles by 10, because I keep getting errors that its missing 3 outfit space and whatnot.
These tests are not meant to test balance, and nobody bothers to update them when an outfit's size of whatever is changed, so this makes sure that'll never be required, pretty much.
> Tests: false positive fix: increase capacities of test ships

- tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
Related to https://github.com/endless-sky/endless-sky/pull/6407 I was asked to do integration tests so here they are. Just one for now, and marking this as a draft as I'm not sure what to do exactly for the atrocity part
Added a test where you are in terra incognita with a derelict quarg ship you need to assist.
That way you get close to it and with this absurd scanning it'll scan you and fine you for the hyperdrive (for one credit) but not for the nerve gas because its ignored.
May need to tweak the event and things like that.
> Testing: new integration test for changing of illegal outfits per government

- data/hai/hai reveal 5 philosophers.txt
**Bugfix:** This PR addresses issue #7592
Ensures that the log for Agent Kopkow goes into the Minor People tab instead of creating a new tab.
It doesn't seem to me like he is a "People", so he goes into the minor category.
I don't think any of the existing PRs already handle this ~~but there's a lot to check so maybe I missed it. None seem to be mentioning the issue, though.~~
> Hai Reveal: Fix Agent Kopkow log

- data/remnant/remnant events.txt
**Bugfix:** This PR addresses issue #7632
In #5001, the Gascraft was renamed to "Puffin", and the names of the event referring to it and the shipyard it was in were also updated.
This, for the most part, should not cause issues, but someone who already has the old version of the mission in their save file but has not yet completed it will encounter issues if they update to a version of the game after the rename (as has happened in the mentioned issue). The mission refers to the event "remnant: gascraft" but this event no longer exists and so the game disables the mission, assuming the non-existent content is from a plugin that has been removed and not wanting to risk breaking something by letting the incomplete mission run.
This PR adds a line `event "remnant: gascraft"` so the event is …
> Ensure Remnant Gascraft event compatibility

- source/Outfit.cpp
**Bugfix:**
Thanks to @Hurleveur for reporting this on Discord.
After the display names is parsed, since a new if statement begins, the value of the display name token will be inserted into the attributes Dictionary like any other, resulting in it being incorrectly displayed in the outfit info display with a value of 0.
> Fix bug with outfit display names

- data/coalition/coalition outfits.txt
- data/hai/hai outfits.txt
- data/human/outfits.txt
- data/remnant/remnant outfits.txt
- data/remnant/remnant ships.txt
**Bugfix:** Some of you may have noticed that, _whoops_, scanning is impossible now. Okay, not impossible, but unbearably slow. This is my fault, I did not practice due diligence with my PR, and the slowing factors to scanning (distance to target, and size of target) are not at all counterbalanced by a corresponding increase to scanning speed.
Bumps "scan speed" (outfit and cargo both) very highly upwards to bring scan times down to reasonable levels. Scanning is still slower than it was pre-change, as that was the original vision of the PR, but the speeds displayed in continuous are _not_ intended.
Flying around in my classy Hurricane with one, or multiple, or many scanners installed, scanning every ship that passes by. With a single outfit and cargo scanner each, scanning is …
> Fix scanning

- source/ConversationPanel.h
- source/Test.h
- tests/integration/config/plugins/integration-tests/data/tests/tests_conditional_choice.txt
As it was pointed out by @petervdmeer https://github.com/endless-sky/endless-sky/pull/5440#discussion_r1027086484 the integration test was not checking for the name being set to F L correctly.
That was not the main goal of the test, it was mainly to make sure "name" didnt cause a crash or wasnt shown as it happened at one point.
But may as well test this correctly.
Edit: in order to fix this I had to set some variables that were uninitialized and thus just took the value of whatever was left in memory, meaning it would trigger shift, tab and whatnot.
> Test fix(integration): check for name working in conversation and initialize variables to 0

- source/PlayerInfo.cpp
- tests/integration/config/plugins/integration-tests/data/tests/tests_store_outfits_on_take_off.txt
**Feature:**
Instead of always selling excess outfits that cannot fit in ships on take off, move them to the local storage, if hte planet has an outfitter.
Have an outfit in cargo that can't actually fit in any of your ships and take off.
It would previously be sold, and should still be if you are at a planet without an outfitter. (It may not actually be possible to get into this situation without save editing.)
If you are at a planet with an outfitter, it should be moved to the storage on that planet.
Adds two new tests:
One checks that an outfit that cannot be carried is correctly moved to storage on taking off from a planet with an outfitter.
The other checks that an outfit that cannot be carried is still correctly sold when taking off from a planet with no outfitter.
N/A
> Store excess outfits in cargo on take off

- source/AI.cpp
**Bugfix:** This PR fixes a small issue introduced by #7524
#7524 scales the current position by a squared factor causing the target point to have a distance from the center potentially far larger than the desired distance.
Also, `Point::Unit()` has a more robust way of detecting potential divisions by zero since the square of a floating point number can be zero without the number itself being zero. Since `Unit()` conveniently also handles this corner case appropriately, we can just call that to clean up this code.
The code only affects very specific circumstances. I tested it by setting 'departure 10000' on a system and verifying the calculated `MoveTo` gave correct values using printf.
> Fix and clean up closestDeparturePoint calculation

- source/Test.cpp
- tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
**Bugfix:**
If a string is not parsed to a proper SDL key code, it will return SDLK_UNKNOWN, but this was not previously checked so the game was running the test with that, which is obviously not correct. This makes it easier to tell when your test has a syntax error.
Also, change `key "enter"` to `key "Return"` in the "Save To Default Snapshot" integration test so it actually does what it's supposed to. `enter` is not a valid SDL human readable key string.
> Print an error when a `key` string parses to SDLK_UNKNOWN for integration tests

- source/GameData.cpp
- source/ImageSet.cpp
- source/ImageSet.h
Makes it so that plugins without a icon don't generate the following warning:
```
Warning: image "<plugin>" is referred to, but has no pixels.
```
The warning disappears with this PR.
> Don't load a non-existent plugin icon

- source/Ship.cpp
The player's piracy threat was updated when the player bought ships. This is because the ship that was bought didn't have a deterrence/attraction value calculated for it. This PR fixes this by always calculating the deterrence and attraction value for ships. In the future a ship's strength will involve those values, so in the future this change won't be unnecessary.
Bought 100 ships on a starter pilot. Without this PR the ship's piracy threat doesn't change unless reloaded.
[op guy.txt](https://github.com/endless-sky/endless-sky/files/10050360/op.guy.txt)
> Always calculate attraction/deterrence

- tests/integration/run_tests.sh
Filters VSync related messages from the output of the integration tests. The software renderer used doesn't even support setting the VSync to 0 (i.e. disable), so we have to filter them out.
Also filters out a warning that says that no audio will play: Yes we know, it's CI.
Ran the integration tests locally, the error messages get correctly filtered out.
> Filter warning messages from integration tests

- data/remnant/remnant 2 side missions.txt
**Bugfix:** This PR addresses issue #6954
Use the `outfit (flagship installed): Research Laboratory` auto-condition to actually check for the outfit.
Go to Vail with the outfit installed and the mission active and see the special text in the conversation.
[test test.txt](https://github.com/endless-sky/endless-sky/files/10050704/test.test.txt)
> Fix Remnant Paradise visit branch

- source/OutfitInfoDisplay.cpp
before:   <img width="122" alt="image" src="https://user-images.githubusercontent.com/101683475/202923100-b9231bdf-352d-4a5e-9e95-b605c78ac901.png">
after:  <img width="119" alt="image" src="https://user-images.githubusercontent.com/101683475/202923600-00993cf2-403f-4543-a83a-4319b9bae0c5.png">
N/A
> Outfit Info Display Displays Seconds with an 's'

- source/ConversationPanel.cpp
**Bugfix:** Fixes #7675 
When the new `to display` feature is used, the number of choices displayed can be fewer than the total number in the txt. The logic for the SDLK_DOWN and SDLK_RETURN does not check the number of displayed choices, so the cursor can go past the end of the list, and an out-of-bounds option's goto can be followed.
I have several PRs open that use `to display`, and they all cause this. You can also use my test file.
[test.txt](https://github.com/endless-sky/endless-sky/files/10052033/test.txt)
> ConversationPanel enter&down keys go past end of choice list when "to display" is used

- endless-sky.6
- source/PrintData.cpp
- source/PrintData.h
**Feature:**
Adds a command line option for testing a LocationFilter to get a list of all the planets and systems that will match it.
Using the current LocationFilter for the Remnant Graveyard rescue job.
`EndlessSky.exe --matches < "location filter file.txt"` (In Windows command prompt.)
> A way to get every planet and system matching a provided LocationFilter

- .github/workflows/ci.yml
- tests/integration/run_tests_headless.sh
This PR does two things:
- Don't force software rendering when running the integration tests. If there is no hardware accelerated driver available, Mesa will fallback to a software driver anyways.
- Disables the Ubuntu 22.04 GLES integration test, since there is a performance regression there.
It fixes the slow OpenGL ES integration tests on my machine. Hopefully, it will also speed it up in CI.
> fix(integration tests): Fix slow GLES integration test

- source/Ship.cpp
- source/Ship.h
this feature allows bay-less variants for ships that have internal fighter bays.
testing was done with Aerie class to verify it is impossible to buy fighter and insert it into a non existent bay.
plugin which uses this feature can be found at https://github.com/daggs1/Lionheart_Customs
this is a resend of https://github.com/endless-sky/endless-sky/pull/7142 which got closed by mistake due to a fork sync with upstream
> add support for ship bays removal

- data/korath/korath ships.txt
**Bugfix:** N/A. No issue for it, but this is a pretty minor fix (it quite literally just replaces two characters)
Changed quotation marks to back tick to accommodate for the quotation marks in the Echo-Galleon description.
N/A
N/A
> Fix Echo-Galleon Description

- .github/workflows/cd.yaml
**Bugfix:** This PR addresses the failing CD workflows.
Here's the error for convenience:
```
> Run go get github.com/github-release/github-release
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
/
/
---
PS: Accidentally created the branch here, delete it with the merge.
> Fix deprecated `go get` usage in CD release upload

- .github/workflows/projects_check.yml
The check copyright CI always ran because the condition always evaluated to true because it was wrong. Not anymore!
> Fix condition for copyright CI

- source/AI.cpp
**Bugfix:** This PR addresses issue #5541.
This is a small fix-up of #7379 fixing a new report in #5541.
MoveEscort() has two branches that were blocked if an escort was out of fuel. These two branches were responsible for planning how an escort should follow its parent, and already contain code handling the out-of-fuel condition, by either landing to refuel (via SelectRoute) or by moving to the system center as a fallback. Also flying through a wormhole without fuel was blocked as an option as a side effect.
This patch enables taking those branches for escorts without fuel.
I have tested with the new savegame submitted by eternal-sorrow on Oct 20 at #5541. The escorts now take the wormhole, refuel and join the flagship without user interaction after loading the savegame.
I have also …
> Let out-of-system escorts without fuel plan their next move

- SConstruct
SConstruct already has support for `CXX`, `CXXFLAGS` and `LDFLAGS`. This patch adds `CPPFLAGS`, used by the preprocessing step.
This is handy for e.g. Debian builds which may put some hardening flags there.
> honour CPPFLAGS from environment

- data/human/free worlds 1 start.txt
I was playing through the first two battles of the free worlds just for fun, and I noticed my flagship Deadhunter (osprey I capped from pirates) was referred to as "your deadhunter" not "the deadhunter" which didn't really make sense. If the game just said "your ship" or "your Osprey" that would make much more sense, but actually using the name of the flagship with "your" in front of it doesn't make sense. So I changed it.
> Very minor wording change

- utils/check_code_style.py
Summary
-------
This is a CI only change meant for local development only.
This change adds support to `utils/check_code_style.py` to optionally receive one or more patterns (or even single files) for the style checker to run against.
Example usage
-------------
For local development, you can run a really fast style check against only files you've changed.  The following is an example for Linux developers.
```bash
git fetch https://github.com/endless-sky/endless-sky.git master
git diff --name-only $(git merge-base FETCH_HEAD HEAD) HEAD '*.cpp' '*.h' \
| xargs python utils/check_code_style.py
```
The above command runs in under 2 seconds when timed with `time`.  Normally `check_code_style.py` takes over 15 seconds.
Performance Impact
------------------
No impact to GitHub actions.  Drastic …
> CI only: Support file args for check_code_style.py

- copyright
Found some patterns that have no corresponding files and it appears that the reason is simple typos
> fix typos in copyright file patterns

- .github/workflows/projects_check.yml
- EndlessSkyTests.cbp
The project checking CI doesn't run if only new unit tests were added because of a missing trigger path. This PR fixes this issue and adds the missing file to the CodeBlocks project.
> Fix the project check CI when adding a new test file.

- source/GameAction.cpp
- source/GameEvent.cpp
- source/GameEvent.h
**Feature:**
GameEvent::IsValid() will now return a string that will be empty if the event is valid or have a reason (either a planet or system it refers to is not valid or it is not defined) if it is not.
GameAction::Validate() will print this string along with its existing error message to help make fixing stuff easier.
> Improve error given on instantiating event with invalid planet or system references

- source/PlayerInfo.cpp
**Feature:**
As pointed out by this comment https://github.com/endless-sky/endless-sky/pull/7730#issuecomment-1329872648 a last spaceport save would be nice to have.
So this PR adds exactly that.
N/A
When you're lost in space you know what last save was "safe".
I did not test this given I'm not on my main computer but there is no way this fails, right?
Used "last-spaceport.txt" as a name so it doesnt mess with anything since there are no spaces or special characters.
N/A
N/A
> Feat: add a save for the last spaceport

- data/human/outfits.txt
- source/Ship.cpp
**Feature:**
This is an alternate PR to PR #7460 which *only* removes the universal ramscoop. @warp-core suggested that just removing the universal ramscoop without transferring it onto the various drives would be preferable, so here it is by request. I would like to make it clear I think this PR is the better one, however I was under the impression that some people preferred the compromise of removing the universal ramscoop from being baked into the game engine, and instead putting it out where it is accessible to content creators, plug-in creators, and people editing their datafiles.
- Universal fuel ramscoop trivializes fuel management, ensuring that there is never any real risk to disregarding one's fuel gauge.
- Universal fuel ramscoop also creates the lore that any ship in any …
> refactor(code): Remove universal ramscoop

- data/wanderer/wanderers start.txt
Danforth's cruiser is now timid rather than heroic during Wanderers: Alpha Surveillance G.
This follows immediately from Danforth saying "My ship is no match for them. Let's get out of here.", so going off that he should probably be trying to avoid combat, rather than flying his cruiser directly at a 349.
> Danforth is now timid when facing Sestor ships in Wanderers: Alpha Surveillance G

- data/human/variants.txt
Renames all Afterburners in human variants.txt to Volcano Afterburners (2 variants used in HR and 2 other variants).
> Rename remaining Afterburners to Volcano Afterburners

- data/governments.txt
- data/quarg/quarg missions.txt
- data/quarg/quarg.txt
**Content (Government Interaction Thing)**
The Intrusion Countermeasures description mentions you don't want to get caught by the Quarg with their equipment.
This PR makes it so that all the Quarg outfits are  considered atrocities by them now, and so would result in the player getting imprisoned for life if caught.
~~Currently ships can't be added as atrocities, but when that's possible, should add in the Quarg ships to the list as well.~~
I've now added a mission that'll account for the Quarg ships, and result in the same death endpoint as the outfits do. Thanks Hurleveur for providing the mission code on that.
> Quarg Consider their Outfits and Ships Atrocities

- data/hai/hai fleets.txt
- data/hai/hai reveal 4 middle.txt
- data/hai/hai reveal 5 philosophers.txt
The Sea Scorpion was added to the Unfettered's ship but it's not seen in HR because it's using a copy of the `Large Unfettered` fleet.
In order to address that and any similar issue in the future I removed the copy, and replaced references of it by references to the actual `Large Unfettered` fleet.
It is not needed to define a copy of a fleet just to change the government, that can be done by the NPC definition. Since these fleets are only used in NPC definitions this will not cause any issues.
> Content: address wrong usage of Unfettered fleet (HR)

- source/AI.cpp
This saves a noticable number of shared_ptr instantiations that show up in a profiling run, and actually seems to make AI::Step() noticably faster.
> Re-order AI::Step Minable checks for performance

- source/PlayerInfo.cpp
Renaming it means it will be at the bottom of the list, suggested by warp-core.
I personaly dont mind it either way but others agree with that, and its not hard to change.
> rename the last spaceport save to previous spaceport

- tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
https://github.com/endless-sky/endless-sky/pull/7737 when this was merged it made Quarg kill you in the "death sentence" conversation.
Basegame they don't scan you but in this test they do, so I just gave them the default conversation for the test.
Not sure how dying in middle of space and conditions work out but best not to take risks if the change is one line and can't hurt.
> Fix: false positive in integration test

- source/Mask.cpp
- source/Mask.h
**Performance:** This PR improve performance of `Mask::Collide` by adding a cheap "broad-phase" test
As outlined in #6329, one of the (most?) prominent code path is:
> CollisionSet::Line (26.1%) spends a lot of time inserting into a set and calling Mask::Collide.
As far I can see, the member `Mask::Collide` has three ways to return:
1) After checking that the distance of the starting point is so big that even with removing the distance to the end it can "reach" the `Mask::radius`... Put another way: if you draw a circle around starting point of radius equal to the length of the segment, you never touch a circle of `Mask::radius`
2) There's a check to see if the starting point is contained in the `Mask` outline
3) There's a check to see if there's an intersection
Without (I admit, I'm …
> Add a coarse check on `Mask::Collide`

- tests/unit/src/test_esuuid.cpp
- tests/unit/src/text/test_displaytext.cpp
- Uses `std::list` instead of having two vectors (the defaulted noexcept move constructors need to be added because std::list has a throwing move constructor)
- Makes the standard layout check be dependent on std::string, since if it's not (like on the MS STL) the test fails
> Some fixes to the unit tests

- source/PlayerInfoPanel.cpp
**Bugfix:**
The flagship pointer was being dereferenced without first checking that it isn't null. In the case where you just sold your only unparked ship, this would cause a crash.
Sell the flagship and try opening hte player info panel. Without this PR, the game crashes.
[crash tester.txt](https://github.com/endless-sky/endless-sky/files/10187629/crash.tester.txt)
> Fix crash when opening player info panel with no flagship

- source/CollisionSet.cpp
- source/CollisionSet.h
**Performance:** This PR improve performance of `CollisionSet::Line` by replacing `std::set` with `std::vector` and making it a member.
As outlined in #6329, one of the (most?) prominent code path is:
> CollisionSet::Line (26.1%) spends a lot of time inserting into a set and calling Mask::Collide.
Replacing that `set` with a more cache friendly `vector` helps improving performances, as anyone can see removing the last commit. [Here](https://github.com/endless-sky/endless-sky/files/10122710/CollisionSet_Line.ods) some numbers.
* No binary search: just a find seems fine because the set of checked objects is limited: on first commit I collected the total number of the objects and is quite low. That can be shown printing `GetNumSamples()`.
* It seems that making the `vector` a member will …
> Improve `CollisionSet::Line`

- data/human/names.txt
**Bugfix:**
"Fury" was entered twice on the names list for "bad outcomes", and I've noticed Fury coming up as a pirate ship name at least six times in an hour, although I was using the all-content-plugin (I don't see anything there that would affect this, though). I removed the extra entry and should have fixed everything else that happens with that change. 
It's a simple fix so I don't know if I have to do anything. I suppose I can download my fork and see if Fury doesn't pop up as often?
> Fix 'Fury' appearing too often as a pirate ship name

- CMakePresets.json
This fixes the issue of the test preset `*-test` and `*-benchmark` not running any tests due to a missing configuration field.
> test(unit-test-buids): Fix test presets not working

- source/main.cpp
This reduces the delay from 3 seconds to 1 second. I execute a couple of integration tests in debug mode and 1 second is more than enough time to keep track of what is going on. 3 seconds is just too much.
> test(ui debug delay): Reduce the input delay when debugging integration tests

- data/hai/hai missions.txt
The text of the initial Nanachi mission are specific to Giverstone as a location. It describes a little used spaceport with large mineral hauls on offer that are inappropriate for a heavy shuttle. The mission offer, however is set to the maximum range for the heavy shuttle and can offer in Unfettered space and as far away as Hai-Home, locations which don't fit with the description. This change sets the job to offer at Giverstone.
The change is straightforward. The syntax checker in VS Code reports no issues. I don't have a pilot in a state to readily test it.
> Hai: Set Nanachi job to offer at Giverstone

- source/ShopPanel.cpp
**Bugfix:**
The support for offering missions in the shipyard and outfitter included the same special case used in the shipyard where, if no more missions are available for the shipyard or outfitter, it will offer any landing missions that were not already offered.
This makes some sense in the spaceport since it is possible to depart from the spaceport without visiting the normal `landed` panel, but this is not the case for the shipyard and outfitter, we must pass through the planet panel before leaving.
Additionally, it results for some perhaps undesired behaviour where, for example, James appears immediately upon purchasing a ship, instead of after leaving the shipyard with a ship.
I expect it is also now possible to get other missions offered in the shipyard or outfitter when they …
> Do not offer landing missions in the shipyard or outfitter

- data/human/fleets.txt
**Content**
Made the large syndicate fleet slightly larger on average.
Specifically:
The variant that consisted of a single laser Splinter (one low-end medium warship does not in my mind constitute a large fleet) has had three quicksilvers added to match some of the other variants that feature Splinters.
Also added two variants with both of the Syndicated Systems heavy warships, one with the stock Vanguard and the Protector (Proton) and one with the stock Protector and the Vanguard (Particle).
This was prompted in part by the fact that the Raider Attack missions which appear post FW in Syndicate space have become much more difficult with the addition of Firelight missiles to the Palavret, but while those missions could be rebalanced separately I think the very small size of Large …
> Enlarge large syndicate fleet

- data/hai/hai reveal 1 intro.txt
**Bugfix:** This PR addresses issue https://discord.com/channels/251118043411775489/536900466655887360/1051558436183220254
Adds Watcher to the planets this mission should not be offered on
> fix(minor): HR: "Hai Leaks Response 2B" do not offer on Watcher

- .github/workflows/cd.yaml
This PR simply removes the basic Ubuntu CD job. That job isn't very useful because the binary created is only usable on a specific Ubuntu version. For Linux CD releases the AppImage CD is the one to use.
> Removes the Ubuntu CD run

- source/Ship.cpp
**Bugfix:** This is an alternative fix to #7862
This fix is from @vitalchip. All I did was test it and make a PR.
**Important: There are two competing solutions. Please discuss them here: https://github.com/endless-sky/endless-sky/issues/7862**
Carriers will refuse to Carry() a disabled ship.
This does fix the one reproducible test case I have for the Stormhold mission (#7662)
However, I expect there are many corner cases this will break. This is the correct fix for the problem, though.
This save file can be used to verify the bugfix. The bug will occur when using 0e7747e7f, and will not occur when using this branch's build.
[Friction Diction~3026-01-21  should work but does not.txt](https://github.com/endless-sky/endless-sky/files/10213016/Friction.Diction.3026-01-21.should.work.but.does. …
> Fix from @vitalchip: Ship::Carry() refuses to carry a disabled ship

- SConstruct
Some Linux distributions seem to require an explicit import of DefaultEnvironment. Thanks to OpalMist on Discord for reporting
> Import DefaultEnvironment from Scons

- data/human/jobs.txt
- utils/test_parse.ps1
- utils/test_parse.sh
This PR does the following:
Powershell:
- Remove AppVeyor logic that isn't used anymore
- Add the optional parameter to specify the config path to pass to the executable.
- I removed ` -or $Env:OS.ToLower().Contains('windows')` because `$Env:OS` is not portable
- Added support for MacOS
- Don't show the error output is twice
- Actually write the error message to stderr. Specifying the category seems to suppress the output (wtf), so I just removed it.
Bash:
- Fixed abort in CI when called with no config folder
Tested the scripts locally, it works! I also added a dummy change to verify that it works in CI too.
> Test parse script improvements

- data/human/deep missions.txt
Change 'exoctic' to 'exotic' in description of goddess stone.
None. One word change. No syntax affected.
> Skadenga: Correct typo

- .github/workflows/ci.yml
- data/human/jobs.txt
This simplifies the data parsing CI: Instead of running 4 jobs (one one each platform and an additional one for the integration tests), it only keeps the Windows data parsing job and merges the integration test checks into it as well.
The reason for this is that it is not necessary to parse the data files on each OS; there's nothing OS specific so the 3 jobs will always have the same output.
As a result of this, the MacOS job doesn't have to upload or cache any binaries anymore.
CI will test it, but I'm only removing stuff.
> Simplify data parsing CI jobs

- data/hai/hai missions.txt
**Bugfix:** This PR addresses a balance issue with the Nanachi accessibility.
The Nanachi missions are designed, I gather, with the primary aim of being post Hai Reveal content. This is fine. They have an alternate criteria that allows them to be accessed prior to Hai Reveal, namely acheiving 2B Networth along with a combat rating of 1200. Now, the combat rating of 1200 is "seasoned fighter", which seems like an appropriate skill level for the mission. 
The Networth, though... Well, just taking a look at things. Right now, the biggest, most expensive ship I can buy is the Shield Beetle, and that's a bit under 34M. To achieve this networth, I'd need a fleet of almost *sixty* of them. (to be exact, 59 Shield Beetles and one additional >12M ship). 
Just to be clear, Networth includes bank …
> fix(content): Make Nanachi pre-HR requirements not encourage mega fleets

- data/human/free worlds 0 prologue.txt
Recent changes to scanners effectively require multiple scanners to be install to complete the FW scanning missions. This PR modifies the initial conversation to let the player know that multiple scanners will speed the scan time.
Text was added within existing syntax boundaries. Syntax checker in VS Code reported no issues.
> FW: Add advice on purchasing multiple outfit scanners

- data/map.txt
- data/remnant/remnant 2 side missions.txt
**Bugfix:**
Thanks to @samoja12 for reporting this on Discord.
https://discord.com/channels/251118043411775489/688532441324847150/1050574382369615906
Add `"remnant capital"` attribute to their three most developed planets, and use that as a requirement in the location filter for the source of the Celebration mission since it can otherwise offer on Ssil Vida and Esquiline where the events occurring don't make sense (Ssil Vida is also the destination, so it doesn't make sense for it to offer there, both in terms of mission design and the request made in the conversation.)
I'm not set on the attribute name, an alternative I considered was `"remnant urban"`.
Used the `--matches` command line argument for the executable to test the previous location filter and this one against a game with all …
> Prevent Remnant Celebration 1 occurring in non-sensical places

- data/interfaces.txt
- source/Interface.cpp
**Bugfix:** This PR addresses issue #7918
Previously using TopLeft() instead of Center(), which made all line elements shift to the left by 50%, and made it impossible to anchor them correctly.
The line elements are now rendered on the configured coordinates, and the existing line elements have been changed from "from" to "center", which keeps them where they are expected.
Verified the hiring, trade, and bank dialog line elements are visually unaffected, and verified that adding a new line anchored to both sides of the screen now works.
> change line to Center() as expected by shader

- data/map.txt
**Content**
Replaces the incorrect planet definition in Yli with one that works.
> fix(content): Gegno Yli Planet Fix

- data/korath/korath jobs.txt
- data/korath/korath missions.txt
- data/korath/korath news.txt
- data/wanderer/wanderer jobs.txt
- data/wanderer/wanderer news.txt
- data/wanderer/wanderers middle.txt
**Bugfix:**
Thanks to `@bossrman#0358` on Discord for reporting this.
When the final Wanderer Sestor mission was refactored to remove the need for patch missions on new saves, the name was changed. A number of jobs, spaceport conversation missions, and news items were checking for the condition indicating the mission with the old name was done and were not updated to check for the new one.
This PR sets a new condition `wanderers sestor done`, similarly to some used in the FW story, for which all these things will now look.
None yet.
If you really want one, I'll make one, but it's perhaps a little excessive.
> Update post-Sestor Wanderer and Korath jobs, news, etc

- data/human/free worlds 3 reconciliation.txt
**Bugfix:** This PR addresses a bug mentioned on Discord
Adds `clearance` attribute to `FW Pug 2C: Hyperdrive` and `FW Pug 2C: Scram Drive` missions so now the player can land without bribing if they had their Jump Drive installed in the campaign by the Syndicate.
done.
> fix(content): Add clearance to all FW Pug 2C variants

- data/remnant/remnant 2 side missions.txt
I just did the shattered light missions, and I liked them. One thing that stuck out to me though was that after finding the ship in Levana the next mission sets a waypoint in Coluber. The ship wasn't even found there, and when you go to Coluber its not there. So I decided to move the waypoint to where you found the ship and add an on enter message saying its not there.
You could either have  the on enter message be in Coluber, or have the waypoint be in the system where you Dromedary goes after you scan it in Levana.
> Remnant shattered light tweaks

- data/human/outfits.txt
Figured this was an oversight, considering the cloaking device predates the unique category
> Change Cloaking Device's Category to "Unique"

- copyright
- data/hai/hai news.txt
- data/hai/hai reveal 2 start.txt
- data/hai/hai reveal 5 philosophers.txt
- data/hai/hai reveal news.txt
- data/whispering void/critters.txt
- data/whispering void/elenchus.txt
**Feature:** Transfers copyright of Hai Reveal
I'd like to keep my name off of copyrights. Any Hai Reveal files with my name on it that had significant work from MasterOfGrey are now (C) MasterOfGrey. The ones that didn't are now Michael Zahniser. (I think the news was 100% me, but i'm only 85% certain of that. @MasterOfGrey can correct me if I'm wrong.)
The recipients of the copyright, or their legal representatives, should approve this PR.
Code is 100% faster?
> Sign over copyright of Hai Reveal to MasterOfGrey and Michael Zahniser

- data/map.txt
Adds a tribute fleet for each of the 3 default Unfettered planets.
They would not accept tribute on the new ones; they don't even let you land there, and most importantly there isn't anything to tribute from there (yet), the Unfettered understand tribute as food, and money. In order to be considered serious you need to have a significant battle reputation.
I tried to not make the fleets too strong, they are all below remnant level of power.
Darkcloak is well defended being the shipyard and the point from where all ships go, to Wah Ki or to Wanderer space.
Warfeed is their only source of food, they will fight to the last to defend it. That fleet is there to defend the world against potential Korath raids.
Firelode does not matter much. It produces heavy metals but it being cut won't …
> Content: add tribute fleets for the unfettered

- data/hai/hai outfits.txt
- data/hai/hai reveal 1 intro.txt
So now that #7210 has been merged it was time to look into the Geocoris rescue sequence in Hai Reveal again to fix the "needing to land, swap flagship, take off and land again" issue.
I originally had this rolled into my collection of changes I'm fixing on my own playthrough, but on consideration I thought it was better presented to be tested and inspected as its own thing since it's using a brand new feature.
> fix?(content): HR Geocoris sequence rework

- data/human/free worlds 1 start.txt
Remove redundant wording from a mission: "sitrep on the situation."
Change made within syntactic boundaries. No breaks reported by VS Code.
> FW: remove redunant wording

- data/coalition/coalition outfits.txt
**Content (Outfit Description Buffing)**
Like many reactors in the game, the Heliarch Reactor Modules are written off as simply being nuclear reactors (assumed fusion, due to the great efficiency). To add some more lore/fluff to their descriptions, and add some more variety to the reactor category game, this PR just updates the descriptions of both Reactor Modules, specifying that they use antimatter catalyzed fusion in order to achieve greater outputs, and linking the advancement to their efforts in understanding the Quarg tech they looted/stole.
The idea to use the antimatter stuff specifically is from @Azure3141 , who also wrote the initial extra paragraphs to go with explaining it in the reactor descriptions. Thanks again!
> [Coalition] Heliarch Reactors Use Antimatter Catalyzed Fusion

- source/Color.cpp
- source/Color.h
- source/Government.cpp
- source/Government.h
- source/UniverseObjects.cpp
**Feature:**
Currently, a government colour must be provided as a literal in the government definition.
This PR adds support for instead referencing a named (stock) colour by storing the colour in the government object inside an ExclusiveItem that can point to a stock colour in `GameData::Colors()`.
This could be especially useful in the cases where we have multiple internal governments which we want to appear identical to the player except for some slight behavioural differences; their colours could be defined once and then referred to instead of having the literals repeated many times.
~~It may perhaps be a good idea to add an `isDefined` member to `Color` and check this for every colour in `GameData::Colors()` to ensure any colour names being referred to have actually been defined. I …
> Governments can refer to named colours

- source/MapPanel.cpp
- source/PlanetLabel.cpp
**Refactor**
`MapPanel::DrawMiniMap()` was doing some stuff to colour values to achieve the same end result `Color::Additive()` does, so I've changed it to use the method of Color.
I also made a change to the `PlanetLabel` constructor but I think that would have a larger performance impact (still not massive,  it'll only be a few extra floating point multiplications, but enough that I don't think it's worth the simplification, the change there is arguably not simpler to read.)
There's also this but I don't think a combination of the existing Color methods can achieve this result.
Maybe `.Transparent(1.5f).Opaque().Transparent(.4f)`, but that's pretty terrible.
https://github.com/endless-sky/endless-sky/blob/31b2bcda12672199d20e59ce78dd61a6eea4e689/source/MapPanel.cpp#L600-L604
> Use existing Color methods in MapPanel

- CMakeLists.txt
- CMakePresets.json
- readme-cmake.md
- source/Files.cpp
This PR includes 3 improvements to the MacOS CMake build:
1. Do not create a bundle by default. Bundles aren't updated when new data/image/sound files are added, so they're not useful for active development.
2. Remove the xcode presets. Use the macos presets instead with `-G Xcode`.
3. The workaround is not needed because SDL_GetBasePath returns the correct path already.
> Improvements and fixes to the MacOS CMake build

- data/governments.txt
Many governments use the same colours, leading to repetitions of the same colour literal throughout the file.
This PR uses 4dbbb5e to define those colour literals once and have the relevant governments refer to those named colours instead.
The named colour is defined above the primary government to use it. In most cases, this is the first government to use it, but the Republic colour, for example, is defined immediately above the Republic government even though the Navy (Oathkeeper) government has used it further up.
I notice that a lot of these probably don't need to have colours at all, so I'm wondering if the colour should just be removed from those governments entirely?
Also, moved the Elenctic Commune government up to where it should be alphabetically. It looks like it wasn't moved …
> Use named colours for governments

- data/governments.txt
- source/UniverseObjects.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #7978
When loading a colour definition, the game will now accept definitions that only include rgb values, and default the alpha value to 1.
Also, remove the alpha values fromm the government colour definitions added recently.
An alternative to this approach would be to pass `Color::Load()` a DataNode, instead of parsing the node in UniverseObjects and passing four doubles to `Color::Load()`, but, Color doesn't currently include any other class, so maybe it's better not to make it depend on DataNode?
```
color "with alpha" .5 .5 .5 1.
color "without alpha" .5 .5 .5
```
These will result in identical colours.
If the actions pass, I think it's probably good?
N/A? Unit tests for UniverseObjects seem a bit …
> Named colours default alpha to 1

- source/Hazard.cpp
- source/Hazard.h
- source/Weather.cpp
**Feature:** This PR implements the feature request detailed and discussed by me
For people who like playing with hazards and envoiremental effects, it can be really annoying to not be able to specify lower numbers for the envoiremental effect amount.
This PR modifies this to accept numbers in the float range.
Of course you cannot generate half of an effect, that is why the total number will be rounded.
`"environmental effect" "blue nebula fragments" 0.01`
Tested it with one of my own effects.
N/A
> Feat(enhancement): Accept float quality precision for envoiremental effect amount

- data/map.txt
**Bugfix:**
A `planet` which is a wormhole should have the relevant `wormhole` object assigned to it.
This does not seem to be done for the Pug Wormhole at the moment.
soon:tm:
As above.
> Assign `wormhole "Pug Wormhole"` to `planet "Pug Wormhole"`

- data/interfaces.txt
- source/Radar.cpp
- source/Radar.h
- source/StellarObject.cpp
- source/System.cpp
Fix #7979 
As described in that issue, I have a lot of trouble in differentiating the star(s) from whatever I have selected and the unfriendlies. Only on close inspection is the difference visible.
This PR adds the support to have a unique star color specified in interfaces.txt which is used exclusively for coloring the star on the radar. As this exposes the color in the data files, it can then be manually adjusted if people wish to do so.
I have picked .6 .6 .6 .0 because stars share significant similarities with the inactive planets. We cannot land on stars, and generally don't interact with them at all. However, it is a little brighter to help it stand out from the other inactive planets, and as such allow people to determine where the center of the system is to assist in collecting …
> feat(UI) Giving the Star a unique color on the Radar

- source/PrintData.cpp
- source/PrintData.h
**Feature:**
It seems I previously overlooked the option to print a list of shipyards/outfitters and the items they sell instead of a list of ships/outfits and the sales they appear in.
N/A
Prints shipyards and outfitters:
```
EndlessSky.exe --sales
EndlessSky.exe --sales -s -o
EndlessSky.exe --sales --ships -o
EndlessSky.exe --sales -s --outfits
EndlessSky.exe --sales --ships --outfits
```
Prints shipyards only:
```
EndlessSky.exe --sales -s
EndlessSky.exe --sales --ships
```
Prints outfitters only:
```
EndlessSky.exe --sales -o
EndlessSky.exe --sales --outfits
```
The result should look something like:
```
shipyards;ships
<shipyard name>;<ship 1 name>,<ship 2 name>
<shipyard name>
<shipyard name>;<ship 1 name>
```
I've also made some changes to names of a method and various variables …
> Print shipyard or outfitter list with items available in each

- data/human/near earth jobs.txt
**Bugfix:**
It is currently possible for jobs going to Earth for Earth Day celebrations to offer with deadlines after Earth Day (22nd April). These jobs are, however, failed on that date, and so they may offer with deadlines beyond the date on which they will fail.
This is not good.
This PR uses two of the new autoconditions, `days until year end` and `hyperjumps to system: <system name>` to ensure that the job will not offer at a point when the deadline date will be beyond Earth Day.
`days until year end` is used to ensure no need to treat leap years differently (since the `days since year start` value for 22nd April is different on leap years.)
I've also explicitly set the deadlines of the missions to `0 2`. These are the default values that were already in use, but since the offer …
> fix(content): Prevent Earth Day jobs offering with deadlines after Earth Day

- source/Engine.cpp
- source/PlayerInfoPanel.cpp
**Bugfix:**
Thanks to @1010todd for reporting this on Discord.
Fixes a crash introduced by https://github.com/endless-sky/endless-sky/commit/95b054f2e5655fcdcaf9cf98893c7876f5384f4e.
Checks that the flagship pointer isn't null before attempting to dereference it.
I suspect there are numerous circumstances where this crash may occur, but the one raised in the original report was of selling the flagship and exiting the shipyard with no ships that can become the flagship.
I also noticed another point where the flagship pointer is dereferenced without checking that it is not null, so added a check to that, though it wasn't responsible for this crash.
You can see the crash occur if you start a new game and just leave the shipyard before buying a ship.
With this PR, it no longer happens.
This …
> Fix crash when you have no flagship

- data/help.txt
- source/OutfitterPanel.cpp
- source/Panel.cpp
A big problem of this game is unknown features.
Part of those features are shown in the tutorial but because they overwhelm the player so much nobody reads them.
This just makes only one of them show per outfitter panel (tested, it works)
Also adds a small title of the tutorial:
OUTDATED (now shows `Multiple ships controls:`) as a title
> Tutorial: don't show more than one tutorial prompt at a time in the outfitter + show title

- source/Government.cpp
- source/Government.h
**Bugfix:**
https://github.com/endless-sky/endless-sky/commit/b7ebc42c26d20a7f37edafb7d8450ff029e98252 introduced a crash on... well, a lot of things, ~~let's not talk about it.~~
This fixes that issue.
The problem was that `std::vector<>::operator[]` does not insert if the given offset is out of bounds, and its behaviour in this case is undefined.
Instead, use an `std::map` and do `find` to check if the desired element exists before attempting to retrieve data from it.
Played the game. It doesn't crash anymore!
> Fix another crash

- data/coalition/coalition missions.txt
**Bugfix**
The sentence wasn't correct as per Coalition grammar. It was pretty easy to spot, since the rest of the dialogue is written so consistently with this grammar.
> Coalition Pilgrimage dialogue: minor grammar fix

- source/Government.cpp
**Bugfix:**
Thanks to @Hurleveur for discovering this in #8016.
`child.Token(1)` is the wrong token, and may be out of bounds.
`child.Token(0)` is what we actually want.
Launching the game with this build with the data changes from #8016 actually works, now.
> Fix custom penalties again

- source/StartConditionsPanel.cpp
reverts a change that removed the setting of a necessary interface variable.
tested, info is showed again
create a new pilot and see everything displayed correctly
> Fix: Display Info of starts

- data/human/hails.txt
I noticed the following message appear today:
Looking through the human hail.txt file, it appears there is a missing 'word' in 'friendly navy' phrases.
I've corrected this and can see the messages appearing correctly now.
> Fix missing 'word' in 'friendly navy' phrase.

- data/coalition/coalition ships.txt
**Content Fix (Missing Outfit)**
The Kimek Briar was accidentally left out when Reverse Modules were added to Coalition civilian ships.
This PR just adds one Large Reverse Module to both stock and the Miner variant.
Reported by DoomKorath on the discord, good eye on that.
> Add Reverse Modules to Kimek Briar

- credits.txt
**Feature:** This PR implements the feature request detailed and discussed in issue #7583
Although PR #7958 is adding Loading Hints to the start up, it would also be useful to point players towards the wiki manual.
Starting the game displays the updated credits including the link to the player's manual.
N/A
N/A
> Docs(manual): Add a reference to the player's manual in the credits.

- CMakePresets.json
- source/Weather.h
This fixes a misconfiguration by VSCode using the clang-cl preset.
> Specify a toolchain host architecture for the Windows Clang build

- source/ShipInfoPanel.cpp
**Bugfix:**
Thanks to @Terin for reporting this on Discord.
The iterator is initialised with the `.begin()` position of the `panelState.Ships()` vector, but it is subsequently compared to `player.Ships().end()`. Since this is the past the end iterator of a totally different vector, and so using its past the end iterator while boundary checking `shipIt` is inappropriate.
This also fails a debug assertion in the MSVC compiler.
While `panelState.Ships()` returns a reference to the vector `panelState.ships`, which was initialised with `player.Ships()`, `panelState.ships` is not a reference, but instead copies the `player.Ships()` vector.
Launch the game, compiled to the Debug target through Visual Studio (using the clang-cl preset) and open the player info panel and then the ship info panel. …
> Fix vector iterator incompatibility in ShipInfoDisplay

- .gitignore
**Bugfix:** This PR addresses issue discovered during testing that Git will attempt to track all the files created by Visual Studio as part of an install test.
Github currently tracks the `install` folder created by Visual Studio during the build process, potentially considering the creation of an internal complete build as something it needs to track to upload to the repository.
This adds the `install` folder to the list of ignored locations so that Git does not try to capture changes therein.
N/A
N/A
> fix(code): Adding the "install" folder to gitignore

- tests/integration/IntegrationTests.cmake
If any errors are emitted when discovering the integration tests, then the build output shows them and it creates the errors.txt file. This PR suppresses both of these, because they aren't useful.
Added a dummy error, and without this PR the build output is spammed and a errors.txt file is generated.
> Eat any parse errors when discovering integration tests

- data/remnant/remnant outfits.txt
Added `"installable" -1` to Void Sprite Parts definition, so they cannot be installed in an outfitter.
- The player is not able to install Void Sprite Parts on their ship.
- Void Sprites still have their parts installed.
> fix(content): Make Void Sprite Parts non-installable

- source/Planet.cpp
**Bugfix:**
Thanks to @Saugia for reporting and helping debug this on Discord.
Check if the ship pointer is null *before* dereferencing it.
The game doesn't crash anymore!
Go get your ship destroyed in a system with a wormhole, that'll probably cause it to crash.
> Fix nullpointer dereference, you guessed it, with no flagship!

- data/gegno/gegno intro missions.txt
**Content (Fix)**
This PR adds an important line missing in the Gegno Hunter fleet mission, that while missing, causes the fleets to spawn infinitely and severely hurt game performance.
I'll be merging this immediately to avoid any more cases.
N/A
> fix(content): Gegno Hunter Fleet Hotfix

- data/persons.txt
I made the mistake of using Zitchas's person ship frequency for both Gefu's and Grey's ships, which is at 1000, compared to all other person ship rates, which are at around 200-300 (for some reason I thought a larger number meant less frequent, like fleets in the map file). Now you won't see those two more than the others! (Sorry Grey and Gef, you had your time in the spotlight.)
N/A
> feat(content): Nerf rate of Gefu & Grey's person ships

- data/map planets.txt
I slashed New Tortuga's tribute amount down to a sixth of it's original amount due to how obnoxiously high it was. I'm open to changing the amount if it seems too low, but I'd like to keep it down below greenrock's amount of 1800 credits. Thanks to @Arachi-Lover for pointing this out on discord.
I tested multiple different planets to gauge their tribute with my fleet of various assorted warships. I found that with New Tortuga zero got killed, with Greenrock one got killed, and with Rust, surprisingly, two got killed. Due to how strong rust is I bumped it all the way down to 1000 credits. I'd say that it needs to be below Greenrock's tribute amount for sure, but I'm definitely open to changing the value if it feels too low.
> Significant Slash to New Tortuga's Tribute Amount 

- data/hazards.txt
- data/map systems.txt
Neutron stars currently look impressive, but that's it. This seems strange when you take in account that they are some of the most dense objects in the universe with incredible strong magnetic fields. That's why I added a weak hazard to them, that attacks shields.
The only neutron star right now is in the rulei system and therefore saugia said their ship should be able to nullify the effects of the hazard. Right now the rulei have no shield generation, so it was impossible for me to adapt the damage to their generation.
But they will probably get shield generation soon and I think the current value should be in an ok area?
If not we can always change it later.
> Content(hazard): Add a weak hazard to neutron stars

- tests/CMakeLists.txt
- tests/integration/IntegrationTests.cmake
This fixes the CMake build if the current path contains whitespace.
Cloned the repo in a path containing a whitespace and verified that everything works.
> build(cmake): Fix CMake build on path with whitespace

- source/ConditionSet.cpp
- source/ConditionSet.h
- source/Test.cpp
- source/Test.h
**Feature:** This PR implements a feature of the integration testing framework #4308
The integration testing framework will now print all relevant conditions for a failing test, instead of only printing the conditions explicitly marked for testing.
This feature should reduce some overhead of defining variables twice when creating new testcases.
(Mockups)
Before:
```
Condition: "test: loopControl" = (not set)
```
After:
```
Condition: "test: loopControl" = (not set)
Condition: "variable I really want to see" = 7
```
N/A, just run the tests as usual.
Tested by printing all conditions in the test-listing from main.
Tested by making one of the tests fail, and verifying that the conditions were printed.
This is part of the automated testing suite.
None expected, should only be active when …
> test(integration): Print relevant conditions on test failure instead of only test conditions

- data/human/ships.txt
**Bugfix:** This PR addresses issue reported by RecursiveParadoz
Reduce stock torpedoes from 60 to 30.
- Raven has reduced long-battle torpedo inventory. This makes it a bit fairer for the player, who could never match this configuration.
Bought  Raven in continuous. Noted that it had more torpedoes than it can actually hold. Sold some. Wasn't until it was below 30 that I could reload it.
Any pilot can test this by purchasing a new Raven with and without this fix.
> fix(content): Raven has too many torpedos

- tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
- tests/integration/config/plugins/integration-tests/data/tests/tests_conditional_choice.txt
- tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_attribute_autoconditions.txt
- tests/integration/config/plugins/integration-tests/data/tests/tests_hyperjumps_to_autocondition.txt
- tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
- tests/integration/config/plugins/integration-tests/data/tests/tests_save_load.txt
- tests/integration/config/plugins/integration-tests/data/tests/tests_ship_sale.txt
**Feature:** This PR is a follow-up for PR #8174 .
Removed variables from the test-scripts that were once needed for debugging, but not anymore since #8174.
Was tested as part of #8174.
N/A
The test-scripts are likely more readable now.
> test(cleanup): Remove obsolete "test:" variables

- source/AI.cpp
I simplified the formula and prevented secretive ships from going beyond the fence when scanned.
I discovered this when testing it, and tested to make sure it fixes it properly.
> bugfix: secretive personality does not ignore fence and properly runs away

- data/hai/hai reveal 3 early.txt
**Bugfix:** This PR addresses issue #8115
Does a few things:
- Fixes the reported bug where the "overdone" text is presented on the final world.
- Also, prevents that secondary helper mission from presenting at all on the final step; it's weird to have that conversation after the `on stopover` conversation of the main mission.
- Removes the `ZZ` from the beginning of hte helper mission, it seems to just be an invitation for someone else to make a mission with a name beginning `ZZZ` which is just a bit silly.
Complete the final leg of the mission with the updated mission and don't get the secondary conversation inappropriately. …
> Hai Reveal: Fix Spruiking conversation

- source/Government.cpp
**Bugfix:**
Thanks to @Hurleveur for reporting this to me.
#7970 truly is the PR that keeps on giving.
It introduced a bug where loading custom values for a governments default penalties (for actions against itself) was silently skipped due to checking the size of the wrong node.
Add code to have the game print the `penaltyFor` table for every government and see that it now includes the expected non-default values, without this PR, it does not.
Without fix:
```
Remnant
1 -0.25
2 0
4 0
8 0
16 0.5
32 0.3
64 1
128 1
256 10
Remnant (Research)
1 -0.25
2 0
4 0
8 0
16 0.5
32 0.3
64 1
128 1
256 10
Republic
1 -0.1
2 0
4 0
8 0
16 0.5
32 0.3
64 1
128 1
256 10
```
With fix:
```
Remnant
1 -0.25
2 0.1
4 0.1
8 0
16 1
32 1
64 10
128 10
256 10
Remnant (Research)
1 -0.25
2 0
4 0
8 0
16 1
32 1
64 10
128 10 …
```
> Fix Government penalty loading

- source/MapPanel.cpp
**Bugfix:**
Fixes a logic error/typo in #7934 that means not all links will be drawn for wormholes connecting more than two systems.
Before:
After:
(Ignore the different colours. They're just me testing stuff.)
See screenshots
> Fix wormhole link drawing for wormholes connecting more than two systems

- source/Engine.cpp
- source/Ship.cpp
- source/Ship.h
**Bugfix:** prevents secretive provoked on scan ships from hailing the player if they are mute or if they do not have the same government
The CanSendHail method was located in the nameless namespace of Engine (dont ask me why) I moved it to ship so we can check before hailing the player to warn them we'll shoot them (or not)
if the tests run this is good; the code for CanSendHail is already used all the time, and there are checks within it.
and no referencing nullptr here (I added a check each time)
n/a
> refactor/bugfix: move CanSendHail to ship

- data/human/human missions.txt
- source/Mission.cpp
- source/MissionAction.cpp
This feature allows the `<payment>` text replacement to display the `"apparent payment"` of a mission, if no payment is present in the current trigger. Having any `payment` in the current trigger will work as before, overriding this default.
If there is both a top-level `payment` and `"apparent payment"`, the apparent payment takes priority.
This feature allows hard-coded 'fake' payments to be replaced with formatted text.
Have a look at the edited missions.
All tests passed. The `A wolf, a goat, and a cabbage` mission displayed `100,000 credits` in the description, and `33,000 credits` in the `on complete` trigger. Regular missions still display their payment as before.
N/A
> Make `<payment>` work with `"apparent payment"`

- endless-sky.6
- source/main.cpp
**Feature:** This PR mutes the game when executing tests.
I just added a quick `Audio::SetVolume(0)` if a test is passed to the game loop. This doesn't affect any default settings for the volume, nor does it change how the game behaves when not running tests.
It muted during tests, and didn't mute when playing.
> Mute audio for testing

- source/ImageBuffer.h
- source/Sound.cpp
Like other versions before, gcc 13 moved some includes around and as a result <cstdint> is no longer transitively included. Explicitly include it for uint32_t.
(You can open a PR to add or improve a section, if you find them lacking!)
Built locally with gcc 13.0.1_pre20230122
> Fix build with gcc 13 by including <cstdint>

- data/human/human missions.txt
- source/Account.cpp
- source/BankPanel.cpp
- source/Engine.cpp
- source/GameAction.cpp
- source/HailPanel.cpp
- source/MapOutfitterPanel.cpp
- source/MapShipyardPanel.cpp
- source/Mission.cpp
- source/MissionAction.cpp
- source/OutfitterPanel.cpp
- source/Planet.cpp
- source/PlayerInfo.cpp
- source/PlayerInfoPanel.cpp
- source/ShipInfoPanel.cpp
- source/ShipyardPanel.cpp
- source/ShopPanel.cpp
- source/TradingPanel.cpp
- source/text/Format.cpp
- source/text/Format.h
- tests/unit/src/text/test_format.cpp
**Feature:** This PR implements the feature requested by @warp-core in #the-hub.
Adds a new function to Format that appends the credit/credits suffix to the formatted credit amount. This fixes a million minor formatting bugs and reduces the amount of duplicate code.
Checked the shipyard, jobs, salaries. Formatting works as expected.
> feat(enhancement): Add function for proper credit string formatting

- tests/integration/config/plugins/integration-tests/data/tests/tests_capture_override.txt
Some changes happened between the moment I wrote this test and when it got merged, this makes it conform to master by containing the mission in test data and removing the test conditions used only for debugging.
> Integration test: cleanup capture-override

- data/human/deep missions.txt
**Bugfix:** This PR addresses issue #7969
This fix was designed by @Amacita, ~~so blame him if it doesn't work.~~
`Deep: TMBR 0` will now fail when `Deep: TMBR 1` is offered instead of completing when you land at the destination after being offered the next mission.
`Deep: TMBR 0` will still appear in the mission list for a day or two after collecting `Deep: TMBR 1` (or, until a reload, whichever is first), I don't think it's possible to do any better than that currently.
[TMBR tester~Valhalla-before-receiving-TMBR-0.txt](https://github.com/endless-sky/endless-sky/files/10521108/TMBR.tester.3013-12-06.txt)
[TMBR tester~Allhome-with-TMBR-0-acitve.txt](https://github.com/endless-sky/endless-sky/files/10521111/TMBR.tester.3013-12-24.txt)
~~I didn't test this yet.~~
Using the attached save …
> Fix Deep: TMBR 0 persisting after TMBR 1 is offered

- data/human/free worlds side plots.txt
**Bugfix:**
The mission "FW: Zug Expansion" requires the event "tarazed diplomacy" to have fired, but that's a mission. This PR changes "tarazed diplomacy" to "tarazed assistance" based off the conversations in #7719  
Thanks to Kroniicoptor on Discord for pointing it out.
> fix(content): Make FW: Zug Expansion fire correctly

- data/hai/hai reveal 5 philosophers.txt
Fixes two instances where the Syndicate wasn't capitalized properly.
> fix(typo): Fix capitalization of Syndicate in HR

- data/sheragi/archaeology missions.txt
Regarding the archaeology mission chain to obtain the Emerald Sword.
Specifically the mission `Sheragi Archaeology: The Emerald Sword 2`
This PR contains small change to the conversation on Zug before heading out to retrieve the emerald Sword acknowledging Albert's willingness to simply allow the player to have the ship.
This PR is intended as a potential solution to the (in my opinion) slightly odd situation where an archaeologist is happy to simply promise you what feels like a priceless historical find.
The goal is to still give the player the ship, but to make it feel slightly more reasonable in the narrative.
I did not create a save file for this specific change.  Instead I wrote a plugin with the mission copied over and adjusted to be offered …
> content: Narriative change when first offered the Emerald Sword

- source/OutfitterPanel.cpp
**Feature:** This PR implements the feature request detailed and discussed in the comments of #6963.
List cost, mass, and installation requirements above the attributes and weapon data of an outfit in the outfit info display in the outshipper panel.
<details> <summary>Long images</summary>
Before | After
-- | --
</details>
Look at the outfit info display for various outfits and see that it appears as expected.
N/A
N/A
> List outfit cost and requirements above attributes and weapon data

- source/Panel.cpp
> fix(typo): Fixes a warning about the order of includes in Panel.cpp

- source/MapOutfitterPanel.cpp
- source/MapPanel.cpp
If there are outfits stored on a planet that doesn't have an outfitter, it makes storage on such planet unusable. This may happen, for example, if outfitters are removed by some events (like in Wanderer storyline).
This PR hides any in-game information about storage on planets without outfitters. The storage itself is left untouched in the pilots's save, so it'll be available again if the outfitter is reinstated.
Checked how it works: there's no storage indicator on the map; tooltip on hover doesn't show storage data, the same for the side panel.
No performance impact.
> feat(ui): Hide storage on planets without outfitters

- source/System.cpp
When you try to land on a non-landable planet or moon within sun's green zone, it tells you the planet/moon is uninhabited. But there are lots of uninhabited planets you can land on, so it shouldn't be a problem.
I reworded two standard landing messages and now they say there's no place suitable for landing.
Of course, there's a question why on the whole planet there isn't even a single larger grassland, but I think that's the difference between landable and non-landable planets.
> Change landing messages for uninhabited worlds

- data/interfaces.txt
**Bugfix:**
Thanks to @movingpictures for mentioning this in https://github.com/endless-sky/endless-sky/pull/8288#issuecomment-1418166305.
Fix the typo so the defined colour name matches the expected name.
This isn't detected by the data files CI because the colour is only referred to when it is used, which doesn't happen when loading. We might want to do something to improve that at some point.
> Fix typo in colour name

- source/Engine.cpp
- source/Preferences.cpp
For various reasons:
- @quyykk has noted that changing the zoom indices is undesirable.
- The new lower zoom levels result in previously reasonable asteroid densities consuming a significant amount of GPU time, and not drawing the asteroids altogether has been noted as being undesirable due to the interactions asteroids have with missiles (and any projectiles, but missiles specifically since they tend to have the longest ranges).
- Planet label overlapping becomes an issue again.
- Probably other stuff, check the bug reporting channel on Discord iff you want to know more.
> Revert "feat(UI): Additional zoom levels (#8081)"

- CMakeLists.txt
- readme-cmake.md
Some small tweaks to CMake:
- The minimum version is actually 3.21 and not 3.16 like I previously thought (whoops). This requires anybody on older distributions to upgrade (to Ubuntu 22, or the new Debian release coming up soon).
- Don't force a different triplet when using system libraries
- Install the `license.txt` file on Linux and Windows too
- Some additional comments
> Small CMake tweaks

- .github/workflows/cd_release.yaml
This changes the release workflow: Instead of creating a release in GitHub and then having to wait until CI publishes the assets:
1. Create and push a new version tag
2. Wait until CI finishes
3. There will be a draft release with the right assets
This simplifies the release process because the assets don't need to be built in a fork.
https://github.com/quyykk/endless-sky/actions/runs/4098609045
The generated draft release looks like this:
And can be modified before being published
> New ES release process that simplifies the existing one

- data/human/variants.txt
This switches out the basic ramscoop for the catalytic ramscoop on jump cruisers used in the assault on the Pug and by Danforth on the assault on Avalon. 
These ships are already fitted with the newest tech from the Deep including electron beams and typhoons. It makes no sense for them to have less capable ramscoops when they are using jump drives. While it doesn't affect the Pug fights it is needlessly problematic for the assault on Avalon where refueling is a critical component of the plan.
A previous PR using the Hai Reveal configurations was rejected but feedback indicated that this might be an acceptable alternative. See: https://github.com/endless-sky/endless-sky/pull/8063
Created ship using a custom start file.
> Catalytic ramscoop for jump Cruiser

- source/ConversationPanel.cpp
**Bugfix:** This fixes something I encountered while testing #7660 and an issue in the HR epilogue that has been brought up on Discord by various people (the most useful report coming from @Zitchas.)
When adding the text of the selected choice to `ConversationPanel::text` (the collection that stores the text that a conversation panel is displaying), it was looking up the selected choice in its own set of chioces (which only contain the choices that were being displayed) using the index of the selected choice in the underlying conversation, which counts all options in this choice node, not only those that were being displayed.
This means that, if the selected choice is after at least one hidden choice, the text conversation panel adds will be from a choice further down the list since the …
> Fix selected choice text added to conversation when some choice nodes are conditionally hidden

- source/AI.cpp
**Bugfix:** This PR fixes a subset of #8228
Some remnant fighters and drones spawn with 'disables' and 'plunders', which causes them to choose disabled 'olofez as targets - but they cannot actually shoot at them or board them, so they just stay there.
This PR makes it so any ship that cannot board and cannot attack disabled ships will not target them.
It seems to stop remnant fighters and drones from grouping up on the korath drones.
[Test Pilot.txt](https://github.com/endless-sky/endless-sky/files/10615157/Test.Pilot.txt)
> bugfix: Fix fighters choosing boarding targets

- data/hai/hai reveal 6 end.txt
**Bugfix:** Fixes #8295 by removing the mission and event
Hai Reveal [C05C] Cleanup Check and its event are not needed, so I deleted them.
Replayed Hai Reveal 4-6
> Hai Reveal: bug fix: remove unneeded clean-up mission and event

- data/hai/hai reveal 4 middle.txt
**Bugfix:** Fixes #8258 
Ensures the ongoing election update mission only triggers when the election is ongoing.
**Edit**: This actually uses an alternative fix, from @warp-core, rather than my original fix to cut off the mission after A12. That's because the text does not explicitly state the election has ended until A13. We may as well leave the election coverage open as long as possible so the player is more likely to see it.
Tested the election a few ways to ensure it works.
[Friction Diction~3025-12-22 TRY16 before A11.txt](https://github.com/endless-sky/endless-sky/files/10609206/Friction.Diction.3025-12-22.TRY16.before.A11.txt)
That's just before A11, which is when the election starts. After that, but before A13, you should see ongoing election coverage at most Hai planets and …
> Hai Reveal: bug fix: do not provide ongoing election updates after the election has ended

- data/hai/hai reveal 5 philosophers.txt
**Bugfix:** Fixes #8298 wherein passing through Hai Reveal part 5 once doesn't stop you from getting arrested a second time.
The two B05 missions (long and short) each refuse to start if the other has been offered. 
Tested the Timmy save (see below) from #8298 and also ensured that B05 would trigger as it should.
The previous save file from @ziproot was broken, and they've provided a new one.
[Timmerson.Timmy.Pre.Glitch.txt](https://github.com/endless-sky/endless-sky/files/10669442/Timmerson.Timmy.Pre.Glitch.txt)
When you fly to Earth, nothing should happen.
Here is another save, just before one of the part 5 routes. You need to depart and land.
[Friction Diction~3026-01-20 TRY20 before B05.txt](https://github.com/endless-sky/endless-sky/files/10637330/Friction.Diction.3026-01-20.TRY20.bef …
> Hai Reveal: bug fix: each HR5 path blocks the other from starting

- source/DamageProfile.cpp
Moves scrambling damage from the DoT with instantaneous analog section to the unique special damage types section.
This places it alongside disruption and slowing, rather than alongside ion, burn, leak, discharge and corrosion.
Also updated the comment to mention that scrambling is 50% blocked by shields, as it already mentioned the same about disruption and slowing.
> Recategorise scrambling as a "unique special damage type" rather than as a DoT

- data/hai/hai outfits.txt
- data/hai/hai ships.txt
The value detector added in PR #7019 received a substantial buff as part of PR #7649 resulting it now being the most powerful scanner in the game by quite a large margin.
Value Detector is too strong as it is currently. ~~I suggest dropping tactical scan from 92 to 20, and cargo scan from 88 to 35 to bring it just a bit above human tech overall like most other Hai outfits.~~
I suggest the following:
Tactical Scan Power 92 -> 35
Cargo Scan Power 88 -> 75
Cargo Scan Efficiency 16 -> 10
Mass/Outfit Space 3 -> 5
Add heat generation -> 2
As a point of comparison, the following chart shows the amount of tactical scan range that each scanner provides per unit of outfit space it uses:
<details>
<summary>Tactical Scan Range/Mass</summary>
</details>
The value detector tops the chart at 319.8 …
> feat(balance): Nerf the value detector

- data/gegno/gegno outfits.txt
**Content (fix)**
improved typo in a Gegno outfit description: "Ballis**t**ic Cannon Turrets"
> fix(content): Typo in data/gegno outfits

- source/Preferences.cpp
The "fancy" parallax option is pretty GPU taxing. The default should be the "fast" option, so that users on low-end hardware don't start to think that newer versions of the game use more resources than it actually needs.
> Default to "fast" parallax

- source/AI.cpp
**Bugfix:** This PR fixes #8228
It appears that the issue was caused by the NPCs re-targeting the ships they just boarded. At least, when I prevented that, it seems to have gone away.
I couldn't reproduce the issue after this fix. The only similar issue was a bunch of Ibis ships overcorrecting on the target and thus not boarding, but I believe that's being fixed by #8343. Other ships seem to work just fine, even if there are Ibis ships attempting to board.
I have observed that some fleets jump away after the flagship finished boarding, even if the other ships haven't; not sure if that's a bug, or that it's introduced by this fix. (The fleets seem to work fine, they just don't all finish boarding.)
Use the save file from the issue.
> bugfix: Fix ships attempting to re-board boarded targets (#8228)

- data/human/human missions.txt
This PR adjusts the display of the riddles in Dangerous Games 2. From the engine this was ported, the riddles were originally supposed to be broken up with newlines, making it more apparent that the first letters of each line in this riddle spell out "NORTH". The newlines were lost in the conversion process, so this manually breaks them up to show that off.
> fix(content): Adjust Dangerous Games riddle display

- data/human/human missions.txt
This closes #8340. 
This PR changes the conditions for Hai Wormhole Warning so that it can offer to the player. Thanks to luuiscool4567 for pointing it out on Discord a year ago.
While we're here, I can change the conversation so that it offers upon landing, because I feel like it would make more sense than right now. The player has to go to the spaceport first, and if it's so urgent that the intelligence officer has to pull the player away from what they are doing why isn't the officer just going right up to the player's door? I'd like other peoples' feedback first though.
[ES Tester.txt](https://github.com/endless-sky/endless-sky/files/10712330/ES.Tester.txt)
Go to Allhome, have the first contact mission offer, go to Farpoint or Prime and try and get the conversation. Works with this …
> fix(content): Let "Hai Wormhole Warning" offer correctly

- source/HailPanel.cpp
- source/HailPanel.h
**Bugfix:** This PR addresses issue #4875
Carryable ships (fighters and drones) no longer offer to assist you, instead going straight to the message indicating they are too small to have the necessary equipment.
Become disabled or run out of fuel and hail a fighter or drone for help and see this message instead of an offer to help following by this message indicating they can't after asking for help.
> Ships that can't repair you don't offer to when hailed

- source/AI.cpp
**Bugfix:** Ships try to stay near their target while scanning it, instead of moving erratically.
Reduces problems described in #8272, #7539, and #7640 caused by ships not trying to stay within their scanning range.
This only solves half the problem: the scanning formula nerfs scanners into oblivion, so that needs to be fixed too. PR #8288 improves the scanning formula to make scanners work again. The combined effect might make scanners too strong, but the tuning parameters added by #8288 can be adjusted to compensate.
A ship will try to stay near its target when scanning. Previously, the algorithm always used `CircleAround`, which is why ships moved erratically near slower targets, instead of staying within scan range. In this version, they'll still `CircleAround` fast-moving targets, …
> bug fix: ships scanning will try to stay near their target instead of moving erratically 

- data/hai/hai reveal 2 start.txt
Adds a missing 'you', and changes a pronoun from 'her' to 'them', as at that point the player is unable to tell what gender the Hai might be. 'She' is used once the player gets a good look at Ooonem.
> Fix typos in Hai Rescue: Ooonem

- source/AI.cpp
Summary
-------
When ships land on a planet or wormhole or board a ship... it tends to over-compensate by constantly turning left and right.
The following video shows the issue by showing constant over-correction.
https://user-images.githubusercontent.com/875669/218235164-8da2f77f-1ce2-4b62-9540-89caaea2fdea.mp4
Fix Details
-----------
Reduce the turning accuracy required when the ship is flying toward its target to land or board.
The following video shows the fix.
https://user-images.githubusercontent.com/875669/218235163-7834a677-73c2-446d-8cf2-a90c071c60ca.mp4
Related issues
--------------
* https://github.com/endless-sky/endless-sky/pull/8304
* https://github.com/endless-sky/endless-sky/pull/7703
Testing Done
------------
Performance Impact
------------------
None
> Bugfix: Reduce overthrusting when landing or boarding

- data/hai/hai reveal 4 middle.txt
**Bugfix:** This PR Fixes #8259
So this was gonna just be in one of my two other PR's, but it couldn't be sorted out as just a bug fix without player experience edits, and it couldn't be left to the player experience PR cause it is actually a bugfix that needs to happen.
So now it's its own thing.
In the issue Sigh said:
> I suspect this was left over from an old mission chain that was removed. Maybe, at one point, it was possible to check in with Alondo before Teeneep, but you can't anymore.
But this was not correct. You end up at a point where two different people ought to be reported to, and one of them has other information you want. So logically, you'd want to talk to the one with other information first.
However, this is intentionally a bad-timing situation.
If you were to get to …
> Fix(content): Sort out the lead from Alondo sequence (address 8259)

- data/human/paradise world jobs.txt
This PR shortens the description of Paradise Job: Debtors to fit into the description box no matter the destination name. Tested with Guardian Array Sapphire + 16 Autumn Rising as some of the longest planet/system names, and it still fit.
> fix(content): Shorten Paradise Job: Debtors description to fit

- data/human/ships.txt
Replaces the single meteor missile launcher on the stock Manta with two Torpedo Pods (and changes the ammo storage accordingly). Torpedo pods are sold on every non-pirate planet that sells the Manta, and Torpedoes are sold on every planet that sells it, so this makes sense.
The one asymmetrical Meteor Launcher just looked bad, and the Torpedoes should be more dodgeable for small maneuverable ships (their position right on the sides of the ship should stop it just point-blank destroying smaller ships like the bomber Hawk does).
> Change the stock Manta's weapons so that they're symmetrical

- source/Outfit.cpp
**Bugfix:** This PR addresses issue #7390
Changed how the game checks if the ship is an automaton, by taking also the automaton value of the outfit being uninstalled.
Captured a Model 16, removed weapons requiring additional crew, installed and uninstalled a Command Center without problems.
See the original issue.
> Fix uninstalling a Command Center

- source/Ship.cpp
**Bugfix:**
Thanks to @Terin for reporting this on Discord.
I am no longer sure of what's going on here, I think it might be a floating point precision error.
This PR now prevents the divisino by zero by not doing the division if the cost is not greater than `0.`.
~~Previously, the logic for scaling down the "turn command" when insufficient energy, fuel, etc, is available was incorrect.~~
~~It was dividing the existing turn command magnitude out of the new value, so the new value would just be `"available energy" / "required energy"`. This is fine when the turn command has a magnitude of `1.`, but for partial turning, this is incorrect.~~
~~Take the example where `turning energy` = `1.`, the existing turn command is `.5`, and the initial energy available if `.4`.~~
~~The `.5` turn command …
> Fix thrust becoming unbounded

- source/HailPanel.cpp
**Bugfix:** This PR addresses an issue found in https://github.com/endless-sky/endless-sky/pull/6438#issuecomment-1430292571. 
Moves the clearance check in the HailPanel constructor for hailing planets above the language check. This means that if any mission that the player has grants clearance to the planet being hailed, it doesn't matter if you lack a shared language with the planet.
I looked at it and thought "Yeah, that looks good."
No thanks.
> Allow mission clearance to bypass language barriers

- source/PreferencesPanel.cpp
Aimimg -> Aiming. Shouldn't cause any preferences to get wiped, since it's only a PreferencesPanel typo.
> fix(typo): Correct automatic aiming preference typo

- data/harvesting.txt
This gives the "plant2" and "large plant2" minables display names.
<details> <summary>Screenshots</summary>
Before | After
-- | --
</details>
> Don't display "Plant2" and "Large Plant2" when targeting those minables

- data/remnant/remnant ships.txt
Changes the Ibis from requiring a "Remnant Capital" license to a "Remnant" license.
Based on my experience playing through the game, the Ibis is not particularly useful once the player has a Capital license, as most combat missions will either require a heavier combat capability, or specialized capabilities (such as cloak, gaslining, or large cargo) none of which the Ibis has. As such, it makes for better progression to let players fly a Starling and upgrade to an Ibis (or let people start out straight into the Ibis if they have the resources for it).
This lets the Ibis be a potential fun upgrade from the Starling, instead of a lackluster combat alternative to the Albatross.
Any …
> feat(content): Changing Ibis license requirement Capital to Remnant

- data/map systems.txt
This PR replaces 3 stars from new Hai Reveal and Gegno content that are no longer in use (and were likely placed there because of a map editor). There shouldn't be any changes otherwise as the new stars are counterparts to the old ones.
No.
No.
> fix(content): Replace Deprecated Stars

- credits.txt
**Feature:**
Updates the list of contributors in the credits.
Some entries have been removed, these correspond to GitHub account name changes.
Many of the additions are new contributors since the last time the list was updated (in October).
A number of the new entries correspond to much older contributions, but don't have accompanying removals. I'm not sure why.
> Add new contributors to the credits

- data/gegno/gegno outfits.txt
- data/map systems.txt
This PR touches up different parts of Acheron space:
-Several planets have been adjusted in the space-life region to be more appropriate (i.e. removing worlds with city lights, adjusting sprites to be more appropriate for their distance to the star, etc.). Additionally, a few spawns have been adjusted.
-Several planets have been adjusted in the Umbral Reach (i.e. remove sprites that are already in use nearby for more variation, adjusting sprites to be more appropriate for their distance to the star, make the area seem more empty, etc.)
-Several Gegno outfits (mainly H2H) now have the appropriate licensing.
Note: No stars have been touched. Habitables, etc. should be fine.
My brain. …
> feat(content): Acheron Touch-Up

- data/hai/hai reveal 1 intro.txt
- data/wanderer/wanderers start.txt
**Misc**
As discussed, locking HR from offering and reverting any changes that it made to Wanderers Start while the content is still under heavy development.
We can unlock it once the next release is out the door.
> Lock Hai Reveal from offering for v0.10.0

- data/bunrodea/bunrodea ships.txt
The Tanto's engine hardpoints were a bit too far into the model and barely appeared. Additionally, the Tanto only has two engines on the model. This adjusts it appropriately. 
No.
> feat(content): Adjust Tanto Engine Hardpoints

- data/bunrodea/bunrodea missions.txt
**Bugfix:**
Thanks to @Terin and @Quantumshark for reporting this on Discord and a different PR earlier today.
Gives the mission a name and description.
> Fix Bunrodea first contact mission display

- source/Preferences.cpp
**Feature:**
@quyykk noted that, if a person uses a preferences file the an entry for previous saves on a version of the game without support for that, the value will be set to 1, which is not updated when coming back to a newer version, which could cause issues for anyone moving between versions without remembering to update the value.
Making 3 the minimum means there will never be fewer than the default number of previous saves.
> Make 3 the minimum number of previous saves

- changelog
**Bugfix:**
Thanks to @Terin for pointing this out on Discord.
The Falcon's bunk count was increased, not required crew.
> Fix a mistake in the changelog

- data/hai/hai reveal 1 intro.txt
- data/hai/hai reveal 4 middle.txt
**Bugfix:**
* Makes Hai Leaks Response 4B invisible and fail itself so that it doesn't appear in the mission list, destined for Allhome.
* Update some conditions to refer to the proper things.
* Remove the combat rating requirement on the HR4 trigger; I don't see any good reason for it given that we have to have done the FW story to get here, as well as defeat the pirate armada in Waypoint. It is also rather high. I have reached this point with a combat rating of 1017, there is no reason I should now have to go and farm combat rating just to continue this story ~~that's what the Kestrel is for.~~
Maybe tomorrow.
[warp …
> Make Hai Leaks Response 4B invisible and a couple of other things

- data/coalition/coalition missions.txt
**Content (Fix)**
~~I blame warp~~
The sell JD mission/job thing makes it possible to get the License without doing the Contributor mission, meaning you could potentially lock yourself out of some of the missions if you got the license that way.
This just changes the requirements to having the License rather than doing the mission.
> Change Coalition requirement for some missions to License instead of Contributor Mission

- source/Personality.cpp
- source/Personality.h
**Feature:** To aid in future development, this adds a comment in Personality warning developers to ensure `PERSONALITY_COUNT` matches `PersonalityTrait`
If the `PERSONALITY_COUNT` is less than the number of elements in `PersonalityTrait`, then `std::bitset` will throw an exception when out-of-bounds personalities are accessed. This *could* be dealt with by putting "if" statements guarding against that everywhere, but I think that's overkill. Instead, I suggest putting in a comment warning about this. Then, everyone will see the comment, and know what they need to do.
There is *nothing wrong* with this aspect of the new Personality class; when you're using an array, you need to make sure the array is large enough. However, this was automatic in the last implementation, and the length has …
> comments in Personality.h & .cpp warning game will crash at runtime if `PERSONALITY_COUNT` is wrong

- changelog
Looks like we hadn't cleaned up a couple entries before merging.
> Remove TODO comments from changelog

- data/bunrodea/bunrodea outfits.txt
Adds a plural entry for Bunrodea Solar Batteries.
> Fix plural for Solar Batteries

- data/hai/hai outfits.txt
**Bugfix:** 
Basrem Reverse Thrusters description displays incorrectly.
Just add backticks instead of quote marks in the description
Just edited the file directly.
> fix: use backticks in Basrem Reverse Thrusters description to allow use of quotes

- data/human/ships.txt
I noticed the standard Mule has both the weapons and outfit space to receive a X1100 Ion Reverse Thruster. Tested it, and it makes the ship more manoeuvrable for jumps and for landing. Very much worth it for a measly 12k credits.
> feat(balance): Adding a reverse thruster to the Mule's standard loadout

- data/hai/hai culture conversations.txt
- data/hai/hai missions.txt
- data/wanderer/wanderers start.txt
Hai Reveal requires the player to *not* know the Hai language, while the Wanderers Campaign requires the player to know the Wanderers language. The opposite is not true: the player does not need to even know the Wanderers exist to play Hai Reveal, and the Wanderers campaign does not need the player to understand the native language of the Hai.
Presently, the game data files do not differentiate between knowledge of the Hai and Wanderers languages since the only device you ever get that can translate, will translate both languages. In a hypothetical future where we can play the Wanderers campaign before Hai Reveal (or at the same time), there must be a way to speak Wanderer, but not Hai.
This PR implements that by adding `language: Hai` in the right …
> `language: Hai`: Split Wanderer and Hai languages in game data files

- source/TradingPanel.cpp
**Bugfix:** This PR addresses a bug mentioned on Discord (https://discord.com/channels/251118043411775489/266345072554016768/1076939938391654471)
Uninstallable outfits are no longer being sold alongside minables using the "sell all" button.
Tested and works.
> Fix uninstallable outfits being sold with minables

- data/hai/unfettered jobs.txt
Repeatable Unfettered jobs grant clearance, to mirror Hai tribute jobs that also do so. This means it is possible to keep landing on Unfettered worlds without bribing the planets while still being hostile with them, as long as you always have a job to complete, which is a better presentation of lore anyway.
> [Content]Repeatable Unfettered Jobs Grant Clearance

- data/remnant/remnant ships.txt
**Content**
Thank you to Cracked Emerald and a few others on Discord who pointed out the discrepancy that the Modified Dromedary has a rather large solar array that is not represented in its stats. This gives it `"solar collection" 1.1`, which is equivalent to a single "KP-6 Photovoltaic Array". These aren't particularly powerful, mostly just a flavor tweak. 
For reference, here's the sprite for the modified Dromedary, where you can see the large array near the back. For the scale, this ship has 2140 hull mass, vs the Bactrian's 940. Slightly shorter, but both wider and taller.
{{attach a save file that allows people to easily test your added mission content or see your new in-game art}}
- ~~[X] I updated the copyright …
> feat(content): Adding solar to the Modified Dromedary

- tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
- tests/integration/config/plugins/integration-tests/data/tests/tests_wormhole_navigation.txt
**Bugfix:** Changes `scan speed` to `scan efficiency` in integration tests.
The integration tests use "scan speed" instead of "scan efficiency" in several places, which leads to warnings about using a deprecated feature during the integration tests. This PR updates the attribute name, to get rid of the warnings.
Manually ran the tests to check that no unexpected warnings were generated.
N/A
> Fix integration test warnings: `scan speed` => `scan efficiency`

- source/text/Font.cpp
**Bugfix:**
It is possible for the truncation algorithm to get stuck switching between two lengths and never terminate correctly (only exiting because of a safety check included for exactly this kind of thing) and is unable to produce truncated text.
I noticed this in the input box of the snapshot save dialog, with the string:
`3020-04-12-Wanderer outfits license acquired`
(Reordering the characters in this string also shows the issue, this exact ordering is not necessary.)
Here, the max width was 209 pixels (220 - 11 for the ellipses.)
It got stuck between 33 characters (216 pixels wide) and 31 characters (196 pixels.)
33 * 209 / 216 = 31.93... -> 31
31 * 209 / 196 = 33.056... -> 33
This PR uses `std::round` instead of just truncating the result of the division.
So, 33 * 209 / 216 = …
> Fix possible failed truncation

- source/Mission.cpp
(Project Hawking just as a usage example, not intended replacement)
This PR adds the `<planet stopovers>` text substitution, which lists all stopover planets simply by name, rather than with the system name included in each entry. This allows for stopovers to be talked about more casually in conversation, or lets a single stopover be included in a mission title without clipping.
> feat(mechanics): Add 'planet stopovers' substitution for shorter list

- source/OutfitterPanel.cpp
**Bugfix:** This PR addresses issue #7424
Added a `static_cast` so that Y pos of the thumbnail is now an integer.
Tested and works.
> Fix blurry thumbnail on outfitter selection panel

- data/human/variants.txt
The Raven has an afterburner variant which does not have a ramscoop equipped, but has the leftover space for one! Since equipping a ramscoop means it can get fuel it used back, and it has space leftover for it, there's no reason for it not to have one. 
Probably shouldn't have chosen to be succinct over delving deep into my reasoning for this change. I have explained in detail my reasoning in the comment below, replying to Zitchas. Thank you, Z, for inducing that!
Due to the discussed points listed below, the ramscoop has been replaced for a fuel pod.
> feat(balance): Adding a fuel pod to afterburner Raven

- .github/workflows/ci.yml
This makes the CI workflow trigger when changing CMake files that are in the root directory, i.e. not caught by the `source/**` and `tests/**` filters.
> Run CI workflow when CMake files have been edited

- source/Preferences.h
This adds a missing #include, caught by gcc 13. Fixes #8439
> Add a missing #include, caught by gcc 13

- CMakeLists.txt
- source/CMakeLists.txt
- tests/CMakeLists.txt
This avoids the creation of the extra static library that is only used to link to the game and the unit tests. This improves build times because it doesn't link an extra library, especially on MinGW where linking is very slow.
CI will test everything and verify that everything still builds correctly.
> Don't create the unnecessary static library for faster builds

- source/Politics.cpp
- source/Ship.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #5544
When a player ship with `inscrutable` attribute gets scanned by an NPC, a special scan message is displayed. Even if the ship has some illegal outfits or cargo, fines aren't applied and stealth missions don't fail.
While testing this, I saw some scan messages overlapping another messages, leaving some dim letters of the original messages. Not sure what causes such behavior or if it was happening before.
> feat(enhancement): Make inscrutable on player ships useful

- source/Ship.cpp
Azure recently made me aware of the obscure fact that active cooling with zero cooling energy causes active cooling to run at full blast at all times, rather than scaled with heat as a percentage of maximum. So, if this was a cooling outfit which used no energy, realistically you would want it to run at full blast, yes. But honestly if this was a cooling outfit which used no energy, it should be using `cooling`, rather than `active cooling`. We have `active cooling` for its specific behavior scaling with heat.
So, I've adjusted the case where there is no cooling energy, to be more consistent with behavior when there is cooling energy.
> Adjust Active Cooling Mechanic

- CMakePresets.json
- source/CMakeLists.txt
This disables treating warnings as errors for release builds, but CI still treats warnings as errors to avoid introducing warnings to the code base.
The reason for disabling it in release builds is that while developing it can be annoying to have to fix warnings that aren't going to make it in the final result anyways. (For example, commenting some bit of code out for testing that produces a unused variable warning).
> Don't treat warnings as errors for release builds

- data/tooltips.txt
**Bugfix:**
This extra backtick shouldn't be here.
Though, I'm not sure it's possible to have the `outfit scan speed` attribute appear in game anymore, so the tooltip might be entirely unnecessary now.
> fix(typo): Remove duplicate backtick in a tooltip definition

- data/governments.txt
**Content**
It has been noted many times in various places that the Wanderers' talons (as mentioned in their first contact mission -  `They do not appear to be armed, but their talons are eight or nine centimeters long.`) should give them an advantage in hand-to-hand combat compared to humans.
At the same time, the Wanderers are birdlike and flying, so it is likely that they share the hollow bones of earth birds, a necessary adaptation to reduce weight enough to allow flight. I think it is reasonable for this to translate to a defensive weakness, as blunt force trauma and shockwaves from explosives would be far more damaging to their hollow bones.
Based on this, the stats given here are 1.4 attack and 1.8 defence, as compared to the default 1 attack and 2 defence that they
currently have. …
> Give the wanderers non-default crew attack and defence stats

- data/human/human missions.txt
The first Pookie mission is available at the spaceport on Hestia, where the tutorial concludes.
However, it only has a fifty percent chance to offer.
Since most new players (essentially all but those who decide not to complete the tutorial, for whatever reason) will end up here, and should check the spaceport, the random offer chance seems to just deny some players this lucrative opportunity for no good reason.
This PR removes the random chance so the mission is always offered if the player visits the spaceport immediately after dropping off James.
> Guarantee pookie

- source/Galaxy.cpp
**Feature:**
Supports the use of:
```
galaxy
remove sprite
```
To set the sprite of a galaxy to nullpointer (the default value, if no sprite entry was given in the definition.)
> Support removal of galaxy sprites

- data/kahet/kahet missions.txt
**Content Refactor**
- Makes all the "Ringworld Debris" missions `minor`.
- Reorders some tokens for consistency.
- Adjusts "Ringworld Debris: Quarg" to never accept, and instead use conversation `action` nodes to apply the appropriate log entries. This also reduces the repetition of the same text in this conversation and removes the need for the deadline on the mission.
- "Ringworld Debris: Quarg" no longer `fail`s "Ringworld Debris" because it doesn't need to: that mission fails itself upon entering Queri.
> Clean up Ringworld Debris Quarg

- data/governments.txt
- data/map planets.txt
- data/map systems.txt
- data/quarg/quarg missions.txt
- data/quarg/quarg.txt
- data/wanderer/wanderers middle.txt
- data/wanderer/wanderers.txt
There has been a desire to split the Quarg into more area-specific governments mentioned by @Arachi-Lover , @Amazinite , and other content creators for future use, and to work around use for area-specific conditions, fixes, etc.. This also supports the idea that in the future, we'll have a Coalition Quarg for that related content instead of messing up with the human Quarg, etc.
So far, I've added several location-related Quarg governments, while keeping the original the human Quarg. Each locational Quarg has their own attitudes with the relevant local factions.
All this said, @Arachi-Lover , this means for Coalition content you can make a Quarg (Coalition) gov to use for them, and we can have future Quarg govs separate for newer races.
Something we …
> feat(content): Split the Quarg Government

- data/human/jobs.txt
All normal bounties were updated to 1 system away in #7317, except the Marauder IV one. This PR makes it consistent with all the others.
> fix(content): Bring marauder bounty distance in line with others

- source/Galaxy.cpp
**Bugfix:**
The expressions were placed in the wrong order so the key wasn't being parsed correctly.
Use the syntax and see that it now actually removes the sprite.
> Fix galaxy definition parsing

- data/human/paradise world jobs.txt
**Bugfix:** This PR addresses an issue raised [on Discord](https://discord.com/channels/251118043411775489/536900466655887360/1085268056311337040).
I've blocked the paradise wilderness retreat job and the parolee job from offering on pirate planets. In addition, I have split the "Paradise Job: Wealthy Retirees" into three jobs: one which doesn't offer on pirate worlds, one which does but you won't get fined for, and one which does and is illegal. The pirate world versions are noticeably more shady, but generally follow the same lines as the original.
I've tested the new jobs, and haven't seen the old jobs where they shouldn't be. For some reason, I'm not getting caught with the illegal pirates though, although the syntax looks fine to me and no errors or warnings are on the console.
This …
> Tweaks to paradise jobs on pirate worlds

- data/governments.txt
- source/Government.cpp
- source/Government.h
- source/Ship.cpp
**Bugfix:**
Thanks to @Rob59er and @KimDare75#9315 (on Discord) for reporting this on Discord in relation to the Ka'het and Korath, respectively.
Governments are given default disabled hails, and now that random interval hails can be sent even if the player doesn't know the government's language (to allow untranslated hails like the Wanderers have), these default disabled hails are used when a.
This changes it so hails from a ship the player does not have the language for are only sent if the government is explicitly set to "send untranslated hails".
None
```
government "Whoever"
"send untranslated hails"
government "Whoever"
remove "send untranslated hails"
```
> Fix untranslated hails again

- data/wanderer/wanderers middle.txt
**Bugfix:**
Thanks to @Jeva1930#1930 on Discord for reporting this.
When Alnilam and Zenith are occupied by the Alpha controlled Sestor fleet, the required reputation for Zenith (so, with the Pirate government) is set to 1000, and the option to bribe is disabled.
When Zenith is bombed, the default values (required reputation of 0 and a bribe fraction of 0.04) are restored, but if the player does not bomb Zenith, no such change is made, and so it is not possible to land there without either a mission providing clearance or a reputation with the Pirate government of at least 1000. This doesn't really make sense.
This PR adds an event which reset the required reputation and bribe fraction only and makes use of it upon eliminating the Alphas there with the help of the Navy (after not bombing …
> Remove Zenith required reputation when not bombing

- data/human/weapons.txt
This PR adds some variance to Flamethrower projectiles so that there's less of a clear cut-off when firing.
[(Suggested by Millie the Witch on the Steam forums.)](https://steamcommunity.com/app/404410/discussions/2/3828662280423713943/)
> feat(content): Add random lifetime to Flamethrower projectiles

- source/GameAction.cpp
**Feature:**
This PR removes the warning that is created for `fail <mission name>` nodes where the specified mission doesn't have an existing definition. What `fail <mission name>` does is fail an instantiated mission by matching the name provided to the mission's identifier. What the warning is saying is that no definition exists for the provided name. The issue with this is that one is capable of having an instantiated mission of a given identifier without a definition for that mission existing, such as in the case of #8594 where we can know that players might have an instantiated version of a mission that we have removed the definition of. Therefore, it doesn't make sense to create a warning in such cases, especially since the `fail` node will continue to function and remove any …
> Don't warn about GameActions that fail missions without definitions

- source/LoadPanel.cpp
**Bugfix:** This PR addresses issue #8205
When double clicking the snapshot list, the game will now only count it as a request to load the selected snapshot if both clicks were on the same snapshot.
Try double clicking snapshots.
Without this PR, it is possible to click on one snapshot and then another in quick succession and the game will attempt to load the most recently selected snapshot, even though this snapshot was not actually double clicked.
With this PR, the game will only attempt to load the snapshot if both clicks were on the same snapshot.
> Fix LoadPanel double clicking

- source/Command.cpp
- source/Command.h
**Feature:** Switches from a uint32_t to a uint64_t to store commands. This is an alternative to an `std::bitset` discussed in #8507
A PR in the queue needs a thirty-third command, but we only have room for thirty-two. My PR #8507 used `std::bitset`, but that was found to slow down the game. The `std::bitset` class is well-known to be slower than integer operations, and Command is used many times per frame, so that result isn't surprising. A faster alternative discussed in that PR is a 64-bit integer, which should be enough to last us a while.
N/A
An auto-steer key (#8508)
Made sure the commands still worked. Tried adding a thirty-third command (#8508) and confirmed it worked.
N/A
N/A
> use 64 bits instead of 32 to store commands (alternative to #8507)

- source/AI.cpp
- source/Engine.cpp
Fix details
-------
Using left alt (mouse control hold) would toggle the preference.  If the player exited the game with alt+f4, then the next time the game launches the mouse control would be toggled in the opposite state.
Due to alt+f4, mouse-hold would act like mouse toggle and exit to save the preference.
AI now relies on active commands instead of reading the preference.
Related Issues
-------------
Partially fixes:
* #8419
Testing Done
------------
Performance Impact
------------------
None
> Bugfix: Do not rely on preference for mouse hold

- .github/sccache/action.yml
- .github/workflows/cd.yaml
- .github/workflows/cd_release.yaml
- .github/workflows/ci.yml
- vcpkg-configuration.json
Another round of updating our dependencies and actions. CI runs should finish quicker because of better caching by the run-vcpkg action.
> Update Actions and dependencies

- data/persons.txt
**Bugfix:**
Thanks to @Ferociousfeind for reporting this on [Discord](https://discord.com/channels/251118043411775489/536900466655887360/1091776239712346142).
The `are capable of` option does not produce grammatically correct phrases.
This PR splits this into separate subphrases so a correct sentence is always formed.
An alternative would be to just remove hte line that gives rise to the offending sequence.
> Fix MMK hails

- data/human/kestrel.txt
This doesn't really fit any of the categories...
I reduced the combat rating requirement for the `"Kestrel Testing"` mission from 8000 to 6000, or 2500 with the FW storyline completed.
While flying around in my shield beetle recently after completing the Free Worlds campaign, I thought I'd go see if I could get the Kestrel. I was surprised to find out that I didn't meet the CR requirement: despite defeating the Pug, fighting numerous battles, and having a ship that overpowered even the Kestrel that I was going to complete the mission for, my CR was 1837 and the requirement was 8000.
I understand that my run did not lend itself well to me accumulating a high combat rating, at least until the end, but it still seems odd to me that you need a higher combat rating than is required to demand …
> Reduce combat rating requirement for the Kestrel

- source/Engine.cpp
- source/Minable.cpp
- source/Minable.h
Summary
-------
This feature was contributed on May 19, 2022.
@RugnirViking made it so that if you have both an asteroid scanner and a tactical scanner, you can see the health of asteroids you have targeted.
Related issues
--------------
This change is split off from and supersedes https://github.com/endless-sky/endless-sky/pull/6840
Complements #6669
Screenshot
----------
[1]: https://user-images.githubusercontent.com/18635337/169382807-4192b883-0476-43e8-a048-3c01c3a499f6.PNG
> Feature: Mining Asteroid Health Bar

- source/OutfitterPanel.cpp
**Bugfix:**
Thanks to `@Viro#7921` for reporting this on Discord.
The use of an `std::vector` instead of an `std::set` to store the outfit lists means the items in the collections are not automatically kept unique.
This leads to any licenses the player has appearing twice:
- They are initially added to the list when traversing `GameData::Outfits()`.
- And then again when checking the player's conditions for licenses they might have.
Because, in order to appear in the outfitter, a license condition the player has must still exist as an outfit in `GameData::Outfits()`, it is not actually necessary to check the conditions and add licenses to the `catalog` here, any license with a valid outfit will already be in the `catalog`, and any without would not be added anyway.
Visit the outfitter …
> Fix license duplication in outfitter panel

- source/ShopPanel.cpp
**Feature:** This PR implements the feature request detailed in issue #8635.
If more than one ship is selected on the sidebar, all selected ships that have the selected outfit installed are marked with a pointer.
N/A
> feat(outfitter UI): Point ships that have the selected item installed

- data/tooltips.txt
- utils/contentStyle.json
**Bugfix:** This PR addresses issue #8629.
I used `git log --follow --diff-filter=A --find-renames=40% data/tooltips.txt` to find out when the file was added, and then added a copyright header to it which gives MZ credit for it.
I opened up Endless Sky and hovered over things to make sure tooltips still popped up.
N/A
> Give MZ credit for tooltips.txt

- source/CargoHold.cpp
- source/OutfitterPanel.cpp
- source/ShopPanel.cpp
**Bugfix:** This PR addresses issue #8623
- Fixed the `Cargo` button text being always dark, and the `Install` button not highlighting on hover.
- Changed the value of one variable in the CanBuy function that should definitely use the floating-point FreePrecise instead of the integer Free.
> Fix some outfitter buttons bugs

- source/AI.cpp
- source/ship/ShipAICache.cpp
- source/ship/ShipAICache.h
Fix Details
-----------
Player escorts and AI escorts misbehave while attacking asteroids.  This fix addresses the issue by reverting a small code change previously made.
Partially reverts https://github.com/endless-sky/endless-sky/pull/7552
The turning radius needs to be calculated based on the ship's current speed instead of the absolute max speed.  This widely varies based on the current ship accelleration and velocity.
This also fixes my afterburner fighter AI which was completely broken due to high ship speeds and accelleration.
Testing Done
------------
Tested with normal fighters doing mining and with after burner fighters mining with extreme speeds.
Performance Impact
------------------
None
> Bugfix: Mining AI, melee, and other AI distance fix

- data/human/human missions.txt
Recently, New Tortuga was added as a pirate world with the attributes "core" and "factory". However, this makes the planet eligible to be a destination for "Immigrant Workers", which doesn't make sense in terms of both gameplay and story. This PR adds a government filter onto the mission.
> fix(content): Stop "Immigrant Workers" from going to Pirate space

- data/gamerules.txt
- source/AI.cpp
- source/Gamerules.cpp
- source/Gamerules.h
**Feature:** This PR implements the feature request detailed and discussed in issue. None. 
Make the max mining time for NPC with mining personality a gamerule. This will allow plugin that adds larger mining ships with larger cargo holds to allow more time for those ships to fill their cargo.
N/A
```
gamerules
"npc max mining time" 3600
```
VSC doesn't say anything.
N/A
idk, hopefully little to none.
> NPC max mining time gamerule

- source/AI.cpp
- source/AI.h
Fix Details
-----------
A player might stop with shift+down or they might be jumping through systems.  If a player is hyper-jumping or stopping, the right-side flares thrust.
See the subtle right-side thrust flares while stopping.
https://user-images.githubusercontent.com/875669/230754469-c6f20359-0c6b-4c92-89e3-29f271d1c5f5.mp4
In this hyper-jump notice there are no flares on the right side while the ship stops.
https://user-images.githubusercontent.com/875669/230754467-5a44f506-82db-4ec5-aef8-35935f94873d.mp4
Testing Done
------------
> Bugfix: Remove turning flares while stopping

- source/Preferences.cpp
**Feature:**
Thanks to `@auldr#3296` for bringing this up on Discord.
What the title says. Ensures continuity for people who update from 0.10.0.
> Keep overlays off if they were off before

- data/human/weapons.txt
The Javelin Mini Pod has a range override of 300, despite the main launcher not having any override at all. This range override was added when the missile pods were introduced (#5793), to save ammo by shooting at close range and reducing the chance of misses. However, in practice, having access to the full range of the launcher is much better, and the chance of missing is often negligible.
This PR also removes the lower range override of the Heavy Rocket Pod, for reasons noted above, and also to reduce the probability of the AI hitting itself with the blast radius.
Footage of a Dagger vs. a Barb; the 300-range Dagger loses, the 600-range wins:
https://user-images.githubusercontent.com/60202690/232261636-1ace74df-b15a-448f-ac01-7e22777f42d5.mp4 …
> feat(balance): Remove range overrides on missile pods

- data/categories.txt
- data/human/human missions.txt
Halves the mission's payment, so you can't pay off your entire mortgage in a single mission.
> feat(content): Reduce payment of "Deal Change 2"

- data/governments.txt
- data/hai/hai reveal 1 intro.txt
**Bugfix:**
These governments are never referred to, except in the attitudes of other governments.
This PR removes them since they have no good reason to exist.
> HR: Remove unused governments

- data/governments.txt
- data/iije/iije.txt
This is a partial re-PR of #8616.
- Removed the unused `Forest (Predator)` government.
- Deleted two blank lines at the end of the `iije.txt`, leaving only one.
> fix(content): Unused government and unnecessary blank lines removal

- data/hai/hai reveal 1 intro.txt
**Bugfix:**
`"Hai Witness Unfettered [1]"` is not a condition that is ever set, it is the name of a mission, though.
Replace it with `"Hai Witness Unfettered [1]: done"` so it does what it's supposed to.
no
> HR: Fix a condition

- source/OutfitterPanel.cpp
**Bugfix:** This PR addresses issue #8687
CanBuy currently treats any outfits as free when the player has some of them in cargo or storage. The credits, however, are taken normally, which can lead to negative credits.
Seems to work.
> bugfix: Don't allow buying outfits the player can't afford

- data/hai/hai missions.txt
**Bugfix:** This PR addresses an issue raised on Discord [here](https://discord.com/channels/251118043411775489/536900466655887360/1099746823410831560).
Adds one line requiring the first contact mission. This means that it will still offer on an uninhabited (Hai) planet, but that it won't offer if you don't know about the Hai.
Alternatively, we could do what Terin suggested and block it from offering on uninhabited planets, but this is a more comprehensive method, and you could probably have picked up a missing child anywhere, even if it's not an inhabited planet.
Tested using the save file. It seems to work fine, although I haven't checked to make sure it still offers when you _have_ done the first contact mission.
This save file can be used to verify the bugfix. The bug will occur when …
> bugfix(content): Require Hai first contact before Unwanted Cargo mission

- source/Engine.cpp
- source/Preferences.cpp
- source/PreferencesPanel.cpp
**Feature:** This PR implements the feature request detailed in issue #8685
Added a "Flagship flotsam collection" preference. When disabled, it prevents the flagship from collecting any flotsam.
N/A
Yes, works as intended.
N/A
> feat(enhancement): A preference to disable flotsam collection by the flagship

- data/_ui/interfaces.txt
- source/EscortDisplay.cpp
- source/EscortDisplay.h
1. Disabled ships are displayed in grey to avoid confusing them with docked ships.
2. Escort selection is indicated with a pointer instead of icon color change.
Before:
After:
(Both images show the same situation: the Black Diamonds carried and selected, the Shield Beetle disabled, the first Albatross selected, and the second Albatross disabled in another system.)
N/A
#4711 suggested to use the selection color for icons more frequently, but I think using a pointer is better as it doesn't hide normal icon colors.
> feat(UI): Escort HUD improvements

- source/AI.cpp
- source/AI.h
- source/Preferences.cpp
- source/Preferences.h
- source/PreferencesPanel.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #8683
Added two new modes of automatic firing: the setting can be toggled between "off", "on", "guns only" and "turrets only".
Tested all autofire types.
N/A
> feat(enhancement): Guns-only and turrets-only autofire modes

- source/AI.cpp
**Bugfix:** This PR addresses issue #8693, and is an alternative to #8698.
AI::TurnToward will now not stop trying to turn towards the target direction until both the facing is sufficiently well aligned with it (currently, this is within ~0.57 degrees of it) *and* the ship is within one step of turning of it. This means that even slow turning ships continue to turn towards the target direction until they are within one step of it, so they are close enough that they are able to jump.
Also, removed an unnecessary vector magnitude calculation: the vector is already a unit vector.
Test autopilot hyperspace jumping with a ship with a turn rate of less than 1 degree per second and see that it is able to jump successfully, never getting stuck.
> Fix some ships being unable to jump

- source/PrintData.cpp
**Feature:**
Adds `"` characters as delimiters around ship and outfit names and categories when printing data since these can have commas in them (and some variant names do) which is problematic given that commas are used to separate fields in each row.
It built and printed data as expected.
> Add delimiters to strings when printing data

- source/Interface.cpp
**Bugfix:**
Earlier in this method, the following code is present:
https://github.com/endless-sky/endless-sky/blob/d2d03934c640b6165738b9e92c680f3c9c821101/source/Interface.cpp#L645-L646
This means that `segments` is already either 0 or greater than 1, and so checking that again is unnecessary.
> Remove some unnecessary code in Interface::BarElement::Draw

- data/human/human missions.txt
This PR reduces the payment of Wool Smuggling from 200,000 credits to 90,000. For comparison, the regular payment formula would make the mission pay around 24,000 credits, and Humanitarian 1 (another mission that goes to a pirate world) has a max payment of 83,000 credits.
> Reduce Payment of "Wool Smuggling"

- EndlessSkyLib.cbp
- EndlessSkyTests.cbp
- source/CMakeLists.txt
- source/DistanceCalculationSettings.cpp
- source/DistanceCalculationSettings.h
- source/LocationFilter.cpp
- source/LocationFilter.h
- source/Mission.cpp
- source/Mission.h
- tests/CMakeLists.txt
- tests/unit/src/test_distance_calculation_settings.cpp
**Feature:**
Adds support to location filter `near` and `distance` nodes for distance calculation settings that determine if non-hyperlinked systems within default jump drive range or wormholes should be considered, similar to what is now possible for mission deadline and payment autocalculations.
Note: if you wish to test the trans-wormhole functionality with the `--matches` command line option, you will need to make a change to the following line:
https://github.com/endless-sky/endless-sky/blob/db89370ee3b369e3b7bdb76685ba29eda52a30db/source/DistanceMap.cpp#L236
I suggest something like:
```c++
if(/*object.HasSprite() &&*/ object.HasValidPlanet() && object.GetPlanet()->IsWormhole()
```
This is because, when running that command, no images are loaded, and so `object.HasSprite()` will …
> Distance calculation settings in LocationFilters

- source/Ship.cpp
**Bugfix:** This PR addresses issue #8663
fixes: 8663
Tested with the savegame from 8663; didn't get the warning messages.
Also did some capturing (getting my crew below the required crew); and got the relevant warning messages.
See #8663 for a savegame to verify that the messages no longer get generated.
> fix(status-messages): Only report insufficient crew on player-owned ships

- data/hai/hai reveal 6 end.txt
**Bugfix:** This PR addresses the bug reported here:
Change mission `to offer` condition to be properly sequential.
None
n/a
There was a point in time where one particular mission needed to look at the mission before its previous one to trigger correctly.
[B14] was added in the rework and I think this got overlooked as possibly being that case, which I actually don't think exists anymore.
> fix(bug): HR Bugfixes 5

- data/coalition/coalition missions.txt
**Bugfix:**
This PR adds the `blocked` field to the Coalition mission "Saryd Students 2". Without it, one could complete the first mission, having enough money to buy the rum cargo, but not have the free cargo space needed for it, and the game would never inform the player why the sudden end to the mission chain.
This'd also break time as the story dealine mentioned in the first mission's text would be extended indefinetly, given the second `deadline` would only start up once one landed there again with the necessary cargo space.
Fix is just adding the `blocked` and its text.
Issue pointed out by simpson86 on the Discord server. Thanks for the help.
> (Bugfix)(Coalition) Add missing "blocked" field to mission Saryd Students 2

- data/korath/korath ships.txt
- data/persons.txt
This is a small, simple style fix that removes an extra piece of whitespace from the Met Par Tek 53's definition. The whitespace is located between the hardpoints and explosions, and is being removed because - as far as I've seen - it is the only ship with this extra whitespace, thus rendering it inconsistent with the datafiles' general layout.
No performance impact or anything like that, this literally just removes one empty line. Shouldn't affect anything besides a tiny win for consistency.
> (Style Fix) Remove extra whitespace from the Met Par Tek 53

- source/OutfitterPanel.cpp
- source/ShopPanel.cpp
- source/ShopPanel.h
**Bugfix:** This PR addresses issue #8089
Currently if the player has an outfit in planetary storage, the game omits any license requirements of the outfit, even when buying from the outfitter using [b] key.
Yes. If the problem seems to persist, depart and land as you may have some outfits in stock.
> fix(outfitter): Don't allow bypassing license requirements

- data/map planets.txt
I wanted to have a branch in a conversation for a new mission based on whether you were on a fully Hai world or one with a fairly consistent human presence.
In doing so I found that a) there was no attribute for identifying that, and b) there were a bunch of attributes missing from worlds they should've been on.
So this just adds some attributes that need to be there.
> Chore(Update) planet attributes for tourism + humans

- source/DataWriter.cpp
This was split off from #8725 to make merging this easier. The version in that PR was tested and working, so hopefully this bugfix also will.
**Bugfix**: This PR fixes an edge case where " quotes in text were not delimited correctly in DataWriter.
Name a ship `"`. You can choose any other name that contains a `"` and no whitespace.
Load the file - the game will handle it just fine.
Save the file - it gets written as `"""`.
Load it again - the name is now parsed as an empty string.
Loaded and wrote a save file with the above case.
> bugfix: Fix incorrect string delimiting in DataWriter

- utils/check_code_style.py
Fixes an issue with the code style checker trying to check the vcpkg files (reported by @thewierdnut). Also fixes the copyright header (reported by @warp-core).
This is not an issue in the main repo, as the CI action doesn't have the vcpkg files.
> bugfix: Disable style checking for vcpkg/cmake C++ files

- data/remnant/remnant jobs.txt
**Feature:**
Uses new distance calculation options to have the location filter select any system within 100 "jumps" of the system Nona (chosen because it was the origin of the Builders, the most recent sentient inhabitants of this region of space), where a "jump" can be either a hyperlink or an unrestricted wormhole (like the one joining Ritilas and Fearis).
This will cover the same set of systems as before, but now exclusions for any new, nearby systems with similar attributes that are not connected via hyperspace links (like Aki'il or Patir) will not need to be added to this filter.
Used `--matches` with the new filter and the old filter and see that the results are the same.
(Note: `Body::HasSprite()` will need to be modified to always return `true` when testing location filters …
> Improve Remnant Rescue 4 location filter

- data/human/human missions.txt
- data/human/intro missions.txt
**Feature:**
Updates the Pirate Duel and Intro mission offer conditions to account for the new ship categories (Space Liner, Utility, and Superheavy.)
The Transport intro missions can now also be triggered by Space Liners, the Freighter ones by Utility ships, and the Interceptor ones by Superheavy ships, since the latter two previously also accounted for larger freighters and warships (and fighters and drones), respectively (there was no corresponding category for Transport so that mission only checked one category before.)
Excluded Space Liner, Utility, and Superheavy ships from the Pirate Duel mission and also added Fighter and Drone to the list of categories from which the player may only have a single ship.
> Add new ship category conditions to missions

- data/hai/unfettered jobs.txt
**Bugfix:** This PR addresses issue #8771
Make sure the player has the drive available to be taken for the mission to be accepted.
~~This is probably showing an underlying issue with the conversation not being parsed properly in the on accept? I'm not sure what's going on but this should quick fix it, whilst adding a functionality to it at the same time (it'll still be shown when you have the drive on an escort and says what you must do to enable the mission)~~ thx warp for pointing out this is the intended behavior
I tested with a JD installed on flagship or in cargo and I could use the mission
I also tested with a JD sold, no JD, a JD on another ship, a JD in storage, and it was greyed out in those instances.
n/a
> Bugfix(data): fix unlimited money/tripulses exploit

- data/stars.txt
Two different ways of looking at this one:
If you look at the trend within the supergiants, the trend is increasing solar wind and decreasing solar power as you go to redder spectral classes, except that the K supergiant's solar wind weirdly goes down instead of up, and the M supergiant has the same.
If you look at the trend from giants to supergiants, you can see that each supergiant has a solar wind 1.0 higher than the corresponding giant, except for the K supergiant which has the same as the K giant, and the M supergiant which has .1 less than the M giant.
This PR adjusts the solar wind values of the M and K supergiants to fit both of these trends.
> Adjust M- and K- class supergiants' solar wind values to fit the trend in similar stars

- data/wanderer/wanderers start.txt
**Bugfix:**
Thanks to ESC#3505 for reporting this on Discord.
The preceding mission requires no passenger space, but this one does. If the player gets here without any passenger space, there is not currently any indicator of why the next mission isn't offered.
This PR adds a blocked message telling the player why they aren't getting the next mission, and also updates the on visit message to account for the possibility that a player escort is carrying the passenger and has not yet arrived.
0
> Add a blocked message to Wanderers Invaded 3

- CMakeLists.txt
- credits.txt
- endless-sky.6
- resources/EndlessSky-Info.plist
- source/main.cpp
**Documentation:**
Updates version numbers in main.cpp, credits.txt, and endless-sky.6 to `0.10.2-alpha` and in CMakeLists.txt and EndlessSky-Info.plist to `0.10.2` (because I don't think these places support the `-alpha` suffix.)
> Update version numbers for 0.10.2 alpha

- data/hai/hai reveal 0 prologue.txt
**Bugfix:**
Thanks to HerrowItsMeme#6837 on Discord for reporting this.
And Highscore#0708 for highlighting the two I missed in the first commit.
These missions were originally written with stopovers but later split into multiple missions, but some uses of the `<stopovers>` text substitution were not updated. This updates them to `<destination>`, which refers to the same locations as the original `<stopovers>` did.
There are also a couple of `<planet stopovers>` from the original `on complete`s that have been changed to `<origin>`.
(Screenshot from HerrowItsMeme#6837.)
0
> Replace incorrect substitutions in new HR intro

- data/human/free worlds 3 reconciliation.txt
**Refactor:**
These three missions previously relied on their `on offer` mission actions blocking the mission if the player did not have the relevant drive to take, and relied on the jump drive option being offered first based on its name.
With some the new autoconditions we have, this is no longer necessary.
It is now possible to ensure that the hyperdrive and scram drive missions are not offered if the player's ship has a jump drive, and so that mission no longer needs to rely on its name.
We can also use the same autocondition to ensure that the jump drive version is only offered if the player has a jump drive installed so there is no longer any need for it to remove and replace a jump drive to block itself if there is no jump drive present.
[warp 0.10.1-alpha …
> Make the FW Pug 2C missions more robust

- data/human/free worlds 0 prologue.txt
**Bugfix:** This PR addresses issue #8813 
In `Pact Recon 0`, Captain Last stumbles upon a recon officer that just happened to be away from Glaze at the moment. She asks you to fly through four systems, and then head to Glaze to meet her upon her return there. The story makes no sense if she is already on Glaze.
Made the mission `priority` with 100% chance of offer. Checked that it never offered on Glaze, but did offer in other places
This save file can be used to verify the bugfix. The bug will occur when using v10.0.1, and will not occur when using this branch's build.
[Zoltan Remnant~3014-01-15 pact recon 0.txt](https://github.com/endless-sky/endless-sky/files/11646333/Zoltan.Remnant.3014-01-15.pact.recon.0.txt)
> Do not allow `Pact Recon 0` on Glaze

- .github/ISSUE_TEMPLATE/feature-request.yml
**Content (Missed for #8805)**
Removed another mention of Google Groups in the template.
> I missed a mention in the template

- source/PlayerInfoPanel.cpp
Fixes #8746. Instead of disabling this warning this PR works around it by making copies of the strings. Since this is in the player info panel, the small performance hit can be ignored.
> Workaround -Wdangling-reference warning

- source/ConditionsStore.cpp
**Bugfix:**
The check that skipped 0 valued conditions in `ConditionsStore::Save` was removed a little bit ago.
This adds it back in so conditions with a value of 0 are not saved because a value of 0 is no different from the conditions just not being present at all.
0
> Don't write conditions with a value of 0

- source/Interface.cpp
- source/Interface.h
**Feature:**
Adds support for limiting the span and adjusting the starting angle for rings drawn with an interface.
Both values are given in degrees.
A span angle of less than 360 will accordingly scale down the value that is set for this ring in the given interface information. A span angle of 180 with a value of 0.5 will draw a quarter circle, instead of the half circle it would draw with a span angle of 360.
~~I'll have to check how the start angle part works.~~
```html
ring "my arc"
"span angle" 90
"start angle" 45
```
> More interface ring options

- data/hai/hai reveal 0 prologue.txt
**Bugfix:**
Thanks to Off To Lunch#1154 on Disocrd for reportingthis.
These missions are written as though Alondo is on some world that isn't Hai-home, so it shouldn't be possible to offer them on Hai-home.
This excludes Hai-home as an option from the source filter.
Test the existing and updated filters with `--matches` and get:
<details> <summary>Existing filter:</summary>
Systems matching provided location filter:
Planets matching provided location filter:
Allhome
Cloudfire
Darkmetal
Dustmaker
Farwater
Frostmark
Giverstone
Greenbloom
Greenwater
Hai-home
Heartvalley
Icelake
Makerplace
Mirrorlake
Newhome
Skyfarm
Snowfeather
Stonebreak
</details>
<details> <summary>Updated filter:</summary>
Systems matching provided location filter:
Planets matching provided location filter:
Allhome …
> Don't initially encounter Alondo on Hai-home in HR

- data/human/free worlds 1 start.txt
**Bugfix:** This PR fixes a conversation where Cruisers are referenced instead of Carriers.
In `Liberate Kornephoros`, FL says `Just fine. It'd take more than a few Cruisers to destroy the <ship>.`
However, in the previous battle (`Defend Sabik`), the navy fleets only had Carriers, and no cruisers.
```
npc evade
government "Republic"
personality waiting heroic
fleet
names "republic capital"
fighters "republic fighter"
variant
"Carrier"
"Lance" 4
"Combat Drone" 6
"Frigate" 2
"Gunboat" 3
"Rainmaker" 3
npc evade
government "Republic"
personality heroic
system "Kornephoros"
fleet 2
names "republic capital"
fighters "republic fighter"
variant
"Carrier"
"Lance" 4
"Combat Drone" 6
"Frigate" 2
"Gunboat" 3
"Rainmaker" 3
```
> fix(content): Change reference to incorrect ship type in FW

- data/_ui/help.txt
**Bugfix:** The `Fighters transfer cargo` preference is in the Gameplay section. I guess this message wasn't noticed when the preference panel got updated.
> fix(content): Fix incorrect preference section in help message

- data/human/free worlds 1 start.txt
**Bugfix:**
This line is supposed to refer to my current planet, the place where this mission is offered, but `<planet>` is replaced with the name of the destination planet.
This PR changes the replacement to `<origin>` which will be the name of this planet.
0
[warp core~~previous-1.txt](https://github.com/endless-sky/endless-sky/files/11715692/warp.core.previous-1.txt)
> Correct text replacement in FW Pirates: Attack 2

- data/governments.txt
This PR adds each Quarg government that was split in https://github.com/endless-sky/endless-sky/pull/8561/files#diff-52ab6c2e7dd87148c178b0cb37499256a21fa460b750065a596d6cce76b0e3ac to the Heliarch's relationships, so that they are properly fired upon should they ever find themselves in Coalition space (see the Wanderer missions that give the player Quarg escorts).
N/A
> feat(content): Add Split-Quarg governments to Heliarch Relations

- data/stars.txt
`power` for `star/wr` increased from 0.4 to 5
In reality, Wolf-Rayet stars are incredibly massive bright stars, shining so brightly that their outer layers of hydrogen are blown away. In the game, they already have a habitable range of 50000, which reflects this. The oddly low `power` value of 0.4 seems very out of place with that habitable range, so I have changed it to 5. This change also makes the WR star more distinct from the carbon star, protostars and the various nova remnants, all of which have high `wind` and low `power`.
The value of 5 was chosen because it is brighter than the 4.2 of the o0 star, but still not quite as bright as the O supergiant, which is currently the brightest (by `power`) star in the game. It could be made higher, since the habitable range around the O …
> Increase the power of star/wr, to reflect its very large habitable distance

- data/human/free worlds war jobs.txt
Adds Free Worlds war jobs that make use of the the `Military` cargo type that was introduced in #6764.
This change is little more than a slight adaptation of existing FW war jobs that give missions hauling `medical`, `food`, and `heavy metals`.
> Add FW war jobs that make use of Military cargo

- data/human/free worlds 2 middle.txt
**Bugfix:**
The missions towards the end of FW start were changed in #7000 but this condition in FW middle still refers to the old mission name, which no longer exists.
This PR updates it so it also refers to a condition that is set by the current missions.
0
[warp core~~previous-1.txt](https://github.com/endless-sky/endless-sky/files/11715932/warp.core.previous-1.txt)
Travel the Winter and FW Diplomacy 1 should be available.
> Properly account for suspension from the FW militia in FW Diplomacy 1

- data/human/kestrel.txt
**Refactor:**
Currently, these missions trigger a delayed event and require a condition set by that event to complete, but they don't do anything else, and there is no need to complete them. The location that the player will have to land on to complete them will also be wherever they first landed after doing the initial Kestrel mission, which could be anywhere.
This PR removes the `to complete` condition set from these missions and instead makes the `on offer` action fail the mission, so it'll set the event to happen on a timer and then be discarded.
No other changes should be necessary; the autoconditions from these missions are never referred to.
0
> Make the missions that trigger the Kestrel available events fail instead of persisting

- data/human/hails.txt
**Content (Text Changes)**
Removes unnecessary spaces from hails, example:
turns
```
word
"xxx "
"yyy "
```
into
```
word
"xxx"
"yyy"
word
" "
```
Also makes changes so there should not be multiple consecutive spaces in hails.
> Spaces on separate `words` in hails

- source/ImageSet.cpp
**Bugfix:** This PR addresses issue #8765 
#7667 added a check that skips attempting to load plugin icons if one isn't present, eliminating the errors that were printed about plugin icons being referred to but not existing (the user is not referring to them, the game was assuming the icon is provided even though this isn't actually a requirement.)
That check assumed no icon file existed if either a standard DPI or @2x version wasn't present, requiring both. So, if only the standard is provided, it will be ignored since the @2x isn't.
This PR means that the icon loading will only be skipped if both a standard DPI and @2x version are not present. That is, if either is present, the icon will be loaded.
Delete the @2x version of the high DPI plugin icon and start the game. Check the plugins …
> Fix plugin icon missing when no @2x is provided

- source/AI.cpp
**Bugfix:**
Out of system escorts that have run out of fuel will often refuse to land and refuel if that is an option.
This PR fixes that.
Use the save file below.
Follow the route to Kraz.
Without this PR, the mission escorts will get stuck in Mimosa. Some are out of fuel, but don't use the planet to refuel and all the other ships are waiting for them.
With this PR, they refuel as needed and all successfully arrive in Kraz.
[warp core.txt](https://github.com/endless-sky/endless-sky/files/11736652/warp.core.txt)
> Fix an issue with out of system escort refuelling

- data/remnant/remnant 1 introduction.txt
- data/remnant/remnant jobs.txt
Fix destination from being Ssil Vida
NOTICE: this does now fix the repeatable job board missions
**Bugfix:** This PR addresses issue #{{#8896}}
not attributes "remnant station" in six different spaces
none, sorry
N/A
> Fix Remnant JD missions destination being Ssil Vida

- .github/workflows/cd_release.yaml
Creates all the Steam depot zips as part of the release workflow. Those zips can then be uploaded to Steam as-is.
Not yet, but it should work (because I copy pasted 95% of it from a previous branch where I tested it)
> Upload all the Steam depots when creating a release

- data/human/news.txt
**Bugfix:** This PR removes the "financial analyst" news from Altair and similar systems while they are occupied by the pug.
Currently, during the occupation, no other news show up, and I don't think this one is anything special.
Doesn't show up after the government was blocked.
[Space Shuttle.txt](https://github.com/endless-sky/endless-sky/files/11756154/Space.Shuttle.txt)
> bugfix(content): Prevent "financial analyst" news from showing up during the Pug occupation

- .github/path-filters.yml
- .github/workflows/compute-changes.yml
- .github/workflows/projects_check.yml
- changelog
Runs the spellcheck ci for the changelog. Fixes some typos in the changelog file (some manually detected, some by codespell).
> typo/feat: Enable codespell for changelog, fix typos.

- data/human/news.txt
**Content**: Adds a new condition to a job that was requested in a TODO comment.
The "shipyard" attribute is added to planets that have shipyards. This is what the TODO requested - spaceship salesmen should only appear on planets with shipyards.
I checked that the shipyard attribute works via `--matches`.
> feat(content): Add missing condition to news entry (resolves TODO)

- data/_ui/help.txt
- keys.txt
- source/Command.cpp
A typo in one of the fleet commands.
**Note:** The fix probably resets the keybind, but I think it's fine since the command was added in 0.10.1
> fix(typo): Don't capitalize "flotsam"

- data/gegno/gegno intro missions.txt
**Bugfix:** This PR fixes an incorrectly separated word
Quarg ringworlds are always one word, not two. There are 285 occurrences of "ringworld", but this is the only "ring world".
N/A, this is a single word edit, doesn't touch the mission syntax.
N/A, same as above.
> fix(typo): `ring world` -> `ringworld` in gegno intro missions

- EndlessSkyLib.cbp
- source/CMakeLists.txt
- source/MissionAction.cpp
- source/MissionAction.h
- source/NPC.cpp
- source/NPC.h
- source/NPCAction.cpp
- source/NPCAction.h
**Bugfix:** This PR addresses issue #8870
Created a new NPCAction class which contains a MissionAction and records whether the action has already been triggered previously. NPCActions which have been triggered cannot be triggered again. This is as opposed to the current behavior of deleting the MissionAction after use, which caused #8870. With this change, the Conversation used by ConversationPanel once again lasts longer than the panel, as it did prior to #7326.
Creating a separate class also lays the groundwork for future enhancements to actions that NPCs can trigger, allowing them to do actions specific to NPCs (such as changing NPC personalities after something has occurred).
Note that this is not necessarily mutually exclusive with the change in #8877. They both fix the crash, but …
> Create NPCAction that wraps MissionAction for NPCs and records usage to prevent crash

- source/AI.cpp
**Bugfix:**
Thanks to riyan_gendut for reporting this on Discord.
Not allowing ships that are targeting an asteroid to consider ships to target can, in some situations, prevent the target ship of an attack or finish off order from being adopted by the ship as its own target, which leads to the ships doing undesirable things, like landing or leaving the system when they have been told to fire on a specific ship.
The easiest way to reproduce this seems to be to instruct escorts to fire on an asteroid and then immediately tell them to fire on a ship before they can destroy the asteroid.
https://www.youtube.com/watch?v=J5AOu3RbRmY
Applying the same steps after this change results in the ships behaving correctly instead of what they do in the video: start jumping out of the system.
This save …
> Do not prevent ships targeting an asteroid from looking for ships to target

- changelog
- source/Preferences.cpp
Makes the status overlays off by default, and fixes the logic that converts the old preference to the newer name
Tested this with the three possible variations (new preference file, old preference file "on", old preference file "off")
> Fix default status overlay preference

- utils/contentStyle.json
**Feature:** This PR adds two new regex-based checks to the content style checker that check whether 'a' and 'an' are used correctly. Some additional safeguards might be required in the future if a new alien race's language abuses these rules, or if there are some rare edge cases not listed. (Works with all current wanderer dialog.)
The checks only give a warning so it won't fail the CI for any new languages.
Found typos. Didn't find anything else. The new checks work correctly with the --auto-correct option.
> feat(testing): Add some rudamentary checks for indefinite articles to the content style checker

- data/remnant/remnant 2 side missions.txt
**Bugfix:**
Thanks to xmind for reporting this on Discord.
The on offer conversation currently begins by talking about the current location (Caelian) but refers to it with the `<destination>` text replacement which will become: "Viminal in the Arculus system" which is obviously not correct.
This PR replaces that text replacement with `<origin>` which will refer to the current planet.
(I tested the updated version on a planet called `Forge` by disabling the source filter. On Caelian, it will of course say `Caelian`. Also, ignore the colours.)
before | after
-- | --
> Correct text replacement in "Remnant: Shattered Light 6"

- data/human/ships.txt
This change addresses one of the major problems introduced via pull request #6203, that being that almost all human fighters have received a direct nerf in their efficacy in combat due to underutilized weapon space. With the additional hardpoints added to (most) human fighters in #8469, no tweaks were made to the kits, so this PR attempts to remedy the nerf to human combat fighters due to the former PR.
I've changed 3 ships in this PR, and only the stock variants: The Finch, the Dagger, and the Lance.
1) The Finch has received a second Javelin Pod and a Javelin Storage crate with no other changes. The reason for this is that the Finch is supposed to be a "top tier fighter", so doubling down on firepower would allow it to better go toe-to-toe with other fighters and small ships.
2) The …
> [Balance] Buff Stock Fighter Kits

- data/human/human missions.txt
This PR partially addresses #8838 by adding a sentence to the mission description about hailing the spaceport authorities to land.
Just need to check the new sentence fits the description box in game. It should do.
There are other solutions like adding an `on enter` dialogue box pop up when you enter Shaula. But I couldn't think of anything that would fit well, especially if I had to tell the player to hit `shift + T` while selecting Greenrock.
> Add text reminding player to hail Greenrock in the 'Deal Change' missions

- source/PlayerInfo.cpp
(You can open a PR to add or improve a section, if you find them lacking!)
**Bugfix:** (I found the bug, and made this patch rather than file a bug report)
When landing, this moves the player cargo hold size calculation and shifting cargo from ship cargo holds to the player cargo hold to after the ships' locations are updated to point to the planet.
It's a simple fix, I did not do extensive testing.  Having cargo, departing from a planet and immediately landing worked correctly (cargo was found).  Jumping to a new system and landing also worked.
[Aria Schafer.txt](https://github.com/endless-sky/endless-sky/files/11850127/Aria.Schafer.txt)
The bug will occur when using …
> fixed cargo capacity calculation when landing

- source/PlayerInfo.cpp
**Refactor:**
Shouldn't change the result of the code, just does it in a way that doesn't duplicate lines, doesn't nest as much, and I think is clearer.
> A small refactor to planet selection for in-system escorts that can't land on the player's planet in PlayerInfo::Land

- data/_ui/interfaces.txt
- source/Engine.cpp
**Feature:**
Inspired by #8955.
This PR gives the flagship status overlay its own set of named colours, separate to the escort overlay colours, allows the flagship overlay colours to be customised without modifying the escort colours so they don't have to be the same.
Also, fixes a bug where the scan overlay constructor was not properly updated when the neutral status overlay colours were added resulting in the scan overlays currently using the `neutral overlay shields` for outfit scans and `neutral overlay hull` for cargo scan.
Also, changed an integer literal to a double literal (`0` -> `0.`) to match the value it is passed as.
Also, adds some trialing decimal points to zeroes for consistency with all the other colour definitions.
<details> <summary>Demonstrating the scan ring colour …
> Separate flagship overlay colours

- data/_ui/interfaces.txt
- source/MapPanel.cpp
**Bugfix:** This PR fixes #8888
When the screen width is lower than 1280 px, the game reads positions of the mode buttons from a separate interface, displaying the buttons in two rows.
You can set window size in the preferences file or just resize the game window.
N/A
> fix(ui): Fix map buttons overlapping on smaller screens

- data/human/hails.txt
**Bugfix:** This PR addresses issue #8942
Adds in a missing space.
Do I need to?
N/A, just text changes.
> fix(typo): add in a missing space

- data/map planets.txt
Adds the ringworld attribute to Quarg ringworlds, and also to the Heliarch ringworlds. This attribute is used by the "Quarg Pug Arfecta Warning" mission, but doesn't actually appear anywhere, and thus that mission can't actually offer. This also makes it possible for future missions to differentiate the Quarg ringworlds from other Quarg stations, and likewise the Heliarch ringworlds from other Heliarch stations.
> Add the ringworld attribute to ringworlds

- data/dialog phrases.txt
- data/human/human missions.txt
- data/human/pirate jobs.txt
**Content (Missions / Jobs)**
Just some minor text corrections I noticed were needed while playing the 0.10.2 release.
Regarding the blind man mission from #8484, I understand there are times when a character may be deliberately written with bad grammar, but the receptionist doesn't appear to be one of those cases.
> Minor text corrections

- data/map systems.txt
**Bugfix:**
Thanks to @MidnightPlugins for reporting this on Discord.f
Eavine's object, and its parent and sibling, were previously removed erroneously, and apparently not noticed until Midnight brought it up.
This PR re-adds those objects to Paeli and increases the period of the parent to fit the new trend.
0
> Re-add Eavine to the map

- source/TradingPanel.cpp
Changed sell-all loop to only go over commodities in player's cargo, not all commodities in the game.  This now matches the following loop that sells all outfits in the player's cargo.
Sell-all works normally, with a variety of commodities/outfits.
> Update TradingPanel.cpp (sell-all)

- data/vyrmeid/vyrmeid.txt
Resolves https://github.com/endless-sky/endless-sky/issues/8947 by adding `inscrutable` so you can't actually see the internals of Astral Cetaceans.
Have fun and go find one and scan them! (If you really need a save I can make one.)
> fix(content): Add `inscrutable` to Astral Cetaceans

- data/bunrodea/bunrodea outfits.txt
**Bugfix:** This PR addresses an issue raised by BBHood217 on the discord.
Adds the missing `unplunderable` attribute to the lasher pistol.
None
None
> Fix(content): Add unplunderable to the lasher pistol

- data/human/ships.txt
The second torpedo launcher was replaced with a sidewinder missile launcher when many human secondary weapons were made larger and there was no longer enough space in the Frigate for the second torpedo launcher.
This PR replaces the LP144a battery with an LP072a and LP036a which leaves enough room to upgrade from the sidewinder launcher to another torpedo launcher, making the ship not only look better in operation but meaning that fire from both launchers will arrive at the target at approximately the same time, increasing the load on their anti-missile systems.
While this battery configuration offers less capacity than a single LP144a, following the battery buff, it is still more than enough energy for this ship.
> Give the Frigate back its second torpedo launcher

- data/remnant/remnant 2 side missions.txt
**Bugfix:**
The conversation for Shattered Light 4 branches for players piloting the living ships (Peregrine or Merganser) to add detail, but there's a bug that means the final paragraphs are not displayed if that's not the case.
> fix Shattered Light 4 conversation

- source/DataWriter.cpp
**Bugfix:**
Thanks to @Zitchas for reporting the issue that led to me finding this on Discord.
In #8744, a special case for saving a token that is an empty string was removed, this leads to nothing being saved for empty string tokens, instead of a pair of quote marks (`""`) to indicate that there is indeed a token and that it is just an empty string.
In this case, an empty government name (empty because it was loaded and saved by a version of the game where the original government was undefined) was not correctly saved:
```
government ""
```
Became:
```
government 
```
In this case, NPC::Load sees a single token, and so skips the line and no government is assigned to the ships in that NPC, meaning the government pointer in those Ship objects is null. This led to a crash moments after take …
> fix(DataWriter): Properly save empty string tokens

- data/human/human missions.txt
**Bugfix:** This PR addresses issue #8981
The player is hostile to the Republic, Free Worlds, and Netural governments which prevents "Expedition to Hope 2" from offering because it cannot find a destination location where the player will be allowed to land.
This PR adds `clearance` to the mission so it will select planets that would not otherwise welcome the player.
Use the attached save. Without this PR, "Expedition to Hope 2" does not trigger when landing on Hope, with it, it does.
[PEPSI MAAAAAAN DUNDUNDUNDUNDUN~bugged save.txt](https://github.com/endless-sky/endless-sky/files/11929962/PEPSI.MAAAAAAN.DUNDUNDUNDUNDUN.bugged.sa …
> Make "Expedition to Hope 2" provide clearance for the destination planet

- data/wanderer/wanderers start.txt
**Bugfix:**
Thanks to @Skeltek for reporting this.
The original patch granting this license to saves that did the missions before it existed was broken when the point at which the license is granted was moved to a mission later. This PR adds a new patch mission that grants the license if the mission where it is supposed to be granted has occurred and the player does not have it.
0
> Wanderer outfits license patch

- source/HailPanel.cpp
**Bugfix:** This PR addresses not being able to land with bribes when your value is negative (with the shooting star having a negative cost)
Just make sure the total value is at least 1, so we dont have negative bribe with sqrt of a negative int going on.
this PR with that savefile (you can pay them to land just fine)
master:
which you can't even pay
[Isatrane_Reck.txt](https://github.com/endless-sky/endless-sky/files/11872182/Isatrane_Reck.txt)
> Bugfix: prevent negative value for bribes

- data/hai/hai reveal 6 end.txt
- data/map systems.txt
**Bugfix:** This PR addresses issue #7702 
Added the "inaccessible" attribute to the deep space systems, devil run and devil hide. Remnant: Expanded Horizons Astral job is set to not use systems with this attribute as waypoints.
Whenever the portion of HR that uses these systems becomes available, we may want an event to remove this attribute.
Arguably not actually testing, but I searched every file in the data folder for "inaccessible" to check that the attribute wasn't being used for anything else, and it isn't. So this shouldn't cause any issues.
Not sure I can use a save file to prove that the mission _doesn't_ offer with these systems as waypoints, but this should work in theory.
> fix(content): Prevent Remnant: Expanded Horizons Astral job from having the HR systems as waypoints

- data/remnant/remnant 1 introduction.txt
**Refactor:**
The missions "Remnant: Key Stones" and "Remnant: Key Stones (Hai)" are almost identical, with the only differences being the conversation text and the `to offer` conditions (which are themselves almost identical.)
Since so much of the conversation text is the same between both paths, we can use the `outfit: <outfit>` autocondition to add a branch to the existing named conversation that is already used by multiple missions in this group, meaning the same text for the same purpose no longer needs to be replicated in multiple places.
The `on offer` conditions can also be combined, meaning that a single mission can now handle the work of both existing missions, so that everything else about the two missions doesn't need to be reproduced.
This PR also modifies the `to offer` …
> Combine remnant keystone missions

- data/human/news.txt
Adds lore about fighters requiring engines, as suggested by @1010todd in [this comment](https://github.com/endless-sky/endless-sky/issues/8979#issuecomment-1616683231).
It felt lame to write a single news entry, so I added a couple other ones as well. (For reference, it's the second entry that was written for the suggestion.)
N/A, this should trigger pretty much anywhere in human space, you can just get a new pilot.
> feat(content): Add more human news

- data/_ui/interfaces.txt
- source/ShipInfoPanel.cpp
Added four new colors to the `interfaces.txt` file: two for guns and two for turrets (normal and hover state).
These colors replace the currently used hardcoded color values of the lines connecting hardpoints with respective weapon names on the Ship Info panel.
Calculated the color values to be the same as currently, so N/A.
yes.
N/A
> refactor(ui): Define Ship Info hardpoint colors as game data

- .github/ISSUE_TEMPLATE/config.yml
Lately, there's been a number of mobile-specific issues which would be better raised on the mobile port's site. So many people play on mobile now that it is probably worth providing a link to where mobile-related issues should be posted, to avoid cluttering up the issues page and creating hassle for everyone.
This PR adds said link to the issue template selection page.
Also, mentioning @thewierdnut since this concerns ES Mobile.
> Add a Link to Endless Sky Mobile's Issue Page

- source/Engine.cpp
- source/StarField.cpp
This PR prevents the starfield from having motion blur when it is disabled.
MB Enabled (was like this before even when disabled):
MB Disabled:
> Fix Starfield Having Motion Blur When Blur is Disabled.

- source/Mission.cpp
- source/Mission.h
- source/PlayerInfo.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #8603
- Added a new mission trigger and an `"on disabled"` node. It fires up when player's flagship becomes disabled.
- Added a condition returning 1 if the flagship is disabled.
Both the trigger and the condition have been tested by inserting some conversations into a mission.
Probably none.
> Add a mission trigger and a condition to check if the flagship is disabled

- source/Interface.cpp
- source/Interface.h
**Feature:**
Adds a new type of element to Interface: PointerElement.
This allows an interface to draw pointers with customisable position, size, orientation, and colour.
The orientation can either be given as an angle in degrees, counting clockwise with 0 being straight up, or a pair of values corresponding to the x and y components of a vector: positive x is right, positive y is down.
```
interface "whatever"
pointer
from 10 50
to 20 70
"orientation vector" 1 0
color "my color"
```
```html
pointer
from <x#> <y#> to <x#> <y#> [<anchor>]
["orientation angle" <degrees#>]
["orientation vector" <x#> <y#>]
[color <color>]
```
It builds!
> Add support for drawing pointers in an interface

- source/ShopPanel.cpp
**Bugfix:**
On the Shipyard/Outfitter screens, the detail panel (the one in the middle, that has the details of whatever's currently selected in the left panel) has scroll buttons that can't be clicked (although the panel is scrollable other ways, by keypress or scroll mouse).
Added a section to ShopPanel::Click() to check for clicks on those buttons.
Opened a game, selected a ship with enough details to be scrollable, tried clicking the buttons.
> fix(ui) : Shop detail panel click scrolling added

- data/_ui/interfaces.txt
Use a slightly stronger blue (`.43 .55 .85 .8` rather than `.43 .55 .70 .75`) in the `shields` colour in interfaces.txt
Taken from #8264, as requested.
Old
New
> Use a more vibrant blue for shields

- data/human/human missions.txt
The human mission Fumbling Mugger has a typo "everying"; should be "everything" instead.
> fix typo in "Fumbling Mugger"

- data/remnant/remnant events.txt
Keep Ssil Vida's "remnant station" attribute when people start working there
Though Ssil Vida had the "remnant station" attribute added, which prevents the "Broken Jump Drive Bounty" job from picking it as a destination, that attribute is removed upon the "Ssil Vida inhabited" event due to its entire definition being replaced and that event not yet being updated with the new attribute.
[Hannah Derinden.txt](https://github.com/endless-sky/endless-sky/files/12073893/Hannah.Derinden.txt)
**Bugfix:** I don't see a reported instance of this bug on GitHub, but I have seen screenshots from other players that verify they experience it too (the job incorrectly pointing to Ssil Vida).
Add the `"remnant station"` …
> fix(content): Keep Ssil Vida's "remnant station" attribute 

- data/human/ships.txt
**Balance:**
Gives the Dagger +5 engine space (30 -> 35), and replaces its X1700 Ion Thruster with an A120 Atomic Thruster. Shield generator is downgraded from a D23-QP to a D14-RN to make space. This gives the Dagger a top speed of 1466.6, a significant improvement over its previous 685.7, and noticeably better than the 1113.2 that the Finch can achieve with the same engine.
While various people have talked about the balance of fighters against other options, the balance within the fighter category in human space is in quite a bad position. The Finch is the fastest (thanks to its larger engine space), largest and toughest fighter. The Dagger is slower by ~150, yet the Dagger's description proclaims it to be "Considerably faster than other fighters". Given that the Dagger is a Lionheart …
> Feat(balance): Give the Dagger +5 engine space and an A120 atomic thruster, to give it a clearer niche and to better match its description

- source/OutfitterPanel.cpp
- source/ShipyardPanel.cpp
**Feature:**
In the Shipyard and Outfitter panels, the selected player ship (if any) will display a list of outfits after the list of attributes, exactly the same as for selected ships in the Shipyard panel (when you're looking at ships you don't own).  If multiple ships are selected, the last one selected will be displayed, same as is currently done for attributes.
This allows for an easy comparison with purchaseable ships, particularly when checking to see what changes you may have made to the stock model of your current ship, in the Shipyard panel.  It's also easier to see what outfits are already installed, as compared to looking through all the listed outfits in the Outfitter panel.
Took a save file with an existing ship with lots of outftis, looked at it in both panels.  Also tried …
> feat(ui): Outfits in drawshipssidebar
