endless-sky/endless-sky

OutfitInfoDisplay.cpp, ShipInfoDisplay.cpp, data/intro missions.txt, data/outfits.txt, data/power.txt, data/ships.txt
As the title says :)
The added colons are to follow the same convention as the other displayed characters in the InfoDisplay menus (most of them are followed by a colon).
The other changes are typo fixes.
=> Typo corrections and cosmetic changes

data/ships.txt
* Quote some unquoted ship/sprite names
* Unquote some quoted numeric values
* Standardise float values <1 e.g. change 0.1 to .1
=> Standardise formatting

data/map.txt
"for yearn for excitement" -> "that yearn for excitement"
=> fixed minor typo in planet text

data/free worlds checkmate.txt, data/free worlds intro.txt, data/free worlds middle.txt, data/free worlds reconciliation.txt, data/free worlds side plots.txt, data/map.txt, data/names.txt
Fixing a few typos that caught my attention.
=> Miscellaneous typo fixes.

source/AI.cpp
To match "Recalling fighters." string.
=> Add period to "Deploying fighters"

data/free worlds reconciliation.txt
Found and fixed some typo in mission text.
=> Fixed typo in mission "FW Pug 2C: Jump Drive"

data/free worlds checkmate.txt, data/free worlds middle.txt, data/free worlds reconciliation.txt, data/free worlds start.txt, data/map.txt, data/ships.txt
I went through all of the data/*.txt files with a spell checker, it caught a number of words that use the British rather than American English variants of words (e.g. "benefited" instead of "benefitted"), whereas I think the writing generally prefers the American English spellings. There are also some spelling/grammar errors regardless of the British/American distinction.
=> Corrected misspellings in multiple data/*.txt files

data/free worlds reconciliation.txt
Remove an extra quote from the `FW Reconciliation Break` mission.
=> Fixed typo.

data/map.txt, data/transport missions.txt
=> Fixed Typo

data/hails.txt
Added new hails and developped some of the existing ones
Nothing major
This is also my first pull request, and experimentation with the code, (please don't be mean)
=> Increase in hail variety

data/hails.txt
=> "as you're" doesn't work much of the time in hails.txt

data/map.txt
"The result are..." -> "The results are..."
=> Fixed a Typo

data/hails.txt
Fixed these hails so that there's a space where previously there was none.
=> Fixes for some of the new Syndicate hails

data/ships.txt
"It can hold it own" -> "it can hold its own"
=> Fixed Typo in ship description

source/OutfitterPanel.cpp
"can't buy more copies of an outfit" -> "can't buy more of an outfit"
I don't feel strongly about this but thought I should say it sounds weird before I get too used to it. I think my suggestion is wrong but maybe it's pragmatic.
=> less correct but less jarring outfits copy

data/free worlds checkmate.txt, data/free worlds epilogue.txt, data/free worlds intro.txt, data/free worlds middle.txt, data/free worlds reconciliation.txt, data/free worlds start.txt
as per https://github.com/endless-sky/endless-sky/issues/749 promotes all the generals (at space) to admirals
=> general -> admiral

data/alien ships.txt
This fixes #756 by correcting the Wardragon's description.
=> Quick description fix for the Quarg Wardragon

source/Ship.cpp, source/Weapon.cpp, source/Weapon.h
I haven't been able to test this; nor has piercing been added to any in-game weapons (yet). However, it should work. Tell me if something's wrong, and I'll try to fix it.
=> Added piercing for weapons

data/free worlds start.txt
whether we to want → whether we want
=> Grammar fix

data/free worlds intro.txt
It says he's not not armed. Didn't know if it meant not unarmed, or if it was a repeat, so I chose the latter.
=> Intro typo fix

source/BankPanel.cpp, source/LoadPanel.cpp
Also fixes the same issue for the load panel
=> Fix endless-sky/endless-sky#795

data/free worlds checkmate.txt, data/map.txt, data/transport missions.txt, data/wanderers.txt, data/weapons.txt
Typo fixes
http://steamcommunity.com/app/404410/discussions/1/458607699619757456/#p1
=> Typo fixes

data/free worlds start.txt
I think I've finally got it to work.... sorry for my cluttering of your pull requests page.
Sys -> says.
=> Antares/Tomek typo fix (again)

data/names.txt, source/Phrase.cpp, source/Phrase.h
The motivation here is an INN-like system. There are already some appropriate phrases, like sports team names or Syndicate advertisements, that would be nice to thread through both systems.
=> Allow subphrases within phrases

source/OutfitInfoDisplay.cpp
=> fix turret info display error and gun info spelling mistake

README.md, data/free worlds middle.txt
to keep in line with the other mentions 
don't mind the 'test' commits. i'm just trying to learn how to use github
=> Change 'senate' to 'parliament' in republic context

data/transport missions.txt
Pretty sure this is intended to be "years" :D I'm interested in contributing to the game, gotta start somewhere.
=> Typo fix: s/year old/years old/

data/free worlds side plots.txt, data/free worlds start.txt
Continuation of #966.
Hopefully I wont brake this one.
=> FW continuity fix

data/persons.txt
Seems like most players didn't jump on the train for content creation, but saw it as help in the grind.
Edit: I mean, i do make blender files, but they are blender files, and nothing ingame.
=> Removed misunderstood lines

data/map.txt
truck - trucks
Edit: sorry it says I changed the whole paragraph.. All I did was add an s. :/
=> Small typo

source/Engine.cpp
fixes commit: https://github.com/endless-sky/endless-sky/commit/e814753cc5153e63f39c31d488be0903adcc5e66
=> SyntaxCorrection

data/hails.txt
I feel like this would be a good fix to replace the use of the word "world" in one of the Navy hails.
I changed "need" to "want" as well because that was the original saying:
https://www.loc.gov/exhibits/treasures/images/tlc0090.jpg
=> Fix awkward use of "world" in Navy hail

data/free worlds reconciliation.txt
Just a tiny fix.
I've really been enjoying this quest and some of the decisions it's made me take have been pretty difficult... Great job!
=> Fix spelling mistake in FWR

source/PlayerInfo.cpp
Allowed outfits that won't fit in your cargo holds during TakeOff to be sold off instead of being vaporized.
=> re: https://github.com/endless-sky/endless-sky/issues/1209

data/map.txt
earth -> Earth
Funny, Earth is one of those words that look really weird after looking at it for a minute.
=> Capitalization

source/ShipyardPanel.cpp
[enhancement] added a credit total to the ship selling confirmation dialogue at the shipyard
=> credit total for ship selling confirmation box

source/InfoPanel.cpp
this kept coming in useful for me for testing purposes so it seemed like it could be useful for players too
=> allow dump all cargo on info panel to dump outfits if there's no commodities

source/OutfitterPanel.cpp
re: https://github.com/endless-sky/endless-sky/issues/1285
small fix to be specific about its check instead of using HasItem
=> change CheckRefill to use a more limited check

source/BoardingPanel.cpp
=> change boarding screen to show fractional mass outfits

EndlessSky.xcodeproj/project.pbxproj, credits.txt
also, a little credit.
edit; i figured it's earned, as your apparently current most active Mac OS X compiler (i've pulled the last three of these XCode project updates), and the numerous other bug reports (some of which, several weeks ahead of confirmation) and enhancement suggestions (most proud of planet indicator enhancement) i've brought forward long before the release schedule.
M.Z.: i'm sure you're aware of all of this - i just wanted others to know my reasoning for requesting the addition, so you suddenly don't get a flood of the second part of this commit.
=> Update XCode project with Hardpoints and Body classes

data/free worlds epilogue.txt
#1331 
"Everything the left " -> "Everything they left "
=> Issue 1331, fix typo in FW Epilogue

data/free worlds reconciliation.txt
http://steamcommunity.com/app/404410/discussions/1/359543951709928034/
=> Keeping the Extremists hostile

data/kestrel.txt
=> Fixing Kestrel turret coordinates

data/free worlds intro.txt
This pull request fixes the typos mentioned in #1478 and #1477.
=> Typo fix - free worlds intro.txt

SConstruct, endless-sky.appdata.xml
https://people.freedesktop.org/~hughsient/appdata/ has more information on how this works.
=> Added a Linux AppData file

data/map.txt
=> Fixed a grammar error in Haven's description

source/PlanetPanel.cpp
re: https://github.com/endless-sky/endless-sky/issues/1270
departure from the planet panel will now check whether missions will fail due to insufficient cargo space or bunks. it feels slightly verbose and I've very open to better wording
[bug] additionally panels weren't being popped, causing you to become stuck on a planet if you got an okay/cancel dialogue while a panel like trade/bank/hire was selected
=> add passenger space check, fix panel popping

source/Politics.cpp
This addresses issue https://github.com/endless-sky/endless-sky/issues/1547.
=> Re-worded the fine dialog to remove awkwardness

data/free worlds start.txt
=> Fixed a typo in this mission

data/hai missions.txt, data/map.txt, data/transport missions.txt, data/wanderer missions.txt
=> fix some typos

CONTRIBUTING.md
Fix typo in CONTRIBUTING.md. Changing 'to easy or hard' for 'too easy or hard'.
=> Fix typo in file contributing.md

data/persons.txt, data/ships.txt
so that M.M.K. is more combat worthy, and uses more outfits created by the artist he pays homage to.
=> Re-Fit Marauder Fury

data/events.txt
=> added Skeins to Dreadnought deployment

data/names.txt
Deathmonger! Bonesnake! Warspike!
=> More ship names, particularly for pirates

data/names.txt
Still more names! This adds a LOT of new variety to civilian and pirate ship names. With this, I feel like we're finally getting close to the point where there are enough for them, given how often you see them.
=> Many more ship name styles and words for civilians and pirates

data/ships.txt
Changed 'nearly half a millenium ago' to 'over half a millenium ago' to better reflect the game history.
=> Updated Firebird description

data/jobs.txt
This Pull Request implements https://github.com/endless-sky/endless-sky/issues/1773 as well as a few other minor changes to the escort missions. Here is a summary of the changes:
- Split each of the Northern and Core escort jobs into two, one of which is offered only at dangerous origins (frontier, north, core) but wants to go to safe destinations ("near earth", paradise, deep), and the other of which is offered at safe origins and wants to go to dangerous destinations.
- Changed the pirate fleet locations so that the dangerous origin jobs don't have pirates waiting at the destination, and the dangerous destination jobs don't have pirates waiting at the origin. In both cases, the removed pirate fleets instead spawn at a random nearby location (close to the origin for the dangerous origin …
=> Escort mission improvements

source/Sale.h
Allow items to be removed individually from Sale.
=> Selective Clearing

data/hai outfits.txt, data/korath outfits.txt, data/outfits.txt, data/wanderer outfits.txt, source/Outfit.cpp, source/Weapon.h
Exposed ammo to be loaded by all outfits not just weapons. #1853
=> Fix not autoselling ammo when selling storage item.

data/hails.txt
first pull request (did it for practise)
took about 10 minutes to figure everything out
found the typo when adding a bit to the bands part (2 bands that exist for myself)
the fixes:
Tarazed stadium -> Tarazed Stadium
Re-Inventing Rythmn -> Re-Inventing Rhythm
=> fixed 2 typos

copyright
Given that the bullet storage image was made from assets by MK, I listed him in the comment as well.
=> Copyright for ammo storage images

source/OutfitInfoDisplay.cpp
Scaled solar collection to 'per second' to be consistent with energy generation and how it appears in the idle energy bar once installed.
=> Made solar collection scale by 60 in Outfitting

data/governments.txt, data/hails.txt
Striking another bullet off the list. 👍
=> Militia Hails

data/wanderers middle.txt
fixed a typo
quizically > quizzically
btw, found out how to make a pull request more easily :3
=> text fixes (spelling/grammar)

data/fleets.txt, data/map.txt, data/variants.txt
Addresses #1577 by making the Human fleets in Hai space sometimes use Hai outfits, very rarely using Hai ships.
=> Human Hai Fleets

data/syndicate world jobs.txt
Reduced the length of the Syndicate Target Practice mission description to address https://github.com/endless-sky/endless-sky/issues/1940
=> Fix #1940 

data/coalition weapons.txt
=> Bombar(d)ment Turret spelling mistake

data/persons.txt
At the community's request, created an in-game Person for myself (Nate Graham/Pointedstick). Thanks for the good vibes, everyone!
Also fixed an issue with Marauding Max K's person (`government` was specified twice).
=> Captain Nate says: Ram them!

data/coalition missions.txt
Trivial fix for #1984: lowercase centaur in "the Centaur says..."
=> Fix a capitalisation typo in coalition missions

EndlessSky.xcodeproj/project.pbxproj
I added the new source files to the Xcode project.
=> Fixed Xcode project file.

data/hai outfits.txt, data/hai ships.txt
Lowercasing a few words in the newer Hai ship and outfit descriptions because there's not other examples in the game that I can find of words being capitalized in this way.
=> Fixing capitalization in Hai ship and outfit descriptions

data/transport missions.txt
=> Changing wording in Expedition to Hope 1

data/free worlds reconciliation.txt
=> Minor grammar correction

data/wanderers middle.txt
"Alninam" misspelt three times as "Alniyam"
=> Fix spelling Alniyam -> Alnilam

data/coalition ships.txt
https://github.com/endless-sky/endless-sky/issues/2043
=> Scrappy Punisher outfit typo

data/transport missions.txt
starting asking > started asking
=> typo fix in a There Might Be Riots transport mission

data/coalition jobs.txt
Fix for https://github.com/endless-sky/endless-sky/issues/2062
Sorry, I am a complete git noob.  Feel free to delete this and fix it properly.
=> Fix for non-repeating coalition jobs

data/wanderers start.txt
Capitalized 'Iktat' to fix issue #2070 identified by @Alkallid
=> Wanderers Invaded 3C typo fix

data/governments.txt, data/hails.txt
I felt lonely when I was friendly with pirates. No one would talk to me. Now they do!
Decided to not bundle this with the pirate jobs because they work independently of each other.
The first two friendly hails in the set are just slightly reworded hostile hails.
=> Friendly pirate hails

data/help.txt
Universe can a dangerous place > universe can be a dangerous place
=> Typo Fix, @alkalid

data/coalition missions.txt
>In the mission on Ring of Friendship, you tell the Heliarchs/Coalition
about the Hai, but you can do this before you have met the Hai.
@toilethinges
My change fixes this problem with a branch using the “First Contact:
Hai” condition.
Disclaimer: I have not had the time to test out my code changes, so that would be appreciated.
=> Coalition/Hai Inconsistency Fix (@toilethinges)

data/interfaces.txt, source/HailPanel.cpp, source/Politics.cpp, source/Politics.h
Allow freeing a dominated planet based on original proposal #870
=> Free Dominated Planet

data/wanderers middle.txt
http://steamcommunity.com/app/404410/discussions/0/135509024338822302/
There has been some confusion with this mission on Steam. I've changed the mission by making it more clear through Danforth's dialog that you most *completely destroy* the ships (I just copied from the mission that defers, because he makes it pretty clear there) as well as putting dialogs on all the fleets that pop up once you have wiped the system clean of Kor Sestor ships..
=> Sestor: Scattered Remnant change

data/hai outfits.txt
Standardize spelling of defense.
Also changed a capital to lowercase in missile.
=> Defence -> Defense

data/hails.txt
though - thought
payed - paid (yes, I know payed is a word, but paid is used everywhere else in the game.)
=> Hail typos

data/transport missions.txt
It was kind of annoying having another mission pop up while I'm getting ready to raid an Alpha base in Host.
=> Making Deep Archaeology 1 minor

data/wanderer jobs.txt
I was doing some of the Wanderer jobs while waiting for missions and noticed that a lot of them don't mention your payment in the on complete dialogs, which is inconsistent with other jobs,
=> Wanderer on complete dialogs now show payment

data/kestrel.txt
https://github.com/endless-sky/endless-sky/pull/2221#discussion_r109287047
=> Small Style Fix

data/hails.txt
=> can not -> cannot

source/Ship.cpp
Removed scanning messages if you scanned one of your own ships, solving issue #2434
=> Solution for issue #2434 : Removed scanning messages if you scan your own ships

data/wanderers middle.txt
=> Human spaceport hint for Sestor Search

data/transport missions.txt
Migrant Workers 1, line 1559. Thanks fgntlucas.
=> passengers added to transport mission

copyright, credits.txt
Putting spfldsatellite's copyright in (now I've got it).
=> Add copyright

data/hails.txt
Looks like no one ever noticed this.
=> Fix in pirate hail name

data/events.txt, data/korath.txt, data/wanderers middle.txt, data/wanderers start.txt
Using commit 9d8f06b8b37a1dca536e3727270a6a69b7743751 to shorten the events that change fleets.
=> Shortening events with add variant

data/map.txt
```
As per: http://steamcommunity.com/app/404410/discussions/1/2333276539613621549/
```
build -> built, in two occasions in map.txt.
=> Spelling corrections noted on Steam (Rhendox)

data/wanderers start.txt
Spotted a place where "the Eye" wasn't capitalized. I checked the rest of wanderer start and middle and this is the only instance that needed capitalized.
=> Capitalizing "the Eye" in "Wanderers Conversation"

source/Account.cpp, source/PlayerInfo.cpp
I have added commas to the displays of planet tribute, player salary, fines, mortgage payments, and, crew salaries.
Note: I have zero experience with C++, so sorry for any mistakes.
=> Prettify more credits displays with Format::Number

data/wanderers start.txt
=> Making "Unfettered: Jump Drive Source" invisible

data/hails.txt
=> Black vegetable new hails

source/AI.cpp
Commit 11774348c22 broke the assignment of fighters to a member of their government if they did not have a free bay to belong to.
This commit randomizes the assigned parent to one of the fellow members of the same government in the same system that is also not a fighter.
This prevents newly captured fighters from performing odd behaviors, such as beelining for the center of a system, as they will instead move to be near your ships.
=> Carried Ships find parents

data/hails.txt, source/MainPanel.cpp
Move the message definition into hails.txt to allow
1) Simpler contributions from the community (not "code" just "text")
2) Mod overwrites
=> enhancement: Allow mods to change wormhole hail messages

data/map.txt
Someone owes me a million credits for finding this.
=> Preventing Far Monad from fining the player

data/remnant missions.txt
=> Add source filter to Remnant Defense 3

data/wanderers start.txt
=> Fixing a typo in Wanderers: Translation Machine

source/MapPanel.cpp
=> Fix travel plan drawing error when no suitable flagship exists.

data/wanderer jobs.txt
=> Fixing errors in "Wanderer Invasive Species" jobs

source/AI.cpp, source/Engine.cpp
#2884 
I used `cend()` instead of `end()`, which fails on some platforms but not others, in #2861 
@endless-sky 's touchup in 381b01fa
This is a subtle nudge for #2786, which would have flagged my PR
=> Fix bugs in two recent commits

data/pirate jobs.txt
=> Fix doubled "description" in two pirate jobs

data/map.txt
=> fixed typo in trove

data/wanderers middle.txt
somehwere --> somewhere. Thanks @Bladewood for spotting.
=> Quarg Assistance 2 Typo Fix (refs #2953)

data/free worlds side plots.txt
Found this while testing #2957
=> Remove unused fleet name argument

data/free worlds middle.txt
=> Made the FW mission's Electron Turret version offer on landing

data/free worlds intro.txt
=> Add missing FW event

source/Politics.cpp
Remove the only warning given by GCC v7.1.
=> Removed compiler warning.

data/free worlds checkmate.txt, data/free worlds intro.txt, data/free worlds middle.txt, data/free worlds reconciliation.txt, data/free worlds side plots.txt, data/free worlds start.txt, data/jobs.txt, data/pirate jobs.txt, data/remnant missions.txt, data/transport missions.txt, data/wanderers middle.txt, data/wanderers start.txt
Implement the feature from #2957
=> Use fleet multiplier to simplify data/*txt files

data/variants.txt
removed mass expansions
added outfits expansions
=> fixed hired gun baccy

source/AI.cpp
=> Clear escorts' target system if landing instead

source/ShopPanel.cpp
=> Arrow keys should not select disabled, in-system ships

source/Ship.cpp
=> Avoid travelling backwards after exiting hyperspace

source/MissionAction.cpp
=> Missions can only be completed if available cargo is present in the system

data/commodities.txt
I have a really hard time imagining how can you fit a planet into your cargo bay.
=> Remove the "endangered planets" easter egg

source/AI.cpp
Brought up by @1010todd via Discord
The player's flagship is currently the only ship that will keep its target despite its target being untargetable, which can result in the player's flagship autofiring at the position of a cloaked opponent when any hardpoint's current aim would predict a collision.
This PR adds an IsTargetable() check prior to adding the ship's current target to the "we can autofire at these ships" list.
=> Flagship should not autofire at cloaked targets

source/Mission.cpp
https://github.com/endless-sky/endless-sky/issues/3049
=> Fix a use after free in mission generation

data/free worlds start.txt
=> Typo in free worlds start.txt

source/PlayerInfo.cpp
- courtesy of @comnom 
(silent nudge to #2786 )
=> Add include missing from endless-sky#3087

data/free worlds middle.txt, data/free worlds side plots.txt, data/free worlds start.txt, data/kestrel.txt, data/pirate jobs.txt, data/transport missions.txt
- Added `"fuel capacity" 1` to Rand's asteroid so it will "hit" and disappear (instead of circling).
- Use `attributes spaceport` to solve #2317 
- Some typos
Other refs #1330, #2623, #2637, #2296
=> Delay messages that may need hyperlinks

source/OutfitterPanel.cpp
=> Fix bug in OutfitterPanel::Refill if the player has no stock of ammo

data/map.txt
Ceasless Toil and Diligent Hand: Saryd factory worlds run by robots
Mystery and Revalation: uninhabited moons
For https://github.com/endless-sky/endless-sky/issues/2515
Still not sure on the Mereti stations (they could have Wanderers on them by the time you are allowed to land) so I'm not touching those.
=> Marking a few uninhabited worlds as such

source/Engine.cpp
It can display "Landing on", "Can land", and "Cannot land".
It adds "(mission)" when it is the destination of a mission.
=> Clarify "Landing on:" navigation mode.

data/transport missions.txt
Reported on steam http://steamcommunity.com/app/404410/discussions/1/1484358860956212716/
=> Add missing " mark

data/free worlds start.txt
Refs #3145 
It's best to not attempt to board spacecraft that are described to be barely spaceworthy.
=> Add self-destruct to Barmy's Doombat

source/Weapon.cpp
Refs #1485, #2003, https://github.com/endless-sky/endless-sky/commit/c3cb2551f67e9d3b57d45c37122f00523b005a71
=> Allow using fuel damage (fix from @Nechochwen-D)

data/names.txt
More words for the civilian and pirate ship names, and higher frequency for the standalone list of civilian ship names.
=> More ship names

source/Ship.cpp
Quick fix of a spelling error.  Mainly used as an example to figure out how to do Pull Request/Forks and the like for larger stuff.
=> Fix misspelling of deceleration

source/EscortDisplay.cpp, source/LoadPanel.cpp
Refs a247a00ae645a038ac5073cc073bca4b842b5461
=> Remove use of static inside anonymous namespace

source/Account.cpp, source/Account.h, source/PlayerInfo.cpp
Creates a few new automatic conditions to allow missions based on the player's financial acumen.
Refs #2737 
I'll let more seasoned writers draft the message / conversation @Pointedstick was looking for :+1:
=> Create player conditions for mortgages, fines, back pay, and credit score

source/AsteroidField.cpp
`min` was added in 14d70baf86932d887de41e3b1aedebd3c6e24633
=> Missing <algorithm> include

data/hai jobs.txt
=> Fix Unfettered Aid job destinations

data/wanderers.txt
Added a bit of diversity to the wanderer hails, that could otherwise get very repetitive late-game
=> Wanderer hail diversification

EndlessSky.xcodeproj/project.pbxproj
Adds BatchDrawList, BatchShader, and ImageSet (.cpp and .h) to
EndlessSky.xcodeproj/project.pbxproj , fixes linker problems when
building from source
=> Update file references in xcodeproj

source/Engine.cpp
=> Inscrutable targets are impervious to tactical scans too

source/Engine.cpp
Refs #3421 
- Use an anonymous function to determine if the given ship is capable of sending a hail (e.g not mute or out-of-system or uncrewed)
- Unify "author" formatting for message printing
=> Update "Grudge" messaging

source/LoadPanel.cpp, source/MapSalesPanel.h, source/MenuPanel.cpp, source/PreferencesPanel.cpp, source/ShopPanel.cpp
=> Truncate long player / player flagship names, and plugin names

data/interfaces.txt, source/BankPanel.cpp, source/BoardingPanel.cpp, source/ConversationPanel.cpp, source/Dialog.cpp, source/ItemInfoDisplay.cpp, source/LoadPanel.cpp, source/LogbookPanel.cpp, source/MapSalesPanel.cpp, source/MissionPanel.cpp, source/Panel.cpp, source/ShipInfoDisplay.cpp, source/ShopPanel.cpp, source/TradingPanel.cpp
- Further support for modified interfaces / reskinning, such as @comnom 's "Pug HUD" ( https://github.com/comnom/es-huds )
=> Define additional filled colors in interfaces.txt

data/variants.txt
Reordered `data/variants.txt` from its previously semi-ordered state into a more tenable structure.
Previously, variants appended to the end of the file, resulting in logical assortments of uses of a given weapon, engine, etc. As more variants were created, some were inserted near existing ones, and some were not, resulting in sections with various ordering schemes.
With this PR, the file does not need to be skipped around in order to assess the differences between any given variant of a base model, as all variants of a base model are next to each other.
<details><summary> The old order:</summary>
- Star Barge Armed
- Sparrow Patrol
- Raven Afterburner
- Wasp Patrol
- Manta Proton
- Quicksilver Proton
- Cruiser Heavy
- Scout Speedy
- Clipper Heavy
- Clipper Speedy
- Freighter Fancy
- …
=> Alphabetized variants.txt

data/interfaces.txt, source/MapDetailPanel.cpp, source/MapDetailPanel.h
- Swaps a few more colors from the map drawing system to be user-defined
- Removes an unused function declaration (function removed in https://github.com/endless-sky/endless-sky/commit/cdb1cb881d04b246feee03dff4ec0028f34f6327#diff-e0a59618d76b767cb62fa83a9f007c59L295)
=> User-defined colors & deprecated function

data/events.txt
per @tehhowch 's comments on #3322
=> converted reputation adjustments to minimums

data/weapons.txt
Now it to provides some more hints about how best to use and defeat them.
=> Adjusted the Meteor Missile's description 

data/jobs.txt
It seems logical that there should be core missions to defend against the Korath, so I wrote a couple missions where you fight off some Raiders
=> Added defense missions to the Core against Korath Attackers

source/Outfit.cpp, source/Ship.cpp
=> Save a ship's base mass.

data/remnant ships.txt
no idea if it's on purpose, while in doubt here's a PR.
it's also for better consistency with other entries imho.
=> added missing quotes on gascraft

data/korath outfits.txt
polishes the description and fixes some errors
=> polish up the korath repeater rifle description

source/Ship.cpp
=> When unloading bays, update cached carried mass

source/AI.cpp
Refs #3561 
- Even if a mission has a deadline, its destination should not be recommended if there are still waypoints or stopovers that need to be visited
=> Do not auto-land on destinations for missions with incomplete travel

data/persons.txt
2f5b760
(Edit: I was just playing last night and I successfully disabled and captured it, so it currently is not "never disabled." tehhowch gives explanation below)
=> Make Power of the People never disabled

credits.txt
realized i had up till now forgotten to add my name to the credits... woops.
=> add my name to credits

data/quarg ships.txt
Refs #1551 , as a placeholder until the Quarg content is further developed.
=> Add base hull "hull repair" for Quarg ships

source/Mission.cpp
@jostephd https://github.com/endless-sky/endless-sky/pull/3615#discussion_r165728476
Refs #2786
=> Remove erroneous semicolon

data/transport missions.txt
https://github.com/endless-sky/endless-sky/commit/01232cd08697137e12b77d229db57b80c8e40909#r28461795
=> Fixed the way the Smuggler's Den: Follow Up log is offered

data/ships.txt, data/variants.txt
Noticed that I missed this one.
~there's always more~
=> Re-ordered the Freighter hardpoint

source/Planet.cpp, source/Planet.h
This + #3720 + #3721 finally get my laptop much quieter and cooler on the map screen.
=> Precalculate Planet::IsInhabited

data/hai ships.txt
`data/coalition ships.txt`, `data/marauders.txt`, `data/variants.txt` are also in alphabetical order.
Second attempt, because #3555 had to be updated because of https://github.com/endless-sky/endless-sky/commit/eb5ceb4eafdbaf4a28e10b23aefbd66ea9c0a830
(Yes, I am aware github allows to merge different branches, but in this case figuring out how to do that was more time-consuming than just starting a new one.)
=> Alphabetized Hai variants

data/free worlds intro.txt
This simple PR adds a missing period in `free worlds intro.txt` (line 301)
=> Added a missing period in "FW Recon 1"

data/hails.txt
=> Add missing space to hail

data/governments.txt
I am wondering why the heck my hostile Heliarch hails doesn't appear, and I know now why. Silly me.
=> Set Heliarch's hostile hail

data/weapons.txt
Changed the beam laser description, because:
* 300 is not a "slightly" shorter range than 510 
* 60*(1+1.3)=138 is not "a comparable amount of damage" to 5*(9.6+6)=78.
=> Corrected beam laser description

endless-sky.appdata.xml
Following https://standards.freedesktop.org/menu-spec/latest/apas02.html
Did this mostly for better category filtering support for the flatpak appstream data.
=> Add categories to endless sky appdata.

data/transport missions.txt
=> Fail drug running missions if discovered by the authorities

endless-sky.6, source/GameData.cpp, source/GameData.h, source/main.cpp
This would keep the game from starting when you just want to know the ship and/or weapon data.
=> Quit after displaying tables

data/free worlds start.txt
https://cdn.discordapp.com/attachments/308902312741568512/480465996172230694/unknown.png
As spotted by Grunt on Discord.
=> Correct the named planet in FW pirates 3.1B

data/pirate jobs.txt
My new PR for assassination jobs, since I messed up the last time
=> Assassination Missions

data/variants.txt
Already done in #3439 but b3ea610de5b2a9c3a9c1014b78e944aa21e2b7ec inserted more variants. Ought to be uncontroversial.
=> alphabetized variants.txt (again)

data/hai ships.txt
Simple adds the leaks already in the game to the hai ships
=> Leaks added to Hai ships

data/transport missions.txt
The new terraforming missions are awesome! While playing through them I noticed a few instances awkwardly-worded text. This PR attempts to improve them.
=> Improve a few strings in the new terraforming missions

data/free worlds intro.txt
It's rather odd landing on the icy hellscape of Hope and finding a group of Navy troops waiting for me to check my cargo.
=> Made FW Katya 1C only offer on inhabited worlds

data/hai jobs.txt
This is just the Hai part of #4086.
=> Add novelty job for Hai who want to pretend to be criminals

data/jobs.txt
These are mirrors of the prisoner transport jobs, but pay less.
=> Add jobs to transport released prisoners home

data/jobs.txt
=> Fix bad indentations in mission "Released Prisoners."

source/AI.cpp
Current master: https://youtu.be/m9Pnv38m1fc
With this PR: https://youtu.be/Ij8IlIxCH60
I tried "damped" Turn commands of `.01`, `.05`, and went with `.025`.
- At `.01` the escorts will take a while to respond to changes in leader direction, and as such they spread out quite a bit
- At `.05` they are quite responsive, but one can more easily see the beginnings of the jitter behavior
In other words, if `.025` causes issues, we can change it.
=> Fix "turn jitter" in escort AI when following a ship

data/hai missions.txt
Contextually "ensures to you" seems less appropriate than "assures you" here.
=> Alteration of minor odd phrasing in Expanding Business 7.

data/syndicate jobs.txt
Mostly these are just flavorful variants of `"Brig"` jobs. I snuck one `"Luxury Accommodations"` job in there as well.
=> Add prisoner transport jobs for the Syndicate

source/SpriteShader.cpp
=> Typo in SpriteShader commet

source/ShipyardPanel.cpp
I missed this one when I was adding "the" to the beginning of all the ship names.
=> Add an article "the" when selling a ship at a shipyard

data/hai jobs.txt
A typo fixed in mission "Unfettered Aid [2]."
=> A typo fixed in mission "Unfettered Aid [2]."

data/hai missions.txt
=> Add 'accompany' to all npcs to escort in Expanding Business

data/governments.txt
Changes to attack and defence
Alpha: +0.4/+0.2
Korath: +0.4/+0.6
Navy Intelligence: +0.2/+0.2
Navy (Oathkeeper): +0.2/+0.2
Remnant: —/+0.2
Republic: +0.2/+0.2
Doesn't cover Coalition governments (there's a separate PR for them).
=> Slightly improve h2h capabilities of trained crews

source/GameData.cpp, source/GameEvent.cpp, source/GameEvent.h
Both can be created entirely through events, so an undefined planet or system is acceptable.
=> parse events for definitions while ref checking

data/ships.txt
This PR tweaks the starting ships to differentiate them a bit better from one another and adjust to the recent changes to missiles.
=> Tweak and differentiate the starting ships

credits.txt
they have added art so seems to be appropriate
=> Add other artist names to the credits

source/Engine.cpp
=> Make log(zoom) lerp to log(targetZoom)

data/remnant missions.txt, data/remnant outfits.txt, data/remnant ships.txt
Some small fixes for the Remnant Missions and/or Outfits.
So far, I've only played the first missions, so i'd prefer that this PR doesn't get merged yet (unless a mysterious release were to knock at the door).
=> Remnant Fixes

data/landing messages.txt
otherwise you get the star message.
=> add a landing message for black holes

data/events.txt, data/free worlds checkmate.txt
=> Pug and FW are now properly hostile during FWC Pug 3B

README.md
Steam Store rather than Steam Community is the more appropriate place to send new users, as long as the game is available on the Store anyway. A future delisting would warrant changing this back.
=> link to Steam Store in README.md

data/wanderers start.txt
A small typo that was spotted by u/NeeHaii [on reddit](https://www.reddit.com/r/endlesssky/comments/c3r437/just_wanted_to_bring_awareness_to_this_typo_your/).
```
Your drop Elias off on <origin>.
```
->
```
You drop Elias off on <origin>.
```
=> Typo in Alpha Surveillance J (u/NeeHaii)

source/BatchDrawList.cpp, source/Body.cpp, source/CaptureOdds.cpp, source/CargoHold.cpp, source/CollisionSet.cpp, source/DataNode.cpp, source/DataWriter.cpp, source/Dictionary.cpp, source/Font.cpp, source/Format.cpp, source/ItemInfoDisplay.h, source/Messages.cpp, source/Messages.h, source/MissionAction.cpp, source/Personality.cpp, source/Point.cpp, source/Politics.cpp, source/SavedGame.cpp, source/Table.cpp, source/shift.h
Fixed some (minor and easy to merge) style issues in the existing codebase.
=> Fixed some style issues in the existing codebase

source/AI.cpp, source/Engine.cpp, source/PreferencesPanel.cpp, source/System.cpp
No big changes, just some spaces removed.
=> Some more coding style fixes.

source/MapDetailPanel.cpp
Removed dead code, these buttons are entirely handled by the interface class which already intercepted the clicks in this area.
=> Removes some dead code, these buttons are entirely handled by the interface class.

source/UI.cpp, source/main.cpp
Some really minor improvements to some comments in the code.
Wanted to include those in other PRs, but didn't have another PR where those would fit in nicely.
=> Really minor code comment improvements

source/ShopPanel.cpp
Adjusted the clickable and hover area of the buy, sell, and leave buttons in the shipyard and outfit shops such that it matches the visual button area.
=> Buy, Sell, Leave button size fix

copyright
This PR just changes the copyright of the boxwing as it wasn't derived from MZ models, but original artwork
=> Updated the boxwing's copyright

data/ships.txt
@beccabunny noticed that they disordered many hardpoint whilst they had their new Southbound shipyard sprites merged. They asked whoever was available to help fix it, so here I am.
=> Fix ordering of hardpoints

data/remnant missions.txt
Fixes in `Remnant Missions.txt`
Line 870: thasher to thrasher
Line 873: tryping to trying
Thanks to Bladewood for spotting the tryping.
=> Fix: Remnant Missions spelling fixes (two)

data/map.txt
Planet in question being Second Viridian.
each -> reach
=> Fixed typo in the description of a Kimek Planet

data/fleets.txt
This PR adds the Osprey/Mule/Aerie/Vanguard/Protector to pirate fleets.
=> Add several ships to pirate fleets

data/transport missions.txt
Added a job where the player is tricked into losing 200000 credits with some inheritance scam story.
I considered an alternative ending (with low probability of appearing) where the player would actually receive half of the suggested inheritance, but decided not to include that.
=> Add scam job

data/intro missions.txt
Ref: #4218
Took and modified some bits from @Pointedstick's #4218 and from some of what @KikoTheExile has posted on the Discord.
Updated the intro missions with new information for the player.
* Sparrow starts are now told about the usefulness of missile launchers over beam lasers and energy blasters for the early game, as well as how mining might be a better choice than combat.
* Shuttle starts are now told about how not having any weapons will cause pirates to be less likely to target you when there are other targets nearby.
* Star Barge starts are now specifically told how it is that they can attract pirate raids, that is with high cargo space and low DPS.
* It is now made explicit that going to the spaceport is how you can be offered new missions. 
* Added an extra choice just before …
=> Updated the intro with new information

data/remnant ships.txt
Fixed the Penguin Gun & Turret Placement
=> Fixing Penguin Gun & Turret placement

SConstruct
Fixes build on GCC architectures on FreeBSD.
=> Respect CXX

data/remnant ships.txt
**Bugfix:** This PR fixes issue #4650 
Seems like my two [suggested](https://github.com/endless-sky/endless-sky/pull/4546#discussion_r339295199) [changes](https://github.com/endless-sky/endless-sky/pull/4546#discussion_r339295223) on this line cancelled each other out.
=> Typo: duplicate "an" in petrel description (@TBBunnyWoar)

data/interfaces.txt, source/Engine.cpp, source/Engine.h
Ref: #4268
This is how it looks in game with the currently selected colors.
=> Status overlays now show the disabled threshold

data/remnant ships.txt
**Bugfix:** This PR addresses issue #4733
As mentioned in the issue, this PR simply removes the leaks from the Ibis
=> Removed the leaks from the Ibis

data/map.txt
**Content**
This PR replaces the description of Relic with one that is much less underwritten. The only change in lore is that there is now only one settlement, unlike the previous version, which mentioned multiple. However, I think the point of the planet is still intact. As in, it was once expected to be a major planet, but has since become just a reminder of the past.
=> Change Relic's description

source/DataWriter.h
**Bugfix:** This PR addresses a very minor coding style issue that became blocking for #4411
Just removed some spaces and added a couple of tabs.
=> Fixed very minor coding style issues related to spaces and tabs

data/hails.txt
First time trying to add content using git.  Forum thread located at:
https://steamcommunity.com/app/404410/discussions/0/1643170903493823790/
=> Adds new friendly civilian hail

data/boarding missions.txt
This PR creates a new boarding mission which is offered in while assisting Merchants and Syndicate, where an asteroid is going to hit the disabled ship you are boarding. There are three versions of it, where some of the choices you can make have a different endings. There are two others, however, that either always fail or always succeed
=> New boarding mission

data/map.txt
=> Minor typo fix

data/remnant missions.txt
There is a small typo, "you" instead of "your".
=> fixing typo in remnant mission "expanded horizons quarg 1"

.github/pull_request_template.md
**Template:** This PR adds testing and performance sections to the PR template.
This adds testing and performance sections to the PR template. Adding those sections should help PR developers think about those topics before finalizing their PR.
=> Extend the PR template with testing and performance impact section.

data/map.txt
seems to acts -> seems to act
also added an a after the as, as I believe that was missing (?)
=> station cian typo fix

data/map.txt
**Bugfix:** This PR addresses issue #4863 
Build -> Built on line 27510
Thanks to Proont for spotting this typo.
=> Typo fix in map.txt

data/hai missions.txt, data/remnant missions.txt
**Bugfix:** This PR addresses issue that blocks Nanachi missions, and fixes one minor bug.
Fixed two simple errors in the condition variables relate to Hai first contact.
I played the Nanachi missions and "Remnant: Lost in Ember Waste."
=> Fix two conditions for Hai first contact.

source/PlayerInfo.cpp
**Feature:** This PR implements the feature request detailed and discussed in issue #{{insert number}}
Updating the automatic conditions here help to ensure that the conditions are up-to-date in relation to the current day/state of the game. This is useful for automatic testing that depend on those conditions being up-to-date.
N/A
N/A (Just use the conditions as usual.)
Verified that the game still properly compiles. Further validation needs to be done by code-review for now, I currently don't have actual code in-game yet that relies on this change.
No significant impact expected, this is just 1 other item that happens on a date-change.
=> Update the automatic conditions also on every IncrementDate()

data/wanderer/wanderers start.txt
Other plausible phrasing would be "any way around it".
=> Phrasing fix

data/remnant/remnant ships.txt
Spelling fixes on line 521.
resemblence -> resemblance
posses -> possess 
Thanks to Arrow2thekn33  for spotting these.
=> Fix (Spelling) in Pelican's description

data/remnant/remnant missions.txt, data/remnant/remnant outfits.txt
"any more" -> anymore
"can not" -> cannot
"maintnance" -> maintenance
"wooshing" -> whooshing
Note: Regarding "any more" and "can not", while the existing is technically correct, int those specific sentences the later flows better to me. (for what its' worth, they were both flagged by Word's grammar checker as something that should be replaced)
=> Fix: Some minor spelling and adjustments in Remnant missions

data/hai/hai missions.txt
**Bugfix** 
Fixes typos throughout hai missions.txt.
=> Fix Typos in hai missions.txt

source/Shader.cpp
Log shader link errors just like compilation ones
=> feat: Log shader link errors

source/BatchShader.cpp, source/FillShader.cpp, source/FogShader.cpp, source/Font.cpp, source/LineShader.cpp, source/OutlineShader.cpp, source/PointerShader.cpp, source/RingShader.cpp, source/SpriteShader.cpp, source/StarField.cpp
This makes it easier to debug compilation errors
=> feat: Add comment with shader name

.github/workflows/cd.yaml
**Bugfix:**: 
Apparently i forgot to add `brew update` to CD runs. The CI already does it correctly.
The actions run for this PR.
=> CD: Run brew update first

data/map.txt
(You can open a PR to add or improve a section, if you find them lacking!) 
**Content**
[the stars] *were* the only viable *options*, instead of *where* the only viable *opinion*
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/endless-sky/endless-sky/5043)
=> Typo fix for Relic

data/human/deep jobs.txt
=> Fix Typo in deep jobs.txt

data/hai/hai missions.txt
`could` makes more sense than `should` in this context.
=> Fix typo in hai missions (chould -> could).

data/remnant/remnant missions.txt
**Content (Missions) **
Fix typo - researchers' instead of researcher's
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/endless-sky/endless-sky/5083)
=> Remnant: Expanded Horizons Quarg 2 - fix typo

data/quarg/quarg missions.txt
adds 2 short missions to the Quarg in human space, + adds a mission where you can ask the Quarg about the Coalition*, after meeting them
*this one is called "Ask Quarg About Coalition Early" because I intend on adding another mission (which will use the same name, only "Late" instead of "Early"), which will be available after the player either is locked to the Heliarch side or the Resistance side of the Coalition campaign, and will branch accordingly to adjust the conversation for each. I haven't included that here since I don't feel it's quite well done yet, and it'd be easier to add it later than to make sure it fits now, (and how long it'd take for these short missions to get merged if it were PR'd with them, considering the branches would depend on stuff from the Heliarch and …
=> A couple Quarg missions

data/ka'het/ka'het missions.txt
This PR changes the wording in a Ka'het intro mission regarding the Ka'het tech found by the Remnant
=> Ka'het wording

data/human/free worlds epilogue.txt, data/human/free worlds side plots.txt, data/human/free worlds start.txt, data/human/kestrel.txt, data/human/transport missions.txt, data/intro missions.txt, data/remnant/remnant missions.txt, data/wanderer/wanderers middle.txt
While working on another PR, I noticed that in rare cases quotes were missing or set incorrectly. So, I had a look at the mission files and found inconsistencies in the 8 files belonging to this PR.
=> Cosmetics: addition and removal of some quotes

credits.txt
I prefer a real name rather than an account name. Been following the project sporadically, impressed at the work. Don't really think I should get a programming credit for minor edits, but you folks made the call. Keep on man, and good luck.
=> Trivial update in credits.txt

data/human/free worlds start.txt, data/human/transport missions.txt, data/sheragi/archaeology missions.txt
* Smart quotes are bad news (and not displayed by the game)
* Plural, other wording
* I feel that a Quarg wouldn't deign to say they "feel like"
=> Minor text changes

data/human/hails.txt
Very small change for very small people. Essentially just adds a hail phrase from the Merchants where they complain about how people aren't paying them enough these days.
=> new merchant hail

source/Engine.cpp, source/Ship.cpp
Improved some ambiguous text about threads and thread safety.
Fixed some spelling issue.
**Feature:** This PR improves some comments in Engine.cpp and fixes a spelling issue
Explains better where the action to pause the calculation thread happens; the original comment confused me a bit and it took quite a bit of time for me to find the actual location of finding the location where the thread was paused.
N/A (only comment changes)
=> feature: Improve comment in Engine.cpp about pausing the calculation thread.

data/coalition/coalition missions.txt
by @ Sergalicious from the Discord
=> Typo in Coalition missions: it's -> its

data/human/hails.txt, data/human/news.txt
Added some civilian hails on current and possible future game content. And added some news items based on sayings.
N/A
=> Some new civilian hails and some new news items.

data/human/news.txt
Bonus points for getting the references. Watch as I blatantly ignore the template like a baaaaaaad boy.
=> Add some creepy poetry to the spaceport news

data/human/hails.txt
Missing space in one of the new merchant hails
=> Spacing fix on hail

data/quarg/quarg missions.txt
the one where you ask the Quarg about the Coalition.
=> add missing period on Quarg mission

data/remnant/remnant outfits.txt
Like how every other ammo thing works
=> Fix the EMP Storage Bay to sell its ammo when sold

.github/workflows/ci.yml, source/main.cpp
=> ci: add test for memory leaks during file loading

data/interfaces.txt
**Feature:** This PR implements the feature request detailed and discussed in issue #1893
This PR adds a Find button to the map panel interface. Being able to search systems has been in the game for years, but has never been surfaced to players unless they accidentally press F. This communicates the function's existence at all times, which would be useful for things such as the FW Bounty missions.
=> Feature: Add Find button to map panel

data/hai/hai missions.txt, data/hai/hai outfits.txt, data/hai/hai ships.txt, data/hai/hai.txt
**Content (Tweak)**
Now that the Pond Strider PR is merged, and the Hai have access to a power source less intense than a nuclear reactor, I took a crack at reworking the default Aphid outfit loadout. This PR makes the Sand Cell available by default, puts two of them in place of the default Pebble Core, and swaps out the Pulse Turret for a Chameleon Anti-Missile.
While it is a thematic point of the Hai that they are less relentless in improving efficiency, the Aphid is extremely poorly balanced in terms of its outfit to hull cost (nearly 4 to 1!). This is mainly due to the Pebble Core providing far too much power, and the Pulse Turret giving poor defense, not letting an Aphid outgun a lone Grasshopper.
This shouldn't conflict with Nanachi's mission string, either. While 1.5 million …
=> Rebalance default Aphid kit to make use of Sand Cells

source/PlanetPanel.cpp
=> Fix depart warning bug

source/MainPanel.cpp, source/MapPanel.cpp
=> make zoom work with numpad keys

source/HiringPanel.cpp, source/TradingPanel.cpp
Haven't found any issues mentioning this.
=> make numpad + and - work in trading and hiring panels

data/ka'het/ka'het ships.txt
**Bugfix:** This PR addresses issue #5630
Added the `uncaptureable` tag to the disable-able Vareti'het variants.
=> Fix: Made disable-able Vareti'het uncapturable

tests/run_tests.sh, tests/run_tests_headless.sh
**Feature:** This PR implements additional graphical debugging info relevant for the discussion at [Discord](https://discord.com/channels/251118043411775489/285540320823869441/798236048844390400)
This PR adds printing of OpenGL-info, DISPLAY and XDG variables and running known X-services.
N/A
This is part of the CI test-suite. Check the logs and see the output when required.
This is part of the CI-system, so will be tested as part of the CI-runs.
The printing itself is likely very fast, but the output could be a bit too verbose (in which case we should follow-up with only printing the information when we detect a display issue in the test).
=> feat: Testframework: Print OpenGL, graphical environment variables and running services

credits.txt
**Content (minor credits update)**
Updated spelling/mentioning of my name from username to full name.
This matches the way Artwork and Beta Testers are mentioned.
N/A
N/A
=> Updated spelling/mentioning of my name from username to full name.

data/persons.txt
Very small PR, it just adds swizzle 0 under the shooting star to prevent it from being swizzled. Asteroids don't belong to any government, not even too self aware ones
=> Don't swizzle me

tests/config/preferences.txt
**Feature:** This PR updates the integration test framework with recent new preferences for pop-up help/hints. 
A number of help-pop-ups were added recently. The tests in the test-framework currently don't handle those hints, so the default preferences for the test-framework disable them.
N/A
N/A
Tested using some new (not yet released) tests for the test framework.
N/A
=> feat: Update integration test framework with new hint-preferences.

data/ka'het/ka'het ships.txt
Followup from #5631. Turns out, one was left.
=> Made another disable-able Vareti'het uncapturable

data/human/transport missions.txt
After playing the mission, it felt a bit awkward to me.
The following changes have been made to it:
- Improved the opening to make the mission start less abruptly
- Tweaked Donna's dialogue to make her feel more like a senior citizen
- Reduced the payment to reinforce ithe bitterness of their poverty in
retirement
- Minor grammar and punctuation improvements
=> fix(content): Tweak "Retired Family to Earth" mission

data/hai/hai missions.txt, data/sheragi/archaeology missions.txt
This PR fixes a small number of typos. Changes include switching an occurrence of "you" inside the logbook to "me" as I feel this would be more appropriate. However, it might be better to rephrase that sentence completely, because no other log entry I know of addresses the player directly.
This is my first contribution on GitHub, so any advice is always appreciated.
=> Various typo fixes

data/commodities.txt
Fix typo (`"laquer thinner"` -> `"lacquer thinner"`) as reported in https://discord.com/channels/251118043411775489/536900466655887360/836626570936451102
N/A
=> Fix lacquer typo in commodoties.txt

data/remnant/remnant missions.txt
**Bugfix:** This PR addresses comments posted on the [original PR](https://github.com/endless-sky/endless-sky/pull/5626) after the fact.
Thanks to TheMarksman-ES for taking the time to read through the PR and post some suggestions to improve the text. These are just a handful of minor wording changes - no impact to lore or functionality.
(They flagged the changes here: https://github.com/endless-sky/endless-sky/pull/5626 )
=> Fix: Remnant: Expanded Horizons Storms 1 proofreading changes

source/ShipInfoDisplay.cpp
This PR implements the feature request detailed and discussed in ~~issue #{{insert number}}~~ this PR, but see #4215 for a listing of related issues
Refactor the code that fills the ShipInfoDisplay heat/energy table to have each table cell's numeric value available in a local variable. This will make it easier to write a future patch that adds a `sum` row to the table without duplicating the calculations.
If adding rows isn't acceptable (see https://github.com/endless-sky/endless-sky/pull/3835#issuecomment-440531655), I'll add that row in a local patch (which I'll post it on my fork if there's interest), but even in that case it'd be nice if the PR was accepted so I would have fewer rebase conflicts with that patch.
No difference before/after the patch.
N/A
Loaded the Shipyard …
=> ShipInfoDisplay: Break out heat/energy table values into their own variables

data/remnant/remnant missions.txt
The description was telling the player to visit the planets in Pantica instead of Nenia.
=> Fixed the description of Remnant: Cognizance 1

data/quarg/quarg missions.txt
**Phrasing fix**
Spotted by Ornok in https://github.com/endless-sky/endless-sky/issues/5952, the mission can offer on Lagrange itself, so I went with the second option they gave, rephrasing the bit that could pose an issue.
Don't suppose it's the best rephrasing as I just glanced at it for some seconds, so feel free to present better ones.
=> Adjust phrasing in the mission Lagrange Ring: Cargo

data/remnant/remnant missions.txt
Changed line 1719 from `"They seem to have taking a liking to the void sprites,"` to `"They seem to have taken a liking to the void sprites,"`. Also tidied up the dialogue a bit by removing repeated information (we don't need to be told that it's good that they are distracted, since the other two sentences basically just say the same thing).
=> Edits to Remnant: Deep Surveillance

data/hai/hai missions.txt
From `Scar's Hideout is a hollowed out asteroids` to `Scar's Hideout is a hollowed out asteroid`.
Also, should it be `hollowed out asteroid` or `hollowed-out asteroid`?
=> Fix Grammar in Scar's Hideout's description

changelog, source/Ship.cpp
Fix active cooling generating heat when energy is negative.
=> Fix active cooling generating heat

changelog, data/ka'het/ka'het outfits.txt
I propose either "...required that the Builders develop..." or "...required the Builders to develop..."
=> Grammatical error in Ka'het Shield Restorer

data/hai/hai missions.txt, data/sheragi/sheragi outfits.txt
Replaced two occurrences of "travelling" with "traveling" for consistency with the rest of the game, where both "traveling" and "traveler" are spelled with a single 'l'.
=> fix(typo): travelling -> traveling

data/coalition/coalition news, data/coalition/coalition news.txt, data/map.txt
**Content (News)**
Creates the coalition news file, with what news I've written so far. I'll be trying to make more news for the Coalition, but I'm not good at it so please review the existing ones and suggest any ideas you have.
As a word of warning, the "coalition ad" news that talks about the energy drink is very close to the limit of the news box, so nothing too much longer than that would work as it'd be partially out of the box, as it happened to me when I was testing their length, before I trimmed down the longest ones.
=> Coalition News

data/human/transport missions.txt
Add some new missions about skydivers. They might look the same at first glance, but there are important differences between the jobs.
Still to be provided (it is also possible to test this by removing the random number conditions and just accept the jobs one by one as they appear in human space).
N/A
=> content: Add some human missions about skydiving/spacediving.

data/hai/hai missions.txt
Removed erroneous second landing tag in Strider: Remnant 3
The downsides of not having my mission builder finished :P
=> Removed erroneous second landing tag

tests/src/test_account.cpp
**Feature:** This PR implements a minimal unit-test for Account.cpp
This test was part of https://github.com/endless-sky/endless-sky/pull/5244 (and was a bit larger there), but it moved out of scope for PR 5344. I'm submitting this test as separate PR because the test itself might still be useful.
N/A
N/A (just run the test as part of the unit tests)
Automatically tested as part of CI.
N/A
=> Test: Add minimal unit-test for account.cpp

data/remnant/remnant missions.txt
**Bugfix:** 
Typo spotted by Scrungusbungus on the Discord. Thanks!
The word "agreed" is now replaced by "agreeing"
=> Fix: Remnant: Deep Surveillance: agreed to agreeing

data/human/transport missions.txt, source/SpriteShader.cpp
---------------------
Add a mission where a (not extremely successful) goon tries to extort money from the player. The player can respond in various ways.
N/A
N/A
=> feat(content): Add a Pirate-world mission about extortion

data/coalition/coalition missions.txt
**Bugfix:** This PR fixes a missing dialog goto as pointed out in Discord: https://github.com/endless-sky/endless-sky/pull/6169/files#r697888781
untested
=> Fix to Coalition Saryd University Lecture mission dialog flow

data/tests/tests_framework.txt, source/main.cpp
**Feature:** This PR improves the speed of integration testing by removing limits and reducing overhead.
Removed the 60 steps-per-second limit during testing and reduced the 3D/graphics drawing to once every 30 frames during testing. The 60 steps-per-second is valuable for players that want to run the game at a speed which humans can interact with, but for testing we are better off running as fast as the system can run for all code that is unaware of time in the real world (which is nearly all of the game-code).
Combined some small tests into a single larger test to reduce overhead.
N/A
Just run the tests.
```
time ./tests/run_tests.sh ./endless-sky ./
TAP version 13
1..4
ok 1 "Test-Framework - Calls - Arithmetic - Loops - Keyboard Control"
ok 2 "Test-Framework - Navigate"
ok 3 "Tests - …
```
=> test: Faster Integration Testing

data/hai/hai missions.txt
This is just a very minor text correction.
=> Fix minor typo

data/human/deep missions.txt
Flavor quests focused around Norn, Helheim and Alfheim in The Deep.
**Content Missions**
A series of missions that begin in Helheim, move to Norn, and eventually take the player to Alfheim. Doing the entire series of quests nets the player 500,000 credits. However there is a 30 day and 60 day wait between some missions, meaning that it would take at least 90 in-game days to complete. 
My goal was to add some minor flavor to The Deep. 
To start the mission head to Helheim spaceport.
=> The Deep (minor) Flavor Missions

data/human/human missions.txt
This PR extends the conversation in Terminus exploration to allow the player to ask about Ivan's suspicion that the anomaly in Terminus is a wormhole. Ivan then responds with telling the player about the Hai wormhole, although without saying where it leads or exactly where it is. The purpose of this is to give the player more of a hint as to where they should go in order to get Deep: Remnant to offer. If the player has already met the Hai, then they ask if he's referring to the Hai wormhole, to which he responds yes.
N/A
N/A
=> Have Ivan give the player a hint to the Hai wormhole's existence and whereabouts

source/MainPanel.cpp
Alternate solution to https://github.com/endless-sky/endless-sky/pull/6325
=> Use DoHelp for lost tutorial messages.

data/coalition/coalition.txt, data/human/human missions.txt, data/remnant/remnant missions.txt, data/remnant/remnant news.txt
Replaces six instances of `can not` with `cannot`.
As per both Merriam Webster and Grammerly, while both are technically correct, typically `can not` is only used when the `not` is part of a different phrase, as in the example `Now I can not only smell the pie, but I can also see it.` In pretty much all other cases `cannot` is the more correct spelling.
https://www.merriam-webster.com/words-at-play/cannot-vs-can-not-is-there-a-difference
https://www.grammarly.com/blog/cannot-or-can-not
Pointed out by Wedge009 here: https://github.com/endless-sky/endless-sky/pull/5626#discussion_r748682390
Prompted by their comment, I took a look through all the instances of `can not` in the data files (only six of them, total), as well as checking [Merriam Webster's …
=> Fix: can not -> cannot

source/Ship.cpp
Fixes a bug I introduced in the recently merged PR #6216. That PR counted the outfits incorrectly.
=> Fix outfit count when deciding whether to clear the armaments.

data/hai/hai outfits.txt
Correcting spelling error introduced in #4494, making direct issue/report as recommended by @Zitchas in #5626.
=> Spelling correction: compliment -> complement

data/human/hails.txt
A handful of hostile hails that use the shakespearean insults toward the beginning rather than at the end. Plus one more to the existing list
Also some new disabled hails that are general enough for just about any human faction, but I think fit the Free Worlds slightly more so (in between the formal Navy and melancholy merchants). They're weighted to be shorter so longer responses would feel more novel
Think I made an extraneous step here
=> feat(content): Additonal Disabled Hails

source/AI.cpp, source/Color.h, source/Command.h, source/ConditionSet.cpp, source/ConversationPanel.cpp, source/FogShader.cpp, source/Outfit.cpp, source/OutfitterPanel.cpp, source/Person.cpp, source/Person.h, source/Phrase.cpp, source/Phrase.h, source/Politics.cpp, source/Ship.cpp, source/Test.h, source/TestData.cpp, source/text/Format.h
This PR simply fixes every typo in the source files. Most of those are comments but one of them is a variable and the other is a typo in a string.
=> Fix typos in the code.

data/map.txt
**Content**
This change is somewhat in preparation for #6359. In thinking of potential alternate solutions to that issue, I remembered that I had written a Java program that parsed and then formatted the map file. This PR is the results of that formatting.
* Anything that can be alphabetically sorted is. This includes galaxies, systems, planets, links, fleets, hazards, asteroids, minables, attributes, and probably a few other things.
* I'll note that of all the map data, the one thing that wasn't typically sorted was system and planet attributes. The prior standard was typically region first, then anything else after that, but that wasn't exactly set in stone. I could change the formatter to just write attributes as they were read if desired, meaning that attributes would stay …
=> refactor(content): Standardize map data

credits.txt
Congratulations. With power comes great responsibility.
This change simply updates the Developers section of the credit file with our two newest additions to the team.
=> (Credit update) Add MCO & W1zrad to Developer section

data/coalition/coalition missions.txt
A few months ago, I made a pull request (https://github.com/endless-sky/endless-sky/pull/6169) for a new mission involving a seminar on humanity in Coalition space. Unfortunately it was merged before Arachi had a chance to look at it. This PR aims to address issues he found with the mission. This includes fixing dialog and poorly thought out lore implications. 
Any file where the player has met the Coalition works. Branching dialog depends on having met the Hai, Quarg, and Korath.
=> Fix Coalition Interview Mission

data/remnant/remnant 2 cognizance.txt
**Bugfix:**
Lines 771 and 778 principle to principal.
Also rewording the sentence to be slightly shorter and flow a bit better.
Thank you to KarikVot on the Endless Sky Discord for spotting this!
=> Fix: Remnant: Correcting principle to principal

EndlessSkyTests.cbp, tests/src/comparators/test_byGivenOrder.cpp, tests/src/comparators/test_byName.cpp
#6465 added two new comparators, ByGivenOrder and ByName.
This PR adds tests for them.
=> Add tests for comparators added in #6465

data/human/culture conversations.txt
These two conversations come to you courtesy of @TheMarksman-ES sending me some drafts to turn into a PR.
For concept criticism please direct your comments at him
For implementation including the mission structure, source locations or miscellaneous grammar fixes that'll be me.
=> Culture Convos 1 & 2 from TheMarksman

changelog
**Bugfix:** This PR addresses an issue reported by Kanerix
Line 94: Zitchs -> Zitchas
Thank you to Kanerix on Discord for reporting this, and reminding me a few times.
Look at the change-log
n/a
=> Fix: mis-spelling of my  name

data/human/culture conversations.txt
These three conversations come to you courtesy of @TheMarksman-ES producing drafts to turn into a PR.
For concept criticism please direct your comments at him
For implementation including the mission structure, source locations or miscellaneous grammar fixes that'll be me.
=> Culture Convos 10 through 12 from Marksman

data/wanderer/wanderers start.txt
=> Fix condition check in "Wanderers: Hai Diplomat"

data/human/human missions.txt
They say they've done the research.
=> Make "Hauler VI cargo prototype 1" not offer if the player has no weapons

data/human/ships.txt
=> Correct Protector description to reflect buffed number of hardpoints

data/remnant/remnant 2 cognizance.txt
Removed an extraneous word:
`	The Remnant around you look amused. "Do not be concerned, <first>. Everything you say will reach them. The sooner you tell us, the sooner we can take start preparing for whatever is necessary.`
To:
`	The Remnant around you look amused. "Do not be concerned, <first>. Everything you say will reach them. The sooner you tell us, the sooner we can start preparing for whatever is necessary.`
=> Typo fix in Cognizance 38

data/human/marauders.txt
The MRavenE now has 4 engine flares instead of 3.
=> Update Marauder Raven (Engines) description to match visual changes

data/remnant/remnant 2 cognizance.txt
'Set up' is a verb, 'setup' is a noun.
=> Fix verb 'set up' not 'setup'

data/human/human missions.txt
=> Action choices to First person

.github/workflows/ci.yml
Fixes a small change missed in #6970.  @quyykk noticed the fix and I'm just relaying their will.
=> CI only: Bugfix windows build part 2

README.md
**Bugfix:** This PR addresses issue #6961
Updated README.md to also include non-CC licenses for artwork
Fixes: https://github.com/endless-sky/endless-sky/issues/6961
=> fix(licenses): Updated README.md to also include non-CC licenses for artwork

endless-sky.desktop
PrefersNonDefaultGPU=true makes it use the dedicated GPU (if available)
and SingleMainWindow=true makes desktop environments hide the "New
window" menu item if the user right-clicks on its icon.
=> docs: Add PrefersNonDefaultGPU and SingleMainWindow keys to desktop file

data/human/deep missions.txt, data/human/free worlds start.txt
Thanks to Bardagh on the Discord for finding this typo.
=> fix(typo): Correct various typos

.codespell.exclude, data/human/human missions.txt, data/wanderer/wanderer news.txt
We are getting spell checks errors on all PRs when they are updated because new words were added to the spellchecker.
This addresses that. Two were obvious mistakes, and the third one is a Pug word, which I added to the .exclude file.
=> (bug) spellcheck quickfix

source/GameWindow.cpp, source/MapPanel.cpp, source/MapPlanetCard.cpp, source/PlayerInfoPanel.cpp, source/PreferencesPanel.cpp, source/StarField.cpp, source/Test.cpp, source/main.cpp, source/text/WrappedText.cpp
**Typo fixes:** This PR fixes minor style and spacing issues in the code.
It still compiles fine
=> fix: Code style fixes

data/remnant/remnant 2 side missions.txt
**Bugfix:** This PR addresses issue reported on Discord
micheviously -> mischievously on L146
Thanks to Cookiebreaker.fnord for reporting this!
=> fix(content): Remnant: spelling micheviously -> mischievously on L146

data/human/free worlds start.txt
Tomek is described as a tactical genius right after he's let his emotions get the better of him and lost a major battle as a result. These are not the actions of a tactical genius, so the description seems odd, to say the least.
To reduce this jarring contrast, let's have Freya qualify the statement a bit.
=> fix(content): qualify Tomek's alleged tactical genius

data/kahet/kahet missions.txt, data/korath/korath outfits.txt
=> Fix bad apostrophes

source/PrintData.cpp
**Bugfix:**
`ship` -> `skip`
Found by @tibetiroka 
Co-authored-by: tibetiroka <68112292+tibetiroka@users.noreply.github.com>
=> fix(typo): Typos in my recent PR

data/human/free worlds 0 prologue.txt
This PR changes the wording in FW Bounty 1 to avoid clunkily reusing dialogue for multiple choice paths.
=> Wording change in FW Bounty 1

changelog, data/human/free worlds 1 start.txt
**Bugfix:**
Make the Wei battle events update the fleets in the Wei system as intended.
=> fix(content): Fix Wei battle events

XCode/EndlessSky-Info.plist, credits.txt, endless-sky.6, endless-sky.exe.manifest, source/main.cpp
Updates the version numbers to 0.9.15! :)
=> Update version numbers to 0.9.15

credits.txt, endless-sky.6, source/main.cpp
Update the version strings to 0.9.16(-alpha) to denote the start of a new release :)
=> Update versions to in-progress 0.9.16

data/human/free worlds 3 reconciliation.txt
#7319 
@williaji I noticed you forgot something...
This PR changes the other mention of Alondo to "Freya" in the sentence.
=> Fix williaji's mistake in name change pr

tests/README.md, tests/integration/README.md
**Bugfix:** This PR addresses fixes #7152
This fixes the links in the integration tests README and a capitalization error in the tests READMe.
=> Some documentation fixes

source/EsUuid.cpp, source/Files.cpp, tests/unit/src/test_conditionsStore.cpp, tests/unit/src/test_esuuid.cpp, tests/unit/src/test_weightedList.cpp
This PR simply fixes a couple of small issues in the code, found by various compilers and linters.
=> fix(chore): Some small code improvements

data/human/free worlds 3 checkmate.txt, data/human/free worlds 3 reconciliation.txt
Summary
-------
Spell out seventeen when referencing seventeen thousand.
=> Small typo fix 17 thousand

data/human/deep missions.txt
=> fix: remove extra word "credits"

changelog
=> Update the changelog for v0.9.16

XCode/EndlessSky-Info.plist, credits.txt, endless-sky.6, endless-sky.exe.manifest, source/main.cpp
Updates the version number for 0.9.16 :smile:
=> Update the version number for the 0.9.16 release!

data/hai/hai reveal 5 philosophers.txt, data/map.txt
Devil-Run was meant to be hidden.
Somehow making that happen got lost in the rework somewhere.
=> fix(content): Missing hidden attribute on Devil-Run

EndlessSky.cbp, readme-developer.md
This PR:
- Updates the CodeBlocks project
- Windows instructions
to make it work with the new development libraries. If you are using CodeBlocks you will have to update your libraries or else you will get an error while linking.
=> Update instructions and project files for the updated libs

data/korath/korath ships.txt
Consistency of double quotes (") and missing indent in second paragraph for Palavret.
=> Content: Palavret and Echo Descriptions

data/hai/hai reveal 5 philosophers.txt
Offer conditions are borked, this should fix them.
=> fix(content): Quick bugfix to the backup smuggler chain for HR

data/human/jobs.txt
Affects the "Bounty Hunting (Hidden)" missions.
=> Remove instance of job text overflowing

data/human/free worlds 1 start.txt
=> Fix typo in "FW Syndicate Diplomacy 1B"

data/human/ships.txt
I saw that the ending of the container transport’s description referred to it as a bull freighter, and while it is a variation of the bull freighter, given the context I feel it should be referred to as a container transport.
=> Tweak container transport description

data/human/human missions.txt
=> Remove unnecessary quotation mark

.github/pull_request_template.md
**Feature:** This PR extends the template with a section regarding automated testing, initially discussed in #4308
Make automated (regression) tests an explicit entry in the PR template.
N/A. Not visible in-game. And just fill the template with all required details.
Used the new template header here in the PR.
Extended the template with a section explicitly for this.
N/A. But considering automated tests earlier in the PR process might help to get things merged more efficiently.
=> doc(PR template): Make automated tests an explicit item in the PR template.

data/hai/hai reveal 3 early.txt, data/hai/hai reveal 6 end.txt, data/hai/hai reveal 7 epilogue.txt
With the new remove object feature it's possible to edit systems *much* more smoothly than before.
Due to a lack of understanding of exactly how it worked only a couple parts were updated previously so as not to break anything more than was already the case; this addresses the rest of the events.
Credit to @warp-core who created the feature and originally PR'd *most* of this to my branch with no testing. I only had to fix issues with 2 events to make it actually work as intended.
=> fix?(content): HR Streamline events that change systems

data/hai/hai missions.txt, data/hai/hai reveal 1 intro.txt, data/hai/hai reveal 2 start.txt, data/hai/hai reveal 4 middle.txt, data/hai/hai reveal 5 philosophers.txt, data/hai/hai reveal 6 end.txt, data/hai/hai.txt
This addresses a swathe of items identified through discord conversation, the start of my playthrough, or while following up on leftover items ID'd on other HR PR's thus far.
=> fix(content): HR Cumulative Playthrough Edits

data/human/deep missions.txt
Changed some previously impossible conditions to allow for the book to offer when going to Windblain. Also adjusted some of the text (Hroar has already gone; why would you look around for him?).
=> Clean up the end of Skadenga Saga

data/hai/hai reveal 4 middle.txt
I just added a letter that was missing.
=> Fix typo in "Hai Reveal: A New Elder"

utils/check_code_style.py
This fix fixes the previous fix and an other related bug in the coding style checker. @quyykk
=> bug(CI): Fix edge case in style checker

data/hai/hai reveal 4 middle.txt
Grammar change to Hai Reveal 4
May you implies that the militia captain is requesting that the pilot ask permission to hunt the pirates. Will you is a direct request for the pilot to do the bounty hunting mission.
N/A
None
=> hai reveal grammar change

source/PrintData.cpp
Requested by @Hecter94 on Discord.
=> Include afterburner attributes when printing engine stats

.github/workflows/cd.yaml, .github/workflows/ci.yml, .github/workflows/projects_check.yml, .github/workflows/steam.yml
Addresses #5033.
Thanks to @quyykk for telling me how to do this.
=> Cancel running workflows when starting new ones

data/human/fleets.txt
Changed the Republic Wormhole Guard ship names to Republic Capital and Republic Fighters.
=> Republic Wormhole Guard names changed to Republic ship names

tests/unit/src/test_dictionary.cpp
Adds a couple of unit tests and a benchmark for Dictionary. That's it!
=> Add unit tests and benchmarks for Dictionary

.github/workflows/ci.yml, source/main.cpp
This adds the missing GLVND dependency to CI to run the integration tests. The integration tests should succeed now.
=> Add missing runtime dependency to the integration tests

source/Engine.cpp, source/Personality.cpp, source/Personality.h, source/Ship.cpp, source/Ship.h
Just adds two helpers I used in these two PR's:  #7750 #7644
that could be useful for more
=> Internal: Two helper functions

.github/path-filters.yml, .github/workflows/compute-changes.yml
Fixes a couple of oversights in the path filter CI configuration.
=> Fix oversight in path filters for CI

.github/workflows/ci.yml, source/Test.cpp, tests/integration/config/plugins/integration-tests/data/tests/tests_ship_sale.txt, utils/test_parse.sh
This adds a new CI run that parses the integration tests to verify that no errors were inadvertently introduced.
I added a bad commit to see if the CI catches it.
=> test(test robustness): Add CI to verify the integration tests syntax

data/human/human missions.txt
This adds an 'on waypoint' dialog that tells the player that the job is done and time to go home.
Also deletes an empty line that shouldn't be there.
=> feat(content): Adding an "on waypoint" to the Star Research mission

data/human/deep missions.txt
One line change. I changed "pants suit" to the more common form "pantsuit" when Carla Von Hausen approaches you attempting to sell you a house on Asgard.
<hr>
=> Reword Carla Von Hausen description

data/human/human missions.txt
This fixes the Laborer mission having the same source and destination. Thanks @Brelov/Brol'tha#9623 on Discord for reporting!
=> Don't let Laborer have the same destination and source

data/quarg/quarg outfits.txt
Thanks to  @Hurleveur for the initial concept and work on this in #7544 , and for giving me permission to utilize their work in creating this. This is not a direct copy, but is based on their work and incorporates much of it. 
Quarg stuff in general is bland and boring, and frankly uninspiring for what they are. While all their outfits and ships are planned to be updated as a whole once all the rest of the factions have been added to the game, I think it is fitting that we should be at least establishing the general feel and interest of their stuff.
As such, this PR takes the Quarg engines - which were good, but boring, and given them an actual unique effect that is both fitting to their reputed technological level, and quite simply really …
=> feat(content) Quarg: Giving their engines unique flavor & capabilities

.github/workflows/cd.yaml, .github/workflows/cd_release.yaml, .github/workflows/ci.yml, .github/workflows/compute-changes.yml, .github/workflows/projects_check.yml, .github/workflows/steam.yml
This PR updates all our Actions to the latest versions.
Tested by CI.
=> Update all our versions of Actions we use

.github/workflows/cd.yaml, .github/workflows/cd_release.yaml, .github/workflows/ci.yml, .github/workflows/projects_check.yml, .github/workflows/steam.yml
This PR adds better names to every job. See the job names in the CI output window to see how it looks like.
=> Add names to every job

.github/workflows/cd.yaml
=> Don't depend on non-existent job

data/human/human missions.txt
**Bugfix:** 
Add missing quote mark in mission dialogue.
None
=> fix missing quote mark in mission dialogue

data/gegno/gegno intro missions.txt
**Bugfix:** This PR addresses a slight wording issue found while playing the game.
swaps `a massive creature hundreds of times the size of you,` for `a massive creature hundreds of times your size,`
The change is, specifically, swapping the "the size of you" for "your size"
This change makes the sentence flow much better and conforms to the more typical sentence structure used in English.
reread the sentence to make sure it fits.
You'll just need to go find Vor Oti in order to trigger the mission.
[Rebbia Rampart~3024-05-24 Exploring the Gegno Pre-Contact.txt](https://github.com/endless-sky/endless-sky/files/10314626/Rebbia.Rampart.3024-05-24.Exploring.the.Gegno.Pre-Contact.txt)
=> fix(content)-Gegno-First Contact Gegno Vi slight wording tweak

data/remnant/remnant 1 introduction.txt
**Bugfix:** This PR addresses issue #7975
Adjust mission wording to clarify requirements
- Clarify that capturing the target is considered a fail
- Reassure the player that failure is not fatal
=> Update Remnant mission description, GitHub #7975

data/hai/hai reveal 4 middle.txt
Present and past tense are mixed in Sayari's dialog. She is clearly speaking over time but using present tense.
Change within syntactic boundaries. VS Code reports no breaks.
=> HR-Mismatched tense in conversation.

data/remnant/remnant 1 introduction.txt
1. Add missing indefinite article.
2. Broke apart run on sentence for clarity. The two sentences are separate and I had to parse the sentence briefly to work out that the 'however' belonged with the second half and not the first.
Change within syntactic boundaries. VS Code reports no breaks.
=> Remnant: Minor grammar changes to Quarg mission.

data/map.txt
**Content (Fix)**
Saving Erba Yle from real world inflation.
N/A
=> fix(typo): Erba Yle plastic price

data/korath/korath ships.txt
didnt break anything (since its a drone) but still good to fix
also add crew equivalent of 1 so they care about the drone.
=> Content fix: add automaton and crew equivalent to the Korath Exile drone 

data/sheragi/archaeology missions.txt
More and more errors kept cropping up as the mission progressed, so this is a mix of several different kinds of grammar fixes.
=> Several grammar fixes to Emerald Sword dialogues

data/human/ships.txt
I changed a few words in the new pirate Valkyrie description to help it flow a little better.
=> Valkyrie Description Change

data/human/human missions.txt
Changes a line from `"I don't like the idea of carrying an unknown cargo. Count me out."` to `"I don't like the idea of carrying unknown cargo. Count me out."`
=> Fix typo in Deal Change 1

data/hai/hai missions.txt
Existing wording is clumsy, should either be 'an escort' or 'escorting'  I've opted for 'an escort.
Single word change within syntactic boundaries. VS Core reports no breaks.
=> Hai: Expanding Business 3: Grammar Edit

.github/workflows/cd.yaml, .github/workflows/cd_release.yaml, .github/workflows/ci.yml, CMakePresets.json, utils/build_appimage.sh
This replaces scons with CMake when building on Linux in the CI environment.
**Note:** This deliberately doesn't touch the Steam workflow 
CI will test everything.
=> build(cmake/linux): Use CMake for building on Linux in CI

.github/workflows/cd.yaml
No zip is created, only an appimage
we will have a look on the tests
=> Hotfix: fix name in upload

.github/workflows/cd.yaml, utils/build_appimage.sh
Fixes the CD AppImage build by actually building the AppImage.
=> Actually build an AppImage

data/deprecated ships.txt, data/hai/hai reveal 1 intro.txt, data/hai/hai reveal 7 epilogue.txt, data/hai/hai ships.txt, data/hai/unfettered 0 prologue.txt, data/hai/unfettered jobs.txt, data/human/deep missions.txt, data/human/free worlds 2 middle.txt, data/human/human missions.txt, data/human/ships.txt, data/human/variants.txt, data/iije/iije.txt, data/kahet/kahet missions.txt, data/korath/korath variants.txt, data/remnant/remnant 1 introduction.txt, data/remnant/remnant outfits.txt, data/wanderer/wanderers middle.txt, data/wanderer/wanderers.txt
This PR was brought to you by #8189 
Mainly whitespace and indentation fixes.
=> fix(typo): Fix typos in data files

data/map planets.txt
**Content**
Ember Waste wormholes are now red-purple
If you don't have a save file where you can visit the Ember Waste, I am sorry for you.
=> [Enhancement] Give Unstable Wormholes Red Links

data/hai/hai reveal 6 end.txt, data/wanderer/wanderers start.txt
=> Remove wandering nightmares

.github/workflows/compute-changes.yml, .github/workflows/projects_check.yml
- Adds a name to the compute changes workflow
- Fixes the if conditional on two jobs; currently they always run
CI will test this. The two jobs should not run (unlike in #8301)
=> Some small fixes to the CI

data/gegno/gegno outfits.txt
Co-Authored-By: Corraban2 <66099507+Corraban2@users.noreply.github.com>
(idk that's what github put here)
Reported by Corraban on discord.
=> fix(typo): Fix 'magnetic' in the description of Plasma Grenades

data/quarg/quarg news.txt
=> fix(typo): Fix typo in quarg news

data/map planets.txt
Judging by the name, it is a Gegno-related Quarg settlement.
=> Fix missing 'gegno quarg' attribute for 'Giaru Gegno'

.github/workflows/cd.yaml, .github/workflows/cd_release.yaml, .github/workflows/ci.yml
=> [CI] Fix MacOS pkg-config error

credits.txt, endless-sky.6, io.github.endless_sky.endless_sky.appdata.xml, source/main.cpp
=> Update man page and appdata.xml file to 0.10.0

data/hai/hai reveal 1 intro.txt, data/wanderer/wanderers start.txt
This reverts commit 5db59161bf5bb9a01e6d0dcf07a0f26aaf02ab62.
=> Revert "Lock Hai Reveal from offering for v0.10.0 (#8396)"

data/hai/hai reveal 1 intro.txt, data/hai/hai reveal 6 end.txt
I refuse to do an individual PR for each bug.
- Fix improper triggering of Hai Leaks Response 5B on existing saves
- Add missing attributes to Al Hurr system
=> fix(bug): HR Bugfixes 4

data/hai/hai reveal 4 middle.txt
**Content (Mission)**
Rearranges wording in "ZZ Hai Reveal [A04] Report to Teeneep" to make it more clear both that you are accepting a mission to speak to Teeneep and that declining is not an optional branch to keep waiting for Alondo.
=> [Content]Hai wording tweak

CMakeLists.txt
There were some MacOS CI error on a couple of PRs lately. This PR fixes them.
I tested it on my fork. It works!
=> Fix MacOS compilation error in CI

data/human/deep missions.txt
This PR updates conversations and logs in missions related to Project Hawking and Beelzebub.
=> fix(typos): Updates to Deep mission chains

data/human/jobs.txt
description `These <bunks> school students have been stranded on a field trip due to the unexpected bankruptcy of their booked transport. The school and parents have put up a reward of <payment> for them "and their Luggage" to be returned home to <destination>.`
"and their Luggage" was added
(You can open a PR to add or improve a section, if you find them lacking!)
{{summarize your content! Include links to related issues, in-game screenshots, etc.}}
{{attach a save file that allows people to easily test your added mission content or see your new in-game art}} …
=> Update jobs.txt at line 2304 to include "And Their Luggage"

data/human/deep missions.txt
Just a few minor changes to improve the grammar and fix some awkward wording in Stone of our Fathers 5. 
If you look at the diff it's pretty self explanatory.
=> Improved grammar

data/coalition/coalition missions.txt, data/hai/unfettered 0 prologue.txt
**Bugfix:** This PR addresses issue #8602
In addition to fixing the issue highlighted in #8602, this PR also rearranges various branches, sometimes using `to display` syntax, to remove numerous lines of text that are replicated for use in different branches.
=> Less repetition in Coalition university lecture

data/hai/hai reveal 3 early.txt, data/human/human missions.txt, data/sheragi/archaeology missions.txt, data/vyrmeid/vyrmeid.txt
**Bugfix:**
Thanks to @samrocketman for bringing this up on Discord.
Removed trailing spaces from some lines of text.
=> Remove some trailing spaces

data/human/human missions.txt
=> fix(content): Fix text overflow on Spaceport Defenses

data/categories.txt
=> fix(content): Remove temporary testing mission

data/governments.txt, data/human/human missions.txt
A new mission, in which an NPC offers protection to a player on a lucrative but dangerous route.
Reopening of #8206 to fix the problems I caused trying to fix the merge conflicts.
[Catalina Garcia~Mission Test.txt](https://github.com/endless-sky/endless-sky/files/10501613/Catalina.Garcia.Mission.Test.txt)
(Already on Sunracer, take off and land again to get the mission)
=> feat(content): Escort Betrayal mission

changelog
=> v0.10.1 changelog update

data/human/names.txt
So that a phrase, like some in #8739, which doesn't care about the gender of the name being used can just ask for "human names".
=> Add a combined phrase for male or female human first names

data/kahet/kahet missions.txt
{{Phenomenon/phenomena type fix.}}
=> Typo fix phenomenon/phenomena

data/gegno/gegno intro missions.txt
As was brought up by MidnightPlugins on Discord, the way the Quarg expresses itself during the conversation with the player is a bit odd as it mentions expressions, and currently, the only example of Quarg expression is in Ringworld Debris where their skin shifts colors. I've modified the conversation to remove the expressions, but added a color-shift at what is the more important part of the discussion pertaining to the Quarg. 
I've also made a few other slight adjustments, including examples where the Quarg wasn't referred to as "it".
Will make one if necessary.
=> feat(content): Gegno Intro Tweaks

data/human/free worlds 1 start.txt
**Content (Issue Response)**
Changes the dialog when talking to Huygens to make it seem barely possible to get the time limit. (Only doable with a JD)
Takes some suggestion from #7883.
N/A, only text changes.
=> Potential change for #7883

source/PlayerInfo.cpp
**Feature:** Adds proper pluralization to two crew-related messages that previously didn't have them.
N/A
N/A
N/A
N/A
=> feat(enhancement): Add proper pluralization to two messages

data/human/human missions.txt
Text / dialogue correction.
Based on the story context, it's the Core / Church who asks the question, not the player.
=> Update human missions.txt

data/hai/hai jobs.txt, data/hai/unfettered 0 prologue.txt
Does what it says, I am just not sure about changing the mission about the child being brought back from Unfettered space's rep?
Otherwise this doesn't affect much, it just helps people getting their reputation back up with the sympathizers a bit faster
=> Sympathizers care more about the player helping Unfettered Hai

data/human/marauders.txt
**Bugfix:** This PR addresses issue #8988
```diff
- [...] featuring extra gun ports, hull plating, and shield emitters.
+ [...] featuring extra hull plating, shield emitters, weapon space, and even a turret mount.
```
Since the ship doesn't actually have any more gun ports than any other Manta.
=> Weapons Marauder Manta description tweak

data/remnant/remnant outfits.txt, tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_attribute_autoconditions.txt, tests/integration/config/plugins/integration-tests/data/tests/tests_wormhole_navigation.txt
**Bugfix:**
The game does not do anything with "scrambling protection" or "scrambling resistance" attributes.
0
=> Replace "scrambling protection/resistance" with "scramble protection/resistance" in various places

data/human/news.txt
Adds human news items that make use of the the `frozen` attribute added in #8880 
- arctic explorer
- mechanic [frozen]
- tourist [frozen]
=> feat(content): Frozen climate news

data/map planets.txt
This PR adds the `frozen` attribute to Nifel. It also moves `frozen` attributes on other worlds to be in the correct alphabetical order, instead of at the end.
=> feat(content): Add `frozen` attribute to Nifel & enforce alphabetisation

data/remnant/remnant 2 cognizance.txt
**Bugfix:** This PR addresses issue #9224
Changes the description of `Remnant: Cognizance 7` to explain you have to go to Nasqueron.
N/A
N/A, only dialog changes.
=> fix(content): Make it clear where you are headed in Cognizance 7

.github/workflows/cd.yaml, .github/workflows/cd_release.yaml, .github/workflows/ci.yml, vcpkg-configuration.json, vcpkg.json
Updates all the dependencies to the latest versions. That's it!
=> Update all dependencies

data/coalition/coalition jobs.txt
Just applying the changes suggested by tibetiroka here: https://github.com/endless-sky/endless-sky/pull/6646#discussion_r1318853149
Replaces written out payments for \<payment\>, and splits a sentence into two.
=> Update Heliarchs Buy JDs job

source/Date.cpp
**Bugfix:**
Fixes a warning from the code style checker.
The inclusion of the header file associated with this cpp file should be separated from other inclusions by an empty line.
Check the details for the code style check workflow.
=> Correct style in Date.cpp includes

source/ConditionSet.h, source/ConditionsStore.h, source/DataNode.h, source/Mortgage.h, source/text/Format.h
Adds some missing #includes, caught by gcc 13 on Windows.
=> Add missing #includes for gcc 13

docs/readme-cmake.md
- Adds a section about VS Code extensions
- Clarify installation instructions for MinGW people using another distribution than WinLibs
=> Some small build instruction tweaks

source/GameEvent.cpp, source/GameEvent.h, source/PlayerInfo.cpp
Optimizes the case where multiple events are triggered on the same day and they all update the map. Instead of applying the data changes individually, which is really expensive, combine all the data changes together and then apply them together at the end.
Tested a save file with like 40 events triggered in a single day. The events are still correctly applied.
[Ford.Prefect.txt](https://github.com/endless-sky/endless-sky/files/12707367/Ford.Prefect.txt)
Big speedup. With this PR the attached save takes half a second to apply the events, on continuous 6 seconds.
=> Optimize applying lots of events with map changes

data/human/human missions.txt
Fixes a capitalization error pointed out by @Amazinite.
=> Fix to 'Refugees to Humanika' mission

data/coalition/heliarch intro.txt
**Content (Missions Dialog)**
As per @W1zrad 's request here https://github.com/endless-sky/endless-sky/pull/6647#pullrequestreview-1640933804 , this adds a dialog to the mission `Heliarch Drills 3`, that displays if you destroy the dummy Punisher npc.
=> Heliarch Drills: Add Dialog in case you destroy the Punisher

data/coalition/heliarch intro.txt
**Content (Missions Goto)**
Just adds a missing goto.
Spotted by @warp-core , thanks!
=> Heliarch Containment 3: Add missing goto

data/human/human missions.txt
=> Give the Hallucination a noun

data/coalition/lunarium intro.txt
Changing the `on offer` `require` conditions to `to offer` `has` conditions for outfits in the Lunarium intro, similar to https://github.com/endless-sky/endless-sky/pull/9358.
=> feat(content) Change `require` to `on offer` conditions in Lunarium Intro

data/coalition/heliarch intro.txt, data/coalition/lunarium intro.txt
**Bugfix:**
What the title says. There was a missing article.
0
=> Typos: "on path to conflict" -> "on a path to conflict"

data/coalition/coalition jobs.txt, data/coalition/lunarium intro.txt, data/quarg/quarg missions.txt
Some conditions in the coalition campaign and related jobs were typo-ed.
=> Fix coalition campaign conditions

CMakeLists.txt, credits.txt, endless-sky.6, resources/EndlessSky-Info.plist, source/main.cpp
**Feature:**
Updates version numbers from 0.10.3 to 0.10.4-alpha where that is supported.
=> Update version numbers for 0.10.4 alpha

data/human/human missions.txt
The missions were missing payment and some cargo information.
=> feat(content): Clean up descriptions of new spaceport missions

source/ShopPanel.cpp
**Bugfix:**
removes the blurryness that could happen when dragging in the outfitter panel
smoothscroll had 1. added to it then -1 etc, making it blurry
compared the game with and without these changes - the blurryness is gone for me
just go in an outfitter and drag
=> bugfix(code, UI): fix blurriness with smooth scroll

source/AI.cpp, source/CargoHold.cpp, source/CategoryList.cpp, source/CategoryList.h, source/ConditionsStore.h, source/Conversation.cpp, source/Conversation.h, source/ConversationPanel.h, source/Engine.cpp, source/Fleet.cpp, source/GameEvent.cpp, source/ImageBuffer.cpp, source/MapDetailPanel.cpp, source/MapPlanetCard.h, source/MapShipyardPanel.cpp, source/MissionAction.cpp, source/OutfitterPanel.cpp, source/Phrase.h, source/PlayerInfo.cpp, source/Plugins.h, source/Preferences.cpp, source/Ship.cpp, source/Ship.h, source/ShipInfoDisplay.cpp, source/ShipyardPanel.cpp, source/Test.cpp, source/TextReplacements.cpp, source/TextReplacements.h, source/Weather.cpp, source/ship/ShipAICache.cpp
**Typo:** This PR fixes a bunch of typos in code comments.
An assortment of typos I could find using spell checkers.
N/A
N/A
=> fix(typo): Fix typos in code comments

data/coalition/coalition jobs.txt, data/coalition/coalition missions.txt
**Bugfix:** This PR addresses an issue reported on discord by Wyrdean
The payment should work now.
Yes.
See below.
=> fix(content): Fix payment of Heliarch JD jobs not displaying properly

changelog, credits.txt, endless-sky.6, io.github.endless_sky.endless_sky.appdata.xml, source/main.cpp
**Docs and stuff:**
- Update version numbers from "0.10.4-alpha" to "0.10.4";
- Update credits (one new contributor), and add some people to the Developers and Editors and Proofreaders lists;
- Update changelog.
- Update the AppStream file.
=> Update version numbers, credits, and changelog for 0.10.4

changelog
~~Quick, guys, attribute @warp-core properly before the release goes out~~
=> fix(typo): Fix typo in changelog

.github/workflows/cd_release.yaml, changelog
Removes 32-bit support. The game can still be built for 32-bit if necessary.
=> Remove 32-bit support

CMakeLists.txt, credits.txt, endless-sky.6, resources/EndlessSky-Info.plist, source/main.cpp
=> Update version numbers for 0.10.5-alpha

tests/integration/config/plugins/integration-tests/data/tests/tests_capture_override.txt, tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
the issue seemed to have been it wasnt pressing return at the right moment, so instead of pressing it every frame I made it check for the conditions we care about
seemed to work for these two but others may need fixing? tell me.
=> testing: fix some integration tests and removed an unused one

data/coalition/lunarium intro.txt
**Bug fix**
Minor correction in the offer conditions for Lunarium: Smuggling: Charity 2
=> Lunarium: Smuggling: Charity 2 - correct offer condition

data/coalition/coalition missions.txt, data/gegno/gegno intro missions.txt, data/human/human missions.txt
=> fix(typo): Keep periods inside of parentheses in choices

data/hai/hai missions.txt
fixed that typo by adding a period
This PR addresses issue #9524 
o7 and thanks
=> fix(typo): Hiding in Plain Sight missing period

data/human/culture conversations.txt, data/human/deep missions.txt, data/remnant/remnant 1 introduction.txt
Some choices were missing periods, so I added them. ~~You're welcome.~~
=> fix(typo): Add missing periods/full stops to choices

data/human/free worlds 4 epilogue.txt
In the Free Worlds epilogue there was a reference to "the rest of the galaxy" having not been implemented. Given that there now is quite a lot of content beyond human space this is no longer accurate.
=> Update outdated dialogue

tests/CMakeLists.txt, tests/integration/config/plugins/integration-tests/data/tests/tests_landing.txt
Adds an integration test for landing on different planets in a single system.
Tests succeeds locally, and CI will test it as well.
=> Add an integration test for landing in systems with multiple planets

source/SpriteQueue.cpp
Fixes a rare deadlock that happens when loading the game. Not much to add to that.
Started the game a hundred times. Without this PR, the deadlock always happens in one of those runs. With this PR, it never deadlocks.
If you want to reproduce:
```bash
$ ctest --preset linux-integration -R "Flagship Attribute Autoconditions" --configuration Release --repeat until-fail:100
```
=> Fix deadlock while loading the game

source/AI.cpp, source/Engine.cpp, source/UniverseObjects.cpp
**Feature**
This PR resolves two TODO items in the code, and fixes a typo in a third todo.
Self-explanatory.
Zoom still seems to work.
=> enhancement: Resolve some C++17 todo items

source/GameWindow.cpp
Fixes #9608 
None, but this should work.
=> Fix compilation error on SDL before v2.0.22

source/ShopPanel.cpp, source/ShopPanel.h
Subset of #9568.
See above for video.
=> fix(ui): Remember Selected Item in Shop Panel

data/human/human missions.txt
**Bug fix**
Typo fix. `deminish` -> `diminish`
N/A
=> FIX: Typo in Puny mission

data/human/intro missions.txt
I just thought I'd make it clearer the AM (or tractor beam) is no issue for AI targeting (for some reason I always assumed it was)
The Sparrow intro also makes it very easy to grab the Fury, and it seems a bit weird he calls it a Sparrow, so I changed it to interceptor.
=> small tweaks to James' intro

data/coalition/heliarch intro.txt, data/coalition/lunarium intro.txt
Some grammar fixes, both for regular English, and for Coalition grammar consistency.
=> More grammar fixes - Heliarch and Lunarium intros

.codespell.exclude, data/map planets.txt
**Typos**
Went into Gegno space for the first time and noticed some typos. Also looked through the rest of the planets (well, all that mention Gegno somewhere) to see what I could improve.
=> fix(typos): Gegno planet description improvements

data/hai/hai missions.txt
It was reported on Discord that the new Hai Film Crew missions offer outside of Hai space. 
So I fixed it.
=> fix(mission): Fix location filters for Hai Film Crew missions

data/map planets.txt
**Bug fix**
This PR addresses the bug described in issue #9565 
Adds missing location attributes to Clink and Mutiny.
=> Add proper location attributes to Clink and Mutiny

credits.txt, endless-sky.6, source/main.cpp
~~I don't know who merged it before.~~
=> chore: Fix Version Numbers

data/human/hails.txt
This PR adds some new hails as mentioned in the campfire chat.
Adds some pirate hails requesting you to drop your cargo, and some merchant hails recommending this strategy.
None.
N/A
=> feat(content): Some new human hails about dumping cargo for pirates

CMakeLists.txt, credits.txt, endless-sky.6, resources/EndlessSky-Info.plist, source/main.cpp
I almost left some of them as "0.10.6-alpha" like last time but I think I did it right today.
=> 0.10.7 alpha versions

source/LoadPanel.cpp
**Feature**
**Bug fix?**
Removed some unnecessarily complex memory management in LoadPanel.cpp that seemed likely to go wrong
The code still work
Faster if anything
=> Feat/Style/Dunno(Code): Remove unnecessary memory managment from LoadPanel.cpp

data/hai/hai news.txt
**Content (News)**
This PR was taken from https://github.com/endless-sky/endless-sky/pull/6416 as suggested by @roadrunner56 
Adds a few new news, one with ppl having lost it all and going to uhai space, another being more interested in whats over there (especially art-wise), and the last one about captains moving hai to unfettered space (this one happening in unfettered space).
=> Feat(content): add unfettered related hai news

.github/path-filters.yml, .github/workflows/projects_check.yml
This PR adds a new check for the copyright file that will actually detect issues.
I also removed an extra empty line from before the check.
#9853
You can see the output of the check [here](https://github.com/endless-sky/endless-sky/actions/runs/8124308308/job/22205636631).
#9853 and testing on various other control files, unit tests etc. The action was also tested, but it's also tested in this PR.
=> feat(CI): Expand copyright checks

data/korath/korath hails.txt
**Bug fix**
Removes a duplicated korath phrase, reported on [discord](https://discord.com/channels/251118043411775489/536900466655887360/1224631407674921051)
Removes one instance of the duplicated phrase.
=> fix(content): Remove duplicate korath phrase

source/Engine.cpp
**Bug fix**
Just what the title says.
yes™
=> fix: Ships with `disables` personality shouldn't ask for destroying their enemies

data/wanderer/wanderers middle.txt
Replaces the line "but the factories are constantly expanding outward" in Sestor Ikfar's planet's description with something more fitting after the factories are shut down.
=> Content: Update the descriptions of two Sestor worlds after the factories are shut down.

data/human/deep missions.txt
**Bug fix**
This PR addresses the bug/feature described in issue #5144
Used the mark/unmark system in #9827 to fix #5144.
None, TBD?
=> fix(bug): Indicate Betelgeuse as a system of importance in Deep Scientist Rescue 0 

copyright, data/wanderer/wanderer missions.txt, docs/readme-cmake.md, source/Ship.cpp
**Typo fix**
This PR fixes some minor typos in the game.
Pretty self-explanatory. Fixed some missing spaces and characters.
=> typo: Various typo fixes

CMakeLists.txt, credits.txt, endless-sky.6, resources/EndlessSky-Info.plist, source/main.cpp
Update version numbers for v0.10.8 alpha.
=> V0.10.8 alpha version numbers

data/human/free worlds 3 checkmate.txt, data/human/free worlds 3 reconciliation.txt, data/human/free worlds 4 epilogue.txt, data/human/free worlds side plots.txt, data/human/free worlds war jobs.txt
**Content (FW Missions)**
This PR addresses the bug/feature described in issue 
None
I changed events so they would happen immediately in some cases. 
Capitalized Dirt Belt. 
Alphabetically ordered npc tags in some cases. 
Made Barmy Edwards name be correct.
Various other fixes. 
No
N/A
No
None
N/A
N/A
N/A
=> fix(typo): More FW fixes

changelog, credits.txt, endless-sky.6, io.github.endless_sky.endless_sky.appdata.xml, source/main.cpp
~Just go check the description of #9725, #9803, and #10078.~
- Update the changelog.
- Update the credits.
- Update the version numbers.
- Add the template for the release entry in the appdata.xml file (to be filled out soon:tm:).
=> 0.10.8 docs update

CMakeLists.txt, credits.txt, endless-sky.6, resources/EndlessSky-Info.plist, source/main.cpp
Updates version numbers to 0.10.9-alpha, or 0.10.9 where the "-alpha" suffix isn't allowed.
=> 0.10.9 alpha versions

source/TextArea.cpp
#10300 forgot to remove the include for cassert
builds
=> Fix? remove unnecessary include

data/human/human missions.txt
This stands out to me in the pookie mission, she's a female dog but described like a male.  Feel free to suggest better wording, but this sounds right to me.
=> Lady dogs squat

tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_attribute_autoconditions.txt
**Bug fix**
A recent balance change broke an integration test that expected the specific attribute values that were changed.
Changes the test's parameters to match the changed data.
It runs now.
=> fix(ci): Fix broken integration test

source/FormationPositioner.cpp
~~I am not going to fill out this all~~
Fixes a check from comparing an int with a double, just good style no impact
=> Feat(smh), correct if

data/incipias/incipias outfits.txt, data/incipias/incipias.txt
also changed category of hicemus license to be a license
=> Fix: minor inicpias adjustments

data/incipias/incipias first contact.txt
**Typo Fix**
Typo fix.
None.
N/A
None.
No.
N/A
N/A
=> Incipian typo fix

source/FillShader.h, source/Government.h, source/OutfitInfoDisplay.h, source/RaidFleet.h, source/SpaceportPanel.h, source/test/Test.h
**Code Style**
Fixes alphabetization errors in forward class declarations. The style guide doesn't require it, but it's nice to have.
=> code(style): Alphabetize forward class declarations

data/gegno/gegno events.txt
**Typo fix**
This PR addresses the bug/feature described in issue none
I forgot to submit my review to #10347 with something like this.
No. 
N/A
One word change, so no.
None.
N/A
N/A
N/A
=> Slight rewording of Ghneoe

data/hai/hai.txt
Suggesting some friendly Hai hails.
=> feat(content): Adding friendly Hai hails

data/wanderer/wanderers.txt
**Content**
The Wanderers have indicated that they are quite happy to give food to really anyone, even if they don't ask in the most polite manner.
This PR adds the "appeasing" personality to the "Wanderer Freight" fleet so we can see that in action.
I didn't test it.
I might upload one later.
=> Give the "Wanderer Freight" fleet the "appeasing" personality

data/remnant/remnant 1 introduction.txt
**Typo Fix**
peaking -> peeking
None
None
None
=> Remnant Typo Fix

data/successors/successor 1 prologue.txt, data/successors/successor side missions.txt
**Bug Fix**
It happened with the Incipias, it's happening with the Successors...
Fixes two small typos.
None
None
None
My save's been overwritten by now.
N/A
N/A
N/A
=> Small Successors fixes

CMakeLists.txt, credits.txt, endless-sky.6, resources/EndlessSky-Info.plist, source/main.cpp
Updates various version numbers for 0.10.10 or 0.10.10-alpha now that 0.10.9 is done.
=> 0.10.10 alpha version numbers

data/map planets.txt
**Typo Fix**
Wording tense fix.
None.
Not really.
Any save that can land on a planet.
=> fix(typo): Cassandra wording fix

data/korath/korath ships.txt
**Typo Fix**
Fixes a typo in the description of the Tubfalet: "terrorise" to "terrorize".
How?
A save file with this ship wouldn't help review.
=> fix(typo): Tubfalet description fix

data/remnant/remnant 2 cognizance.txt
**Typo fix**
After going to all that effort to use the right pronouns for Gavriil, it's pretty amusing to turn around and call a technician with some cargo an 'it'. xD
=> Correct pronoun in Remnant: Cognizance 10

docs/readme-cmake.md, docs/readme-developer.md
=> docs: Add instructions for building without tests

data/remnant/remnant 2 side missions.txt
**Bug fix**
Just like with Plume, Taely is a living, breathing person who needs a bunk to sleep.
=> Hoverboarding with the ghost of Taely

data/remnant/remnant events.txt
**Typo fix**
Typo in flavour text.
=> Correct Fertriery spelling

data/remnant/remnant 2 side missions.txt
**Typo fix**
One is a spelling fix. Another is a wrong person mentioned. 3rd is a tiny grammar improvement.
=> Fixed a couple typos in Shattered Lights

data/drak/drak ships.txt
**Bug Fix**
Actually use the attributes from #10648.
=> fix(content): Use the new silent jumps attribute

CMakeLists.txt, credits.txt, endless-sky.6, resources/EndlessSky-Info.plist, source/main.cpp
Update version numbers for 0.10.11-alpha.
=> 0.10.11 alpha version numbers

source/Armament.cpp, source/Armament.h
Corrected a comment in Armament.
=> Correct a comment

data/human/hails.txt
**Bug Fix**
`disabled hostile` to `hostile disabled`.
=> fix(bug): Un-halve the number of hostile disabled hails

data/human/human missions.txt
A grammatical correction for the Quicksilver package mission, plus a single punctuation correction down the mission chain and another typo fix down the file.
=> Grammar fix for the Quicksilver package mixup mission.

source/OutfitterPanel.cpp
**Bug fix/grammar fix**
Fix grammar, adjust code line length, fix math, use "buy" or "load" as appropriate.
(As I previously touched this area of code, I saw this change, and tweaking it for correctness)
The code is simple enough to not need testing.
=> A few tweaks to #10581

data/successors/successor side missions.txt
**Typo fix**
I believe this is a typo. If it is intentional, feel free to close :)
=> Typo (?) fix

data/human/human missions.txt
**Bug fix**
These two lines have an extra indent each.
Removed one tab from each.
=> content(fix): Remove extra tabs from two human missions

data/human/ships.txt
The Aerie has four bays now, not two. Aerie gang.
=> fix(content): Update Aerie description

data/map planets.txt
**Content (Artwork / Missions / Jobs) / Typo Fix**
The sentence explaining the Key Stones took me a few seconds to parse through while playing the game for the first time.
I think this rewrite is clearer.
N/A
As it's a one-line copyedit, I have not tested these changes.
N/A
N/A
N/A
N/A
=> Streamline Viminal's description

data/sheragi/archaeology missions.txt
**Fix?**
This PR addresses the bug(?) described on [Discord](https://discord.com/channels/251118043411775489/536900466655887360/1330507532799574137)
Clarify which jump drive in The Emerald Sword 2: "a jump drive" -> "another jump drive"
=> fix(explanation): clarify which jump drive in The Emerald Sword 2

data/bunrodea/bunrodea weapons.txt, data/effects.txt, data/hazards.txt, data/human/engines.txt, data/human/weapons.txt, data/korath/korath outfits.txt, data/korath/korath weapons.txt, data/pug/pug outfits.txt, data/quarg/quarg outfits.txt, data/remnant/remnant outfits.txt, data/successors/successor outfits.txt, data/wanderer/wanderer outfits.txt
**Feature**
This PR categorizes existing sound effects for more intuitive volume control.
Most effects are explosions, so they don't need a custom category. Sounds defined directly on an outfit, such as a flare sound, are also played with the appropriate category. There are some cases where the category cannot be determined correctly, so this PR puts them in the correct category.
I tested some of these to make sure the volume control works.
=> feat(sound): Categorize existing sound effects

data/map planets.txt
**Typo fix**
Wording fixes made to the descriptions of Revelation, Deka Dathnak, and Independance
=> fix(typo): Another batch of wording fixes

CMakeLists.txt, credits.txt, endless-sky.6, resources/EndlessSky-Info.plist, source/main.cpp
Like last time, but with a 12 where there was 11.
=> 0.10.12 alpha version numbers

data/human/human missions.txt
**Bug fix**
Fixes #11003
Added a missing `passengers` line to the `Human to Hai Space`.
=> Benjamin should take up a bunk

.codespell.exclude
Removed a duplicate line from the `.codespell.exclude` file.
Should be exactly the same.
=> Remove a duplicate line from .codespell.exclude

CMakeLists.txt, credits.txt, endless-sky.6, resources/EndlessSky-Info.plist, source/main.cpp
Update version numbers for 0.10.13-alpha.
=> 0.10.13-alpha versions

data/human/human missions.txt
**Typo fix**
Timothy Radrickson 1: Remove extra quote
=> Timothy Radrickson 1: Remove extra quote

data/remnant/remnant 2 cognizance.txt
**Typo fix**
Three Remnant typo fixes.
=> Remnant typo fixes

data/governments.txt
**Content**
Use the `color "governments: X"` feature for Quarg governments.
=> feat(content): Create and use `colour "governments: Quarg"`

data/gegno/gegno events.txt, data/human/human missions.txt, data/wanderer/wanderer missions.txt, tests/integration/config/plugins/integration-tests/data/tests/tests_to_accept.txt, utils/contentStyle.json
Related: #11214
Adds a style check to see if any common doubled-up words are present.
See the failing checks on the second commit here
=> feat(ci): Add a check for commonly doubled-up words

source/Ship.cpp
**Bug fix**
Fixes #11196, for real this time.
=> fix(bug): Clear selected ships when landing

data/map planets.txt
Re-PR of #9948 with Quantumshark's comment addressed.
=> Fix to Baianus description

data/map planets.txt
**Content: Location Description**
There was a "but, although" statement on Ketar Fort and I wanted to change it. I ended up adding a little bit. I'm still learning the github system, so hopefully this helps. 😃
N/A
N/A
=> Update Katar Fort description in map planets.txt

docs/CONTRIBUTING.md
This PR addresses the bug/feature described on Discord by Saugia.
After issues with people submitting AI-generated content to Endless Sky, Saugia mentioned that it might be worthwhile to clarify exactly why we don't use AI in ES development in the contributing guidelines. To do this I created a new section of the Contributing file and used parts of my comment that I posted here (https://github.com/endless-sky/endless-sky/pull/11313#issuecomment-2807505352) along with parts of @reticent-rem's comments on Discord (thanks by the way!). If anyone else wants to add anything to this PR, I'm open to suggestions. 
N/A
N/A
N/A
N/A
N/A
N/A
N/A
=> feat(docs): Add more info on why AI is not allowed in ES

source/MapPanel.h
Nested classes go before functions and variables.
No.
=> style(code): Fix the order of MapPanel members

CMakeLists.txt, source/DistanceMap.cpp, source/GameAction.cpp, source/MissionAction.cpp, source/MissionAction.h, source/PlayerInfo.cpp, source/Projectile.cpp, source/TaskQueue.h, tests/integration/config/plugins/integration-tests/data/tests/tests_conditional_choice.txt, tests/integration/config/plugins/integration-tests/data/tests/tests_hyperjumps_to_autocondition.txt, tests/unit/src/test_categoryList.cpp, tests/unit/src/test_conditionsStore.cpp
**Typo fix**
~~This PR addresses the bug/feature described in issue #{{insert number}}~~
Found via codespell
n/a
n/a/
n/a
n/a
(If any artwork was added or changed by this PR, the following must be provided.)
n/a
n/a
=> fix(typo) : Fixes several typos

tests/unit/src/test_account.cpp
This PR improves the unit test for the `Account::AddMortgage` method.
Ran the full test suite. All tests passed successfully.  
The changes are limited to test code and do not affect runtime behavior.
=> Added test for account.AddMortgage

data/human/human missions.txt
Several tweaks and one bugfix for the existing Syndicate Business Missions came up during review of [Part 3](https://github.com/endless-sky/endless-sky/pull/11298), that I think would be valuable to try to get in separately and earlier than that PR:
- **Combat Rating Tweak**: Removed `"combat rating" > 50` as the first mission can be completed in a Star Barge or other starting ship, and makes it more likely the player will leave the Vanguard alive.
- **Source Attribute Tweak**: Removed `attributes "core"` requirement from mission sources since that is largely covered by the `Syndicate` government.
- **Deja Vu Text Tweak**: Improved Vanguard "deja vu" text line, as suggested by mOcatve.
- **Comment Removal Tweak**: Removed comments above Part 2 missions, as the …
=> feat(content): Syndicate Business minor tweaks and bugfix

data/avgi/avgi weapons.txt, data/bunrodea/bunrodea weapons.txt, data/coalition/coalition weapons.txt, data/hai/hai outfits.txt, data/human/weapons.txt, data/incipias/incipias outfits.txt, data/kahet/kahet outfits.txt, data/korath/korath weapons.txt, data/remnant/remnant outfits.txt, data/rulei/rulei outfits.txt, data/successors/successor weapons.txt, data/wanderer/wanderer outfits.txt
**Feature**
This PR addresses the bug/feature described in issue #11010.
This PR adds conditional outfitters for restocking various secondary weapons. These conditional outfitters appear only on planets that already have an outfitter, and only provide ammo for weapons or ammo storage outfits you have present in your fleet.
Seeing as how #11402 isn't merged yet, these outfitters can't change the price of the ammo. If we feel like price premiums are really necessary for the balance of being able to restock anywhere, then we can add that in later.
In order to indicate that a weapon's ammo can be restocked universally, I've added that information to the description of the weapon.
This is the table of all secondary weapons in the game, whether they restock, and notes on some of them explaining …
=> Create conditional outfitters for restocking most secondary weapons

data/human/ships.txt
**Typo fix**
"Fer a ship now belongin' to pirates, ye be missin' the most valued letter!"
Fixes the spelling of "Berserker" in the Jackal's description.
=> fix(typo): Misspelling of "Berserker" in Jackal description

data/avgi/avgi 0 first contact.txt
Fixes 1 instance of misspelled "Abberant".
=> fix(typo): Abberant to Aberrant

data/governments.txt
**¯\\\_(ツ)\_/¯**
This PR addresses #9110.
Alphabetizes the government data. That's about it.
=> chore(data): Alphabetize government data

data/human/free worlds 2 middle.txt
This PR addresses the bug described in issue #10062.
Closes #10062.
This PR updates the on offer conversation of "FW Southern Recon 1B", the mission in which you are tasked with plundering an electron beam or turret from the Navy, to recognize whether you already have an electron beam or turret on you. If you do, you get the option to hand it over immediately, or you can choose to not mention to Freya that you already have one and instead hunt for another one.
The next mission in the chain, "FW Southern Battle 1", has been updated to have a `to offer` condition that matches `"FW Southern Recon 1B"`, but now has a `to accept` condition of `has "fw provided electron beam"`. This new condition is set when you give Freya an electron beam, whether that …
=> feat(content): Allow "FW Southern Recon 1B" to be completed immediately if you already have an electron beam

CMakeLists.txt, credits.txt, endless-sky.6, resources/EndlessSky-Info.plist, source/WinApp.rc, source/main.cpp
=> 0.10.15 alpha version numbers

data/kahet/kahet missions.txt
**Typo fix**
'most' is only applicable when comparing three or more things.
=> Patir 7: Minor grammar change

source/image/ImageSet.cpp
**Style**
1. Fixed [opening bracket placement](https://github.com/endless-sky/endless-sky/wiki/C++-Style-Guide#opening-braces).
=> style(code) fix style in ImageSet.cpp

source/AI.h, source/Animate.h, source/ClickZone.h, source/ConversationPanel.h, source/DataWriter.h, source/Dialog.h, source/Engine.cpp, source/EsUuid.h, source/ExclusiveItem.h, source/FireCommand.cpp, source/LocationFilter.cpp, source/Outfit.cpp, source/PlayerInfoPanel.cpp, source/PrintData.cpp, source/RandomEvent.h, source/Sale.h, source/ScrollVar.h, source/Set.h, source/ShipNameDialog.h, source/Shop.h, source/WeightedList.h, source/comparators/ByUUID.h
**Style**
Updated the existing code to match the additions to the style standards proposed in https://github.com/endless-sky/endless-sky-wiki/pull/168.
https://github.com/endless-sky/endless-sky-wiki/pull/168
=> style(code): Unify the template declaration style

data/human/culture conversations.txt
=> fix(typo): offwolders to offworlders

README.md
Added version requirements for the main supported OSes: Linux, MacOS, and Windows (order is alphabetical).
In case of Linux it's hard to pinpoint specific versions. I decided to mention Ubuntu 20.04 because of [a source comment](https://github.com/endless-sky/endless-sky/blob/70988eec1a678a59619f5409ccc8b684c9c7acd6/source/Files.cpp#L50) indicating support, and because just saying "any modern distro" can mean really everything.
MacOS has hardcoded version requirements anyway, so this PR just publicly documents existing values.
As for Windows, 5.1 is what we use for the main exe, and our dependencies have no problems with it.
Also mentioned that it may be possible to run the game on other systems (I think there are people using UNIX-related systems other than Linux and …
=> docs: Update and expand system requirements
