endless-sky/endless-sky

data/human/campaign events.txt
**Bugfix:**
I suddenly started getting lots of deprecated warnings when loading my save files
>Warning: Deprecated use of "fighters" <names>. Use "names" <names> node under "fighters" instead.
While I can't change people's save files, I can change the way this line gets into new ones.  Changed fighters line to avoid the warning by moving the names into a names child.
Well, new starts don't generate the error (and do start).  However, these fleets are added by an event, and I'm not sure what triggers it.
=> changed fighters entry to avoid deprecated warning

data/remnant/remnant 2 side missions.txt, data/remnant/remnant jobs.txt
=> fix(typo): "you where"->"you were" in remnant.

source/Account.cpp, source/Mortgage.cpp, source/Mortgage.h
**Bugfix:**
Due to rounding errors in Mortage::Payment(), taking loans in certain amounts can result in a greater (or lesser) total amount of loans being offered.
Added a new method, Mortage::PrecisePayment(), that returns the unrounded payment schedule (double versus int64_t).  This is then used by Account::Prequalify() and Mortage::Maximum() to accurately calculate the maximum loan available.  Splitting up the loans has no effect on the overall amount that can be loaned out.
This change will have small effects on offered loan compared to what they were originally, but they'll be more consistent now and changes appear to be very small (about .1% in my test case, although a set of carefully crafted loans might see a larger change).
Combined with my previous PR (allowing the starting …
=> Mortgage rounding fix

source/Mission.cpp
**Bugfix:** This PR addresses issue #9057
Added code in Mission::Save to save shipyard and landing locations.
Ran it with #9024 also added for the early shipyard mission, saved at a location the mission would be saved, saved the game, checked the save file, found the tag.  Loaded the game and the mission would not fire in the spaceport, but would in the shipyard.
While I was in there, changed save to use else's when checking location, as missions can only be at one location.
=> fix(saves): save all location tags for missions

source/PlayerInfo.cpp
**Bugfix:**
Thx to MidnightPlugin for reporting this on the discord
the tribute: autocondition would never work, because it was not using a substring
I used a quick mission that would only offer if the "tribute: Bloodsea" was > 0, whilst having Bloodsea tributed, naturally
doesnt work without this PR because of looking for `tribute: planet` in the planets instead of `planet`
I think the oversight is obvious enough?
=> Bugfix: `tribute: ` autocondition

data/pug/pug news.txt
This PR limits the human Pug news to only appear on inhabited planets, stopping them from appearing during the period where the Pug have abandoned Deneb. Also refactors the location criteria: with the splitting of Wanderer and Human Pug, these filters are unnecessary.
=> fix(content): Stop Pug news from appearing on uninhabited planets

data/human/free worlds side plots.txt
This PR adds `minor` to "FW Zug Expansion: Assisted", preventing it from offering at the same time as another mission in the Free Worlds chain.
=> fix(content): Add `minor` to "FW Zug Expansion: Assisted"

source/MapOutfitterPanel.cpp, source/MapSalesPanel.cpp, source/MapShipyardPanel.cpp
**Feature:**
On the outfitter and shipyard maps, systems are displayed in one of three colors, depending on if they have an outfitter/shipyard or not, and if they sell a selected item (if any).  The color currently used for no outfitter/shipyard is a lighter blue (SystemValue -.5).  This would change it to use a darker blue (SystemValue -1.) to make systems with outfitters/shipyards more apparent.
Before:
After:
N/A
=> feat(ui): change map none color to darker blue (for shipyard/outfitter lists)

data/remnant/remnant 1 introduction.txt
**Bugfix:** 
This PR addresses issue reported by rumplestiltskin on Discord. Thanks for spotting it!
Adds the requirement to the Face to Maw 1 that the player must be flying the Puffin; as no other ship matches the mission text.
n/a
[Rebbia Rampart~3023-10-01 Found the Remnant.txt](https://github.com/endless-sky/endless-sky/files/12207927/Rebbia.Rampart.3023-10-01.Found.the.Remnant.txt)
(You'll have to unlock the puffin first. This is merely the closest save available.)
=> feat(fix): Adjust Face to Maw 1 to require the player to be flying a Puffin

source/MainPanel.cpp
**Bugfix:**
Thanks to @Hurleveur for reporting this on Discord.
The number of units of the outfit the ship has in cargo is first added to the output stream, then the mass of those outfits is added to it, resulting in the value being duplicated.
For example:
This creature actually only has 27 tonnes of the first item and 13 tonnes of the second, but those values are being added to the output string twice so they appear as 2727 and 1313.
This PR removes the duplication.
Scan ships carrying harvested materials in cargo.
Without this change, the value is repeated, with it, the correct values are shown.
[warp void sprite cargo …
=> Fix a bug when displaying the amount of harvested materials a ship has in cargo

source/MapPanel.cpp
Uses the custom wormhole color for the travel plan too.
before:
after:
just look at the map and select a route with a custom wormhole color
=> Fix(map): use the correct wormhole color on travel plan

source/Conversation.cpp, source/Conversation.h, source/ConversationPanel.cpp, source/ConversationPanel.h, source/GameAction.cpp, source/GameAction.h, source/Mission.cpp, source/MissionAction.cpp, source/MissionAction.h, source/NPC.cpp, source/NPC.h, source/NPCAction.cpp, source/NPCAction.h, source/PlanetPanel.cpp, source/ShipManager.h
**Bugfix:** This PR addresses issue #9093.
The documentation for `fail` is as follows:
> This causes the named mission (*or this mission, if no name is given*) to fail immediately.
Emphasis on "or this mission, if no name is given". The current behavior is not simply "this mission," but "all missions of this type."
Changed "fail" without a mission name provided to only fail the calling mission. The old behavior of failing all missions of the same type can still be used by explicitly providing the mission name.
This was accomplished by replacing the behavior of using the name of the mission that loaded the action to instead set a "failCaller" boolean. This avoids the need to pass around the name of the mission that is loading the various actions that the mission can trigger. Instead, …
=> Update `fail` action with no mission name behavior

data/drak/indigenous.txt
As noted in #9105.
Shield resistance does not appear anywhere in the source folder - there is no code to handle it. It does nothing.
=> Replace `shield resistance` on the Embersylph with `ion resistance`.

data/human/free worlds 0 prologue.txt
**Tweak:** This PR addresses some technically valid but unpleasant grammar I encountered after the description was brought up on Discord.
All I've done here is edit the description of the mission so that instead of saying "attacking freighters" twice in two sentences it first says "attacking shipping" and then later, "going after freighters."
The text should still be short enough that it doesn't overflow the description box.
=> feat(text): More pleasing grammar in FW Bounty 1

source/PlayerInfoPanel.cpp
Fixed the bug when you perform a double click, but the first click is on one ship and the second one is on another ship. Currently, it opens an info panel for the second ship.
With this change, it just selects the second ship without switching to any ship info panel.
Everything else works as before: tested both landed and in flight.
=> fix(ui): Correctly check for double clicks on ship list of Player Info panel

source/ShopPanel.cpp, source/ShopPanel.h
**Feature:** This PR resolves #4535
You can now open the map in outfitter and shipyard, with the default mode depending on where you are. When you close the map, the shop is as you left it (selected item remains selected etc.).
N/A
yes.
N/A
=> feat(ui): Allow opening the map in outfitter and shipyard

source/OutfitterPanel.cpp, source/ShipyardPanel.cpp
1. Made ship sprite scaling more restrictive, so that the ship won't appear larger than the background.
2. Made the item name look more centered (both shipyard and outfitter).
Before:
After:
=> fix(ui): Fix some shop info bar display bugs

data/governments.txt, data/hai/hai fleets.txt
**Bugfix:**
The government "Hai Merchant" is never used. ~~The only references to it are its own definition and attitudes towards it from various other governments. None of these attitudes do anything, though, because no ship with this government will ever appear in the vanilla game. This PR removes the government definition along with all those attitudes because they don't do anything and can only lead to confusion.~~
This PR adds it to the "Small Hai Merchant" and "Large Hai Merchant" fleets per https://github.com/endless-sky/endless-sky/pull/9111#issuecomment-1661280560.
~~Launch the game, see that it doesn't produce any errors about the government being referred to but not fully defined (will need to make sure recent.txt is empty because the save file will have a reference to it in …
=> Use an unused government

source/PlayerInfo.cpp
**Feature:**
This PR adds a new derived condition, `"roll: <input>"`, which rolls a random number in the range [0, input). The input can either be a number (which gets converted to an integer), or the name of a condition. If a condition name is provided, then the value of that condition is used as the input to the random function. If a value is provided that is <= 1, then the output will always be 0.
The existing `random` condition is hardcoded to always roll in the range [0, 100). By adding this condition, we can now roll random numbers in any arbitrary range that we want. Allowing the input to be a condition also allows for ranges that change dynamically depending on the state of the input condition.
N/A
See testing done.
Tested the following mission with "roll: deathroll" and "roll: …
=> Condition that allows rolling a random value in a specified range

data/wanderer/wanderers middle.txt
**Bugfix:** thx to sndeang51 for mentioning this on the discord
You would be able to get peace with the exiles without it making any sense because you just left.
I made the event and log fire later, once you actually accept doing this, after talking with them - I didnt move the failing of the previous mission tho caus that one is about establishing contact which you kinda did? I can change that tho
doesnt feel necessary
simple fix so should be fine
=> Bugfix: exile rep being positive when deferring the diplomacy

.github/workflows/steam.yml
**Bugfix:** This PR should address an issue in the CI: https://github.com/endless-sky/endless-sky/actions/runs/5769078872/job/15644655853
Run apt-get update before apt-get install. This is the proper way of installing anyways, so even if it doesn't fix, it's a good change.
/
=> fix(ci): run apt update before apt install

source/PlayerInfo.cpp
One can use "destroyed person: <name>" to find out if it died.
n/a
This can be mostly useful for plugins, that would for instance spawn custom person ships or react to you killing one of them.
I made the authors spawn all the time to snatch Tranquility (was noted in my savefile) and then made a small mission to see if it was always on (it isnt) and if it works properly (the mission offered as planned)
re-tested, still works
n/a
n/a
~~Small extra memory usage because we dont clear the destroyed authors anymore (that's why it wasnt working when I first tested it lol) but memory really doesnt matter even for old computers, especially at this scale.~~ realized I could do it another way so none
=> Feat(enhancement): destroyed persons autocondition

source/HailPanel.cpp
**Feature:** This PR resolves #4466
When you hail a ship carrying fighters or drones externally, the carried ships are visible on the hail panel.
Also fixed displaying `under` hardpoints (haven't tested how it behaved before, but the code seemed to display all hardpoints on top of the ship sprite).
Before:
After:
Fighters (over and under) and hardpoints (over and under) display correctly.
N/A
=> feat(ui): Display fighters of the hailed ship

source/MapPanel.cpp
**Feature:**
If the flagship is a fighter that has been modified for jump travel, the travel path will show the correct colors for the amount of fuel it has.
In theory, you could extend this idea to any fighter (not just the flagship) that's been modified for jump travel (and isn't able to be carried).  But that would be a lot more work. ;)
=> feat(mechanic): handle fighter flagship for jump path planning

data/hai/hai culture conversations.txt
From sergekoriakin on the Steam forums, this PR updates the Robotic Musical culture conversation to use the `hai tourism` tag rather than just the `tourism` tag, which does not exist in Hai space.
=> Update Robotic Musical to use Hai Tourism tag

endless-sky.6
**Bugfix:** This PR addresses a warning from troff:
```
troff:<standard input>:84: warning: expected numeric expression, got an escaped ' '
```
Remove the escaping backslash from the letters to turn them back to ordinary text and not special sequences.
There are no more warnings from troff after the fix.
=> fix troff errors in endless-sky.6

source/Test.cpp, source/main.cpp
**Bugfix:** This PR addresses small spelling mistakes in the source code
Replace occurrences of 'succesfully' with 'successfully'. The second one is in a comment, but is still an easy fix.
The result builds successfully.
=> two small spelling mistakes

source/Mission.cpp, source/MissionAction.h
**Bugfix:** This PR addresses an issue introduced in https://github.com/endless-sky/endless-sky/pull/9096
These were not updated to give the calling function, hopefully that's enough
I checked that no other do() were forgotten
nope
apparently this causes issues with missions failing on enter so test those ig
=> bugfix: fail missions not working properly

source/Angle.cpp, source/pi.h
**Feature:**
Angle::Unit no longer checks to see if it needs to create its static cache each call.  Instead, the cache is created when the program starts.
I also added const/constexpr as appropriate throughout Angle (which required also hitting pi.h).
Flew ships around.  Angle::Unit gets a lot of use.
Should be a _very_ small improvement when flying, with cache creation time moved to startup instead of showing up whenever.
=> feat(code): move angle unit cache creation to local storage

source/Angle.cpp, source/Angle.h, source/Ship.cpp
**Bugfix:** This PR addresses issue #9136
When testing to see if a ship is ready to jump, explicitly check for an exact turn (that is, one step of turning will align the ship in exactly the right direction).  In some instances, the default logic could fail because of rounding errors introduced by converting to/from Angle.
Ran 100 ships over 24 jumps twice.
This save file can be used to verify the bugfix. The bug will occur when using 4174fff, and will not occur when using this branch's build.
[Asteroid Miner~Arculus.txt](https://github.com/endless-sky/endless-sky/files/12294232/Asteroid.Miner.Arculus.txt)
<strike>AI::TurnToward could be modified so that this case wouldn't come up.</strike>  Actually, I think this case can always come up, and modifying AI::TurnToward would at best just …
=> fix(bug): check for exact turn prior to jumping

source/Ship.cpp
**Bugfix:**
If multiple elements cause thrust to be reduced (such as lack of energy, fuel, heat, etc.) reductions are cumulative, rather than only the greatest being used.  For example, having 1/2 the required energy and 1/2 the required fuel will reduce thrust to 1/4, not to 1/2.
Take into account prior reductions in thrust when checking to see if further reduction is necessary.  This brings the code into alignment with reducing turns, which also gets changed to use the same logic (using copysign, which is more elegant than multiplying by value/fabs(value)).
Not much, other than check to make sure the basics still worked.  I'm not sure the problem ever arose in practice.
I would have reopened #9155, but I deleted the branch, so that was out (reusing the branch name did not fix that). …
=> fix(bug): fixed bug in thrust scaling, modified turn scaling to match

data/hai/hai ships.txt, data/wanderer/wanderers start.txt
Change the license to match the one from the Unfettered campaign and add the new Unfettered ships to the Unfettered shipyards on Darkcloak.
This also splits the relevant event in two parts with the Solifuge part being renamed to "solifuge deployment" for easier finding and savefile clarity.
n/a
=> Content: add the solifuge to Unfettered shipyards when deployed during the wanderer campaign

source/MissionPanel.cpp
**Feature:**
When accepting a mission on the MissionPanel, when there are >2 available missions in the same system, try to advance forward in the list from the current position.  If there's no mission at the same system forward, then look backwards from the current position.  The old behavior is to reset to the first one available at that system.
This makes it easier to accept multiple missions to the same system while avoiding the first mission to the system, for example if the first mission is a Scout mission following by three Marauder missions.  In the original, after selecting each Marauder mission the selection would reset to the Scout, requiring moving the selection.  With the new code, if you selected the a Marauder mission, after each accept it would advance to the next one.
It's …
=> feat(ui): change mission list accepting advance to be more intuitive

source/Politics.cpp
**Bugfix:** This PR addresses issue #9135
`Politics::IsEnemy` now returns false if either government pointer is null and doesn't dereference either.
This essentially means no ship or planet can be hostile to a ship without a government.
Carry out the reproduction steps from the linked issue.
=> Fix a crash when spawning a defense fleet with no government

data/map planets.txt, data/map systems.txt
Stormhold didn't get the `forest` attribute added to it when I PR'd the expansion of that attribute to other planets. It's clearly a forest planet...
I've actually known this for a long time but never changed it until now, hahaha
=> Add `forest` attribute to Stormhold and change its planet sprite

data/human/hails.txt
** Summary
Replaces tabs after `phrase` with spaces, like every other phrase I've seen. I'm not sure if it has any effect on the hails, but we'll at least keep `hails.txt` consistent, hey?
Thank you zuckung for reporting this on the community discord server.
=> Replace tabs with spaces in two hails

data/map systems.txt
**Bugfix:** This PR addresses an issue I spotted a moment ago
Before:
After:
Two reasons for this. Firstly, and most obviously, having the outermost moon of that gas giant overlap Starting Rubin sometimes is not ideal.
But also, it's mentioned in some Coalition planet descriptions that the Kimek favour hotter, dryer conditions such as savannah and plains environments, which is contrasted with the Saryd preference for cooler boreal forest (description of Far Home). Yet currently Ki Patek Ka sits notably on the outer edge of its star's habitable zone (about 1.5 times further than the ideal habitable distance), which would make hot conditions very rare there, if not turn the planet into an outright ice world. While moving it to the inner edge of the habitable zone isn't possible without …
=> Move Ki Patek Ka inwards somewhat

data/human/free worlds 1 start.txt, data/human/free worlds 2 middle.txt, data/human/free worlds side plots.txt
This PR changes a the description of `FW Alphas 1.1` from:
> Destroy all pirates ships in the Graffias system with the help of the Navy Oathkeepers, then land on the planet and let the Navy troops eliminate the Alphas.
to
> Destroy the pirate ships occupying the Graffias system with the help of the Navy Oathkeepers, then land on the planet and let the Navy troops eliminate the Alphas.
It also changes mentions of "increased Naval fleet movements" to "increased Navy fleet movements", and `F.M.S.` ship prefixes to `F.S.`. 
Personally I prefer F.M.S. to F.S. because it implies there will be a more organised military (Free Military Ship?) but F.S. is used so much more.
=> fix(content): Minor Free Worlds text changes

source/OutfitterPanel.cpp, source/OutfitterPanel.h, source/ShipyardPanel.cpp, source/ShipyardPanel.h, source/ShopPanel.cpp, source/ShopPanel.h
**Feature:**
The only difference between the ShipyardPanel and OutfitterPanel versions of DrawPlayerShipInfo was passing a bool that stated whether or not it was for a shipyard or outfitter.  Now that ShopPanel knows which one it is (isOutfitter), there's no reason to have this code duplicated in both kids.
Checked the displays in both shops.
=> refactor: moved DrawPlayerShipInfo into ShopPanel

source/PlayerInfo.cpp
**Feature:** This PR closes #9170
You can now get the number of bays the flagship has with an autocondition:
`"flagship bays: <category>"`, where `<category>` is category of the bay.
Seems to work correctly in a conversation.
I think N/A
=> feat(enhancement): Autocondition for counting flagship's bays

data/hai/hai reveal 5 philosophers.txt
**Fix (Missions)**
This PR updates the description of `Hai Reveal [B08] Syndicate Internal Affairs` to give more information to the player. It also fixes a problem with the mission log's wording.
Thanks to u/riyan_gendut on the community discord server for bringing this to my attention.
=> fix(content): Update the description of `Hai Reveal [B08] Syndicate Internal Affairs` and fix log's wording

source/OutfitterPanel.cpp
**Bugfix:**
It occurred to me that, just like in the shipyard, the outfitter description zone is noticeably above the actual description.  This moves it down to match the description.  The name is also slightly off-center, which this corrects.  It also refactors Outfitter::DrawDetails a bit.
Clicked on edges of zone.
=> fix(bug): move description zone in outfitters to match description

source/ShipyardPanel.cpp
**Bugfix:**
Shifted the description clickzone down to match the description text (both collapsed and not).  Also shifted ship name to center it better,
Checked details display in shipyard, tried clicking in various places.
This pulls out the bug fix from #9085, as requested by @warp-core.  It's the mirror of #9194, but for the shipyard rather than the outfitter.
=> fix(bug): description zone in shipyard

data/_ui/interfaces.txt, source/HiringPanel.cpp, source/PlanetPanel.cpp
**Feature:**
On the Planet panel, buttons for all subpanels are shown (and active), even if the player doesn't have a flagship (i.e., has no ships on planet).  Depart is inactive unless the player has a ship.  All panels behave properly for the player not having a ship (jobs are listed as unavailable, crew is zero, no commodities can be purchased).
This changes the existing PlanetPanel UI which hides the Trading, Job Board, Spaceport, Outfitter, Hire Crew, and Depart buttons when the player has no flagship.
One of the primary reasons a player has no ship is that they're buying a new one, and having access to various information (trading prices, jobs available, outfits available) can inform that decision.  Also, if the player has outfits in storage on the planet, they cannot sell them …
=> feat(ui): always show subpanel buttons on Planet Panel

source/OutfitterPanel.cpp, source/ShipyardPanel.cpp
**Refactor:**
Turns out the vector with the description zone is cleared every cycle, so there's no reason to check if it's still there from the last cycle.  And if someone named a category "description", I think we have other issues.
Checked to make sure description clickzones behave properly, and that it didn't mess with the category clickzones in the main pane.
=> refactor: don't bother checking for existing description zone

source/PlayerInfo.cpp
**Bugfix:** This PR addresses issue #9144
In `PlayerInfo::FlagshipPtr()`, add a check as to whether any mission gives clearance to the current planet, and make that an allowable condition for setting the flagship. This ensures that even when on a planet for which `Planet::CanLand()` returns false, if the player got there through a mission that allows clearance, they will still be able to depart.
Note that there is still a potential concern here: If the player landed normally, with positive reputation, but some mission/event on the planet caused their reputation with the planet's government to become negative, they might be trapped.
Loaded a save file exhibiting the bug; observed that it no longer occurred.
Took off and landed a few times to ensure that other related mechanics 
This save …
=> fix(mechanics): Correctly pick flagship when landed on clearance planet

source/ItemInfoDisplay.cpp, source/OutfitterPanel.cpp, source/ShipyardPanel.cpp
**Bugfix:**
Currently, the description click zone and collapsed label will still be created and drawn even if the description is completely empty.
This PR skips these items if the description is empty.
Visited the outfitter and shipyard and checked items with no description:
Before | After
-- | --
=> Handle empty descriptions in shops

data/_ui/interfaces.txt, source/AI.cpp, source/Engine.cpp, source/Messages.h
**Feature:** This PR implements the feature request detailed and discussed in issue #9191
Added a new message priority, "info", which can be used for messages that should be more visible than normal hails, but are different then a warning.
Currently only used for the message that tells if a mission requires you to land on a planet.
See screenshot
=> Feat(ui): Make the message about missions require landing more notable

data/remnant/remnant 1 introduction.txt
**Bugfix:**
- Removes `minor` from Face to Maw 1 so it is not blocked by Face to Maw 1B.
- Added `has "flagship model: Puffin"` to the `to offer` conditions of Face to Maw 1B to match Face to Maw 1 so the missions always offer together.
These are also fixed by #9098 but that also reorganises the missions to remove the possibility of this sort of thing occurring in the future.
0
This save file can be used to verify the bugfix. The bug will occur when using [41e3eba](https://github.com/endless-sky/endless-sky/commit/41e3eba00496db934a191ed288e4c47cd971e8b4), and will not occur when using this branch's build.
[warp core 1~3016-10-06.txt](https://github.com/endless-sky/endless-sky/files/12334464/warp.core.1.3016-10-06.txt)
The Summer Leaf flagship has been given gaslining to demonstrate that …
=> Fix Face to Maw 1 and 1B offering

source/Ship.cpp
**Bugfix:**
Thanks to @Amazinite for reporting this.
Because of the exclusive inequality, a second scan dialog may be displayed after the first if the player presses the scan key again, after closing the first dialog. This shouldn't happen.
Scanned a ship, closed the dialog, pressed the scan key again and no longer get the scan dialog repeated.
=> Fix duplicate scan dialog display

data/kahet/kahet outfits.txt
**Balance:**
In the same spirit of https://github.com/endless-sky/endless-sky/pull/9070, I've changed the balance between scrambling (nearly removed) and direct ion damage (increased of roughly the 45%), with the addition on top of an energy damage of 3200/shot
Mentioning again https://github.com/endless-sky/endless-sky/pull/9070 because the reasoning is kind of the same - much of the concept between the two weapons is identical, only that one is bigger and a tier higher than the other. In this case I've gone with an even bigger disparity between scrambling and ion since, despite the nullifier being intended as more powerful, the scrambling can be particularly annoying to fight against in large quantity; energy damage maintains the theme of the weapon, while hopefully avoiding to become …
=> Balance: Nullifier rebalance

data/hai/hai outfits.txt
**Balance:**
The ion cannon went from 5 ion 5 scrambling to 6 6 scrambling.
The scrambling element's interaction with lasers will get a rework soon I just dont know how yet.
Currently the weapon is only borderline useful if you spam it a lot, although some say the scrambling part is too good in duels (I didnt notice that myself tho)
~~Hence why I am reducing it, whilst increasing the ion side of the weapon, but I could go to say 4 on it, and only buff it by 5% in total? Or make it 6 - 4.5? (or 6.5-4 but then its getting close to prototype territory, which could be fine)~~ changed to sticking with 6 6 because the normal version should not be "prototyped"
I like the ion cannon keep on being sort of a jack of trades, not too good but good against some factions still, that's why I don't want …
=> Balance: ion cannon 20% ions buff

data/governments.txt
I changed the Hai-Unfettered relations:
The Unfettered do not mind being disabled anymore, as you just bested them (they won't be proud to tell anyone!). This means that the player's reputation towards them is more reflective of things they actually mind (and your fleet passively disabling them is fine).
I could make them care less about being boarded, too.
As for the Hai, they should not approve you destroying or capturing their cousins. The compromise is to make them have -0.01 relation, meaning they wont react to you disabling/killing/capping the Unfettered at all.
To compensate for the lower overall reputation that will result of this, I made them care more about you assisting their ships (they go as far as giving you money for it, so they care a lot, especially since being disabled …
=> content: adapt the Hai relations to better reflect the Hai-UHai situation

utils/contentStyle.json
**Bugfix:** This PR addresses a false positive in the content style checker.
Some abbreviations could trigger one of the checks. It's fixed now.
See https://discord.com/channels/251118043411775489/266345072554016768/1144277408892067971
I checked in an online regex matcher thingy, it should be fine now.
N/A
=> fix(ci): Fix false positive in content style checker

source/MapDetailPanel.cpp
**Bugfix:** This PR fixes #9211.
Currently, planet list used by the orbits view is cleared only if the system has been visited (see lines 816-817), which causes a bug described in the issue. Moving the clear command up fixes the problem.
Works good both in visited and unvisited systems.
=> fix(ui): Always clear orbits view storage

data/human/marauders.txt
**Balance:**
Reduced the engine space of the Marauder Falcon (Engines) by 30, and reduced the engine space of the Marauder Leviathan (Engines) by 40. The Marauder Falcon (Engines) keeps its A860 thruster, but downgrades its steering to A525, while the Marauder Leviathan (Engines) does the reverse - downgrading its thruster to A520, but keeping the A865 steering. The Falcon has the option to run either setup, the Leviathan cannot fit the A860 thruster without downgrading to A375 steering.
Also tweaked the other outfits to make use of the freed-up space and power - the engines Falcon upgrades its shield generator, and swaps its blaster turrets for quad blaster turrets, while the engines Leviathan adds a second shield generator.
As noted in #8124, the two engines marauder heavy warships are …
=> feat(balance): Make the engine variants of the two marauder heavy warships less absurd

source/Fleet.cpp
Undeprecates the simple fighter name syntax that got deprecated in #9029:
```
fleet "some fleet"
"fighters" <name> # no longer deprecated
```
The reason being is that using the longer form is unnecessary if you don't need your fighters to have a different personality than the parent. ~~I've also added a warning if somebody tries to use both syntax types together.~~
Verified that the deprecated warning isn't showing up anymore.
=> Undeprecated the simple "fighters <name>" syntax

source/Fleet.cpp
This makes fleet spawn from a random ringworld location, instead of all ships coming from one single location in the ringworld. Open question whether this should apply to defense fleets too (~~currently I haven't changed this~~ edit: this applies to defense fleets too now).
Verified that the PR works as advertised, fleets in systems with a ringwold depart from any random location from the ringworld.
Go to any system with a ringworld.
=> Stop making fleets spawn from one single ringworld location

CMakeLists.txt, docs/readme-cmake.md, vcpkg.json
There seems to be a problem with CMake being unable to find system installed OpenAL Soft on MacOS ARM64, which meant that the build always failed due to being unable to find OpenAL.
This PR fixes this issue by always installing OpenAL Soft as a dependency through vcpkg, instead of requiring the user to install it system-wide.
=> Always use vcpkg's OpenAL Soft on MacOS

CMakeLists.txt
The logic to properly update the dependencies was a bit broken, which meant that any dependency update didn't properly register and you had to remove the build folder for it to initialize properly if dependencies were updated.
This PR fixes this problem, so that any future dependency updates works seamlessly.
=> Fix dependency update logic to fix future updates

source/Outfit.cpp
**Bugfix:** This PR fixes #8557
Changed outfit adding logic so that flares using the same sprite, but having different scale are now treated as separate entries in ship's flare table.
Tested with steps provided in the original issue.
=> Correctly update engine flares with the same sprite, but different scale

CMakePresets.json
In CI we don't need to build debug versions of dependencies, we can simply use the release versions all the time. While this doesn't have a big effect right now because host dependencies are currently just a couple of scripts, if they ever change to add executables which will need to be built, this will have an effect.
This is basically future-proofing.
=> Don't build unnecessary debug dependencies

source/Engine.cpp, source/PlanetLabel.cpp, source/PlanetLabel.h, source/Preferences.cpp, source/Preferences.h, source/Rectangle.cpp, source/Rectangle.h
**Feature:** This PR implements the feature request detailed and discussed in issue #9181
This extends some of the changes made in #9181.  Most of the code changes shown here are already in that PR.  Only the last 3 or so commits (at submission time (more now ;)) go beyond that.
Planet labels can now be drawn at any angle, and the list of angles has been expanded to include the cardinal directions.  The labels are centered rather than left/right justified.  Every zoom level is checked for overlaps.
Possible Label Positions Before 9181:
Possible Label Positions After 9181:
Possible Label Positions After This:
Centering of labels when government is the longer string:
Labels with no government:
How it looks in practice:
Not too much, given that this only affects the label offset calculation, …
=> expanded planet label drawing

source/main.cpp
Toggling fullscreen, unlike opening the menu or toggling fast-forward, is not a "game" command and rather a "window" command. Limiting the ability to do so (in non-interruptible panels) may seem like something's broken.
Opened the logbook and successfully toggled fullscreen mode.
=> Allow toggling fullscreen in all panels

data/human/campaign events.txt
Right now, the New Austria description fits into its text box awkwardly: there is more empty space at the top of the box than there is at the bottom. This PR slightly truncates the New Austria `"initial deployment 1"` description, so that there is a spare line of space at the bottom.
=> fix(content): Trim New Austria's post-bombing description to better fit text box

data/human/human missions.txt
This is a small mission during the early days of the Free Worlds campaign to take some refugees to Humanika. Mostly I thought Humanika was a cool planet that was too easy to miss, so I wanted to create a way to introduce the player to it.
* [refugees-to-humanika-with-quarg-contact~3021-09-14.txt](https://github.com/endless-sky/endless-sky/files/12326065/refugees-to-humanika-with-quarg-contact.3021-09-14.txt)
* [refugees-to-humanika-without-quarg-contact~3021-09-14.txt](https://github.com/endless-sky/endless-sky/files/12326066/refugees-to-humanika-without-quarg-contact.3021-09-14.txt) (I manually edited out the Quarg first contact from this file, so this might not be a good file to …
=> Add mission to take refugees to Humanika

source/Engine.cpp
**Bugfix:** This PR addresses issue #7631
I think the planet label was updated one too many times.
Actually, I'm not 100% sure if that was the issue, but it seems to be gone now, so I guess that was it? ~~I don't know much about the UI code.~~
Landed a couple times. Seems to be gone now.
Literally any save file.
=> fix(ui): Fix planet being offset from its label when landing

source/NPC.cpp, source/NPC.h
**Bugfix:** Alternative to #9258, addresses #9253.
Makes the "kill" NPC action trigger from either the DESTROY or CAPTURE ship events.
Also, adds a "destroy" NPC action that is only triggered by the DESTROY ship event.
Also, makes the NPC::Trigger enum and enum class and reorders the NPC action triggers to match the order of the ship events they correspond to.
0
=> Add NPC action triggered by capturing or destroying a ship

source/NPC.cpp
**Bugfix:**
Thanks to @Anarchist2 for reporting this on Discord.
When multiple events occur simultaneously (for example, a ship going from not disabled to destroyed in a single hit, such as from heavy rockets) NPC actions will not correctly be triggered because it searches the map of ShipEvents to NPC action triggers for exact matches to the new event, but if the new event is actually multiple simultaneous events, it will not match any of the ShipEvent keys in the map and so will not trigger anything.
This PR traverses the map and adds any triggers triggered by any of the new events to an std::set which is then traversed when actually doing the actions.
0
=> Correctly trigger NPC actions with simultaneous events

data/sheragi/archaeology missions.txt
Commit 99a69a7ae1cab14f5b098775e6af16bad282155b (PR #9264) made "on kill" also function when ships are captured, removing the requirement of an additional "on capture" branch. I removed these branches from Deep Archaeology 3 and 5.
[Endless-Sky any%~Deep Archaeology.txt](https://github.com/endless-sky/endless-sky/files/12514737/Endless-Sky.any.Deep.Archaeology.txt)
This is the same one as from PR #8582  where these conditions were initially added.
n/a
=> refactor: Remove now redundant conditions in deep archaeology

data/_ui/interfaces.txt, source/MapDetailPanel.cpp, source/MapPlanetCard.cpp, source/MapPlanetCard.h
**Feature:** This PR resolves #4022
The name of the planet's government is now displayed on the planet card (map UI), above the friendliness line. Selecting the entry activates the government map mode.
This is enabled for systems that have a planet with government different from that of the system (planets with the special "Uninhabited" government aren't considered).
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
(no difference here)
</details>
Displays correctly, selecting works.
N/A
=> feat(ui): Display the government name on the planet card

.github/workflows/cd.yaml, .github/workflows/cd_release.yaml, .github/workflows/ci.yml, .github/workflows/compute-changes.yml, .github/workflows/projects_check.yml, .github/workflows/steam.yml
Updates the checkout action used in pretty much every CI/CD job. Unless I missed something, this is the only outdated action we are using.
Also disables progress reporting and removes some redundant configuration.
=> chore(ci): Update actions/checkout

data/hai/hai outfits.txt, data/hai/hai ships.txt
This is a re-PR of https://github.com/endless-sky/endless-sky/pull/8908.
A lot of discussion occurs around Endless Sky's "Railgun". While we don't follow realism to the T, the fact that the Railgun is simply named "Railgun" implies that it is *the* Railgun in the game. Although the principles are the same, it is truly of more Hai-nature with the ion damage and the special tactical use of it on smaller ships.
This PR adds "Skipper Railgun" as a display name for the Railgun and related oufits. Skipper is another terminology for water strider bugs, and the Railgun's main aspect is the tactical usage of the recoil on Fleas, allowing them to "skip" around. This presents the weapon as even more so of Hai origin, and not the Railgun of the ES universe.
Originally, this replaced the name and …
=> feat(content): Rename Hai "Railgun" to "Skipper Railgun" using `display name`

source/GameData.cpp, source/PlayerInfo.cpp, source/Plugins.cpp, source/Plugins.h, source/Set.h
**Bugfix:** This PR fixes #9237
Plugins with a custom name where saved under the folder name, instead of of the custom name. This PR fixes this by properly storing the plugin with its custom name in the plugins set.
Tested with the steps described in the linked issue, which are fixed with this PR.
=> Fix plugins with a custom name

.github/sccache/action.yml, .github/workflows/cd.yaml, .github/workflows/cd_release.yaml, CMakePresets.json
- Downgrades sccache because the last 3 versions are currently broken
- sccache changed the environment variables to enable its cache somewhere along the way, which meant that nothing was cached
- Removes 'read-only' caches, because they don't really make sense anymore
- Avoid repeating the compiler launcher for CI builds in the preset file
- Reenabled warnings as error for CD builds, because if the command line flags are different the caches won't match.
- Reenabled PR cache writes (see below)
A while back we were constantly hitting GitHub's cache limit of 10GB because we were caching the object files of PRs too. As an experiment, I'm reenabling this caching now as an experiment to see if we will hit the cache limit again. The difference to before is that with sccache the caching is …
=> Fix caching that's been broken for a while

source/PreferencesPanel.cpp
**Bugfix:**
When the checkboxes were added to the plugin panel, the x coordinate at which the plugin name starts was moved to the right by 20 pixels, but the allowed width for the plugin name was not reduced and so plugin names can currently extend beyond the expected region before they are truncated.
This reduces the allowed width by 20 pixels to account for the reduced space.
Open the plugin panel with a plugin that has a very long name and see it is now truncated to an appropriate length, staying within the box for the plugin list.
=> Fix plugin name truncation

.github/workflows/cd.yaml
**Bugfix:** This PR fixes an edge case where some build artifacts are not uploaded to the continuous release.
If you check [this](https://github.com/endless-sky/endless-sky/actions/runs/6132248511/job/16643037290) CD job, you will see that the windows artifact's upload failed, causing the fresh macOS artifact to also not get uploaded because the job has already failed.
This PR makes the job continue even if one of the previous uploads fail, so all platforms with successful builds should get their latest artifact uploaded to continuous.
I didn't make the same change in the release CD because if something goes wrong there, having a big red error about it is probably more important than getting more build artifacts.
I don't know how to test this tbh.
N/A
=> fix(cd): Don't skip artifact uploads to continuous

source/MapPanel.cpp
**Refactor:**
When a system is selected in the map, if that selection results in the final system in the travel plan being different to what it previously was, reset the travel destination planet.
I don't think not resetting this actually causes any problems at the moment, but it is more robust to ensure that it is cleared when the travel plan changes.
=> Clear the travel destination when the final system in the travel plan is changed

data/human/culture conversations.txt
**Bugfix:**
`attributes "dirt belt" "farming"` matches locations with either of these attributes. This doesn't seem to match the content of the conversation. It includes farming worlds that aren't in the dirt belt and dirt belt worlds that aren't farming.
```
attributes "dirt belt"
attributes "farming"
```
Will only match locations with both of these attributes, which is much more in line with the conversation.
<details> <summary>Planets matched by the current filter:</summary>
Arabia
Big Sky
Bounty
Clark
Cornucopia
Darkstone
Flood
Gemstone
Harmony
Heartland
Hopper
Ingot
Lichen
Mars
New Argentina
New Austria
New Boston
New Britain
New Greenland
New Holland
New Iceland
New India
New Kansas
New Portland
New Sahara
New Tibet
New Wales
New Washington
Oasis
Oblivion
Poisonwood
Rand
Rust
Sinter …
=> Fix "Trash Fire Crops" source location filter

data/map systems.txt
**Bugfix:**
The "rouge" (rogue) brown dwarf sprites are rendered with self-illumination, for use when the object does not have a parent star and has no nearby light source to illuminate it in the usual way.
This system contains four stars, so this brown dwarf is clearly not a rogue planet.
This PR switches the object from using a rogue brown dwarf sprite to the corresponding normal brown dwarf sprite.
=> Use correct version of brown dwarf sprite

source/SpriteQueue.cpp
This PR stops loading images past a certain number. For a very small time increase it can reduce memory usage by as much as 3x. (might even be more if for some reason your CPU has like 32 threads).
The following table represents the maximum amount of RAM used at any point during the program's startup. Note that the exact RAM used depends on your CPU (faster and/or thread count).
| | this PR | continuous |
|-|--|---|
| no plugins | 0.4 GB | 1.5 GB |
| high dpi | 1.2 GB| 4.2 GB|
The performance impact depends on your CPU, but in the absolute worst case it will be a couple of seconds more load time at startup I believe. I would expect an average CPU to only see a couple hundred ms impact if at all.
My machine sees no impact at all.
=> Optimize memory usage when loading images at startup

README.md
Updates the system requirements:
- The RAM usage on a clean build is a bit higher than 500MB on my machine, so I increased it to 750 MB to be on the safe side 
- The size of continuous is very close to 300MB, so I increased it to 350MB to be on the safe side again
- The size of the high dpi plugin is pretty big, so I increase the storage size for "recommended" as well.
=> Update system requirements

docs/readme-cmake.md
Tweaks the build instructions a bit:
- Fix internal hyperlinks
- Removed some unnecessary text
- Tweaked the wording in several places
- Improve organization
- Updated links
- Updated some old steps which didn't apply anymore
- typos
- Fix Markdown formatting
=> Tweaks to the build instructions

source/PlanetPanel.cpp
**Bugfix:**
This bound was previously removed by mistake.
Not having it means that, if you try taking off with fewer crew than your ship requires, the game will think you are "overbooked," that is, it thinks you have more mission passengers than you can carry, even when this is not the case.
Use the below save file.
Without this PR, attempting to depart gives a dialog indicating that a mission will be aborted because I cannot carry 48 of its passengers, even though the mission only has 1 passenger and I have plenty of bunks for it (it will actually give the warning even if I have no missions.) Taking off doesn't actually abort the mission.
With this PR, no warning is displayed.
This save file can be used to verify the bugfix. The bug will occur when using a576744, and will not occur when …
=> Fix fewer crew than required 

.editorconfig
**Feature:**
Adds an entry in the .editorconfig file for the credits.txt file.
Without this, VSCode expects 4 space wide tabs for indentation, marking the double space indentations used in this file as erroneous, and will not use this indentation style. With this, it recognises those indentations as correct and will use that indentation style itself.
=> Add editorconfig for credits file

source/OutfitterPanel.cpp
**Feature:**
Currently, the outfitter's offer to automatically refill ammo does not account for ammo that might be in planetary storage.
This PR enables it to pull ammo from storage as well as cargo for free, before buying new ammo.
Ammo is loaded from storage first. This could potentially be user customisable, though.
With the attached save file, without this PR, opening the outfitter does not offer to refill ammo despite the Model 64 having space for a few more Teciimach Canisters and those Canisters being available in storage.
With this PR, there is an offer to refill that ammo.
[warp core Refill from storage~original.txt](https://github.com/endless-sky/endless-sky/files/12705070/warp.core.Refill.from.storage.original.txt)
=> Auto-refill ammo from storage

data/human/free worlds side plots.txt
**Content (Remove word)**
Noticed there was this random "and" on the on visit for the FW Flamethrower Fury mission.
Just removes it from the dialog.
=> Remove "and" from an on visit

source/OutfitterPanel.cpp, source/PlayerInfo.cpp, source/PlayerInfo.h, source/ShopPanel.cpp
**Bugfix:** This PR fixes #9334 
Refactors the problematic function in question to always return a valid storage.
Open the outfitter with a ship that needs ammo on a planet without storage. Without this PR, it crashes.
=> Fix crash when opening the outfitter

data/coalition/coalition outfits.txt
(this doesn't really fit anywhere so I'm just going to put it as a fix)
Recategorises the Heliarch License to conform with all other licenses
=> Recategorises the Heliarch License

source/Engine.cpp
As the title said. Departing from a ringworld now makes you depart from the exact dock you landed on originally, instead of always the same one.
Landed on a ringworld in many difference places, made sure that I always departed from the same place.
=> Make the player takeoff from the ringworld dock it landed on

source/Engine.cpp, source/Engine.h
Fixes a performance regression in systems with a lot of planet labels introduced in f52da6510be9310675eba63b182334278706141d
The planet labels still appear.
=> Fix performance regression in Omnis system

CMakeLists.txt
Turns out main.cpp was getting compiled without any of the compiler flags that we use :/
=> Correctly add compiler flags for main.cpp

data/coalition/heliarch intro.txt, data/coalition/lunarium intro.txt
**Content (Fix)**
Propaganda mission chain didn't require First Contact, which could get potentially awkward.
Containment mission chain had a redundant requirement for mission 2 to have been done by mission 4, despite mission 4 requiring mission 3 to be done and mission 3 requiring mission 2 to be done.
=> 2 quick fixes to Coalition Intros

source/Files.cpp, source/Files.h
**Bugfix:** This PR addresses fixes #9295 
This corrects the SDL_GetPrefPath call, to properly get the user-defined config folder on every platform. This was broken on Android.
/cc @thewierdnut 
Tested this on Linux. I haven't tested the others, but I don't expect there to be any problems.
=> Fix usage of SDL_GetPrefPath

data/human/human missions.txt
A week or two ago a series of new missions in the galactic south were committed in 7379ea7c27356ded3bb8ffc01e89adbb2bf7ff32 as part of PR #9097, however, one of them contained a circular dependency/catch 22 where a mission required itself to be offered in order to offer, as mentioned by @waterhouse [here](https://github.com/endless-sky/endless-sky/pull/9097#discussion_r1330033604). It looks like this was supposed to require the previous mission to offer, so that's what it does now.
The original PR didn't appear to need a save file, so I'm not providing one here. If necessary, I or the OP can provide one.
~~- [ ] I updated the copyright attributions, or decline to claim copyright of …
=> Fix catch 22 in new south mission

data/human/near earth jobs.txt
Changes `workers` to `farmers` and `tourists` as appropriate in the dialogs of `Transport farmers to Mars` and `Transport tourists to Luna`.
=> Fix to intra-Sol transportation jobs

data/coalition/heliarch intro.txt
**Bugfix:**
This conversation has actions splitting the text nodes and the actions are placed as though they are a part of the "on offer" trigger and not conversation actions.
Not only does this lead to the contents of the conversation below these actions being discarded when loading, but hte actions will be applied when the mission is offered, even if the player chooses to defer or decline.
This PR puts these items inside an conversation action that is only applied if the player accepts the license.
Also, changes the endpoint at the end of the conversation to `accept` to `decline`. This isn't a mission where accepting it has any meaning. It should just decline to avoid confusion about what it's supposed to do.
0
=> Fix Heliarch License 2

data/coalition/heliarch intro.txt
These missions incur significant reputation penalties when they are failed.
These probably shouldn't apply if the player simply aborts them because they don't want to do them, so the missions need explicit "on abort" triggers else the "on fail" ones will be triggered when aborting.
This adds "on abort" triggers to these missions which do not apply the reputation penalties.
=> Give some Heliarch missions "on abort" triggers

data/coalition/heliarch intro.txt
**Bugfix:**
Mostly just reordering stuff for consistency.
Removes a duplicate `on complete` trigger in a mission.
Moves a couple of `action`s out of conversations where they are always applied into the parent `action` to make it clearer what's happening.
Removed the deadline from "Heliarch License 2" which I should have done in my other PR because that mission is no longer accepted.
=> Some more Heliarch intro changes

source/AI.cpp
**Bugfix:** This PR addresses a long-standing performance issue in the game engine.
One of the lambda functions was copying a massive list of ships on every call, because it wasn't using a reference parameter.
The issue was found by @quyykk using my profiling data.
Profiling data gathered using CLion's C++ profiler. 
Before:
After:
The massive amount of malloc/free calls are gone.
The in-game reporting of CPU usage went from 1200%+ to 500-550%, which is a massive improvement.
[Test Pilot.txt](https://github.com/endless-sky/endless-sky/files/12752926/Test.Pilot.txt)
=> fix: Fix missing reference parameter

data/human/deep jobs.txt
**Bugfix:** This PR addresses issue #7825 
As mentioned in the bug, there is an apparent oversight where, upon dropping off a "secure package" to a security officer, police officer, ship captain, or reception counter, you wonder how the bank knew the delivery was a success, even though the answer is pretty clear. This is unlike the mystery boxes where you place them in discrete locations. This PR fixes that issue by removing the line of text where you wonder how the bank knew.
I looked at the various places you could deliver the secure package to in the message:
reception counter: the receptionist reports the delivery
spaceport security officer: they report the delivery
curiosities store: this is the most likely issue. If needed, I can try separating this from the others and having two …
=> Fix secure package delivery message

data/coalition/heliarch intro.txt
This PR adds `fail` conditions on the `board` or `capture` of the Punisher, and moves the original `fail` conditions into the on `kill` of it as well. This way, the rep loss is instant, rather than pending the player's next landing.
This save file can be used to play through the new mission content, courteous of @danaris :
[Hannah_Derinden.txt](https://github.com/endless-sky/endless-sky/files/12754120/Hannah_Derinden.txt)
All you have to do is re-land on Belug and go to the spaceport to accept the mission.
=> feat(content): Adjust how "Heliarch Drill 3" `fails`

data/coalition/heliarch intro.txt, data/coalition/lunarium intro.txt
**Bugfix:**
The missions "Heliarch Recon 3-B" and "Heliarch Recon 3-C" are mutually exclusive. One is for if you do not have the Heliarch license, the other is for if you do have it. As it is, you could do the first one and then be offered the second later after acquiring the license, which doesn't make sense.
This PR prevents each from offering if the other has already been offered.
Additionally, added a "joined the lunarium" condition that is set upon completing "Lunarium: Join" which is used throughout where "Lunarium: Questions: done" was previously used.
Also, removed an incorrect "to complete" condition in "Lunarium: Questions" which will now complete immediately upon arriving at the destination and being offered the next mission. There isn't any need to keep this mission around, …
=> Fix some conditions in the Coalition intros

source/SpriteShader.cpp
**Bugfix:** This PR addresses an issue reported by @Azure3141 
Swizzlemask was getting applied in the ship info panel, I fixed that
Lookes in the panel, works
random swizzlemask for a maboro for testing:
=> Fix(swizzlemask): do not apply in ship info panel

source/ShipJumpNavigation.cpp
**Bugfix:** This PR addresses issue #https://github.com/endless-sky/endless-sky/pull/9374#issuecomment-1741281313
The problem of not being able to travel along a hyperlink with only a jump drive (no hyperdrive) from a system with a reduced jump range (so, the other end of the hyperlink is not within the system's jump range) is indeed a recent one, introduced in #9289.
This PR fixes that by addressing the oversight in that PR.
A system being linked will now correctly count as it being accessible by jump drive regardless of jump range and distance.
Try to jump out of the Yranjiu system with a ship that has only a jump drive, no hyperdrive. It is now possible again.
This save file can be used to verify the bugfix. The bug will occur when using 9eb74d2 onwards, and will not occur when using …
=> Fix jump drive usage of hyperlinks from systems with limited jump range

data/coalition/heliarch intro.txt, data/coalition/lunarium intro.txt
**Bugfix:**
Offers these missions when the previous missions are done instead of active. Those missions are completed upon arriving at hte sources of these missions and so will no longer be active, meaning these missions would otherwise never be offered.
Tested the Heliarch one. I am now actually offered the second mission upon completing hte first.
=> One more Coalition intro thing

data/human/syndicate jobs.txt
Some Core jobs don't give the player the number of bunks needed to accept the job. This adds that to the descriptions of those jobs.
Before:
After:
=> fix(content): Add `<bunks>` to core jobs missing them

source/Engine.cpp, source/Preferences.cpp, source/Preferences.h, source/PreferencesPanel.cpp
#9391
basically the heading, I disabled the the extended jump effects by default, and made it so that you can choose between tow levels of strength, the "medium" level had no performance impact on my end, while the "heavy" level increased my gpu load by a factor 4.
some numbers,
medium increases drawn area by roughly 1500 pixels in each direction
heavy by 3000
My reasoning:
Having effects on that have a heavy gpu load can scare away first time users, so something like this should be off by default.
later if requested
yes
See above
=> Feat(extended jump effects): Add a new level for the setting and disable by default

data/human/frontier jobs.txt
`"reputation: Pirates"` can never be below zero, because there is no government named `Pirates`.
=> fix(content): Correct offer conditions of `"Small Pirate gambling"`

data/wanderer/wanderers middle.txt
**Bugfix:**
Thanks to @Hurleveur for reporting this on Discord.
The event that updates attitudes when the Kor Mereti become friendly only updates the attitude of the "Quarg (Kor Efret)" government, not the "Quarg" government (which may be used for older, persistent mission NPC ships, and is still used for many Quarg fleets in the area) so those ships remain hostile to the Mereti. Additionally, anyone who got the older version of this event will have *only* had the attitude of the "Quarg" government updated, meaning the "Quarg (Kor Efret)" government remains hostile to the Mereti.
This PR updates the event to make both of these Quarg governments friendly with the Mereti (the other Quarg governments are never hostile to them) and adds a patch mission that will rerun that event to ensure …
=> Fix Quarg attitudes towards the Kor Mereti post-Mind

data/map systems.txt, data/wanderer/wanderers middle.txt
This PR updates several Quarg fleets in old Korath space to use the proper Quarg "Kor Efret" government, and updates two Quarg governments used in Wanderers Middle that are recruited from the Quarg (Hai) ringworld, not the regular Quarg or Kor Efret Quarg.
#9408 solves any issues with pre-determined Quarg fleets that I had missed before.
=> fix(content): Update several Quarg fleets

source/LoadPanel.cpp
**Bugfix:**
When scrolling up from the top of a short list with the keyboard, all the items will jump to the bottom. This is because the scroll value is being set to a negative number. This PR ensures that the scroll value does not become less than zero.
Tried scrolling up with the keyboard and see that the items remain in the correct positions.
=> Fix load panel keyboard scrolling up

data/coalition/lunarium intro.txt
Prior to the merge of https://github.com/endless-sky/endless-sky/pull/9402, there was a (relatively small?) chance that the player could have joined both the Heliarchs and Lunarium. This PR introduces a patch for those saves who have joined both factions, and forces them to choose one side. Based on their choice, the conditions of the other side are cleared. I've put the patch below the Lunarium intro as this was a result of a Lunarium mission lacking some conditions.
=> fix(content): Choose which Coalition faction to side with if player joined both

data/human/free worlds 0 prologue.txt
During `FW Katya 2A`, Katya says that Ijs is "a little unpopular with big corporations and certain corrupt planetary governments," and in `FW Katya 2B`, Ijs directly says that "the Syndicate hates my guts right now." Despite this, the NPCs in `FW Katya 2B`, who are implied by the previous statements to be Syndicate-paid mercenaries, are just regular pirates, and tend to be destroyed by Syndicate forces themselves. This PR makes the titular change so that this doesn't happen. To compensate for the increased difficulty (especially since this mission might be the first time a player is chased by an enemy with force damage), the fleet now has the `staying` personality.
=> feat(content): Change `FW Katya 2B`'s fleet's government from `Pirate` to `Bounty Hunter`

data/_ui/interfaces.txt, data/_ui/tooltips.txt, source/PreferencesPanel.cpp
Create tooltips for all controls and settings. I tried to recall any extra quirks about any of the controls or settings and mention them in the tooltip. Let me know if I missed anything.
Expanded the width of the tooltips in the preferences panel from 150 to 250 to give more room to explain.
Since tooltips contain information about combining the keys with shift, also replaced the shift panel with an "Additional info" panel. Moved the line about unbinding controls to this panel, along with a line about binding multiple controls to the same key.
Resolves #9360.
=> Create tooltips for all controls and settings

source/Outfit.cpp
**Feature**
This PR removes `"hull repair rate"` and `"shield generation"` (suggested by quyykk) from the attributes whitelist.
https://github.com/endless-sky/endless-sky/pull/6646 added the Shield Refactor Module, which reduces hull repair by a flat value as well as by a -20% multiplier, while increasing shield regen by 25%.
It was reported on the Discord that the outfit was being installed even in ships which completely lacked hull repair.
That is not intended behavior.
Upon investigation it appears to be happening because https://github.com/endless-sky/endless-sky/pull/6872 added `"hull repair rate"` to the attribute whitelist, allowing it to go below 0, meaning the flat value reduction of hull repair is simply meaningless currently.
This PR thus aims to address …
=> Remove regen attributes from attribute whitelist

data/coalition/coalition outfits.txt, data/coalition/heliarch intro.txt
**Balance:**
Doubles the cost for the `Anti-Materiel Gun`, lowers its attack by .2 and increases its defense by .1
Increases the shield energy and shield heat for the `Shield Refactor Module`, and reduces its shield generation multiplier from 25% to 20%.
Makes the Heliarch Drills mission chain slightly easier to start, by increasing the `random` from 8 to 11
It has been discussed in the Discord that the `Anti-Materiel Gun` was too cheap and powerful, and that the `Shield Refactor Module`'s downsides weren't enough to counter its boost to shields. This PR addresses both cases.
It was also mentioned in one of the responses in the feedback box for 0.10.3 that the Heliarch side of the Intros is harder to find or start than the Lunarium side. While the current …
=> Coalition Intros: a few balance tweaks

data/human/free worlds war jobs.txt
**Bugfix:** This PR addresses the issue reported by lazer_lit [on discord](https://discord.com/channels/251118043411775489/536900466655887360/1160874403366719499)
Some FW jobs were using `medical` instead of `Medical` as the commodity name. I couldn't find any other jobs using this lower-case variant, so I guess this is what was broken. I haven't really used this commodity thing, though.
Will be, if I have the time.
Same as above.
=> fix(content): Fix commodity categories in FW war jobs

data/governments.txt, data/map systems.txt
Prevent random Pug fleets from leaving Pug systems and jumping into human or Wanderer space by giving the two Pug governments travel restrictions to not travel to any location that isn't one of their own. In order to not have Pug fleets stack up in single systems and still appear to jump in and out, added three hidden "pocket dimension" systems that share a position with the main systems and act as viable jump destinations for Pug fleets.
No changes made to campaign Pug fleets because NPCs don't follow travel restrictions by default.
Resolves #8876.
Observed that Pug fleets still spawn in Pug systems. They sometimes jump out, but they never jumped out to an accessible system, meaning they're jumping to the hidden pocket dimension systems.
=> Prevent random Pug fleets from leaving Pug systems

source/AI.cpp
**Bugfix:** This PR fixes an issue reported by "Rocket Witch" on Steam: https://steamcommunity.com/app/404410/discussions/1/5374541530380822538/
Adds the missing checks that make sure that the asteroid is in fact inside the asteroid scanner range when targeting one.
not yet
=> Don't target asteroids past your scanner range

source/Preferences.cpp
Removed "Extended jump effects" from boolean settings. Before, it was saved twice: first with the correct value, then with the default value of true (1), which can't be changed as the old boolean setting is no longer connected with the UI. When loading such corrupted file, the game first loads the correct value and then overwrites it with 1.
yes.
=> fix(preferences): Save extended jump effects value correctly

data/coalition/lunarium intro.txt, data/governments.txt
**Bugfix:** This fixes something mentioned by @Arachi-Lover :
> Their swizzle is ghe FW one but I should change theirs to be the standard Coal one for the time being at least
> Kinda a dumbo they go about not disguised. Anyone want to farm a commit with that too be my guest
Adds a new government called `Lunarium (Hidden)` that has the same attributes as `Lunarium`, but uses the coalition swizzle.
None. (I haven't gotten this far yet, so I don't have a save file.)
~~Please don't make me play through the entire game to get one~~
=> fix(content): Fix swizzle of Lunarium ships training in human space

data/human/deep missions.txt
If I understand how to-offer works, `or` is redundant in this mission because there is only one condition inside it
=> micro-refactor: simplify to-offer

data/governments.txt
**Bugfix:**
Makes the "Quarg (Hai)" government hostile to the Kor Sestor so the Quarg ships that come to assist in the defence of Farpoint from the Alpha controlled Sestor ships will actually help.
Without this change, the Quarg won't help fight the Sestor. With it they will.
This save file can be used to verify the bugfix. The bug will occur when using continuous, and will not occur when using this branch's build.
[warp core.txt](https://github.com/endless-sky/endless-sky/files/12910975/warp.core.txt)
=> Make Quarg escorts in "Wanderers: Sestor: Quarg Help 2" actually help fight the Sestor ships

data/human/frontier jobs.txt
Because of the age of the mission (and the fact that it's never been offerable until recently), the mission uses outdated formatting, which sometimes leads to bugs. This PR makes the following changes to fix these bugs:
- The mission is now `invisible`, since it isn't a mission that the player can "complete". In lieu of this, the description has been removed.
- Rather than failing the mission in the `on accept`, the mission uses a deadline instead, as well as a `to complete`: `never` so that the mission NPCs persist through reloads.
- The mission uses `actions` to handle payments now. This was originally part of a change to stop the pirates from spawning if you win the pot fairly, but I'd like more opinions on the change first.
Additionally, the following tweaks have been made to the …
=> feat(content): Modernise and tweak `Small Pirate Gambling`

source/GameLoadingPanel.cpp, source/LoadPanel.cpp, source/MaskManager.cpp
**Bugfix:** This PR addresses an issue reported by "Atypical Swiftclaw" on Discord.
Masks for scaled sprites are currently only generated for sprites defined in the data files. If you happen to have a ship with a scale, but this scaled sprite doesn't appear anywhere in the data files, your ship will not have a collision mask.
This PR fixes this issue by scaling the mask only after the player has been loaded, and rescales any missing mask when loading a new save through the load panel. Previously generated masks that aren't used anymore are still being kept around, but that's not a big issue.
Used a save file with a scaled ship that isn't in the data files. Tried directly loading into it and loading it through the load panel. This PR fixes both cases.
[f …
=> Fix collision masks for scaled player ships

data/_ui/tooltips.txt, data/coalition/coalition outfits.txt, source/Ship.cpp
Reverts endless-sky/endless-sky#8968.
Resolves #9470.
#8968 was a nerf to heat damage, but it affected it in the wrong way, I think. As outlined in #9470, some ships, particularly the Kor Sestor, benefited disproportionately, and the balance of the wanderer campaign and heat weapons in general was negatively affected as a result. I felt that was a problem with #7042, and I agree that it's a problem with #8968.
=> Revert "feat(mechanics): don't disable cooling and active cooling when overheated"

.github/workflows/cd_release.yaml, changelog
Add an input to the release workflow to provide the version of the release instead of the one from GitHub that isn't accurate.
=> Fix release workflow binary names

source/AI.cpp
This PR adds a couple of improvements to the landing logic when hovering above star:
- If you're hovering above a planet as well, target the planet instead.
- Don't emit the `fail` sound if the player already has a target selected.
Tested the two scenarios above.
=> Planet landing improvements when hovering above a star

data/human/pirate jobs.txt
**Bugfix:** This PR addresses an issue reported on discord (I think)
EDIT: I couldn't find the bug report, so I made a new one.
Some of the pirate escort jobs had the distance in source, which was meaningless, rather than in destination, which appears like the intended spot. This way the missions offer 3-6 hops away from a pirate world, which prevents it from sending you halfway across the galaxy or to the same world (in which case you just reload your save)
Tested to make sure the fix worked.
This save file can be used to verify the bugfix. The bug will occur when using latest continuous, and will not occur when using this branch's build: [John Doe.txt](https://github.com/endless-sky/endless-sky/files/13065320/John.Doe.txt)
This uses the all content plugin but I have loaded it …
=> Fix pirate escort jobs

data/persons.txt
The Waverider `pers` ship has no thumbnail, so this line left in by accident causes an error message. Some other person ships don't have thumbnails, so it's fine without one.
=> fix(content): Remove `thumbnail` definition from Waverider

data/coalition/coalition jobs.txt
**Bugfix:** Job Description
Tweaks the job description for the `"Heliarch Investigate"` job to include mention of having to return to the `<origin>` to receive the payment.
Pointed out by MidnightPlugins on the Discord server, thanks!
=> Update Heliarch Investigate job description to mention return to origin

.codespell.words.exclude
**Bugfix:** This PR fixes a false positive in the spellcheck CI.
ES uses the aesthetic/aesthetics variant of the word, instead of the US-only esthetic/esthetic, as shown by the existing excludes. In #6416, this triggered a false positive on the word `aesthetically`.
N/A
N/A
=> fix(CI): Fix missing word exclude from the spellcheck CI

data/coalition/lunarium intro.txt
**Bugfix**
Adds a mention of having to return to `<origin>` (Zug) for the mission description for the Lunarium mission Combat Training 2.
Brought up by MidnightPlugins on the Discord server, thanks!
=> Update Lunarium Combat Training 2 description to include a mention of having to return to Zug

data/map systems.txt
Simply adds `departure 1000` to Dokdobaru (the system in Korath space with a ringworld), as I noticed it didn't have any ingame, seems https://github.com/endless-sky/endless-sky/pull/8026 missed this system.
=> Add missing departure distance to Dokdobaru

data/human/jobs.txt
As mentioned in [this post](https://steamcommunity.com/app/404410/discussions/0/3881598799636016217/), Stranded Field Trip shows up far too frequently for what should be a freak incident, reaching 70% offer rate in a stock Bactrian. This PR reduces the offer rate of the job to 1/10th its original, with the payment being increased to compensate.
=> feat(content): Reduce offer rate of Stranded Field Trip

data/human/weapons.txt
**Balance:**
Firing fuel is increased from 15/sec to 24/sec
Heat DPS is reduced from 9000 to 7500
It's still overpowered. 
The nerf in #7606 was evidently insufficient, and as was discussed on #9470 and #9495 the Flamethrower is still too strong as an applier of heat damage.
I've reduced the heat DPS and increased the firing fuel here. I think 9000 heat damage was simply too much, and hence that does need to be reduced, but where possible I'd like to lean more in the direction of increasing its downside (the firing fuel) rather than reducing the strength of its upside (the heat DPS), since that's a better approach for variety than doing the reverse.
=> Feat(balance): nerf the Flamethrower again

data/hai/hai reveal 5 philosophers.txt, data/hai/hai reveal 7 epilogue.txt, data/human/culture conversations.txt, data/human/sales.txt, data/human/variants.txt
**Bugfix:** This PR fixes inconsistent uses of the Syndicate's security forces.
According to Derpy, it is called Syndicated Security, not Syndicate Security.
Most of the changes here are pretty simple. The two scary ones are the outfitter and the mission name.
The outfitter is only used in a locked part of HR (iirc), so it shouldn't be too bad. The mission, however, is available as-is, so renaming it might cause it to trigger again. (Maybe I should add a condition for the old mission not being done, or just not rename it?)
N/A
N/A
=> fix: Syndicate Security -> Syndicated Security

data/human/deep jobs.txt, data/human/human missions.txt, data/human/names.txt, data/human/near earth jobs.txt, data/human/paradise world jobs.txt
This PR:
* updates a job for Tycho Crater Shipyards which had a different description to the rest
* makes the name of that electronics company on Vinci consistent; it's now Polymath Nanoinstruments instead of Vinci Nanocircuits/Cyberacme (the reference is now slightly more obvious); it was suggested by Azure sometime last year and I forgot lmao
* separates the Deep's science ship names from from Deep Sec ship names; D.R.S. stands for Deep Research Ship (thanks mOctave for suggesting the name). It'd be confusing if the Deep used D.S.S. for both Deep Security Ship and Deep Science Ship.
=> fix(content): Consistency fixes in text, adjust Deep's science ship names

data/coalition/heliarch intro.txt
**Bugfix:** This PR addresses an issue reported on [Steam](https://steamcommunity.com/app/404410/discussions/1/3880473965436854772/)
The heliarch expedition 5 mission now gives `assisting heliarchy` as it was supposed to do. The heliarch license mission gives a warning if you are assisting the lunarium about why you can't join the heliarchs and stays in your jobs list until you are actually able to join. 
Made sure both lunarium and coalition sides gave and removed the assisting conditions properly after this change. 
This was the "save file" given:
If someone has an actual save file, that would be helpful.
=> Fix heliarch intro

data/map systems.txt
I was doing a silly little project and I noticed some systems were missing their proper locational attributes- two Coalition Saryd systems, and two Pirate Core systems. 
This just adds attribute "saryd" to the two systems that were missing it, and attribute "core" to the two systems that were missing it.
I haven't got confirmation whether Misam and Atik are excluded from the Core attribute on purpose.. As it stands, if Misam (or indeed any other currently Syndicate or Pirate system) has a different government than Pirate then there's the possibility that a "defend against pirates" spaceport mission will fire- that mission for the Core assumes that the planet has a Syndicate defense fleet. This isn't an issue right now, but if #8752 goes through that mission will need to be adjusted to …
=> fix: some attributes in Coalition, Core missing

source/Ship.cpp
**Feature:** This PR implements the feature request that's been bugging me for a long time
Right now the only use case of crew equivalent is having drones affect your reputation when they get destroyed for instance, or making some ships count more than what their crew count would show in terms of the reputation hit.
This expands it to anything, meaning one can make a ship matter for 1 or no crew if they feel like it. As suggested by @Amazinite this was made explicit by having to use the `"use crew equivalent as crew"` attribute change the old behavior.
n/a
I dont have anything in mind right now, but this always felt too limiting to me
n/a
n/a
n/a
=> Feat: add a new `"use crew equivalent as crew"` attribute

data/human/culture conversations.txt, data/human/human missions.txt, data/map planets.txt
**Bugfix:** This PR fixes some erroneous hyphens/dashes/whatevers.
Headshake is one word according to Merriam-Webster, though the wikipedia page has it as two words. The `head-shake` usage doesn't look common either way (though it is grammatically correct).
`Flyby`, `subtropical` and `stained glass` were also corrected to their standard forms.
N/A
N/A
=> fix(typo): Fix hyphen usage

source/Engine.cpp, source/Engine.h
**Bugfix:** This PR fixes #9520
The zoom value was different in a single frame when landing zoom was on and the user was zooming in or out. 
Tested the scenario described in the issue. The screen no longer jumps around.
=> Fix zoom mismatch with landing zoom and zooming in/out

source/MapDetailPanel.cpp, source/MapPanel.cpp, source/MapPanel.h, source/MissionPanel.cpp, source/MissionPanel.h
**Feature:** This PR adds the "Selected system: X (Y jumps away)" element that is currently only on the Missions panel to all map panels.
The ports map panel before:
The ports map panel after, note element in the top center of the screen:
I tested by going through each panel and seeing if the element was correct.
N/A
N/A
=> Add the "Selected system: X (Y jumps away)" element to all Map Panels

data/coalition/coalition missions.txt
**Bugfix**
This PR adds a goto, along with its corresponding label, to skip the 'pirategood' response when not choosing that option.
Before when selecting the option,
`"There are many independent worlds that are not ruled by one singular government. Some groups there support piracy, but others are peaceful."`
the text for Heliarch censoring you would be displayed erroneously. The new goto should skip this if you don't choose that option.
I might have made a mistake with the syntax, but it looks good from what I've seen in the rest of the file.
=> (Bugfix)(Coalition) Added missing goto+label to the 'Saryd University Lecture' mission

data/human/human missions.txt
**Bugfix:** This PR addresses an issue reported several months ago that nobody bothered to fix. 
Reduces the depth of the player's ship in "Dangerous Games 2" to 3/500. Water pressure is much higher than air pressure, so currently this means the player's ship can withstand extreme pressures, which doesn't make much sense. As this is essentially flavor text, the lore shouldn't be that the player's ship can go 25 km underwater. This ship can still apparently withstand a pressure of 15 atm, but that's a lot better than almost 27 times the pressure of Venus.
EDIT: Also, for the record, the deepest part of an Earth ocean is around 11 km deep.
EDIT 11/14: I switched from a depth meter to a pressure gauge as requested. The depth is still about 250 m.
EDIT 11/16: I further reduced the depth to …
=> Make depth of spaceship in dangerous games 2 more reasonable

tests/integration/config/plugins/integration-tests/data/tests/tests_afterburn_flight.txt, tests/integration/config/plugins/integration-tests/data/tests/tests_capture_override.txt, tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt, tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_model_condition.txt, tests/integration/config/plugins/integration-tests/data/tests/tests_framework.txt, tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt, tests/integration/config/plugins/integration-tests/data/tests/tests_save_load.txt, tests/integration/config/plugins/integration-tests/data/tests/tests_shipyard_outfitter_missions.txt, tests/integration/config/plugins/integration-tests/data/tests/tests_store_outfits_on_take_off.txt, tests/integration/config/plugins/integration-tests/data/tests/tests_take_ships.txt
This PR fixes an issue where sometimes the integration tests would fail because the flagship would not land. This is because, if a destination planet is not specified and the flagship hovers above an uninhabited planet or a star, it will try to land there instead of the actual inhabited planet. By specifying a destination planet, it will always land there.
A bit hard to test but the integration tests should fail less often.
=> Add a landing destination to every integration test

.github/workflows/projects_check.yml
The check CMake CI job wasn't running when the only thing changed was an integration test.
=> Run CMake check when only the integration tests were changed

source/BoardingPanel.cpp, source/ClickZone.h, source/HailPanel.h, source/Hazard.h, source/MapDetailPanel.cpp, source/MenuPanel.cpp, source/MissionPanel.cpp, source/OutfitterPanel.cpp, source/PreferencesPanel.cpp, source/SpaceportPanel.cpp, source/comparators/BySeriesAndIndex.h, source/opengl.cpp, source/text/WrappedText.cpp, source/text/WrappedText.h
**Chore:** This PR removes a number of unused include directives. Also fixes a typo in a variable name; hopefully that won't cause conflicts.
I mostly removed include directives that were entirely unused; I didn't go out of my way to check for transitive includes and stuff. Duplicated includes are cheaper than unused ones anyway.
WrappedText had a private member called `longesLineWidth`; that has been corrected to `longestLineWidth`.
Still compiles.
N/A
=> chore(code): Remove unused includes

source/EscortDisplay.cpp
Set a limit for escort heat bars so that they no longer overlap with the message log when a ship is overheated.
Before:
After:
=> fix(ui): Limit heat meter length on escort HUD

data/governments.txt, data/quarg/quarg missions.txt, data/quarg/quarg.txt
Replaced the "Quarg Ships Atrocity" placeholder mission and instead added Quarg ships to the appropriate atrocity lists.
That means detection chance depends on the planet's `security` value (with the mission it's always 100%). Also, the native atrocity conversation is triggered before missions (currently, you can talk to the Quarg in the First Contact and then get arrested).
As the "quarg imprisonment" conversation is no longer used in any mission, the `die` endpoint is not needed.
Landed with a Quarg flagship on Echo, the death sentence conversation was activated.
=> Replace the Quarg atrocity mission with proper atrocities

source/PlayerInfo.cpp, source/Politics.cpp
**Bugfix:** This PR addresses a bug reported on [Discord](https://discord.com/channels/251118043411775489/536900466655887360/1174359125984026644) by @ziproot
Fines are now applied before cargo is pooled. Before this change, player ships inspected by planetary security had their cargo holds empty (because all cargo had already been moved to the common pool).
Also added a planet check to the core function responsible for fining.
Tested with some illegal mission cargo and the Nerve Gas.
See the original report on Discord.
=> fix(mechanics): Apply planetary security fines for illegal cargo

docs/readme-cmake.md
**Bugfix:** This PR fixes #9450 
Improves the CMake docs for Linux a bit:
- Mention the minimum version needed for Debian/Ubuntu
- Add gles preset mention
- Mention `cmake --list-presets`
- Add a short sentence about needing to install additional dependencies when building from source.
=> Improve the linux CMake instructions a bit

tests/integration/config/plugins/integration-tests/data/tests/tests_capture_override.txt
Fixes the capture override integration test . It seems like there was some sort of race condition where the boarding panel gets closed by accident. This PR fixes this issue by simply removing the unnecessary panel that gets shown when the mission is offered.
Ran the integration test one hundred times to make sure that there isn't any problems left. CI should also succeed.
=> Fix capture override integration test

.github/path-filters.yml, tests/integration/IntegrationTests.cmake, tests/integration/RunIntegrationTest.cmake
Running the integration tests in a loop (by passing `--repeat` to ctest) was broken and caused failures for some integration tests. The reason was that the config folder was not properly cleaned between individual runs, and the old files would conflict with the integration test.
Ran the integration tests on `--repeat` in debug mode and verified that the config environment is properly cleaned up, and that the integration tests stop failing.
=> Allow ctest to repeatedly run integration tests

.github/pull_request_template.md
The PR template currently has four sections: content, bugfix, balance, and feature.
Each of these sections has a series of subsections. With the idea being that a user should choose one section and then fill in each subsection, which should be relevant to that section.
In practice, there is a lot of overlap in terms of subsections between each section.
For example, all but the bugfix section begin with a "Summary" subsection. The bugfix section beginning with a "Fix Details" subsection, but this is essentially the same as the summary subsections of every other section. The only difference being the name.
All but the feature section have a "Save File" subsection, however, it is perfectly possible for a feature PR to benefit from the inclusion of an appropriate save file …
=> Condense PR template

tests/integration/config/preferences.txt
#9515 added a new help message, but it wasn't disabled in the integration tests, which made them fail because it showed the help message in the middle of the test.
The "Sell X ships" integration tests succeed with this PR, and fail without. ~~CI will also verify~~ guess not.
=> Don't show 'shipyard' help message for integration tests

data/human/human missions.txt
The mission name of the Return to Paradise mission has a full stop (which generally should not happen), and the destination is not necessarily clear from the dialogue that the player gets. So I've added some paragraph breaks and made the lady repeat her destination.
~~I purposely make mistakes in my PRs to inflate my PR count in the future. On my way to becoming one of the top 15 contributors!~~
=> fix(content): Update parts of Return to Paradise

data/human/human missions.txt
**Bug fix**
This PR adjusts the wording and mission syntax for some of the "Early south missions" content in #9097, and fixes a `branch` node that referred to a missing mission that was renamed.
=> fix(content): "Early south missions" adjustments

source/PreferencesPanel.cpp, source/PreferencesPanel.h
While talking with RisingLeaf, I found out that the preferences and plugin panels didn't have keyboard navigation :(
I've added it in :)
=> feat(ui): Keyboard Navigation for Preference & Plugin Panels

source/PreferencesPanel.cpp
Stops the changing of the selected item via keyboard from jumping back to the last keyboard-selected item in the plugins.
=> fix(ui): Better switch from mouse to keyboard in plugins menu

data/coalition/coalition jobs.txt, data/human/human missions.txt
**Typo Fixes**
This PR fixes three instances of payments being referred to as `you see <payment> has been added to your account` or similar, which would produce `you see 830 credits has been added to your account`.
I changed a grand total of +6/-3 characters. The offending lines now read "have" instead of "has"
I haven't tested this. I'm going to hope that reviews are good enough :)
=> Fix(content): Minor typo fixes in payment reporting

.github/workflows/cd.yaml, .github/workflows/ci.yml, .github/workflows/projects_check.yml, .github/workflows/steam.yml
Commits are currently cancelling previous commits' runs just like PRs are. Now that the integration tests run much quicker, there isn't really a reason to do this anymore. Currently the commit list has a lot of Xs due to cancelled runs which isn't great because it makes it harder to pinpoint actual failures versus just cancelled runs.
This continues to cancel old PR runs.
Tested both commits on the main branch and PRs to it to verify that the behavior works.
=> Don't cancel commits to the main branch

.codespell.exclude, data/human/deep missions.txt
**Bug fix**
This PR addresses some issues in the Skadenga mission string.
1) Addresses typos in Hjlod's affect during the Skadenga "bad end" followup missions:
* She uses `vho`, which doesn't make sense, because the `w` makes an `h` sound in `who`, so changed it back to `who`. You can see similar usage of `w`s when she correctly pronounces words like `now` and `know`.
* Two instances of her using `will` instead of `vill`, which stuck out.
* One instance of her using `what` instead of `vhat`, which also stuck out.
* One instance of her using `was` instead of `vas`, which, again, stuck out.
2) Addresses bug where First Last is told to take Skadenga mourners from Windblain... to Windblain, in the `on offer` dialog. See below screenshot. 
3) Removes male title "Ser" from Skadenga and Skaldgar …
=> FIX: Hjlod use of 'w' in places, plus stopover name in mission

data/_ui/interfaces.txt, source/TradingPanel.cpp
**Feature**
This PR addresses the problem described in issue #9473
Pretty much changed the keys of Buy All and Sell All:
- Buy All 'B' -> 'u'
- Sell All 'S' -> 'e'
in `TradingPanel.cpp`
And also modified `data/_ui/interfaces` to underline the `u` and `e`
Note that `Alt` is pressed in all images.
| Original | After Changes |
|----------|---------------|
|![before, alt sell all](https://github.com/endless-sky/endless-sky/assets/63902100/6fbf9e5c-b622-4db7-bfce-82ef4eff5b17)|![after, alt sell all](https://github.com/endless-sky/endless-sky/assets/63902100/27c4eab9-6caf-47af-9bd6-f922c17154f0)|
|![before, alt sell outfits](https://github.com/endless-sky/endless-sky/assets/63902100/3f39d474-e576-4522-9355-d23dcdaa43c3)|![after, alt sell …
=> feat(ui): Change Shortcut Key for Buy/Sell All

data/human/campaign events.txt
**Balance**
Added an event after the typhoon becomes available, which expands the sale of both the torpedo and its launcher to some worlds with major navy shipyards and outfitters (specifically the `lovelace advanced` outfitter, which is present on Shroud, Ada, Hermes and Geminis, and is also the only outfitter that sells the Navy's Armageddon Cores) a short while after it begins being sold in the Deep.
Launcher sales before:
Ammunition sales before:
Planets to which sales are expanded:
Any post-FW save file will work. The sales will update after a delay of 120 days.
=> Have Typhoons sold on planets with major Navy shipyards/outfitters, rather than only in the deep.

data/human/free worlds 2 middle.txt
Read title,
replaced 
the "event: fw suppressed Bloodsea" which is not used anymore
with "event: fw suppressed Greenrock"
if you want more description tell me
=> Fix: FW Bloodsea 1.1 Mission oversight, outdated event label

source/Mask.cpp, source/Ship.cpp
As discussed on discord:
WithinRing only checked if the circle intersected the outline, this allowed for bugs where floatsams bypassed the outline if they moved too fast.
This was fixed by adding a Contains check to the function if the inner radius of the circle is less than the radius of the outline.
As visible in this graphic the inner edge of the ring will always be in the outline, if the inner radius of the ring is smaller than the radius of the outline.
Blue = inner radius of ring
red = radius of outline
triangle = outline
=> Fix(code): Add a contains check to Mask::WithinRing

data/human/free worlds 1 start.txt
Picked up this really cool game called Endless Sky and started helping these green Free Worlds dudes, noticed this missing punctuation mark.
~~I thought I fixed this in #7647. The typo was in fact a few lines away and I didn't notice it.~~
=> fix(typo): Add missing punctuation in FW

data/human/free worlds 1 start.txt, data/human/free worlds 2 middle.txt
**Bug fix**
I went to Bloodsea for the mission `"FW Bloodsea 1.1"` and got the dialogue labelling me an "invader" when I didn't attack Greenrock with Tomek in `"FW Pirates: Attack 2"`. It turns out that that branch occurs if you have the event `"fw suppressed Greenrock"`, which always occurs no matter what you do. This dialogue only appears if you have done `"FW Pirates: Attack 2"` now.
[Tricia McMillan~3016-10-23 Bloodsea condition.txt](https://github.com/endless-sky/endless-sky/files/13840121/Tricia.McMillan.3016-10-23.Bloodsea.condition.txt)
Here's my current save originating from New Tibet. ~~Yes, it's a Hitchiker's Guide character. Also don't judge my Marauder Falcon.~~
~~Will be done. Pinky promise.~~ Of course it works.
=> fix(content): Avoid mentioning that the player invaded Greenrock with Tomek when they did not invade Greenrock

data/wanderer/wanderers start.txt
This PR addresses the bug/feature described in issue 
The Wanderers wonder what the humans want from from them, through Sayari's translation, that they send a representative.
From both the Wanderers and Sayari, a Hai, they are inquiring the intentions of a third race, the Humans.
The appropriate wording should be along the line of "What do the Human want from us?".
I don't think they would refer to humans as "Human beings", because it emphasises an individual. The Wanderers are inquiring about humans as a collective whole.
=> "What human beings want" to "what humans want"

source/Engine.cpp
**Bug fix**
This PR addresses a bug uncovered during testing of #9396, but it turns out to be a bug in vanilla.
If the player has an available mission to an unexplored system, the location and name of that system is revealed to the player. This is the case even if the player has no known route to the system. Should the player have the means to select this system and add it to their travel path and then take off without accepting the mission, the system will remain in the player's travel path despite the fact that they no longer have the knowledge to see it.
To address this, I've added to the current travel plan validation check in Engine::Step. Instead of just checking that the next jump is doable, check that all jumps in the travel plan are visible.
Available mission to Caph. Select the …
=> Ensure that all steps of the player's travel plan are visible

data/gegno/gegno intro missions.txt, data/governments.txt, data/map planets.txt, data/map systems.txt
As #8750 is quite a bit of extra content as-is, I've split off the changes that PR makes to base Gegno content to this one as they are changes that should be changed regardless of the additional content. These changes include:
- A few word changes in existing missions.
- A few data file space consistency fixes.
- A few fleet frequency edits.
- A few reputation edits to missions.
- Edits to the two main Gegno governments that more properly reflect them. (I.e., care less about destruction or disabling, more about stealing and capturing.)
- Adds/adjusts required reputation for Gegno civilian planets for the upcoming content.
- Removal of an npc who's purpose was shifted elsewhere in the upcoming content.
=> feat(content): Gegno Intro Content Adjustments (separated from #8750)

data/remnant/remnant news.txt
**Bug fix**
The "remnant cafeteria" news item has no "location" in its definition. This means it is never actually shown. From the wiki:
> `location` (optional): A [location filter](https://github.com/endless-sky/endless-sky/wiki/LocationFilters) that is used to identify on which planets this News message can appear. If not provided, or removed, then this news source will not be displayed anywhere.
And, yes, labelling it as "optional" even though the thing won't actually work without it is a bit strange, I'm assuming it's because it will not be considered malformed if no location is provided, as you can reasonably add, remove, or update the location filter through events. Though, this doesn't appear to be the intention here. No such events exists and the message in this news item was …
=> Make the "remnant cafeteria" news item show up

data/coalition/coalition jobs.txt
**Bug fix**
This PR alters the distances for the `stopover` and `destination` of the Evacuate Lunarium jobs, to prevent overlaps where the stopover is the same world as the destination.
This was reported on the steam forums by MeninliteZ: https://steamcommunity.com/app/404410/discussions/0/4034728517981281987/
=> (fix) Change Lunarium rescue jobs distances to prevent overlap

data/kahet/kahet missions.txt
Requested by Amazinite on the Discord.
Changes the Quarg conversation in their Ringworld Debris mission to be more vague about the fate of the destroyed ringworld.
=> Update Ringworld Debris Quarg Conversation

source/Messages.cpp
**Bug fix**
This PR addresses the bug/feature described in issue #9674
Adds a missing check otherwise you get a nullptr
Launched on the same type of machine as in the issue, but that should not be related
=> Fix(code): Message Log, check if a message to compare exists

tests/integration/RunIntegrationTest.cmake
#9246 was merged with failing integration tests because it wasn't clear from the error message what the problem was. Turns out it was a segmentation fault that didn't get caught by the output filter, so it was not shown to the user.
This PR emits the error reason in addition to the application output when an integration test fails. It would look like this for a segmentation fault:
```
Test project /home/user/endless-sky/build/linux
1/41 Test  #1: Abort Take Off On Excess Outfits In Cargo Warning....***Failed    4.38 sec
CMake Error at integration/RunIntegrationTest.cmake:15 (message):
Integration test failed with 'Segmentation fault':
```
Without this PR, the `'Segmentation fault'` part is not shown and thus it's impossible to know what caused the failure.
Deliberately added a segfault to …
=> Output the reason why an integration test failed if it failed because of a segfault

data/_ui/tooltips.txt, source/main.cpp
**Bug fix**
as in: #5177
ES only recognizes the caps lock while the game window is in front. This can lead to a situation where you switched windows, released caps lock, switch back and the game is still in fast forward.
I don't think this behavior is intended , so instead of only recognizing the key press, fast forward gets now updated per frame with SDL_GetModState , if it is on capslock
Yes
N/A
=> Fix(input): recognize release of caps lock(fast forward) even when game window is not in front.

data/gegno/gegno intro missions.txt
This PR temporarily addresses the bug/feature described in issue #9611
This PR introduces a temporary fix suggested by @warp-core to the Gegno Intro where in which if the player has not met the Quarg, the intro comes to an abrupt hault. The "First Contact: Quarg" requirement has been moved to the first Gegno mission.
As the Quarg conversation originally requires you having done the Quarg first contact in human space, if you skip out of human space to do the new content, you run into a wall and the mission series stops here until you go back to human space and meet the Quarg. Although this is an edge-case, it still can happen, and having no missions is preferable to broken missions.
Although this is a solution, in the future I wish to explore Quarg first contact missions, and instead of …
=> fix(content): Disable Gegno Intro if player has not met the Quarg

data/_ui/tooltips.txt
Added a tooltip for the "View message log" control in Preferences I forgot about in the original message log PR.
=> Add a tooltip for the message log

data/human/human missions.txt
**Bug fix**
This PR addresses a bug that I found when looking at the hai wormhole warning mission.
The hai wormhole warning mission checks if "Hai Leaks Response 1" is offered, even though that mission doesn't exist. This ~~removes that unnecessary check~~ replaces it with a check that actually works in the current version of the game.
Tested to make sure Hai Leaks Response 1 didn't exist.
[Test Pilot~Hai Wormhole Warning.txt](https://github.com/endless-sky/endless-sky/files/13994228/Test.Pilot.Hai.Wormhole.Warning.txt)
=> fix(content): Fix hai reveal check in "hai wormhole warning"

source/Ship.cpp
Sometimes (but not directly after a reload) when taking off the planet, my ship's flight and facing directions seem to differ randomly.
I think this may be caused by https://github.com/endless-sky/endless-sky/commit/ab87988b41db166d6c6c68380eada99258c85db2 replacing angle assignment with a function that adds the angle to the existing value; if the previous ship angle was non-zero, it corrupts the new value.
Departed a few times with and without the patch.
N/A
=> fix(mechanics): Always face the flight direction on takeoff

source/Engine.cpp
Fixed an edge case when the Engine is loaded with Landing zoom enabled and then, before departing from the planet, Landing zoom is turned off. This results in broken zoom until you manually zoom in/out.
Tested these cases: 
- Landing zoom on -> Engine loaded -> takeoff,
- on -> Engine -> off -> takeoff,
- off -> Engine -> takeoff,
- off -> Engine -> on -> takeoff.
Haven't noticed any buggy behavior.
N/A
=> fix(ui): Reset zoom modifier if "Landing zoom" is off

source/Outfit.cpp
**Bug fix**
This PR addresses the bug/feature described in issue #8562 wherein the ship "add attributes" property could not add licenses.
This works now:
```julia
ship "Base Name" "Variant Name"
add attributes
licenses
"License Name Goes Here"
```
- fixes #8562
```julia
ship "Archon" "Navy Archon"
add attributes
licenses
Navy
description `"Lieutenant, are we prepared for the Third Alpha War?"`
description `	"Yes, sir. I think our new ships are up to the task."`
```
1. Custom ship variant with fancy stats requires a license.
2. One faction will sell a ship to anyone. Another faction requires a license to buy the same ship.
1. Put this in [data/add-attributes-licenses.txt](https://github.com/endless-sky/endless-sky/files/13972226/add-attributes-licenses.txt)
2. Depart and land anywhere with …
=> Apply license definitions in variants

data/remnant/remnant 1 introduction.txt
**Bug fix**
This PR addresses the bug/feature described in issue #9567
This changes the `on visit` dialog to `generic missing stopover or cargo`, so that if the player lands on Nenia without the necessary cargo being present (i.e. it was on one of their escorts that are not in the system), it gives the appropriate dialog and informs the player why the mission wasn't completed.
Thanks to @bMorgan01 and Amazinite for pointing the issue out and providing a solution, respectively.
0
=> Fix "Visit void sprite planets" mission dialog

data/human/variants.txt, source/Outfit.cpp
This PR adds a mining variant of the Nest that is missing from #9621, pointed out by @SomeTroglodyte.
=> feat(content): Add Missing Nest Mining Variant

source/Engine.cpp
**Bug fix**
Thanks to @alexrovw for reporting this on Discord and in #9717.
The flagship pointer is passed to "Engine::MoveShip" without null-checking, and that method assumes the pointer it is given isn't null.
This PR adds a check that the pointer isn't null.
Attempt to capture a ship that has too many crew for me. Lose. Close the boarding panel. From faad2481691b1890844131ddd67ec6a60cf54c75 onwards, without this PR, the game crashes. With this PR, it doesn't.
[on encounter segfault test~3013-11-22.txt](https://github.com/endless-sky/endless-sky/files/14036930/on.encounter.segfault.test.3013-11-22.txt)
Take off, board one of the disabled ships. Attempt capture. Fail. Close the boarding panel. Crash.
=> Fix a segfault on losing your ship during boarding

source/Outfit.cpp, source/Outfit.h, source/Ship.cpp
**Bug fix**
This PR addresses the bug/feature described in issue #9722.
This is one fix I have. An alternative is #9723.
In 9d8dfc4, `Outfit::Add` will add all the licenses from the other Outfit it is given, as well as all the attributes. This was done for the purpose of copying licenses added to a ship variant via `add attributes` into that ships `baseAttributes` object, instead of discarding them. It has the side effect of also copying the licenses from any outfit added to a ship into its `attributes` object, where the ships base attributes and the attributes of all its outfits are pooled together. It also doesn't maintain uniqueness of the lements of the `licenses` vector. The shipyard looks at the licenses required by the ships `attributes` object, so it ends up seeing all the …
=> Fix outfit licenses propagating onto ships (option 2)

.github/workflows/steam.yml, changelog, io.github.endless_sky.endless_sky.appdata.xml
The Steam release workflows previously used a test parsing script that has since been deleted.
This PR updates that workflow to test parse the same way the CI test parses (I hope).
Derpy'll test it.
=> Fix Steam workflow test parsing

CMakeLists.txt, credits.txt, endless-sky.6, resources/EndlessSky-Info.plist, source/main.cpp
Like #9490 and #9387, etc, but for 0.10.6-alpha this time.
=> Update version numbers for 0.10.6-alpha

.github/ISSUE_TEMPLATE/bug-report.yml
This PR is inspired by #9729.
Adds "GoG" as an option in the drop down menu for "game source" in the bug report issue template, so users who got the game from GoG don't need to choose "other" and then enter "GoG" manually.
No
=> Add "GoG" as an option for "Game source" in the bug report issue template

data/map systems.txt
This PR reduces the spawn rate of the Astral Cetacean to a little under half of what it is currently. My original intention for this lifeform is to be super rare, where during your first time exploring the Vyrmeid region, it, for the most part, would be unlikely you see one. As time has passed and I've observed the frequency at which players run into them, I feel as though the spawns can be cut back to truly uphold their mysterious and rare natural spawns (as well as cutting them back the further away from some systems).
I have plans in the future for the player to revisit the area, so there still would be opportunities in which the player returns and runs into one (or perhaps a mission or special condition that explicitly spawns one outside of …
=> feat(content): Reduce the spawn rate of Astral Cetaceans

data/gegno/gegno intro missions.txt
The modified message exists twice, once if the player knows the Vi
already, once if not. But both copies were identical. This fixes
the second copy to say 'alien' instead.
=> Fix reference in 'First Contact: Gegno Vi'

data/human/boarding missions.txt
**Bug fix**
Adds spaces to reward phrases in boarding missions.txt to prevent word merging
=> Fix typos in boarding missions.txt

data/human/weapons.txt
**Bug fix**
This PR addresses the bug described in https://steamcommunity.com/app/404410/discussions/1/4204741842670747847/
Aside from AM turrets and the tractor beam, which are automated, all turrets in human space require crew. The Javelin and Gatling Turrets currently don't require crew, but they should. Added one required crew to each. May no variants that you guys made become undercrewed.
=> Give required crew to the Javelin and Gatling Turrets

data/human/paradise world jobs.txt
**Bug fix**
This PR addresses the a bug found on Discord by ziproot.
The mission incorrectly refers to `war begins` instead of `event: war begins` in its `to offer` node, which means that the job is offered even after the war begins.
Alex Rov also pointed out that the additional `and` was not necessary, because I don't understand logic.
=> fix(bug): Update conditions in Gemini Shipyards jobs

data/human/ships.txt
**Balance**
Adding back the torpedo launcher (and torpedoes) that were removed in #6260 and reducing the battery from an LP144a to an LP072a to make space. It doesn't really need the higher energy capacity and 3 torpedo launchers is just wrong.
=> Give Dreadnoughts back their fourth torpedo launcher

source/ShipInfoDisplay.cpp
**Bug fix**
The padding between the energy/heat table and the installed outfits list is too small in the shipyard and outfitter.
First, the additional height of the "attributes" section added by the category label was not accounted for.
The padding for player owned ships is then smaller still because the "saleHeight" is not counted properly.
I'm aiming for the padding to be the same for player owned ships and ships available for sale in the shipyard.
panel | before | after
-- | -- | --
shipyard | ![image](https://github.com/endless-sky/endless-sky/assets/20605679/4822852b-e371-43e7-8f08-e1cde8272c01) | ![image](https://github.com/endless-sky/endless-sky/assets/20605679/dab8438c-d3a1-4d3b-88e5-9cc176bac91a)
outfitter | ![image](https://github.com/endless-sky/endless-sky/assets/20605679/7e1c …
=> Ship info display fixes

source/ShopPanel.h
**Bug fix**
There is no method definition for this declaration. It looks like the declaration is left over from when #9515 was being worked on.
It still builds without this declaration.
=> Remove ShopPanel::Search declaration

data/human/campaign events.txt
**Content (Planet Descriptions)**
This PR adds new lines to planets that used to hold Navy bases but were abandoned as a result of the Checkmate plan.
The text mentioning the new Navy bases that are built in New Iceland and New Austria as a result of the civil war is removed in Checkmate once you begin to take more Republic systems. I've added lines mentioning these bases back as I thought that it didn't seem right for them to simply disappear.
Also fixes the fact that New Austria's decription loses its indented lines when it is captured in `fwc capture menkent`, and New Iceland loses the line `Many of the inhabitants wear dust masks to avoid letting the particulate matter from the volcanoes accumulate in their lungs` in `fw southern expansion` since there was no apparent reason for it …
=> feat(content): Mention the presence of abandoned Navy bases on planets during Checkmate

data/bunrodea/bunrodea outfits.txt
**Balance**
This PR addresses the issue described in #8559
I believe the original intention of the Lasher Pistol was for it to have flipped stats to the Korath Repeater Rifle. The description didn't actually make sense with that intention, though.
I've changed the stats so that they are now more in line with the description. I've also massively dropped the price because there's no good reason it's that high.
=> Make Lasher Pistols more defensive than offensive

.github/ISSUE_TEMPLATE/feature-request.yml
This PR addresses the bug/feature described in issue #9233
As noted in the linked issue, we currently have a "Feature Request" template for requesting new features, but there's no immediately obvious location to ask for balance changes, or changes in general. A feature request sounds like the creation of something new entirely, although not all uses of the feature request template are actually for new features.
This PR renames the feature request template to "Feature/Balance/Change Request", making it more clear that this is the general template that should be used for anything that doesn't fall under any of the other templates.
I've renamed this template to cover all three cases instead of having a new template for each given that the templates would likely all be …
=> Rename feature request template

source/MenuPanel.cpp
**Bug fix**
Currently, if you set the credits scroll speed to 0 (with the arrow keys) and make a new instance of the menu panel (enter ship and return to the menu), the credits won't appear.
With this fix, the 0 scrolling speed is reset to the default value (1) on panel construction.
Tested with the above steps; doesn't seem to break anything.
N/A
=> ui: Fix credits not showing if speed is set to 0

data/human/campaign events.txt, data/human/free worlds 3 checkmate.txt
**Bug fix**: This PR addresses the bug/feature described in #6949
Makes uninhabited systems switch to associated gov'ts for the events (`tarazed neutrality`, `southern expansion`, `northern expansion`, `fw expanded cut`, `fw tarazed joins`) and FWC-specific events (`tarazed republic`).
I might have missed some. Testing should tell me whether I have ~~when I do it.~~
Soon™
None yet.
Will do.
=> fix(content): Uninhabited systems & Kaus Borealis switch sides throughout the FW campaign

source/HailPanel.cpp, source/HailPanel.h
**Bug fix**
This PR addresses the bug/feature described in issue #9766
Ships and planets in the hail panel should now be properly animated.
No.
=> Render animated sprites in the hail panel correctly

data/sheragi/archaeology missions.txt
**Bug fix**
This PR addresses the bug described multiple times on Discord.
EDIT: Also issue #4616 
I have given the timer ship `ramming` so that its AI is back to what it was before.
Tested how long the timer ship took. It's reasonable now.
[Taiho_Heihachiro~timer.txt](https://github.com/endless-sky/endless-sky/files/14226775/Taiho_Heihachiro.timer.txt)
[Taiho_Heihachiro~visible timer.txt](https://github.com/endless-sky/endless-sky/files/14226776/Taiho_Heihachiro.visible.timer.txt)
Thanks TheLastShogun for providing the save.
=> fix(balance): Fix the timer ship AI

data/hai/hai ships.txt
**Bug fix**
This PR addresses a typo reported on Discord by Arachi
I moved an apostrophe.
=> fix(typo): Move apostrophe in Solifuge description

data/coalition/lunarium intro.txt
**Bug fix**
This mission has 2 "on completes". This moves the contents of the second into the first and removes the second.
No
=> Remove second "on complete" in a Lunarium mission

data/_ui/interfaces.txt
**Bug fix**
This PR addresses the bug/feature described in issue #9818
Adds the missing colors for messages.
=> fix(ui): Add missing message colors

data/_ui/interfaces.txt
**Bug fix**
This PR addresses the bug/feature described in https://github.com/endless-sky/endless-sky/pull/9831#issuecomment-1947593173
As mentioned in the linked comment, these message types previously used all white and the colours used in the log were deliberately different. This restores the colours to what they were before.
No
=> Correct message colours

data/gegno/gegno fleets.txt
The intent of the Protolith is to appear as a very old Gegno Generation ship, lacking a hyperdrive, that spawns very rarely in Heutesl and flies between the planets. The AI under these circumstances either goes to land on the other inhabited planet in the system, or sometimes, it will take off and immediately land back on the planet it takes off from.
Adding the `lingering` personality makes this behavior appear less goofy as the ship will spend a small amount of time longer in space, even if is going to land on the same planet, rather than fly directly back to it.
=> feat(content): Add `lingering` to Gegno Protolith Fleet

.github/workflows/cd.yaml, .github/workflows/cd_release.yaml, .github/workflows/ci.yml, .github/workflows/compute-changes.yml, .github/workflows/projects_check.yml, .github/workflows/steam.yml
This PR updates various Github Actions.
`download-artifact` and `upload-artifact` updated to `v4`, bringing some massive improvements:
> up to 80% faster download times and 96% faster upload times
`paths-filter`, `cache`, `setup-python` were updated to no longer use the unsupported Node 16.
=> chore(CI): Update Github Actions

utils/check_copyright.py
This PR makes the existing copyright check more strict. Unfortunately, this is still not good enough to catch all issues, such as the ones #9731 fixes, but it should be better now.
I'm still actively looking for a reliable copyright linter, but all of them seem to have issues... I went through most options listed in #9731 and they either didn't work reliably, reported no issues, only did parsing instead of linting, or would be painful to get working in our current CI setup.
I tested that the checker still runs.
=> Stricter copyright checking

utils/check_code_style.py
**Bug fix**
~~The unholy function slew the mighty linter~~
This PR fixes a rare edge case in the code style checker, namely in code looking like this: `->*`, such as `this->*f`. ~~Apparently this wasn't used anywhere else in the engine.~~ This fixes an issue with #9786, though the other reported style issues are valid.
I tested that this specific issue is no longer falsely detected on the text, and that all other issues are still reported.
=> fix(CI): Fix edge case in code style checker

data/hai/hai fleets.txt
**Content**
I simply added the harvests personality to all unfettered fleets (which wont affect their mission instances).
This means you can dump cargo to distract them, which makes sense as thats what they're supposed to be doing: getting supplies - they should get the supplies the appeasing merchants throw at them. In fact they should almost be raiding mainly to get those, I think.
I looked at the code for cargo and it gives a random amount up to the total amount of cargo available. This means some logistic ships could have been moving around with very little cargo, which makes little sense.
I don't think this is required?
=> Content: give the harvest personality to unfettered, and add more cargo to the logistic fleets

source/PlayerInfo.cpp
**Feature**
This PR offers a clean way of addressing issues like #7663.
Adds a new autocondition:
* `"landing access: <planet name>"`: Returns 1 if your flagship is able to land on the given planet. This includes checking that your reputation with the planet's government is greater than the required reputation to land, whether you've dominated the planet, whether your flagship has the necessary `"requires: <attribute>"` attributes, and will also update to reflect whether you've bribed the planet or provoked its government (although this is probably only useful for integration tests). Returns 0 otherwise.
If you can't land on Earth, be that because you're hostile to the Republic or some other reason, then this mission wouldn't offer.
```
mission "Friendly Earth Visit"
destination "Earth" …
```
=> Autocondition for testing if you can land on a given planet

source/HailPanel.cpp, source/HailPanel.h, source/Messages.cpp, source/Messages.h
**Feature**
Responses from hailed ships and planets are now added to the message log. These entries have `High` importance (like normal messages from ships) and start with `(Response to your hail)`.
Hailed a few ships and planets, bribed them, asked for help, and demanded tribute. Response messages were saved in the log.
N/A
=> feat(enhancement): Log response messages from the hail panel

data/human/human missions.txt
**Bug fix**
This PR addresses the bug described on [Discord](https://discord.com/channels/251118043411775489/308902312741568512/1206431000091955271)
There Might Be Riots part 3A is one of the few missions in the game that, after the first choice, swaps accept and decline, so the top option leads to decline instead of accept. I've switched it so that it is consistent with the way it is ordered in the rest of the game.
Tested all the branches of the conversation. They all work as they should.
[Test Pilot~TMBR.txt](https://github.com/endless-sky/endless-sky/files/14256548/Test.Pilot.TMBR.txt)
=> fix(content): Make TMBR 3a dialogue choices consistent

data/human/jobs.txt
Added a missing "by" before the deadline; checked other bounty missions and they don't have this problem.
=> fix(typo): Add a missing word in a bounty description

source/Engine.cpp, source/Projectile.cpp, source/Projectile.h, source/Weapon.cpp, source/Weapon.h
**Feature**
This PR addresses the feature described in issue #9765.
Add a new weapon attribute with no value (like "cluster" or "safe").
* `"fused"`: Causes the projectile to explode when it reaches the last frame of its lifetime. Normally, a projectile that reaches the last frame of its lifetime just disappears, creating any "die effect" that may be present on the weapon.
The following weapon would create an explosion the moment it is fired, dealing 1000 shield or hull damage to everything within 1000 units. The use of "fused" is what causes the projectile to instantly create an explosion without the need of a trigger radius. The use of "safe range override" allows NPCs to ignore the fact that they're about to also damage themself. This is effectively what is desired out of an aura …
=> Allow blast radius projectiles to explode when their lifetime runs out

source/main.cpp
**Bug fix**
When launched with "-d -p", the game will always report errors even if no actual parsing errors were present.
This is because anything logged to the errors file is considered an error for the purpose of test parsing, but "-d" results in a list of all parsed data files being output and logged to the errors file.
This PR means those "Parsing: " lines are not considered errors (because they aren't) so running with "-d -p" now produces useful output.
No.
=> Don't consider the "Parsing: <file>" output when in debug mode errors when test parsing

source/main.cpp
**Bug fix**
This PR fixes a crash reported by @Arachi-Lover on discord.
The game crashed when loading a save file. No longer crashes after this PR.
I tested that the game no longer crashes when the save is loaded.
[Arachi's save file](https://discord.com/channels/251118043411775489/536900466655887360/1211341115165380618)
N/A
=> fix(crash): Fix game crash on short error messages

data/governments.txt, source/Government.cpp
**Feature**
This PR addresses the bug/feature described in issue #5442.
Removed the lines from the end of the Government Load function that set the friendly and hostile disabled hails to the default phrases if none were provided.
Went through governments.txt and added the friendly and hostile disabled hails to any governments that 1. were already using the defaults and 2. where it made sense for them to continue using the defaults. Let me know if there's any I missed that you think should be using these hails, or any that I gave hails that you think shouldn't have them.
For any government without disabled hails specified, they will now say nothing if you hail them while they are disabled, assuming that you can also communicate with them.
The code looks like it should work. \:)
But in all …
=> Remove the forced-default disabled hails from Government

source/Ship.cpp
**Bug fix?**
This PR addresses something Hurl brought up and I thought it was a very good point (I was talking to myself)
Disabled hails (`friendly disabled hail`, `hostile disabled hail`) are not sent passively; you can only ever see them in the hail panel when you directly hail them. This removes that restriction.
I waited in Pherkad to see the disabled hails of Militia and Pirate ships.
Hurl was saying that pirates probably shouldn't taunt you if they're disabled. It's because the pirate government doesn't use their unique disabled hails; I can add new ones in another PR.
I am aware of #5442; would it be too naïve to think it could be solved by removing those lines? I am not sure of the interaction that happens if a government has no hail phrases at all (but I can test that)
=> fix(bug?): Disabled hails are now sent passively

source/Personality.cpp, source/Personality.h, source/Ship.cpp
**Feature**
This PR addresses the feature described in #6052
Creates a new personality, `quiet`, which does not send hails passively but will hail in the hail panel. Basically `mute` without the `(There is no response to your hail.)`
See #6052
I added this personality to all Merchant ships and went to Sol. After a minute on fast-forward, I only recieved hails from Republic ships. I then hailed a Merchant ship and I recieved a response.
Negligible?
=> feat(personality): `Quiet` personality

data/human/human missions.txt
**Fix (Mission)**
Adds an indent that was missing in the conversation.
=> Add missing indent to Mafia Extortion mission

source/ShopPanel.cpp
Currently, if you have a lot of ships and your fleet list in the shop sidebar becomes so long that some ships go behind the footer, the name / warning tooltips are still displayed when you're hovering over the hidden ships, which blocks the credits tooltip.
Before:
After:
See the above screenshots.
Just buy a hundred ships and remove their hyperdrives.
N/A
=> fix(ui): Don't draw name tooltips for ships hidden under the shop sidebar footer

data/map systems.txt
This PR addresses a [comment brought up](https://steamcommunity.com/app/404410/discussions/1/4304949638716477535/) on the steam forums.
Umbral's binary stars are overlapping. This PR makes it so they don't do that.
Note: If we use scripts (mainly @Amazinite's) to re-do the map file in the future again, this will have to be re-adjusted.
Before (too clingy):
After (respecting boundaries):
In the wise words of another dev:
No
=> fix(content): Fix overlapping stars in Umbral system

data/wanderer/wanderer outfits.txt
**Balance**
Reverted the buff to `energy capacity` that the Wanderer Sun reactors (that is, the Red Sun, Yellow Sun, White Sun and Blue Sun) recieved in #6783. As their `energy capacity` was doubled in that PR, this PR halves the current values, returning them to their prior values.
The Blue Sun in particular is simply too strong in its current state. Before accounting for its energy capacity, it is already on par with (marginally more efficient than, in fact) the Triple Plasma Core once cooling requirements are accounted for, while also being smaller (despite the general trend being efficiency increasing with size), and generating less heat (meaning that less efficiency is lost with cooling efficiency, and further reducing the effective space cost relative to the TPC). That's not …
=> Revert the buff to `energy capacity` that the Wanderer Sun reactors recieved in #6783 and nerf the energy generation of Wanderer biochemical cells

source/AI.cpp, source/AI.h
**Feature**
This PR addresses the issues with NPC scanning behavior noted by #9706, #4723, and #4240.
With this PR, ships with cargo and outfit scanners now behave as follows:
* All ships with scanners:
* Will not scan ships that have already been scanned by another ship in their government. **(New)**
* This was previously always the case for non-surveillance ships, but is now also the case for surveillance ships, which would scan any ship they haven't scanned regardless of whether an ally has.
* Will prefer to scan the closest target to them when finding a new target. **(Unchanged)**
* Will prefer to continue scanning targets they have already started scanning. **(Unchanged)**
* Will give up on scanning their target if an addition 1 minute has elapsed past their base search timer. …
=> NPC scan and surveillance personality behavior changes

data/vyrmeid/vyrmeid.txt
**Bug fix**
This PR addresses the bug described in https://github.com/endless-sky/endless-sky/issues/9894#issuecomment-1984197525
The Vyrmeid has “atmospheric scan,” which does nothing. I think that it is supposed to have “atmosphere scan.”
The Vyrmeid still don’t try to scan stellar objects, even when I’m cloaked. I think this is because a different personality overrides it.
[Test Pilot~Vyrmeid.txt](https://github.com/endless-sky/endless-sky/files/14528962/Test.Pilot.Vyrmeid.txt)
=> fix(bug): Give Vyrmeid atmosphere scan

source/Ship.cpp
This PR addresses a bug [reported on Discord](https://discord.com/channels/251118043411775489/536900466655887360/1215255778156355605).
If a `display name` is specified in the base ship model definition, variants should now use that name instead of defaulting their display name to their true model name.
Not yet.
N/A
=> fix(bug): Apply display name of base ship models to variants

source/AI.cpp
**Bug fix**
This PR fixes a bug where the `Deployed/Recalled x carried ships` says `ships` for a single affected ship.
I tested that the messages use the singular version.
=> fix: Fix plural `ships` in messages when recalling/deploying a single ship

copyright
**Bug fix**
This PR addresses the bug reported on the debian bugtracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1061241
- Moved around file stanzas to make more generic entries come first
- Added a short name for Unsplash License
- Moved explanations from the Comment fields to the License fields for `public-domain` assets, as mandated by the specs
There are also a large number of redundant patterns that we don't actually need, but they don't do any harm and aren't technically in violation of any standard I know of.
=> fix(copyright): Fix errors in the copyright file

source/Audio.cpp
On newer clang versions the game fails to compile due to an ambiguous name:
```c++
/home/user/endless-sky/source/Audio.cpp:252:3: error: reference to 'queue' is ambiguous
252 |                 queue[it.first].Add(it.second);
|                 ^
/usr/local/bin/../include/c++/v1/queue:300:28: note: candidate found by name lookup is 'std::queue'
300 | class _LIBCPP_TEMPLATE_VIS queue {
|                            ^
/home/user/endless-sky/source/Audio.cpp:85:33: note: candidate found by name lookup is '(anonymous namespace)::queue'
85 |         map<const Sound *, QueueEntry> queue;
|                                        ^
```
This PR fixes the issue by renaming the problematic variable.
=> Fix 'ambiguous name' compilation error using clang

data/_ui/interfaces.txt, source/PreferencesPanel.cpp, source/PreferencesPanel.h
Currently the controls screen in the preferences is full and the "Interface" category is split across the two columns.
To make room for possible new hotkeys and put all "Interface" commands to one place, I've added a second page.
The new layout is shown in the screenshots below (and of course is subject to changes).
Before (no pages):
After (page 1):
After (page 2):
Tooltips still pop up, conflicting keybinds are still marked, page switching works.
N/A
=> feat(ui): Allow multiple pages of controls

utils/contentStyle.json
**Bug fix**
This PR loosens the restrictions on in-mission substitutions in the content style checker.
Adds the `substitutions` node to the excluded nodes for these checks, similar to how they exclude `word` and `phrase`. This was previously causing issues in #9757 (https://github.com/endless-sky/endless-sky/actions/runs/8268384341/job/22621129434)
I tested that the issue above is no longer detected.
=> fix(CI): Don't check for leading/trailing spaces in substitutions defined in missions

data/human/free worlds 3 checkmate.txt
**Bug fix**
Cruisers have drone bays, not fighter bays, so they should be using drones rather than fighters.
=> Bugfix: give Cruiser in `FWC Cebalrai 1B` Combat Drones instead of Lances.

source/PlayerInfo.cpp
**Bug fix**
This PR fixes an issue where ships don't get assigned a parent when all of your ships (including your flagship) can be carried.
Currently, if you try to have a fleet of only fighters/drones, they will ignore where your flagship goes and will instead constantly go to planets to refuel (even if they have no HD or fuel capacity). (The only case where this does not happen is if your other fighters have the jump fuel attribute set; it still happens if your flagship has the HD/JD.)
With this fix, these fighters will follow the flagship around as expected. Since fighters get reparented to their carrier during takeoff, this just changes the default from 'no parent' to 'flagship'.
This is helpful for fighter flagship gameplay, especially if one intends on capturing a carrier in-system …
=> fix(mechanics): Fix ship parenting on takeoff with fighter flagship

data/governments.txt, data/human/human missions.txt
**Refactor (Missions)**
This PR addresses some issues I've had with this mission I wrote, especially how it is triggered.
The Argosy Hijacking mission is made of three missions; a trigger mission that tests whether the player is in Syndicate space and has >200 CR, and then a conversation mission that fires after the trigger mission has been offered, and which spawns an NPC if you accept the mission. Because missions are only ever offered once upon landing on a planet, it is not possible to make the trigger mission lead immediately to the conversation mission. Therefore, you can be offered the trigger mission, then wander out of Syndicate space, then come back and get surprised with the mission way after the trigger was meant to happen.
The reason why the trigger mission is necessary in …
=> refactor(content): Refactor the Argosy Hijacking mission

data/_ui/help.txt, source/OutfitterPanel.cpp, source/OutfitterPanel.h, source/ShopPanel.cpp, tests/integration/config/preferences.txt
Added a help message that appears when you open the outfitter with more than one ship. It explains that you can change outfits of multiple ships at once and also tells you about the "has this outfit installed" sidebar indicators.
Works both automatically and manually.
N/A
=> feat(ui): A help message for managing multiple ships in the outfitter

source/ShopPanel.cpp
**Bug fix**
To reproduce the bug:
1. Open a shipyard/outfitter, but don't select anything.
2. Press down arrow key - the first item should be selected now.
3. Press down again - the shop selects an item from the middle of the next row.
With this fix, when you press down the second time, it selects the first item from the next row (which is right under the previously selected item).
The same applies to scrolling up.
Opened the outfitter and somehow it works.
N/A
=> fix(ui): Correctly handle arrow keys with no item selected in the shop

data/human/fleets.txt, data/map systems.txt
**Bug fix**
This PR addresses the bug/feature described on Discord various times.
This PR creates a new fleet, "CCOR Logistics", which exclusively contains the CCOR variants of the Hogshead and Haulers, so they don't appear in CCOR planetary defense fleets. Also adds those fleets to the CCOR systems. All numbers I just guessed (lmao), I'm open to suggestions.
=> fix(content): split off "CCOR Logistics" fleet from Large CCOR fleet

source/PreferencesPanel.cpp
**Bug fix**
This PR addresses the bug/feature described in issue #9920
Fixed the problem described in the linked issue.
I believe the click zone for the checkboxes was originally actually a little smaller.
Would something like this be preferable over what is shown in the screenshot in the table?
I've added highlights over the click zone for demonstration purposes:
before | after
-- | --
Click around the checkbox. The click zone is now centred on the sprite properly.
N/A - a save file won't help you test this.
=> Fix plugin checkbox click zones

source/Mission.cpp
**Bug fix**
When a new mission is being instantiated, the number of jumps it is expected to require is calculated by the new mission object, not the template mission.
Currently, the distance calculation settings are not copied from the template mission to the new mission. This means that, when the expected number of jump for the new mission is calculated, it does not account for the distance calculation settings.
This PR copies the distance calculation settings from the template into the new mission prior to calculating its expected number of jumps, so it actualy uses the settings for that.
Visit Allhome and check the job board.
The jobs that involve traveling to a planet in human space now have varying payments, based on the actual number of jumps and payload amount, instead of all …
=> Fix mission distance calculation with distance calculation settings

source/Engine.cpp, source/GameData.cpp, source/PlanetPanel.cpp, source/TaskQueue.cpp, source/TaskQueue.h, source/main.cpp
Fixes various lingering crashes from #6928 
- while unloading landscapes
- `-p` while having plugins
Also correctly unload old landscapes (this was somehow broken ever since MZ changed that part of the code 7 years ago lmao).
Ran the changes, still works and no longer crashes! Also enabled a thread sanitizer to catch any possible race conditions, and none were found.
=> Fix various crashes when loading/unloading images

source/Port.cpp
**Bug fix**
The port always uses the second token in the "port" line as its "name" (the text shown on the spaceport button.)
But, if "add port" was used, the second token is "port" and a special name (if provided) would be the third token.
This PR checks if hte first token is "add" and, if it is, looks at the third token for the name, instead of the second.
N/A
Use the attached save file with and without this change.
[warp core vara ke stai abandonment~original.txt](https://github.com/endless-sky/endless-sky/files/14734109/warp.core.vara.ke.stai.abandonment.original.txt)
Ignore the disabled mission.
=> Fix custom port button name when using "add port"

data/hai/hai jobs.txt
**Bug fix**
This PR addresses the bug described in PR #9872.
Fixes a bug that prevents some quantum keystone jobs from offering. Specifically, you would need to have the quantum keystone and shield beetle pendant installed and have the tree skeleton key stone. I fixed it so that you just need to have one of the three keystones mentioned installed.
Should be blocked
Should be able to be accepted for both jobs
Should be able to be accepted for less restrictive job only
This save file can be used to test these changes: 
[Test Pilot~Quantum Keystone Only.txt](https://github.com/endless-sky/endless-sky/files/14717501/Test.Pilot.Quantum.Keystone.Only.txt)
[Test Pilot~Non Remnant Keystones.txt](https://github.com/endless-sky/endless-sky/files/14717502/Test.Pilot.Non.Remnant.Keystones.txt)
=> fix(content): Allow quantum keystone jobs to offer properly

copyright
Moved various file patterns from a block for original works to blocks for derived works as appropriate.
There are a few entries remaining in the original block that I am not yet sure on the correct place for:
```
images/effect/efreti?flare/*
images/outfit/*?korath?afterburner*
images/outfit/*efreti?steering*
images/outfit/*efreti?thruster*
```
Determining where these should go requires further investigation.
High DPI PR: https://github.com/endless-sky/endless-sky-high-dpi/pull/399
=> Yet Another Copyright Fix PR

data/human/outfits.txt
**Balance**
This PR cuts the Asteroid Scanner's price in half.
Buffed the Asteroid Scanner by cutting its price in half, from 122,000 -> 61,000 credits. There's been a decent amount of discourse on the discord over mining's place in the meta, and it's widely regarded that mining is most beneficial to early-game players as systems have fixed asteroid/day caps. It's also been pointed out that mining requires a fairly significant investment compared to other forms of income, such as trading, transport missions, or looting/capturing. More specifically, the 61,000 credit pricetag allows a starting Sparrow pilot to afford the asteroid scanner by selling only some frivolous things like one of their beams or their shield generator, rather than needing to commit to selling their Hyperdrive to …
=> feat(Balance): Cut the asteroid scanner's price in half

source/Government.cpp
Replace wrong value retrieval with the right ones in source/Government.cpp.
=> Fix government reputation error when loading data files

data/human/culture conversations.txt
**Typo fix**
This PR addresses something I noticed while I was making another PR.
In https://github.com/endless-sky/endless-sky/pull/9455 the people of Burthen were originally called Burthensiders; however this was later changed to Burthenian. It seems like I missed a couple while I was making the change.
=> fix(typo): Replace two mentions of "Burthensider" with "Burthenian"

data/wanderer/wanderers start.txt
**Bug fix**
This PR addresses the bug/feature described in #8067 by ThrawnCA.
Changes the `accept` end word to `launch` to prevent the player from accessing the deserted outfitter and trading center, since you're there to transport a bunch of people in a hurry, not buy millions of credits' worth of goods.
=> fix(content): Ensure player can't access planetary facilities while evacuating Vara Ke'stai and Varu Mer'ek

data/korath/korath ships.txt
This PR addresses the issue described in issue #9957.
Zitchas pointed out that the description of the FS27 implied that it would have far more weapon space than human fighters. While at the time the description was made, it had more weapon space, now this implication would be inaccurate. As suggested by @xX-Dillinger-Xx and @warp-core, I have opted to change the description to be more clear. Though I am not sold on this new description either, I still think it is an improvement, and this way the issue won’t be forgotten about.
TBD: Check that the description is actually changed
This save file can be used to test these changes: I can’t provide any save files that don’t require a plugin (omnis or all content), so you’ll have to just read the …
=> fix(content): Clarify FS27 description

data/persons.txt
**Bug fix (sort of)**
This PR addresses the issue described in discussion #9974, specifically @MasterOfGrey's comment at https://github.com/endless-sky/endless-sky/discussions/9974#discussioncomment-9065672
Removed outfit scanning power and efficiency from the Modified Ladybug, to prevent it from doing outfit scans. Kept other scanning attributes.
None
N/A
=> Fix(content): Remove outfit scanning capabilities from Grey's person ship

data/human/kestrel.txt
**Balance**
This PR addresses the bug/feature described in discussion https://github.com/endless-sky/endless-sky/discussions/9980
Simply reduces the combat rating required for the Kestrel mission to trigger from 8000 >> 6000.
I think the Kestrel mission comes too late. I don't agree with Saugia's comment on https://github.com/endless-sky/endless-sky/pull/8578#issuecomment-1484178674 that "It's not designed to be rewarding to the player in a progressive way based on their place in campaigns or combat in the game." Why not? It's a nice combat ship progression from a Falcon/Leviathan, a nice alternative to a Bactrian, and is still outclassed by the various alien ships the player will gain access to. 
Waiting until a combat rating of 8K basically guarantees the ship will be a fairly useless …
=> Reduce combat rating kestrel.txt

data/coalition/lunarium intro.txt
**Bug fix**
This PR addresses the bug described on [Discord](https://discord.com/channels/251118043411775489/536900466655887360/1227755770750177360).
In https://github.com/endless-sky/endless-sky/commit/2cc4256f2aea1943f772ae5cf87df48babd34412, I fixed an issue where the Heliarch join mission would silently disappear if you were assisting the Lunarium and landed on Ring of Friendship, but I didn’t fix the same issue on the Lunarium side. This PR fixes that.
Tested that the Lunarium meeting mission was postponed with a pop-up instead of disappearing.
This save file can be used to test these changes: [Dag Roth.txt](https://github.com/endless-sky/endless-sky/files/14939925/Dag.Roth.txt)
Thanks @Dagroth1
=> fix(content): Block Lunarium: Questions from finishing if you are assiting the heliarchs and explain why

source/LoadPanel.cpp
**Bug fix**
This PR addresses the bug described in issue #9971.
This fixes the format strings for the date/time, as the program that interpreted the date/time format was changed but the format strings weren’t.
Before commit 3f890aa4c343b974d120879d7408d77dbb43540a
After commit 3f890aa4c343b974d120879d7408d77dbb43540a
After this commit:
Tested that the issue was no longer present (linux, windows through WINE)
Any save file will work. Here, take one: [Test Pilot.txt](https://github.com/endless-sky/endless-sky/files/14898702/Test.Pilot.txt)
None
=> fix(ui): Fix timestamp tooltip not displaying properly for save files

source/MapPanel.cpp, source/MapPanel.h
**Bug fix**
Moved DrawSelectedSystem from MapPanel::Draw to MapPanel::FinishDrawing to fix MissionPanel's rings overlapping with the distance info box. Also updated the comment of DrawSelectedSystem to match its comment in the header file.
Before:
After:
See the screenshots above.
N/A
=> fix(map ui): Draw distance to the selected system after mission markers

data/quarg/quarg missions.txt
**Bug fix**
This PR addresses the bug/feature described in issue #10007
Some choices meant to disappear after picking them once (to prevent an infinite loop of the same choice) weren't disappearing.
The `to display` blocks of the choices were indented once further than they should be, which led to this.
This PR simply removes one indent from them.
=> (bugfix) Correct indentation in Gohl's mission choices

tests/integration/config/plugins/integration-tests/data/tests/tests_random_links.txt
**Bug fix (merged outdated test)**
This PR removes an outdated watchdog which I accidentally merged as part of a rebase/merge of PR #7987
Watchdog code was removed from testing in 2023, but I merged an older PR and overlooked the test-failure which I should have seen.
CI tests are working as expected, but I overlooked a failing CI test.
This PR also goes through CI testing, so I should pay more attention this time.
=> fix: Remove outdated watchdog

.codespell.exclude, .codespell.words.exclude, data/human/deep missions.txt
**Content fix**
This PR addresses something SpearDane brought up while we were working on Saga's Saga.
In #9622 all instances of "ser" were changed to "Captain" to make the dialogue more gender neutral (as the captain is never given a gender, being an extension of the player). However, "ser" is actually used in literature as a gender neutral form of address, and is not to be confused with "sir". It is meant to be used in the Deep somewhat regularly, but "especially by more traditional communities".
See: https://en.wiktionary.org/wiki/ser#English
=> fix(content): Add back instances of "ser" and explain what it means in the Skadenga and Stones of Our Fathers missions

data/gegno/gegno intro missions.txt, data/human/free worlds 0 prologue.txt
This fixes two text mistakes. One is a clear typo: “oufitter.” The other is a word which disputably does not exist: “monumentous” isn’t in any dictionaries.
=> Fix two typos

CMakeLists.txt
My Nix setup shits itself if `GLEW::GLEW` is used, for some reason.
From my understanding, `GLEW::GLEW` just uses `GLEW::glew` anyways if we're not statically linking glew, which I'm _pretty_ sure we aren't ever doing.
Pinging @quyykk for build-related stuff
=> Link GLEW::glew instead of GLEW::GLEW in CMakeLists.txt

CMakeLists.txt, CMakePresets.json, docs/readme-cmake.md, vcpkg.json
- Drop required CMake version to 3.16. However, 3.21 is still highly recommended since it makes it easier to build and run the unit/integration tests.
- Stop using Vcpkg by default on Linux.
- Remove custom Flatpak code, it is not necessary anymore.
- Simplify MacOS dependency declaration
- Adjusted build instructions accordingly
- Fix syntax error while specifying CMake version range
- Increase highest supported CMake version to 3.29
/cc @thewierdnut 
Works correctly on Linux. CI will test everything else.
=> Simplify CMake build on Linux and MacOS

data/human/campaign events.txt, data/map systems.txt, data/sheragi/archaeology missions.txt
**Content**
Regarding sad archie timer ship, I noticed that when you move it resets it (as intended), meaning if you're fighting pirates you wont be able to meditate properly.
This removes pirates from that system.
We can just say the Archon stopped them from entering
it worked, no pirates and it triggered a bit later
[Uploading Carstesan Nemo.txt…]()
launch, land (to trigger the latest version of the mission), and then go to Ildara to test it out. (and you get to see the magnificent Emperor Beetle from up close, too)
=> Content: remove pirates from Ildaria

data/human/marauders.txt
**Balance**
This PR addresses part of a problem described a bit in issue https://github.com/endless-sky/endless-sky/issues/7763
The synd shield regen is too easy to acquire from these ships, giving you even less incentive to play checkmate and causing issues if we want to rebalance them, due to how easily and early they're available.
For consistency we also removed the electron guns.
In order to compensate for removing those, I added a smidge more Hai technology to some marauder builds - it could be done more so later on if we feel like this is a good decision. (rn its only 2 small shield gen, one battery and a small a big AM)
Some marauder ships also had a bunch of outfit space left over after the battery buff, and this fills it up, whilst making them and some others a tad bit more …
=> Balance: tweak marauder builds, and remove later game content from them

data/wanderer/wanderer missions.txt
**Bug fix**
This PR addresses the bug/feature spotted by Arachi
The mission should reference the Wanderer ship, not the Mereti ones.
Played through the mission and read the relevant conversation. Confirmed that the name was a Wanderer-sounding one and not a mereti one.
=> fix(content): make the <npc> substitution in Wanderers: Mereti: The Plant 5 point to the right npc

data/korath/korath weapons.txt
**Balance**
This PR addresses the bug/feature described on discord various times in various places
Drop the missile strength from 60 to 30 for all three stages, and drop the turn rate from 2 to 1.7 for the activated stage.
Currently, it is excessively difficult to shoot down or evade the Firelight, so facing opponents with firelights simply becomes a case of taking all the hits and hoping you have enough HP and/or regen that the opponent runs out of ammunition. This makes it more possible to avoid damage from firelights rather than needing to tank it.
=> feat(balance): Tone down the missile strength and turn rate of the Firelight, so that it is less excessively difficult to evade and/or shoot down.

data/_ui/tooltips.txt, source/Outfit.cpp, source/OutfitInfoDisplay.cpp, source/Ship.cpp
Renamed the "cloaking shield" attribute to "cloaking shields" to make it consistent with other similar attributes ("firing shields", "thrusting shields" etc.).
None.
=> fix(typo): "cloaking shield" -> "cloaking shields"

data/human/human missions.txt
By request of warp-core and tibetiroka
=> fix(content): syntax in Lost Dog missions

data/_ui/tooltips.txt
**Bug fix**
The "cloaked action" attribute was removed from #7025 prior to it being merged, but these tooltips were never updated to reflect that.
I've also updated the tooltip for "cloak by mass" to better describe how it relates to the mass of a ship.
=> Update some cloaking tooltips

data/human/free worlds war jobs.txt
**Bug fix**
It seems very strange for these jobs to ask the player to scout Graffias, given that it is deep within Free Worlds space. There is no way any Navy ships could get there without passing through several Free Worlds systems first.
In particular, selecting Graffias as the scouting target doesn't really serve the purpose of having the player travel into Republic space. While the system is technically allied with the Republic, it has no Navy fleets, and is only one jump away from Free Worlds space, with no other hyperlinks.
No
=> Don't select Graffias as a target for Free Worlds "Scouting Run" jobs

source/ShipInfoPanel.cpp
**Bug fix and/or mechanics enhancement**
If the user decides to adjust the size of the Weapons box in the Ship Info display Panel by changing the values present in Interfaces.txt, then the hoverbox and line positions will not display correctly.
In its current state, hoverbox and line placement only works if the weapon box is centered on 0.
This merely adds `centerX` to these two lines. In vanilla with default values, this is 0, and thus there is no change to the game. 
By including centerX which is already there in the previous line, the Weapon box can be adjusted in size in interfaces.txt without any code updates required.
In other words, this makes the existing code much more resilient to changes that a regular user could make to their data files.
Note: Yes, this is a picture of …
=> feat(code): Ensuring label and line positions adapt to Weapons box positioning

data/human/fleets.txt, data/human/variants.txt
With the introduction of mining and tractor beams, Amazinite has talked about adding tractor beams to a few pirate ships to collect flotsams for situations such as when freighters dump their cargo in appeasement (which is especially the case with the Syndicate).
I've added four new Tractor Beam pirate variants for the Headhunter, Splinter, Falcon, and Protector. The Headhunter variant gives a little extra love to Twin Modified blasters, meanwhile the Falcon variant gets a little extra love as the first Falcon variant with Proton Guns. I had considered giving the Vanguard a variant, but I feel it better to not jump on every possibility to give the player a tiny bit of "what if I do it" scenario (along with the Firebird). The Argosy, although sold in …
=> feat(content): Core Pirate Ship Variants with Tractor Beams

data/human/deep missions.txt
This PR addresses the bug/feature described in issue #7465 
This PR adds offer conditions to "Deep: Interrogation" so it doesn't offer during the middle of the main campaign, by making it so it can't offer once you've chosen a side, and only after you have completed the main plot if you have. This is the same thing done with other Deep missions.
I no longer get the interrogation conversation when first landing on Valhalla, nor do I have it offered in the save file (however I did get a Skadenga conversation on Nifel). Removing the "chosen sides" condition made it offer again.
Used the save from the issue.
=> feat(content): Prevent "Deep: Interrogation" from offering during the Main Campaign

data/human/deep missions.txt
**Bug fix**
This PR addresses the bug/feature described in issue #6637 (assuming I understand it correctly)
In commit 7686991, Deep Remnant missions were re-organized with the introduction of the "Deep: Remnant: Continue Research" mission. If the player has completed this mission series prior to this addition, this mission will offer and lead to nothing. This PR adds a condition check for this using "not: offered" (the next mission doesn't give the player a second chance if declined), so if the player has finished the following missions, this one won't offer. (If we want this as separate mission, I can do that).
This doesn't apply to saves that have the mission already active, which would be very few. If we want to include those cases as well, I can add a patch mission for that.
None yet.
=> fix(content): "Remnant: Continue Research" no longer offers if you've completed the missions after it

data/hai/hai fleets.txt, data/map systems.txt
This PR addresses the bug/feature described in issue #2700 
This PR adds additional mineables to Imo Dep to further support the description of the system having unusually large amounts of metal asteroids, as described in the linked issue. Additionally, this PR adds a few Hai Miner fleets to some Hai systems as suggested [here](https://github.com/endless-sky/endless-sky/issues/2700#issuecomment-312967208) by MZ. The fleet itself is small and minimal, and the spawn rates are somewhat higher, to keep the sense of mining being an uncommon sight.
N/A
=> feat(content): Adjust Imo Dep Minables & Add Hai Mining fleets

data/human/kestrel.txt
In #7719, the "Tarazed Advanced" shipyard was added to Zug through an event to implicate the FW's acquisition of more advanced ships for their fleets during the war. However, the Kestrel Easter Egg ship is also found in this shipyard. From my understanding, "Tarazed Advanced" was originally meant to be only found on Tarazed. Now that it is on Zug, the Kestrel can be sold there too.
As an easter egg, the encounter and mission series the player has with the Kestrel is intended to be directed at the player as a player (specifically through this individual on Tarazed), not necessarily the player as a "special" pilot within the universe of ES. The Kestrel being sold at Zug can be confusing and seem odd as it implies the FW has means of production for it. …
=> feat(content): Separate the Kestrel from "Tarazed Advanced" shipyard

data/korath/korath ships.txt
**Balance**
This PR addresses the bug/feature I noticed just now.
The Korsmanath A'awoj used the same explosion stats as the Kasichara A'awoj and the numbered world-ships, which meant that despite being the largest ship in the game it had a smaller explosion than the Ikatila'ej and Rai'alorej. The explosion has been increased to be larger and more damaging than that of those two ships.
The Echo-galleon had an extremely large explosion (larger than any other ship I could find, actually) with oddly low damage (lower than the smaller Arch-carrack also produced by the Efreti). This has been adjusted to instead be similar to, but slightly weaker than, the explosions of the Kasichara A'awoj and the numbered world-ships, with which the Echo-galleon shares a common origin.
=> fix(balance): Adjust explosion stats for the Korsmanath A'awoj and Echo-galleon to follow the trend in explosions from other comparable Korath ships.

source/GameAction.cpp, source/PlanetPanel.cpp, source/PlayerInfo.cpp, source/SpaceportPanel.cpp
**Feature**
This PR addresses the bug/feature described in issue #6719 and as requested by @bene-dictator 
Up til now events were only applied on the next increment of date. This PR allows for an explicit time to event of 0, which mean the event gets applied when the game action is triggered.
Take this example:
```html
event "war begins"
system Sol
government "Free Worlds"
mission "Name2"
job
repeat
on accept
event "war begins" 0
```
The map changes will be seen as soon as the mission gets accepted
I used the test mission to test it once with explicit 0 and without, worked like expected, with explicit 0 map changes were seen directly, without I had to depart
N/A
I looked through the data files and there is no place where event gets used with a 0, so no need to change anything there.
=> Feat(events): Allow explicit 0 for events to apply directly

data/human/free worlds 0 prologue.txt
**Bug fix**
This PR addresses the bug/feature described in issue #8422 
Currently, Pact Recon 3 is only finished when you visit every system. However, with a637e1e4c9b78029f4567f7b0b80c74e5f0d2807, you can use marks to only require visiting certain systems. This PR modifies Pact Recon 3 so that entering the system with the pirate fleet gives you a popup and allows you to go to the destination to complete the mission without having to visit the other systems.
- Systems without the pirate fleet getting unmarked as you visit them
- All systems unmarking when you visited the system with the fleet
- The on visit message mentioning the four systems that the pirate fleet could be in for searching the wrong system
- The mission tick lighting up when finding the fleet
- The mission subsequently …
=> fix(content): You only have to visit the system with the pirate fleet in Pact Recon 3

source/AI.cpp
This PR addresses the bug/feature described in issue #9316
Checks that the target system of an escort is not the same as as the target system of the flagship, skipping recomputing a distance map every frame (very expensive).
Improves performance, for once
=> Don't recalculate escort's distance maps every step when jumping.

data/human/human missions.txt
**Bug fix**
Two fixes to the Lost Dog mission.
Replaces `planet` with `origin` at the starting conversation, and adds a closing quotation near the end of the on complete.
=> Couple of Fixes to the Lost Dog mission

source/AI.cpp, source/Color.cpp, source/Dialog.cpp, source/Files.cpp, source/Hardpoint.cpp, source/Hazard.cpp, source/Interface.cpp, source/Personality.cpp, source/Preferences.cpp, source/Ship.cpp, source/ShipEvent.cpp, source/System.cpp, source/Wormhole.cpp
**Style fix**
This PR fixes some cases where functions had more or less than 3 empty lines between them.
According to the style guide, we should use exactly three empty lines as the separator.
I did not fix test functions, functions within namespace blocks, nor within special preprocessor directives.
I tested that the game still compiles.
=> fix(style): Fix function spacing in the source files

data/_ui/tooltips.txt
**Bug fix**
This PR adds a tooltip for the preference added in #9638.
I tested that the tooltip shows up in-game.
=> fix(ui): Add missing tooltip for `Camera acceleration`

source/Engine.cpp
Fixes #10082, and deduplicates some code.
Works by setting camera position on `EnterSystem()` _after_ the initial ship positions are set, which was default-initialized to (0, 0) when buying ships before.
=> Properly set camera position when leaving planet

data/human/human missions.txt
I noticed a ` log `` ` in the Adelita missions that snuck in. Remove it.
=> fix(content): Remove an empty log from Adelita

.codespell.exclude
Codespell had an update, and is now detecting lines that were previously fine. This is causing the CI to fail on unrelated pull requests.
I fixed the issue by excluding the relevant lines from codespell.
The CI should pass here.
=> fix(ci): Add missing codespell excludes for the new version

changelog, io.github.endless_sky.endless_sky.appdata.xml, steam/docker-compose.yml
**Bug fix**
This PR addresses the bug/feature introduced in issue #9945
#9945 changed the linux build from vcpkg to system libraries, which works well on our normal workflows. However, the steam workflow runs in a steam-sdk container, which seems to be missing libmad0-dev.
=> fix: steam workflow is missing libmad0-dev library

.github/workflows/steam.yml, changelog
Currently, the Steam workflow is only triggered by "workflow_dispatch" events. This means it only runs when someone tells it to run.
However, the build job within the workflow only conditionally runs when certain files are changed.
This is a problem when, for example, only the configuration for the workflow itself is changed and you want to rerun it. You tell it to run, but it'll bail out after calculating the changes because none of the required things have changed.
Instead of modifying the condition to also check if the workflow configuration has changed, this PR simply removes the conditional check. If I dispatch the workflow, I want it to run, regardless of what has changed. And, this way, there's less maintenance.
=> Always run Steam workflow if it is dispatched

data/map planets.txt
Fixes an awkward sentence fragment in the Stormhold planet description.
Before
After
See above.
[Balance Tester.txt](https://github.com/endless-sky/endless-sky/files/15424851/Balance.Tester.txt)
=> (fix)content: Fix sentence fragment in Stormhold description

data/wanderer/wanderer missions.txt
**Bug fix**
This PR addresses a bug I noticed because the game gave me a warning
Due to capitalization, the event "mereti visiting eneremprukt" wasn't working
This is my save, which has the issue
[Eebop Masch~~previous-1.txt](https://github.com/endless-sky/endless-sky/files/15449356/Eebop.Masch.previous-1.txt)
=> fix(content): Typo in new mereti missions

data/human/free worlds 0 prologue.txt
The Pact Recon missions are capable of being offered immediately after completing the previous one, which is awkward with how Freya says that she'll get in touch, only to call back right after hanging up. This PR uses events to force a one-day delay to the next mission in the chain.
=> fix(content): Prevent the Pact Recon missions from offering right after each other

data/hazards.txt
**Balance**
oops
Rescales `relative heat damage` everywhere I'm aware of it being used, to take into account masses being on average 1.5 times higher and heat dissipations being on average 1.5 times lower.
Because `relative heat damage` scales off heat capacity, not maximum heat, #9616 has indirectly made the heat of the Ember Waste somewhat more powerful than it was intended to be.
This change, which should have been part of #9616 to begin with, fixes that.
=> feat(balance): Divide `relative heat damage` by 1.5, for consistency with #9616

data/sheragi/archaeology missions.txt
**Bug fix (typo)**
This PR addresses the bug/feature described in issue #10118
Erroneous plural fixed in Emerald Sword 3 mission, after the black box explodes (label explodes) in the visiting Desyo branch.
N/A
N/A
N/A
N/A
N/A
N/A
=> Typo fix in "archaeology missions.txt"

source/PlayerInfoPanel.cpp
**Bug fix**
When sorting ships, the game makes a list of what ships are selected before sorting so it can reselect the new indices of those ships afterwards.
If there are no ships selected, it will dereference the `std::multiset::end()` iterator, because this is what is returned by `std::multiset::begin()` for an empty container.
When built with gcc, this is apparently not an issue. The game will continue.
When built with clang, though, this results in a crash.
This PR fixes this by checking if the container of selected ships is empty and then not attempting to dereference any of its iterators.
Build with clang.
Try sorting ships without first selecting a ship.
Without this PR, crash.
With this PR, no crash.
=> fix(bug): invalid pointer dereference on sorting without ship selected

source/DataNode.cpp, source/DataWriter.cpp, source/GameAction.cpp, source/text/Format.cpp
**Bug fix**
Functions from the standard library header <cctype>, such as `std::isspace`, `std::islower`, and `std::toupper` have undefined behaviour if the value of the argument cannot be represented as `unsigned char` and is not equal to `EOF` (usually -1).
Source: https://en.cppreference.com/w/cpp/string/byte/islower
In the Microsoft implementation we use with clang, the undefined behaviour is the failure of a debug assertion.
This can be seen when loading [Ursa Polaris](https://github.com/LocalGod79/UrsaPolaris) with a binary built with clang in the Debug configuration.
This PR makes the recommended change of `static_cast<unsigned char>`ing the arguments passed to these functions.
Build with clang in the Debug configuration.
Install the [Ursa …
=> Fix(bug): std::isspace negative signed char on clang

source/PlayerInfoPanel.cpp
**Bug fix**
This PR addresses the bug/feature described in issue #10126
Currently, the game calls `std::stable_sort` on an invalid range if the list of ships is empty and user tries to have it sorted in the player info panel.
This causes bad things (usually a crash).
This PR fixes it by exiting the ship sorting method early if the list is empty, because there's nothing (good) left to do.
Launch the game.
Start a new pilot.
Don't buy a ship.
Leave the shipyard.
Open the player info panel.
Click one of the column headings to sort the (empty) list.
Without this change, you're likely to see a crash (at least, when built with clang, I didn't test a gcc implementation).
With this change, nothing happens (there's nothing to do).
=> Don't do bad things when user tries to sort an empty ship list

source/Mission.cpp, source/Ship.cpp
**Feature**
Add the ship model in "ship destroyed" logs.
I want to know what kind of ship I just lost. If it was a Scrapper, I don't care, if it was a heavy warship, I need to reload my save.
I also changed the mission failed version to use "destroyed" instead of "lost" so that they match (and because 'lost' is ambiguous in English — did it just fly to the wrong system?)
No before screenshot. All orange messages just said "Your ship ..."
I flew around and got shot a lot.
Any save with a fleet will do. I don't exactly have a handy one since I had to fly a lot to get to systems where my fleet would die. Let me know if I should make one specificly for this.
N/A
=> Tell me what kind of ship I just lost.

data/human/hails.txt
**Typo fix**
This PR fixes a minor typo in human hails.
Somewhat counter-intuitively, the species name Quarg is always used in a singular fashion. This means that the possessive form is `Quarg's`, not `Quargs'`. This form is already used in some places, such as various Coalition and Quarg missions.
=> fix(typo): `Quargs'` -> `Quarg's` in human hails

source/PlayerInfoPanel.cpp
Show most important (greatest value) salaries and tributes at the top of the list in the player dialog.
Before:
After:
Nearly zero. I don't even have multiple salaries at the moment.
Someone else's save would probably be better for this as I am still at the beginning of the game.
N/A
=> Sort salaries and tributes in descending order.

source/AmmoDisplay.cpp, source/AmmoDisplay.h, source/Engine.cpp, source/MainPanel.cpp, source/PlanetPanel.cpp, source/PlayerInfo.cpp
**Bug fix**
This PR addresses the bug described in issue #10125 
Resetting the player flagship seems to fix most issues, except:
- the ammo counter is still visible (but cannot be interacted with)
- the trading panel is still available
Tested with a mission that kills the player on a planet. Needs testing with mid-flight death.
=> fix(mechanics): Properly reset player flagship after death

.github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md
Updates the issue template to direct users to https://github.com/endless-sky/endless-sky-wiki/issues for issues about the issue.
Updates the PR template to inform users that they should open a PR to https://github.com/endless-sky/endless-sky-wiki if updating the wiki alongside their PR is appropriate, and that a link to that PR should be included.
No.
=> Update issue and PR templates for new wiki repository

source/DataFile.cpp, source/text/Utf8.cpp, source/text/Utf8.h
**Bug fix**
This PR addresses the bug/feature described reported on Discord: https://discord.com/channels/251118043411775489/285540320823869441/1245161589779468340
Some text editors ~~notepad~~ will save a byte order mark (BOM) sequence at the beginning of a UTF8 encoded text file, to indicate that it is UTF8.
Currently, Endless Sky doesn't know what that is, it just looks like another character to it.
This results in the first token it reads in the example text files being `ï»¿#`. This is the three bytes of the BOM plus the hash character to denote the comment. But, this isn't parsed as a comment. So, UniverseObjects checks it against all the expected root nodes, doesn't find a match and calls `DataNode::PrintTrace` on it.
During this step, the first byte is passed to `std::isspace`. In …
=> Detect and move past the UTF8 byte order mark (BOM) at the beginning of a data file

source/PreferencesPanel.cpp
Provide finer grained user settings for scrolling speed.
In order to be able to scroll the fleet list in the player info panel one line at a time, I would like to be able to set my scroll speed preference to "10". This change allows users to maintain their existing preference but provide more choices in the UI, in the range 10 to 60 going up in incrememnts of 10.
After:
I manually tested clicking to advance the preference (which loops around from 60 back to 10) and hover-scrolling over it, which is bounded at 10 and 60.
I checked the effects of the 10 setting in the player info panel fleet list with 177 ships, and in the shipyard and outfitter panels with the same, on both the left (new ship and outfit) and right (owned ship) sides.
It is a user preference.
I did a repo search and browsed …
=> Provide more user settings for scrolling speed.

data/hai/hai jobs.txt
**Bug fix**
This PR addresses the bug described in issue #10141
The Hai Festival jobs do not have a deadline and can still offer even if it would be impossible to deliver the passengers until after the deadline. This PR adds a deadline, makes it so the mission can only offer if it is always possible to complete, and makes it fail after the end of the month.
EDIT: It can now also offer on February 27 or Februrary 28 as it takes at least two days to reach the destination, one to depart, and at least one to jump.
Tested that the mission offered
This save file can be used to test these changes: [Test Pilot~Festival.txt](https://github.com/user-attachments/files/15526771/Test.Pilot.Festival.txt)
=> fix(content): Give hai festival jobs a deadline

source/Mission.cpp, source/NPC.cpp, source/Ship.cpp
Currently, when an escort is destroyed, you only get a log message after all the explosions have finished. This may be after you have landed or jumped out of the system, in which case the ship is still destroyed but no log message appears!
After moving the log message to the first frame where the escort is irrevokably destroyed, I realised that the same "ship destroyed" log was being sent for every affected mission, at the point the ship starts exploding, and then again once the ship concludes exploding. I replaced this with just one message at the start.
Before:
After:
N/A
A lot of departing from planets using the attached save, and getting shot at.
[Mission Failed.txt](https://github.com/user-attachments/files/15612308/Mission.Failed.txt) …
=> Earlier destroyed log

source/Ship.cpp
While investigating #10172 I discovered the "battery only?" warning never shows up for the affected ship, which will be how I got in to this situation in the first place.
When a ship with "energy consumption" has no "energy generation", the check for `!generation` fails because the value is negative. We need to check if all sources of energy combined are not positive.
No before image possible.
After:
Just tested with one ship that only had a battery and nothing else.
Any save file will do. Remove your energy generation, fuel converters, and solar power. Add some batteries.
N/A
N/A
=> Fix battery only warning

data/remnant/remnant 2 side missions.txt, data/remnant/remnant jobs.txt
**Bug fix**
This PR addresses the bug reported on [Discord](https://discord.com/channels/251118043411775489/308902312741568512/1251331405003231234).
There are Remnant jobs involving disabling a world ship, however, the name of that world ship was not updated in #9696, so this PR updates the name.
Made sure there are no other places where world ship names were not updated.
[Matthew Weaver~Pre-Disable.txt](https://github.com/user-attachments/files/15845070/Matthew.Weaver.Pre-Disable.txt)
=> fix(content): Update korath worldship names for remnant jobs

data/hai/hai outfits.txt
**Bug fix**
This PR addresses a bug described in bug reports on the Steam forum.
The Benga Reverse Thruster currently uses "flare sound" for its audio, when reverse thrusters use "reverse flare sound". This PR changes it to the proper use.
=> fix(content): Correct sound reference for Benga Reverse Thruster

source/Engine.cpp
**Bug fix**
This PR addresses a bug introduced by #9642
If a ship has no sprite, then the size of the sprite cannot be calculated. This causes a nullpointer dereference when the outlines are drawn.
I tested that the game no longer crashes after this change
N/A
N/A
=> fix(mechanics): Fix crash when calculating sprite outline

CMakeLists.txt, steam/docker-compose.yml
**Bug fix**
The Steam runtime does not provide libmad. This means we need to acquire it via vcpkg and statically link it. We should also use system libraries where possible for this build.
A previous change disabled these things so the build for the Steam runtim was not working.
This PR re-enables them so the Steam Linux build now works correctly.
Built in the Steam Linux runtime with:
```bash
cd steam
docker-compose run steam-x64
```
Then tried running the result in the Steam Linux runtime:
```bash
cd build/steam-x64
docker run --rm -it -v ".:/pwd" registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest /pwd/endless-sky
```
(Both starting in the root directory of the repository.)
Without this change, it fails the run because it cannot find libmad.
With this change, it fails to run …
=> Fix steam linux build

.github/ISSUE_TEMPLATE/config.yml
**.github fix**
This PR addresses the bug/feature described in issue
None. 
I removed a word in the new issue template. 
Not really. 
N/A
It’s a one word change and isn’t in-game. 
N/A
N/A
N/A
N/A
=> fix(typo, issuetracker): Remove typo in the New Issue template

data/wanderer/wanderers middle.txt
This PR addresses the problem described in issue #7896. 
In `Wanderers: Mind Escorts`, I added one Tempest.
In `Wanderers: Mind 6`, I took away from the hostile Mereti fleet one 128, one 64, and one 32. 
In `Wanderers: Mind 6`, I also added to the friendly fleet two 16s, but took away a 128. 
None
N/A
None
[Melchior.Jack.txt](https://github.com/user-attachments/files/15845773/Melchior.Jack.txt). Courtesy of the issue. 
N/A
N/A
Fewer mines.
=> Help balance the Mind battle

data/gegno/gegno outfits.txt
**Bug fix**
This PR addresses the bug/feature described in issue #10138.
I made the Gegno Excavator be consistently named by removing one word. 
Break save file compatibility and call the outfit Excavator Drill instead. 
None. 
N/A
No, but it is a one word change. 
N/A
N/A
N/A
N/A
=> fix(typo): Consistent Excavator naming

.github/workflows/cd_wiki.yaml
This PR addresses the bug/feature described in issue #9043
Adds a GitHub Action that will copy changes in https://endless-sky/endless-sky-wiki to the [GitHub wiki for this repository](https://github.com/endless-sky/endless-sky/wiki).
It runs on workflow dispatch because there's no easy way to make it run when that repository has changes without personal access tokens which I have been told is not acceptable.
I'll describe it later.
=> Add action to deploy wiki updates

source/Engine.cpp, source/Ship.cpp
**Bug fix**
This PR fixes `flagship only` flotsam collection, which didn't actually enable the flagship to collect flotsam.
It only checked if the preference was set, without checking whether it was your flagship picking up flotsam.
Flotsam collection?
I tested that the flagship can now collect flotsam with this preference, and escorts can't.
=> bugfix: Fix `flagship only` flotsam collection

data/human/marauders.txt, data/human/ships.txt
**Feature**
This PR addresses the bug/feature described in issues #10204 and #2218.
I added Nerve Gas (sorry for the capitalization) to three especially pirate ships. I can remove it from the Modified Argosy if people want, because that is a bit iffy. I’m also requesting a review from @Amazinite before this gets merged. 
Important to note is that the Nighthawk also has Nerve Gas, which I did _not_ add. 
None. 
N/A
No. 
None. Start a World Forge or Omnis game with this PR installed and buy a ship. 
N/A
N/A
N/A
=> Nerve Gas for Marauders & Some Pirates

data/wanderer/wanderer missions.txt
**fix**
This PR addresses the bug/feature not described in any issue
`the air that blows in through the open door sting your eyes` -> `the air that blows in through the open door stings your eyes`
=> fix(typo): sting -> stings

data/_ui/tooltips.txt, source/ShopPanel.cpp
add a second line with "(parked)" to the tooltips of any parked ship in the shop fleet panel.
See screenshot. That was it.
Park any ship and hover it in the shop panel.
N/A
N/A
=> Add parked label to the ship tooltip.

source/ShopPanel.cpp
I might as well do this now too.
Adds a ship "parked" indicator to the shop panel. It lives in the bottom-right corner of the ship tile because that is where the warning/error indicator is, and you can't have that if the ship is parked, leaving the other three corners available for things like hotkey assignments (coming one day).
The design is a small square, chosen because it is language-neutral, which a blue parking "P" roadsign is not, and because it looks like the stop button on a cassette recorder. An argument could be made for using an octogon (universal shape for road Stop signs), but that is harder to implement than just `FillShader::Fill()`)
Extensive.
Any multi-ship save file will do.
Testing of flagship-only fleets can be done with a new game or by leaving your fleet parked …
=> Shop parked indicator

source/AI.cpp
**Bug fix**
This PR addresses the bug reported in https://github.com/endless-sky/endless-sky/pull/10039#issuecomment-2180264491
Escort ships were still following (GATHER) orders after the flagship died. This PR fixes that by checking for ships with orders if they have a parent.
Tested dying with an active gather command, before and after this fix. The escorts were no longer gathering after dying after this fix.
N/A, any save file with a flagship, escorts and hostiles that can kill the player will do. (Using a weak ship without shield generators helps in dying faster.)
This only affects player ships with active orders, little to no impact expected.
=> fix(mechanics): Escorts stop following orders after the flagship dies

data/_ui/tooltips.txt
**Bug fix**
This PR changes the text of the `Hold position` tooltip, which seems to have been copied from the previous tooltip.
N/A
N/A
N/A
=> fix(content): Fix `Hold position` tooltip text

source/DataNode.cpp, source/DataNode.h, source/DataWriter.cpp, source/DataWriter.h, source/PrintData.cpp, tests/CMakeLists.txt, tests/unit/src/test_datawriter.cpp
**Refactor**
This PR refactors DataWriter to enable unit testing and safe PrintData output parsing.
Exposes the quotation logic in DataWriter, removing the need for the re-implemented version in DataNode.
Adds a SaveToString() function to DataWriter for unit tests, and some modifier functions to DataNode.
Fixes the long-standing bug of PrintData not quoting its output properly.
Adds some new unit tests.
Unit tests and PrintData. Also useful for future work with somewhat complicated data writing semantics, such as #9114 (which could get more unit tests with this refactor).
The new tests run. PrintData seems to work.
=> refactor(code): Small DataWriter refactor

data/_ui/tooltips.txt, source/Engine.cpp, source/Ship.cpp
Change the "Extra fleet status messages" preference to suppress lower priority fleet messages, not higher priority ones. Specificly, always show 'destroyed' messages and conditionally show 'collected flotsam' and 'escort under-crewed' messages. Mission and player-owned escorts now behave the same, per the preference. Update the tooltip accordingly. Nota bene: there never was a message saying your escort had been scanned, despite what the tooltip had said.
Not a visual change.
Repeated with preference on/off:
* Ordered escort to it's inevitable doom, message always showed.
* Collected flotsam with flagship, message always showed.
* Collected flotsam with escort, message showed conditionally.
* Captured ship with too few crew to transfer a full compliment, message shows for both flagship …
=> feat(status-messages): Always show destroyed escorts, flotsam collect only if enabled

source/Outfit.cpp, source/Outfit.h, source/Ship.cpp
**Feature**
You can now set custom sounds for cargo and outfit scanners. They're played when you scan a ship, or when someone scans your ship. If there's no custom sound set, the default one is used, for two reasons: to prevent situations where someone forgets to add a sound and there's no audible warning that the player's ship is being scanned, and to provide some backward compatibility.
There are no data changes in this PR.
I've done some in-flight testing with custom outfits.
https://github.com/endless-sky/endless-sky-wiki/pull/15
N/A
=> feat(enhancement): Custom scan sounds

source/ConversationPanel.cpp, source/Mission.cpp, source/MissionAction.cpp, source/PlayerInfo.cpp, source/TextReplacements.cpp, source/main.cpp
**Feature**
resolves #5366
Added a `<model>` text replacement (expanded to the display model name of the flagship), which should work in the same places as the `<ship>` replacement.
Tested with this mission:
```
mission "model replacement test"
job
name "Model replacement test"
destination "Earth"
on accept
conversation
"<model>"
```
https://github.com/endless-sky/endless-sky-wiki/pull/14
N/A
=> feat(enhancement): `<model>` replacement for model name of the flagship

source/ConditionSet.cpp, source/ConditionsStore.cpp, source/ConditionsStore.h, source/PlayerInfo.cpp, source/Test.cpp, tests/unit/src/test_conditionSet.cpp, tests/unit/src/test_conditionsStore.cpp
**Bug fix**
This PR removes unused functionality that was accidentally introduced as part of #5017 (in PR #5244)
The keyword `has` for conditions is defined as "is not zero", which means that actual presence of conditions is never visibile outside the codebase. It also means that conditions which are zero don't need to be written at saving, which we actually also don't do.
The DerivedConditionsProviders however had extensive support for "Has" for conditions, while this support was never used. Removing this "Has" support makes the codebase quite a bit simpler.
There were 3 locations within the codebase that used Has to check if a condition was existing, but all those locations were easily re-implemented by Get, since they used a default value of 0 when the condition was not present (which …
=> fix(conditions): Remove unused Has functionality

data/human/variants.txt
**Bug fix**
This PR addresses the bug/feature described in issue # none.
I standardized line breaks in the `human/variants.txt` file, and made some things alphabetical. I also added quotation marks for standardization in another way.
If something looks like it has been deleted, don't worry, it hasn't.
N/A
N/A
N/A
N/A
N/A
There could be one, if we want.
N/A
We may want to change it so that the variants/ships in other fields follow the human standard, of vice versa.
=> Standardize line breaks in the human/variants.txt file

data/_ui/interfaces.txt, source/MessageLogPanel.cpp, source/MessageLogPanel.h
**Feature**
resolves #9999
Added a centered text (defined in the interface) saying that the message log is empty.
<details>
<summary>Screenshot</summary>
</details>
yes™
N/A
=> feat(ui): Display a placeholder text when the message log is empty

source/TextArea.cpp
This PR addresses the bug described in issue [#10299](https://github.com/endless-sky/endless-sky/issues/10299). This was caused by the textwrap support from [#9786](https://github.com/endless-sky/endless-sky/pull/9786)
Hover already has code to just return false if there isn't a valid box, I just removed the check so that the code will do it.
Game doesn't crash any more when moving mouse when a dialog pops up
Do a mission and then move your mouse during the done dialog
Makes the code infinitesimally faster by removing a check
=> Fix(Code): Fix assertion fails in TextArea::Hover

data/remnant/remnant events.txt
**Bug fix**
This PR addresses the bug/feature described in issue #10309.
I removed an "add " from before the Esquiline "add spaceport" in remnant events.txt.
This fixes #10309.
Before:
After:
N/A
Tried it with my save file. Seems to work.
Before:
[Asiah Racer Before.txt](https://github.com/user-attachments/files/16163019/Asiah.Racer.txt)
After:
[Asiah Racer After.txt](https://github.com/user-attachments/files/16163029/Asiah.Racer.After.txt)
N/A
N/A
N/A
=> Fix spaceport on Esquiline

data/coalition/coalition outfits.txt
**Fix**
This PR addresses the bug I just noticed
Prior to the mass rebalance (#9616) the Small Turn Module had 178.8 turn. After the mass rebalance, it now has 214.2
However, 214.2 is not, in fact, 1.5 times 178.8
I don't recall whether I made a mistake typing it in, or used the wrong value somewhere else, but in any case the number is wrong, and this fixes it.
Oops.
=> fix(typo): Fix the Small Turn Module's turn

source/OutfitInfoDisplay.cpp
**Typo fix**
This PR fixes a missing period.
Every other boolean attribute had a period after its description, but it was missing from `cloaked afterburner`.
N/A
N/A
=> fix(typo): Add missing period to cloaked afterburner description

source/Paragraphs.cpp
**Bug fix**
This PR addresses the bug/feature described in https://github.com/endless-sky/endless-sky/issues/10309#issuecomment-2220679738
The text is always the last token, so just parse that.
Warp's provided save now works, both with and without `add`.
[warp.core.add.descriptioin.tes.txt](https://github.com/user-attachments/files/16189347/warp.core.add.descriptioin.tes.txt)
=> fix(mechanics): Correctly parse `add description/spaceport` text nodes

source/Dialog.cpp
**Bug fix**
This PR addresses the bug/feature reported on [discord](https://discord.com/channels/251118043411775489/536900466655887360/1259648458764193822)
Apparently, the scroll area's size was one pixel shorter than necessary. This caused dialog text to nearly always be scrollable, even when the dialog's size was large enough.
I tested that simple dialogs no longer scroll. The mission panel seems to not have the same scrolling issue to begin with.
=> fix(ui): Fix off-by-one error in dialog size calculation

source/AI.cpp, source/Ship.cpp, source/Ship.h
**Feature**
This PR addresses the bug/feature described in issue #10285 (fixes #10285)
Adds automatic snapping to the position and velocity of ships once they are in formation. The position is adjusted continuously over multiple frames to make it appear smooth.
I tested that ships require far less corrections to stay in formation (none if the lead ship doesn't accelerate), and that major course changes by the lead ship still require the ships to manually move back to position.
Should be minimal.
=> feat(enhancement): Make ships snap to formation

source/Engine.cpp, source/Engine.h
**Bug fix**
This PR brings back the ~~"kill your GPU" mode~~ extended jump effects that were effectively disabled because a variable that was supposed to store the hyperjump progress wasn't being set.
Also replaced some duplicate calculations with that variable and added a comment explaining that it's not really a percentage (should it be renamed then?).
yes.
Huge, but disabled by default.
=> fix(bug): Restore extended jump effects

data/incipias/incipias first contact.txt
**Bug fix**
This PR addresses the bug described in #10356.
I noticed that there is an extraneous label now in the “Incipias: Help the Stranded 1” mission, so I removed it.
Tested that this doesn’t break the mission because I missed something.
This save file can be used to test these changes: [Test Pilot~Incipias Thruster.txt](https://github.com/user-attachments/files/16400711/Test.Pilot.Incipias.Thruster.txt)
=> refactor(content): Remove extraneous label in “Incipias: Help the Stranded 1” 

docs/readme-cmake.md, docs/readme-developer.md
In the C++20 migration PR, Catch2 was removed from our tree and is now used as a standalone dependency. The documentation was not changed to address this change, however. Fixes #10360.
Adds Catch2 as a dependency to the developer and cmake guides. I believe these are the only places where build instructions are stored currently.
=> fix(docs): Add Catch2 dependency to the developer documentation

source/Person.cpp, source/Person.h
This PR adds a feature for person ships as discussed in PR #10374
This PR adds support for formations around person-ships.
NPC ships typically seem to be too busy planning their next action (landing or jumping) which results in fleets immediately going for landing or jumping, and as a result having the formations not appearing. Fixing those is part of other PRs, this PR is only for adding formations for person-ships.
See #10374 for an example of a person-ship with a formation around it.
```
person "Some Person"
formation "Some Formation"
```
I've seen a formation briefly appear for ships in #10378 (when they were not busy jumping or landing).
N/A. But can be tested in combination with PR #10374.
Let's update the wiki when the other formation issues (of NPCs being too busy to form …
=> feat(persons): Add formation patterns for Persons (Person ships)

data/korath/korath weapons.txt, source/Projectile.cpp, source/Projectile.h, source/Weapon.cpp, source/Weapon.h
**Feature**
This PR addresses the bug/feature described in issue #10370.
Adds a new submunition attribute, "spawn on". It accepts a list of attributes and overrides the default behavior, which is to spawn only on natural death (without this PR, submunitions are spawned also if the source missile was killed by AM).
If you want to spawn the submunition only if the source missile was shot down by AM, you can do this:
```html
submunition <name>
"spawn on" anti-missile
```
If you want both:
```html
submunition <name>
"spawn on" natural anti-missile
```
Fiddled a bit with submunitions of the Firelight.
https://github.com/endless-sky/endless-sky-wiki/pull/40
minimal, if any
=> feat(mechanics): Submunition spawning attributes

data/remnant/remnant outfits.txt
**Bug fix**
This PR addresses the bug/feature described in issue none
A space where necessary to make a Remnant weapon work.
Thanks to 7even for pointing this out [here](https://github.com/7even/endless-ships/pull/21#issuecomment-2282752341).
N/A
N/A
N/A
N/A
N/A
N/A
N/A
=> Remnant weapon fix

docs/CONTRIBUTING.md
This PR adds additional documentation to the CONTRIBUTING.md file added in PR [#8599](https://github.com/endless-sky/endless-sky/pull/8599)
When creating a different PR I used the existing [style goals](https://github.com/endless-sky/endless-sky/wiki/StyleGoals) and [quality checklist](https://github.com/endless-sky/endless-sky/wiki/QualityChecklist) documents and saw they weren't included in the CONTRIBUTING file. These docs are applicable to a wide variety of PRs so I've added them below the C++ coding standards link.
=> Adding existing quality checklist & style goals documents to CONTRIBUTING.md

.codespell.exclude
**Bug fix**
This PR fixes the codespell action failing due to new issues it detects.
Example failed workflow: https://github.com/endless-sky/endless-sky/actions/runs/10443036384/job/28916006388?pr=10413
It detects yet another line from the deep missions, which I added to the excludes.
Should pass now.
=> fix(ci): Add missing exclude to codespell

.codespell.exclude, data/human/deep missions.txt, data/human/free worlds 2 middle.txt
**Bug fix**
Just two typoes I noticed...
None, TBH. :)
=> fix(typo): two/to, than/then in mission texts

source/Engine.cpp
**Feature**
This PR addresses the feature described in issue #10228
As the issue suggested - my skills are very limited, but finding the message was trivial, and adapting the "which ships should I count" loop from Engine::Place seemed straightforward too.
<details>
Sorry for the size... Also not vanilla rules, plugins active. But for a simple message...
</details>
Took screenshot. :zany_face: 
Actually, with my mods I can generate way more flotsam in a very short time than one can in vanilla, so it got some stress test.
May add one later, or on request - should be vanilla and not require any plugin
A loop to get a total is more expensive than the one method call this message had before, but -as mentioned- my tests suggest that has little impact, especially as this does not repeat per …
=> UI: Harvesting message includes fleet remaining free space

data/hai/hai reveal 2 start.txt, data/human/human missions.txt
**Bug fix**
This PR fixes some datafile issues that were found while testing for #10213
The `has` and `not` statements should only be followed by a single condition. And the undocumented feature of using assignments within condition-tests was apparently used once within the datafiles.
N/A
N/A
Those bugs were actually found during some tests.
N/A
N/A, the wiki already has the correct descriptions of the syntax for conditions.
N/A, datafile update only.
=> fix(data-files): Fix has, not and assign condition usage in datafiles

docs/readme-cmake.md
This PR addresses faster rebuilds after switching branches
Ccache can significantly speed-up Cmake builds after switching branches. If you are about to build the same code twice, then the build will finish almost instantly the second time, since the build will not execute, but just re-use cached artifacts.
Install ccache (as mentioned in the instructions) and enjoy re-builds that are a lot faster.
Installed ccache, and noticed the builds being faster.
This is the wiki-update with the build instructions. The developer documentation apparently lives in the main archive.
Some more diskspace would be used for caching, but your builds would be faster. Not related to in-game performance.
=> doc(building): Mention ccache to speed-up rebuilds

source/Engine.cpp
**Bug fix**
This PR addresses the bug/feature that was reported in my terminal:
.../endless-sky/source/Engine.cpp:693:66: runtime error: reference binding to null pointer of type 'const struct System'
We were converting a null-pointer to a system into a reference. This PR adds a check if the pointer is not null before turning it into a reference.
Verfied that the warning was gone after this change.
N/A
N/A (fix in code)
Should be no impact.
=> fix(Engine): Check if system is not null before making it a reference

README.md
README.md now mentions that Endless Sky is officially available on GOG.
=> fix(documentation): Add GOG to the README

docs/readme-cmake.md
The build manual now makes it clear which runtime to use. Also bumped up the latest available mingw release (ideally I'd link it to the always-latest release, but the MSVCRT version is marked as latest).
=> docs: Clarify required mingw version

source/Dialog.cpp
PopThrough is not needed when removing only a panel and its children.
The TextArea doesn't appear after closing its Dialog (tested on a search dialog and a normal one).
N/A or unnoticeably better
=> refactor(ui): Switch from PopThrough to Pop in Dialog

data/incipias/incipias outfits.txt
**Bug fix**
This incipias weapon had a missing sound file. I replaced the reference to it with `explosion small`, as suggested by @Saugia.
The game no longer complains about missing audio.
=> fix(audio): Fix missing sound effect for `star tail hit`

data/sheragi/sheragi outfits.txt
This PR alters the behaviour of the Dragonflame Cannon, removing its Blast Radius (50) in exchange for Penetration Count (20), making it better against lined up targets while reducing its performance against broader, spread-out clumps.
Some brief flying around shooting at random things to ensure it works. In normal gameplay, it doesn't seem to affect the weapon's performance much; there are relatively few situations where the player is dealing with huge clumps of enemies, with tributes and extensive time in Mesuket being the only two situations I can think of off the top of my head.
A penetration count of 20 was picked to compensate for the difficulty of lining up multiple targets, while also not massively increasing the weapon's strength. The most notable performance increase occurs in …
=> Feat(Misc): Make Dragonflame Penetrate instead of doing Blast Radius Damage

data/remnant/remnant events.txt
**Bug fix**
This PR addresses a bug described on discord
Ssil Vida has a unique outfitter called `Remnant Core` which fails to receive an update after Teciimachs are rolled out, making it the only place in the game where you can still buy EMP Torpedoes. This PR fixes the issue by removing EMP Torpedoes and replacing them with Teciimach canisters in the associated event.
=> fix(bug): remove EMP torpedoes from Remnant Core Outfitter; add Teciimachs instead

data/quarg/quarg news.txt
**Bug fix**
Prevent the "ringworld quarg news" news entries from showing on the station Ruelogakk.
The news simply excluded Lagrange, which at the time was the only quarg+station that wasn't a ringworld. With the addition of Ruelogakk in the game with the Gegno, this allowed for the ringworld news to show there, a not-ringworld station.
This PR just changes the news source to be from "quarg" and "ringworld" attributes.
Bug reported by user Uuugggg on the Discord.
=> Prevent ringworld quarg news from showing on Ruelogakk

data/incipias/tace mesa.txt
**Bug fix**
This PR addresses the bug described in issue #10457
Fixes #10457
Added inscrutable to Tace Mesa so they are not scannable.
Thanks @tekker2234 for flagging this issue.
N/A
The new indigineous lifeforms added with the Incipias lack "inscrutiable" and can thus have their outfits scanned.
None
None
N/A
=> [Bugfix] Make Tace Mesa inscrutable

source/AI.cpp, source/Engine.cpp, source/PlayerInfo.cpp, source/PlayerInfo.h
Currently, if you have a single escort selected and that escort is destroyed, the game thinks you still have a ship selected and sends your orders only to that destroyed ship.
With this PR, when an escort dies, it's removed from the selected ships.
Unselected destroyed escorts are now excluded too. This doesn't make any difference in which ships receive the orders, but fixes pluralization in the orders messages.
Also, if all escorts you're sending an order to are destroyed, you get a message about it.
yes.
N/A
=> fix(mechanics): Unselect destroyed escorts and exclude them from receiving orders

source/AI.cpp
This PR resolves #1153.
Aliens no longer assist player's escorts if their government has a language that the player doesn't know.
Tested with the Wanderers.
N/A, I think
N/A
=> feat(mechanics): Aliens don't assist player escorts if the player doesn't know their language

source/Engine.cpp
**Bug fix**
This PR fixes #10454.
The cargo collection message now excludes destroyed ships.
Alternatively, we could just remove those ships from the player ship list, but currently they stay there until next landing, because this allows showing them as destroyed in the player info panel.
yes™
N/A
=> fix(ui): Don't include destroyed ships in the fleet cargo message

source/Planet.cpp
**Bug fix**
This PR fixes #10051.
Now, if the planet doesn't have a custom defined spaceport, but is still supposed to have a spaceport, the game chooses between the uninhabited and normal default configs, depending on the `uninhabited` planet attribute.
Tested with the save file provided in the original issue.
N/A
=> fix(mechanics): Update default uninhabited spaceports properly

data/governments.txt
**Bug fix**
When the Incipias were added with their new Quarg government, the Heliarch did not get a negative reputation toward that new government. This adds that, and alphabetizes the Heliarch `reputation toward`s, just because I was right there anyway.
N/A
No.
Not really.
=> Fix: Heliarch no longer like Incipias Quarg

data/sheragi/sheragi ships.txt
Thanks to MidnightPlugins for reporting. 
**Bug fix**
This PR addresses the bug described by MidnightPlugins in Discord.
Black Diamond hull repair is currently not delayed due to not having proper "delayed hull repair rate" and "repair delay" attributes introduced in 10.7. This PR makes 2 changes:
- `"hull repair rate" 1` --> `"delayed hull repair rate" 1`
- `"hull delay" 60` --> `"repair delay" 60`
Tested a Black Diamond in current state and with the fix.
N/A
N/A
=> [Bugfix] Delay hull repair on Black Diamond

data/coalition/lunarium intro.txt
**Bug Fix**
Fixes #9792.
Adds and clears conditions so that questions properly disappear after selecting.
None
None
None (issue had none)
=> Lunarium Intro: questions properly disappear

data/quarg/quarg outfits.txt, data/quarg/quarg ships.txt
**Bug fix**
Fixes #8515.
Tweaked the Quarg Nanotech Battery description so that it no longer says that it is "less than a third the size", the human battery nerf changed that.
None
None
None - I don't steal.
=> Quarg battery description fix

data/successors/successor 1 prologue.txt, data/successors/successor fleets.txt, data/successors/successor side missions.txt
**Bug fix**
This PR addresses bugs and unintended behaviors described on the Discord [here](https://discordapp.com/channels/251118043411775489/1287895983207878686/1288231585132314644). 
* `Successors: First Contact 3` now offers only if `Successors: First Contact 2` has been completed
* Civilian Successor and People's Houses fleets can no longer carry High Houses outfits in their cargo
* Mining fleets and High Houses naval fleets no longer carry cargo
* The `end` labels in `Successors: Predecessor Research 1` and `Successors: Biology Research 1` now contain a sentence so the conversation does not proceed to a blank `(done)` screen.
Missions offer and complete as expected. Scanning Successor fleets shows they do not carry outfits in their cargo that they shouldn't be able to have.
=> (fix): Successors mission and fleet fixes

data/successors/successor 1 prologue.txt
**Bug fix**
I made a significant error in my previous PR; the `Successors: First Contact 2` mission always reaches a `decline` endpoint and is never `done`. Adding `has "Successors: First Contact 2: done"` to the offer conditions of `Successors: First Contact 3` prevented it from offering. This PR fixes that by changing that `done` requirement to `has "event: successors: first contact wait"` instead, allowing FC3 to offer both at all and during the same day as FC2.
Hopefully better than last time. First Contact 2 Prompt, First Contact 2, and First Contact 3 all offer and complete as expected. Also provided a save so you can verify.
[Done Declined.txt](https://github.com/user-attachments/files/17154873/Done.Declined.txt)
=> (fix): Successors First Contact 3 offer fix

data/successors/successor side missions.txt
**Bug fix**
This PR addresses the bug/feature described in issue #10506.
Add a missing `branch` condition so that `flee` works in the Successors United Defense mission.
TomGoodIdea pointed out why it didn't work: https://github.com/endless-sky/endless-sky/issues/10506#issuecomment-2378748602
None
Works for me
Use the save from the issue
=> Add a missing branch condition for Successors Unified Defense

data/human/news.txt
**Typo Fix**
Typo fix: guerilla -> guerrilla.
Guerilla is spelled with two r's on the next news line, and from what I could find people seem to prefer guerrilla. For example, Marriam-Webster lists guerilla as an alternate spelling.
None.
None.
Not really.
=> Guerilla -> Guerrilla - human news.txt

source/PlanetPanel.cpp
**Bug fix**
Fixes #10504.
When the player is dead, the planet panel automatically closes itself and any other panels that are higher, including any conversations and dialogs that appear. This, combined with the fact that atrocities kill the player as soon as the death sentence dialog/conversation is displayed, causes the conversation to disappear.
With this fix, the planet panel closes only itself (and its children), leaving the death sentence panel until the player closes it manually.
N/A
Tested with the save file provided in the issue.
N/A
=> fix(mechanics): Prevent death sentences from closing automatically

.github/workflows/projects_check.yml
This PR addresses the bug/feature described on [discord](https://discord.com/channels/251118043411775489/536900466655887360/1289041499232796683) and in #10511.
Github is migrating the `ubuntu-latest` tag to Ubuntu 24.04, which has a newer python/pip setup. This new setup doesn't allow installing system-wide packages by default, which breaks our setup.
I added the `--break-system-packages` option, which re-enables the previous behaviour. This is the same fix that was applied by @MCOfficer in the [plugin repo](https://github.com/endless-sky/endless-sky-plugins/commit/464b663c245252586df8327e5f31afb7b18795f6).
The checks passed here.
=> fix(ci): Fix dependency installation for python checks

data/successors/successor weapons.txt
**Balance**
This PR addresses the bug described on [discord](https://discord.com/channels/251118043411775489/536900466655887360/1290537627434614897)
Turrets generally require at least one crew member. These don't seem too special, so that's the number I went with. This should also avoid redoing the bunk count of successor ships using these turrets.
=> fix(balance): Add required crew to Successor turrets

source/LineShader.cpp
**Bug fix**
This PR addresses the bug/feature described in issue #10520
This adds the required precision specifiers to the LineShader code to allow it to compile and work properly on OpenGL ES. `highp` is used, but should always present in OpenGL ES 3.0 compatible systems according to the spec, which I believe we are targeting.
=> fix(ui): Fix compilation error & visuals for LineShader in GLES

data/successors/successor 1 prologue.txt
**Bug fix**
This PR addresses the bug described [on Steam](https://steamcommunity.com/app/404410/discussions/1/4848778277267041650/).
`Successors: First Contact 2 Prompt` no longer offers after `Successors: First Contact 2` has been offered. Because `to offer` and `to fail` conditions are ANDed together rather than ORed, the mission wasn't failing to offer appropriately. Who knew the fundamentals of Boolean algebra were so important?
I reproduced the steps listed in the bug report and confirmed that the error did not occur. I also played through all the mainline `Successors: First Contact` missions from a fresh save post-fix and can confirm that this fix does not introduce any new issues to them that I can see.
Let me know if you really …
=> fix(content): Successors FC2 Prompt does not offer after FC2

data/successors/successor side missions.txt
**Bug fix**
This PR addresses the bug described ~~where else but on [Discord](https://discord.com/channels/251118043411775489/536900466655887360/1290992266592260137)~~
You get clearance to land for the `Successors: Predecessor Research 1` mission.
No
Not yet.
None.
=> fix(content): allow players to land to complete Successors: Predecessor Research 1

data/kahet/kahet missions.txt
**Bug fix**
This PR addresses the bug described on [discord](https://discord.com/channels/251118043411775489/536900466655887360/1290124748797513839)
This can now only offer on Hai and human quarg settlements, as those are the only ones where the human languages are spoken properly. It's also restricted to ringworlds to better fit the wording.
Not yet.
None yet.
=> fix(content): Make `Ringworld Debris: Quarg` not offer on Incipias Quarg planets

data/human/deep missions.txt
**Typo fix**
This PR addresses the bug described on [discord](https://discord.com/channels/251118043411775489/536900466655887360/1290648766298325085)
The content had the incorrect word; it was talking about the past, so it couldn't have been their descendants.
=> fix(typo): `descendants` -> `antecedents` in Stone of our Fathers

data/map systems.txt
**Bug fix**
This PR addresses the bug/feature described on [Discord](https://discord.com/channels/251118043411775489/536900466655887360/1290502371348185168).
Most of the new systems added with the Incipias were missing a defined government, causing Vulpa to display wrong and potentially causing future problems. Now they're all `Uninhabited`.
Flew to Vulpa to make sure 
Any save with a gaslining ship should work. Unfortunately, my testing save had non-vanilla content, so...
~~The game now crashes 300% more often before being opened.~~ N/A
=> Fix(content): Add missing government definitions to Incipias systems

source/Conversation.cpp
**Bug fix**
Thanks to acquire_squids on Disocrd for reporting this.
The correct syntax is `to display`, but the error message says `to show`.
This PR updates the message to describe the correct syntax.
No.
=> Correct the error message for incorrect syntax in the children of a text node within a conversation

CMakeLists.txt, resources/EndlessSky-Info.plist
**Bug fix**
Reported by comradecandy on Discord.
Some of the substitutions in the info.plist file used included in the MacOS package are incorrect, and so those values are not being correctly set by CMake.
One of the issues this results in is the name of the whole package needing to be the same as the executable within it. If the package is renamed, MacOS will no longer be able to find the executable within it and it will no longer run.
This PR corrects the substitution used for the executable name so it should be set correctly by CMake, as well as correcting syntax for the bundle identifier replacement and the name used for the minimum version replacement.
We'll see when it builds.
=> Fix mac os info.plist entries

data/successors/successor jobs.txt
**Bug fix**
This PR addresses the bug described in Discord -- thanks DAK for reporting!
Currently Successor Old & New House rush delivery jobs don't have a minimum distance, so that the rush delivery can have the destination be the same planet you're already on. This PR should be reviewed by @Daeridanii1 
None yet
None yet
=> [Bugfix] Minimum Distance for Successor Rush Delivery Jobs

data/incipias/incipias ships.txt
**Balance/Bug Fix**
Adds a missing `weapon` to Incipias ships so that they explode properly.
None.
Not yet - I'm not a murderer.
Any save file that has a Jump Drive.
=> fix(content): add `weapon` to Incipias ships

data/korath/korath outfits.txt, data/pug/pug outfits.txt, data/quarg/quarg outfits.txt
**Balance**
With the changes to the boarding calculations made recently, `capture defense` will now come into play every round, rather than only on rounds the AI chooses to defend. This will make it far more powerful.
This creates a problem, because for a while we have been balancing capturing around the low capture defense exploit - and hence, made that exploit the only way to capture many things. In order to preserve the best-case performance while no longer requiring this exploit, we need to scale down the defense of these outfits to balance out the fact that that defense comes into play more often.
I have divided the defense of these outfits by 2.5. This is based on some screenshots of boarding combat prior to this change, which seemed to suggest about a 5:1 ratio between the enemy …
=> feat(balance): Rebalance certain defense-heavy outfits to account for defense being used more often.

.github/path-filters.yml, .github/workflows/cd_release.yaml, .github/workflows/ci.yml, .github/workflows/compute-changes.yml, steam/docker-compose.yml
This PR removes unused configurations from the steam docker config and enables an extra test. It also applies some generic fixes to the CI setup.
- We don't use the x86 steam builds anymore, so those configurations were removed from docker.
- The existing test configuration for the x64 build was added to the CI via a new job.
- ~~Changes in the `sounds` and `images` directories can now trigger the CI, as there are errors that can be generated from only these data changes.~~
- The CI trigger for release branches was removed, as we don't use release branches and no other workflows are configured to work with them.
- The CI can now trigger for changes made only to the path filter configuration. (If it doesn't affect the CI, all jobs get skipped.)
Workflows.
=> fix(ci): Remove unneeded Steam configurations from CI and enable testing for Steam

data/human/culture conversations.txt
**Bug fix**
This PR addresses the bug/feature described on [Discord](https://discord.com/channels/251118043411775489/536900466655887360/1293446118386176032).
Makes the Earth Day Blackout mission offer in April instead of May.
No.
None
Go land on Earth on April 22nd.
=> fix(content): make Earth Blackout offer on the right day

source/Date.cpp
**Style**
Renamed some variables from snake_case to camelCase (as required by the style guide).
=> fix(style): Use camelCase for variables

source/Flotsam.cpp, source/Flotsam.h, source/Ship.cpp, source/Ship.h
**Bug fix**
This PR addresses the bug/feature described in issue #6727
Currently, when cargo is dumped, it is moved to a list of "jettisoned" items which are gradually added to the global collection of `Flotsam` to make them appear in system. When this process occurs for a carried ship, items are instead essentially discarded because the ship is considered to be outside the player's current system.
This PR instead passes any items to be jettisoned by a carried ship up to its carrier, from which they will be jettisoned normally.
Using the attached save file:
- Take off.
- Open the player info panel.
- Navigate to the ship info panel page for either of the two Daggers.
- Dump their cargo.
Without this PR, the cargo is removed from the ships but no flotsam appears. :(
With this PR, flotsam …
=> Don't delete cargo dumped from a carried ship

.github/pull_request_template.md
**GitHub**
PR templates now have **Typo fix** as an option for a header.
Also added **Refactor** at the request of TomGoodIdea.
=> Two new pull request template categories

data/human/jobs.txt
In a similar vein to #9501, it's been brought up that the strike breaker jobs offer far more often than what should be expected. This PR reduces the offer rate of the jobs ~while increasing their payment~.
=> feat(content): Reduce offer rate of Strike Breaker jobs

data/gegno/gegno I corroboration.txt
**Bug fix**
Reported on discord, someone was offered "Gegno Intervention" after the current extent of the new missions, when it is supposed to be an alternate version of "Gegno Anticipation". Although the player did the latter, they eventually met the conditions for the former (enough negative rep/actions), which still offers even if the other has already been offered. Added said conditions.
Not sure if I need to add a patch fix yet.
Soon if needed.
Soon.
=> fix(content): "Gegno Intervention" no longer offers if you have done "Gegno Anticipation"

source/AI.cpp
**Feature**
When a ship dumps cargo as part of "appeasement", it sends a message requesting its attacker take its cargo and leave it alone. This message is visible to the player, even if that government will otherwise not communicate with the player in a way they can understand.
This PR skips sending that message if the government has a "language" that the player does not know.
I didn't.
Maybe I'll add one later.
=> Don't send the appeasement message from "mute" ships or when the player doesn't know the language

data/remnant/remnant 2 cognizance.txt
**Bug fix**
Plume is a tangible passenger who takes up a bunk in Cognizance 6. But he turns into a ghost in 7, not needing to occupy a bunk.
=> Prevent Plume from turning into a ghost in Remnant: Cognizance 7

.github/workflows/projects_check.yml
This PR adds a missing `setup-python` step to the old copyright action.
The missing setup step results in using the python and pip version shipped by the runner image, instead of what we configured to use. This can break the check when the runner version changes, as seen in #10522.
Github [reverted](https://github.com/endless-sky/endless-sky/pull/10522#issuecomment-2418780018) the change as it broke too many things, but as we already fixed our setup, github broke it again.
The setup-python action is more stable, as it installs a python environment that is not externally managed. It also ships a new enough version of pip that it recognizes the `--break-system-packages` option. Using this action should therefore help us avoid future breakages due to ubuntu version changes. …
=> fix(ci): Add missing setup-python step to the old copyright check

source/OutfitterPanel.cpp
**Bug fix**
This PR fixes #10605.
Currently, non-installable outfits (such as minerals and Void Sprite Parts) for some reason are excluded from being displayed as "in stock" even though you can still buy them directly to cargo. This PR fixes this problem.
yes.
N/A
=> fix(ui): Show sold non-installable outfits as "in stock"

data/remnant/remnant 2 side missions.txt
**Bug fix**
This PR addresses the bug/feature described in issue #10644 (and several reports on Steam, linked in the comments of that issue).
The mission "Remnant: Shattered Light 3" spawns a "ghostly" Shattered Light in Lucina. The player is to carry out an outfit scan of the ship and land on Far Monad in that system.
After scanning the ship and landing on Far Monad, the player is offered "Remnant: Shattered Light 4", which "fails" the preceding mission when it is offered.
However, by the time new missions are instantiated and offered, the processing of existing missions is already finished and so failed missions will not be removed until the next time the player lands on a planet.
This results in the "ghostly" NPC spawned by mission 3 persisting, while mission 4 spawns its own NPC that …
=> Fix Shattered Light duplication

data/human/culture conversations.txt
**Content**
This PR increases the **fire rate of culture conversations that occur on only a single planet from 1% to 10%**. Today, all culture conversations have only a 1% chance of occurring. This means a player will need to visit a spaceport ~230 times (1-0.99^230) before there is a 90% chance of seeing a culture conversation. For many culture conversations, the source can be multiple planets so that these visits can at least be spread across multiple locations, but it is unlikely a player will visit a single planet's spaceport over 200 times. 
This change makes it so that a player will have a 90% of seeing a culture conversation after only 22 spaceport visits when the culture conversation can only occur on a single planet. This is much more comparable to other culture missions that …
=> (Content Tweak) Increase Frequency of Single Planet Culture Conversations

data/quarg/quarg missions.txt
**Bug fix**
The Quarg First Contact conversation is restricted to human and Hai Quarg. I'm making this PR after landing on Spec Inci and getting the Quarg First Contact while wondering if the Quarg can give me advice about the Incipias.
=> fix(content): restrict Quarg First Contact from offering on non-human/Hai worlds

data/map planets.txt
**Typo fix**
This PR addresses the bug/feature described in issue N/A
The description of Successor space planet Khosa-Kella-Oa says it's at the eastern end but it is at the southern end.
(You could arguably say southwestern end of Successor space, but it's the southern end of the entire galaxy which is the interesting part)
=> Khosa-Kella-Oa is at the southern not eastern end

data/korath/korath variants.txt
**Bug fix**
In #10682, the "Korath Piercer Launchers" on these variants were replaced with the new version of that outfit, "Piercer Missile Launcher".
Those variants also carried the ammunition "Korath Piercer" for the deprecated launcher which were not replaced.
This PR replaced the "Korath Missiles" on those variants with "Piercer Missiles", which correspond to the new "Piercer Missile Launchers".
Literally nothing.
=> Replace deprecated "Korath Piercers" with "Piercer Missiles" in some variants

data/_ui/tooltips.txt, source/Engine.cpp, source/Ship.cpp
**Feature**
This PR is an alternative to #10510.
Currently, a ship with no jump sounds or scan sounds listed will play the default sounds.
This PR adds attributes that can be used to prevent the playing of those default sounds (or any other sounds that may be present on the ship).
~The silent jumps is only applied to ships that are not the flagship. It could also be done for the flagship, but that would just remove an indicator to the player that they have jumped, which seems unnecessary and unhelpful. It certainly wouldn't serve the purpose of having a ship stealthily follow the player.~
~Similarly, scan sounds from player ships will not be silenced, since this would just remove an indicator for the person playing the game.~
```
ship "whatever"
attributes
"silent scans"
ship "whateverer" …
```
=> Silent scans and jumps

source/PlayerInfo.cpp
`sold`, the integer used to store the tons of excess outfits and commodities are sold when taking off, is calculated before the cargo is removed from cargo. However, if the player is landed on a planet with an outfitter, outfits are stored instead of sold. Despite this, the take-off message still considers the outfits as being sold for zero credits. This PR subtracts the mass of outfits stored this way from the amount of excess cargo sold, and appends the tons of outfits stored to the main message.
- Took off with 40 tons of outfits in a Shuttle. Game wrote out that 20 tons of outfits were stored.
- Took off with 50 tons of cargo. Game wrote out that 30 tons of cargo were sold.
- Took off with 40 tons of outfits and 10 tons of cargo. Game wrote out that 10 tons of cargo were sold and 20 …
=> fix(mechanics): Outfits stored on take-off no longer count towards excess cargo sold

source/CoreStartData.cpp
**Feature**/**Bug fix**
If your current system is invalid, the game teleports you to the place where you started the game. But what if that location is invalid too? You have an opportunity to visit the famous 0 0 system (#2369) with no way out, even with a jump drive.
The game already switches to the vanilla starting point (New Boston) in some cases, so I've enabled it also in this case.
Load [this](https://github.com/user-attachments/files/17529788/nullsystem.zip) test plugin. Start a new game with the start provided by the plugin, then disable the plugin and load the pilot. On master, you stay in the 0 0 system; with this patch, you are transported to New Boston.
N/A
=> feat(mechanics): Fall back to the vanilla starting location when a custom one is invalid

source/AI.cpp
**Bug fix**
This PR addresses the bug described in #10620.
Ships will now stop completely when ordered to and their velocity is exceedingly low. This shouldn't affect ships that try to move at a low speed. 
I did not observe any movement with these changes. I tested with various heavy ships that didn't always stop properly in the old version.
=> fix(mechanics): Stop ships when their velocity is exceedingly low

source/text/Format.cpp
**Refactor**
Refactors `Format::Credits` to store million, billion, and trillion threshold values and suffixes in an `std::array<std::pair<int64_t, char>>` instead of two `std::vector`s.
Related: https://github.com/endless-sky/endless-sky/pull/10473#discussion_r1769378014
The unit tests test it.
=> refactor: use constexpr array for formatting credits

data/_ui/tooltips.txt, source/DamageProfile.cpp, source/OutfitInfoDisplay.cpp
**Feature**
This PR addresses the feature described in issue #5805 
While you are cloaked, your shields' permeability is increased by your `cloaked shield permeability`
Stacks additively with the existing permeability attributes; final permeability value is safely bounded to be below 1 to prevent unintended behaviour.
```
outfit "cloaking device that makes shields slightly less efficient while active"
...
"cloaked shield permeability" .1
```
```
outfit "cloaking device that makes shields entirely defunct while active"
...
"cloaked shield permeability" 1
```
Put `"cloaked shield permeability" 1` on the cloaking device, and confirmed that my shields were pierced by non-piercing weapons when I was cloaked, and when I was in the process of cloaking or decloaking, but not when I was uncloaked. …
=> feat(mechanics): Cloaked shield permeability

source/ShipJumpNavigation.cpp
**Bug fix**
This PR addresses the bug/feature described in issue #10462 
#10462 describes that a system with higher jump range override isn't working. The problem was a validation check added 2023, in #9289 which invalidates the selected travel plan. That code used the system's jump range incorrectly, assuming it could only lower the range. This bugfix has the system's jump range override the ship's range, since it can be higher .
Edit map systems.txt and set "jump range" to 500 for whatever system you're in (with a jump drive). See that plotting and taking a course works as expected.
N/A
=> Fix #10462: Systems with increased "jump range" work

source/Engine.cpp
**Bug fix**
This PR addresses the bug/feature described in issue #10713
The size of the outline was not taking into account the `scale` property of the `Body`, so the outline was always using the original size of the sprite instead of scaling it as appropriate.
This PR applies the `scale` to the outline as it is drawn.
before | after
-- | --
What it took to make the above screenshots.
[test test 2.txt](https://github.com/user-attachments/files/17558797/test.test.2.txt)
May be noticeable on some particularly low performance systems (likely only old ones) with particularly complex or large sprites or large scales, but just turn the outline off in such cases? The alternative is that the outline is just wrong which is hardly a good option.
=> Fix flagship highlight with scaled ship sprites

source/MapPanel.cpp
**Bug fix**
This PR addresses the bug/feature described in issue #10722
Restoring this piece of code from merge conflicts from recent #6940 merge. Seems to fix this easily reproducible mid-jump navigation hiccup, where simply creating a new path that backtracked would break it.
New game shuttle, chart a few systems, plot courses 2 jumps away, set new path, mid-jump now works fine
=> Fix navigation while mid-jump

data/gegno/gegno ships.txt
**Typo Fix**
This pull request fixes a bug described in a comment on the Gegno PR.
Gniess-> Gneiss in the description of that ship.
=> fix(bug): reference the Gneiss in its description correctly

source/PlanetPanel.cpp, source/PlayerInfo.cpp
If you try to run `PoolCargo()` while you have more cargo than you have cargo space, then not all your cargo ends up being unloaded from your ships. This leads to some bugs, as seen by following these instructions:
1. Start a new save and buy a Star Barge.
2. Get more than 20 tons of cargo by buying commodities/accepting jobs.
3. Sell your Star Barge and buy a Shuttle.
4. Attempt to take off and back out of the warning dialog saying that you don't have enough cargo capacity.
5. Notice that the amount of free cargo space you have has suddenly increased.
6. Attempt to take off again, and see that the take-off warning lists you as needing to get rid of more cargo than the trade panel says you do.
This PR fixes this bug by temporarily uncapping the player's cargo and bunk capacity while …
=> fix(mechanics): Fix bug where over-capacity fleets don't unload all their cargo

.github/workflows/cd.yaml, .github/workflows/cd_release.yaml, .github/workflows/ci.yml, vcpkg-configuration.json
Updated the vcpkg baseline to [c82f74667287d3dc386bce81e44964370c91a289](https://github.com/microsoft/vcpkg/commit/c82f74667287d3dc386bce81e44964370c91a289).
I've chosen this version, because the latest one is only 2 days old.
There's an important (in my opinion) [fix in vcpkg's openal version](https://github.com/microsoft/vcpkg/commit/35afd117ef1d1120af32edc4ba14aa9f4165246e), which enables sound on Windows XP.
=> Update vcpkg packages

data/sheragi/sheragi outfits.txt
**Bug Fix**
This PR addresses the bug/feature described in issue #10729 
Added a `"fuel cost" 100` to the Fusion Drive, so that it shows up correctly.
This doesn't change how much fuel it costs to jump, because the default is 100, but is a workaround for the moment until the underlying issue of #10729 is addressed.
=> fix(bug): display the fuel cost for the Fusion Drive correctly 

source/Engine.cpp
**Bug fix**
If your ship is destroyed and you attempt to land on a planet, a message incorrectly appears, stating that you are landing on the planet, even though your ship is destroyed.
I have fixed this issue by adding a check to verify that the ship is not destroyed before displaying the landing message.
```
if(!flagship->IsDestroyed())
Messages::Add("Landing on " + planet->Name() + ".", Messages::Importance::High);
```
Before:
After:
See screenshots
N/A
=> Fix destroyed ship landing message

data/gegno/gegno ships.txt
(Choose one heading, or add your own.)
This PR addresses a writing suggestion brought up by @Arachi-Lover in discord.
After the Gegno ships were re-balanced before their introduction to the game, the Slate received a bit more love than the Mica or Shale, gaining a bit more cargo than it started out with and fell into the Light Freighter role.
The current description talks about it being a Shale variant that is slightly larger for the larger Vi with some cargo room to spare, but the stats suggest it got a decent amount of cargo room increase from the Shale. Edited the description to reflect this better.
N/A - can just read the PR changes, since the description is shorter.
=> feat(content): Adjust Gegno Vi Slate description

data/map planets.txt
Sandsnap's description touches the bottom of the textbox, which we try to avoid. This PR cuts out some of the descriptors and words in the description that don't hurt the original meaning or writing of the description to resolve the issue.
Before:
After:
It's fairly easy to get to the system.
=> fix(content): Shorten Hai station Sandsnap's description

data/human/news.txt
The news entry "betelgeuse stolen ship advisory" can overflow the text box, as evident in the below image. This PR reduces the length of one of the longer lines in the third word section, as the other two are shorter. Still might need testing considering the length of the phrases in the fifth word section.
I only have a before image at the moment - it's hidden behind a dialog because I rushed to take it. If it's really necessary, I can sit and spam news or make a plug-in for it to come back (unless someone else gets to the clicking before me). 
N/A - news is RNG. Though, for extreme testing, could test this in a plug-in of sorts.
=> fix(content): Shorten News entry about Betelgeuse ships

data/globals.txt, data/starts.txt
This PR addresses parts of #10741 
This PR makes the unlocks requirements for the Hai start clearer, by directly stating that it's locked under `on display`, and that you need to complete the FW campaign under `on reveal`. It also adds a mission that notifies the player that they've unlocked the start when they land in a save where they've completed the main plot and have asked the Hai about the Unfettered. To make this mission work as cleanly as possible, `"main plot completed: global"` has been removed, and the Hai start now directly checks for a global condition set by the Hai start notification mission.
The description for the `on reveal` is also slightly shorter to make space for the unlock requirements.
Tested `"Ask the Hai about the Unfettered"` followed by `"main plot completed"` …
=> feat(content): Clarify unlock conditions for the Hai start

.editorconfig
**Code Style**
a few `.editorconfig` settings that Visual Studio will use to enforce the code style:
- New lines for control blocks
- Align the pointer `*` to the right
- No space after if
(More could be done but these trip me up all the time)
Possible values are here:
https://learn.microsoft.com/en-us/visualstudio/ide/cpp-editorconfig-properties?view=vs-2022
Global settings are in Tools -> Options -> Text Editor -> C++ -> Code Style -> Formatting -> (various) which are overridden by the value in .editorconfig
(I dunno where the actual code style rules are and if they exist, why doesn't visual studio know about them already so I have to duplicate them here)
=> Some editor config updates that at least Visual Studio uses:

data/human/variants.txt
**Bug Fix**?
This PR addresses the bug described on Discord.
Removed a duplicate `outfit` node in the `Splinter (Tractor Beam)`'a definition.
=> fix(bug): remove duplicate outfits node in a Splinter variant

data/gegno/gegno ships.txt, data/remnant/remnant 2 cognizance.txt
**Bug Fix**
**Typo Fix**
Removed a duplicate `"launch effect" "scin launch"` from the Feldspar and fixed a typo when Torza gestures.
=> Remove a duplicate Scin bay definition and fix a Remnant typo

data/human/free worlds 1 start.txt
This PR gives `"Tarazed neutrality"` a delay of 0, meaning that the new outfits and government changes are immediately available after completing the mission, instead of needing to take off to see the changes.
[Meat Girl.txt](https://github.com/user-attachments/files/17639162/Meat.Girl.txt)
=> fix(content): Make "Tarazed neutrality" apply immediately

data/map systems.txt
This PR addresses an issue raised in discord by Witch in discord, along with some other cases.
This PR fixes a few overlapping orbits in Gegno systems Zeinar, Heutesl, and Scija (which ironically are all three capital systems).
N/A - did it in an editor.
N/A
=> fix(content): Fix overlapping planets in a few Gegno systems

data/hai/hai jobs.txt
**Bug fix**
Prevents Hai tourism missions from having a station as their destination, as these are implied to be for Hai who want to go on a vacation to a Hai world that's mildly dangerous and unpredictable - a Hai station does not fit that bill. 
TBD
TBD
=> fix(content): Stop Hai tourism jobs from using Swiftsong as a destination

data/human/human missions.txt, data/korath/korath missions.txt, data/starts.txt
**Bug fix**
This PR addresses the bug/feature described in issue #10741
I made sure the conditions after starting with the hai start were the same as with normal play if one did these missions.
I also spotted inconsistencies in how the First contact conditions were checked and made them only check for offered in the hai cases.
I don't think it's needed since it's just condition updating.
=> Bugfix: hai first contact conditions in hai start and other

data/coalition/coalition culture conversations.txt
**Content**
#10663 increased the frequency of single-planet culture conversations, but didn't check for non-human culture conversations that met the same criteria.
This PR increases `Coalition Incident: Ring of Wisdom`'s offer chance to 10.
=> tweak: update a Coalition culture conversation

data/map systems.txt
**Balance**
Because the Korsmanath A'awoj (the largest ship in the game) became significantly slower (-45%) after the mass rebalance, it now spends longer in-system (be that turning around to jump, or flying in to land somewhere). As a result, the number of Korsmanath A'awojs in these systems became higher.
This PR reduces spawn rates accordingly, meaning the number of Korsmanath A'awojs in a given system should now be about the same as it was before the mass rebalance.
=> feat(balance): Reduce spawn rate of Korsmanath A'awoj, so that fewer are in-system at any given time

data/_ui/tooltips.txt, source/Outfit.cpp
**Bug fix**
This PR fixes two regressions introduced in #10732. Related: https://github.com/endless-sky/endless-sky/commit/c11fd9029e2a59edad169fb7925aaf5e033ee122#r148916170
The tooltips didn't show up in-game due to a typo. The fuel cost was also displayed twice if the old "jump fuel" attribute was used instead of the new attributes, as it would be displayed both as "hyperdrive fuel" and as "jump fuel".
I also removed the tooltip for the now-unused jump fuel.
I tested that the tooltips now show up, and the fuel cost is only displayed once.
N/A
=> fix(ui): Fix duplicated display of the new fuel attributes

source/OutfitterPanel.cpp
**Bug fix**
This PR addresses the bug/feature described in issue #10775.
The game will no longer allow you to buy an outfit into cargo or install it on a ship if you have insufficient credits.
before | after
-- | --
N/A
What it took to make the above screenshots.
[test buying ibut not installing.txt](https://github.com/user-attachments/files/17705158/test.buying.ibut.not.installing.txt)
N/A
N/A
Immeasurable.
=> fix(mechanics): Don't allow buying outfits with insufficient credits

source/Engine.cpp, source/Information.cpp, source/Information.h, source/Interface.cpp
**Bug fix** ?
The "fast" method of displaying the "target sprite" and "player sprite" graphical elements of the HUD were not showing proper swizzling colors.
| Before | After | After |
|--------|--------|--------|
| ![image](https://github.com/user-attachments/assets/d46537cd-28c3-4931-bc09-eb30d632928d)| ![image](https://github.com/user-attachments/assets/860fc62c-9637-4e79-8552-df7a8ec6f657) | ![image](https://github.com/user-attachments/assets/874032d4-54fe-4013-8068-e416461a8ab8) |
| no swizzle | pirate | syndicate | 
Another thing, though is that with this "fast" "outline" (i.e. sprites, no outline) there is also no color indicating the threat...
```c++
int targetType = RadarType(*target, step);
info.SetOutlineColor(GetTargetOutlineColor(targetType));
```
I actually don't know what …
=> fix(ui): Apply proper swizzle to 'target sprite' and 'player sprite' in 'fast' 'outline' mode

source/AI.cpp
**Feature**
This PR addresses the bug/feature described in issue #10546
See issue discussion: I've been playing this long enough by now (a month) to feel confident it's okay and has no unexpected drawbacks.
N/A
* "Control ship with mouse" option on, some reverse thruster installed: Steer while reversing by holding down arrow and moving mouse: Works as expected.
* Option is on, no reverse thruster installed: Down arrow orients the ship such that thrusting would counter the current motion vector, while held only, when releasing key orientation goes back to follow mouse. Not really _perfectly_ intuitive, but same as master.
* Option is off, with reverse thrusters: Unchanged, Holding L/R+Down complements L/R+Up as expected.
* Option is off, no reverse thruster installed: same as with option …
=> feat(ui): Allow steering while reversing

data/governments.txt, data/map planets.txt
**Content**
This PR addresses the bug/feature described [on Discord](https://discord.com/channels/251118043411775489/1287895983207878686/1302589645262950501).
The required reputation with the `Old Houses` government to land on Tuur-Aasa-Kaska has been reduced from 15 to 1, making it accessible after completing the `Successors: Trusted` mission. Though its description makes it clear it's a military planet, basic access is permitted on other Successor military planets, so I see no reason why it shouldn't be on Tuur-Aasa-Kaska after the Trusted mission.
Both the `Old Houses` and `New Houses` governments now have `bribe 0` so that they cannot be bribed, similar to most other strict governmental factions like the Republic, for example.
Played through the Successors mainline missions through …
=> fix(content): Old Houses required reputation, bribe-ability 

data/human/ships.txt
**Balance**
This PR addresses the bug/feature described in various discord comments.
Human heavy freighters are slow. They're slow because they have very little engine space for their size. This is deliberate, and I am not changing it here.
However, on top of being slow, they also have a weird acceleration profile - which, counterintuitively, is arguably _more_ responsive than other ships. They reach their top speeds much more quickly than any other ship does.
This is because they have excessively high drag stats relative to their mass.
It has been suggested at various times that heavy freighters should instead accelerate slowly relative to their top speeds. They already accelerate slowly relative to other ships - this is due to the aforementioned low engine space - but relative to their …
=> feat(balance): Tone down the excessively high drag of many human freighters.

.codespell.exclude, .codespell.words.exclude
**Unknown**
Removed aesthetic and related words from `.codespell.words.exclude`, as they are no longer needed. Pointed out by @ziproot in #10797.
=> fix(ghactions): remove aesthetic and variants from `.codespell.words.exclude`

data/incipias/incipias ships.txt
**Bug fix**
This PR increases the ammo count of the stock Venta from 80 to 120, which is its true max capacity.
Just changes the # of ammunition on the stock Venta from 80 to 120.
=> fix: Increase Venta ammo count

source/Date.cpp
**Bug fix**
This PR addresses the bug/feature described in https://github.com/endless-sky/endless-sky/pull/10800#discussion_r1849125539.
Prior to the option to change date formats between DMY, MDY, and YMD, Date::LongString (which is used for the "<day>" substitution in missions) would produce an output of the form "the DDth of Month". 
See: https://github.com/endless-sky/endless-sky/blob/839f5af27fa92c7030284502648e81a1baad0e31/source/main.cpp#L534
And the wiki: 
https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#text-replacements
> <day> = the deadline in conversational form ("the DDth of Month")
However, when adding support for the other date formats, this result was changed to the form: "DDth of Month".
This PR restores the expected "the" preceding the day of the month …
=> fix(text/dates): Date::LongString should output the DDth of Month

data/remnant/remnant 1 introduction.txt
When I played `Remnant: Logistics 1` I had not gotten very far through the Remnant storyline. My character would thus be unaware of the significance of the phrase 'the Embers' in Remnant culture, so I thought it was odd that I could sing about the Embers despite this. This PR removes that reference. 
My last PR (https://github.com/endless-sky/endless-sky/pull/10746) locked this mission behind other missions that would ensure that the player would hear the phrase 'the Embers' before they got this mission, but it was too convoluted and this seemed like the easier solution.
N/A
I changed a few words.
[warp core logistics 1 changes test~original.txt](https://github.com/user-attachments/files/17873680/warp …
=> fix(content): Remove reference to 'Embers' in an early Remnant mission

data/human/human missions.txt
**Typo fix**
This PR addresses the bug described in https://github.com/endless-sky/endless-sky/pull/9977#discussion_r1855392414
The condition name had a tab in it instead of a space. This makes it a different condition, which seems to be an accident. This is also the only place it is used with a tab.
N/A
N/A
=> fix(typo): Fix tabulator character in condition name

source/BankPanel.cpp, source/BoardingPanel.cpp, source/HailPanel.cpp, source/HiringPanel.cpp, source/Information.cpp, source/Information.h, source/Interface.cpp, source/LoadPanel.cpp, source/MapPanel.cpp, source/MenuPanel.cpp, source/MessageLogPanel.cpp, source/MissionPanel.cpp, source/Panel.cpp, source/Panel.h, source/PlanetPanel.cpp, source/PlayerInfoPanel.cpp, source/PreferencesPanel.cpp, source/ShipInfoPanel.cpp, source/ShipInfoPanel.h, source/StartConditionsPanel.cpp, source/StartConditionsPanel.h, source/TradingPanel.cpp
**Bug fix**
This PR fixes a bug where inactive interface buttons would continue to work.
This PR stores the Information object for each Panel, allowing condition checks when an interface zone is clicked in. In addition, interfaces now pass their `activeIf` and `visibleIf` conditions when being added to the panel.
Information got a `ClearConditions()` function to allow reusing it; strings, sprites etc. don't need to be cleared every frame.
I tested that active buttons still work, and that inactive buttons don't. You can verify this by clicking the disabled `Attack` or `Defend` buttons in BoardingPanel, for instance.
N/A
=> fix(ui): Don't generate key presses from inactive interfaces

data/human/human missions.txt
**Bug Fix**
Should fix #10816.
In #10369, numbers at the beginning of mission names were removed. `00 Spaceport Reminder Resetter` was changed to `aa Spaceport Reminder Resetter`. @warp-core pointed out that `minor` missions are offered in reverse alphabetical order. Well, all vanilla mission names start with capital letters, so using "aa" blocks them.
This pull request fixes that by changing the mission to begin with "AA" instead of "aa".
=> fix(bug): Use "AA" instead of "aa" in the Spaceport Reminder Resetter

SConstruct
This PR is inspired by https://github.com/endless-sky/endless-sky/issues/10823#issuecomment-2506543588.
Users who just pull & build and don't track the development actively may not notice that we are deprecating SCons and they should migrate to CMake. If we want to give them some time to figure out CMake, we need to tell them they should do it, instead of just removing SCons support one day and leaving these people in not quite nice situation.
See the screenshot above.
N/A, the SCons readme already says it's deprecated.
=> Warn users that SCons is deprecated and point them to the CMake instructions

data/_ui/interfaces.txt, source/BoardingPanel.cpp
**Bug fix**
This PR fixes two issues on the boarding panel:
1. In the boarding panel, when not in combat, clicking the "Defend" button sends the 'd' key as input, which results in the panel being closed as though you pressed 'd' or clicked the "Done" button.
This PR changes the "Defend" key to sending 'D', so as to not trigger the exit condition when not in combat. The 'd' key on your keyboard will still count as "Defend" when in combat.
2. When in combat, clicking the "Attack" button when attacking is not possible (because you only have one crew and the target ship requires crew) will defend. This PR changes it so that nothing happens, instead.
No.
[test test 2.txt](https://github.com/user-attachments/files/17921408/test.test.2.txt)
Try boarding the disabled Vanguard in orbit and see …
=> Fix boarding panel buttons

data/_ui/help.txt, source/Engine.cpp, tests/integration/config/preferences.txt
**Feature**
This PR addresses the feature described in discussion #10776
While the game shows help messages, they are shown once, and it can be difficult to figure out that it is possible to see them again. This PR adds a third “basic” help message which describes how to view help messages or reactivate them, so that players know that they can review these messages as necessary.
EDIT: Updated screenshot
Made sure the help messaged showed up for the first few days, then did not show up again even after reactivating help.
Make a new pilot.
Not zero, but barely so.
=> feat(ui): Add a help message describing how to see help messages

source/ShipInfoPanel.cpp
**Bug fix**
The ship info display ("I" - click a ship) shows either the pooled cargo hold while landed or the individual ship's cargo hold. The decision is based on whether the pooled cargo is empty or not. This leads to the info being basically incorrect for escorts in other systems.
<details>
After a farming run, where I accidentally captured one of the already plundered ships, so it stayed in Deneb:
Before:
After:
</details>
See screenshots
Negligible
=> Don't override ship cargo display with pooled cargo when not appropriate

source/Preferences.h, utils/check_code_style.py
**Feature**
This PR updates the style checker for Doxygen comments as discussed in #10497
Updates the style checker to allow `///` and `///<` comments in addition to `//` comments. Also updated Preferences.h to follow this new format (both as an example, and to verify that the style checker is doing what it should be doing.)
N/A
N/A (use Doxygen as discussed and specified)
I verified that the script still runs without issues.
I'm not sure if the Wiki update was already done as part of #10497. If not, then that also needs to happen before those new comment formats are actually allowed.
N/A, this is a style checker during compilation. (So doesn't impact our end-users.)
=> style(doxygen): Allow doxygen single line comments from style checker

tests/integration/IntegrationTests.cmake
This PR makes it easier to debug integration test failures by configuring their timeout.
Our (non-debug) integration tests pass in less than10 seconds consistently. Their timeout is 1500 seconds however, which makes for a really long wait if they get hanged up on something.
This PR changes the timeout to 15 seconds, which shouldn't fail well-behaved tests, but should immediately alert us when things go wrong. It also allows for executing the remaining tests without running into github's runner timeouts.
I tested that the tests now compute the timeout to 15 seconds.
Nothing for passing tests, and massively faster progression for hanging tests.
=> feat(ci): More aggressive timeouts for integration tests

source/ConditionSet.cpp, source/PlayerInfo.cpp
**Refactor**
This PR moves the random function, which is helpful for #10810 (since it avoids a special case there)
The on-demand auto-conditions already have a `roll: [nr]` and `roll: [condition]` function, but the `random` function was implemented as a special case in ConditionSet (that code was from before on-demand auto-conditions existed) and not available as a generic condition.
This PR moves the random function to a read-only on-demand auto-condition, similar to how the `roll:` function works.
Just use `random` as before. The change should not be visible externally.
Integration tests `"Clear flagship model condition"` and `"Landing in a system with multiple planets"` have a very large change of failing when random is not really returning random numbers. See #10835 for details. Those …
=> refactor(random): Move random from ConditionSet to on-demand auto-conditions

data/human/human missions.txt
**Typo fix**
Thanks to Algaean on Discord for reporting this: https://discord.com/channels/251118043411775489/536900466655887360/1315020213850210304
One of the "go east" choices leads to text that says you go west.
This PR changes that line to say "east".
=> Fix typo in Dangerou Games 2

data/_ui/interfaces.txt, source/OutfitterPanel.cpp
**Feature**
I often find myself wanting to have a group of ships to be identical - model and outfits. In other words, a successful loadout might be worth having more ships of. To assemble one at a sufficiently stocked port, this is the simplest help I could think of.
This tiny change makes any differences more eye-catching by using a highlight colour for the "installed:" line, but only if all selected ships are of the same base model.
<details>
</details>
If desired, the new colour "outfitter difference highlight", could be set to 1 1 1 0 in a mod to effectively disable this.
Had this in my play-branch for three weeks, works fine.
[Gary from Vault 78.txt.zip](https://github.com/user-attachments/files/18027038/Gary.from.Vault.78.txt.zip) …
=> Outfitter: highlight differences in a group of same-model ships

source/Mission.cpp, source/Mission.h, source/PlayerInfo.cpp
**Feature**
Currently, a mission marked "minor" can only offer one at a time and when no other mission is being offered.
That is, if any non-"minor" missions are being offered, no "minor" missions will be offered, and if multiple "minor" missions may be offered, and no non-"minor" missions, all but the last "minor" mission will be discarded, and only that mission will be offered.
This can be somewhat limiting, so this PR introduces a way to mark a mission as "non-blocking". Such missions will not prevent "minor" missions from being offered; "minor" missions can offer alongside them.
The most obvious use for this would be the spaceport reminder resetter.
The spaceport reminder missions currently work as follows:
1. The "Spaceport Reminder Setter" mission offers on landing (in practice, …
=> Missions that don't block minors

source/GameData.cpp, source/audio/Audio.cpp
**Refactor**
A previous version of #10392 made a change that drastically increased the time taken by "GameData::FindImages" to finish. This function is run asynchronously, as is much of the image loading progress, and so does not block the loading of audio and game data.
Often, this was so long that the "GameLoadingPanel" would have been constructed before it was finished, and all audio and game data would be fully loaded. As a result, 2GameData::GetProgress" would be called which quantifies image loading progress as the ratio of the variables "spriteLoadingProgress" and "totalSprites", in the anonymous namespace of GameData.cpp.
Because "GameData::FindImages" has not finished yet, "totalSprites" is still zero (as is "spriteLoadingProgress").
Therefore, when "GameData::GetProgress" …
=> Improve GameData::GetProgress

source/MapPanel.cpp, source/MapPanel.h
**Bug fix**
This PR addresses the bug/feature described in issue #10840
When drawing mission pointers on the map, they are drawn mission by mission (for active missions).
There is a check on if the destination system of the mission currently under consideration already has the maximum number of pointers allowed for active missions (some spaces my be reserved for available jobs).
If the destination already has enough pointers, drawing the waypoint, stopover, and mark pointers for this mission on other systems are also skipped, resulting in the behaviour where the waypoint pointer on Mimosa is not drawn because the destination pointer for that mission on Aludra is not being drawn because that system already has the maximum number of pointers.
This PR makes it so that pointers on other …
=> fix(ui-bug): Fix mission waypoint/stopover/mark pointers disappearing

data/korath/korath missions.txt
**Typo Fix**
This PR addresses the typo described on [Discord](https://discord.com/channels/251118043411775489/308902312741568512/1317385103126827059)
Otherwise it doesn't make sense.
See the before screenshot.
Before:
After:
Hasn't been tested.
=> fix(typo): Efreti Distress Call: specify a noun in a blocked message

source/Files.cpp
**Bug fix**
This PR addresses the bug described on [discord](https://discord.com/channels/251118043411775489/285540320823869441/1317756034961379328)
Due to an oversight in the recent filesystem refactor, the game's resource path was based on the current working directory, instead of on the executable's directory. This broke certain application bundles when combined with some specific launchers. (Note: it was running fine in the CI and in local builds, as those have a compatible working directory.)
This PR reintroduces the previous SDL call, which should restore functionality even on the systems where I couldn't test it.
I tested that it now works when launching the executable from a different directory in a specific case where it was broken.
=> fix(startup): Fix application directory query

source/Dialog.cpp, source/TextArea.cpp, source/TextArea.h, source/text/WrappedText.cpp, source/text/WrappedText.h
**Bug fix**
This PR addresses the bug reported by @Saugia
Conversations would have a slight height offset following #10323. This PR makes that disappear by conditionally re-introducing the previous behaviour to panels that have yet to be refactored.
After: 
Before:
See screenshots above.
=> fix(ui): Fix conversation height offset

source/test/Test.cpp, source/test/Test.h, tests/integration/config/plugins/integration-tests/data/tests/tests_afterburn_flight.txt
**Feature**
This PR adds an option to the integration test framework to print messages to a terminal
Integration tests running in CI were not very transparent, they either pass, fail or timeout, but it is not always clear why a test passes or fails. This PR adds an option to include debug-messages within integration tests to allow some more information about the internals of the test to be printed to the outside world.
The output should look a bit like:
```
ok 2 Afterburner-flight - Simple depart land
```
Add `debug` statements in integration tests, but please don't add them in long loops.
Ran the integration test (in debug mode) and noticed the output messages appearing on the terminal.
I don't think the integration tests are documented on the wiki.
Test-code only. Should not impact the …
=> test(integration/ci): Option to print debug messages from integration tests

source/ConditionsStore.cpp, source/ConditionsStore.h, source/PlayerInfo.cpp, tests/unit/src/test_conditionsStore.cpp
**Refactor**
This PR removes complex condition-erase functionality that was never used
ConditionsStore had an Erase function, but no code in ES  explicitly erases conditions. Erasing an condition is done implicitly by setting the condition to zero. (And conditions set to zero are never written out to savegames, thus effectively erasing them at save.)
Removing this unused functionality should make the codebase simpler.
N/A
Removed the affected functions and compiled the code. The code was never called.
N/A
This should have no impact. The functions were never used.
=> refactor(conditions): Remove unused condition erase functionality

data/map systems.txt
I gave the Umbral Reach the `shrouded` attribute to make the area more mysterious and considered it a good first use of the shrouded mechanic, though I wasn't entirely sure how I felt about it. After re-thinking it, I feel it is better that the area ultimately does not have the attribute - the UR is about there being an eerie silence and *lack* of something - for everything to be shrouded draws more attention than I feel the area should [currently] have.
Shrouded is a good mechanic for areas that have dynamic reasons for it to exist, such as Successor space and the upcoming Avgi area, where shrouded is a core mechanic for the region. There are actual things to find in those areas, as opposed to the UR, so it's more engaging there and makes more …
=> feat(content): Revert `shrouded` from most Umbral Reach systems

source/Hardpoint.cpp
**Bug fix**
This PR fixes #10442.
Jamming is supposed to reset the reload counter, so that after the (unsuccessful) attempt to fire, you need to wait another reload cycle. But currently there's a bug that causes the cycles to build up, which means that if you try to fire while your ship is scrambled, you may end up with a single "reload" lasting many normal reload cycles.
Edit: this may be even more complicated (see the comments below).
With this patch, a single jam never blocks the weapon for more than one reload cycle.
It's kinda hard to reliably test this, but it seems to work now.
N/A
N/A
=> fix(mechanics): Fix weapon jamming accumulation

data/pug/pug outfits.txt
**Balance**
Reduced the `missile strength` from 40 to 10.
This means one heavy anti-missile turret now expects to score about 4 kills/sec (blocking 2/3 of the incoming fire from a single seeker, or 1/3 of the fire from two), rather than the 1 kill/sec that would have been expected previously (blocking only 1/6 of the incoming fire from a single seeker, or 1/12 of the fire from two).
This should make AM much more useful during the FW pug fights, allowing the Seeker's incoming damage to be mitigated somewhat if you have invested in AM, rather than the current situation where AM becomes effectively dead weight because it doesn't significantly reduce incoming damage.
=> feat(balance): Balance the Pug Seeker's `missile strength` against human AMs

data/human/human missions.txt
**Refactor**
This PR addresses the bug described in pull request #10852.
The Spaceport Reminder mission uses a hacky workaround in order to give a reminder to players to check the spaceport, and is described in the linked PR as follows:
> The "AA Spaceport Reminder Resetter" mission is a "minor" spaceport mission. Because its name begins with "AA", it will not offer unless no other vanilla missions are going to offer; every vanilla "minor" mission will take precedence over this one and all non-"minor" missions will block it (because it is "minor"). (A plugin could define a new "minor" mission that would have a lower precedence than this one, if it really wanted.) When this mission is offered, it updates the conditions set in the previous mission with the current month and year. This …
=> refactor(content): Give the Spaceport Resetter mission non-blocking

source/MissionAction.cpp
**Bug fix**
The recently added functionality for a missio naction to be allowed to trigger even after a mission has failed (but not yet erased) was not persisting across reloads because the "can trigger after failure" property of a mission action was not being written to the save file, and so after the reload, the mission action no longer had that property.
This PR updates mission actions saving to write that line to the save file if the action has the property.
None
=> Fix "can trigger after failure" mission action saving

data/human/human missions.txt
**Bug fix**
This PR addresses the bug described on [Discord](https://discord.com/channels/251118043411775489/308902312741568512/1326183397583749220)
Adds a tab character.
=> fix(bug): fix an overindented `decline`

data/gegno/gegno I corroboration.txt, data/gegno/gegno intro missions.txt
Currently, there is a way to circumvent the "Gegno Genocide Defense" mission in a way that allows the player to land on a Gegno world (mainly Dueyu Eitch) and outfit stolen ships after having provoked their civilians. The `clearance` tag found in some of the intro content is being used to land despite having killed/stolen civilian ships and aborting it after the fact. While most civilian ships are eventually going to be available to the player, the player should not be getting away with murdering civilians and stealing away ships aggressively as they must use a Gegno planet to outfit them.
The main problem with this is the player can actually obtain one of the large Gegno Protolith Generation ships, which were never intended to be obtainable in the …
=> feat(content): Gegno "Unwelcoming" mission that stops `clearance` workarounds

CMakeLists.txt, source/CMakeLists.txt
This PR addresses the bug/feature described in issue #my computer
Removes the module support that enabled itself on the C++20 switch that introduced gcc-specific flags that broke clangd diagnostics, and makes -fno-rtti only active in release modes as it conflicted with the sanitizers.
=> fix(build): Fix clangd errors on project files

source/Files.cpp
**Bug fix**
https://github.com/endless-sky/endless-sky/commit/d67480c35f0984a902d507c698ecf11197fbc0df added an `SDL_GetBasePath` call which should have a corresponding `SDL_free`, as stated in the [docs](https://wiki.libsdl.org/SDL2/SDL_GetBasePath).
yes™.
=> fix: Deallocate the SDL base path properly

source/audio/Music.cpp
**Bug fix**
The paths for audio files were not made relative in the filesystem changes, causing them to not play.
Makes the path relative and stuff plays now.
Listened to it.
=> fix(audio): Use relative path for sounds

source/MapPanel.cpp, source/MissionPanel.cpp
**Feature**
Makes the selected system on the map have a brighter name colour. Useful when there's lots of names clustered in an area.
Clicked on Zubenelgenubi while in Ruticulus:
This does have a slight performance impact, but it is way overshadowed by the DistanceMap route calculation cost.
=> feat(ui): Highlight name of selected system in map panel

source/audio/Audio.cpp
**Bug fix**
Adds back a line that was unnecessarily removed in #10862, in which its absence caused sound effects not to play properly.
Tested before and after; sounds play properly again.
N/A; Pick a ship that has a 3x sound and spam weapons/landing.
=> fix(audio): Re-add missing `alSourcef` line removed from Audio.ccp in #10862

copyright
The image at https://github.com/endless-sky/endless-sky/blob/12bd2b14526809a257cf66f46750f97126aa7011/images/ui/tactical/tactical.png was previously used for the tactical scan display.
It is composed of four separate, disconnected icons all in one file.
In #8172, it those four icons were moved into their own files:
https://github.com/endless-sky/endless-sky/blob/12bd2b14526809a257cf66f46750f97126aa7011/images/ui/tactical/crew.png
https://github.com/endless-sky/endless-sky/blob/12bd2b14526809a257cf66f46750f97126aa7011/images/ui/tactical/fuel.png
https://github.com/endless-sky/endless-sky/blob/12bd2b14526809a257cf66f46750f97126aa7011/images/ui/tactical/energy.png
https://github.com/endless-sky/endless-sky/blob/12bd2b14526809a257cf66f46750f97126aa7011/images/ui/tactical/ther …
=> Update copyright for tactical scan icons

copyright
Following on from https://github.com/endless-sky/endless-sky/pull/10921, this PR modifies the copyright entry for those icons to include a description stating that they were cropped by Zitchas, while still indicating that the copyright owner is Michael Zahniser.
I'm not going to copy-paste the description and conversation on that PR here.
=> Update tactical icon copyright again

tests/integration/config/preferences.txt
Adds some new help messages that weren't marked as "seen" in the integration tests preferences file there so they cannot show up while running integration tests (unless they are requested).
Not currently an issue for any of our integration tests, but doing it now so that it doesn't become an issue later and give people headaches.
Never.
=> Disable all help messages in integration tests

data/avgi/windjammers.txt, data/governments.txt
**Bug fix**
Restores the accidentally deleted player reputation line in the Aberrant government. Also corrects `disabled recovery timer` to `disabled recovery time` on the Windjammer ships.
Shot at Windjammers, watched them recover after being disabled. ~~Didn't actually test the player rep fix with the Aberrant.~~
=> [Bugfix] Quick Aberrant Player Rep Fix + Windjammer Timer Typo

source/ShipInfoPanel.cpp
As reported [on Discord](https://discord.com/channels/251118043411775489/308902312741568512/1331179187511496745).
When opening the ship info panel, the ship is selected as the flagship's target, but not actually selected for the player as the target of orders.
This PR fixes the problem by properly selecting the ship.
yes™
N/A
=> fix(ui): Properly select the ShipInfoPanel's ship

source/PlanetPanel.cpp, source/audio/Audio.cpp
**Bug fix**
This PR addresses a bug where sound effects would get paused even if their playback started after the game paused.
Imagine landing on a planet. The planet panel pauses audio (for reals, this time), and landing popups might also pause audio. This happens in the same frame as the landing sound, so it doesn't cause issues. However, if you visit the spaceport and get a popup there before the landing sound finishes playback, it would get paused. This is unintentional, and is fixed here.
I tested that stuff still pauses and resumes fine.
=> fix(audio): Don't pause sound effects when audio is already paused

source/MenuPanel.h, source/audio/Audio.cpp
**Bug fix**
This PR addresses the bug described in issue #10944
Looping sources would sometimes get moved to the `endingSources` list in a paused state; this PR resumes them when appropriate.
I can no longer reproduce the bug.
=> fix(audio): Fix some paused sources not getting resumed properly

data/human/paradise world jobs.txt
**Bug fix**
This PR addresses the bug described on [Discord](https://discord.com/channels/251118043411775489/308902312741568512/1333017595712110622)
Don't allow the job `"Paradise Job: Wilderness Retreat"` to go to a station, as both the description and `on complete` dialog imply there is a planetside destination.
=> Don't allow "Paradise Job: Wilderness Retreat" to go to a station

data/human/human missions.txt
**Typo fix**
This fixes the typo called out in Discord by Alliat.
=> Fix(Typo) Tim the Stowaway

data/human/deep missions.txt
**Bug fix**
This PR addresses the bug/feature described on Discord by dariusjenai: https://discord.com/channels/251118043411775489/536900466655887360/1333805486428127284
Indents the "decline" so it is a child of the text node above it and treated as an endpoint instead of being used like its own text node.
No.
No.
=> Fix conversation endpoint indentation in "Skadenga Call 5

data/human/human missions.txt
**Bug fix**
This PR addresses the bug/feature described on Discord by phil_4: https://discord.com/channels/251118043411775489/536900466655887360/1333794593040367649
Adjusts the source location filters of the two Dangerous Games missions so they only choose systems between 1 and 100 hyperspace links from the stopover/destination system.
Without this, the second mission can choose Avgi planets as the source. The first mission cannot only because its location filter was adjusted when the Avgi were added to only offer from Republic, Free Worlds, Syndicate, or Pirate worlds. That part of the filter is now gone because the "near" filtering makes it redundant.
None.
No.
=> Improve Dangerous Games source location filters

source/AI.cpp
**Bug fix**
Thank you to various people who have reported this on Discord, and in particular admitus who found a reliable reproduction method.
It is possible for a ship to be recruited to help another ship, usually because that ship has insufficient fuel to jump to another system, and set that ship as its target, but for that ship to no longer need help by a later "step" before the helper has reached it. This would usually be through the use of a ramscoop. It is particularly noticeable when the ship is using afterburners or, I expect, other outfits that consume fuel at a relatively low, but sustained rate, as the ship may only be slightly below the threshold of being able to jump when it asks for help, and so will not take long to accumulate sufficient fuel to no longer consider itself …
=> Fix some issues with escorts jumping around on their own

source/BoardingPanel.cpp, source/PlayerInfo.cpp, source/ShipInfoPanel.cpp, source/ShipNameDialog.cpp
I'm not sure why (maybe a gcc update?), but some files failed to build without these includes.
Example errors:
```prolog
FAILED: source/CMakeFiles/EndlessSkyLib.dir/Debug/ShipNameDialog.cpp.o
/usr/bin/c++ -DCMAKE_INTDIR=\"Debug\" -isystem /usr/include/SDL2 -isystem /usr/include/AL -g -std=c++20 -fdiagnostics-color=always -Wall -pedantic-errors -Wold-style-cast -g -fsanitize=address,undefined,pointer-compare,pointer-subtract,unreachable,builtin,integer-divide-by-zero,vla-bound,null,return,signed-integer-overflow,bounds,alignment,bool,enum,pointer-overflow -fno-omit-frame-pointer -fsanitize=leak,vptr -MD -MT source/CMakeFiles/EndlessSkyLib.dir/Debug/ShipNameDialog.cpp.o -MF source/CMakeFiles/EndlessSkyLib.dir/Debug/ShipNameDialog.cpp.o.d -o …
```
=> fix(build): Add missing includes

data/human/human missions.txt
**Bug fix**
This PR addresses the bug/feature described by @Azure3141 on Discord: https://discord.com/channels/251118043411775489/536900466655887360/1333981172979601450
When a `log` entry in a mission, NPC, or conversation action is followed by only one more token, the text in that node is used as the log text, which is added under the current in-game date to the player's logbook.
When it is followed by two or more tokens, the second token is used as a "special log category" and the third is used as a subheading under which the remaining tokens (and the tokens in any child nodes) appaer as log entries.
The "log" nodes being modified in this PR contained three tokens total: the "log" keyword, followed by the character's name, and then finally the log text. This resulted in the character's …
=> Fix stowaway tim logs

source/text/WrappedText.cpp
**Bug fix**
This PR addresses the bug/feature described by phil_4 on Discord:
https://discord.com/channels/251118043411775489/536900466655887360/1333860535535665326
The tooltip code in ItemInfoDisplay expects the height of its WrappedText object to be "0" when there is no text.
This was originally the case, and remained the case when WrappedText::Wrap was adjusted to not incorporate a final paragraph break into the height of the text (this code was not reached if there was no text so no text = no final paragraph break) but this broke other things so the paragraph break height was optionally added in WrappedText::Height. But, this didn't account for how the paragraph break would not have been included if there was no text initially.
So, ItemInfoDisplay::DrawTooltips expected:
- no text: …
=> Fix tooltip boxes being drawn when there is no tooltip text

data/human/ships.txt
**Balance**
This PR addresses the bug described on [today’s campfire chat](https://discord.com/channels/251118043411775489/1136144420681560064/1335336094895444070).
Multiple people have noted that the Bastion was too slow for a medium warship. This PR starts the process of buffing it by reducing mass and drag, increasing HP, and increasing heat dissipation to account for the reduced mass.
EDIT: Also buffed the Bulwark as recommended by Quantumshark
None.
=> feat(balance): Buff the bastion and bulwark

data/_ui/tooltips.txt
This PR addresses issue #10664 (I'm not sure if we need a tooltip for `quantum keystone` as it doesn't have any special meaning in the engine).
As the title says, added a tooltip for the `automaton` attribute and fixed some typos in the same file.
Checked that the tooltip shows up.
N/A
=> Tooltip for automaton + typo fixes

data/_ui/interfaces.txt, source/MapPanel.cpp
**Refactor**
This PR resolves #5127.
The color used for rendering map rings for unexplored systems is now defined as an interface color.
Looks the same (as it should).
=> refactor(ui): Move the unexplored systems color to the interfaces

data/_ui/tooltips.txt
**Bug fix**
This PR addresses the bug described on discord
Whoever added the flotsam chance attribute in #7942 was incompetent and didn't include a tooltip description for `flotsam chance.` Obviously, this person has no business adding features to Endless Sky, so I took it upon myself to fix their bug-riddled feature and do the work they were clearly too lazy to do.
That would require me to open the game and verify that this works.
haha
Really?
Critical
=> [Bugfix] Add missing `flotsam chance` tooltip

source/Ship.cpp, source/Weapon.h
**Bug fix**
This PR addresses the bug/feature described in issue https://github.com/endless-sky/endless-sky/issues/8041#issuecomment-2638094966
In the situation described, the equipped afterburner lowers the firing ship's "slowness" below zero. Then, when checking if the weapon can fire, it is concluded that it cannot because the available "slowness" is lower than the amount of slowness the weapon consumes, even though the weapon consumes zero "slowness" upon firing.
This PR adds an additional check for each quantity checked in "Ship::CanFire" to ensure that the weapon actualy consumes that quantity.
I note that there are some things, such as shields, discharge, corrosion, burn, and leak, which are not checked in this manner, but I'm not doing anything about that in this PR.
Use the ship …
=> Check that a weapon actually consumes a resource before requiring that the resource amount exceed some minimum value

source/Files.cpp, source/Files.h, source/LoadPanel.cpp
**Bug fix**
This PR addresses the bug reported somewhere on Discord.
Trying to create a snapshot with illegal characters in the file name crashes the game, because a runtime error is thrown before our custom error checking code has a chance to respond.
Tested on Linux with the `/` char.
=> fix(crash): Handle snapshot file errors properly

data/korath/korath.txt
**Balance**
This PR implements the change suggested by Ravenshining [here](https://github.com/endless-sky/endless-sky/pull/10923#discussion_r1935252449)
Adds frugal to `Korath Raid` and `Korath Large Raid` fleets (the two that raid human space).
This should reduce the frequency with which these extremely powerful weapons are used against players in human ships that have no way to effectively deal with them.
This also makes more sense in-universe - it doesn't make sense for the severely resource-limited Korath to use these expensive missiles to blow up flimsy human ships that could be disabled and plundered without using them.
Took some small human ships (a Clipper and a Corvette) into systems with Korath raids with and without the change, observed that without the changes I died …
=> feat(balance): Make Korath raids in human space `frugal`

data/remnant/remnant jobs.txt
**Bug fix**
This PR addresses the bug/feature described in issue #10974
The filters these jobs currently use to select the starting location of their NPC can currently select some systems beyond what is reachable from the core Remnant worlds without a jump drive. Since the NPCs don't have jump drives, this leads to them being unable to follow the player back to the destination.
Additionally, these systems contain Aberrant fleets. This seems out of scope for these jobs which explicitly do not select graveyard systems wher the Ka'het are present.
This PR modifies the filters in these jobs so they will only select systems that can be reached from the Arculus system by wormhole or hyperspace link and are at least 
<details> <summary>The current filters can select any of:</summary>
- …
=> Fix Remnant Rescue 1 through 3 location filters FOR THE LAST TIME

data/human/free worlds 3 reconciliation.txt
**Bug fix**
This PR addresses a bug described on Discord
Added two Daggers to the Aerie in mission `"FW Syndicate Capture 1B"` and adjusted dialog accordingly. Apparently this was missed in the Carrier Rework.
None so far.
=> Add fighters to the Aerie in "FW Syndicate Capture 1B" and adjust dialog accordingly

data/wanderer/wanderers start.txt
**Bug fix**
This PR addresses the bug/feature reported by Midnightplugins in Discord.
In the Carrier update, the Giftbringer was decided not to be adjusted as it is sufficiently strong as-is. However, it did not get redefined bay hardpoints, so on top of the old Carrier weapon configuration, it also has the buffed bay count, which is meant to be an offset of a loss of weapons, not an additive buff.
This PR defines the Giftbringer's bay count to the original 4 fighter bays, as well as gives it a display name since it is now considered a "Modified Carrier" (the sprite name being different than the original sprite was more my concern, but it does make sense to make it visible).
Will get one soon, or if …
=> fix(content): Correctly redefine Giftbringer Carrier variant

source/ShipInfoPanel.cpp, source/ShipInfoPanel.h
**Bug fix**
To reproduce the bug:
1. Open the game.
2. When the sound starts playing, quickly enter the game and open Player Info. Notice that the sound pauses.
3. Select a ship to open Ship Info. The sound unpauses.
yes™.
=> fix(audio): Pause audio on the Ship Info panel

data/avgi/avgi side missions.txt
**Bug/Typo fix**
This PR addresses a bug described on Discord, plus another one I found.
Fixed a few typos in the `Avgi Culture: Twilight Tavern Guard` mission, as well as fixing three `goto` issues.
I'm not 100% that the goto fix was correct, but given the responses I believe it was.
None.
I don't have one that meets the requirements yet.
=> "Twilight Tavern Guard" fixes

data/human/human missions.txt
**Bug fix**
Thanks to @Saugia for reporting this on Twitch.
The first mission in this chain, "Timothy Radrickson 1: Stowaway" is invisible. On the second time of entering a system after it has been received, it shows a conversation where you have the option to ignore Timothy, allowing him to die, murder him, agree to drop him off on the next spaceport you reach, or agree to take him to his desired destination (Rand in the Zeta Aquilae system).
There is a second, visible mission that is supposed to offer the next time you land, only if this first mission is still active (which is only the case if you agreed to take him to Rand), reminding you of this objective.
However, if you take off and then land again without travelling to another system, you can receive the second mission before the …
=> Fix Timothy Radrickson 1a being given inappropriately

data/korath/korath weapons.txt
**Balance**
This PR addresses concerns raised by @Quantumshark regarding the strength of the Firelight missile
This slightly reduces Firelight missile speed and blast radius, removes its IR tracking ability, and downgrades its homing behaviour.
There is a balancing act to be danced with speed and anti-missile strength.  If speed is reduced too much, AM becomes too effective.  The design goal is that one out of every three shots (note how they fire in threes) should be able to get through a PDT, given the Korath use these offensively against the Remnant.  Or, at least one in six, given these are equipped in pairs.  Increasing drag beyond the .12 given here would give a PDT a third shot, requiring a dramatic increase in missile strength.
Blast radius has been reduced to match the scale of …
=> feat(balance): Make firelights jammable, slightly slower, smaller radius

data/human/variants.txt
**Balance**
With the Carrier rework removing the Carrier's main four Particle Cannons and replacing them with more Fighters and stronger munitions, Carrier variants lost their strict forward weapon power. While this is a plus for its role, its a minus for certain situations.
In FW Reconciliation, the Jump variant Carriers no longer have their Particle Cannons, meaning none of the ships escorting the player in these fights, Cruiser or Carrier, have Particle Cannons, which are decent at providing constant fire on ships in Pug fights. The replacements on the Carriers being reliant on munitions means they're susceptible to Pug AM, whereas Particle Cannons are not, so this can spike the fight's difficulty.
This PR replaces the munitions on the Cruiser variants with Particle Cannons. This …
=> feat(balance): Replace missiles with Particle Cannons on Reconciliation's Cruiser (Jump) Variant

data/human/ships.txt
**Balance**
Following the Carrier rework, the now twice as many Lances flying around Carriers with Sidewinder Pods can get a bit unruly in Free Worlds combat missions. Not only do they have the Pods, but they also have ammo racks, so after their initial burst, if you don't seek them out right away, their follow-up missiles can start to put a lot of pressure on you or other ships.
This PR removes their ammo racks, reducing their Sidewinder count from 35 to the original 12. Since these are pods, it kind of makes sense these aren't full-blown launchers with consistent damage and more-so focused around their initial attack. This is also likely more healthy for fights as the ammo rack is a sort of "min-maxing" Lances here, which we probably shouldn't try to min-max everything. The Carrier …
=> feat(balance): Remove ammo racks from Lances

source/Engine.cpp
**Bug fix**
This PR addresses the bug/feature described in issue #10688
Reduces the maximum fuel capacity for which the fuel bar will be drawn with segments from 5000 to 3000 so it doesn't exhibit the issue described in the linked issue.
I considered making the limit dynamic, so that it could account for custom interfaces using a bigger or smaller bar length, but I haven't come up with a way to do that that I like.
Seems like effort.
None.
=> Reduce the maximum fuel capacity at which the fuel bar will be drawn segmented

data/avgi/avgi outfits.txt
**Graphic Fix**
This PR temporarily adds a `scale` factor to the Tachytia's engines, scaling them down to a quarter of what they currently are. This is because with how the game's engine and AI currently work, engine flares flicker during adjustment. Currently they fill the entire screen and go pass it considerably, and halving them still fills up a majority of the screen. This can be concerning visually and possibly cause problems for players up to a point that may cause visual impairment or seizure-inducing conditions. They are still longer than any other Avgi flare 
Once functionality to have engine flares "scale outward" visually when thrusting is added (it is a desired feature), such as from https://github.com/endless-sky/endless-sky/pull/9019, the scale change can be removed. …
=> fix(graphics): Temporarily reduce scale of Z-3600 to prevent visual impairment

source/Command.cpp
Add a fleet jump description. This allows endless-mobile to trigger this command from a button.
**Feature**
This PR addresses the bug/feature described in issue #11012
This just adds a description to the `FLEET_JUMP` command, which can be used as a key for endless-mobile buttons. 
Checked that existing shift+`JUMP` still works as designed.
Checked that `keys.txt` is not affected (since no key is bound to `FLEET_JUMP` by default, and it does not show up in preferences)
N/A
=> Add fleet jump description

data/_ui/interfaces.txt, source/Engine.cpp
**Feature**
The messages on the main panel can now be drawn in reversed order and alignment: newer messages above older, starting from the top edge of the box. It's controlled by an interface value set to 0 by default - it's backward-compatible, so outdated interfaces file won't be a problem here.
<details>
<summary>
Example (I haven't changed the box dimensions, so it looks a bit odd, but it works)
</summary>
</details>
See the screenshot above.
N/A
=> feat(ui): Support for reversing the draw order of HUD messages

source/PlayerInfoPanel.cpp
**Feature**
This PR resolves #10707.
Just what the title says.
See the screenshot above.
=> feat(ui): Show sums of salaries and tributes on the Player Info panel

source/main.cpp
**Bug fix**
They key used to trigger the debug mode pause was erroneously changed in a previous PR. This changes it back.
=> Correct debug mode pause key

source/Dialog.cpp
**Feature**
This PR addresses the bug/feature described in issue #10701
See issue discussion. This implements whole-field copy using Ctrl-C and whole-field paste using Ctrl-V for all string-accepting dialogs (not number-accepting ones).
As mentioned, a "contra" argument would be that it raises unfulfilled expectations, as there's still no "cursor" other than the field's end let alone a selection, so no partial edists and/or partial copy-pasta. Still, I've played with the patch in my codebase for a while and by now think it's better than nothing, and have actually used it once.
As for the sanitizing comment in the issue - this now filters to ascii only.
Does not work for the name of a new pilot - duh, that's not a Dialog.
N/A - not really. 
Just basic - I can paste a ship name from …
=> feat(ui): Allow Copy&Paste in string input dialogs

data/wanderer/wanderer ships.txt
**Balance**
This PR addresses the bug/feature described in Discord by me.
The Autumn Leaf is described as a wartime conversion of the Summer Leaf, but the Autumn Leaf currently functions better in a peacetime capacity than the Summer Leaf, with greater bunk, cargo, and fuel capacity than its less warlike counterpart. This PR makes the wartime conversion have logical drawbacks similar to [what has been proposed for the Heavy Gust](https://github.com/endless-sky/endless-sky/pull/10672).
This change better fits the Autumn Leaf into its lore as a warlike version of the Summer Leaf, and balance-wise gives the peacetime utility niche back to the Summer Leaf and introduces tradeoffs to this ship, which could otherwise make the Summer Leaf redundant in its role.
This PR changes:
1. Bunks to be …
=> feat(Balance): Reducing Autumn Leaf peacetime utility

data/remnant/remnant 2 cognizance.txt
**Typo fix**
This PR addresses the bug/feature described in issue #11098 
Revised wording to restore original intent, while avoiding mis-reading.
=> feat(fix): Revised wording in Remnant Cognizance 2 that were mis-interpreted.

source/AI.cpp
**Bug fix**
Thanks to @TomGoodIdea for pointing this out on Discord.
This expression currently compares a boolean value to 0.9, which is fairly non-sensical.
This is the result of a bracket being misplaced in a previous modification of this code.
This PR moves the bracket to the correct position so that the value compared to 0.9 is the dot product of this ship's current facing direction and the direction to the target, that is, it is checking if this ship is facing mostly towards its target (within approximately 26°).
I don't know how much of an impact this will have on actual AI behaviour, but I expect it might help some ships turn back towards their targets faster, instead of potentially accelerating away from their target after flying past it, which the current code allows.
I've also …
=> fix(code): Fix a misplaced bracket in AI::MoveToAttack

source/ConditionAssignments.cpp, source/ConditionAssignments.h, source/ConditionSet.cpp, source/ConditionSet.h
1. public enums go before everything else
2. no space between functions in the header or a single blank line
3. removed unnecessary prefixes
4. `{` on new line only after `)`
=> fix(style): Minor code style fixes and cleanup for conditions

source/image/ImageSet.cpp, source/image/Mask.cpp, source/image/Mask.h
**Feature**
Currently, if there are lone floating pixels in a ship or asteroid image, the game will output an error about that causing problems while creating the collision mask, but it will only include the dimensions of hte image nad the coordinates of the problematic pixels.
This PR adds the name of the image and the frame number to this message, to make it easier to find the offending file.
Use a bad image.
Without this PR, get a message like:
`Unable to create mask for 60x60 px image: lone point found at (49, 27)`
With this PR, get a message like:
`Unable to create mask for 60x60 px image "ship/asteroid young 3" frame #0: lone point found at (49, 27)`
=> feat(error-handling): Include image name and frame number in collision mask error message

data/human/deep missions.txt, data/human/human missions.txt
This adds a very small invisible mission that makes it so someone who completed Stones of our Fathers 5 prior to getting the update with the Ildico missions can now still get the missions.
=> Ildico Save Compatibility Patch

data/incipias/incipias first contact.txt
**Bug fix**
Hopefully fixes a bug people had where they would perform the missions prior to rescuing the incipia, but then would land on Turra and nothing would trigger.  This doesn't stop it from not working, but it does tell the player that they need to get more passenger space, which should be the only reason the mission does not get offered upon landing.
This PR addresses the bug/feature described in issue #ImadeItUp.png
Bug described by a few discord users where they would land on turra with a gas lined ship, but nothing would happen.
I edited my save file so that the gaslined ship I used did not have enough passenger space to meet the mission requirements.
[incipias testing~3011-01-08incipiarescuefix1.txt](https://github.com/user-attachments/files/19037092/incipias.testing.3011-01-08 …
=> Add "blocked" dialog to incipias first contact.txt

data/remnant/remnant 2 cognizance.txt
**Bug fix**
Fixes #10608.
Added a missing `passengers` line to `Remnant: Cognizance 21`
This number (5) was inferred from a mission or two before.
=> fix(bug): add missing passenger to Remnant: Cognizance 21

data/kahet/kahet missions.txt
**Bug fix**
This PR addresses the bug described on Discord
See the title.
None.
=> fix(bug): remove duplicate log entry in mission `Boarding Ka'het`

data/coalition/heliarch intro.txt, data/coalition/lunarium intro.txt
**Content (Mission Tweaks)**
This PR makes several changes to the `to offer` requirements of the Coalition Intro mission chains, in an effort to make them easier to find and complete, as per the results of the following poll that ran over the course of 2 weeks on the Discord server:
The difficulty in finding and completing the Coalition Intros mission chains has been a recurring topic of discussion on the Discord server, so this PR aims to reduce the need to go into the game files to figure out where exactly to land for XYZ mission.
Changes are as follows:
- Increased the effective offer range for missions that rely on the `near` keyword;
- General increase to the random % chance of offering missions;
- Completely removed the arbitrary number of `"coalition jobs"` required for some …
=> fix(content): Make the Coalition Intros easier to find

data/map systems.txt
**Bug fix**
This PR addresses a bug described by Witch of Many Colours on Discord
Moved Kasii-Tuur-Saqru out a bit from the planet it orbits to prevent overlap. Also moved the moon a little to accommodate this.
I haven't tested every orbit, but it seems to work just fine.
[Successor Station.txt](https://github.com/user-attachments/files/19072930/Successor.Station.txt)
=> fix(bug): fix Kasii-Tuur-Saqru overlapping its mother planet

source/PlayerInfo.cpp
**Bug fix**
Thanks to etherdais for reporting this on Discord.
The Heliarch jump drive jobs expect to fail themselves upon being acceptance, thus not appearing in the mission list.
However, the way a mission failing itself works, it only occurs if the mission is already in the player's active missions list.
A job being accepted is not there until the offer and accept actions have been executed, and therefore, when the job tries to fail itself, it does not succeed because it does not appear to be active.
This PR modifies this process so that a job being accepted is moved to the active missions list before these two actions are executed. Immediately after these actions have been executed, the game will check if hte job is failed and, if it is, removes it.
```
mission "Whatever"
job
on offer …
```
=> fix(jobs-code): Allow jobs to fail themselves on offer or accept

data/avgi/avgi outfits.txt, data/successors/successor outfits.txt
**Content**
As of 2c2e654, afterburner effects can scale with the engine hardpoints that spawned them. For the Successor **edit: and also Avgi** afterburners, which are an integrated part or mode of their engines, scaling along with regular engines plumes is desirable. I have changed them accordingly by adding the `zooms` keyword to their afterburner effects.
Before:
After:
**With regular engines also firing:**
Before:
After:
Things look fine on ships with multiple engine zooms (like the Korsmanath)
Let me know if you really need one
=> Successor, Avgi afterburners zoom with engine scale

.ecrc, .editorconfig-checker.json
**Bug fix**
This PR addresses the issue describe in [this job](https://github.com/endless-sky/endless-sky/actions/runs/13704344545/job/38326402398?pr=10391).
Apparently, the name of the config file changed, so this PR renames it to match the changes. I also removed the exclusion for mp3 files, as those are filtered by default. The checker also complained about the space-based indentation, so that was changed to tabs.
Runs fine.
=> fix(ci): Rename editorconfig-checker's config file

source/AsteroidField.cpp, source/AsteroidField.h, source/CMakeLists.txt, source/DamageProfile.cpp, source/DamageProfile.h, source/Engine.cpp, source/Minable.cpp, source/Minable.h, source/MinableDamageDealt.h
**Bug fix**
This PR fixes #9785.
Implemented blast damage for minables.
yes™.
N/A
hopefully none.
=> fix(mechanics): Fix blast damage not affecting minables

data/_ui/tooltips.txt, source/AI.cpp, source/Armament.cpp, source/Armament.h, source/Hardpoint.cpp, source/Hardpoint.h, source/Outfit.cpp, source/Ship.cpp
**Feature**
Added a multiplier attribute for turret turn rates (additive, like all other multipliers). It can be set on the whole ship (by adding it as an attribute of the ship or its outfits) or directly on a particular hardpoint. As there's no UI for viewing the detailed attributes of hardpoints, it should be mentioned somewhere else (for example in the ship's description) if we want the player to know about it.
As usual, no data changes in this PR, just the engine feature.
`"turret turn multiplier" <value#>` can be a child of the hardpoint, and a standard attribute of the ship (or its outfits).
yes.
soon
most likely none.
=> feat(mechanics): Turret turn multipliers

source/System.cpp
**Bug fix**
This PR addresses the bug/feature described in issue #11016
As described in the linked issue, the game currently checks that an "(add) minables" or "(add) asteroids" node has at least four tokens before trying to add a new asteroid object to the system.
The expected tokens are:
- Literal "minables" or "asteroids",
- Name of the minable or asteroid to use,
- A "count" value, and
- An "energy" value.
This is four tokens, explaining why it requires at least four tokens. However, when using "add" to avoid deleting whatever asteroids the system already has and instead only add new asteroids to the end of the list, the required number of tokens is five: the previously listed four plus the "add" token itself.
Since the game only requires four tokens, however, this means that a node …
=> Fix adding minables and asteroids error detection and reporting

source/SavedGame.cpp
**Bug fix**
Thanks to @MidnightPlugins for reporting this on Discord.
Currently, the "load panel" (the panel where you load saves from) displays the name of the system and planet the selected save file is at. However, the names it displays are the unique names of the system and planet, not necessarily the display names. This is because it just reads the text from the save file, which uses the unique name (in order to uniquely identify the objects).
This PR updates this code to check if a system and planet with the given names are valid and, if they are, retrieves their display names.
This will not display the correct names if either the planet or the system display names are updated by changes present in the selected save file but not currently loaded.
No.
This save file can be used to …
=> fix(load/ui): Use display names for systems and planets in the load panel

data/human/deep missions.txt
**Bug fix**
Hardcoded the planet name in mission `Stones of Skadenga 3` so the Ondurdis doesn't tell you about the wrong planet.
=> fix(bug): hardcode the planet name in `Stones of Skadenga 3`

data/human/human missions.txt
**Typo fix**
Fixes #11147 
Changed log entries that contained `Radickson` to say `Radrickson`. Also fixed two incorrect gender references in the Monk and Hospice missions.
@danrr pointed out that this essentially would make two entries in the log, one for both versions of the name, so I also added missions to remove the "Radickson" entries and add the correct "Radrickson" ones.
That adds more lines than it should, but I'm not sure what else could happen to make sure the logs are correct.
=> fix(bug): standardize use of Radrickson

data/human/culture conversations.txt
This PR addresses the bug/feature described in issue #10659. ~~I originally said I'd get the ball rolling in a week but time is an illusion.~~
opusforlife2 shared in the issue that there aren't many cases of getting to see exotic organisms native to the many livable planets in the game. I agree, and this culture conversation starts to expand that by giving the player a chance to see the `reclusive ape-like` `"canyon people"` already stated to live on Glaze (or just a bunch of tourists). 
I also plan to make at least a couple more exotic organism culture conversations in a similar vein to expand out the scope of alien life in Endless Sky.
Played through the mission
TBD
=> feat(content): Culture Conversation for native life on Glaze

data/persons.txt
**Style**
The content style check is throwing warnings about an overindented line in Cap'n Pester's definition. While it won't (shouldn't) break anything in-game, it could get confusing for other contributors. This PR fixes it.
=> fix(style): fix overindentation in Cap'n Pester's definition

source/Files.cpp
**Bug fix**
This PR addresses the bug/feature described in issue #11160 
Removes trailing slashes from parent directories, to prevent iterator from creating an empty trailing element that fails the match.
N/A
N/A
Tested locally by just running the game. Fails to start without the change (see issue for details)
N/A
N/A
N/A
N/A
=> fix(bug) Fix resource directory not being found on linux

source/AI.cpp, source/AI.h, source/CategoryList.h, source/ConditionSet.cpp, source/ConditionsStore.cpp, source/ConditionsStore.h, source/DataWriter.cpp, source/DataWriter.h, source/Engine.cpp, source/Engine.h, source/Fleet.cpp, source/Fleet.h, source/FormationPattern.cpp, source/FormationPattern.h, source/MissionPanel.cpp, source/PlayerInfo.cpp, source/PlayerInfoPanel.cpp, source/Ship.cpp, source/System.cpp, source/System.h, source/audio/Sound.cpp, source/comparators/BySeriesAndIndex.h, source/image/ImageSet.cpp
* Declare reference parameters as const reference where applicable.
* Declare member functions as const where they don't manipulate state of the class. Some more member functions could be declared const, but they manipulate reference or pointer member of their class. So I left them as mutable as constness would only be "memory const" not "logical const". Examples are the "click" functions of Gui Panels.
I am currently trying to familiarize myself with the ES codebase and usually do a bit of surface level refactorings / core cleanups when doing so.
This is a pure refactoring, there are no changes in functionality.
Existing unit-tests are green
None expected,
=> Refactor: Increase const correctness of reference parameters and member functions

.editorconfig
Set the editorconfig's indent style in CMakeLists to tab.
Also removed some leftover SCons files from the list as they are no longer used.
=> feat(style): Force tab-indents in CMakeLists

data/kahet/aberrant missions.txt
**Typo fix/Content (Mission)**
This PR addresses a bug/feature described on [Discord](https://discord.com/channels/251118043411775489/536900466655887360/1350684669921857586)
Fixed a typo fix in the `Boarding Aberrant` mission.
Also added some explanatory text about how to loot Anomalous Mass.
=> Aberrant first contact edits

data/_ui/interfaces.txt, source/Interface.cpp, source/Interface.h, source/shader/LineShader.cpp, source/shader/LineShader.h
**Feature**
This PR addresses the bug/feature described in issue #my head, but could be useful for stuff like az's gunsights
Adds a gradient method to lineshader that draws a linearly interpolated gradient between two point.
spoopy orange-to-yellow gradient
(for demonstration purposes only, not part of this PR)
I'd guess pretty little, as all of the gradient work is being done on dedicated hardware by GPUs.
=> feat: Gradient in the LineShader

data/human/human missions.txt
**Bug fix**
This PR addresses a bug described on [Discord](https://discord.com/channels/251118043411775489/536900466655887360/1350569543017300078)
Added a missing description to the mission `Timothy Radrickson 3c: Escort the Convoy`.
=> fix(bug): add a description to `Timothy Radrickson 3c: Escort the Convoy`

data/human/human missions.txt
**Bug fix**
Every other mention of `<ship>` that I can find in `human missions.txt` refers to `the <ship>`. Using just `<ship>` can be somewhat jarring, though it does depend a little on the name.
=> fix(content): Refer to `the <ship>` instead of just `<ship>` in `"Hai Wormhole Warning"`

data/human/human missions.txt
This PR addresses the bug described in issue #11190. (closes #11190)
In `Timmy Radrickson 1`, one day after you take off, you detect Timmy due to his infrared radiation, however, the mission text assumes that you always jump after taking off, which is not necesarily the case. This PR updates the text so that, if you take off, the text mentions you taking off instead of completing your jump.
Warp core did the testing for me
=> fix(content): Have `Timmy Radrickson 1` describe how you entered the system before detecting Timmy 

source/BoardingPanel.cpp
**Bug fix**
There was a line limiting the selected outfit index on the boarding panel when the previously selected item is removed from the list. However, it didn't do anything as the index was already at the limiting value. Instead of subtracting 1, I chose to do it in a different way to not mess up the logic in the rest of the file.
Now when you take everything from the last element of the list, the selection changes to the now-last element.
yes.™
=> ui: Fix off-by-one index on boarding panel

source/ConversationPanel.cpp, source/Mission.cpp, source/MissionAction.cpp
**Refactor**
A little while ago, a new method was added to `PlayerInfo` that provides a central place to apply some substitutions that involve information about the current state of the player info:
`<first>`, `<last>`, `<ship>`, `<model>`, `<system>`, `<date>`, `<day>`.
This PR makes use of this function in some places that were manually adding a subset of these substitutions:
- Mission blocked messages.
- MissionAction dialogs.
- The conversation panel.
In the case of the conversation panel, a mission may already be using the "<system>", "<date>", and "<day>" substitutions. The values provided by the mission (if they are not empty strings) will be preserved.
Similarly, the player's "<ship>" and "<model>" substitutions will be replaced by the values for the ship if this conversation was …
=> Use PlayerInfo::AddPlayerSubstitutions method more widely

source/SpaceportPanel.cpp
**Feature**
This PR addresses the bug/feature described in issue #11139
Global and player (\<first\>, \<last\>, \<ship\>, \<model\>, \<system\>, \<date\>, and \<day\>) substitutions will now be used in news messages.
None.
https://github.com/endless-sky/endless-sky-wiki/pull/113
Minimal; this is only done when updating the news text which is only when the player clicks the spaceport button or presses the "p" key in one of hte planet panels.
=> feat(news): Use global and player substitutions in news messages

data/human/human missions.txt
**Bug fix**
**Typo fix**
This PR addresses a bug described on [Discord](https://discord.com/channels/251118043411775489/536900466655887360/1350872989763375249)
Simplified the mission `Timothy Radrickson 5: Oblivion Meeting` so that `Timothy Radrickson 5a: Timshank Redemption` properly offers.
Also fixed a typo in the dialog. Before merge, I'd like @SpearDane to confirm it was actually a typo and not an intentional repeated word.
[Dag Roth~Timothy.txt](https://github.com/user-attachments/files/19387077/Dag.Roth.Timothy.txt)
=> Timothy Radrickson 5: Oblivion Meeting: simplify and fix

data/human/deep jobs.txt, data/human/far north jobs.txt, data/human/near earth jobs.txt, data/human/paradise world jobs.txt, data/human/rim jobs.txt, data/human/south jobs.txt, data/human/syndicate jobs.txt
**Bug fix**
This PR addresses the bug described on [Discord](https://discord.com/channels/251118043411775489/1016522571782574180/1350168505265295493).
It was possible to get missions to transport materials to the Syndicate from Pirate planets. This is no longer possible. Furthermore, I have gone through and made it so that you cannot get these missions, along with the intrasystem jobs in Sol, if you do not have landing access to the destination.
Made sure transport jobs stopped offering in the reported system.
[Test Pilot~Pirate.txt](https://github.com/user-attachments/files/19252900/Test.Pilot.Pirate.txt)
=> fix(content): Block more human space jobs from offering without landing access or in pirate space

source/audio/Sound.cpp
**Bug fix**
Sounds are not currently loaded by executables built by clang (self-compiled on Windows or our MacOS CD).
This is because of a difference in behaviour of `std::fstream` objects upon construction between gcc and clang implementations of the C++ standard.
This difference results in there being no available bytes when `std::istream::readsome` is called to traverse the audio file header in the clang implementation, while there are many available bytes in the gcc implementation.
`std::istream::readsome` will only read from already available bytes, and so it reads nothing in the clang implementation. Not reading files is not conducive to loading them, and so, they are not loaded.
This PR removes the calls to `std::istream::readsome` and replaces them with calls to …
=> fix(sound): Read 32 and 16 bit sound fragments fully

data/human/fleets.txt
Removed the four falcon variants (total weight 5), added a variant which is just a Leviathan (weight 1), and added a total of 3 weight to variants with the Protector or the Vanguard.
Falcons shouldn't be appearing at all in random pirate spawns in the core - the Falcon is a relatively new ship that's only manufactured in Tarazed, it shouldn't be showing up anywhere near this frequently in the hands of Core pirates. The Leviathan, on the other hand, is old enough that there might reasonably be some around further from where they're built, and in any case the Far North is more accessible for Core pirates than the South.
Conversely, ships made in the Core should appear more commonly in the Core, and the increased spawn frequency for Protectors and …
=> feat(content): Adjust the contents of the `Large Core Pirates` fleet

source/MapOutfitterPanel.cpp, source/MapSalesPanel.cpp, source/MapSalesPanel.h, source/MapShipyardPanel.cpp, source/Ship.cpp, source/Ship.h
**Feature**
Since the addition of the "Unfettered Shipyards" variants of the Shield Beetle and Lightning Bug (variants of those ships with different outfit configurations sold at the shipyard in Unfettered Hai space), various people have been confused by the appearance of two very similar looking entries for each ship in the map shipyard panel.
This PR adds a feature to try to resolve some of this confusion: variants (well, all ships, really) can be given an extra name that will appear below the model name in the map shipyard panel.
before | after
-- | --
```
ship "Whatever" "Whatever (Two)"
"variant map shipyard name" "A different configuration"
```
Gave the "Shield Beetle (Unfettered Shipyards)" a variant map shipyard name and see that it appears in the map shipyard as expected. …
=> Differentiate variants in map shipyard

source/Preferences.cpp
This PR edits a few settings' defaults:
- Status Overlays: Defaults to `on hit` (before: `off`)
- A balance between visual clarity and gameplay usefulness.
- Missile Overlays: Defaults to `on` (before: `off`)
- Most useful in the early-game, where dodging missiles can be necessary.
- Deadline Blink by Distance: Defaults to `on` (before: `off`)
- Highlights urgency, a better representation than just a date.
These are intended to make the new player experience better, mostly by bringing harder-to-notice details into the foreground that would otherwise go unnoticed until much later.
=> Use some better default preferences

source/Engine.cpp
**Bug fix**
This PR addresses the bug/feature described in issue #on discord by me
Fixes the camera being one step ahead while paused.
https://github.com/user-attachments/assets/f04342f1-a3cf-4bac-b738-d2a7eb80c857
=> fix(bug): Camera disassociates while paused

data/map systems.txt
**Bug fix**
This PR addresses a bug described on [Discord](https://discord.com/channels/251118043411775489/536900466655887360/1353112333580505129)
Fixed the overlapping of two stars.
Before:
It takes many years of in-game time to get the star to the right point, so I haven't tested it.
=> fix(bug): Li-7 star changes

data/coalition/coalition weapons.txt
**Balance**
This PR reverts the buff to the Ion Rain Gun's ion damage done in #4868, and also nerfs the Ion Hail Turret's ion damage. Both weapons' scrambling damage values were also updated.
With the advent of the Quarg Revamp, it's been noticed that the Quarg ships are affected quite a bit by the Heliarch ion/scrambling weaponry. This isn't really the purpose of these weapons - as it stands, they're the only weapon in the Heliarch arsenal *not* specifically developed to fight the Quarg, and instead are more of the police-force and general peacekeeping weaponry.
This PR brings the ion DPS of the Ion Rain Gun from 480 back to its original 300, and also lowers the Ion Hail Turret's from 512 to 480 (if I did my math right). Scrambling damage values also followed these changes in values. …
=> (balance) Nerf Heliarch Ion Weapons

data/sheragi/sheragi outfits.txt
**Balance**
This PR addresses the incessant complaining described in my fever dreams
The Sheragi batteries were skipped over during the big battery buff in #6783, only receiving a 2x buff when most other battery outfits received buffs between 4-10x. This was because they are technically dual use outfits, being shield generators as well as batteries. However, literally no one is going to go for a 150 ton shield generator that has 0.8 shield generation.
More importantly, the Sheragi batteries are described as Superconducting Magnetic Energy Storages, (SMES) which are incredibly cool, and depending on the critical field limits of the superconductors in question, are up near the upper limit of energy storage density. Since these are unique outfits, with the player only able to ever obtain 1 …
=> [Balance] Buff the Sheragi EM Batteries

data/human/paradise world jobs.txt, data/human/south jobs.txt
**Bug fix**
This PR addresses the bug described on [Discord](https://discord.com/channels/251118043411775489/536900466655887360/1354795576289398814).
There were still a few shipment jobs that could offer on pirate worlds, that were not fixed in https://github.com/endless-sky/endless-sky/commit/34383dd960f42de2537a06c2bb0ba3f35a8a73c0. This PR makes sure that all shipment jobs cannot offer on pirate worlds.
Before
After
Made sure each of the jobs in https://github.com/endless-sky/endless-sky/commit/34383dd960f42de2537a06c2bb0ba3f35a8a73c0 either specified that they were not offered on pirate systems, or their location filter did not match any inhabited pirate systems, by using the `--matches` flag.
This save file can be used to test these changes: [Test …
=> fix(content): Fix remaining shipment jobs from offering on pirate planets

data/remnant/remnant events.txt
**Revert**
Revert #7377 so SSil Vida space gets lower jump range permanently (as it was originally, right?)
Since the DistanceMap Rework #6940 is in, AI ships use jump range correctly so the changes from #7377 can be reverted.
Note, there could a bit more to be done around this. #7377 Added the comment: "Instead, jump range of other systems nearby may need to be reduced on activation to prevent escorts outside the Postverta cluster jumping into that region." 
Yes, escort ships can now jump into the dimensional bubble (from Edusa or Levana). The jump range for those two systems could be changed with this activation/deactivation event, but then that also technically changes the theoretical fleet maneuvers you could order while in SSil Vida space. Plus, any map changes around there would …
=> Revert the workaround for SSil Vida jump ranges

data/successors/successor 1 prologue.txt
**Bug fix**
In Successors: First Contact 3, the spaceport (on offer) conversation options had a few display logic issues:
- Some options could be selected multiple times, when this was not intended by the author.
- Some follow-up questions could not be asked if a different question was asked in between. I confirmed with @Daeridanii1 on [discord](https://discord.com/channels/251118043411775489/266345072554016768/1354650059786027089) that this was not desired.
These issues have been fixed in this PR.
Steps to reproduce this issue:
1. Load the attached save.
2. Take off and land on the same planet. (This step is required, as the mission is cached in the save file after landing.)
2. Select the following conversation options. Picking other options should also work, as long as you accept their …
=> Fix follow-up question display logic in Successors: First Contact 3

data/wanderer/wanderer ships.txt
**(Content, Balance)**
Adds stats for the Wanderers' Heavy Gust. The comparison to the Strong Wind mirrors the comparison between the Autumn Leaf and Summer Leaf, as is (I understand) the intent.
The Heavy Gust loses the Strong Wind's integrated scanning, with the exception of the tactical scanning which it instead improves on.
In terms of implementation, I'm thinking this should appear alongside, or slightly after, the Autumn leaf. It will become _available_ alongside the Tempest, as it requires the Wanderer Military License, but it'll be visible and present in fleets before that point.
As suggested by Amazinite when the Heavy Gust was conceptualised, this adds a visible ship to the game that requires the military license and can be seen before you gain that license, and serves as an …
=> feat(content): Add stats for the Heavy Gust

source/Mission.cpp, source/Mission.h, source/PlayerInfo.cpp
**Feature**
This PR is a reopening of #10828. This feature has uses outside of just the spaceport reminder mission, so it still makes sense to add to the game. The missions in FW Reconciliation where the Syndicate gives the player a jump drive, but the game checks if the player has a hyperdrive, scram drive, or already has a jump drive is another example of how this feature could have been used (the jump drive version of the mission was titled "A Jump Drive" to force it to offer first), although that case was actually already fixed by other means: https://github.com/endless-sky/endless-sky/commit/127faa20b0b5e44cea8970f08696f88e78dd3474. Had this case not been fixed by other means, this is not a case that the non-blocking tag from #10852 would have been able to address.
Adds the following …
=> feat(missions): Add an "offer precedence" token to Missions for controlling offer order

.github/workflows/cd.yaml, vcpkg.json
This PR addresses the bug/feature described in issue #11248
The failing CI is complaining about the difference between the expected and installed versions of libjpeg-turbo. This PR enables the v8 compatibility mode that should allow the library to function with our binary.
Let's see if the CI works
=> fix(ci/cd): Fix libjpeg version on Mac

data/avgi/avgi 0 first contact.txt
**Bug fix**
This PR addresses a bug described on Discord
Deleted an extraneous tab character to make a label work properly. ~~I was sure Azure had fixed this, but apparently not~~
edit: oops, I apparently PRed this from master
[Dag Roth.txt](https://github.com/user-attachments/files/19525910/Dag.Roth.txt)
=> fix(bug): Avgi: Defend Ensemble 1 fix

source/ShopPanel.cpp
**Bug fix**
Forgot to add the new message introduced in #11048 to the manual show help command functionality. The code in this PR is the same as in the place where it's displayed automatically, except for the flag required for manual messages.
yes.™
N/A
haha std::set go brrr
=> fix(ui): Add a missing message to the help command

data/korath/korath hails.txt
This PR addresses the feature described on [Swizzle 6](https://discord.com/channels/844344915454722089/849060713485041704/1355953019333775372).
Raven deosn’t want the korath to eat kittens.
Unlikely
=> feat(content): Remove reference to kittens from korath hails

data/hai/unfettered side missions.txt
**Content (Mission Addition)**
This PR addresses an issue mentioned on discord.
Hai Legacy is a unique mission in that it requires you to not have your fleet with you for the fight.
Considering that, I think it makes sense to add a small warning at the start to make sure players don't take it with a full cargo hold and many passengers.
~~Note that they could always make their fleets hold position in another system but that's a bit much to ask.~~
I updated the fight to still happen in Ehma Ti but have you land on Darkcloak to reoutfit the ships and leave the fleet on hold there.
Launch, land and go to the shipyard to start the mission.
[Intrepid.Enterprise.txt](https://github.com/user-attachments/files/19151752/Intrepid.Enterprise.txt)
=> Hai Legacy: tweak according to player feedback

.github/path-filters.yml, .github/workflows/ci.yml
**Feature**
This PR enables CI-build-runs for PRs with overlay-only changes, noticed by warp_core and me while investigating #11242
Test-PRs like https://github.com/petervdmeer/endless-sky/pull/13 were not triggering CI-builds.
Added a commit on the test-PR in the summary and noticed that the CI-buids do run. Then copied the change into this PR.
N/A
No noticeable impact expected.
=> feat(ci): Also run CI on overlay changes

data/gamerules.txt, source/Engine.cpp, source/Gamerules.cpp, source/Gamerules.h, source/System.cpp
Added in gamerules.txt "system arrival min", "system departure min", "fleets multiplier" 
Default Values keep the game content unchanged. 
You can achieve a slower Gamefeeling closer to Escape Velocity by setting default system departure and default system arrival to 4500 and fleet multiplier to 0.5  without having to edit hundreds of systems individually via a plugin impossible to maintain.
**Feature**
This PR addresses  discussions about the game feeling too fast to some players described in [issue](https://steamcommunity.com/app/404410/discussions/0/591761634944357020/).
You can achieve a slower Gamefeeling closer to Escape Velocity by setting system departure min and system arrival min to 4500 and fleet multiplier to 0.5  without having to edit hundreds of systems individually via a …
=> feat(mechanics): Added 3 optional settings in gamerules.txt, 

source/PlayerInfo.cpp, source/Ship.cpp, source/Ship.h, tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_attribute_autoconditions.txt
**Feature**
This PR addresses the bug/feature described in issue #7795
Adds autoconditions for the flagship properties that were left over from the linked feature request:
- "flagship bays free: <category>" - Like the existing "flagship bays: <category>" autocondition, but one only returns the number of bays of that category that are free.
- "flagship bays" - Like the existing "flagship bays: <category>" but returns the total number of bays across all categories.
- "flagship bays free" - Returns the total number of bays that are free across all categories.
- "flagship shields" - The current absolute shield level.
- "flagship hull" - The current absolute hull level.
- "flagship mass" - The current mass of the flagship; the masses of any carried ships, any cargo, and this ship and its …
=> feat: Flagship property (bays, shields, hull, mass) autoconditions

data/avgi/avgi outfits.txt
**Bug fix**
This PR addresses the bug described by 7even in https://github.com/7even/endless-ships/issues/26#issuecomment-2781673443
Removed an extraneous "c" character at the end of an Avgi outfit description.
If this causes problems, call me a toad.
=> fix(bug): remove extra character

CMakeLists.txt
**Bug fix**
Having 3.16 as the minimal required CMake version doesn't make sense, as [presets](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html) were added in 3.19.
Also since our official workflows now use CMake 4.0, we should probably set the policy version to that.
CI/CD will do the testing for me.
=> fix(ci/cd): Correct required CMake version

data/human/free worlds 3 reconciliation.txt
**Bug fix** 
This PR addresses the spoiler in the FW Syndicate Capture 1C mission that tells the player Rand may have been disconnected before they can find out for themselves.
A new player would have no idea that hyperspace connections being removed is possible in this game and should discover this naturally when they enter the waypoint systems in this mission. I have removed the text that suggests this possibility whilst keeping a hint to look in neighboring systems.
=> Remove spoiler suggesting hyperspace links are fragile

data/remnant/remnant 2 cognizance.txt
**Typo fix**
Thanks to the numerous people who have reported this on Discord.
This mission uses the substitution "\<tons\>" in its description, but the mission has no cargo. The description is referring to the cargo that will be collected in the subsequent mission. Since this mission has no cargo, "\<tons\>" is replaced with "0 tons" which is not very useful.
This PR replaces the use of the substitution with "58 tons", which is the amount of cargo involved in the next mission.
I will not.
=> Fix "Remnant: Cognizance 32" description

.github/pull_request_template.md, docs/CONTRIBUTING.md
This PR updates the Contributing.md file to include an "Acknowledgement" section explicitly stating that content that is contributed to the game isn't under the ownership of its contributor, and that contributors must be comfortable with the possibility that their work may be modified in the future by others should they choose to open a pull request to add it to the game, although it is also made clear that publishing one's work as a plugin is both possible and welcomed as well.
This has been an implicit expectation of content creation for years (really for the game's entire history), but this PR seeks to make that expectation explicit as to prevent issues around unshared expectations between new contributors and the existing content creator base.
This PR also updates …
=> Update PR template to add an acknowledgement that the author has read the Contributing article

source/OutfitInfoDisplay.cpp
**Bug fix**
This PR addresses the bug/feature reported in https://github.com/endless-sky/endless-sky/pull/10993#issuecomment-2800365631.
The turret turn multiplier should be displayed in the same style as other multipliers.
Before:
After:
see the screenshots above.
=> fix(ui): Display turret turn multipliers with consistent formatting

data/human/outfits.txt
**Content (Mapping Update)**
Fixes #10024
Added the `"map minable" 1` attribute, introduced in #10573, to the Local Map. This will help beginning miners get started.
=> Local Map reveals minables

source/PreferencesPanel.cpp
**Bug fix**
The game doesn't allow unbinding the menu command to prevent the player from getting stuck. The problem is that it doesn't check for the command itself, but for the key that is bound to it, which means you can't unbind commands other than the menu if they have the same key assigned.
yes.
=> fix(ui): Allow unbinding commands set to the same key as the menu command

source/PlayerInfo.cpp
**Feature**
This PR adds the auto conditions described here: https://github.com/endless-sky/endless-sky/pull/10787#issuecomment-2764375703
Adds the following auto conditions:
* `"ship attribute: <attribute name>"`: Has the same behavior as `"flagship attribute: <attribute name>"` (returns the value of the given attribute multiplied by 1000, except for cost), except it returns the sum total of the attribute across all the ships in your fleet that are local to you (i.e. in the same system when not landed, or on the same planet when landed, excluding parked ships).
* `"ship base attribute: <attribute name>"`: Same as above, but only looks at the base attributes of the ships.
* `"ship attribute (all): <attribute name>"`: Same as `"ship attribute"`, except it looks at every ship in your fleet …
=> Create auto conditions for reading the attributes from your fleet's ships

source/PreferencesPanel.cpp
**Feature**
This PR addresses the bug/feature described in issue #on discord somewhere?
This changes the PreferencesPanel to check for the menu keybind's validity on exit, and gives a warning if the user wants to change the keybind.
=> feat: Warn the player if they are rebinding the menu key or the key is not bound properly

source/ConditionsStore.h, source/Engine.cpp
**Refactor**
This PR addresses the bug/feature described in issue #11335
Deletes the copy constructor and copy assignment operator of ConditionsStore to prevent copying objects of that type.
Replaces two places where ConditionsStores are unnecessarily copied (repeatedly) with references.
Explicitly default the move constructor and move assignment operator because PlayerInfo can be moved and needs to move its ConditionsStore.
Compiles
I will be very surprised if this isn't an improvement, but probably minimal, given that we don't actually use the feature that involved copying the object in vanilla.
=> fix(conditions): Prevent copying conditions stores

data/human/free worlds 0 prologue.txt
**Bug fix**
This PR addresses the bug/feature described in issue https://github.com/endless-sky/endless-sky/issues/11319
This PR removes the line in FW Recon 1 that says that the player "feel[s] a little bit creepy," as per #11319. It also removes the unnecessary `goto` that follows that line.
None
Nope
=> Fix(content): Remove a reference to the player feeling creepy in FW Recon 1

data/remnant/remnant 2 cognizance.txt
**Bug fix**
Thanks to `ubriefnotawalrus` on Discord for reporting this.
This mission ("Remnant: Cognizance 24") is offered from the planet "Ssil Vida", in the "Postverta" system.
It also uses "Postverta" as a waypoint.
A waypoint for the system a mission is offered in is immediately marked as visited (before the mission has actually even been fully instantiated). As a result, this mission doesn't actually require you to take off and enter the system, it is always ready to complete.
This means that loading a save file where this mission was just offered (such as reloading immediately after getting the mission) will immediately complete it, without the player actually seeing the conversation they were supposed to get upon taking off. It also means that the next mission won't be available …
=> Fix "Remnant: Cognizance 24" completing unexpectedly on reloading save

source/NPC.cpp, source/NPCAction.cpp, source/NPCAction.h
**Bug fix**
@beccabunny noticed recently that an NPC "on board" conversation cannot destroy the boarded ship when using the "launch", "flee", or "depart" endpoints (in this context, all three do the same thing because there's nothing to defer or accept here).
This PR makes it so that conversations from an NPC "on board" trigger will be able to destroy the boarded ship with these conversation endpoints. More generally, these conversations will act more similarly to conversations that occur as part of the "on offer" trigger of a "boarding" mission, so will use the boarded ship's name in the "\<ship\>" substitution, for example.
```
mission "whatever"
npc
ship "whoever"
on board
conversation
`However`
launch
```
Not one bit.
I don't even know.
Immeasurable
=> Allow NPC "on board" conversations to destroy the ship

source/Date.cpp, source/Date.h
**Feature**
Historically, Sunday has been generally recognized as the first day of the week in many cultures. Relying on ISO isn't the right decision in my opinion, as most people find ancient politics a more neutral topic than modern-day politics.
Manually verified that the formula is correct.
https://github.com/endless-sky/endless-sky-wiki/pull/132
N/A
=> Make Sunday the first day of the week

tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_attribute_autoconditions.txt
This PR addresses the bug described in the comments of #11321
The flagship attributes autocondition test had the flagship located in the Ember Waste. One of the things this test did was read the autocondition for the flagship's shields. Since the Ember Waste contains ion storms that can damage your ship's shields, the assert on the shields condition could fail if an ion storm was active when the check occurred,
I've moved this test to instead launch from Earth.
It tests itself.
=> Move the flagship autoconditions test out of the Ember Waste

source/audio/Audio.cpp
**Bug fix**
With a stereo layout, I don't think this will change anything. With a quad (or other surround sound) layout, this moves sounds from the rear speakers to the front speakers.
https://github.com/kcat/openal-soft/blob/2175689979558a64e21e2285904db4175e5ab5a2/include/AL/al.h#L163-L177
> Z points towards the viewer/camera (middle finger)
This can be tested without a real surround sound system by creating an [alsoft config
file](https://github.com/kcat/openal-soft/blob/master/alsoftrc.sample) like this:
```ini
[general]
drivers = wave
channels = quad
[wave]
file = /path/to/file.wav
```
N/A
N/A
I played briefly with a quad speaker layout.
N/A
N/A
N/A, I think?
N/A, I think?
=> fix(audio): Place sounds in front of the listener

source/CMakeLists.txt, source/ConditionEntry.cpp, source/ConditionEntry.h, source/ConditionsStore.cpp, source/ConditionsStore.h, source/PlayerInfo.cpp, tests/unit/src/test_conditionsStore.cpp
**Feature**
This PR separates the ConditionEntry from ConditionsStore as part of issue #7451 
- [X ] I acknowledge that I have read and understand the [Contributing](https://github.com/endless-sky/endless-sky/blob/master/docs/CONTRIBUTING.md) article.
ConditionEntry becomes it's own stand-alone class (split off from ConditionsStore). ConditionEntry now also contains the derived condition providers directly, and this simplifies the syntax for creating new derived conditions.
ConditionEntry also got a notify function, to prepare for the future subscribe mechanism that is required for #7451.
PR #11318 refers to some of the changes in this PR. (But there are no dependencies between that PR and this one.)
N/A
N/A
The unit-test for ConditionsStore has been updated to reflect the updates (and I …
=> feat(conditions): Make ConditionEntry standalone and simplify condition providers

source/CategoryList.cpp, source/CategoryList.h
**Bug fix**
This PR addresses the bug/feature described in issue #11325
Fixed #11325
Removes the map of category name to category object from CategoryList. Looking back at #7054 when it was added, it seems like it was just kinda tossed in there. Instead of maintaining a separate map of the categories, just search the list of categories using find_if instead.
Nope.
=> Search a CategoryList's internal list when retrieving by name instead of maintaining a separate map

source/Engine.h, source/Planet.cpp, source/UniverseObjects.cpp
**Feature**
This PR addresses the feature described during a conversation about new/changed mechanics that could be used for pirate content.
Currently, a planet will only display the outfitter if it has any outfits for sale. This means that even if you list an outfitter under the planet, but that outfitter is empty, the shop won't display in game. UniverseObjects will also log and error about empty outfitters.
This PR makes it so that UniverseObjects no longer log an error for empty outfitters, and the criteria for determining whether the outfitter should display is now whether the planet has any outfitters defined for it, not whether any of those outfitters have something for sale. This allows us to have planets that don't sell anything, but still have the facilities necessary for you to …
=> feat(mechanics): Allow outfitters and shipyards to be empty

data/kahet/kahet missions.txt
One of the optional choices in Patir Mystery 1 can bring you to this paragraph:
`"Oh, the scanner is working perfectly. But the Ka'het seem to follow no pattern whatsoever, not even the most basic ones. I guess you could compare them to simple animals, searching for food and fighting each other for their territory. They seem to have some sort of 'imprinting' towards the stations that breeds them, but other than that, they have not shown any other particular behavior yet."`
Rereading it now, I feel like it does not do a good introduction of the Ka'het to the player - it is not even too internally consistent, as simple animals *do* tend to follow patterns and the one described in the same paragraph also counts as one. This PR rewords it to:
`"Oh, the …
=> Rewording in Patir Mystery 1

source/GameWindow.cpp
We don't get any reports that the Windows version of the game crashes at exit, so the comment is incorrect. And I don't think we allow commented-out code just for archival purposes, that's what git blame is for.
0
=> style(code): Remove incorrect comments

.github/workflows/cd.yaml, .github/workflows/cd_release.yaml, .github/workflows/ci.yml, CMakeLists.txt, docs/readme-developer.md, source/CMakeLists.txt, source/Files.cpp, source/Files.h, source/GameData.cpp, source/UniverseObjects.cpp, source/ZipFile.cpp, source/ZipFile.h, source/audio/Audio.cpp, source/audio/Music.cpp, vcpkg.json
**Feature**
This PR enables loading plugins directly from zip files, without having to unzip them.
Related: #10431, #9068
Adds support for loading plugins from zip files using zlib. This implementation is abstracted away from the users via `Files`, `std::iostream` and `std::filesystem::path`, so no changes were necessary in any other part of the codebase (unlike in #10431). (I did remove trailing slashes from directory names everywhere, though, as that's been known to be problematic with path comparisons.)
Individual zip files are handled via `ZipFile`, which provides a `Files`-like interface. This class is used only by `Files`, I just didn't want to dump all the code there.
The relevant `Files` functions were patched to check zip files and open them as needed. Since zlib doesn't support …
=> feat(enhancement): Load plugins from zip files

source/Dialog.cpp
**Feature**/**Bug fix**
Since https://github.com/endless-sky/endless-sky/commit/f4f787b5c9b3717f9c983c75b437f6988805b620, the height of `TextArea`s can change after the initialization, which can cause unwanted offset if not handled properly, so we need to move the dialog resizing code from `Init` to `Draw`.
As a side effect, this also makes dialogs change their form (adding or removing scroll bars, or switching between the normal and double width) if the game window is resized.
Before:
After:
Tested with the snapshot dialog above to make sure everything is being positioned properly, and a scan results dialog to check window resizing.
N/A
In theory considerable, but nothing else really happens in Dialog, so not really important.
=> feat(ui): Resize dialogs dynamically

source/TextArea.cpp
**Bug fix**
This PR addresses the bug/feature described in issue #11372
This is quite the journey.
When you click on the game, the SDL event for the click gets passed into the game's UI stack (which contains the collection of all active "Panel" objects) via `UI::Handle`.
This method than calls the relevant method (for this case, `Panel::DoClick`) on each `Panel` object in the stack, until one reports that it handled the event (click).
(Well, actually, first `UI::Handle` passes the click into a `Panel`'s `ZoneClick` method, before giving it to that `Panel`'s `DoClick` method, but that's not relevant here, so we'll ignore it.)
`Panel::DoClick` then passes the parameters to `Panel::EventVisit` as well as telling it to call `Panel::Click`.
`Panel::EventVisit` is a helper function. It …
=> Fix improper click handling in the mission panel sometimes

source/ConditionEntry.cpp, source/ConditionEntry.h, source/ConditionsStore.cpp, source/ConditionsStore.h, source/PlayerInfo.cpp
**Bug fix**
This PR should addresses the double free part of the bug/feature described in issue #11378
ConditionEntry contained some manual memory management. That was not working well, especially when entries got copied (since the copy actions duplicated pointers, and this duplication was not expected).
This PR does not address the copy action itself, but it replaces the manual memory allocation. This should prevent the double-free as seen in #11378. (Since ConditionEntry objects should be copy-able just fine now).
This PR might also be useful just to prevent access to the provider on object-destruction of ConditionEntries. The stacktrace in https://github.com/endless-sky/endless-sky/issues/11378 shows that the provider object itself gets freed when the ConditionEntry gets destructed. …
=> fix(conditions): Replace manual memory management

source/TextArea.cpp
**Bug fix**
This PR addresses the bug described in https://github.com/endless-sky/endless-sky/pull/11362#issuecomment-2844354046.
The actual scrollability of the Dialog TextArea can change independently of the cached flag, throwing the dialog into an infinite readjusting loop, if we don't reset the flag properly.
Tested on the dialog provided by the OP (installing engines without enough engine space), and the snapshot creation dialog.
N/A I think
=> fix(ui): Fix dialog flickering

source/Dictionary.cpp, source/Dictionary.h, source/Outfit.cpp
**Bug fix**
This PR addresses the bug described in https://github.com/endless-sky/endless-sky/issues/11128#issuecomment-2706424798.
I think I've tested #10771, but maybe not, or something broke in the meantime, idk. Anyways, as the author of the linked comment mentioned, we need to remove the attribute entry from the dictionary completely instead of just zeroing it.
Before:
After:
Tested on the Hyperdrive, as shown on the screenshots above.
N/A
=> fix(ui): Fully clear the jump fuel attribute

CMakeLists.txt
**Bug fix**
This PR addresses the bug/feature described in issue #11393
Add a task in CMakeLists to symlink `build/<preset>/compile_commands.json` to `build/compile_commands.json`, making the configuration discoverable to (clangd) LSP so that it is able to provide correct diagnostics. 
I simply re-ran `cmake --preset linux` and verified that everything still compiled and that the LSP issue was resolved. This change has _zero_ impact on the actual game code, so it would be rather impressive if it managed to break the game in any way. I do not have access to Windows or MacOS machines to verify that the fix doesn't break compilation in that instance, but it shouldn't make a difference.
It arguably did change code, but not game code, just build system code, so performance should be identical.
=> Symlink compilation database to build for LSP discoverability

source/ConditionsStore.cpp, source/GameData.cpp, source/OutfitterPanel.cpp, source/PlayerInfo.cpp, source/System.cpp, source/image/ImageSet.cpp, source/image/SpriteSet.cpp, tests/unit/src/test_conditionsStore.cpp
**Refactor**
`std::string::compare` is a method that can be used for comparing part of all of a string to some other string.
In a lot of cases, we are using it to compare the beginning or end of a string to another string.
In C++20 (maybe also 17), there are two other member methods of `std::string` that do this and only this: `std::string::starts_with` and `std::string::ends_with`.
Making a call to one of these functions is a lot easier to read than a call to `std::string::compare` that does the same thing (see the diff for examples).
So, I've replaced all applicable calls to `std::string::compare` with calls to one of these newer methods, as appropriate.
N/A
N/A
Builds (and unit tests pass)/
N/A
N/A
N/A
Very small, but should not be worse.
=> refactor(strings): replace uses of std::string::compare with starts_with or ends_with

source/PlayerInfo.cpp, source/PlayerInfo.h
**Bug fix**
This PR addresses the bug described [on Discord](https://discord.com/channels/251118043411775489/536900466655887360/1369354602939420712).
The auto flagship unpark helper sets parked flags directly instead of using the PlayerInfo::ParkShip wrapper, so it needs to call UpdateCargoCapacities on its own.
yes™.
See the original report.
N/A
=> fix(mechanics): Update fleet cargo cache on auto unpark

CMakeLists.txt, docs/readme-developer.md
**Feature**/**Documentation**
CMake 3.31 added a native replacement for pkg-config, which makes requiring pkg-config unnecessary on certain systems. Also added the missing dependency to the build instructions (on brew I think it may not be needed, as it already provides CMake 4.0).
Additionally, fixed the minimal required CMake version in the docs.
Compiles locally, we'll see what CI says.
N/A
=> feat(build): Use external pkgconf only when needed

source/Engine.cpp
**Bug fix**
@TomGoodIdea reported on Discord that where you:
1. Pause the game (with the "p" key (by default), not by opening the main menu) while a looping sound (like engines) is playing;
2. Open a panel, like the map;
3. And then close that panel;
You hear the engine sounds again even though you haven't unpaused the game.
First, when you pause the game with "p", it pauses audio. This involves Audio::Step going through every source that's playing right now and marking it as AL_PAUSED, instead of AL_PLAYING.
After this, while the main panel is still on top, Engine::CalculateStep is still constantly telling Audio to play the engine sounds.
Audio::Step takes this to mean that the looping sounds are still active and keeps them in the list of active sources, but they remain paused.
When you …
=> Don't constantly refresh engine sounds while paused

source/MapDetailPanel.cpp, source/MapSalesPanel.cpp, source/MissionPanel.cpp
**Bug fix**
When opening the map and then switching to another mode, sounds become unpaused, even though you're still in the map.
The different map panels (ports, named "detail" internally, missions, shipyard, and outfitter) all extend a common base "MapPanel" class. (The shipyard and outfitter have an intermediate "MapSalesPanel" class).
When first opening the map from a non-map panel, all of these classes use the explicitly defined constructor of "MapPanel" in their own constructors. This constructor pauses sounds, which are then resumed in the destructor of "MapPanel", which all of its children must call when they are destructed.
However, when switching from one map mode to another, the new panel initialises itself by copying the previously open panel, via the implicitly defined copy …
=> Fix sounds resuming when switching map panel modes

data/human/human missions.txt
(The lines in parentheses (like this one) are instructions for filling out this template. These lines can be deleted.)
(The lines in double curly brackets ({{}}) should be replaced as it describes.)
(You can open a PR to add to or improve this template, if you find it lacking!)
(Choose one heading, or add your own.)
**Content  Missions**
**Bug fix**
**Typo fix**
This PR addresses a bug described on [Discord](https://discord.com/channels/251118043411775489/536900466655887360/1358197812038205530)
Made changes to the mission Timothy Radrickson 5: Oblivion Meeting so that Timothy Radrickson 5a: Timshank Redemption properly offers. This fix didn't seem to work: https://github.com/endless-sky/endless-sky/pull/11198
Also fixed a typo in the dialog. 
I tested it using the pilot file given to me …
=> fix(bug) Timothy Fix

source/Date.cpp, source/Date.h, source/PlayerInfo.cpp
**Refactor**
https://github.com/endless-sky/endless-sky/pull/11346#issuecomment-2818386591
I created the following mission and observed that the correct day would output 1 on each landing, and all other days would output 0.
```
mission "testing"
repeat
landing
on offer
conversation
`What day is it?`
`	Sunday: &[weekday: sunday]`
`	Monday: &[weekday: monday]`
`	Tuesday: &[weekday: tuesday]`
`	Wednesday: &[weekday: wednesday]`
`	Thursday: &[weekday: thursday]`
`	Friday: &[weekday: friday]`
`	Saturday: &[weekday: saturday]`
decline
```
https://github.com/endless-sky/endless-sky-wiki/pull/144
=> Replace the "weekday" number condition with a "weekday: <day>" true/false condition

shaders/line.frag, source/PlayerInfo.cpp
**Typo fix**
~~This PR addresses the bug/feature described in issue #{{insert number}}~~
Found via codespell
n/a
n/a/
n/a
n/a
(If any artwork was added or changed by this PR, the following must be provided.)
n/a
n/a
=> fix(typo): Fix a couple more typos

source/Engine.cpp, source/PlanetLabel.cpp, source/PlanetLabel.h
**Bug fix**
When a planet's display name or government is changed via a 0-day event, its engine label should be updated. This PR does it every frame (instead of just on entering the system, which obviously doesn't work with 0-days), but tries to avoid recalculating the overlap bounding boxes if the strings happen to be the same as before.
See #11406.
N/A
Tried to minimize it; seems N/A.
=> fix(ui): Update planet labels if the planet's data has changed

data/incipias/incipias ships.txt
**Content (I think?)**
This PR addresses ~~my OCD~~ the fact that the Venta's weapon hardpoints aren't defining which gun goes where, leading to an asymmetric layout.
Just defines where each gun goes on the Venta's gun hardpoints, making it so the 2 Plasma Dischargers are on the 2 isolated, further out hardpoints, whereas the 4 Star Tails are clustered together in 2 groups of 2, on the 2 sets of justapositioned hardpoints, as shown in the pics below.
Before:
After:
=> Specify Venta gun hardpoints to be symmetric

data/_ui/landing messages.txt, source/System.cpp
**Bug fix**
This PR addresses the bug described in issue #11412
This PR makes the textual change discussed in #11412 to state for a single planet why you cannot land on it, without specifying for other similar planets if you would be able to land on those other planets.
Fixes: #11412
Attempted to land on a gas giant in Kappa Centauri, and got the updated error-message.
See #11412 for a savefile that could be used.
N/A
None expected.
=> fix(ui): More specific reasons for being unable to land

data/_ui/landing messages.txt, source/System.cpp
**Feature**
This PR addresses stars and black holes from the bug described in issue #11412
- [X ] I acknowledge that I have read and understand the [Contributing](https://github.com/endless-sky/endless-sky/blob/master/docs/CONTRIBUTING.md) article.
Nobody is currently expected to land on stars and black holes.
Will be checked in CI, and those are the original messages from before #11427
N/A
N/A
None expected
=> fix(ui): Restore landing messages for stars and black holes

source/Engine.cpp
**Bug fix**
The starfield should not move when the engine is out of focus or paused.
Departed and started moving, then opened the player info panel.
N/A
=> fix(ui): Stop starfield movement when the engine is inactive

data/hai/hai jobs.txt
**Bug fix**
While doing jobs in Hai space, a `Superstitious Hai` job auto-failed at takeoff. Looking at the datafile, the job `"Superstitious Hai [3]"` and `"Superstitious Hai [9]"` were missing `distance 4 8`, which is found on the other `Superstitious Hai` jobs (1-12).
This PR adds that same `distance 4 8` to `destination` to the two jobs missing it so that the jobs don't auto-fail in some scenarios.
Did not test such a minor change, though I can if desired.
=> fix(content): Add missing "distance 4 8" to Hai job

data/human/pirate jobs.txt
This PR addresses the feature described in the pirate content discord channel, and is an implementation of #11331.
This PR makes 2 changes:
1. Implements red custom job colors for existing pirate jobs, using the pirate job example file Amazinite created in #11331.
2. Adds a "pirate jobs" condition similar to the "coalition jobs" counter to all pirate jobs to be used in future pirate content.
Screenshot above, and confirmed that "pirate jobs" increased after doing a pirate job.
Any save that can do pirate jobs.
=> feat(content): Red Colored Pirate Jobs & Pirate Job Counter

data/remnant/remnant outfits.txt, data/wanderer/wanderer outfits.txt
**Content (Outfit Descriptions)**
This PR seeks to continue the work of https://github.com/endless-sky/endless-sky/pull/10584 , by addressing the other Licenses mentioned there (the existing Remnant and Wanderer Licenses), providing them with new descriptions, instead of the current copied logbook entries.
This PR changes the descriptions of the following outfits:
- Remnant License
- Remnant Capital License
- Wanderer Outfits License
- Wanderer License
- Wanderer Military License
Like with the change to the Coalition License in https://github.com/endless-sky/endless-sky/pull/10584 , these new descriptions seek to provide lore tidbits about their respective factions. 
For the Remnant ones, I tried to focus on the "music" seen in various instances for the initial license, and on a more …
=> feat(content): New descriptions for Remnant and Wanderer Licenses

shaders/font.vert, source/text/Font.cpp, source/text/Font.h
**Feature**
This PR fixes #11364
Previously, every font size required a different shader, as the glyph sizes were baked into the VBO. I moved the glyph size into a parameter, so now we can reuse the same shader with multiple font sizes.
This also fixes a bug where the scale would not be properly reset between calls to the font shader.
I tested that the bug can no longer be reproduced.
We pass two more uniforms to the shader and do an extra multiplication, but that shouldn't be a problem.
=> feat(enhancement): Generalize font shader

data/_ui/tooltips.txt, source/Outfit.cpp, source/OutfitInfoDisplay.cpp, source/Ship.cpp
**Feature**
Adds two new attributes to the game:
* `"cloaked regen multiplier"`: A multiplier applied to your shield generation while your cloaking device is active.
* `"cloaked repair multiplier"`: A multiplier applied to your hull repair while your cloaking device is active.
As noted in #11343, the existing cloaked shield/hull delay attributes can't really be used for what they were originally intended for as a result of #9771.
See #11343.
Tested the cloaking device in #11343.
https://github.com/endless-sky/endless-sky-wiki/pull/146
=> Create attributes for multiplying shield generation/hull repair while cloaked

data/human/campaign events.txt, source/Mission.cpp, source/Mission.h, source/PlayerInfo.cpp
**Feature**
In https://github.com/endless-sky/endless-sky/pull/11388#discussion_r2082801463 I called out how, for some reason, the code that runs when you have a `priority` mission has a boolean that is true for every location except for the LANDING location. What this actually means in practice is that if any one `priority` mission is present, all `landing` missions are implicitly treated like priority missions. This even includes landing missions that are also marked as `minor`, since the code that runs to exclude `minor` missions when other missions are available is not run.
This has been the behavior of the `priority` tag ever since it was implemented (see https://github.com/endless-sky/endless-sky/commit/ccf4dc315a64515e25ff3f0df1d9ba06c12a8da6, and note that at the time the only …
=> Don't check the offer location when filtering non-priority missions

data/_ui/interfaces.txt, data/_ui/tooltips.txt, source/MenuPanel.cpp, source/MenuPanel.h, source/Preferences.cpp, source/PreferencesPanel.cpp
**Feature**
This PR adds a new preference that is on by default to animate the stars and haze in the background on the menu panels. The background follows a sine curve.
https://github.com/user-attachments/assets/609c2ae8-a011-45a4-ac91-e236d638d920
=> feat(ui): Animate the main menu background stars and haze

source/shader/StarField.cpp
**Bug fix**
Enable “fancy” parallax background and start moving down. Observe the lower edge of the screen. You will notice groups of stars suddenly jumping into existence there. This mostly affects the third parallax layer (foreground stars), the effect is far less noticeable with the second layer. The issue is the field bounds calculation failing to consider the `shove` value.
*Note*: I made `shove` an integer given that it is only used in integer operations. Calculating it as an integer would add only minimal complexity but still not worth it here.
With this change the effect is gone.
None
=> fix(mechanics): Correct field bounds calculation for fancy parallax

data/kahet/kahet missions.txt
**Typo fix**
Patir 2 mistakes spotted by Arachi, all from that mission that had a stopover and was then split into two
=> Patir 2 corrections

data/map beyond patir.txt
**Balance**
Based on Arachi's comments and my testing, the current black hole gravity in Patir 2 requires around 300 units of max speed in order to be reasonably completed. It also messes with the landing autopilot, making it difficult to land on the Chanai structure. The PR changes the systems to use the small black hole gravity instead of the standard one; not particularly accurate lore wise, but much less frustrating overall by reducting acceleration and the effect radius by a third. Chanai is still not out of the effect, but right at the edge, where even low thrust ships should be able to land without too much effort as long as they can get to that point. Another possibility would be to add an arrival distance, butI'd leave that maybe for after the unstable is out
Verified that it …
=> Lower Patir 2 gravities across the board

source/Engine.cpp
**Feature**
Even though motion blur and extended jump effects can be toggled separately, the motion blur added by extended jump effects won't apply unless motion blur is on. This PR decouples the two preferences, allowing for motion blur to apply only when jumping.
Tested every combination of motion blur and extended jump effects.
A single new variable.
=> feat(mechanics): Allow extended jump effects to function independent of motion blur

source/CMakeLists.txt, source/Camera.cpp, source/Camera.h, source/Engine.cpp, source/Engine.h
**Bug fix**
This PR addresses the bugs described in issues #11455 and #11457.
This PR fixes both bugs described in #11455. This is achieved by turning the camera into its own class.
The Camera class has a MoveTo function that is mostly the same as the NewCenter function from Engine. Instead of accepting a target position and velocity, this function now only accepts a target position. The target's velocity is then calculated by subtracting the target's previous position with its newest position to get the true amount of movement that the target made between frames. This is the second approach that I described in the issue:
> Or the camera velocity can ignore the flagship velocity all together, and instead use the difference in position between two frames to determine the velocity.
By …
=> fix(ui): Fix camera acceleration/starfield movement/motion blur breaking under certain circumstances

data/_ui/interfaces.txt, source/Engine.cpp, source/GameData.cpp, source/GameData.h, source/MenuPanel.cpp, source/MenuPanel.h, source/shader/StarField.cpp, source/shader/StarField.h
**UI**
This PR addresses #11444 and a few other starfield tweaks mentioned on Discord.
This PR makes the following changes:
* Removes the random starting point from the main menu animation.
* Tones down the animation speed, matching the values that @Anarchist2 provided in the linked issue.
* Makes it so that the menu animation doesn't impact the starfield position when you return to the game.
* Jumping between systems and traveling through wormholes now sets the starfield position to the camera's position, which matches the behavior of the starfield prior to #11345.
I played the game.
=> feat(ui): Adjust the starfield behavior and menu animation

data/_ui/tooltips.txt, source/Ship.cpp
This PR addresses the bug described in issue #11473 and other places.
This PR adds a warning if a ship's idle heat is zero or negative while its thrusting heat or turning heat is negative, as their engines may not be able to produce enough heat to power their engines.
Installed heat-consuming engines on a ship whose idle heat was negative and saw the warning. Took off and couldn't move as expected.
Zilch.
=> feat(ui): Warn the player if their ship is too cold to use their engines

CMakeLists.txt, credits.txt, endless-sky.6, resources/EndlessSky-Info.plist, source/main.cpp
Updates version numbers to "0.10.14-alpha", or "0.10.14" where that isn't an option.
=> 0.10.14 alpha version numbers

source/System.cpp
**Bug fix**
This PR addresses the bug described in issue #2369.
If an invalid system is encountered (one that is referenced but not defined), it creates an invisible system at 0, 0. We've made a few changes in the past to prevent players from entering this 0, 0 system, but as noted by Hurl's comment a couple years ago, there's still one case where players can enter this invalid system.
Now it could be possible that the relatively recent DistanceMap refactor unknowingly caught the case of routing to invalid systems, but I think it'd be safe to make this change as well. This PR makes it so that invalid systems cannot be hyperdrive or jump drive neighbors to any systems, therefore completely eliminating the possibility of the player jumping into an invalid system, as no other system in the …
=> fix(mechanics): Skip invalid systems when calculating system neighbors

data/human/free worlds 0 prologue.txt
This PR addresses an oversight brought up on Discord.
This PR adds a `<destination>` substitution to FW Bounty 1, removing any ambiguity if the mission is offered in a system with multiple landing locations.
=> fix(content): Specify the destination of FW Bounty 1

data/_ui/interfaces.txt, source/MapPanel.cpp
**Bug fix**
This PR addresses the bug described in issue #11483.
Updated the screen width at which the small map buttons interface kicks in to <1300 pixels instead of <1280 pixels.
This is the narrowest I can get my window without the small screen buttons kicking in. Note that there is no overlap between the shipyard button and the abort button, as can be see in the linked issue.
Any narrower and it swaps over to the small buttons interface.
=> fix(ui): Use the small screen map buttons sooner to avoid overlapping UI elements

source/MenuPanel.cpp
**Bug fix**
This PR addresses the bug described in issue #11493.
The reason for the bug is because the zoom of the starfield is updated by the StepBackground call, but StepBackground isn't called if the background animation is disabled. This PR makes it so that the StepBackground call is made even when the animation is disabled.
Maybe.
=> fix(ui): Allow the fixed starfield zoom preference to immediately update the menu background when the menu animation is disabled

source/Dialog.cpp, source/MissionPanel.cpp, source/MissionPanel.h, source/TextArea.cpp, source/TextArea.h
Reverted shrinking of TextAreas if the text is scrollable, because it seems that it creates more problems than it fixes (until we have an appropriate refactor).
Also standardized all panels that use them to set the area rectangle only once on initialization (opposite of what #11488 did, while still fixing the same bug).
Finally, dialogs no longer auto resize, because doing it every frame isn't an ideal solution, and with the above reverts, it's not needed for any bug fix anymore.
Same as in #10612, but the other way around.
Tested dialogs, mission descriptions, and planet descriptions in both the planet and map panels.
N/A to slightly better.
=> ui: Disable TextArea scrollshifting and optimize area resetting

source/WinApp.rc
Added some version metadata so that Windows doesn't show version 0.0.0.0
Compiled locally with mingw, and made sure the metadata shows up in the main exe's properties.
N/A
=> feat: Add version metadata for Windows

data/map planets.txt
**Typo fix**
Reported by Zugidor on discord. Thanks!
Fixes a typo in Avalet's description - "gas plant" to "gas planet".
=> fix(typo): Avalet description typo

docs/CONTRIBUTING.md
This PR addresses #9413.
Adds a new "Acceptable license" section to the contributing file, documenting what copyright licenses are allowed to be used for contributed assets.
=> docs: Add an "Acceptable licenses" section to the contributing file

source/MapPanel.cpp, source/MenuPanel.cpp, source/PlayerInfo.cpp, source/PlayerInfo.h, source/PreferencesPanel.cpp, source/PreferencesPanel.h
**Bug fix**
This PR addresses the bug described in issue #11351
As noted in the linked issue, a DistanceMap calculation was being made every frame when the "Deadline blink by distance" preference was set to true and you were looking at the map, or the minimap when jumping had a deadline mission nearby. When using a plugin jump drive with a large jump range, this calculation becomes extremely expensive.
This PR changes it so that this calculation is cached whenever a new deadline mission is accepted, and it is recalculated for all current deadline missions whenever...
1. the day changes,
2. the map is opened while you're landed on a planet (since you could have changed your flagship's jump capabilities),
3. whenever the preference is changed in the preferences panel, or
4. a zero-day event …
=> fix(ui): Cache the days remaining for completing deadline missions

data/successors/successor 1 prologue.txt
**Typo fix**
This PR addresses a bug described [on Discord](https://discord.com/channels/251118043411775489/536900466655887360/1381595315395629130).
Changed is->are to match the plural form "thy words"
N/A
I don't have a save for this... and honestly it probably doesn't need one?
=> Fix(typo): Agree with plural "words" in Successors: Trusted

source/PlanetPanel.cpp
**Typo fix**
This time around things should actually work...
This PR addresses a bug/feature that I noticed on a Discord screenshot.
Removed the word "be" from `Some of your ships in other systems are not be able to fly`
N/A
Loot vital outfits off a ship and test if you get this message properly, I guess.
=> Fix(typo): Reword no-fly warning for ships in another system

data/governments.txt
**Bug fix**
This PR addresses the bug described on Discord.
The first contact missions (both the original one and the patch) let the player learn the "Incipias" language. The problem is that the goverments actually use a language called "Incups" that isn't referred to anywhere else.
So I've renamed "Incups" to "Incipias".
None.
=> fix(content): Rename the Incups language

source/Mission.cpp, source/PlayerInfo.cpp, source/PlayerInfo.h
**Bug fix**
This PR addresses the bug described [on Discord](https://discord.com/channels/251118043411775489/536900466655887360/1383485791791087777).
When a job is accepted, it should be added immediately to the player's deadline cache. It seems the function that was supposed to do it, isn't called for jobs, so I moved it to another place.
Please don't tell me to move the function in PlayerInfo.cpp, it's already a mess there. I'll do it separately.
yes™.
N/A
=> fix(ui): Properly cache job deadlines on accept

source/BoardingPanel.cpp
**Refactor**
Exactly what the title says. The rounding function in BoardingPanel.cpp predates Format::Decimal, but I replaced it for simplicity and consistency.
No.
N/A
=> refactor: Replace a custom formatting function with Format::Decimal

.github/workflows/cd_release.yaml
Apparently, uploading and then downloading artifacts in GitHub Actions jobs with actions/upload-artifact and actions/download-artifact doesn't preserve the executable bits.
We recently started doing this as part of our MacOS release CD workflow in order to parallelise the compilation of the x64 and arm binaries.
This results in the final dmg containing executables without the executable flags set, so MacOS won't run it.
This PR fixes this by zipping the things we are uploading via actions/upload-artifact and then downloading via actions/download-artifact. This means that these Actions never see the individual executable files, and so cannot mess up the executable bits.
N/A
N/A
Ran the Release CD. Checked the files inside the resulting dmg and the executable and libraries …
=> Fix MacOS Release CD

source/LogbookPanel.cpp
**Bug fix**
This PR addresses the bug reported on [discord](https://discord.com/channels/251118043411775489/536900466655887360/1383476645234479244)
Removes the sound.
=> fix(ui): Don't play sound when scrolling in the logbook

source/PlayerInfo.cpp, source/PlayerInfo.h
- Moved `CalculateRemainingDeadline` in both the header and cpp to the rest of deadline cache functions.
- Moved an enum above functions (as per the style guide).
- Moved around functions in cpp to match the order in the header.
- Moved a function into the class as a private member since it already used PlayerInfo.
No.
N/A
=> fix(style): PlayerInfo cleanup

source/text/Font.cpp, source/text/Font.h
**Bug fix**
This PR addresses the bug/feature described in issue #11286
Redo of #11308
Replaces #11484 
Reimplements the three `Font::TruncateSomewhere` functions using a binary search approach. Prevents issues with border cases.
(See discussions in previous issues/PRs).
<details>
Input in the snapshot name dialog:
```
3017-04-29ajksololdJOIDJoasidjoAIJSDOIajdpoiAJDPOIJaosdijAPOIDJOaijdoAIJDOaijsdopiAJDPOiajdoijASODIJaopisdjAPOIJSDPOaijsdpoAIJSDPOiajsdopiAJDSMMMMMMMMMMMMMMMMMMMM........................
```
Using `zoom 150` on a 2560x1440 display on Mint 22.1 cinnamon.
Before (lazy, running a compile from end of April):
After:
Video from #11484 showcasing that dialog hacked to `Truncate::MIDDLE`:
https://github.com/user-attachments/assets/73875762-18f9-4d04-86c8-63ddf27ed1fb
</details>
- …
=> fix(ui): New, robust truncation functions used in DisplayText

data/_ui/interfaces.txt
**Feature**
This PR addresses the bug/feature described in issue #11557
This PR makes it possible to close the message log panel by clicking the darkened background region, similar to how the logbook works.
This is done by adding a button element to the "message log" interface that sends the "d" key, which closes the panel.
The region spanned by this button is similar to the region that closes the logbook panel.
There is also a "dummy" button that sends the "A" key (which is unused by the logbook panel) creating an exclusion zone around the filter toggle click zone.
Red highlight is the region that closes the panel.
Yellow(?) is the "dummy" region.
Blue-white is the filter toggle zone.
(The colours are not present in this PR.)
N/A
Click
N/A
N/A
N/A(?)
Minimal
=> Close message log by clicking empty space

data/kahet/kahet missions.txt
Line below "to accept" had 3 tabs, but should only have 2 tabs.
**Typo fix**
This PR addresses the bug/feature described in discussion #11565
Deleted one <tab> character at the start of line 1573.
only build-test. I haven't reached that particular mission yet.
=> Correct 'Patir Mystery 12.2A' indentation under 'to accept'.

source/shader/StarField.cpp
**Bug fix**
The parallax layers currently draw the same stars at slightly different zoom levels. If you look closely, this actually shows – you have the same constellations moving in the foreground and background. This is unnecessary given that the number of stars displayed is divided by the number of layers anyway.
This change makes sure that the starting offset for each layer is different, so there are no overlaps between the stars drawn in each parallax layer. It also moves multiplication with the vertex count towards the end, so that the vertex count passed to `glDrawArrays` is guaranteed to be a multiple of 6. I think this code has been drawing partial stars before, and my screenshot actually shows something that seems to be one half of a star.
Duplicate constellations currently …
=> Don’t draw the same stars in different parallax layers

data/remnant/remnant 2 cognizance.txt
**Bug fix**
This PR addresses the bug/feature described in issue #7442
The mission "Remnant: Cognizance 18" involves the player travelling from Viminal in the Arculus system to the Nenia system with some escorts and then returning to Aventine in the Pantica system.
The mission contains an "on enter" dialog for the Pantica system. This dialog is intended to appear after you have visisted the Nenia system during this mission, but there is no such limit placed on the "on enter" dialog; it will appear the first time you enter the Pantica system with this mission active.
This PR moves this "on enter" dialog to a new mission, which is offered when entering the Nenia system with the mission "Remnant: Cognizance 18" mission active. This new mission is invisible and has no other content. This …
=> Fix inappropriate dialog appearance in Cognizance 18

data/map planets.txt, data/wanderer/wanderers middle.txt
This PR addresses the feature described in issue #1722.
Closes #1722.
Changes all the automata planets to only have "offers missions" as a service, removing crew, bank, job, and trading services. This makes the automata planets effectively behave as uninhabited planets when you land on them.
I've also gone ahead and added `mereti` and `sestor` attributes to the respective automata planets, since they lacked such attributes.
Well I sure hope it works.
=> feat(content): Remove crew, bank, job, and trading services from automata planets

source/PlayerInfo.cpp
**Feature**
This PR addresses the bug described in issue #11387.
Closes #11387.
Right now, we have "cargo space" and "passenger space" conditions that change their behavior depending on the context. If they're used in most cases, then they return the total cargo and passenger space of your local fleet. But if you're used during a boarding mission, they return the free cargo and passenger space of your flagship. As noted in #11387, this contextual behavior isn't working as was likely intended.
This PR creates multiple conditions for each case that a mission might want to check.
* `"cargo space"`: The total cargo space of your local fleet.
* `"cargo space free"`: The free cargo space of your local fleet.
* `"flagship: cargo space"`: The total cargo space of your flagship.
* `"flagship: …
=> feat(condition): Add separate conditions for fleet/flagship cargo/passenger space total and free

data/wanderer/wanderers start.txt
Closes #7964.
Adds `"offer precedence" 100` to "Wanderers: Alpha Surveillance H". This causes the mission where you wake up after getting knocked out be the first mission to offer, assuming there are any other missions that are able to offer at the same time.
I decided to do this instead of using `priority` because it allows other missions to offer, while `priority` would block other missions from offering.
Yes.
Let me know if you ~don't trust me~ need one.
=> feat(content): Make "Wanderers: Alpha Surveillance H" offer first before any other eligible missions can offer

source/Projectile.cpp
**Bug fix**
This PR addresses the bug described in issue #5479.
Closes #5479.
When die effects are placed, they currently don't account for the velocity of the parent projectile, hence the behavior seen in the linked issue. This PR changes die effects to have 1.5x the velocity of the parent projectile added to the effect's spawn position. This causes the die effect to appear where the projectile would be next frame had it still been alive.
I'll note that I first tried using an offset of 0.5x, and that did cause the die effect to appear on top of where the projectile was the frame that it died, but that only occurred while my flagship was stationary. As soon as I started moving my flagship, the die effect's origin started to move away from where the projectile was on its last frame. By …
=> fix(mechanics): Properly place die effects spawned by projectiles

data/_ui/tooltips.txt, source/OutfitInfoDisplay.cpp
**UI**
This PR addresses the feature described in issue #3771 w.r.t displaying velocity, plus the an observation made on Discord at least once w.r.t. prospecting not being visible.
Closes #3771.
Adds the following two weapon attributes to the outfitter info display:
* `velocity`: The initial velocity of the projectile, or the velocity override if one is provided. For weapons whose velocity equals their range (i.e. lasers), the display reads "instantaneous".
* `mining precision`: Instead of displaying the prospecting "damage" per shot or DPS, this value is the prospecting per shot divided by the minable damage per shot of a weapon. The reason for displaying this instead of the raw prospecting value is because the manner in which prospecting interacts with minables means that this ratio …
=> feat(ui): Display a weapon's velocity and prospecting efficiency in the outfitter

.github/workflows/cd_release.yaml
It seems the `.` character in the cpack parameter name breaks the workflow if not enclosed in quotes.
=> Fix Windows release CD

data/map planets.txt, data/map systems.txt
This PR makes gas giants landable in the Graveyard: Antamesa, Baliesa, Faliete, Meligara and Pathera. This makes it somewhat more dense than most of the galaxy in that, but the same can be said about the Ember Wastes and they are planned to be used by the Remnant in a number of missions - especially the north, which is why I tried to put three there. The only change to the systems themselves was swapping the sprite of the gas giant in Delia, as it was yet another blue gas giant (like the other 4) and I wanted some more variety. No major lore implications, but they elaborate a bit on other plot points relevant to the area they are in. Huge thanks to reticent-rem for writing three of these descriptions!
Note: some of the landscapes used are from …
=> Graveyard gas giants

data/_ui/tooltips.txt, source/Engine.cpp, source/Engine.h, source/MapPanel.cpp, source/MapPanel.h, source/Preferences.cpp, source/Preferences.h, source/PreferencesPanel.cpp
**UI**
This PR addresses the feature described by https://github.com/endless-sky/endless-sky/issues/10949#issuecomment-2944677259.
Updates the "Show mini-map" from a boolean setting to instead have three options: "off", "when jumping" (which is the current "on" behavior) and "always on".
I've also slightly changed the behavior of the "when jumping" option. Currently, if you send a jump command to your flagship and then immediately cancel it, the minimap will fade in slightly and the start fading out when the command is cancelled. Now, the minimap will remain visible for 3 seconds after the jump command is canceled.
When the mini-map display is set to always on, then it will display the next jump in your travel plan.
If you have no travel plan, it will only display the current system. …
=> feat(ui): Added a "Show mini-map" preference option for having the system mini-map always on

source/AI.cpp, source/AI.h
**Bug fix**
As @Amazinite noticed in https://github.com/endless-sky/endless-sky/pull/11591#issuecomment-3029947619, the stop command message gets posted every frame you hold the key. It's obvious with the message animations, but it's just an unrelated problem that got highlighted with that changes.
Also renamed the param in the header to match cpp.
Departed from a planet to have a few messages in the list. Noticed that with this PR the list doesn't get cleared completely.
N/A
=> fix(ui): Don't spam the "Coming to a stop" message

source/Files.cpp
**Bug fix**
This PR addresses the bug described in issue #11613 (resolves #11613).
With the iostream refactor it was changed so that files use the binary mode when writing, which doesn't convert `\n`s to `\r\n`s on Windows. As our data, including save files, is just plain text, and we don't write into zip files it's safe to use the text mode for writing.
Related: https://github.com/endless-sky/endless-sky/commit/5659a072a4f26aee15ee0a275387918c6165c1b3
yes™.
N/A
=> fix: Use the text mode for writing save files on Windows

source/AI.cpp, source/Account.cpp, source/ItemInfoDisplay.cpp, source/Mission.cpp, source/PlayerInfo.cpp, source/text/Format.h
**Refactor**
This PR addresses the problem that has always bothered me.
Added a templated (so it works in various cases) function to Format, responsible for adding `,`, `and`, and `, and` when listing items from the given container.
It's currently used in the four places that I managed to grep out, but if you know of any other code that could benefit from it, post your comments below. I didn't replace the ships listing code in the sale dialog as it puts everything on separate lines, and is more complicated in general.
N/A
=> refactor: Move common code for listing items to Format

data/wanderer/wanderer ships.txt, data/wanderer/wanderers middle.txt, data/wanderer/wanderers start.txt, data/wanderer/wanderers.txt
Adds the Wanderer Heavy Gust to fleets and shipyards, appearing after the Autumn Leaf but before the Tempest. While it's visible before the Tempest enters production, it can't be purchased until the player gains the military license.
Also adds Heavy Gusts in some fleets added later (including adding a moonbeam variant that appears when the moonbeam becomes available), and to some mission fleets.
I was originally planning to have more mention of it, but there really isn't much space at all between those two events, since the Tempest appears almost immediately after the Unfettered attack, and that's the first event after the Autumn Leaf's release.
none
Will be available on any save that's completed Wanderers, I don't currently have one at the relevant …
=> feat(content): Make the Heavy Gust available

source/Body.cpp, source/Body.h, source/Engine.cpp
**Feature**
This PR addresses the feature described on Discord.
You can now make a visible hardpoint swizzle accordingly to the ship (see the syntax below). It can be especially useful for larger sprites that would look weird with a static color.
```html
outfit <name>
weapon
"hardpoint sprite" <name>
"inherits parent swizzle"
```
yes.™
https://github.com/endless-sky/endless-sky-wiki/pull/160
I'm not really sure about the additional bool. A possible alternative would be to set the swizzle to null instead, but that could be easily overlooked in future code and lead to problems.
=> feat(enhancement): Allow weapon hardpoints to be swizzled with the ship

data/human/outfits.txt
**Bug fix**
Thanks to @MidnightPlugins for reporting this on Discord.
Endless Sky looks for the attribute "map minables" on map outfits to determine if they should reveal minables in the region they map.
The Local Map has the "map minable" attribute, which is ignored.
This PR corrects the attribute name.
Not today.
N/A
I will not.
Just start a new game. It's right htere.
N/A
N/A
N/A
=> Fix local map minable mapping

data/hai/hai ships.txt
Adds "variant map name"s to the variants of the Shield Beetle, Lightning Bug, and Aphid sold by the Unfettered Hai.
Previously, the shipyard map would have two apparently identical entries for each of these ships, which led to confusion for players.
This PR means the variants sold on Unfettered worlds will have the subheading "Unfettered Shipyards" to differentiate them from the base models.
before | after
-- | --
N/A
Looked in the map shipyard.
[test hai.txt](https://github.com/user-attachments/files/21069113/test.hai.txt)
N/A
N/A
N/A
=> Variant map names for unfettered outfitted ships

data/_ui/interfaces.txt
**Bug fix**
This PR addresses the bug/feature described in issue #11660
The planet description content box is taller than it should be. I think the odd height contributes to the blurriness described in the linked issue.
This PR fixes the height.
No
N/A
@Anarchist2 said "i think that fixed it".
N/A
N/A
N/A
N/A
=> Fix blurry text on the planet description

data/human/free worlds 2 middle.txt
This PR addresses the bug described by Dagoth on Discord.
"Pirates Use Cutthroat" changes a fleet named "Large Southern Pirate", but the actual fleet is named "Large Southern Pirates". This PR fixes the typo and renames the mission to let it trigger on saves that already have the broken version of the event.
None.
=> fix(content): Fix bug where Cutthroats wouldn't spawn

tests/unit/src/test_point.cpp
**Bug fix**
This PR addresses the bug described in issue #11623 in part.
Use `std::abs(double)` from cmath instead of the default abs on arm64, which used to return int and fail test_point
https://launchpadlibrarian.net/806416697/buildlog_ubuntu-questing-arm64.endless-sky_0.10.14-1_BUILDING.txt.gz
Before applying the fix:
```
1/1 Test #89: unit .............................***Failed    0.19 sec
Randomness seeded to: 202319588
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
endless-sky-tests is a Catch2 v3.7.1 host application.
Run with -? for options
-------------------------------------------------------------------------------
Scenario: Calculating absolute value
Given: any Point
When: Calculating abs
Then: The result is correct …
```
=> fix(code): Fix test_point failing abs test on ARM64

source/HailPanel.cpp
**Bug fix**
This PR addresses the bug I discovered while working on something else.
In #11596, I forgot that the hail panel renders the ship independently of the engine.
None.
N/A
N/A
=> fix: Choose correct hardpoint swizzle in the hail panel

.github/workflows/ci.yml
A little while ago, we expanded the "test parse" CI job to also check images and sounds for some things. But, the CI jobs won't run if only stuff in the images or sounds folders was changed.
This PR updates the path filter on the CI workflow so that it will run on changes in those folders.
N/A
N/A
None.
N/A
N/A
N/A
N/A
=> Run CI on changes to images or sounds only

source/GameData.cpp, source/Person.cpp, source/Person.h, source/UniverseObjects.cpp
**Bug fix**
When you load a save that has some undefined (for example from removed plugins) persons marked as destroyed, they will get added to the persons GameData set, just like any other new data. However, currently the set isn't hard-reset to the default state, but instead the individual persons get restored. This means all undefined persons are added to the set never to be removed (until you relaunch the whole game). If you then load another pilot and save it, the persons will get added there too, since they are still in the set without any ships assigned, which makes IsDestroyed return true.
This PR changes the Restore loop to a full reset of the data, removing the persons that aren't in the default set and automatically resetting the rest to their default state. Additionally, the …
=> fix: Reset the Person database when reloading saves

.github/workflows/cd.yaml, .github/workflows/cd_release.yaml, .github/workflows/ci.yml, .github/workflows/compute-changes.yml, .github/workflows/projects_check.yml
Bumps [`actions/checkout`](https://github.com/actions/checkout) from v4 to v5.
=> chore(ci): bump actions/checkout from v4 to v5

data/korath/korath weapons.txt
Gives the Firestorm a velocity override of 5 (the velocity it actually achieves based on its drag and acceleration), so that the game can use that when calculating its range rahter than the launch velocity of 6.6
none
=> feat(content): Add a velocity override to the Firestorm to stop the game overestimating its range

source/Angle.cpp, source/Animate.h, source/CMakeLists.txt, source/ExclusiveItem.h, source/GameWindow.h, source/RenderBuffer.h, source/ScrollVar.h, source/WeightedList.h, source/comparators/ByDisplayName.h, source/comparators/ByGivenOrder.h
**Style**
1. Fixed [`Type& name`](https://github.com/endless-sky/endless-sky/wiki/C++-Style-Guide#pointers-and-references) occurrences.
2. Fixed [opening bracket placement](https://github.com/endless-sky/endless-sky/wiki/C++-Style-Guide#opening-braces).
3. Fixed [variable names](https://github.com/endless-sky/endless-sky/wiki/C++-Style-Guide#lower-case-camelcase) that weren't formatted in camelCase.
4. Removed parentheses from [return values](https://github.com/endless-sky/endless-sky/wiki/C++-Style-Guide#return-is-not-a-function).
5. Split the ByName.h file into two as it contained two [separate classes](https://github.com/endless-sky/endless-sky/wiki/C++-Style-Guide#one-class-per-file).
=> style(code): Various style fixes

source/CMakeLists.txt, source/EsUuid.cpp, source/EsUuid.h, source/PlayerInfo.cpp, source/Ship.cpp, source/comparators/ByUUID.h, source/comparators/UUIDComparator.h, tests/unit/src/test_esuuid.cpp
**Refactor**
1. Replaced `#if defined(WIN32)` with `#ifdef _WIN32`.
2. Fixed the [order of `#include`s](https://github.com/endless-sky/endless-sky/wiki/C++-Style-Guide#order-of-includes-in-a-h-file).
3. Dropped the custom `es_uuid::detail::` [namespace](https://github.com/endless-sky/endless-sky/wiki/C++-Style-Guide#namespaces). One function from it is needed outside (in the test), so made it a public static member of `EsUuid`.
4. Fixed a capitalization error in a [function name](https://github.com/endless-sky/endless-sky/wiki/C++-Style-Guide#function-names).
5. Moved the portions of platform-specific code with the same functionality together.
6. Added a proper [`using namespace std` declaration](https://github.com/endless-sky/endless-sky/wiki/C++-Style-Guide#the-std-namespace) to the …
=> style(code): EsUuid cleanup and style fixes

data/_ui/interfaces.txt, source/MapPanel.cpp, source/MapPanel.h
**Feature**
Re-PRed (kind of) #10163.
Changing zoom on the map now has an animation implemented with the Animate class. The duration can be customized in the interface (defaults to 10 frames).
yes™.
N/A
=> feat(ui): Smooth map zoom animation

source/Engine.cpp, source/Messages.cpp, source/Messages.h
**Bug fix**
This PR addresses the bug described in issue #11640 (closes #11640).
Adds a new special message importance level that uses the "highest" color, but "low" deduplication strategy, which means new messages will be added to the list only if there are no entries with the same text already.
Also noticed that removing old and invisible entries _after_ a new message appears, although doesn't make any difference for most importance levels, makes the "low"-deduplicated messages appear less frequently than they should: a new message isn't added because there already exists an invisible entry with the same text, and that entry doesn't get checked for removal, because the new message doesn't end up being added.
yes™.
None.
=> fix(ui): Clear old messages every frame, and fix ship overheat message spam

CMakeLists.txt, docs/readme-developer.md, source/CMakeLists.txt, source/audio/Music.cpp, source/audio/Music.h, source/audio/supplier/AsyncAudioSupplier.cpp, source/audio/supplier/AsyncAudioSupplier.h, source/audio/supplier/FlacSupplier.cpp, source/audio/supplier/FlacSupplier.h, source/audio/supplier/Mp3Supplier.cpp, source/audio/supplier/Mp3Supplier.h, vcpkg.json
**Feature**
This PR adds the often-requested FLAC support to music, so either mp3 of flac files can be used.
**This PR is based on and includes changes from #11065. It will be rebased with changes made there.**
As we don't want to cache music in memory, flac also uses a threaded decoder, like mp3. The common functionality was lifted out to a superclass so the thread management code isn't duplicated between flac and mp3.
The flac files are decoded via libflac.
Flac music?
I tested both looping and non-looping playback with mp3 and flac, both works fine.
Some short test files: [ambient.zip](https://github.com/user-attachments/files/21321586/ambient.zip)
Shouldn't be much.
=> feat(audio): Add FLAC support for music playback

data/human/human missions.txt
**Bug fix**
This PR addresses a bug described on [Discord](https://discord.com/channels/251118043411775489/536900466655887360/1417209523315281982)
Fixed a bug in the Lost Racer mission chain where LR3 wouldn't offer.
Added an `on visit` node to LR2C so that people with JD who skipped Acamar would know what was going on.
No.
=> fix(bug): Lost Racer bug fix

data/map beyond patir.txt, data/remnant/remnant jobs.txt
**Bug fix**
This PR addresses the bug/feature described in the Discord server
As in https://github.com/endless-sky/endless-sky/issues/7702, https://github.com/endless-sky/endless-sky/issues/8543, and https://github.com/endless-sky/endless-sky/pull/10960, the Research Expedition has a new unintended location - the Patir 2 cluster, currently unreachable by the player after the mission chain in question. This fixes it by adding a set of attributes to the relevant systems and excluding it from the location filter.
None.
=> Fix Remnant Research Expedition jobs again

source/orders/OrderSet.cpp
**Bug fix**
Although there's one "hold position" order type the player can issue, AI internally uses another, "hold active", to differentiate between ships moving to the target position, and those that actually are stopped.
Unsetting orders (via pressing the same key a second time) relies on the ships having the same order type that is being unset. So, the type needs to be set to "hold position" when reading player input, and to "hold active" when needed by the AI. While switching between "hold position" and "hold active" is implemented for some cases in OrderSet::Update, the unification of these orders for player input purposes is still required (but was mistakenly removed in #10843).
Perhaps solving this by removing "hold active" completely would be cleaner, but it would require a …
=> fix(mechanics): Make it possible to clear "hold position" orders by pressing the key again

source/AI.cpp, source/Ship.cpp, source/Ship.h
**Refactor**
This PR addresses the bug described in issue #7577, #6667 and #6604. (closes #7577, closes #6667, closes #6604)
In most cases, this PR makes forward and reverse thrusters work the same way, without special handling. It also makes use of the True... values to better account for crew or slowing-related effects for navigation.
In most cases, reverse thruster support can be achieved by simply decomposing the "what to do" problem into two independent sub-problems: "is forward or reverse better in the long run", and "is forward or reverse useful right now". We adjust the facing angle based on the preferred long-term thruster, and set the current thrust based on the current facing. If a ship has both forward and reverse thrusters, this usually makes it behave even nicer than before; …
=> refactor: Make reverse thrust work properly

utils/check_code_style.py
This change to the `check_code_style.py` script to add a check for an ampersand followed by a space preceding a left square bracket by adding the following two lines to the existing checks:
```
r"\s&\s+\[": "structured bindings should not contain a space after the ampersand: &[first, second]",
```
Addresses: https://github.com/endless-sky/endless-sky/pull/11736#issuecomment-3315376155
=> code checker catch bad structured bindings

source/MapPanel.cpp
**Bug fix**
This PR addresses the bug/feature described [on Discord](https://discord.com/channels/251118043411775489/536900466655887360/1420789874721685574)
Previously, when zooming the map by scrolling, it would zoom centred around the mouse pointer. That is, the point in the map below the mouse pointer would remain the same before and after the  change in zoom level.
The addition of smooth zooming breaks this because the actual zoom value is no longer changed immediately, so the code that recentred the map to keep the map from moving under the mouse pointer doesn't work since it expects to be able to do it instantly. As a result, the map always zooms around the centre of the screen.
This PR fixes this by continuously recentring the map every step while the zoom animation is occurring. …
=> Fix the map not recentring about the mouse pointer when zooming by scrolling

source/Ship.cpp
**Bug fix**
Some calls to DoRepair on carried ships have heat and fuel mixed up (which this PR fixes). As you can see, the signature matches
https://github.com/endless-sky/endless-sky/blob/ea826d4427277f0625bca012abb89325b7d86daa/source/Ship.cpp#L111-L112
so the compiler has no problems when the values are in a wrong order where the function is used.
None.
N/A
=> fix(mechanics): Correctly apply fighter repair heat and fuel

source/Messages.cpp, source/Messages.h, source/Ship.cpp
**Feature**
This PR addresses the behavior reported [on Discord](https://discord.com/channels/251118043411775489/536900466655887360/1421837228182605835).
Currently if you have multiple ships with the same name, and they get destroyed in a short time, the duplicate messages get removed. This PR adds a new importance level that allows duplicates in both the main list and the log, and uses it for these messages.
See the above screenshots.
N/A
=> ui: Add a message category that allows duplicates

source/MenuPanel.cpp, source/PlayerInfo.cpp
**Bug fix**
This PR addresses the bug described in issue #11150 (closes #11150).
Moved the code responsible for playing planet music to a single place. It's now independent of opening the menu panel, and only started when landing or loading a save.
yes™.
N/A
=> fix(sound): Fix planet ambient music playback

source/Hardpoint.cpp
**Bug fix**
This PR addresses the bug reported [on Discord](https://discord.com/channels/251118043411775489/536900466655887360/1420819056671588494).
Currently, all weapons check the blindspot as part of the function that tells if the weapon is ready to fire. While it works well for normal weapons, special systems that can rotate instantly (anti-missile systems and tractor beams) are ready even if currently facing a blindspot, as they can still reaim before firing.
This PR changes it so that those systems now check the blindspots directly before firing.
yes™.
N/A
=> fix(mechanics): Correctly check blindspots on special weapons

CMakeLists.txt, source/audio/supplier/AudioSupplier.h, tests/unit/src/test_weightedList.cpp
**Build fix**
This PR addresses the bug/feature described in issue #11760
Adjusts flac on linux targets to pull in flac via pkg-config instead of relying on a potentially non-existent `flac-config.cmake`. 
Adds a missing header that defines size_t in `AudioSupplier.h`
Conditionally skips a test that relies on catch2 v3, which is not available on debian stable. 
Compiled, flew around. 
None
=> Fixes needed to get this to compile on my debian box

data/coalition/coalition missions.txt
**Bug fix**
This PR addresses the bug described in [this Steam post](https://steamcommunity.com/app/404410/discussions/1/591783706467849836/) by user hellminister.
- [ x ] I acknowledge that I have read and understand the [Contributing](https://github.com/endless-sky/endless-sky/blob/master/docs/CONTRIBUTING.md) article.
Just adds a line to prevent the mission from offering on a gas giant (Uninhabited).
=> (bugfix) Prevent Coalition Yottrite missions from offering on Gas Giants

source/MenuAnimationPanel.cpp
**Refactor**, I guess
When testing the game on low(est)-end hardware, I noticed that the animation happening after all data is loaded is relatively heavy, considering its visual simplicity.
This PR makes use of the Bind/Add/Unbind functions available in PointerShader instead of binding and unbinding with each Draw call.
The game still works and the animation looks like before.
Unnoticeable on most devices.
=> refactor(ui): Optimize the startup animation

source/Ship.cpp
**Bug fix**
This PR addresses the bug reported [on Discord](https://discord.com/channels/251118043411775489/536900466655887360/1424725869804392478).
Changed the importance of the "You cannot board a ship while cloaked." message to prevent it from being posted every frame.
yes™.
=> fix(ui): Don't spam the cloaked boarding message

data/hai/hai missions.txt
**Bug fix**
This PR addresses a bug described on [Discord](https://discord.com/channels/251118043411775489/536900466655887360/1424447969457078394)
Added `to display` nodes to each option in Acorn Delights: Part 1 so that it is not possible to repeatedly pick the same option.
=> Acorn Delights: fix repeatable options

source/Command.cpp
The downstream fork endless-mobile uses the command name to link to interface buttons. Normally I wouldn't bother with an upstream merge as I can just add the label in endless-mobile, but this particular command keeps being a source of merge conflicts.
I just added a label to Command::STOP.
Verified that that the stop command still works as expected.
N/A
=> Add label to STOP command

data/_ui/tooltips.txt, source/CMakeLists.txt, source/GameWindow.cpp, source/GameWindow.h, source/Preferences.cpp, source/Preferences.h, source/PreferencesPanel.cpp, source/main.cpp, source/windows/WinVersion.cpp, source/windows/WinVersion.h
**Feature**
Instead of hardcoding the title bar theme to dark, there's now a preference allowing to choose between the default option (read from the registry) and force-enabling dark or light.
As window corner rounding on Windows 11 is controlled in the same way (must be done by programs themselves, and there's no documented global setting), it now also has an in-game preference controlling it.
Preferences on Windows XP:
on Windows 11:
On systems other than Windows, they are ifdefed out, so they don't appear at all.
Tested both settings on Windows 11.
N/A
=> feat(ui): Use Windows DWM attributes preferred by the player

data/wanderer/wanderers start.txt
This PR addresses the bug/feature described in issue #9182
This PR adds markers to the systems that you fly through in Wanderers: Alpha Surveillance D, addressing some of the concerns that it's too difficult to figure out where you're supposed to go while you're being shot at.
Did the mission.
[combat testless~autosave.txt](https://github.com/user-attachments/files/20537725/combat.testless.autosave.txt)
=> feat(content): Add markers to systems in Wanderers: Alpha Surveillance D
